### ISSUE TITLE
Issue #1000, Yay! Should we add a issue template to celebrate the occasion?

### ISSUE THREAD

**Issue by ecdye** [openhab/openhabian#1000]
Title says it all, thoughts?

**Comment by mstormi** [comment]
🥳 🎉 
what sort of template?

BTW, less than 20 left to go ! It was ~130 when we started.

**Comment by ThomDietrich** [comment]
🎉 
way to go guys!!

**Comment by ecdye** [comment]
One that gives an outline of the information we need to help the user, For example:

Did you check to see if the issue has already been reported to the community or here?

What is the issue:

Please provide the debug info as described in `openhabian-DEBUG.md`

something like that.

**Comment by mstormi** [comment]
yes please. Maybe copy that section from openhabian-DEBUG, maybe rework it a little while we're on it ?

BTW I wrote that alone (it was before you joined dev), and noone ever reviewed.
Maybe you could have a look in terms of wording but also in terms of the proposed procedures?.
Multiple branches also did not exist at the time of writing.

**Comment by ecdye** [comment]
Sure, I'll add that to my list of things to work on.

**Comment by ecdye** [comment]
Alright, lets brainstorm and revise / update `openhabian-DEBUG.md` in #1006.
