### ISSUE TITLE
systemd errors in CI

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1002]
See https://travis-ci.com/github/openhab/openhabian/jobs/353508710#L1186

**Comment by BClark09** [comment]
That's a fairly strange error to have, shouldn't it be looked into instead of hiding it?

**Comment by ecdye** [comment]
The error is because of the Docker setup we use and as far as I know cannot be fixed. It is all because of the systemd replacement we use.

**Comment by mstormi** [comment]
exactly, it doesn't happen on real HW
