### ISSUE TITLE
openHABian Installation Status can't connect to openhab:80/first-boot.txt

### ISSUE THREAD

**Issue by Tomasmerca** [openhab/openhabian#1024]
## Issue information:
It is a very simple issue with the openHABian Installation Status page. It did not appear using http://openhab/
but it did appear using the pi's IP but didn't show anything. Looking at the source code it wants to connect to http://openhab:80/first-boot.txt
If I replace openhab to it's IP with firefox tools it loads the logs

## System information:
Latest Firefox on Windows 10
Rapberry 3B+ - Latest public release

**Comment by ecdye** [comment]
Image install is broken right now in some aspects as we are preparing to release a new image. When released, then new image should fix the issue.

**Comment by mstormi** [comment]
That's not an openHABian issue if your DHCP does not  properly map the DNS name "openhab" to its IP. If it does not, you obviously need to use the IP (as mentioned in the docs I think).
Last time I checked it worked and I would still expect it to work but as Ethan commented, wait for the new image then check back and eventually reopen this issue.
