### ISSUE TITLE
New Openhabian - Installation Script

### ISSUE THREAD

**Issue by DerFossiBaer** [openhab/openhabian#1025]
Hello forum.

I manage 3 to 5 openhab installations and today i tried to setup a new one. I get the things working on virtual maschines (Proxmox) and the VM is running on Debian 9 or now 10.

Until a few weeks ago there was only a problem with zulu and i got the script working by installing zulu-8 by hand from zulu repos. 

But today im struggling completly. there are a few new points in the installation process and it seems that the script doesn't fits to debian any more. So what can id or witch parameters I have to look for that the script rolls proper. I think the first is to add user and group openhabian:openhabian - they doesnt't created anymore and I get a few errors with user:user. So is it a problem to work with zulu-8 64? I installed zulu by hand and i think i takes 64 bit according to the system. I found somthing with fake - hardware in the explanation - but i have no clue, what there should be putted in.

So I hope i can get some help here to understand the new features and can still work with a standard Debian 10.

ThX Fossi

**Comment by ecdye** [comment]
Try using the guide.

### Other Linux Systems (add openHABian just like any other software)
openHABian is also supposed to run on generic Debian/Ubuntu based systems on x86 and some ARM hardware platforms.
Start with a fresh installation of your operating system, login and run

```shell
# start shell as root user
sudo bash
```

then start installation

```shell
# install git - you can skip this if it's already installed
apt-get update
apt-get install git

# download, link and create config file
git clone -b stable https://github.com/openhab/openhabian.git /opt/openhabian
ln -s /opt/openhabian/openhabian-setup.sh /usr/local/bin/openhabian-config
cp /opt/openhabian/openhabian.conf.dist /etc/openhabian.conf
```

Edit `/etc/openhabian.conf` to match your needs, then use

```shell
openhabian-config unattended
```

`openhabian-config unattended` is what sets up the base system so the other scripts work properly. Try running that first and see if the functions all work properly. Zulu install script should work fine on Debian 10 as in our testing it does.

**Comment by DerFossiBaer** [comment]
That is exactly (nearly) what I've done yesterday. the only think is, that te Platform is not 32bit. It was a fresh setup from a Debian 10. Befor starting the script I installed zulu8 by cli  and I didn't touch the /etc/openhabian.conf - till 1.4 there was no need to thange something. 

I saw in the script output that the issue seems to be something with the user. The script didn't createt the user openhabian and than stucks, where the user is needed (samba, and something else). 

So why openhabian isn't supposed to run on Debian 64 bit. The only thing i saw was zulu in the past. And what I have exactly to change in the openabian.conf - there are only the first to points to change and then there is commented 

`# Do not change these lines`

Its a clean fresh install and I was fin with the user openhabian, so there should be nothing to change in best case.

Thanks for the help.

**Comment by DerFossiBaer** [comment]
So now I take a look to the last working installation and compared the openhabian.conf. The system user was added in the conf file, whitch must by done by the installation routine. And in the first section i found three entries. hostname username userpw. In my installation rests there where found only two. 

I added some entries in the script and saw a struggling with the password from the systemuser "LMU=o:)" - the script can't working with a secret like this. That's the point. And the rest belongs to this fault. 

I changed the password and the script runs clean - so by the way - my first time, i took unattended installation. Until yesterday i made it by hand.

Thx - Fossi

**Comment by mstormi** [comment]
> Hello forum.

This is not the forum but Github. It is not for user support so please turn to the forum next time.
Github is to track bugs which is not obvious that it is one in your case.

openHABian is supposed to run on Debian but you have to meet the [prerequisites](https://github.com/openhab/openhabian/blob/master/docs/openhabian-DEBUG.md#prerequisites) and - probably even more important - you must not do anything "by hand" or "the way it always worked" as that likely *invalidates* prerequisites hence breaks openHABian install (unattended or not).

Your posts are unclear if you still have a problem (if so, turn to forum) and if you still believe there's a bug (for that, stay here).
If the latter, get us input we can work on. Read the debug guide, set `debugmode=maximum` in `/etc/openhabian.conf` to get verbose output and start another unattended installation attempt.
And - most important - *properly describe* the problem and symptoms again.
Post the relevant part of the log (or everything if you're unsure). 
Check the log if your OS is correctly identified. We had #665 with similar symptoms so that may be the problem here.

**Comment by DerFossiBaer** [comment]
Ok - i understand - here is not a forum.

I do not know, if it is a bug, when the script isn't able to get working properly, when a special kind of password is set to the default system user with sudo privileges. The script hat problems with the ":" or the ")" in the password. I changed the password to somthing less special and it works fine. So this thread could be closed or not. I don't know if someone will spend the time to have a lock at this - I think it is not necessary, but perhaps someone else could get in same trouble with a special kind of signs in his password.

**Comment by mstormi** [comment]
> The script hat problems with the ":" or the ")" in the password.

*If* that happens to everybody it's a bug worth fixing.
But openhabian doesn't prompt for any password on _unattended_ install so your description is confusing.

So again, properly specify the problem first. *When* (in what situation) does it happen?
If it happens on interactive use, set debugmode=maximum in openhabian.conf and run openhabian-config, select the menu option you used earlier to pchange password (or whatever you did) and upload the resulting logfile.

**Comment by mstormi** [comment]
reopen if you believe there's still a problem but provide details if so please
