### ISSUE TITLE
OpenHABian crashes again and again - probably udevd issue

### ISSUE THREAD

**Issue by TS-Tec** [openhab/openhabian#103]
Hey all,

I am using openHABian since 3 or 4 weeks and are very happy with whole package at all. 
@ThomDietrich Thanks for the great work!

But what is driving me mad are system crashes repeating every few days. I did a clean install of the whole system 4 times because I was even not able to recover from backup images.

What happens:
The system runs nice for a given time and then starts to do unnormal things.. While I am doing some configuration stuff in the PaperUI (let time setting up HomeKit integration) for example, it gets stuck and does not answer any more.

The start up log then throws many error messages and end up in recovery mode or even kernel panics. I attached a few logs, most time the issue has to do with the `udev Kernel Device Manager`

I exchanged nearly everything in regards of hardware:
The power supply unit, the power cable, the SD card and also the complete Raspi 3.

If I do some google searching, it sometimes says it has to do with hardware incompatibility with some modules.

I have installed:
OpenHABian v1.1, zway Z-Wave Server (controlling a RaZBerry Daughter Board), PiLight (controlling a 433MHz transmitter) and thats all.
All in the latest version.

I hope you can give me some hints.. I spend plenty of hours for re-installing and debugging attempts and I am on the verge to give  up :(

Here are the screenshots:
https://www.pic-upload.de/view-32745992/Foto25.02.17104132.jpg.html
https://www.pic-upload.de/view-32745990/Foto25.02.17031425.jpg.html
https://www.pic-upload.de/view-32745991/Foto25.02.17031024.jpg.html
https://www.pic-upload.de/view-32745993/Foto25.02.17030940.jpg.html

**Comment by ThomDietrich** [comment]
Hey, I believe we were talking in the community forum? Where you able to solve this issue?

**Comment by johannesbonn** [comment]
Hello Thomas,
I have exactly the same problem after a restore of an backup. Did You find a solution?

Greetings

Johannes

**Comment by ThomDietrich** [comment]
Any news on the issue? Temporarily closing, please provide new information to reopen.
