### ISSUE TITLE
InfluxDB install failing

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1031]
I used the latest beta RaspiOS image.
It fails to install Grafana. On installing via menu, it's complaining about Grafana repo
gpg: no valid OpenPGP data found.

@holgerfriedrich could you please take a look? You're more familiar with that than I am. 

[install.log](https://github.com/openhab/openhabian/files/4912341/install.log)

**Comment by holgerfriedrich** [comment]
@mstormi won't be able to look at this the next days....

**Comment by mstormi** [comment]
No worries.
But could you please give an estimate when we can finalize the image ? (without offline install)

**Comment by mstormi** [comment]
See https://travis-ci.com/github/mstormi/openhabian/jobs/361419253#L439
(@ecdye would you know how to fix the repo keyring ?)

**Comment by ecdye** [comment]
Hmm, not really. You could try using the `add_keys` function and see if that helps.

**Comment by mstormi** [comment]
does no longer happen with current code and repo
