### ISSUE TITLE
Auto-backup

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1044]
Just an idea to track and discuss

We equip a Pi with a say 16GB internal SD card plus an external card reader(!) with a 64GB one.
First two partitions on the external card will be mirrors of the two partitions on the internal one, and the rest will be dedicated to provide backup storage for use by Amanda.
Also add cronjobs to rsync config and persistence DB daily and copy partitions say monthly (eventually mount+unmount after).
Now if the internal card fails for whatever reason, we have a ready-to-run backup on the external card, including daily snapshots of persistence and other data in ZRAM(!) that otherwise gets lost.

Implementation: Make card reader device a parameter in openhabian.conf.
In unattended install, check for partition sizes, partition external stick and call amanda_setup with suitable parameters. 

wdyt?

**Comment by ecdye** [comment]
Not a bad idea, but I feel like it should not be a high priority because it would probably have very low usage. Great concept though.

**Comment by mstormi** [comment]
Usage is a matter of marketing, isn't it

**Comment by ecdye** [comment]
You're not wrong. However, this adds more to the base system purchase price and it may not be very appealing to the average user.

**Comment by mstormi** [comment]
This is what, $15 maybe ? Less than half of a spare RPi.
Let alone that anyone with serious intentions should be having a full set of spare HW at hand anyway.
And if you were reading the forum about people using virtualization on PC hardware and fantasizing about Kubernetes-managed RPi clusters ... so there definitely is a need for clever, simple resilient system setup.
If that's a significant number of users, I don't know, we'll see.
Check back with https://github.com/orgs/openhab/teams/openhabian-maintainers/discussions/17 , too.
