### ISSUE TITLE
Suggestion for openhabian-config: Disable WLAN, switch to LAN

### ISSUE THREAD

**Issue by Diapolo** [openhab/openhabian#1049]
I'm missing an option to switch from a WiFi-only setup to a LAN-only setup. When I was initially setting up OpenHABian I chose WLAN, which is working, but not as stable as a cable and so I want to change this. Im suggesting an option to disable WLAN and remove the configuration and activate all stuff that is needed for using a LAN connection.

**Comment by ecdye** [comment]
If you rerun WiFi setup there should be an option to disable WiFi and return to Ethernet.

**Comment by Diapolo** [comment]
This is indeed working as intended, but the dialog is missing a switch back to **LAN** message as far as I remember. So just a cosmetic glitch, nothing more :).
