### ISSUE TITLE
Openhabian on Pine 64 2Gb won't boot without HDMI

### ISSUE THREAD

**Issue by sihil** [openhab/openhabian#105]
I've not done a lot of troubleshooting on this yet but wanted to open this here in case anyone else is experiencing the same thing. 

I've successfully installed openhabian on a pine 64 2gb board with the zwave daughter board. It works great and was super easy to get set up so first of all congratulations and thank you to all of the contributors. 

The one thing I've found so far is that whilst everything works as expected when I have both ethernet and HDMI connected, it seems I cannot get the pine 64 to boot without the HDMI connected. With no HDMI, the ethernet port never comes up. 

My googling so far has not shown this to be a generally known issue with the pine64 which is why I'm raising it here rather than on a pine64 forum. 

Sadly I don't have a serial port so don't really have a strategy to troubleshoot, although my next plan is to image some other OSes to see if this is peculiar to openhabian or whether Ubuntu and Pine 64's Openhab2 image also exhibits it.

**Comment by ThomDietrich** [comment]
Hey @sihil thanks for taking the time to report this issue, besides these I'm happy everything else worked out for you.

This problem doesn't make sense to me. What's the special role of the HDMI port on the Pine A64? Why would something being connected to it make any  difference!?

openHABianPine64 is mainly based on https://github.com/longsleep/build-pine64-image which in return is what is used to generate http://wiki.pine64.org/index.php/Main_Page#Ubuntu_16.04

If the described issue is true for openHABian, it must also be true for the Ubuntu distribution by longsleep. Could you test with a spare SD card?

**Comment by sihil** [comment]
Doesn't make sense to me either. I'll find a spare SD card and experiment with the base images this week and get back to you with the results.

**Comment by sihil** [comment]
I've finally got round to installing longsleep's `xenial-pine64-bspkernel-20161218-1.img` and it exhibits exactly the same behaviour. When HDMI is plugged in it boots and when it's not plugged in it seems to do nothing at all.

Upon further experimentation I've discovered that if you DON'T plug an HDMI display in on the first ever boot then it DOES boot and continues to boot even when an HDMI display is subsequently added and removed (with reboots between config changes).

Something seems to happen on first boot. If an HDMI display is connected at this point then that means that the OS will no longer boot headless. I've spent my evening trying to figure out what is different between the two scenarios, but have yet to turn anything up.

I've added a query about this to a Pine64 forum post about the images: http://forum.pine64.org/showthread.php?tid=376&pid=26510#pid26510

**Comment by ThomDietrich** [comment]
interesting findings! Let's see what others in the forum have to say. You might want to also create an issue here: https://github.com/longsleep/build-pine64-image/issues

**Comment by sihil** [comment]
I was trying to reply to longsleep's reply on the forum but my account no longer seems to be allowed to reply so I'm putting it here for now (with the aim of moving it later).

I'm using a Raspberry Pi 2A PSU that I had to hand so I'm confident that power is not an issue and the issue only starts on subsequent boots if an HDMI display was attached on the first boot - and it doesn't sound like it should be generating keys on subsequent boots.

My testing setup has been to simply have it plugged into an ethernet port. My criteria as to whether it has booted or not is whether the interface comes up and I see traffic on the port. I've been leaving my laptop pinging the IP address. Crude, but effective and reproducible many times.

I was looking at dmesg output and noticed that the sunxi disp2 is initialised once on first boot and twice on subsequent boots. I have no idea if that's connected. 

Sadly it's impossible to tell where it is stuck without a display or console attached. I've just ordered a USB/UART cable so I can do that (been regretting not buying the Pine64 adaptor in the first place). I might try seeing if I can connect it to the serial port of a raspberry pi tonight rather that waiting for delivery.

I'd be intrigued to know if anyone else was able to re-produce it (or not able to re-produce it) - would give me more confidence that this is actually a thing rather than it being something silly that I've done or my particular board.

I'll write more when I discover anything new.

**Comment by sihil** [comment]
I've just re-imaged my openhab without an HDMI display connected on first boot and can confirm that my experiments with longsleep's image are also borne out with openHABian. My Pine64 can now happily boot without an HDMI screen connected.

I've not proven first boot with display connected is broken in the same way (I'm kinda bored of imaging SD cards after doing it circa ten times yesterday), but I assume it would exhibit the same issue.

Do you want to leave this issue here @ThomDietrich? It's a bit of a corner case. Perhaps a short term solution can be some documentation for Pine64 warning against having HDMI connected on first boot?

**Comment by ThomDietrich** [comment]
Hey I've seen the discussion over in the longsleep repo got some attention. Hopefully this is resolved soon. Till then I'll add a warning to the openHABian documentation as per your suggestion.

I'll leave the issue open, please let me know about noteworthy developments 😉

**Comment by mstormi** [comment]
I think with almost 3yrs without news and our decision to discontinue PINE support we should close this. Please reopen if you disagree.
