### ISSUE TITLE
Java cacerts

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1050]
is said to be removed on Java change
https://community.openhab.org/t/java-11-test-amazonechocontrol-2-5-7-snapshop-throws-exceptions-due-to-missing-cacerts-file/102446/4

not sure what that contains and who generates that so lets find out first

**Comment by ecdye** [comment]
I know what caused it. It is me forgetting that other things end up being installed where the CEK goes. I'll work on a fix ASAP, but I am currently out of town so it might be a few Days.

**Comment by GumbyMan82** [comment]
just FTR: I've closed my issue in the openhad-addons since the problem isn't caused by the amazon binding.
