### ISSUE TITLE
Node.js should be updated

### ISSUE THREAD

**Issue by benderl** [openhab/openhabian#1056]
## Issue information:
I am running my openhabian installation since several month now. It got installed with node.js 10.x but meanwhile version 12.x is marked as LTS. Due to the generated `/etc/apt/sources.d/nodesource.list` the version sticks to 10.x. I would expect an update of the nodesource.list file if the installation/update of node-red is triggered from within openhabian-config.

## System information:
Latest openhabian version.
```
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**Comment by mstormi** [comment]
I don't understand your point.
If you install nodered from the openhabian-config menu, [nodejs_setup()](https://github.com/openhab/openhabian/blob/master/functions/nodejs-apps.bash#L8) is triggered, and that regenerates /etc/apt/sources.d/nodesource.list with a source to use 12.X

**Comment by benderl** [comment]
Well here the nodesource.list was not updated from 10.x to 12.x. I have to look through the function and check what prevented the update.

**Comment by mstormi** [comment]
You can set debugmode=maximum in /etc/openhabian.conf, then re-run installation via menu

**Comment by benderl** [comment]
I think, I found the problem:
In [line 100](https://github.com/openhab/openhabian/blob/fc4e8e041e4ae5181793d6df4ad4a808de6f3fb8/functions/nodejs-apps.bash#L100) only the presence of npm is verified but not the version of node.js. So the function to update the sources file never triggers.

**Comment by ecdye** [comment]
Yes I did that intentionally, it was in order to not break any existing installations. If you would like to update it using `openhabian-config` simply remove those checks and it will upgrade it for you.

**Comment by mstormi** [comment]
> it was in order to not break any existing installations

Does that make sense ? It's in the *install* routine for nodered *on openHABian* so at least on image-derived Raspbian there should not be any existing installations (then again on other Unices yes there could be).
Eventually add a whiptail query in that case?

**Comment by benderl** [comment]
I just edited the sources file to upgrade node.js. But as the config tool installs all dependencies for node-red I would also suggest to check the installed version and prompt if an upgrade should be triggered.

**Comment by ecdye** [comment]
No, it is there because otherwise we will overwrite the APT config and reinstall every time wasting resources. When we release a new image it should result in zero issues as with the new installation APT will upgrade NodeJS automatically. This all stems from us moving to an apt based install for NodeJS rather than a download based install (excluding `armv6l`).

**Comment by benderl** [comment]
> No, it is there because otherwise we will overwrite the APT config and reinstall every time wasting resources.

Sorry, but I do not understand this. Upgrading the repo results in just one package upgrade. Then it is treated as every other package by apt and only updated, if there is a new version.
> When we release a new image it should result in zero issues as with the new installation APT will upgrade NodeJS automatically.

Yes, apt will take care of the updates, but in my case during installation openhabian added a sources list for node.js 10.x. Apt did take care of this, but was limited to the old 10.x branch of node.js.

**Comment by ecdye** [comment]
I understand, we need to add a case for is node is v10 update it.

What I was referring to by wasting time is the installer would recreate the apt lists and run an `apt-get update` and then try to install, which wastes resources and time.

**Comment by benderl** [comment]
Yes, if version 10.x update the sources list to 12.x.
