### ISSUE TITLE
Reboot on fresh install?

### ISSUE THREAD

**Issue by ecdye** [openhab/openhabian#1058]
I think that after a fresh install we should automatically reboot the system. I suggest this for a few reasons,

1.   Several operations performed on first install require reboot for changes to take effect (locale, wifi, ipv6...).
2.  Acts as a way to refresh the network connection for instances where that may have changed.
3.  It is a very common operation to perform after system upgrades and our install process often installs kernel upgrades or other significant upgrades to the system during setup.

Thoughts?

**Comment by mstormi** [comment]
Agree but the open question is if it is sufficient after an unattended installation (then we should automate that) or if a user would need to manually add whatever first before it makes sense to reboot.

**Comment by ecdye** [comment]
I think that because we are trying to leave the user with as complete and functional system as possible we should to it automatically on unattended install. If the user makes further changes that require a reboot that should be their responsibility. Especially since the majority of users won't care enough or be technically inclined enough to want to do such changes.
