### ISSUE TITLE
image failing to install with various symptoms

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1063]
In the first place I thought it was a problem with mosquitto that didn't run after a reboot
Debugging, I came to think it is ZRAM related because that fails to install

But I believe the problem is larger:
Apparently modprobe zram fails because the kernel modules (5.4.51) do not match the kernel (4.19.57).
The kernel that's in the old image is too old!

That's why installing zram fails unless we reboot. But that results in a need to install zram manually.

I believe we should hurry up with the new image as it probably will not happen there.

**Comment by ecdye** [comment]
It won't help, as the image RasberryPi provides is still based off of the old 4.19 kernel so it will still upgrade to 5.4 when installing.

**Comment by mstormi** [comment]
ok could you put that into master? that's broken anyway ATM. Need to leave now but will be back in ~2 hrs.
I've just prepared a pre-release we can direct people at when they have problems.
https://github.com/openhab/openhabian/releases/tag/v1.6-alpha

**Comment by ecdye** [comment]
@mstormi We should probably sync master and stable for the image release when we finish testing, that way it is the same across the board.

**Comment by mstormi** [comment]
Yes. I'd think stable is currently affected as well.

**Comment by ecdye** [comment]
And that way they are both in sync for the image release and people won't be confused by why it is a different git hash when we trigger the build from stable

**Comment by mstormi** [comment]
Trouble is, first-boot.bash is run off /boot which is the image-contained version not the current one
So we need to build another image for this to work, right ?

**Comment by ecdye** [comment]
Yes, but as I was saying that is why the image should be built off of a synced stable and master branch

**Comment by mstormi** [comment]
I'm right now syncing stable to master

**Comment by mstormi** [comment]
strange, it's building an oldish stable....

**Comment by mstormi** [comment]
Ouch we have a problem. The box keeps rebooting over and over. Any spontaneous idea ? Just wanted to go to bed ;(

**Comment by mstormi** [comment]
I've quickly put up #1066/#1067 but haven't been able to fully test

**Comment by mstormi** [comment]
... and I wonder what a reboot is doing to CI ...

**Comment by ecdye** [comment]
No, idea. CI, appears to be handling it without errors though. Your solution seems fine to me, however I don't have time to test today.

**Comment by mstormi** [comment]
Damn it, there's reports of the image failing to complete installation / start the dashboard

**Comment by mstormi** [comment]
ZRAM down, too.
But both just needed a systemctl start ...

 I'll check if the just-merged additional reboot will fix that

**Comment by mstormi** [comment]
is #1069 a duplicate?
will therefore #1070 fix this?

**Comment by ecdye** [comment]
IDK, I think we should merge #1039, #1070, and #1072 ASAP and finalize the image as I believe those contain all of the remaining breaking changes to the final image.

**Comment by mstormi** [comment]
call of delayed_rules (and ZRAM changes to service!) suddenly missing in openhabian-setup.sh ?

openhabian@openhabianpi:~/openhabian $ grep delayed functions/* openhabian-setup.sh
functions/menu.bash:      *Delay\ rules\ load) delayed_rules yes;;
functions/menu.bash:      *Default\ order) delayed_rules no;;
functions/openhab.bash:##    delayed_rules()
functions/openhab.bash:delayed_rules() {
functions/openhab.bash:  delayed_rules "yes"

**Comment by ecdye** [comment]
Yes, that is because I only included the FIND3 branch changes not the others, sorry for the confusion.

**Comment by mstormi** [comment]
tested build #207 (to include ZRAM patches)
The service files look fine but ZRAM fails to start. Or to be more precise, it is started and stopped again. If manually started again it's fine but why does it stop ?

**Comment by ecdye** [comment]
Not sure. Is this the result after the final reboot during install? It shouldn't be being stopped it is one of the last things installed and nothing after it calls for a reinstall.

**Comment by mstormi** [comment]
test with latest build was ok

**Comment by mstormi** [comment]
given there were no more unexplained problems on latest build (except #1078), I'm gonna close this now.
Reopen in case of new or re-occuring issues.
