### ISSUE TITLE
not syncing on ZRAM shutdown

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1078]
As there's reports of mapdb persistence data (to run on ZRAM) not being restored, I've investigated how zram behaves and found out that if you simply 'reboot', changes *sometimes* are lost.

I'm asking all of you for help. *I just don't understand what's going on here.*

[ hint for debugging: the lower FS contains the directory as it existed when ZRAM starts for a dir. It's mounted under /opt/ram/*.bind so I use [ `date>/var/lib/openhab2/persistence/date` and `cat /opt/zram/persistence.bind/date /var/lib/openhab2/persistence/date` after startup to see the last modification date ]

On boot persistence files are what they used to be on last time's zram start. When you manually systemctl stop zram-config before boot, files are apparently correctly synced to lower FS (on SD card).
~~So this seems to be a systemd config problem !? Apparently there's no systemctl stop zram-config being carried out ? Anybody proficient in debugging systemd startup/shutdown order ?~~

Preliminary investigations show zram-config stop *is* called. But it does *not always work.*

Another possibly relevant detail: freshly after boot, with oh2 running, I get a warning although I don't modify any systemd config files:
```
[15:21:09] root@openhab:/home/openhabian# systemctl stop openhab2
Warning: The unit file, source configuration file or drop-ins of openhab2.service changed on disk. Run 'systemctl daemon-reload' to reload units.
```

There's a known bug to output this but I'm not sure if that is what I hit because that is said to be just cosmetic.

**Comment by mstormi** [comment]
cc: @holgerfriedrich

**Comment by ecdye** [comment]
I'm not sure. I don't really have much time to debug today but I should be able to work on it tomorrow. 

We may need to invest some time in making the ZRAM tool openHABian uses safer and more reliable. Perhaps after I finish #1055 I can look into rewriting and updating ZRAM.

**Comment by ecdye** [comment]
@mstormi, I think I might have found it. 

In the `zram-config.service` file the line
```
RemainAfterExit=yes
```
Should be
```
RemainAfterExit=true
```

Try changing that and see if it works.

**Comment by mstormi** [comment]
systemd.service manpage says

       RemainAfterExit=
           Takes a boolean value that specifies whether the service shall be considered active even when all its processes exited. Defaults to no.


so "no" is boolean?

**Comment by mstormi** [comment]
"zram-config stop" should create a log line in /usr/local/share/zram-config/logs/zram-config.log but that does not appear
so I'm not sure it's called at shutdown/reboot time at all.

I created another service to just "ExecStart=zram-config stop" on *shutdown* but it is not even listed by systemctl list-dependencies so I'm a bit lost where the error might be ATM

**Comment by ecdye** [comment]
Did you run `sudo systemctl dameon-reload`?

**Comment by mstormi** [comment]
of course
I now get to list it but it does not exec

**Comment by ecdye** [comment]
Is it because ZRAM is PartOf openhab2 and openhab2 is not explicitly stopped on reboot?

**Comment by mstormi** [comment]
No I test with
date | sudo tee /var/lib/openhab2/persistence/date;systemctl stop openhab2;zramctl;reboot

so if that worked, it would
strange thing *sometimes* it works, most of the time not

**Comment by ecdye** [comment]
Have you tried a fresh install to see if it is an isolated issue?

**Comment by mstormi** [comment]
just trying ATM

**Comment by mstormi** [comment]
happened the same with fresh install.
After some play forth and back I came up with this service below.
That now seems to work although it does not explain why it's needed (zram-config already should do).
And as the problem seemed to have been intermittent I'm not sure it will not happen again with this fix

```
[Unit]
Description=zram sync on shutdown/reboot
PartOf=openhab2.service
Before=reboot.target shutdown.target poweroff.target halt.target

[Service]
Type=oneshot
ExecStart=/usr/local/bin/zram-config stop
ExecStop=/usr/local/bin/zram-config stop
TimeoutSec=0
RemainAfterExit=yes

[Install]
WantedBy=basic.target reboot.target shutdown.target poweroff.target halt.target
#WantedBy=basic.target

```

**Comment by mstormi** [comment]
> Is it because ZRAM is PartOf openhab2 and openhab2 is not explicitly stopped on reboot?

rereading this .... do you know if openhab2 stops on reboot ? Didn't even think of that possibility.

**Comment by ecdye** [comment]
No idea, does running `sudo systemctl stop zram-config.service` work properly? If so then it a bug somewhere in the reboot process that causes it not to run.

**Comment by mstormi** [comment]
It's none of the obvious things.
First, note I've added zram-sync service as above. I now do
`date|sudo tee /var/lib/openhab2/persistence/date;zramctl;reboot` and look at the file after boot.
Sometimes it's updated on boot, sometimes not. I JUST DONT UNDERSTAND IT, damn it.
So the problem must be in the shutdown sequence, right ?
Could you try reproducing on your system ?

**Comment by mstormi** [comment]
Hmm, I've apparently managed to get rid of the cycle it's not showing errors now but it doesn't help.
Seems I still cannot get the script to execute on shutdown.

**Comment by ecdye** [comment]
I'll investigate it some this afternoon, I am not sure what is happening. Does making openHAB and frontail stop before shutdown in addition to zram-config help?

**Comment by mstormi** [comment]
I've made more investigations but fail to find the root cause.

I've added (und meanwhile retracted) a zram-sync service. Retracted because I believe zram-config IS properly being executed on reboot/shutdown, i.e. zram-config stop *is* *always* called so that cannot be the problem.
You can see with journalctl -xu zram-config --no-pager.
But I fail to understand why it *sometimes*  does not sync a file from ZRAM back to SD and sometimes it does.

**Comment by ecdye** [comment]
Is it possible that the stop command is not getting enough time to finish, or the system is already shutting down certain areas that ZRAM needs to sync before ZRAM can get to them?

**Comment by mstormi** [comment]
I've encountered at least 2 cases.
See /usr/local/bin/zram-config. The 1st case is that the lazy unmount (umount ... -l around line 181) in removeZdir()fails and mergeOverlay() isn't called.
In the 2nd case it is but the list of sync files is empty and I don't understand why

**Comment by ecdye** [comment]
Possibly because of global variables not being changed? I see what issue you are running into, and agree that it appears to be caused by the ZRAM code.

As I said, it may be best to completely rewrite ZRAM and use it for our purposes.

**Comment by mstormi** [comment]
> As I said, it may be best to completely rewrite ZRAM and use it for our purposes.

The original author no longer works on it and offered to transfer the project to anyone willing to continue.
It's not a matter of rewriting for our purposes. Frankly I wouldn't know what to do there :-|

**Comment by mstormi** [comment]
Don't know how to resolve for the time being.

I came to think that with #1077, I can introduce a "zramsync" service to sync zram dirs to external disk on shutdown and to restore from there on boot.

**Comment by ecdye** [comment]
Possibly. It may be a better idea to look at the OverlayFS code and see if we can find a proper fix though.

**Comment by mstormi** [comment]
> look at the OverlayFS code and see if we can find a proper fix though.

Feel free to give it a try, but given the ZRAM author himself didn't succeed there (see his comments) I'm sceptic here.

**Comment by mstormi** [comment]
hopefully fixed by https://github.com/mstormi/openhabian-zram/commit/589ca5984b2cd196a10a66638d2336994772792a

this is rsync'ing ZRAM dirs only (not "log" dirs) to (extra) disk on shutdown and recovers on boot.

**Comment by mstormi** [comment]
I've attempted multiple forms, rsync and tar, the joint FS and just the upper FS in /opt/zram/zramX and I think they all worked.
But it just doesn't sync. 

I'm getting mad at this.
I must be overlooking something serious. Please Ethan or Holger take over or at least a look. I just cannot find out why it doesn't work. Another pair of eyes sees different things than mine do I hope.

When I use zramsync interactivelym everything is working. But called from the service it doesn't.
Grab the output of journalctls -xu zram-config to see for yourself and help me find out please.
I see zramctl output all dirs but on accessing /opt/zram/zramX/upper, it's gone. Or the file I created for the test just isn't there.
As I said already more than once, I'm getting mad at this.

At times while experimenting zramsync didn't run because of a dependency cycle so watch out for that.
But with the zram-config.service in the openhabian-zram repo it is working with cycles I believe so that's probaby not the root cause.

**Comment by ecdye** [comment]
I have been working on a rewrite, and am testing it. Also overlayfs was recently updated, it may be fixed now. I'll update you when I have more informatiion on testing.

**Comment by mstormi** [comment]
Glad to hear. But mind that I think all those versions of zramsync I tried were fine and that the problem is not in our code.
Just not always executed on shutdown while I've been tinkering with systemd options but I think at least that is working in current version.

**Comment by mstormi** [comment]
> 
> 
> Glad to hear. But mind that I think all those versions of zramsync I tried were fine and that the problem is not in my new or existing code. In addition to that - but not as the root cause - it was not always executed on shutdown while I've been tinkering with systemd options but I think at least that's working now.

**Comment by ecdye** [comment]
https://github.com/kmxz/overlayfs-tools/commit/77bf3f7ad3e7b834a15e2166780167646d51cce8

**Comment by mstormi** [comment]
still trying to debug but still need your help

Latest finding:
I have zram-config.service properly execute on start and stop on reboot. I execute a script and add debug output in that script.
On stop, the ZRAM dirs seem to already be unmounted by the time the stop script executes.

Any idea how to find what unmounted them *before* ?

Log of stop script:
```
[16:01:43] root@openhab:/storage/zram# cat zramsync.log
zramsync creating backup @ Mon 24 Aug 16:00:41 CEST 2020
inFile=/usr/local/share/zram-config/zram-device-list
swap            /zram0          zram-config0
dir             /zram1          /var/lib/openhab2/persistence           /persistence.bind
log             /zram2          /var/log                /log.bind
NAME       ALGORITHM DISKSIZE  DATA COMPR TOTAL STREAMS MOUNTPOINT
/dev/zram2 lzo-rle       500M 17.2M 81.9K  432K       4
/dev/zram1 lzo-rle       500M 16.4M 10.1K   96K       4
/dev/zram0 lzo-rle       600M    4K   87B   12K       4 [SWAP]
overlay2          479560    9396    434324   3% /var/log
/opt/zram/zram1/upper
zramsync end run @ Mon 24 Aug 16:00:41 CEST 2020
```

**Comment by mstormi** [comment]
Just found out about the `RequiresMountsFor=` option in .services. 
Gets me a tiny bit closer to the target....

**Comment by ecdye** [comment]
I'm hopeful, this has been a real PITA. Ideally that would allow for proper execution without need for zramsync.

**Comment by mstormi** [comment]
Unfortunately not (I tried right away, of course) but at least we only need a single service.

**Comment by ecdye** [comment]
So it is working correctly and syncing with zramsync now right?

**Comment by mstormi** [comment]
Apparently yes but I'd like others to validate.

**Comment by ecdye** [comment]
I will test this afternoon.

**Comment by mstormi** [comment]
eventually use the latest image with clonebranch=testbuild

**Comment by ecdye** [comment]
I have to wait to test the other PRs until I get a usb SD card reader as I don't have one available at the moment. I'll just uninstall and reinstall zram as that will update the repo.

**Comment by ecdye** [comment]
I don't think it is working correctly as the RequiresMountsFor would prevent it from starting zram on boot as those DIrs would not be mounted and as such would fail.

**Comment by ecdye** [comment]
See https://github.com/mstormi/openhabian-zram/pull/5 for continued info

**Comment by mstormi** [comment]
I presume you have seen https://community.openhab.org/t/mapdb-no-restore-at-startup-for-item-status/102835/61
But I just don't know what else to check now that zram start seems to always work on my test system.
My hope is just it is because of storage.mount and dependencies intro'd in #1077.

**Comment by ecdye** [comment]
Did you have him reinstall the timesync dhcp hook to see if that fixes the issue?

**Comment by mstormi** [comment]
not explicitly but I had him reinstall and as that's in master now it should be there.

**Comment by mstormi** [comment]
See my latest post at https://community.openhab.org/t/mapdb-no-restore-at-startup-for-item-status/102835/66

Not sure why local-fs.target depends on `srv-openhab2*.mount`.
/srv/... is loopback mounts that require the mount they loop back to exist so After=local-fs.target in their .service definitions should be about right.
Eventually any `.mount` implicitly is part of` local-fs.target` ?
See also https://unix.stackexchange.com/questions/519221/how-can-i-solve-this-ordering-cycle-in-a-mount-unit

I'm thinking to remove those `/srv` mounts and export the real dir(s) instead but that's only the second best option.
If possible I'd like to keep those.

**Comment by ecdye** [comment]
But why is this not happening to us, only to him?

**Comment by mstormi** [comment]
Coincidence.
systemd has many freedom degrees in choosing startup order. It may choose any order that isn't prohibited by setting dependencies, plus scheduling has impact on how fast services start, giving way for other dependent services to start.
And when there exists a circular dependency, it's coincidence whether systemd chooses a startup order that makes us end up in the circle or not.

We need to get the startup free of any cycle. So it's about testing, testing, testing to discover as many of them, then analyse each one we find and change one of our services to break the cycle.

**Comment by ecdye** [comment]
What if we add a `Before=smbd.service` to the mount template? It already has an `After=zram-config.service` so won't that fix it?

**Comment by mstormi** [comment]
It won't make a difference for our cycle problem because smbd.service isn't in the cycle (see thread).
And if we removed After=zram-config.service it could even start before that, exporting the non-ZRAMed lower FS.

**Comment by mstormi** [comment]
and as he just wrote that seemed to have done the trick. Keep your fingers crossed.

**Comment by mstormi** [comment]
I noticed you removed this line from zram-config.service:
ExecStartPre=-/bin/rm -f /usr/local/share/zram-config/zram-device-list /usr/local/share/zram-config/zram-device-list.rev

Accidential? I think we need it. Have you tested multiple zram-config start + stop in a row ? That's when it's needed.

**Comment by mstormi** [comment]
Do we really need the zramsync service or can we put everything into zram-config.service ?

**Comment by ecdye** [comment]
We need zramsync, it failed starts because of missing mounts. We discussed this before merging.

>I noticed you removed this line from zram-config.service:
ExecStartPre=-/bin/rm -f /usr/local/share/zram-config/zram-device-list /usr/local/share/zram-config/zram-device-list.rev

This is because the files were moved to `/tmp` like in upstream after a recent change which should remove them after stop but I don't know. However, in my testing I have had no issues with multiple starts and stops. If you have issues feel free to add it back.

**Comment by mstormi** [comment]
> We need zramsync, it failed starts because of missing mounts. We discussed this before merging.

Right. Just cross-checking everything again.
But now on my dev machine I cannot properly stop the service:

```
[21:57:38] root@devpi:/home/openhabian/openhabian-zram# systemctl stop zram-config.service
[21:58:14] root@devpi:/home/openhabian/openhabian-zram# zramctl
NAME       ALGORITHM DISKSIZE  DATA COMPR TOTAL STREAMS MOUNTPOINT
/dev/zram3 lzo-rle       500M   30M  1.7M  2.1M       4 /opt/zram/zram3
/dev/zram2 lzo-rle       350M 16.3M  5.6K  100K       4 /opt/zram/zram2
/dev/zram1 lzo-rle       500M 16.5M 16.8K  188K       4 /opt/zram/zram1
/dev/zram0 lzo-rle       600M    4K   87B   12K       4 [SWAP]
[21:58:18] root@devpi:/home/openhabian/openhabian-zram# zram-config stop
+ ZSHARE=/usr/local/share/zram-config
+ ZLOG=/usr/local/share/zram-config/log/zram-config.log
+ ZDIR=/opt/zram
+ [[ -f /boot/cmdline.txt ]]
+ grep -qs init=/bin/ro-root.sh /boot/cmdline.txt
+ ZEPHEMERAL=false
+ case "$1" in
++ date +%Y-%m-%d-%H:%M:%S
+ echo 'zram-config stop 2020-09-01-21:58:28'
+ tac /volatile/temp/zram-device-list
tac: failed to open '/volatile/temp/zram-device-list' for reading: No such file or directory
+ file=/volatile/temp/zram-device-list.rev
+ read -r line
+ rm -fv /volatile/temp/zram-device-list.rev /volatile/temp/zram-device-list
[21:58:29] root@devpi:/home/openhabian/openhabian-zram# echo $TMPDIR
/volatile/temp
[21:58:34] root@devpi:/home/openhabian/openhabian-zram#
```

**Comment by ecdye** [comment]
try adding it back and see if it fixes it. It is possibly I was wrong or that it has to do with the longevity of files in your particular `/tmp` directory. We may need to revert the change to `/tmp` if that was the case and give an explanation as to why it the upstream rewrite.

**Comment by mstormi** [comment]
what do you mean by "add it back" ? The file is not there, neither in /usr/local/... nor in $TMPDIR so adding the line that removes it PreStart won't change a thing.

**Comment by ecdye** [comment]
What I mean is revert to putting in /usr and then add the deletion back to the service as it is a better solution and avoids potential conflicts that might occur like yours.

**Comment by mstormi** [comment]
One problem with the current code is that it executes without environment (hence $TMPDIR is unset so the file is created in /tmp) but when I manually run zram-config stop, it *does* use TMPDIR hence looks for the file in the wrong place.

**Comment by ecdye** [comment]
systems should be stopping zramsync when it stops zram-config as well. BindsTo is a higher link then PartOf

**Comment by mstormi** [comment]
> 
> 
> systems should be stopping zramsync when it stops zram-config as well. BindsTo is a higher link then PartOf

In the first place, we need to find out why zram-config does not stop.

Once that works we might need BindsTo=zramsync in zram-config.service as well ?

**Comment by mstormi** [comment]
I made TMPDIR point statically to /tmp in openhabian-zram repo's zramsync and zram-config.
Change this in your PR against the original repo, too.

**Comment by ecdye** [comment]
I don't think that the gram devices have been removed properly for some time. I looked into it before and never did find a resolution.

**Comment by mstormi** [comment]
> 
> 
> I don't think that the zram devices have been removed properly for some time. I looked into it before and never did find a resolution.

Yes they were. Well all but sometime one of them was to remain.
But the current code does not even get that far, it leaves all of them unchanged.

**Comment by ecdye** [comment]
I don't know why because the logs indicate that it is attempting to remove them. Any ideas?

**Comment by mstormi** [comment]
[21:46:20] root@devpi:/home/openhabian# zramctl
NAME       ALGORITHM DISKSIZE  DATA COMPR TOTAL STREAMS MOUNTPOINT
/dev/zram3 lzo-rle       500M 40.9M  1.8M  2.3M       4 /opt/zram/zram3
/dev/zram2 lzo-rle       350M 16.3M  5.6K  108K       4 /opt/zram/zram2
/dev/zram1 lzo-rle       500M 16.5M 15.1K  156K       4 /opt/zram/zram1
/dev/zram0 lzo-rle       600M    4K   87B   12K       4 [SWAP]
[21:46:22] root@devpi:/home/openhabian# systemctl stop zram-config.service
[21:46:31] root@devpi:/home/openhabian# vi zramsync.service ^C
[21:46:38] root@devpi:/home/openhabian# systemctl status zram-config.service zra                                                                     msync.service
● zram-config.service - zram-config
   Loaded: loaded (/etc/systemd/system/zram-config.service; enabled; vendor pres
   Active: inactive (dead) since Thu 2020-09-03 21:46:31 CEST; 14s ago
  Process: 1019 ExecStartPre=/bin/rm -f /usr/local/share/zram-config/zram-device
  Process: 1029 ExecStartPre=/usr/local/sbin/zramsync recover /storage/zram (cod
  Process: 1430 ExecStart=/usr/local/sbin/zram-config start (code=exited, status
 Main PID: 1430 (code=exited, status=0/SUCCESS)

● zramsync.service - zramsync
   Loaded: loaded (/etc/systemd/system/zramsync.service; enabled; vendor preset:
   Active: inactive (dead) since Thu 2020-09-03 21:46:31 CEST; 14s ago
  Process: 2167 ExecStop=/usr/local/sbin/zramsync sync /storage/zram (code=exite
  Process: 2209 ExecStopPost=/usr/local/sbin/zram-config stop (code=exited, stat
[21:46:46] root@devpi:/home/openhabian# zramctl
NAME       ALGORITHM DISKSIZE  DATA COMPR TOTAL STREAMS MOUNTPOINT
/dev/zram3 lzo-rle       500M 40.9M  1.9M  2.3M       4 /opt/zram/zram3
/dev/zram2 lzo-rle       350M 16.3M  6.8K  124K       4 /opt/zram/zram2
/dev/zram1 lzo-rle       500M 16.5M 16.4K  172K       4 /opt/zram/zram1
[21:46:49] root@devpi:/home/openhabian#

(no recent output for journalctl -xu zram-config.service or zramsync.service)
This is why:
[21:50:03] root@devpi:/home/openhabian# zram-config stop
+ ZSHARE=/usr/local/share/zram-config
+ ZLOG=/usr/local/share/zram-config/log/zram-config.log
+ ZDIR=/opt/zram
+ [[ -f /boot/cmdline.txt ]]
+ grep -qs init=/bin/ro-root.sh /boot/cmdline.txt
+ ZEPHEMERAL=false
+ case "$1" in
++ date +%Y-%m-%d-%H:%M:%S
+ echo 'zram-config stop 2020-09-03-21:50:08'
+ tac /tmp/zram-device-list
tac: failed to open '/tmp/zram-device-list' for reading: No such file or directory
+ file=/tmp/zram-device-list.rev
+ read -r line
+ rm -fv /tmp/zram-device-list.rev /tmp/zram-device-list

**Comment by mstormi** [comment]
But this show what you also saw: log says they get deleted but they don't:

```
[22:03:13] root@devpi:/home/openhabian# cat /tmp/zram-device-list
swap            /zram0          zram-config0
dir             /zram1          /var/lib/openhab2/persistence           /persistence.bind
dir             /zram2          /opt/find3/server/main          /find3.bind
log             /zram3          /var/log                /log.bind
[22:03:15] root@devpi:/home/openhabian# /usr/local/sbin/zram-config stop
+ ZSHARE=/usr/local/share/zram-config
+ ZLOG=/usr/local/share/zram-config/log/zram-config.log
+ ZDIR=/opt/zram
+ [[ -f /boot/cmdline.txt ]]
+ grep -qs init=/bin/ro-root.sh /boot/cmdline.txt
+ ZEPHEMERAL=false
+ case "$1" in
++ date +%Y-%m-%d-%H:%M:%S
+ echo 'zram-config stop 2020-09-03-22:03:24'
+ tac /tmp/zram-device-list
+ file=/tmp/zram-device-list.rev
+ read -r line
+ case "$line" in
+ set -- log /zram3 /var/log /log.bind
+ echo 'ztab remove log /zram3 /var/log /log.bind'
+ case "$1" in
+ ZTYPE=log
+ ZRAM_DEV=/zram3
+ TARGET_DIR=/var/log
+ BIND_DIR=/log.bind
+ [[ false == \f\a\l\s\e ]]
+ removeZlog
+ [[ -n '' ]]
+ echo /zram3
++ echo /zram3
++ tr -dc 0-9
+ local DEV_NUM=3
+ [[ -n /var/log ]]
++ dpkg -s nginx
+ [[ -n Package: nginx
Status: install ok installed
Priority: optional
Section: httpd
Installed-Size: 98
Maintainer: Debian Nginx Maintainers <pkg-nginx-maintainers@alioth-lists.debian.net>
Architecture: all
Version: 1.14.2-2+deb10u2
Depends: nginx-full (<< 1.14.2-2+deb10u2.1~) | nginx-light (<< 1.14.2-2+deb10u2.1~) | nginx-extras (<< 1.14.2-2+deb10u2.1~), nginx-full (>= 1.14.2-2+deb10u2) | nginx-light (>= 1.14.2-2+deb10u2) | nginx-extras (>= 1.14.2-2+deb10u2)
Description: small, powerful, scalable web/proxy server
 Nginx ("engine X") is a high-performance web and reverse proxy server
 created by Igor Sysoev. It can be used both as a standalone web server
 and as a proxy to reduce the load on back-end HTTP or mail servers.
 .
 This is a dependency package to install either nginx-full (by default),
 nginx-light or nginx-extras.
Homepage: https://nginx.net ]]
++ systemctl is-active nginx.service
+ [[ -n active ]]
+ systemctl stop nginx.service
++ systemctl is-active rsyslog.service
+ [[ -n active ]]
+ systemctl stop rsyslog.service
+ umount --verbose /var/log/
+ umount --verbose --lazy /var/log/
+ mergeOverlay
+ [[ -n /zram3 ]]
+ umount --verbose /opt/zram/zram3/
+ umount overlay3
+ rm -rfv /opt/zram/zram3
+ [[ -n /log.bind ]]
+ umount --verbose /opt/zram/log.bind/
+ rm -rfv /opt/zram/log.bind
++ dpkg -s nginx
+ [[ -n Package: nginx
Status: install ok installed
Priority: optional
Section: httpd
Installed-Size: 98
Maintainer: Debian Nginx Maintainers <pkg-nginx-maintainers@alioth-lists.debian.net>
Architecture: all
Version: 1.14.2-2+deb10u2
Depends: nginx-full (<< 1.14.2-2+deb10u2.1~) | nginx-light (<< 1.14.2-2+deb10u2.1~) | nginx-extras (<< 1.14.2-2+deb10u2.1~), nginx-full (>= 1.14.2-2+deb10u2) | nginx-light (>= 1.14.2-2+deb10u2) | nginx-extras (>= 1.14.2-2+deb10u2)
Description: small, powerful, scalable web/proxy server
 Nginx ("engine X") is a high-performance web and reverse proxy server
 created by Igor Sysoev. It can be used both as a standalone web server
 and as a proxy to reduce the load on back-end HTTP or mail servers.
 .
 This is a dependency package to install either nginx-full (by default),
 nginx-light or nginx-extras.
Homepage: https://nginx.net ]]
++ systemctl is-active nginx.service
+ [[ -n inactive ]]
+ systemctl stop nginx.service
++ systemctl is-active rsyslog.service
+ [[ -n active ]]
+ systemctl stop rsyslog.service
+ echo 3
/usr/local/sbin/zram-config: line 188: echo: write error: Device or resource busy
+ zramctl -r /dev/zram3
+ return 1
+ read -r line
+ case "$line" in
+ set -- dir /zram2 /opt/find3/server/main /find3.bind
+ echo 'ztab remove dir /zram2 /opt/find3/server/main /find3.bind'
+ case "$1" in
+ ZTYPE=dir
+ ZRAM_DEV=/zram2
+ TARGET_DIR=/opt/find3/server/main
+ BIND_DIR=/find3.bind
+ [[ false == \f\a\l\s\e ]]
+ removeZdir
+ echo /zram2
++ echo /zram2
++ tr -dc 0-9
+ local DEV_NUM=2
+ [[ -n /opt/find3/server/main ]]
+ umount --verbose /opt/find3/server/main/
+ mergeOverlay
+ [[ -n /zram2 ]]
+ umount --verbose /opt/zram/zram2/
+ umount overlay2
+ return 1
+ read -r line
+ case "$line" in
+ set -- dir /zram1 /var/lib/openhab2/persistence /persistence.bind
+ echo 'ztab remove dir /zram1 /var/lib/openhab2/persistence /persistence.bind'
+ case "$1" in
+ ZTYPE=dir
+ ZRAM_DEV=/zram1
+ TARGET_DIR=/var/lib/openhab2/persistence
+ BIND_DIR=/persistence.bind
+ [[ false == \f\a\l\s\e ]]
+ removeZdir
+ echo /zram1
++ echo /zram1
++ tr -dc 0-9
+ local DEV_NUM=1
+ [[ -n /var/lib/openhab2/persistence ]]
+ umount --verbose /var/lib/openhab2/persistence/
+ umount --verbose --lazy /var/lib/openhab2/persistence/
+ mergeOverlay
+ [[ -n /zram1 ]]
+ umount --verbose /opt/zram/zram1/
+ umount overlay1
+ return 1
+ read -r line
+ case "$line" in
+ set -- swap /zram0 zram-config0
+ echo 'ztab remove swap /zram0 zram-config0 '
+ case "$1" in
+ ZTYPE=swap
+ ZRAM_DEV=/zram0
+ LABEL=zram-config0
+ removeZswap
++ echo /zram0
++ tr -dc 0-9
+ local DEV_NUM=0
+ swapoff /dev/zram0
+ echo 0
+ zramctl -r /dev/zram0
+ return 1
+ read -r line
+ rm -fv /tmp/zram-device-list.rev /tmp/zram-device-list
[22:03:25] root@devpi:/home/openhabian# zramctl
NAME       ALGORITHM DISKSIZE  DATA COMPR TOTAL STREAMS MOUNTPOINT
/dev/zram3 lzo-rle       500M 22.9M  1.5M  1.9M       4
/dev/zram2 lzo-rle       350M 16.3M  6.8K  108K       4
/dev/zram1 lzo-rle       500M 16.5M 15.1K  156K       4
[22:03:27] root@devpi:/home/openhabian#
```

**Comment by ecdye** [comment]
Yes, I have observed that as well. For the log mount I noticed that the only thing keeping it from unmounting and resetting properly was that `unattended-upgrades` was still trying to access it so stopping that with `systemctl stop unattended-upgrades.service` allowed it to reset. The others I am still searching for a cause.

**Comment by mstormi** [comment]
Before latest changes I used to see a *single* mount to remain only I think it was the log one.
How about `Conflicts=unattended-upgrades.services` in zramsync.service as a fix? (or vice versa ? need to read systemd docs again)

**Comment by mstormi** [comment]
I wonder what about the rest to access /var/log: openhab2 itself, frontail, mosquitto, ...
zram-config stop tries to unmount and if it fails, tries *lazy* unmounting it.

**Comment by ecdye** [comment]
I think that the rest are not accessing it after we unmount and are working as expected. I think that conflicts would probably be sufficient for now. If we run into issues with the others then we can add cases for them. I'm not sure why the other mounts, specifically the openhab2 persistence one are not being removed and I am almost certain it is not because openhab is still running because even after manually stopping it and trying to remove the device it would not work.

**Comment by mstormi** [comment]
Did you try to manually remove a zram device ?
Do you use anything but mapdb for persistence ?
You could use `lsof `or `fuser -c` to find out about processes that still have files open with a specific directory.

**Comment by ecdye** [comment]
> Did you try to manually remove a zram device ?

yes

> Do you use anything but mapdb for persistence ?

Nothing at all, I just use test files when testing zram so it should not even be accessing that folder at all.

> You could use `lsof `or `fuser -c` to find out about processes that still have files open with a specific directory.
> EDIT: I just tried but it shows me a huge amount incl. PID 1. No I don't think that helps.

Yep I tried that, it was how I found `unattended-upgrades` was still using the log mount.

**Comment by mstormi** [comment]
I added the conflicts: incl. after: to zramsync.service in openhabian-zram repo

**Comment by ecdye** [comment]
I tried killing samba but it still didn't work. I haven't tried anything with the mounts. Any success on your end?

**Comment by mstormi** [comment]
no none

**Comment by mstormi** [comment]
latest Conflicts: addition seems to have broken reliable startup again, see forum link
(not guaranteed it was because of this change, nevertheless I think we should retract it. If unattended-upgrades takes loooooooong to finish that's a problem. I suggest we rather complete remove that "service" wdyt?

**Comment by ecdye** [comment]
Agreed I don't think that `unattended-upgrades` is really that important and also makes the user have less control over their system and it's current setup.

**Comment by mstormi** [comment]
I've removed Conflicts: and After=unattended ... again from openhabian-zram repo.
I'll also add a systemctl mask unattended-upgrades.service. Just need to find the proper place to do that, maybe in zram install routine.

**Comment by mstormi** [comment]
ok, is there anything left we want (dare?) to change about zram ?
stop-start-stop-... still isn't ideal but I'd question that we manage to fully resolve that.

**Comment by ecdye** [comment]
Other than hope that someday someone far smarter than us creates a less hacky tool to do the job? Other than that no, I think we are done for the moment.

**Comment by mstormi** [comment]
ok then ;-)

**Comment by mstormi** [comment]
> I wonder what about the rest to access /var/log: openhab2 itself, frontail, mosquitto, ...

Looking after #316, I came to think that to run frontail possibly results in a lot of open files (because of the nested structure of node.js and its modules)
