### ISSUE TITLE
smbd startup errors

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1079]
journalctl -xu smbd gives

Aug 07 17:38:01 openhab systemd[1]: /lib/systemd/system/smbd.service:9: PIDFile= references path below legacy directory /var/run/, updating /va
Aug 07 17:38:01 openhab systemd[1]: /lib/systemd/system/nmbd.service:9: PIDFile= references path below legacy directory /var/run/, updating /va

=> use
PIDfile=smbd.pid
RuntimeDirectory=samba

**Comment by ecdye** [comment]
If it is not an urgent issue I can work on a fix in #1055.

**Comment by mstormi** [comment]
just writing down things I find along the way

not urgent but no please not in 1055, have one PR per issue where possible

**Comment by mstormi** [comment]
seems that's a Raspbian problem we would need to fix by something like

sed -iE 's/^PIDFile/RuntimeDirectory=samba\\nPIDFile=smbd.pid/g'


(just sed does not take the \n ?)
