### ISSUE TITLE
openhabianpi-ua-netinst-20170218 has no pi user

### ISSUE THREAD

**Issue by aness-github** [openhab/openhabian#108]
Fresh install using openhabianpi-ua-netinst-20170218-git11d8ebc and RPI3 results in an install without a pi user. 

Looking at the passwd file I did find the openhabian user, but this user seems to be undocumented.

**Comment by ThomDietrich** [comment]
Undocumented? I'm curiously surprised by that 😄 

* https://github.com/openhab/openhabian/releases/tag/v1.1
* http://docs.openhab.org/installation/openhabian.html#raspberry-pi
* https://community.openhab.org/t/openhabian-hassle-free-rpi-image/13379/736
* https://community.openhab.org/t/openhabian-hassle-free-rpi-image/13379/731

**Comment by aness-github** [comment]
Ack, I've clearly been blind and/or reading outdated docs.
