### ISSUE TITLE
build.bash no longer runs without superuser permissions

### ISSUE THREAD

**Issue by holgerfriedrich** [openhab/openhabian#1085]
Building the image now requires root permissions. This is due to use of `parted` command during image grow.

run this command as user without superuser permissions.
`./build.bash rpi`

>2020-08-10_00:31:31_CEST [openHABian] Growing root partition of the image by 300 MB... 
./build.bash: line 163: parted: command not found

When I change `parted` to `/sbin/parted` it still fails, now missing `dmidecode`. Seems parted is using this command even when working with file devices, https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=905144

We should find a solution for this.

**Comment by mstormi** [comment]
Sounds like differences of your build platform so I'' m wary to fiddle with build.bash (you know it better than me anyway)
You could add /sbin to your path. Eventually chmod u+s /sbin/parted on your box?

Mine's not working without root either, saying
[11:15:20] openhabian@devpi:~/openhabian$ ./build.bash rpi
2020-08-10_11:15:38_CEST [openHABian] This script will build the openHABian image file.
2020-08-10_11:15:38_CEST [openHABian] Hardware platform: Raspberry Pi (rpi)
2020-08-10_11:15:38_CEST [openHABian] Checking prerequisites...
2020-08-10_11:15:38_CEST [openHABian] For use with Docker, this script must be run as root
[11:17:34] openhabian@devpi:~/openhabian$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games

**Comment by holgerfriedrich** [comment]
Not sure if `parted` is a good solution at all (for the non-root usecase). Running parted with path does not help as well, see the part on `dmidecode` above....

**Comment by mstormi** [comment]
Then why don't you use sudo/root as well for the time being? I don't want to revamp all that stuff just for this minor issue, plus I'm sure there's solution to that, too.

BTW there's an "is_pi" in L270 that's why the output on my machine.
Not sure if we should keep that.
