### ISSUE TITLE
Manually installing openhabian: useradd, etc-dir & setcap issues

### ISSUE THREAD

**Issue by Urmel** [openhab/openhabian#109]
I just installed openhabian manually on a qemu-virtualized raspian image (which might have nothing to do with the issue). What I did...

Followed the instruction on the page http://docs.openhab.org/installation/openhabian.html under "Manual Setup":
```
sudo git clone https://github.com/openhab/openhabian.git /opt/openhabian
sudo ln -s /opt/openhabian/openhabian-setup.sh /usr/local/bin/openhabian-config
sudo openhabian-config
```
**(actually the sudo part for the second line was missing in the instructions)**

In the config interface, I subsequently started the setup tasks, starting from the top...
- 01 Update
- 02 Upgrade System
- 10 Basic Setup
- 11b Oracle Java

During these tasks, I receive multiple multiple errors, which can be seen in the log below along with what I did to "fix it". As I'm no expert, the fixes might as well be plain wrong :)

Excerpt from the log:
> 2017-03-12_10:57:32_CET [openHABian] Applying multiple useful system settings (permissions, ...)..._
> $ adduser openhab dialout
> adduser: The user `openhab' does not exist.
> 
> $ adduser openhab tty
> adduser: The user `openhab' does not exist.
> 
> $ adduser pi openhab
> adduser: The group `openhab' does not exist.
> 
> $ adduser pi dialout
> The user `pi' is already a member of `dialout'.
> 
> $ adduser pi tty
> Adding user `pi' to group `tty' ...
> Adding user pi to group tty
> Done.
> 
> $ setcap cap_net_raw,cap_net_admin=+eip cap_net_bind_service=+ep /usr/bin/java
> Failed to set capabilities on file `/usr/bin/java' (Invalid argument)
> The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file
> 
> $ chown -R openhab:pi /opt /etc/openhab2
> chown: invalid user: ‘openhab:pi’
> 
> $ chmod -R g+w /opt /etc/openhab2
> chmod: cannot access ‘/etc/openhab2’: No such file or directory
> OK
> _2017-03-12_10:58:50_CET [openHABian] Preparing and Installing Oracle Java 8 Web Upd8 repository...

**Useradd issues**
I notes that the line to create the openhab user are commented out in the openhab-config script (method openhab2_user() ) and corrected with the following commands:
```
sudo adduser --system --no-create-home --group --disabled-login openhab
sudo adduser openhab dialout
sudo adduser openhab tty
sudo adduser pi openhab
sudo adduser pi dialout
```

**/etc/openhab2 not created**
As with above log, it can be seen that the directory /etc/openhab2 is missing.

Correction:
```
sudo mkdir /etc/openhab2
sudo chown -R openhab:pi /opt /etc/openhab2
sudo chmod -R g+w /opt /etc/openhab2
```

**Setcaps Issue**
As far as I understand before the Java install, setting capabilities with buggy arguments for a symlink file is tried.

Correction (after Java install):
```
sudo setcap cap_net_admin=+eip /usr/lib/jvm/java-8-oracle/jre/bin/java
sudo setcap cap_net_bind_service=+ep /usr/lib/jvm/java-8-oracle/jre/bin/java
sudo setcap cap_net_raw=+eip /usr/lib/jvm/java-8-oracle/jre/bin/java
```

**Comment by ThomDietrich** [comment]
Hello @Urmel,
these errors can be expected the if you run basic setup in the beginning because neither Java nor openHAB are installed yet. My suggestion in the moment would be to run Basic Setup once in the beginning and after all other steps.
Of course I can see how this is not ideal and I was thinking to restructure the menu. Suggestions are welcome!

**Comment by Urmel** [comment]
Hi @ThomDietrich,
if its really not a must to have these things setup before Java and openHAB, just split the item and have a "Setup Preparation" and a "Setup Finalization" (or something like it).
It's for the unexperienced user just easy to click 1,2,3,4 ... :)
Thx.

**Comment by ThomDietrich** [comment]
Basic Setup was originally intended for an upgrade of the existing system. Only later I abused it for manual fresh setups. 
I've just released Version 1.2 of openHABian. The next version will concentrate on menu structure!

**Comment by ThomDietrich** [comment]
One small step: Before setting permissions I'm now checking of openHAB has previously been installed.

**Comment by ThomDietrich** [comment]
Hey @Urmel, if you are still with us and can spare the time a new try would be interesting. I've restructured the menu. Let me know of your findings!
