### ISSUE TITLE
Thare is no default back-up folder

### ISSUE THREAD

**Issue by MORD0R** [openhab/openhabian#1094]
## Issue information:
I did a fresh install of openhabian.

I had to make a back-up first. So the folder "back-up" is created and run fix permisions. Or else i could not move my back-up to the pi
This is not very nooby friendly.

I expected a folder back-up so i  could move  the back-up to the pi. And run the back-up tool.

## System information:
Pi 4 
`cat /etc/os-release` and `uname -m`.

**Comment by ecdye** [comment]
That is a openHAB issue. There is no need for us to do that on our end. Try raising this issue in openHAB-core.

**Comment by mstormi** [comment]
Frankly I don't even understand what you did and expect to happen. That's nothing we can comment or even work on.
Please open a thread on the community forum and take care of https://community.openhab.org/t/how-to-ask-a-good-question-help-us-help-you/58396 .

**Comment by ecdye** [comment]
He's talking about the folder where openHAB configuration backups are stored.
