### ISSUE TITLE
Unable to setup nginx reverse proxy for localhost w/o public ip/domain

### ISSUE THREAD

**Issue by roberlax** [openhab/openhabian#1096]
setup reverse proxy fails with openhabian-config, because it tries to get a letsencrypt certificate even if  the proxy should be installed for localhost with self signed certificates.

I think the root case is here:
https://github.com/openhab/openhabian/blob/38af6f0e9fdbe8b368d154f66891be2eb6ae808b/functions/packages.bash#L612

Removing this line fixed the issue for me.

**Comment by ecdye** [comment]
@roberlax Sorry for the delay, you are correct that line should be removed. @mstormi You are correct that was unintentionally changed during the rewrite. I'm issuing a patch now.

Thank you all for your patience with me I completely forgot to look into this until now.
