### ISSUE TITLE
HM-MOD-RPI-PCB GPIO access not working for Homegear

### ISSUE THREAD

**Issue by harabeck** [openhab/openhabian#1097]
## Issue information:
Hardware wise BidCos RF Module (HM-MOD-RPI-PCB) is simply connected to the UART (RX - GPIO15, TX - GPIO14) which is provided by dtoverlay=miniuart-bt in /boot/config.txt
and the ReSeT is connected to GPIO18 on the Raspberry PI3 and probably 4 as well . The GPIO18 causes all the trouble.

## Debug information:
https://community.openhab.org/t/hm-mod-rpi-pcb-raspberry-pi-4/84576
https://forum.homegear.eu/t/openhabian-homegear-fehler-could-not-connect-to-socket-permission-denied/3609/30

## System information:
RaspBerry Pi 3 + HM-MOD-RPI-PCB
originally everything worked fine with Openhab installation 2.5.4 until the update to 2.5.7
I tried the Strech and Buster version.
openhabianpi-raspbian-201804031720-gitdba76f6-crc9e93c3eb.img.xz
openhabian-pi-raspbian-201908050414-gitca0976f-crc6a66b5a1.img.xz

**Comment by xasz** [comment]
I tried setting up the permissions as you told, and the problem troubles more users with the HM-MOD-RPI-PCB going to a newer openhabian version. For now i did not find a solution.

**Comment by fmeies** [comment]
After updating to openHABian Buster, I had the same issues with my HM-MOD-RPI-PCB. From my point of view, this is not an ownership or permission issue since I was perfectly able to export gpio18 as user homegear manually. The problem was the missing initialization of gpio18. The [homegear docu advises](https://doc.homegear.eu/homegear/installation.html) to add this to `/etc/systemd/system/homegear.service`: 
```
ExecStartPre=/usr/bin/gpio export 18 out
ExecStop=/usr/bin/gpio unexport 18
```
Maybe _Fix permissions_ should add these lines to `homegear.service` automatically?

**Comment by mstormi** [comment]
I could add it to homegear.service.

However, even with the package from homegear install docs installed, /usr/bin/gpio does not exist on Raspbian.
Can you do `dpkg -S /usr/bin/gpio` ?

**Comment by fmeies** [comment]
Sorry, I forgot to mention. The `wiringpi` package needs to be installed. Please note that in the homegear documentation, gpio17 is also exported/unexported but since this doesn't seem to be required for my HM-MOD-RPI-PCB, I didn't add the respecting lines to my `homegear.service`

**Comment by mstormi** [comment]
I'm adding the `wiringpi` package and changes to `homegear.service` but note this crappy device is not supported for openHABian.
I don't own it so cannot do proper testing, and it is a big risk and PITA as it requires so many changes to system fundamentals.

And next time open a proper request please. Follow-ups on already closed ones (incl. this) will be ignored.

**Comment by fmeies** [comment]
Thanks. Btw: HM-MOD-RPI-PCB might not be supported by openHABian but I don't consider the module itself to be crappy. It has been working perfectly fine for me (and others) for many years. 😃

**Comment by mstormi** [comment]
Only as long as you stay in the HM world. But the purpose of openHABian is not to support HM or homegear.
The module is a PITA to support from an OS POV, and interferes with non-HM hardware. Any CUL is a better design.
