### ISSUE TITLE
package whiptail may be missing and hindering manual installation

### ISSUE THREAD

**Issue by Urmel** [openhab/openhabian#110]
In openhab-config, there is a query for the username commonly used to log in. The command to input the username uses the program "whiptail" for inputting, if the package "whiptail" is not installed on the system, the input will not take place at all and the user is just confronted with an error message

> root@...:~# openhabian-config
2017-03-15_21:52:24_UTC [openHABian] Checking for root privileges... OK
2017-03-15_21:52:24_UTC [openHABian] Setting up and loading configuration file '/etc/openhabian.conf' in manual setup... FAILED
2017-03-15_21:52:24_UTC [openHABian] Error: The provided user name is not a valid system user. Please try again. Exiting ...

After installing package "whiptail", the configuration starts as expected.

Issue encountered while manually installing openhab according to instructions under http://docs.openhab.org/installation/openhabian.html#manual-setup on a Debian LXC container.

**Comment by ThomDietrich** [comment]
🤕 there is a [function for that](https://github.com/openhab/openhabian/blob/master/openhabian-setup.sh#L157)... which is called after the configuration file part ^^

**Comment by ThomDietrich** [comment]
Fixed in https://github.com/openhab/openhabian/commit/d12d3711ab67ada1fc1a459e6ffae3c8558a1797
