### ISSUE TITLE
reorder ztab, adjust FIND install

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1100]
We need `RequireMountsFor=/opt/zram/zramX/upper` in zramsync.service

Reorder ztab so #1 is /var/log, #2 is /var/lib/openhab2/persistence, and #3 is /opt/find3/server/main
Adjust find3_setup() to reflect and add another line RequireMountsFor=/opt/zram/zram3/upper if FIND3 is installed

See also https://github.com/mstormi/openhabian-zram/pull/5#discussion_r477330296

**Comment by ecdye** [comment]
Should we leave the the disabled jsondb line in ztab? I can think of many ways that a user enabling that would lead to issues. Either we should enable it by default or remove it. 

@mstormi thoughts.

**Comment by mstormi** [comment]
remove it
