### ISSUE TITLE
Running apt-update takes very long time

### ISSUE THREAD

**Issue by TheSleepySlee** [openhab/openhabian#1101]
## Issue information:
Trying to run apt update to update system. 

## Debug information:
[23:09:59] root@openhab:~# apt update
Hit:1 http://ftp.fr.debian.org/debian buster InRelease
Hit:2 http://ftp.fr.debian.org/debian buster-updates InRelease                                                                                                                           
Hit:3 http://security.debian.org buster/updates InRelease                                                                                                                                                             
Hit:4 https://deb.nodesource.com/node_10.x buster InRelease                                                                                                                                                           
Hit:5 https://packages.grafana.com/oss/deb stable InRelease                                                                                                                                                 
Hit:6 https://repos.influxdata.com/debian buster InRelease                                
Ign:7 https://dl.bintray.com/openhab/apt-repo2 stable InRelease     
Get:8 https://dl.bintray.com/openhab/apt-repo2 stable Release [6 051 B]
Fetched 6 051 B in 1s (7 733 B/s)      
Reading package lists... 2%

## System information:
I have fiber connection. Trying to run apt update. Takes more than 1 hour. CPU Load goes very high.
Running openhabian on LXC running on proxmox. Debian buster x86_64.
Other LXC work fine.

**Comment by TheSleepySlee** [comment]
When commenting first line of /etc/apt/sources.list, I am getting this warning:
`
W: Ignoring translated description fr LC_ALL=fr_FR.UTF-8 LANG=fr_FR.UTF-8
`

I have tried modifying locale to get correct formatting in openhab UIs, seems this is causing issues.

**Comment by TheSleepySlee** [comment]
Fixed in /etc/environment. Sorry for disturb.
Should anything be set in openhabian.conf for locales?

**Comment by ecdye** [comment]
First of all, you should not be using the root user. Try updating your packages using `openhabian-config` menu option 02 as that is the recommended way to update packages.

Also please keep on topic, I fail to see why locale has anything to do with updating packages.

**Comment by mstormi** [comment]
... or why you think this is openHABian that caused it.
As you're running virtualized you must have installed the base OS yourself and if that hangs - well, it's the base OS that hangs then, not openHABian. But that we're neither responsible for nor could we really do anything about it.
Will close since you said you fixed it yourself.

**Comment by TheSleepySlee** [comment]
@ecdye I changed the locale in debian because the menus were displaying strange characters in openhab UIs. Since doing so, it was almost impossible to apt update. I don't remember how the openhabian is done wrt locale, maybe this could be improved.

@mstormi you are true. I will have a closer look for local config in openhabian before posting next time. thanks for closing.
