### ISSUE TITLE
FIND3 issues

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1108]
```
+ echo -n '2020-09-01_22:35:10_CEST [openHABian] Adding FIND3 to ZRAM... '
2020-09-01_22:35:10_CEST [openHABian] Adding FIND3 to ZRAM... + cond_redirect sed -i -e '/^RequiresMountsFor=/ s/$/ /opt/zram/zram3/upper/' /etc/systemd/system/zramsync.service
+ [[ -n '' ]]
+ echo -e '\n\033[90;01m$ sed -i -e /^RequiresMountsFor=/ s/$/ /opt/zram/zram3/upper/ /etc/systemd/system/zramsync.service \033[39;49;00m'

$ sed -i -e /^RequiresMountsFor=/ s/$/ /opt/zram/zram3/upper/ /etc/systemd/system/zramsync.service
+ sed -i -e '/^RequiresMountsFor=/ s/$/ /opt/zram/zram3/upper/' /etc/systemd/system/zramsync.service
sed: -e expression #1, char 29: unknown option to `s'
+ return 1
+ echo 'FAILED (zramsync service)'
FAILED (zramsync service)
```

**Comment by mstormi** [comment]
where does find3server actually log to ?

**Comment by mstormi** [comment]
it doesn't work end2end and I'm having problems troubleshooting:

There's at least 2 issues left:
1) where's the log ? I can start find3server manually to see output but no log
2) on fresh install, the password to use should be used from /etc/default(find3server, not statically from /etc/systemd/system/find3server.service

**Comment by ecdye** [comment]
I have some extra SD cards and a SD reader on the way. I will set up a new Dev machine and test a lot of the most recent changes and this when they get here.

**Comment by ecdye** [comment]
> 4. on fresh install, the password to use should be used from /etc/default(find3server, not statically from /etc/systemd/system/find3server.service

I believe that it will take the values in the Default file over what it put in the service if they differ, however I may be wrong. 

 > starts on port 8003
Will interfere with nginx if that is on => always start find3server on 8005 instead (nginx always maps there)

What do you mean, why is nginx mapping there? HTTPS port for openHAB should be 8443

**Comment by mstormi** [comment]
> I believe that it will take the values in the Default file over what it put in the service if they differ, however I may be wrong.

Installation sets values in both, find3server.service and /etc/default/find3server. The latter however is ignored. That we should change.

I just tried to replicate on a fresh install but that failed to install FIND3 giving:
```
Processing triggers for systemd (241-7~deb10u4+rpi1) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for libc-bin (2.28-10+rpi1) ...
+ return 0
+ cond_redirect python3 -m pip install cython --install-option=--no-cython-compile
+ [[ -n '' ]]
+ echo -e '\n\033[90;01m$ python3 -m pip install cython --install-option=--no-cython-compile \033[39;49;00m'

$ python3 -m pip install cython --install-option=--no-cython-compile
+ python3 -m pip install cython --install-option=--no-cython-compile
/usr/bin/python3: No module named pip
+ return 1
+ echo 'FAILED (cython)'
FAILED (cython)
+ return 1
+ '[' 1 -ne 0 ']'
+ whiptail --msgbox 'There was an error or interruption during the execution of:\n  "20 | Optional Components"\n\nPlease try again. 
```


> > starts on port 8003
> > Will interfere with nginx if that is on => always start find3server on 8005 instead (nginx always maps there)
> 
> What do you mean, why is nginx mapping there? HTTPS port for openHAB should be 8443

You're right I was mistaken. 
A fresh install does not do what I do so FIND can be accessed on its default 8003 but not from the outside
(unless you add port forwarding in router and nginx).
I got confused by looking at my dev + prod machines:
As I want to be able to also connect to the dashboard or for learning purposes from the outside (Internet), I run access
through nginx so I changed FIND to some other port (8005) and nginx exposes 8003 to the outside while internally connecting to FIND's 8005.
FIND uses 8003 by default (or today: by explicitly calling it with 8003 which is the default so could be omitted as well).
But I wouldn't think a normal user would need to run FIND through their firewall so we should not copy my personal setup.
So forget about this point on my list.

**Comment by ecdye** [comment]
I can add python pip to the install prefetch and that should solve it.

**Comment by ecdye** [comment]
I think everything is working now.

**Comment by mstormi** [comment]
yes (didn't test but no need it's clear from the PR)
