### ISSUE TITLE
Install Graphical UI (window manager)

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhabian#112]
Either as an optional component or as part of docs. Should still be discouraged.

**Comment by ThomDietrich** [comment]
Confirmed solution: https://community.openhab.org/t/does-openhabian-offer-more-than-a-command-line/27524/5

@kubawolanin any opinion on this topic? Mine is here: https://community.openhab.org/t/openhabian-hassle-free-openhab-setup/13379/936

**Comment by kubawolanin** [comment]
My opinion is aligned with yours, my friend ;-) 
I wouldn't use any GUI for system like openHABian. SSH all the way! 👍 
Therefore, I don't think it's something crucial.

**Comment by ThomDietrich** [comment]
I chose documentation ;)
