### ISSUE TITLE
installation fail, bug ?

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1123]
See https://community.openhab.org/t/zram-install-fails/104939/9

I'd still think he has an Internet issue but let's see.

On some recent CI run I saw ZRAM didn't compile because of something that changed with a recent kernel (4.19). There's code in the openhabian-zram to distinguish based on kernel version IIRC.
So either code or kernel were old. Sorry  forgot where so I didn't follow up but it makes me wonder if everything's still compiling right in latest openhabian (also when an older image is used?)

**Comment by ecdye** [comment]
No, CI fails were actually because of my changes but I fixed them yesterday.

**Comment by mstormi** [comment]
ok, thanks for checking this out.
