### ISSUE TITLE
missing packages in 6X menu

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1127]
at least missing:

Amanda
FIND

others TBD

**Comment by mstormi** [comment]
On second thought: do we need the 6X menu any more ?
Is there anything being installed on unattended setup we cannot select via menu ?

**Comment by ecdye** [comment]
Only samba, we could move that to menu 1X or 2X though.
I think it would be good to get rid of the 6X menu as it also has become crowded with new options and no longer really displays properly.
