### ISSUE TITLE
Login warning message

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1132]
Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
You have new mail.
Last login: Fri Sep 18 11:27:24 2020 from ::1

Wi-Fi is currently blocked by rfkill.
Use raspi-config to set the country before use.

**Comment by mstormi** [comment]
[12:54:54] openhabian@openhab:~$ rfkill list
0: phy0: Wireless LAN
        Soft blocked: yes
        Hard blocked: no
1: hci0: Bluetooth
        Soft blocked: no
        Hard blocked: no
[12:54:54] openhabian@openhab:~$ rfkill unblock 0
[12:55:42] openhabian@openhab:~$ rfkill list
0: phy0: Wireless LAN
        Soft blocked: no
        Hard blocked: no
1: hci0: Bluetooth
        Soft blocked: no
        Hard blocked: no
[12:55:44] openhabian@openhab:~$

**Comment by ecdye** [comment]
This was a more recent change by default for RPiOS I believe you can actually just use `rfkill unblock wifi` and it will work. I don't see any real harm either way, as it is unblocked as part of the WiFi setup and elsewhere is really not very necessary.

**Comment by mstormi** [comment]
> as it is unblocked as part of the WiFi setup

what about booting from WiFi ?

**Comment by ecdye** [comment]
As part of that process, it checks for and unblocks the wifi. Check `first-boot.bash`

**Comment by mstormi** [comment]
Ah ok. I didn't boot from WiFi and didn't configure to use it either on my test system that's why I'm still seeing it and thought it would apply to others too. So can close.
