### ISSUE TITLE
MQTT binding not visable.

### ISSUE THREAD

**Issue by Rockonit42** [openhab/openhabian#114]
I have loaded up openhabian 1v1 from an image and also installed the Mosquito MQTT broker from the config shell which I have tested on the network and is working fine.
When I install the MQTT binding in the Paper UI it is not visible in the Configuration>Bindings page .
I have also installed the Network Binding which is visible there and items etc.
Have I missed something with the MQTT binding ?

**Comment by ThomDietrich** [comment]
Hello, please be aware that openHABian installs openHAB for you, all further configuration is done just on any other openHAB setup, hence you should ask your question in the community forum.

* http://docs.openhab.org/addons/bindings/mqtt1/readme.html
* https://community.openhab.org/t/mqtt-binding-not-running-in-oh2-paperui-after-install-in-openhabian/21593

Good luck! ;)
