### ISSUE TITLE
Rework openhabian.conf

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1143]
See https://community.openhab.org/t/openhabian-installation-more-detail-needed-on-etc-openhabian-conf-step-of-setup-process/105335
_Unattended_ install on already installed machines is an edge case that was never designed to be universally applicable, it is merely a reusable waste product of the image installer where stuff like user and hostname, SSID and the like MUST be set in one form or another.
So while that guy is somewhat annoying because he expects to get everything detailed and presented upfront but he himself does not give any reasonable information or debug logs about his own system(s), he has somewhat of a point that it should at least be documented what these settings do and - when you _must_ set them.

We should browse the existing settings, in particular the first entries.
Yeah I know this is about the most ancient settings in there, it's about digging through code that we never wrote ourselves thus don't know what the author had in mind and we don't have the time to analyze that for the time being.
Then again I myself had asked that, too. At least for hostname and username.
In particular why set username=openhabian and shortly after username=user ?

**Comment by ecdye** [comment]
No clue, but certainly worth looking into.

**Comment by mstormi** [comment]
I'll try to collect here

wifi_ssid= is used in build.bash but only when not -z (i.e. empty)
timeserver seems not to be used anywhere
timezone *is* used
hostname *is* used to set the hostname, even on manual install when you run openhabian-config unattended
username - tricky see https://github.com/openhab/openhabian/issues/665#issuecomment-522884304
If I understand the code right, the "openhabian" or "pi" (latter on RPi) account will be renamed to"$username" so the user can use that as his account for administration works. Correct ?
userpw is used exactly once in first-boot to provide the initial password (then it's even replaced in openhabian.conf)
