### ISSUE TITLE
Setup of inital influxdb database and InfluxDB users... curl: (7) Failed to connect to localhost port 8086: Connection refused

### ISSUE THREAD

**Issue by joshuakoh1** [openhab/openhabian#1158]
Using the openhabian-config tool to install InfluxDB + Grafana, some issues with setting up table/users.

It sets up the admin account properly but fails at setting up db/users.

```
...

$ systemctl restart influxdb.service
OK Configure InfluxDB admin account... {"results":[{"statement_id":0}]}
{"results":[{"statement_id":0}]}
OK Configure listen on localhost only...
$ sed -i -e /# Determines whether HTTP endpoint is enabled./ { n ; s/# enabled = true/enabled = true/ } /etc/influxdb/influxdb.conf

$ sed -i s/# bind-address = ":8086"/bind-address = "localhost:8086"/g /etc/influxdb/influxdb.conf

$ sed -i s/# auth-enabled = false/auth-enabled = true/g /etc/influxdb/influxdb.conf

$ sed -i s/# store-enabled = true/store-enabled = false/g /etc/influxdb/influxdb.conf

$ systemctl restart influxdb.service
OK Waiting for InfluxDB service... FAILED
Setup of inital influxdb database and InfluxDB users... curl: (7) Failed to connect to localhost port 8086: Connection refused
curl: (7) Failed to connect to localhost port 8086: Connection refused
curl: (7) Failed to connect to localhost port 8086: Connection refused
curl: (7) Failed to connect to localhost port 8086: Connection refused
curl: (7) Failed to connect to localhost port 8086: Connection refused
curl: (7) Failed to connect to localhost port 8086: Connection refused
curl: (7) Failed to connect to localhost port 8086: Connection refused
FAILED Installing Grafana... --2020-09-27 02:41:06--  https://packages.grafana.com/gpg.key
Resolving packages.grafana.com (packages.grafana.com)... 199.232.194.217, 199.232.198.217, 2a04:4e42:4c::729, ...
Connecting to packages.grafana.com (packages.grafana.com)|199.232.194.217|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1694 (1.7K) [application/x-iwork-keynote-sffkey]
Saving to: ‘STDOUT’

-                                                           100%[========================================================================================================================================>]   1.65K  --.-KB/s    in 0s

2020-09-27 02:41:07 (37.0 MB/s) - written to stdout [1694/1694]

OK

...
```
After installation, checked influx for more details.

```
~# influx
Connected to http://localhost:8086 version 1.8.2
InfluxDB shell version: 1.8.2
> auth
username: admin
password:
> show users
user  admin
----  -----
admin true
> show databases
name: databases
name
----
> exit
```

Only admin user exists, openhab/grafana users not created. DBs empty as well.
Repeated installation by purging influxdb and grafana but no difference.

Ubuntu 18.04
openhabian-config [stable]patchday-20200912-805(12917d6)

**Comment by mstormi** [comment]
We don't actively support Ubuntu we just provide openhabian as-is.
But various optional components including InfluxDB are known not to work on Ubuntu so sorry but cannot help you there.

**Comment by joshuakoh1** [comment]
Which distro other than raspbian would have these features out of the box? I run openhabian in a VM so raspbian is not a possibility.

I'm actually perfectly fine with doing manual installation on my own, just that the forums constantly push for people trying to install things on regular linux to just install openhabian.

Unfortunately my experience has been pretty underwhelming with a lot of the addon installers throwing errors with no logs (node red broke as well and samba did not create a default user either). You should probably also edit the docs to say that openhabian isn't stable with Ubuntu so people don't go down the same rabbit hole.

**Comment by mstormi** [comment]
> Which distro other than raspbian would have these features out of the box?

Read the [README](https://github.com/openhab/openhabian/blob/master/README.md). It mentions those issues, doesn't it. Generic Debian should do.

**Comment by mstormi** [comment]
@holgerfriedrich please have a look if you have some spare time

But as mentioned openHABian on Ubuntu is not supported thus closing.

**Comment by joshuakoh1** [comment]
@mstormi I completely understand the need to narrow down distros but the wording of the readme is still ambiguous. The following statements are contradictory. Does this mean that Ubuntu 20.04 (focal) is being actively tested against or does this mean that Ubuntu is completely untested?

"We do not actively support Ubuntu so no promises but we provide code "as-is" that is known to run on there."
"We expect you to use the stable distribution that openHABian testing is based on, 'buster' for Raspberry Pi OS (ARM) and Debian (x86) and 'focal' for Ubuntu (x86) these are."

**Comment by mstormi** [comment]
thanks for the hint, I corrected that.
