### ISSUE TITLE
Problem to complete install, error with tzupdate

### ISSUE THREAD

**Issue by ghost** [openhab/openhabian#116]
Hi, i have a problem to complete install on Raspberry pi Zero W, setup timeout on autosetting time zone. The Raspberry is correct connected to wireless network. any idea?

**Comment by ThomDietrich** [comment]
Didn't experience that during my tests. Maybe related to your ISP or location?
You can manually set the timezone before installation: After flashing the image open the file "openhabian.conf" on the sd card and uncomment the timezone parameter. It should work now. 

Would you please help solve this issue by testing tzupdate after the installation was finished? I'D be interested in the exact error message. Here is all you need to know: https://github.com/cdown/tzupdate

**Comment by docbit9** [comment]
before i tried to setting timezone manually but i've not seen (?) comment to line timezone....
With setting timezone manually installation correctly end.

![tzupdate](https://cloud.githubusercontent.com/assets/26510004/24079688/d46ac0fa-0c8d-11e7-9998-b53db8c2463a.PNG)
This is error message on i tried to install tzupdate

**Comment by ThomDietrich** [comment]
Hey @docbit9 are you still seeing the issue? If so please report the error over at https://github.com/cdown/tzupdate

**Comment by EliasGabrielsson** [comment]
Closing this as I guess this was an edge case somehow. Please reopen if problem still exist.
