### ISSUE TITLE
System in read only mode, after fresh install when zram is disabled

### ISSUE THREAD

**Issue by seaside1** [openhab/openhabian#1165]
## Issue information:
1. Fresh openhabian install on rpi3
2. Via menu disable zram
3. Reboot
4. echo "" > /srv/openhab2-conf/test     Result: 
20:09:35] openhabian@xyz:/srv/openhab2-conf$ echo "" > dd
-bash: dd: Read-only file system

**Comment by mstormi** [comment]
What do you mean by "System" in RO mode ? You only show one particular loopback mount unit, what about all the rest ?

`/srv` mounts are designed to work with ZRAM so you must not expect them to work when you disable it (no need for that anyway)

Try replacing `After=` in /etc/systemd/system/srv*.mount by `Wants=`.

**Comment by seaside1** [comment]
You are right. I've used the /srv/ mounts as a working directory. I realize that it's not working anymore to use it that way as per design together with zram. I'll close this bug. The Zram is a good alternative, in my case I have a durable sd-card and perfer to write on that instead of in RAM. I use ZRAM on other installations.

**Comment by mstormi** [comment]
Nonetheless please Try replacing After= in /etc/systemd/system/srv*.mount by Wants= and let me know

**Comment by mstormi** [comment]
I tried Wants= didn't make a difference.
I don't know why they're in RO, but you can do `systemctl restart srv-openhab2*` to get them RW again.
