### ISSUE TITLE
Problem during install on a Raspberry PI 3

### ISSUE THREAD

**Issue by mrerhart** [openhab/openhabian#117]
Hi,

I tried to do an install using this image with the PI connected to the ethernet but it did not complete due to this error.
openhabianpi-ua-netinst-20170317-git5125a3d-crcf1577bcb.img

Validating libbz2-1.0
P: 
Retrieving liblzma5
wget: can't connect to remote host (189.45.5.90): 
Connection timed out
E: 
Couldn't download pool/main/x/xz-utils/liblzma5_5.1.1alpha+20120614-2_armhf.deb!

Oh noes, something went wrong!

You have 10 seconds to hit ENTER to get a shell...

Can you help me?

**Comment by ThomDietrich** [comment]
Hey, this looks like a temporary server problem users encounter rarely. Please just try again. If the problem persists, please use the Raspbian Lite based image, the advantages are described here: https://github.com/openhab/openhabian/releases/tag/v1.2
Please let me know of the outcome. Good luck!

**Comment by mrerhart** [comment]
Hi Thom,

I tried again now but gave it error again, this time to download another file.

I already gave up the Raspbian Lite based image because of another problem, but I'll try again and ask for help around here if it does not work.

Thank you for now.

=================================================
raspbian-ua-netinst
=================================================
Revision git~11d8ebc
Built on Fri Mar 17 16:37:22 UTC 2017
Running on Raspberry Pi version 3
=================================================
https://github.com/debian-pi/raspbian-ua-netinst/
=================================================
Starting HWRNG succeeded!
Copying boot files... OK
=================================================
=== Start executing installer-config.txt. ===
=== Finished executing installer-config.txt. ===
=================================================

Network configuration:
  ip_addr = dhcp
  online_config = 

Waiting for eth0... 
Configuring eth0 with DHCP... 192.168.25.201
Time set using ntpdate to... Mon Mar 20 16:40:53 UTC 2017

Installation started at Mon Mar 20 16:40:37 UTC 2017.


Installer configuration:
  preset = server
  packages = sudo
  mirror = http://mirrordirector.raspbian.org/raspbian/
  release = jessie
  hostname = openHABianPi
  domainname = 
  rootpw = raspbian
  root_ssh_pubkey = 
  disable_root = 1
  username = openhabian
  userpw = openhabian
  user_ssh_pubkey = 
  user_is_admin = 1
  cdebootstrap_cmdline = --flavour=minimal --include=linux-image-rpi2-rpfv,cpufrequtils,kmod,libpam-systemd,rng-tools,fake-hwclock,ifupdown,net-tools,ntp,openssh-server,dosfstools,vim-tiny,iputils-ping,wget,ca-certificates,rsyslog,cron,dialog,locales,less,man-db,isc-dhcp-client,sudo
  boot_volume_label = openHABian
  bootsize = +128M
  bootoffset = 8192
  rootsize = 
  timeserver = 0.pool.ntp.org
  timezone = Etc/UTC
  locales = en_US.UTF-8 de_DE.UTF-8
  system_default_locale = en_US.UTF-8
  cmdline = dwc_otg.lpm_enable=0 console=ttyAMA0,115200 kgdboc=ttyAMA0,115200 console=tty1 elevator=deadline
  usbroot = 
  rootdev = /dev/mmcblk0
  rootpartition = /dev/mmcblk0p2
  rootfstype = ext4
  rootfs_mkfs_options = 
  rootfs_install_mount_options = noatime,data=writeback,nobarrier,noinit_itable
  rootfs_mount_options = errors=remount-ro,noatime
  final_action = reboot
  hardware_versions = 3
  gpu_mem = 

Waiting 5 seconds.....
Waiting for /dev/mmcblk0... OK
Applying new partition table... OK
Initializing /boot as vfat... OK
Copying /boot files in... OK
Initializing / as ext4... OK
Mounting new filesystems... OK
Starting install process...
P: Retrieving Release
P: Retrieving Release.gpg
P: Validating Release
I: Good signature from "Mike Thompson (Raspberry Pi Debian armhf ARMv6+VFP) <mpthompson@gmail.com>"
P: Parsing Release
P: Retrieving Packages.gz
P: Validating Packages.gz
P: Parsing Packages
P: Retrieving gcc-4.9-base
P: Validating gcc-4.9-base
P: Retrieving libgcc1
P: Validating libgcc1
P: Retrieving libc6
P: Validating libc6
P: Retrieving multiarch-support
P: Validating multiarch-support
P: Retrieving libbz2-1.0
P: Validating libbz2-1.0
P: Retrieving liblzma5
P: Validating liblzma5
P: Retrieving libstdc++6
P: Validating libstdc++6
P: Retrieving zlib1g
P: Validating zlib1g
P: Retrieving libapt-pkg4.12
P: Validating libapt-pkg4.12
P: Retrieving gpgv
P: Validating gpgv
P: Retrieving libpcre3
P: Validating libpcre3
P: Retrieving libselinux1
P: Validating libselinux1
P: Retrieving libattr1
P: Validating libattr1
P: Retrieving libacl1
P: Validating libacl1
P: Retrieving tar
P: Validating tar
P: Retrieving dpkg
P: Validating dpkg
P: Retrieving readline-common
P: Validating readline-common
P: Retrieving libtinfo5
P: Validating libtinfo5
P: Retrieving libreadline6
P: Validating libreadline6
P: Retrieving libusb-0.1-4
P: Validating libusb-0.1-4
P: Retrieving gnupg
P: Validating gnupg
P: Retrieving raspbian-archive-keyring
P: Validating raspbian-archive-keyring
P: Retrieving apt
P: Validating apt
P: Retrieving mawk
P: Validating mawk
P: Retrieving base-files
P: Validating base-files
P: Retrieving libdebconfclient0
P: Validating libdebconfclient0
P: Retrieving base-passwd
P: Validating base-passwd
P: Retrieving sensible-utils
P: Validating sensible-utils
P: Retrieving debianutils
P: Validating debianutils
P: Retrieving dash
P: Validating dash
P: Retrieving libncurses5
P: Validating libncurses5
P: Retrieving bash
P: Validating bash
P: Retrieving libgpg-error0
P: Validating libgpg-error0
P: Retrieving libgcrypt20
P: Validating libgcrypt20
P: Retrieving libsystemd0
P: Validating libsystemd0
P: Retrieving bsdutils
P: Validating bsdutils
P: Retrieving perl-base
P: Validating perl-base
P: Retrieving debconf
P: Validating debconf
P: Retrieving libssl1.0.0
P: Validating libssl1.0.0
P: Retrieving openssl
P: Validating openssl
P: Retrieving ca-certificates
P: Validating ca-certificates
P: Retrieving coreutils
P: Validating coreutils
P: Retrieving libcpufreq0
P: Validating libcpufreq0
P: Retrieving lsb-base
P: Validating lsb-base
P: Retrieving cpufrequtils
P: Validating cpufrequtils
P: Retrieving libaudit-common
P: Validating libaudit-common
P: Retrieving libaudit1
P: Validating libaudit1
P: Retrieving libpam0g
P: Validating libpam0g
P: Retrieving init-system-helpers
P: Validating init-system-helpers
P: Retrieving libsemanage-common
P: Validating libsemanage-common
P: Retrieving libsepol1
wget: can't connect to remote host (189.45.5.90): Connection timed out
E: Couldn't download pool/main/libs/libsepol/libsepol1_2.3-2_armhf.deb!

Oh noes, something went wrong!
You have 10 seconds to hit ENTER to get a shell...

**Comment by ThomDietrich** [comment]
You should go with the Rasbian image. It's more reliable. In fact that's why I've introduced it and that's why I'll probably abandon the ua-netinst image soon.

**Comment by ThomDietrich** [comment]
ua-netinst image will be discontinued
