### ISSUE TITLE
ERROR on Logon : Ip = Unable to parse ip . Please debug.

### ISSUE THREAD

**Issue by helmar74** [openhab/openhabian#1171]
## Issue information:
Hi, I set up a new Raspberry Pi (4GB RAM) with openhabian 1.5 
I replaced the SD thru a SSD which is connected to USB3
The RPI 4 is connected to the network and has a manual configured IP adress in /etc/dhcpcd.conf

Everything works so far. But I get the "Ip = Unable to parse ip . Please debug." Error when logging on to the RPI:

```
###############################################################################
###############  openhab #################################################
###############################################################################
##        Ip = Unable to parse ip . Please debug.
##   Release = Raspbian GNU/Linux 10 (buster)
##    Kernel = Linux 5.4.51-v7l+
##  Platform = Raspberry Pi 4 Model B Rev 1.2
##    Uptime = 0 day(s). 0:1:16
## CPU Usage = 0.25% avg over 4 cpu(s) (4 core(s) x 1 socket(s))
##  CPU Load = 1m: 0.56, 5m: 0.21, 15m: 0.08
##    Memory = Free: 3.01GB (80%), Used: 0.77GB (20%), Total: 3.78GB
##      Swap = Free: 1.99GB (100%), Used: 0.00GB (0%), Total: 1.99GB
##      Root = Free: 205.32GB (97%), Used: 5.64GB (3%), Total: 219.93GB
##   Updates = 0 apt updates available.
##  Sessions = 2 session(s)
## Processes = 134 running processes of 32768 maximum processes
###############################################################################
```

If I "update" Firemotd manually in openhabian-config, the IP adress is shown. 
After the next reboot the error ist back!!!

Has anyone an idea, what I can do?

Thanks!

## Debug information:
Please provide all of the output provided by utilizing the `debugmode=maximum`
parameter in the `/etc/openhabian.conf` file. For more information on how to
accomplish this, please see [openhabian-DEBUG.md](https://github.com/openhab/openhabian/blob/master/docs/openhabian-DEBUG.md#create-a-debug-log).

## System information:
Please tell us what OS you are running (Raspberry Pi OS, Debian, Ubuntu), what
HW you are running on (Raspberry Pi, amd64). Also include the output of
`cat /etc/os-release` and `uname -m`.
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"

Linux openhab 5.4.51-v7l+ #1333 SMP Mon Aug 10 16:51:40 BST 2020 armv7l GNU/Linux

**Comment by mstormi** [comment]
This is not a helpline for people who messed up their system on their own.
You obviously did by changing your ip config.
The bad output is generated by FireMotD because. You have to debug that yourself. Don't expect us to.

**Comment by helmar74** [comment]
Thanks for your help
