### ISSUE TITLE
Improve backup to USB device

### ISSUE THREAD

**Issue by holgerfriedrich** [openhab/openhabian#1176]
Apparently there is a way to fill the whole system partition, i.e. the backup was stored to directory `/storage` (which might be the mount point w/o mounded device).
https://knx-user-forum.de/forum/supportforen/openhab/1550022-durch-backup-sd-karte-voll

We should improve checking.

**Comment by mstormi** [comment]
Ahem. Don't quote me in public please, but
https://www.goodreads.com/quotes/177682-programming-today-is-a-race-between-software-engineers-striving-to

What sort of improvement do you mean ?

**Comment by holgerfriedrich** [comment]
Not sure, but either you can select the main partition as backup device or the mount went wrong and backup rsyncs everything to the empty mount point. Maybe we should check for that.

I had no time to look into it, and maybe we just close the issue.  I noticed the post in knx user forum...

**Comment by mstormi** [comment]
> Not sure, but either you can select the main partition as backup device or the mount went wrong and backup rsyncs everything to the empty mount point. Maybe we should check for that.

Code does
`    if ! (mountpoint -q "${syncMount}"); then echo "FAILED (${dest} is not mounted as ${syncMount})"; return 1; fi`
before starting rsync. That'll fail if the mount failed before.

I have no idea how that guy managed to end up like this.

Just an idea, as he wrote he freed 51GB eventually the rsync copied more than just the local filesystem ?
openHABian should be occupying way less than that. But without more info that's useless guessing in the dark.
