### ISSUE TITLE
Pine64 img- NPM not installed fails at Line 70

### ISSUE THREAD

**Issue by Kerr1st** [openhab/openhabian#119]
Hi Love Openhabian!
Received the following 1)**error**: 
2) checked whether _installed_ re-ran install same _error:_
3) Also noticed earlier on in the script:

1) $ apt -y install nodejs 
Reading package lists... Done
Building dependency tree        
Reading state information... Done
nodejs is already the newest version (4.2.6~dfsg-1ubuntu4.1).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

$ npm install -g frontail 
**/usr/local/bin/openhabian-config: line 70: npm: command not found
FAILED (frontail)**

2) _[08:48:59] openhabian@openHABianPine64:/usr/local/bin$ npm -v
-bash: npm: command not found_

3)Get:11 http://ports.ubuntu.com xenial-security InRelease [102 kB]                  
Get:12 http://repos.azulsystems.com/debian stable/main armhf Packages [1,339 B]
_Err:12 http://repos.azulsystems.com/debian stable/main armhf Packages
  Hash Sum mismatch_
Fetched 221 kB in 2s (91.0 kB/s)                            
Reading package lists... Done
E: Failed to fetch http://repos.azulsystems.com/debian/dists/stable/main/binary-armhf/Packages.bz2  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by ThomDietrich** [comment]
Hey, this seems to be related to #118 which was merged only yesterday. Let me look into this this evening.

**Comment by ThomDietrich** [comment]
I've removed frontail from the setup for now. Please try again!

**Comment by Kerr1st** [comment]
Wow! very fast... sorry still same error.... full capture

[11:08:34] openhabian@openHABianPine64:/usr/local/bin$ sudo openhabian-config
2017-03-21_11:19:34_PDT [openHABian] Checking for root privileges... OK
2017-03-21_11:19:34_PDT [openHABian] Loading configuration file '/etc/openhabian.conf'... OK
2017-03-21_11:20:03_PDT [openHABian] Updating myself... OK - Commit history (oldest to newest):


83e9df9 - Remove frontail from unattended installation (8 minutes ago) <Thomas Dietrich> N
 openhabian-setup.sh | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)


openHABian configuration tool successfully updated.
Visit the development repository for more details: https://github.com/openhab/openhabian
You need to restart the tool. Exiting now... 
[11:20:05] openhabian@openHABianPine64:/usr/local/bin$ sudo openhabian-config
2017-03-21_11:20:48_PDT [openHABian] Checking for root privileges... OK
2017-03-21_11:20:48_PDT [openHABian] Loading configuration file '/etc/openhabian.conf'... OK
2017-03-21_11:21:01_PDT [openHABian] Installing basic can't-be-wrong packages (screen, vim, ...)... 
$ apt update 
Hit:1 http://ppa.launchpad.net/longsleep/ubuntu-pine64-flavour-makers/ubuntu xenial InRelease
Hit:2 http://ports.ubuntu.com xenial InRelease                      
Ign:3 http://repos.azulsystems.com/debian stable InRelease          
Ign:4 http://dl.bintray.com/openhab/apt-repo2 stable InRelease                                 
Hit:5 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty InRelease                        
Hit:6 http://repos.azulsystems.com/debian stable Release                                       
Hit:7 http://ports.ubuntu.com xenial-updates InRelease                                         
Get:8 http://dl.bintray.com/openhab/apt-repo2 stable Release [6,050 B]   
Hit:9 http://ports.ubuntu.com xenial-security InRelease                             
Hit:10 https://deb.nodesource.com/node_7.x xenial InRelease
Fetched 6,050 B in 2s (2,418 B/s)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'https://deb.nodesource.com/node_7.x xenial InRelease' doesn't support architecture 'arm64'

$ apt -y install screen vim nano mc vfu bash-completion htop curl wget multitail git bzip2 zip unzip xz-utils software-properties-common man-db whiptail 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
bzip2 is already the newest version (1.0.6-8).
git is already the newest version (1:2.7.4-0ubuntu1).
man-db is already the newest version (2.7.5-1).
screen is already the newest version (4.3.1-2build1).
unzip is already the newest version (6.0-20ubuntu1).
whiptail is already the newest version (0.52.18-1ubuntu2).
xz-utils is already the newest version (5.1.1alpha+20120614-2ubuntu2).
zip is already the newest version (3.0-11).
mc is already the newest version (3:4.8.15-2).
multitail is already the newest version (6.4.2-1build1).
vfu is already the newest version (4.10-1.1build1).
bash-completion is already the newest version (1:2.1-4.2ubuntu1.1).
curl is already the newest version (7.47.0-1ubuntu2.2).
nano is already the newest version (2.5.3-2ubuntu2).
software-properties-common is already the newest version (0.96.20.5).
vim is already the newest version (2:7.4.1689-3ubuntu1.2).
wget is already the newest version (1.17.1-1ubuntu1.1).
htop is already the newest version (2.0.1-1ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
OK
2017-03-21_11:21:18_PDT [openHABian] Installing additional needed packages... 
$ apt update 
Ign:1 http://repos.azulsystems.com/debian stable InRelease
Hit:2 http://repos.azulsystems.com/debian stable Release                                                                     
Ign:3 http://dl.bintray.com/openhab/apt-repo2 stable InRelease                                                               
Get:4 http://dl.bintray.com/openhab/apt-repo2 stable Release [6,050 B]                                                       
Hit:5 http://ppa.launchpad.net/longsleep/ubuntu-pine64-flavour-makers/ubuntu xenial InRelease                                
Hit:7 http://ports.ubuntu.com xenial InRelease                           
Hit:8 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty InRelease  
Hit:9 https://deb.nodesource.com/node_7.x xenial InRelease               
Hit:10 http://ports.ubuntu.com xenial-updates InRelease
Hit:12 http://ports.ubuntu.com xenial-security InRelease
Fetched 6,050 B in 2s (2,802 B/s)                  
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'https://deb.nodesource.com/node_7.x xenial InRelease' doesn't support architecture 'arm64'

$ apt -y install apt-transport-https bc sysstat avahi-daemon python python-pip 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
avahi-daemon is already the newest version (0.6.32~rc+dfsg-1ubuntu2).
bc is already the newest version (1.06.95-9build1).
python is already the newest version (2.7.11-1).
apt-transport-https is already the newest version (1.2.19).
sysstat is already the newest version (11.2.0-1ubuntu0.1).
python-pip is already the newest version (8.1.1-2ubuntu0.4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
OK
2017-03-21_11:21:33_PDT [openHABian] Adding slightly tuned bash config files to system... OK
2017-03-21_11:21:33_PDT [openHABian] Adding slightly tuned vim config file to system... OK
2017-03-21_11:21:33_PDT [openHABian] Downloading and setting up FireMotD... 
$ git clone https://github.com/willemdh/FireMotD.git /opt/FireMotD 
Cloning into '/opt/FireMotD'...
remote: Counting objects: 706, done.
remote: Total 706 (delta 0), reused 0 (delta 0), pack-reused 705
Receiving objects: 100% (706/706), 7.97 MiB | 1.07 MiB/s, done.
Resolving deltas: 100% (397/397), done.
Checking connectivity... done.

$ /bin/bash /opt/FireMotD/FireMotD -S 
OK
bash: line 2: $'\E[90': command not found
--2017-03-21 11:22:03--  https://deb.nodesource.com/setup_7.x
bash: line 2: 01m$: command not found
bash: line 2: 49: command not found
bash: line 2: 00m: command not found
Resolving deb.nodesource.com (deb.nodesource.com)... 52.84.133.65, 52.84.133.9, 52.84.133.202, ...
Connecting to deb.nodesource.com (deb.nodesource.com)|52.84.133.65|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12255 (12K) [text/plain]
Saving to: ‘STDOUT’

-                               100%[=====================================================>]  11.97K  --.-KB/s    in 0.004s  

2017-03-21 11:22:04 (3.30 MB/s) - written to stdout [12255/12255]


## Installing the NodeSource Node.js v7.x repo...


## Populating apt-get cache...

+ apt-get update
Ign:1 http://repos.azulsystems.com/debian stable InRelease
Hit:2 http://repos.azulsystems.com/debian stable Release                                                                  
Ign:3 http://dl.bintray.com/openhab/apt-repo2 stable InRelease                                                               
Get:4 http://dl.bintray.com/openhab/apt-repo2 stable Release [6,050 B]                                                       
Hit:5 http://ppa.launchpad.net/longsleep/ubuntu-pine64-flavour-makers/ubuntu xenial InRelease       
Hit:6 http://ports.ubuntu.com xenial InRelease                           
Hit:7 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty InRelease
Hit:8 http://ports.ubuntu.com xenial-updates InRelease
Hit:10 http://ports.ubuntu.com xenial-security InRelease
Hit:12 https://deb.nodesource.com/node_7.x xenial InRelease
Fetched 6,050 B in 2s (2,579 B/s)
Reading package lists... Done
N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'https://deb.nodesource.com/node_7.x xenial InRelease' doesn't support architecture 'arm64'

## Confirming "xenial" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_7.x/dists/xenial/Release'

## Adding the NodeSource signing key to your keyring...

+ curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
OK

## Creating apt sources list file for the NodeSource Node.js v7.x repo...

+ echo 'deb https://deb.nodesource.com/node_7.x xenial main' > /etc/apt/sources.list.d/nodesource.list
+ echo 'deb-src https://deb.nodesource.com/node_7.x xenial main' >> /etc/apt/sources.list.d/nodesource.list

## Running `apt-get update` for you...

+ apt-get update
Ign:1 http://repos.azulsystems.com/debian stable InRelease
Hit:2 http://repos.azulsystems.com/debian stable Release                                                                     
Ign:3 http://dl.bintray.com/openhab/apt-repo2 stable InRelease                                                               
Get:4 http://dl.bintray.com/openhab/apt-repo2 stable Release [6,050 B]                                                       
Hit:6 http://ports.ubuntu.com xenial InRelease                                                                               
Hit:7 http://ports.ubuntu.com xenial-updates InRelease                   
Hit:8 http://ppa.launchpad.net/longsleep/ubuntu-pine64-flavour-makers/ubuntu xenial InRelease
Hit:9 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty InRelease  
Hit:10 http://ports.ubuntu.com xenial-security InRelease                 
Hit:11 https://deb.nodesource.com/node_7.x xenial InRelease
Fetched 6,050 B in 2s (2,429 B/s)
Reading package lists... Done
N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'https://deb.nodesource.com/node_7.x xenial InRelease' doesn't support architecture 'arm64'

## Run `apt-get install nodejs` (as root) to install Node.js v7.x and npm


$ apt -y install nodejs 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
nodejs is already the newest version (4.2.6~dfsg-1ubuntu4.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

$ npm install -g frontail 
/usr/local/bin/openhabian-config: line 70: npm: command not found
FAILED (frontail)
[11:22:31] openhabian@openHABianPine64:/usr/local/bin$

**Comment by ThomDietrich** [comment]
This seems to be the crux of it all:
```
nodejs is already the newest version (4.2.6~dfsg-1ubuntu4.1).
...
$ npm install -g frontail 
/usr/local/bin/openhabian-config: line 70: npm: command not found
```

A first step in looking into and solving the issue: https://github.com/openhab/openhabian/commit/2b66d31f09d643fcbafc403b0e4a0a312ccfd7ca#diff-cdd86852ccd3c255a7233e741f26a137

**Comment by felixekman** [comment]
@ThomDietrich When might you roll out new pre-compiled images for the Pine64 with all the new great fixes?

**Comment by ThomDietrich** [comment]
Tomorrow 😸

**Comment by EliasGabrielsson** [comment]
Dropped support for pre-built PIN64 installation. Recommendation is to install openHABian on top of Armbian.
