### ISSUE TITLE
[OH3] don't detected

### ISSUE THREAD

**Issue by grzegorz914** [openhab/openhabian#1199]
Hi,

I use openHAB3 branch since I moved to OH3.0 but some tool not working correct like 'Fix permissions'  or 'Backup/Restore', looks like OH3.0 is not detected:

`2020-10-20_09:54:30_CEST [openHABian] Applying file permissions recommendations... FAILED (please execute after openHAB is installed)`

**Comment by mstormi** [comment]
openHABian does not support OH3 yet 
as also noted in the [announcement](https://community.openhab.org/t/openhabian-1-6-released/105938)
