### ISSUE TITLE
Configuration of blinds control system to openhab

### ISSUE THREAD

**Issue by mo802** [openhab/openhabian#1203]
I’m trying to make a smart blinds control system ,i'm using raspberry pi as my home automation server .  i built up my system using esp8266 wifi module and burned the software image to it , then connected it to my servo motor .
Then i checked it using mqtt broker . i published to the topic and it worked well . 
![asd](https://user-images.githubusercontent.com/67571553/96629425-e0196880-1313-11eb-9ef9-b74065743e53.PNG)

After that i tried to configure it to openhab , but it gave me no response .
those are my configuration files :
things file :
![asg](https://user-images.githubusercontent.com/67571553/96629525-0212eb00-1314-11eb-92d3-26215ef14846.PNG)

items file : 
![asf](https://user-images.githubusercontent.com/67571553/96629578-10f99d80-1314-11eb-9b1e-46b329afb412.PNG)

sitemaps file : 
![ash](https://user-images.githubusercontent.com/67571553/96629604-1ce55f80-1314-11eb-8c1b-f38082d2b25c.PNG)
i have no rules file .
i think the problem is in my configuration .i’m trying a week ago but the problem still exists . please help me

**Comment by mstormi** [comment]
You issues are related to your openHAB config and rules but not to openHABian which the OS underneath.

**Comment by mo802** [comment]
yes , i also think so . but i don't know where the problem actually exists . 
do you have any suggestion ?

**Comment by mstormi** [comment]
Please stop misusing this medium. Turn to the forum.

**Comment by mo802** [comment]
ok , thanks .
i'll do
