### ISSUE TITLE
package exists but not in apt ?

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1208]
just to not forget since I stumbled across during my OH3 upgrade tests
Any Debian expert who can explain ?

[12:27:05] root@openHABianDevice:/opt/openhabian# dpkg -s openhab2|head
Package: openhab2
Status: deinstall ok config-files
Priority: optional
Section: java
Installed-Size: 92582
Maintainer: https://community.openhab.org
Architecture: all
Source: openhab2
Version: 2.5.9-1
Config-Version: 2.5.9-1
[12:27:16] root@openHABianDevice:/opt/openhabian# apt --yes remove openhab2
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package 'openhab2' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by ecdye** [comment]
Perhaps you did not read closely enough it says `Status: deinstall ok config-files`

**Comment by mstormi** [comment]
yeah saw that myself meanwhile. Also change openhab_is_installed() to check for that
