### ISSUE TITLE
FireMotD Unable to parse ip

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1213]
on a new box:
[22:52:00] root@openHABianDevice:/opt# ls -l /usr/local/bin/FireMotD /opt/FireMotD/FireMotD
-rwxrwxr-x 1 root root 91170 Oct 23 20:54 /opt/FireMotD/FireMotD
-rwxr-xr-x 1 root root 91170 Oct 23 21:42 /usr/local/bin/FireMotD
On older boxes, these can be different versions which can lead to problems.

Just do not find the reason right now but should be simple
@ecdye Is it the offline prefetched copy in /usr/local/bin ?

**Comment by ecdye** [comment]
It is because I am stroing the source repo in /opt/FireMotD which also has the binary. This was a change from previous version where we used the setup script from the repo. It allows for proper offline installation and update (although rare). The end version that the user gets is in /usr/local/bin

**Comment by mstormi** [comment]
There was some thread on the forum where both existed and had different versions.
Maybe turn /usr/local/bin into a link ?

**Comment by ecdye** [comment]
Nah, that shouldn't happen unless there was an error during upgrade. I would rather stick with the provided install script.

**Comment by mstormi** [comment]
ok then

**Comment by mstormi** [comment]
see https://community.openhab.org/t/unable-to-parse-ip/107165/21
We should ensure to update FM in /opt (as part of apt upgrade ?) and link /usr/... there (as part of openhabian_update() ?)
