### ISSUE TITLE
hassle-free openHABian image fails on network 

### ISSUE THREAD

**Issue by dfletter** [openhab/openhabian#122]
Hi
I tried to install using the easy way on the boot image you gave but no matter what I do, it does not reach the network by itself. I have RPi3 without the z-wave shield installed yet. All the documentation assumes that it will succeed in gaining an ip address and continue so if this is a common error people have, a word about how to go about reconfiguring the Linux to enable the ethernet connection would be helpful. I am not a complete noob but I don't like os config much either.

**Comment by ThomDietrich** [comment]
If your Pi is correctly connected via Ethernet your DHCP server should assign it an IP. An internet connection is needed to succeed with the setup.

How do you know the device "does not reach the network"? You should see a new device called "openHABianPi" in your (router's) DHCP lease table. If that's not the case, maybe the image was not correctly flashed or corrupted during download.

**Comment by Sp4rtan** [comment]
Same for me trying wifi.
There is no way to get a connection.
I followed the Wfifi Setup in the instructions.
Even with static IP an manual wifi connection attempt over iwlist scan with wpa_passphrase I had no luck...
I dont know what else I could do.
Connection via eth0 works fine btw :)

**Comment by ThomDietrich** [comment]
I've just updated the instructions for Wi-Fi based setup and added it to the documentation. My test was successful. I think this should be settled.
