### ISSUE TITLE
WiFi hotspot

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1227]
Can we open a WiFi hotspot on boot when the network does not become active on boot ?
That would bridge the install time gap when there is no Ethernet and user needs to enter WiFi credentials in openhabian.conf before 1st boot. This is a real hassle when installing in some remote location or into someone else's network.
A hotspot provides a solution to this and is therefore becoming a more and more common feature in commercial products.

Let's see if we can find a working script framework that we can integrate rather than program that ourselves.
I'm just installing an Open Source/RPi based wallbox for my EV (electric car) that has this feature built in, maybe we can
extract the code. It's using `hostapd`: https://github.com/snaptec/openWB

Others:
https://www.raspberryconnect.com/projects/65-raspberrypi-hotspot-accesspoints/157-raspberry-pi-auto-wifi-hotspot-switch-internet
https://github.com/billz/raspap-webgui

**Comment by ecdye** [comment]
Do you mean open a locally hosted WiFi hotspot to allow the user to connect and enter WiFi credentials? If not I am confused by your use of the term WiFi hotspot because it would be pointless to create one as the user would not be able to connect to the outside world.

Can you try to clarify?

**Comment by mstormi** [comment]
>  a locally hosted WiFi hotspot to allow the user to connect and enter WiFi credentials?

Exactly. A simple-most web page that does nothing except to list available SSIDs and offers two input fiels for SSID and password.
The openWB I linked to opens this hotspot only when it fails to connect via Ethernet and via WiFi.

**Comment by ecdye** [comment]
Ah, ok. Thanks for clarifying.
