### ISSUE TITLE
OH2 > OH3 update: ability to choose snapshot or milestone build

### ISSUE THREAD

**Issue by eikowagenknecht** [openhab/openhabian#1231]
It would be great if during the installation there would be a possibility too choose whether to update to OH3 Snapshot or OH3 Milestone.

I did this manually by editing the `/etc/apt/sources.list.d/openhab.list` file after the installation.

Also after installation, the menu options to switch branches still refer to openhab2. Can these be used (only text is wrong) or would they cause damage, i.e. downgrade to OH2? This is unclear from the descriptions.

**Comment by mstormi** [comment]
no running snapshots is a feature request and not recommended to people who don't know how to do that on the CLI themselves

which menu options do you mean ?

**Comment by eikowagenknecht** [comment]
I meant these options. What do they do after the OH3 update?

![image](https://user-images.githubusercontent.com/1475672/99155236-709a5d00-26b6-11eb-88ca-6dd3fd27e829.png)

![image](https://user-images.githubusercontent.com/1475672/99155239-72fcb700-26b6-11eb-8b7e-96d3e0f27b4a.png)

I understand that using snapshots is an option for experienced users and I had no major problems finding out how to achieve that using the CLI. But if switching to snapshot is supported for OH2 I thought it would be nice to have it for OH3 as well ;-)

**Comment by mstormi** [comment]
> I meant these options. What do they do after the OH3 update?

Whatever they did before: install the respective OH2 version. I'll add some "2"s.
