### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1257]
see https://github.com/github/renaming/blob/main/README.md

**Comment by mstormi** [comment]
or rename openHAB3 to main ? @ecdye wdyt?

**Comment by ecdye** [comment]
I know that there have been issues with it causing a loss of commit history, and as such I'm inclined to wait and see what thee tools GitHub develops for migration will be as referenced in the document above. 

If they end up never producing them then I would say do it on the openHAB3 branch after making a backup that way it will affect the end user less and we can push an update once all the bugs are sorted out. 

For now, I think that we should wait.

**Comment by mstormi** [comment]
ok makes sense to me. Let's revisit this when Github has come out with something

**Comment by pfink** [comment]
Anyhow, the openHAB3 branch seems to be outdated and could be deleted already, correct?

**Comment by mstormi** [comment]
*cough* NO
It's the new 'master' for OH3 in fact

**Comment by pfink** [comment]
Nevermind, I did read "30 commits behind master", but in fact it was "30 commits ahead of master"  ^^

**Comment by ecdye** [comment]
@mstormi I have created the main branch, I am working on a PR that will finish preparing it to be the main branch.

**Comment by mstormi** [comment]
see https://github.com/orgs/openhab/teams/maintainers/discussions/6
Are you ready to switch ?

**Comment by ecdye** [comment]
Well there is a new github function to automate it. I think that the best way to proceed is to use that and then fix all references from openHAB 3 to main. I'll create a PR that has all the refrences to openHAB3 changed and then once you approve of that I'll Rename the branch and merge the PR right away. Sound good?

<https://github.com/github/renaming>

**Comment by mstormi** [comment]
Just wondering what about our stable/master 2-stage approach for OH3.

If "openHAB3" is the OH3 version of "master" then where's OH3 stable ? Or is it that and "main" is the new OH3 master ?

**Comment by ecdye** [comment]
I think that we no longer maintain a stable OH2 and once the branch has been renamed forward main to stable.

**Comment by mstormi** [comment]
Not a good idea. That would force all users of OH2 stable onto the OH3 branch, effectively breaking their setup unless they migrate to OH3 which they for sure don't want at that stage.

**Comment by ecdye** [comment]
That would work, so instead we would no longer have a stable branch for OH3?

**Comment by mstormi** [comment]
Simply _add_ (not rename) main to become the "new master" for OH3. openHAB3 would then become the stable branch for OH3.

**Comment by ecdye** [comment]
Well then, that adds a lot more complexity as we have to add support for both it and the OH3 branch. Would we want to simply swap master and main in the code to make it so that the master branch is no longer readily accessible but stable is?

That would also help to reduce the amount of re-coding needed and help to speed the transition.
