### ISSUE TITLE
Mosquitto trademark recognition

### ISSUE THREAD

**Issue by mmilinkov** [openhab/openhabian#126]
This is a bit of a nit, but it would be appreciated if the proper trademark recognition was given to Mosquitto in the documentation, and (for example) in the openhabian-config tool. 

Mosquitto is an Eclipse Foundation project, and as such it should be referred to as "Eclipse Mosquitto" at both the first, and the most prominent use of the name in any document or tool. 
https://www.eclipse.org/legal/logo_guidelines.php

Happy to answer any questions.

Thanks for your consideration.

**Comment by ThomDietrich** [comment]
Hello @mmilinkov and thanks for the information. I/We are always trying to play fair and inside the rules and standards in place. I've just updated the wording inside the openHABian Configuration Tool, please let me know if I missed a prominent spot.
I'll leave this issue open, as I did not yet address the [documentation](http://docs.openhab.org/installation/openhabian.html), which I'll have to edit in the next couple of days anyhow.

**Comment by ThomDietrich** [comment]
This should be resolved with https://github.com/openhab/openhabian/commit/c692d448a4c32b91b02f90930ab942f314b6898e
Best regards!

**Comment by mmilinkov** [comment]
Thanks!
