### ISSUE TITLE
minimizing (SD card) writes

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#128]
Hi,
this started off as a discussion on SD card writes and SD corruption.

The current 'move system to USB' menu option will actually rather mislead the average user because he will have read about SD corruption and will likely expect this move to increase availability.
But except in special cases (like a USB HDD), it won't. A USB stick uses the same tech and is as-unreliable as are SD cards.

I'd rather try to enhance the 'time-to-crash' by reducing the number of writes to (default: SD) disk.

My suggestion would roughly be as follows:
Create dirs `/volatile/essential` and `/volatile/expendable`.
Identify and move 'everything that is being written to' - or at least the high-intensity-write parts of the OS such as `/var/log` and `/tmp` - to `/volatile` and replace them with links.
Note the distinction: there's a set of write-intensive data that we needn't be afraid to loose ("expendable") such as `/var/log` or openHAB logs, and another set where that would cause quite some pain if it got lost ("essential") such as the thing config (jsondb) or persistence data storage area.

Now we could give users a choice to mount either all of `/volatile` or `/volatile/expendable` only as tmpfs (or from USB flashdrive or from a NAS if available).
The contents of `/volatile/essential` should be backed up and recovered in case of crash.

We should also apply a size restriction on tmpfs like 10% (of RAM) or 100M (just for example, to be discussed) to ensure RAM shortage cannot result in swapping (thus heavy write activity).

Opinions?

**Comment by ThomDietrich** [comment]
https://community.openhab.org/t/openhabian-problem-after-upgrade/23446/8?u=thomdietrich

**Comment by mstormi** [comment]
and [https://community.openhab.org/t/oh2-saving-sd-card-writes/25859/34](https://community.openhab.org/t/oh2-saving-sd-card-writes/25859/34l) and probably many more....

So while we seem to agree on the principles (SDs are basically ok, don't add HW, invest in backup instead), I actually don't want to discuss how unreliable SD cards are (or not), that's a somewhat religious topic. Let's face the fact that there's rather many crashes, and writing to SD increases the probability.
That's why I want to minimize them, thus my proposal, please comment on that.

**Comment by FulvioSpelta** [comment]
Just a hint: if you are going to use your Raspi or other sd based computers in a production environment consider the use of proper sd card eg: https://www.sandisk.com/about/media-center/media-resources/product/oem-design/industrial-solutions/industrial-sd-microsd
(Im not related to SanDisk it's just an example search for other options)

**Comment by mstormi** [comment]
Trying to revive this issue as SD crashes are a constantly reappearing topic on the forum.
I renamed the issue so it's now more what it actually is about.

@ThomDietrich, does openHABian by default properly delete old logs based on a maximum size ?
(sorry I have no running openHABian instance to check against).
If yes (but only if so), there is no danger of a user not pruning his logs (eventually resulting in 'disk full', leading to system lockups) which is the main risk I would attribute to the introduction of tmpfs for logs.
The other risk I see is that we might allow tmpfs to take too much RAM which then is missing for regular use. I believe we should detect RAM size of the box and make a decision based on that.
No tmpfs on systems <= 512 MB RAM but maybe 100MB on 1GB+ ones. Java process is ~550MB (maximum, more than half of that is paged out) on my (fairly large) OH installation.

Thinking about it, I also came to believe that paging/swapping is probably going to SD as well (probably a raw partition as of today).
As that'll happen proactively controlled by the kernel, we cannot stop it other than by moving the swap partition to USB, too. Now as we cannot do that with a NAS, I think the better solution will be to setup a swap FILE instead of a partition.
So instead of (eventually) using a swap partition, we should turn that partition into a filesystem and put the swapfile on there (dphys-swapfile command, config is in /etc/dphys-swapfile).

The current "move root to USB" option should be reworked to become a mere "minimize writes" option to include all those modifications mentioned above (including the introduction of /volatile).
It should query the user for availability of a directory name on external storage (USB or NAS).
If there is none, we would go for a swapfile on local SD and tmpfs for /volatile/expendable.
If there is such storage, we should refrain from using tmpfs and move [= place links from] /volatile to point to that external storage and we should also place the swap file there.

Thoughts, opinions ?

**Comment by ThomDietrich** [comment]
Hey @mstormi,
that would have been a good topic for the Smart Home Day. I'm honestly still critical and undecided about the whole topic. I don't see a big issue in the basic workings of the operating system. After all Raspbian (we are only talking about the RPi system) is developed by many clever folks with the RPi om ,ind. They are aware of the real issues of the RPi and took considerable measures (like dphys-swapfile, yes). I'd be careful to mess around with that. We are trading flexibility and traceability for an uncertain benefit.

Speaking of benefits: I know that you are aware of my often cited statement. I've recently [updated it](https://community.openhab.org/t/openhabian-problem-after-upgrade/23446/8?u=thomdietrich) with some real data and a table to do some tests yourself. Could you please compare them to your system and let me know to which conclusion you are coming with that?

**Comment by mstormi** [comment]
Yes it would have been a good topic for a session, maybe something to keep in mind for the next event.
I agree on the "no big issue" BUT the average openHABian user will not use a NAS and even will not have a backup strategy, but he'll still suffer from SD crashes or at least he heard about them.
It's their lives I'm trying to improve....
I agree on the clever Raspian people but their pov is to have a RPi and nothing else (because that is what most RPi users have in terms of HW and capabilities), and for them openHAB is just one app out of many, so they cannot and won't want to optimize the OS for that specific use case.
And they certainly did not plan or optimize for a single java process to consume 500+ MB.
All of this is different for openHABian and the RPi use case as a server to primarily run openHAB.

Now my suggestion wouldn't change anything for someone to just have a RPi (and no stick, NAS or UNIX knowledge). It would just be an _option_ (not a default) in openHABian setup like 'move to USB' is today for people to know how to mount a stick or to run a NAS.
I fully disagree on your statement 'We are trading flexibility and traceability for an uncertain benefit.'
Ok, the _extend_ of the benefit is uncertain, but not the benefit per se.
And I don't see at all where we give up flexibility and traceability?

**Comment by ThomDietrich** [comment]
@mstormi we sadly didn't have the time to talk in person over the course of the Smart Home Day. Let's catcxh up on that... Are you free to talk on the phone tomorrow?

**Comment by ThomDietrich** [comment]
@mstormi 0173/6152492
I am busy today and tomorrow. If you are free call me any time Friday afternoon?

**Comment by mstormi** [comment]
I've re-setup my own server using the scheme depicted in my post.
This is the essence of my /etc/fstab:

192.168.1.100://server/pi/essential         /volatile/essential     nfs     nolock,noatime  0       0
192.168.1.100://server/pi/expendable     /volatile/expendable    nfs   nolock,noatime  0       0
192.168.1.100://server/pi/backup           /volatile/backup        nfs     nolock,noatime  0       0
/var/log                                    /volatile/expendable/var/log            none bind 0 0
/usr/share/openhab2               /srv/openhab2-sys                           none bind 0 0
/etc/openhab2                         /srv/openhab2-conf                         none bind 0 0
/var/lib/openhab2                    /srv/openhab2-userdata                  none bind 0 0
/var/log/openhab2                   /srv/openhab2-logs                         none bind 0 0
/usr/share/openhab2/addons   /srv/openhab2-addons                    none bind 0 0

Now if someone didn't have any NAS but say a stick, we would just need to replace the first mount-from-NAS lines by mount-local-device ones.
Swap is defined in /etc/dphys-swapfile to reside on 'expendable' dir on NAS, too:
[11:59:42] pi@openHABianPi:~$ swapon -s
Filename                                Type            Size    Used    Priority
/volatile/expendable/temp/pi3-swapfile  file            2007036 10720   -1

**Comment by mues-lee** [comment]
Hello,

@mstormi 
why to struggle with the division into /volatile/expendable and /volatile/essential when you can just move the whole system to nfs, leaving only /boot and the swap file on the sd?
I also would leave the swap file on the sd, because the access to it via nfs can cause some serious trouble (are at least it had in the past, not sure if there is anything changed on how debian is managing the swap access)

Benefits : (of course depending on the hostsystem of nfs) 
- snapshot function in addition to amanda backup
- backup could be handled offside pi (easier to use than amanda?)
- bit rot prevention
- raid for additional data "safety" (i know raids can't replace a backup, for this the " ")
- fast restore time in case of sd needs to replaced 
- much more disk space (if this ever should be a problem on times with cheap 64gb sd)
- no big deal to go back to sd only
- more user friendly than dividing into categories (?)
- i believe easier to implement since you basically do similar things when using a usb drive

Cons: (mostly the same as moving only 'essentials' and 'expandables' there)
- system stop working when nfs is off 
- 2 systems to maintain
- a bit more network traffic

jm2c
Best
mues-lee

**Comment by mstormi** [comment]
openHABian is meant to be useable in a variety of HW setups, including for people that e.g. just own a Pi, so we must allow for running without any NAS or other NFS server.
That's why a first step must be to logically slice (divide) the system into volatile/non-volatile and expendable/essential data. That (and no more for now) is my proposal here.

As a second step. any user can then decide which part of these he is willing to move to NFS or any USB-attached storage medium by simply mounting these.

Swap is volatile-expendable and no, there's no general reason to not put it on NFS, but the same logic applies here: it needs to remain the user's choice, i.e. it can just be an option in openHABian.

**Comment by mues-lee** [comment]
Hello

thank you for your quick reply, i didn't meant that the whole should be moved for everyone to nfs, just for the user that want to use it this way, as an option via openhabian-config after normal installations on sd, sorry for not making this clear enough in my post.

I also agree that it should always be the users choice, if s/he only wants to use sd, partially sd/nfs or complete nfs. (iscsi could be an additional options)

Anyways as you wrote that for now your goal is to divide the the files, if the user wants to do this, i suppose that the offer for a "complete nfs use" script PR as optional setting in openhabian-config is needless, right?

Best
mues-lee

**Comment by mstormi** [comment]
Right, thanks for offering but I think it's needless indeed.

**Comment by ThomDietrich** [comment]
Hey guys, I still think we should ship a near-to-default system and such tweaks shouldn't be part of that. I still think that a good backup strategy is more important. The solution by @mues-lee is good indeed but the normal openHABian user will not own a nas/nfs system.

That said, feel free to create a PR with such steps as optional steps in the openHABian menu ;)

**Comment by EliasGabrielsson** [comment]
@mstormi I see the Z-ram as an alternative implementation to solve this problem. Could we close this?

I advocate that we focus our effort to get zram rock solid instead of implement alternative methods.

**Comment by mstormi** [comment]
yes zram indeed is an alternative and even better solution than this here to use external HW.
However I still like the original idea to identify "expendable" vs. "essential" data.
I've come up with an initial set as part of the the zram implementation as I had to specify the dirs to move into RAM at some stage, but we might want to modify the list of dirs over time.
We don't need to track that in an issue, though, so I agree to close it.

**Comment by EliasGabrielsson** [comment]
Yea lets keep those thoughts in mind when we further develop the ZRAM implementation.
