### ISSUE TITLE
Enforced architecture in openhabian config scripts

### ISSUE THREAD

**Issue by edspiner** [openhab/openhabian#1288]
https://github.com/openhab/openhabian/blob/68a729cbef9f1a22b1a273740957493197e638ec/functions/find.bash#L254

**ISSUE:** This line (and some others in this script) enforce OS architecture with hardcoded path to libs folder to `armv7` however the latest openhabian i installed (RPi4) is `aarrch64` so this path is different. 
In result, the installation script fails to install "Monitor mode" patches

**SUGGESTED SOLUTION**: The script should check OS architecture and use a relevant path

**Comment by mstormi** [comment]
aarch64 is 64bit this is not supported for the time being
(sure we take the hint so thanks nonetheless)

**Comment by ecdye** [comment]
@edspiner As should be clearly seen by the many warnings involved in this script, it is not guaranteed to work and is very clearly labeled as 'ALPHA/DANGEROUS'. 

Additionally, the primary reason for this is that the upstream project last I had checked does NOT support 64 bit installations of monitor mode. However, I will look into this and see if I can fix the issue.

**Comment by edspiner** [comment]
Thanks for the response. 

Yeah, indeed I followed that path which leads me to nowhere. Nexmon has no official support for `aarch64` so that installation would fail anyway.

Just keep an eye of that once monitor mode gets propper support on 64bit arm.
