### ISSUE TITLE
Wireguard removal broken menu option

### ISSUE THREAD

**Issue by gargamelonly** [openhab/openhabian#1294]
openHABian Configuration Tool [stable]v1.6.1-963(1fa8959)
 
A not supported option was selected (probably a programming error):          │
                         │   "   | Remove WireGuard VPN" 

![image](https://user-images.githubusercontent.com/29747434/101691675-b957f280-3a77-11eb-8df7-e40bafc8528c.png)

**Comment by gargamelonly** [comment]
Still Error:

```
2020-12-10_08:20:35_IST [openHABian] Removing Wireguard service...
$ systemctl stop wg-quick@wg0.service
FAILED (remove service)
2020-12-10_08:21:03_IST [openHABian] Updating Linux package information... OK
2020-12-10_08:21:03_IST [openHABian] Removing Wireguard service...
$ systemctl stop wg-quick@wg0.service
Warning: The unit file, source configuration file or drop-ins of wg-quick@wg0.service changed on disk. Run 'systemctl daemon-reload' to reload units.
FAILED (remove service)
```

**Comment by mstormi** [comment]
depending on what you installed or configured before this may be correct or not

reproduce with a fresh install to install first then uninstall WG

show a log with debugmode=maximum
