### ISSUE TITLE
openHAB3 branch

### ISSUE THREAD

**Issue by ecdye** [openhab/openhabian#1297]
@mstormi Please be careful when force pushing changes to the openHAB3 branch, you keep losing commits.

Try running 
```
git fetch origin && git reset --hard origin/openHAB3
``` 
before rebasing and force pushing

**Comment by mstormi** [comment]
big sorry! I usually do but have forgotten you might be working on the branch

**Comment by ecdye** [comment]
It's all good. Just a friendly reminder :)

**Comment by BClark09** [comment]
It would also be safer to create PRs against the `openHAB3` branch instead of working directly off the branch, just like you would the `master` branch.

**Comment by mstormi** [comment]
> It would also be safer to create PRs against the `openHAB3` branch instead of working directly off the branch, just like you would the `master` branch.

We do when we _work_ on the openHAB3 branch but for the most part it's about forwarding changes made to master to openHAB3 users.

**Comment by mstormi** [comment]
any todo here? if yes please reopen
