### ISSUE TITLE
Add veto files to smb conf share

### ISSUE THREAD

**Issue by metbril** [openhab/openhabian#130]
Please also add veto files to [openHAB-conf] like [openHAB-share].

https://github.com/openhab/openhabian/blob/master/includes/smb.conf#L229-L230

**Comment by ThomDietrich** [comment]
Hey,
I didn't do that at first to possibly catch freshly introduced side effects but yeah sure.

Do you see any reason to still provide [openHAB-conf]? I've left it in for compatibility reasons but was to eventually remove it in favor of [openHAB-share].

**Comment by rtvb** [comment]
I would not mind getting rid of the conf share all together. Had not yet noticed that the share share provides access, too.

**Comment by ThomDietrich** [comment]
Didn't announce the share share yet. It's in "hot beta phase" right now ;) Same goes for https://github.com/openhab/openhabian/pull/118 if you are interested.
I want to add one more change, then I'll announce version 1.3

**Comment by ThomDietrich** [comment]
Fixed with https://github.com/openhab/openhabian/commit/1a35e7b32efcde87f2c8d389179a9a7168431a04 (finally 😓 )
