### ISSUE TITLE
Upgrade to OH3 doesn't work on Ubuntu Server 20.04.1 LTS

### ISSUE THREAD

**Issue by bccrew** [openhab/openhabian#1306]
Fresh installed Ubuntu 20.04.1 LTS and updated to latest security updates.

When choosing option 42 as first step, it fails with following error. (logfile changed to debug=maximum)

+ echo 'deb https://openhab.jfrog.io/openhab/openhab-linuxpkg testing main'
++ timestamp
++ date +%F_%T_%Z
+ echo -n '2020-12-17_10:39:02_UTC [openHABian] Installing selected openHAB version... '
2020-12-17_10:39:02_UTC [openHABian] Installing selected openHAB version... + cond_redirect apt-get update
+ [[ -n '' ]]
+ echo -e '\n\033[90;01m$ apt-get update \033[39;49;00m'

$ apt-get update
+ apt-get update
Hit:1 http://nl.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://nl.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:3 http://nl.archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:4 http://nl.archive.ubuntu.com/ubuntu focal-security InRelease
Get:5 https://openhab.jfrog.io/openhab/openhab-linuxpkg testing InRelease [12.5 kB]
Get:6 https://openhab.jfrog.io/openhab/openhab-linuxpkg testing/main amd64 Packages [8,825 B]
Get:7 https://openhab.jfrog.io/openhab/openhab-linuxpkg testing/main i386 Packages [8,805 B]
Fetched 30.1 kB in 2s (18.3 kB/s)
Reading package lists... Error!
E: Encountered a section with no Package: header
E: Problem with MergeList /var/lib/apt/lists/openhab.jfrog.io_openhab_openhab-linuxpkg_dists_testing_main_binary-i386_Packages
E: The package lists or status file could not be parsed or opened.

**Comment by mstormi** [comment]
Ubuntu is not supported as you can see in the README
