### ISSUE TITLE
ZRAM missing on fresh install

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1307]
not sure yet why

[18:46:57] root@openhab-test:/boot# zramctl
[18:47:13] root@openhab-test:/boot# systemctl status zram-config.service
● zram-config.service - zram-config
   Loaded: loaded (/etc/systemd/system/zram-config.service; enabled; vendor preset: enabled)
   Active: failed (Result: timeout) since Fri 2020-12-18 12:10:28 CET; 6h ago
  Process: 24951 ExecStop=/usr/local/sbin/zram-config stop (code=killed, signal=TERM)
 Main PID: 12322 (code=exited, status=0/SUCCESS)

Dec 18 12:05:46 openhab-test zram-config[24951]: + [[ active == \a\c\t\i\v\e ]]
Dec 18 12:05:46 openhab-test zram-config[24951]: + export rsyslogActive=true
Dec 18 12:05:46 openhab-test zram-config[24951]: + rsyslogActive=true
Dec 18 12:05:46 openhab-test zram-config[24951]: + systemctl stop syslog.socket
Dec 18 12:05:46 openhab-test zram-config[24951]: ++ systemctl is-active systemd-journald.service
Dec 18 12:05:46 openhab-test zram-config[24951]: + [[ active == \a\c\t\i\v\e ]]
Dec 18 12:05:46 openhab-test zram-config[24951]: + export journaldActive=true
Dec 18 12:05:46 openhab-test zram-config[24951]: + journaldActive=true
Dec 18 12:05:46 openhab-test zram-config[24951]: + journalctl --flush
Dec 18 12:05:46 openhab-test zram-config[24951]: + systemctl stop systemd-journald.socket systemd-journald-audit.socket systemd-journald-dev-log.socket

Log looks fine to me: [first-boot.log](https://github.com/openhab/openhabian/files/5717361/first-boot.log)

**Comment by mstormi** [comment]
All fine after a reboot.

Do we need to artificially insert one ?

**Comment by ecdye** [comment]
Not sure why that happened. I'll look into it when I have a chance

**Comment by mstormi** [comment]
did not happen again although did several installs.
Closing for now, reopen if you manage to reproduce it
