### ISSUE TITLE
3.0 release

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1308]
We need to switch to install OH3.0 by default.
Please help by double-checking so I don't forget anything of importance.

Plan is to
1) add last minute changes (release repo ?) to master
2) rebase openHAB3 branch on master
3) build a new image from the openHAB3 branch (to have clonebranch=openHAB3).
There was a report it works to install OH3 right away like this but we need to test this ourselves upfront
4) forward master to stable

Is that the best order ? Or should we dare to replace stable with openHAB3 ?

Ethan will you be available on Monday for OH3 release if there's a need for last minute changes?

**Comment by ecdye** [comment]
I should be in the afternoon, but I'll be busy during the morning.

**Comment by mstormi** [comment]
The final 3.0 package is now on bintray. It should work to install from either master or openHAB3 branches.
Please try yourself when you have a chance to.

I triggered another image build, will that pull in the latest "openhab" package? If not can you please build an image to include that.
I'll also forward master to stable now.

**Comment by mstormi** [comment]
OH3 got announced. I've built another image (see actions) and will be putting it out as openHABian v1.6.2 release.
Please test when you have a chance to.

**Comment by mstormi** [comment]
See https://community.openhab.org/t/openhabian-update-help-needed/110780/11

Not sure why it didn't upgrade Java. Possibly the existing java setting in openhabian.conf ?

**Comment by mstormi** [comment]
Ethan could you please at times replace the images ? They still show the menu with "openHAB 2"

**Comment by ecdye** [comment]
What do you mean?

**Comment by mstormi** [comment]
Sorry. I mean the images in docs/openhabian.md that ultimately show up on www.openhab.org/docs

**Comment by mstormi** [comment]
Regarding TODOs left on OH3:
#1273 imho is important as it seems to confuse quite some people so could you please tackle that?

I've fixed the duplicate repo warning in https://github.com/openhab/openhabian/commit/692eee77807d80859b5d33fe64ea3e7881b97c6d

What's left and most important is that apparently many people to upgrade to (or 1st time install?) OH3 do **not** end up in an active openHAB3 branch, then they complain to get affected by the differences in setup OH2/3, directory names for the most part. I'm pretty sure it's because they're in the wrong branch. Unfortunately there has not been a single useful report to date telling how they got there.

**Comment by ecdye** [comment]
Perhaps we should make openHAB3 main (i can do it) and then set if as default and leave master for now as a legacy branch for any critical updates that may be needed.

I already experimented with migrating branches successfully with zram-config so it should be pretty easy. I don't have maintainership access though, so you will have to change it to be the default branch.

WDYT?

**Comment by mstormi** [comment]
Yes that's a good idea of yours, please prepare.

But have yourself a merry christmas first!
[just returned from church, and it was the first time in months we were able to sing there. That just got me sort of 'high'.]
Merry christmas,

**Comment by vguna** [comment]
> What's left and most important is that apparently many people to upgrade to (or 1st time install?) OH3 do not end up in an active openHAB3 branch, then they complain to get affected by the differences in setup OH2/3, directory names for the most part. I'm pretty sure it's because they're in the wrong branch. Unfortunately there has not been a single useful report to date telling how they got there.

I've just started a thread that might be related [here](https://community.openhab.org/t/openhab-3-0-release-discussion/110751/50). Meanwhile I think I should have opened that in an appropriate openhabian release thread. But anyway. I think I have the issue you described: after doing the 03 step to upgrade from 2.5 to 3.0 - it seems I'm still on a wrong branch, leading to paths pointing to wrong directories. When I open the "select branch" dialog, it says that I'm neither on stable nor master. AFAIR I never actively selected a branch, but started back then with a plain 2.5 install. So if I get it correctly, it should point to openhab3 branch instead, right?

**Comment by mstormi** [comment]
> So if I get it correctly, it should point to openhab3 branch instead, right?

It should point to openHAB3 after you have run menu option 3.
Which one does it point to on your box ? It's in the title line. Also if you select menu 01 the current branch should be marked with an asterisk (you said it's neither stable nor master but you didn't mention which one it is 🙄 )

**Comment by vguna** [comment]
That's the thing: it didn't say on which branch I was. I just quoted what the dialog said ("neither stabile nor master"). And I think it pre-selected stable as a recommandation. I performed step 03 before - no idea why it didn't select oh3 after it finished. I manually set it to oh3 then and reinstalled the problematic parts. Seems to work now - except that it tries to downgrade to jdk8 on update step.

**Comment by mstormi** [comment]
> it didn't say on which branch I was.

It did but you didn't see. It did in the title bar and the asterisk will have marked it, too. 

> it tries to downgrade to jdk8 on update step

Check /etc/openhabian.conf for a line "java_opt", let me know and change it to 11 if it's on 8.

@ecdye would we need to replace this as part of OH2/3 migration ?

**Comment by ecdye** [comment]
Possibly as a safeguard, it's possible that it could mess it up. I don't know if the code actually would do this but it won't hurt to change it on migration.

**Comment by mstormi** [comment]
see also #1327 yes let's safeguard this

**Comment by vguna** [comment]
> > it didn't say on which branch I was.
> 
> It did but you didn't see. It did in the title bar and the asterisk will have marked it, too.

Then I need new glasses :). But maybe you can show me where it is:

![IMG_20201226_122903](https://user-images.githubusercontent.com/3257311/103150643-7768c500-4776-11eb-8a97-4aa3a6628134.jpg)

BTW: After starting the config this morning and updating itself, it somehow switched back to "unknown" branch - defaulting/proposing to stable as it seems.


> > it tries to downgrade to jdk8 on update step
> 
> Check /etc/openhabian.conf for a line "java_opt", let me know and change it to 11 if it's on 8.

Hmm for me it's not there:

```
# Modify your openHABian settings
# Handle with care, only touch if you need to!!

hostname=xxx
username=xxx
#userpw=xxxxxxxx

# Language and time. Be sure to set these to valid values
timeserver=0.pool.ntp.org
locales="en_US.UTF-8 de_DE.UTF-8"
system_default_locale="en_US.UTF-8"
#timezone=Europe/Berlin

# Wi-Fi settings. An ethernet connection is recommended
# Requirement: RPi3, RPi0W, PineA64 or a supported external Wi-Fi dongle
# Fill in your SSID and password below, leave empty to use ethernet
wifi_ssid=""
wifi_psk=""

# vim: filetype=sh
```

**Comment by mstormi** [comment]
The current branch is displayed in the title bar of the **main menu**.
The asterisk should mark the branch in the window so I assume it is stable. Please cross-check with the main menu.
The message you see claiming you are not on master is wrong. The code actually checked for master only.

I've just fixed that. To validate, set terminal to record your output then add `debugmode=maximum` in openhabian.conf` and restart the tool, then re-do what you did to get to see this window you showed.

What branch does the main menu show you're on ?
Did you update openhabian-config on start ? Did you ever ? Did it ask you to on this start ? On last start ? Were you asked to select a branch and which one did you choose ? 



As a sidenote, your openhabian.conf is very old (a year at least I'd guess) as it's missing options many of the new features. I've only seen that on one or two other occasions, and seems it's those people have the biggest problems so I'd suggest to reinstall from scratch.
The older the more difficult to find out the better to restart from scratch.

**Comment by mstormi** [comment]
> > Check /etc/openhabian.conf for a line "java_opt", let me know and change it to 11 if it's on 8.
> 
> Hmm for me it's not there:

so it is not set to Java 8

@vguna Please describe how you installed openHABian. Do I assume correctly that you manually cloned the Github repo ?
Point me to the instructions you used please.

@ecdye so the problem with Java being downgraded to 8 apparently happens when someone installed without the image
**and** has an old `openhabian.conf` that has neither cached_java_opt` nor `java_opt` set (on manual install it does not update openhabian.conf, I actually don't even know where that originates from in case of manual clone install).
Can you please change the code to take care of this ?

**Comment by vguna** [comment]
Ah, that explains it :).

For me it shows `[stable]v1.6.1-1061(940f995)` - even after it just asked on startup if I want to update to the lastest changes (I confirmed) and directly after that, which branch to select (showed asterix on stable) - where I selected OH3. So it seems it somehow does not persist my branch selection.

Here is the debug log you requested:

[openhab-config-debug.txt](https://github.com/openhab/openhabian/files/5743283/openhab-config-debug.txt)

The steps in this are:

- start config
- it shows the news and I set it to "don't show again"
- main page shows stable version
- I go to select branch and it shows stable with an asterik
- I select OH3 there and confirm
- main page shows branch OH3 now
- I exit the main page

When I now start the config again, it asks me always again whether to show the news or not.
Then it's back to stable showing it in the main page. I can repeat those steps above infinite.

I always let openhabian config update itself when it requests it. While I was trying your suggested steps and restarting config a couple of times within minutes, it asked if I want to update and I confirmed. The last times it stopped asking for it. Most of the time it asked after the update what branch to use and I selected OH3.

I installed OH 2.5 maybe 1 year ago or so using the [provided Raspberry image](https://www.openhab.org/docs/installation/openhabian.html#raspberry-pi-prepackaged-sd-card-image). Just wrote it to the sdcard and took it from there. I did never do a manual install nor cloned something related to OH/openhabian config from a git repo.

What is the option exactly to keep jdk11? `java_opt=11`?
Thanks for taking a look into this!

**Comment by ecdye** [comment]
> @ecdye so the problem with Java being downgraded to 8 apparently happens when someone installed without the image
> **and** has an old `openhabian.conf` that has neither cached_java_opt`nor`java_opt` set (on manual install it does not update openhabian.conf, I actually don't even know where that originates from in case of manual clone install).
> Can you please change the code to take care of this?

The problem I see with that is if we override the users config file then we ruin any of their manual settings. Perhaps it would be best to document this use-case and explain how to reset the configuration file manually and warn that it will override any previous settings.

**Comment by mstormi** [comment]
I'd think this is not an issue because it's all relevant at installation time only, isn't it?
Or is there any parameter (except debugmode) to take effect in normal operations ?

**Comment by ecdye** [comment]
Yes, there are several, the Java settings the HW override settings and possibly others as well. I need to check which ones though.

**Comment by mstormi** [comment]
Maybe we should do it 'right' in the first place: cycle through all params and replace them with defaults (from openhabian.conf.dist) when they're missing (else keep user definitions).
Will save work for analysis and will also work for future params.

**Comment by ecdye** [comment]
Probably, do you want to take that one on?

**Comment by mstormi** [comment]
Well very busy but I'll see if I can take on it

**Comment by catsoo** [comment]
There seems to be an issue with switching the branches with an existing setup. After Switching to openHAB3 branch manually (and successfully) the script always changes back to the stable branch on next start:

`[15:53:13] openhabian@openHABianPi:~$ sudo openhabian-config
2020-12-28_15:53:21_CET [openHABian] Checking for root privileges... OK
2020-12-28_15:53:21_CET [openHABian] Loading configuration file '/etc/openhabian.conf'... OK
2020-12-28_15:53:21_CET [openHABian] openHABian configuration tool version: [openHAB3]v1.6.1-1067(36bfa61)
2020-12-28_15:53:22_CET [openHABian] Checking for changes in origin branch HEAD... OK
2020-12-28_15:53:26_CET [openHABian] Switching to branch stable... OK`

**Comment by mstormi** [comment]
Thanks for the info.

@ecdye: I think that is because of clonebranch= in openhabian.conf

**Comment by ecdye** [comment]
I think i fixed that in master but the change may not have been synced to stable yet.

**Comment by mstormi** [comment]
please look it up if so I'll forward master to stable again

**Comment by ecdye** [comment]
> please look it up if so I'll forward master to stable again
> 
> and if clonebranch is set it actually _should_ use that branch so it's sorta correct.
> But we would need to store the current branch into openhabian.conf clonebranch after a branch change, shouldn't we ?

Yes, that is the change I am referring to that I am not sure if was forwarded. I'll go look now.

**Comment by catsoo** [comment]
Thanks for looking into this - just confirmed by adding `clonebranch=openHAB3` to my config

2020-12-28_21:46:19_CET [openHABian] Loading configuration file '/etc/openhabian.conf'... OK
2020-12-28_21:46:19_CET [openHABian] openHABian configuration tool version: [openHAB3]v1.6.1-1067(36bfa61)
2020-12-28_21:46:19_CET [openHABian] Checking for changes in origin branch openHAB3... OK
2020-12-28_21:46:24_CET [openHABian] Switching to branch openHAB3... OK

**Comment by mstormi** [comment]
> > But we would need to store the current branch into openhabian.conf clonebranch after a branch change, shouldn't we ?
> 
> Yes, that is the change I am referring to that I am not sure if was forwarded. I'll go look now.

Did you check ? I'd like to merge the config-redo script then forward master to stable but wanna be sure this save-the-branch fix is contained.

**Comment by ecdye** [comment]
I did, it appears to be there. I'm not sure what is causing this, I can switch branches just fine on my config.

**Comment by mstormi** [comment]
and it gets stored into openhabian.conf and the branch remains after a restart ?
Yeah same for me. At least I never hit that before (or did but didn't notice)

**Comment by mstormi** [comment]
ok will forward to stable now

**Comment by mstormi** [comment]
Dunno of any remaining general openHABian issues around OH3.0 that don't have their own issue open yet so will close.
Reopen if you disagree or have impotant news.
