### ISSUE TITLE
Add option to choose download repo from config 

### ISSUE THREAD

**Issue by rtvb** [openhab/openhabian#131]
If you like to switch from stable to beta or nightly you have to edit the repo used by apt-get yourself. It would be nice if the openhabian-config tool would provide a switch option.

**Comment by ThomDietrich** [comment]
If everything stays as planned I'll have some spare time this evening.

**Comment by ThomDietrich** [comment]
I was always a bit unsure how to secure the switching between different versions, back and forth, while also making sure the configuration stays sane. Basically this can not be ensured with the constant improvements happening in unstable.
Therefore I decided to implement a one-way option to switch over to unstable. I guess this will be sufficient for 80% of the interested users.

https://github.com/openhab/openhabian/pull/132
