### ISSUE TITLE
OH3 64 bit SD-Card image file not working - Raspberry is blinking 7 times on Boot 

### ISSUE THREAD

**Issue by Duffy77** [openhab/openhabian#1311]
## Issue information:
Downloaded the Image from 
https://github.com/openhab/openhabian/releases/download/v1.6.2/openhabian-pi-raspios64beta-v1.6.2.img.xz

Unpacked with 7zip and written with Win32DiskImager

Put SD Card in Raspberry PI 2 Model B and powered on

Green LED is flashing 7times in loop

## System information:
Raspberry PI 2 Model B 
8GB SD Card

**Comment by mstormi** [comment]
So when you downloaded it there you will have read this

Note the 64 bit version is unsupported and untested. It's provided just as-is.

**Comment by Duffy77** [comment]
Hi,
yes, i have read and understand it. 
But i thought, that it would be nice that you get some feedback, that there is something wrong with it.
But when you don't care about the feedback, then you can skip the creation of the 64 bit version.

**Comment by mstormi** [comment]
well thanks then. But that was not obvious from your writing.

**Comment by mstormi** [comment]
You used a Pi 2. That cannot run 64 bit, only models 3 and newer can.
