### ISSUE TITLE
64 bit image

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1313]
I think we should at least fix the password issue
https://community.openhab.org/t/no-sudo-on-openhabian-64bit/110335/6

**Comment by burkhardtnb5** [comment]
I did it how he described it and had the same problem when I tried to open the openhabian-config. I have a Raspberry Pi 4 8GB and used the 64bit image. But my Raspberry didn't generate a log file after the first boot. I tried many times and different solutions but nothing works, I just can't get a log file out of it.

**Comment by LinqLover** [comment]
Additional comment from the thread above: The `openhabian` user is not a member of the `sudo` user group, and a separate `pi` user exists. So probably the rename does not work ...

**Comment by JAMESBOWLER** [comment]
Ok I installed an got the same issue 🥇 

![Screenshot 2020-12-28 092647](https://user-images.githubusercontent.com/2579619/103182514-8b880000-48f7-11eb-9c4c-dd0b6e2edacd.png)

[firstboot.log](https://github.com/openhab/openhabian/files/5745480/firstboot.log)

The PI user with default password is still present.

I added openhabian to sudo

```
pi@openHABianDevice:/etc/sudoers.d $ sudo cat 010_pi-nopasswd
pi ALL=(ALL) NOPASSWD: ALL
openhabian ALL=(ALL) NOPASSWD: ALL
```

Others have recently had issues with mosquitto so I installed that and everything is fine 

[Mqtt Setup.log](https://github.com/openhab/openhabian/files/5745490/Mqtt.Setup.log)

**Comment by mstormi** [comment]
anyone with the 64bit image please do in shell
``` 
source /opt/openhabian/functions/helpers.bash
set -x
is_raspbian && is_raspios
```

**Comment by LinqLover** [comment]
> anyone with the 64bit image please do in shell
> 
> ```
> source /opt/openhabian/functions/helpers.bash
> set -x
> is_raspbian && is_raspios
> ```

```
[01:56:45] openhabian@openhab:~$ uname -a
Linux openhab 5.4.79-v8+ #1373 SMP PREEMPT Mon Nov 23 13:32:41 GMT 2020 aarch64 GNU/Linux
[01:55:33] openhabian@openhab:~$ source /opt/openhabian/functions/helpers.bash
[01:55:37] openhabian@openhab:~$ set -x
[01:55:37] openhabian@openhab:~$ is_raspbian && is_raspios
+ is_raspbian
+ [[ '' == \r\a\s\p\b\i\a\n ]]
++ cat /etc/os-release
+ [[ PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/" =~ Raspbian ]]
+ return 1
```

**Comment by mstormi** [comment]
again with is_raspios please

**Comment by LinqLover** [comment]
> again with is_raspios please

```
[02:07:32] openhabian@openhab:~$ source /opt/openhabian/functions/helpers.bash
[02:07:33] openhabian@openhab:~$ set -x
[02:07:33] openhabian@openhab:~$ is_raspios
+ is_raspios
+ [[ '' == \r\a\s\p\i\o\s ]]
++ cat /etc/os-release
+ [[ PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/" =~ Raspberry Pi OS ]]
+ return 1
```

**Comment by mstormi** [comment]
Hmm
@ecdye seems we need new functions to reliably identify Raspbian/Raspi OS

**Comment by mstormi** [comment]
please also do
cat /boot/issue.txt /etc/issue

**Comment by JAMESBOWLER** [comment]
[11:49:18] openhabian@openHABianDevice:~$ cat /boot/issue.txt /etc/issue
Raspberry Pi reference 2020-08-20
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 7252c154838ec5b4576f29c996ac8fe3750cae12, stage2
Debian GNU/Linux 10 \n \l

**Comment by LinqLover** [comment]
> cat /boot/issue.txt /etc/issue

```
[03:24:52] openhabian@openhab:~$ cat /boot/issue.txt /etc/issue
Raspberry Pi reference 2020-08-20
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 7252c154838ec5b4576f29c996ac8fe3750cae12, stage2
Debian GNU/Linux 10 \n \l
```

**Comment by mstormi** [comment]
and lsb_release -a please

**Comment by JAMESBOWLER** [comment]
[13:46:13] openhabian@openHABianDevice:~$ lsb_release -a 
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

**Comment by mstormi** [comment]
Anyone to read, please test with the 64bit image from https://github.com/openhab/openhabian/actions/runs/453449798#artifacts
when you have a chance to

**Comment by JAMESBOWLER** [comment]
Tested and working user openhabian has sudo access 

Test machine pi4 8gig   
debugmode=maximum [first-boot.log](https://github.com/openhab/openhabian/files/5756525/first-boot.log)  

Thankyou

**Comment by mstormi** [comment]
given the 64bit image remains to be officially unsupported, I'll close this for now.
We can reopen it if there's any new issue of _general_ interest.

**Comment by mstormi** [comment]
@JAMESBOWLER thanks for your feedback (other, too)

Do you run it with a 64bit JVM ?

**Comment by JAMESBOWLER** [comment]
> java -version
> openjdk version "11.0.9" 2020-10-20 LTS
> OpenJDK Runtime Environment Zulu11.43+88-CA (build 11.0.9+11-LTS)
> OpenJDK 64-Bit Server VM Zulu11.43+88-CA (build 11.0.9+11-LTS, mixed mode)

There are only 2 types of people in this work those that can extrapolate from incomplete data

**Comment by brangc** [comment]
Unsubscribe

Jimmy <notifications@github.com> schrieb am Do. 31. Dez. 2020 um 22:17:

**Comment by krikk** [comment]
64-bit is out of BETA (https://www.raspberrypi.com/news/raspberry-pi-os-64-bit/) ...so perhaps we should remove the beta tag also here?

**Comment by mstormi** [comment]
No. The beta tag has a number of implications such as "no support" that we should not give up thoughtlessly.
And In the first place there hasn't been any testing of 64bit openHABian so no reason for removing.

**Comment by ecdye** [comment]
To be clear, yes eventually we will remove the beta tag. We will only do so when we are really ready to, we have been waiting for a stable version to do any real testing on the platform. If I had to guess I'll be ready to call it stable before summer but we'll see.
