### ISSUE TITLE
move toot to USB

### ISSUE THREAD

**Issue by hrf3** [openhab/openhabian#1314]
Hello,
I tryed v.1.6.2 (32) on a Raspi 3B+ and get "Move root to USB can only be used on a Raspberry PI !"
On Raspi 3B "Move root to USB must not be used while using ZRAM! Canceling move root to USB!"
With v.1.5 it worked on both Raspis and two SSDs.

**Comment by mstormi** [comment]
pls send the output of `tail -4   /proc/cpuinfo`

**Comment by hrf3** [comment]
###############################################################################
###############  openHABianDevice  ############################################
###############################################################################
##        Ip = 192.168.178.3
##   Release = Raspbian GNU/Linux 10 (buster)
##    Kernel = Linux 5.4.79-v7+
##  Platform = Raspberry Pi 3 Model B Plus Rev 1.3
##    Uptime = 0 day(s). 0:2:0
## CPU Usage = 0.25% avg over 4 cpu(s) (4 core(s) x 1 socket(s))
##  CPU Load = 1m: 1.44, 5m: 0.75, 15m: 0.29
##    Memory = Free: 0.40GB (44%), Used: 0.50GB (56%), Total: 0.90GB
##      Swap = Free: 0.68GB (100%), Used: 0.00GB (0%), Total: 0.68GB
##      Root = Free: 0.63GB (20%), Used: 2.53GB (80%), Total: 3.35GB
##   Updates = 0 apt updates available.
##  Sessions = 1 session(s)
## Processes = 136 running processes of 32768 maximum processes
###############################################################################

[14:40:48] openhabian@openHABianDevice:~$ tail -4 /proc/cpuinfo
Hardware        : BCM2835
Revision        : a020d3
Serial          : 000000004db45252
Model           : Raspberry Pi 3 Model B Plus Rev 1.3

**Comment by hrf3** [comment]
Hardware        : BCM2835
Revision        : a02082
Serial          : 0000000027cc0ab1
Model           : Raspberry Pi 3 Model B Rev 1.2

**Comment by mstormi** [comment]
Should be fixed by https://github.com/openhab/openhabian/commit/25c9a1872b59b3adc073efd8754fe826cd2b979e
