### ISSUE TITLE
first-boot.bash always fails

### ISSUE THREAD

**Issue by RogerG007** [openhab/openhabian#1315]
## Issue information:

The first-boot script seems to always fail while "Waiting for openHAB to become ready" 

`if ! tryUntil "curl --silent --head http://${HOSTNAME:-openhab}:8080/start/index |& grep -qs 'HTTP/1.1 200 OK'" 20 10; then echo "OK"; else echo "FAILED"; exit 1; fi
`
When checking manually, the curl test returns HTTP/1.1 404 Not Found. 

However, openhab is up and running and can be configured.

## System information:
openhabian 1.6.2
Raspberry4, 4GB

**Comment by mstormi** [comment]
Thanks for reporting

https://github.com/openhab/openhabian/commit/1fab88836bbd3f7d8304f635a032e2a6e9f80376 should fix it
