### ISSUE TITLE
Openhabian is trying to add dashboard tiles in openHAB 3 environment

### ISSUE THREAD

**Issue by Confectrician** [openhab/openhabian#1316]
We need to either remove or fix the dashboard functionality for OH3

See https://community.openhab.org/t/oh3-where-is-frontail-and-paper-ui/110792/13 for details.
See also openhab/openhab-core#1849

### Original issue information:
When i install frontail i get the following error message:
>[openHABian] Adding an openHAB dashboard tile for 'frontail'... FAILED (openHAB or config folder missing)

I think this should get a problem for anything that aims to add a dashboard tile, since those tiles aren't available anymore without Paper UI in openHAB 3 environments.

## Debug information:
Install an openHAB 3 environment on openhabian base and try to install a component like frontail which will cause openhabian to add a tile.

## System information:
Ubuntu Server 20.04 as virtual machine on a Synology NAS

**Comment by mstormi** [comment]
your point is valid but you want support for an unsupported system. Ts ts ....

**Comment by Confectrician** [comment]
I can reproduce it on my spare pi and post again if you want to. 😛

**Comment by mstormi** [comment]
@ecdye did you tiles change fix this too ? if no would you please ?

**Comment by dimmenhau** [comment]
i have the problem that frontail is not in the dashboard of OH3.

her is the log from the install:
```
2021-01-04_11:44:12_CET [openHABian] Updating openHAB Log Viewer (frontail)... OK
2021-01-04_11:44:22_CET [openHABian] Configuring openHAB Log Viewer (frontail)... OK
2021-01-04_11:44:22_CET [openHABian] Setting up openHAB Log Viewer (frontail) service... OK
2021-01-04_11:44:25_CET [openHABian] Adding an openHAB dashboard tile for 'frontail'... OK
```

**Comment by ecdye** [comment]
Yes it should have. However the link may need to be updated for proper operation in all systems but I'm not sure how to as it no longer works by substituition. Perhaps we need to use the IP address. @mstormi any ideas?

**Comment by dimmenhau** [comment]
have you tried ```hostname -A```, because it returns the hostname with the domain.

**Comment by ecdye** [comment]
Just tried, and it did not work for me.

**Comment by dimmenhau** [comment]
then it could be that I only get this because my FireWall with the DHCP server delivers this correctly to the client.

IP address I find dangerous, if the DHCP times changes. But should it not go without .local ?

**Comment by ecdye** [comment]
Without local it would not work for me. FOr now I'll stick with IP and if it causes issues we can revisit it

**Comment by mstormi** [comment]
>  @mstormi any ideas?

on what exactly?
If a client cannot or does not properly resolve a dns name then it's a problem of either the client or the dns server (which in most home or SOHO is a combined DNS resolver/DHCP server in fact.
Using IPs works around this but the problem is still with the user and his machine to translate that name or not.

**Comment by dimmenhau** [comment]
the fix has a bug, he have a "space" before the port. 'http://192.168.0.51%20:9001/'
