### ISSUE TITLE
Mosquitto passwd file is created with world-readable permissions

### ISSUE THREAD

**Issue by mstefany** [openhab/openhabian#1321]
## Issue information:
Mosquitto `passwd` file is created with world-readable permissions, and I think it should not be this way.
Probably good solution would be to create the file with 0660 permissions and owner:group as `mosquitto:openhabian`.
This way mosquitto can read the file for its own run and default openhabian user can manage the passwd database without using sudo.

## Debug information:
```
$ ls -la /etc/mosquitto/passwd
-rw-r--r-- 1 root root 120 Dec 22 15:25 /etc/mosquitto/passwd
```

## System information:
OS: openHABian image -> Raspberry Pi OS, 32-bit version
HW: Raspberry Pi 4, 2 GiB version

```
$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
$ uname -m
armv7l
```

Should I submit a PR for this?

**Comment by mstormi** [comment]
Well we could discuss the importance of file permissions on a single user system
but if you submit a PR I don't mind to put it in

**Comment by mstormi** [comment]
should be fixed by https://github.com/openhab/openhabian/commit/7c062e6cc124b988a10a38d520e05e9671c59c3e
