### ISSUE TITLE
OH3 Configuration Tool install of mosquitto fails

### ISSUE THREAD

**Issue by basovink** [openhab/openhabian#1325]
## Issue information:
A fresh install of OH3.0 on a RPI
I changed system name (#31) and admin passwords (#34) → reboot
Then I installed mosquitto (#23)
Mosquitto runs but after reboot fails to start
Somehow mosquitto cannot write in /var/log/mosquitto

## Debug information:
`debugmode=maximum` is not very helpfull
syslog gives:
`mosquitto[572]: 1608679321: Error: Unable to open log file /var/log/mosquitto/mosquitto.log for writing.`

Managed to fix it using steps in [this post](https://community.openhab.org/t/openhabian-mosquitto-mqtt-failed-to-start/102951/41?u=basovink)

## System information:
OH3.0
Raspberry Pi 3B Quad Core 1.2GHz Broadcom BCM2837 64bit CPU 1GB RAM

```
$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```
```
$ uname -m
armv7l


```

**Comment by mstormi** [comment]
> `debugmode=maximum` is not very helpfull
> syslog gives: [...]

For sure it is. But only if you record and post the output....


And these statements of yours
1) Configuration Tool install of mosquitto fails
2) Mosquitto runs but after reboot fails to start
3) Somehow mosquitto cannot write in /var/log/mosquitto

contradict each other:  It cannot run after install failed. It cannot fail to write wherever when it doesn't run.

So please in the first place, **properly** describe your problem.


And before you do, upgrade openhabian, remove mosquitto and install it again.

**Comment by basovink** [comment]
Dear Markus,

Ad 1. install is offered to me. So, if it keeps running after (ad 2.) reboot, I experience this as success. If it doesn't I experience it as failure.
Ad 3. I have determined the problem and solved it for my situation. I hope my report will trigger some _friendly_ developer into looking at the permissions given to different folders during this install script. My goal is not to build a better system for others (I wish I was smart enough). My goal is to get my openHAB running as it was before.

**Comment by mstormi** [comment]
> My goal is not to build a better system for others

But mine is, and that's what this whole Github-Open-Source thingy is about.
So please help with that by providing clear, useful input.

Did you upgrade openhabian and reinstall mosquitto ?

**Comment by pbogaert** [comment]
hi Markus, first of all many thanks for all you great work.

first of all, I'm a novice and I learn along the way by tinkering and hence that's why I love your work with openhabian which is in essence for dummies like me...

I love OH and can't wait to upgrade to OH3. I've got 2 runining with moquette and tried the new version (fresh install 1.6.2) on a new SD, but unfortunately the Mosquitto does not install similar to.

https://community.openhab.org/t/openhabian-mosquitto-mqtt-failed-to-start/102951

What would be your suggestion?

Cheers

Paul

**Comment by mstormi** [comment]
Thanks but Github is the wrong medium please post this on the forum and mind the posting rules (e.g. not to directly address people).
Provide a debug log as explained in the debug guide.

**Comment by mstormi** [comment]
https://github.com/openhab/openhabian/commit/30efe9a366abdd511604103e0c03f482c8ecc2e1 implements the solution from 
https://community.openhab.org/t/openhabian-mosquitto-mqtt-failed-to-start/102951/41 so until further notice I believe the issue is fixed.
