### ISSUE TITLE
/usr/share/openhab/addons isn't linked to /srv/openhab-addons properly

### ISSUE THREAD

**Issue by SRGDamia1** [openhab/openhabian#1328]
With OH2, these folders were linked, so adding an add-on to the samba shared srv folder got it installed.  That doesn't seem to be working with OH3.

**Comment by mstormi** [comment]
That's right.
But not an issue.
You can login and put your jars there.

**Comment by SRGDamia1** [comment]
Well, yes, of course I can. But there is a shared folder created called openhab-add-ons and putting a file in it does nothing. If it won't be functional, it shouldn't be created.

**Comment by ecdye** [comment]
It is functional for me, I can use it just fine. Are you logging in with the correct credentials?

**Comment by SRGDamia1** [comment]
Hm. I'm in as "openhabian" but it's entirely possible I have the permissions wrong. The former magic "fix permissions" command is still set to oh2 folders. I thought I caught all the new folders, but I might have missed it.

**Comment by mstormi** [comment]
> he former magic "fix permissions" command is still set to oh2 folders.

Nope then you are on the wrong openHABian branch. You need to be on openHAB3 branch then fix permissions should work for you as well.

**Comment by SRGDamia1** [comment]
Um, that's not good.  I did the upgrade through the openhabian config tool and selected the "stable" branch.

**Comment by mstormi** [comment]
Right that's not good. You mustn't change (back) to "stable" after you upgraded. Noone told you to, right ?

**Comment by SRGDamia1** [comment]
Hm.  Totally missed that the OH3 branch even existed.  I think I just used the 03/Install openHAB option without changing the branch so I was still on "stable."

Now I'm on [openHAB3]v1.6.1-1067(36bfa61) and the permission fix works and the mount works perfectly.

Doh.  Thank you so much for bearing with me and getting me fixed up!

**Comment by mstormi** [comment]
>  I think I just used the 03/Install openHAB option without changing the branch

Are you sure on that? 03 should also switch the branch.

**Comment by SRGDamia1** [comment]
Every time I reopen the config tool, it switches itself back to stable.

**Comment by mstormi** [comment]
Update the config tool when it asks you to.
You can change the clonebranch= setting in openhabian.conf but it should save the branch there when you change it.
if that does not help provide a debugmode=maximum log of the tool start

**Comment by SRGDamia1** [comment]
I'm sorry.  There is definitely something really wrong with my permissions.  The "fix permissions" link errors out (with a message about samba shares).  And I can't modify the openhabian.conf file because something's wrong with the permissions on it.

**Comment by mstormi** [comment]
>  And I can't modify the openhabian.conf file because something's wrong with the permissions on it.

sudo vi /etc/openhabian.conf

Or sudo bash then continue as root but be careful
