### ISSUE TITLE
Mosquitto "Unable to open log file /home/mosqitto.log for writing."

### ISSUE THREAD

**Issue by Adminius** [openhab/openhabian#1329]
## Issue information:
I've installed openHABian v1.6.2 a view days ago an installed Mosquitto via openhabian-cli config.
And provided password.
But I can't connect via openhab or other Clients to the server

After some try&error I managed to get this error:

`Error: Unable to open log file /var/lib/mosquitto.log for writing.`

If I disable 
`#log_dest file /var/log/mosquitto/mosquitto.log`
in _/etc/mosquitto/mosquitto.conf_ I can start mosquitto without any problems and openHAB MQTT and other clients can connect to MQTT broker (with password)

## System information:
Tested on RasPi 3

PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

armv7l

**Comment by mstormi** [comment]
> `Error: Unable to open log file /var/lib/mosquitto.log for writing.`

Neither openHABian nor the mosquitto default config do that per default so I'd think you must have configured that yourself.
That's not an openHABian issue, sorry

**Comment by Adminius** [comment]
@mstormi I've installed mosquitto this way and didn't changed anything else...
`sudo openhabian-config`
![image](https://user-images.githubusercontent.com/17052262/103152845-2ebc0680-478c-11eb-897c-33269c4409e7.png)

that means, that this line `log_dest file /var/log/mosquitto/mosquitto.log`
was added automaticaly at setup process into `/etc/mosquitto/mosquitto.conf`

**Comment by Hotte37** [comment]
@mstormi,
I have the same issue on a new setup. I also only used openhabian-config.
Directly after a installation of Mosquitto the file /var/log/mosquitto/mosquitto.log was existing and mosquitto was able to start.
After a `reboot -f ` the file directory var/log/mosquitto was no longer existing and thus mosquitto was not able to start.
Then i also commented the line in mosquitto.conf and mosquitto was able to start.

So i am very interested in this bug fix. But i understood your answer, that you think this is not an openhabian issue and you don't care abaut this. Is this correct?

**Comment by mstormi** [comment]
The OP wrote about var/**lib**/mosquitto.log (not **log**) hence my answer.

I haven't read his response until now. That's clearly different from the original input. I have no opinion on that for the time being.
