### ISSUE TITLE
Mosquitto setup fails when the password includes a space

### ISSUE THREAD

**Issue by k-a-p** [openhab/openhabian#133]
I entered a password which included a space and that made the Mosquitto setup to fail. See screen output below:

$ mosquitto_passwd -b /etc/mosquitto/passwd openhabian 1234 5678
Error: -b argument given but password file, username or password missing.
FAILED

Solution would be to (at least it worked for me on the console) put doublequotes around the password e.g. "1234 5678"

**Comment by ThomDietrich** [comment]
Hey @k-a-p, thanks for reporting!
I'm unsure about how to "solve" this issue. You should not put a space in passwords, I'm not saying it's not possible but highly unusual. The error message could be clearer or an active check&fail for spaces could be implemented. I'd not implement changes to support spaces. How do you think about that?

**Comment by ThomDietrich** [comment]
Sounds good, let's do that 👍

**Comment by ThomDietrich** [comment]
Fixed. Thanks for the input!
