### ISSUE TITLE
[Migration] Upgrade from 2.5.x to 3.x failed

### ISSUE THREAD

**Issue by Jochen1980** [openhab/openhabian#1331]
Today I tried to update my openhabian instance from 2.5.x to 3.0. I used sudo openhabian-config and my installation crashed afterwards. The update took not longer than 5 seconds but openhab-config jumps over to the configuration news announcement screen. 

I am using an RbPi 3 and my current openhabian version is 1.6.1. After restarting the Pi my first boot logfile says that "cloning myself ... FAILED" and "Initial setup exiting with an error!" It seems, that the commands before have been running properly.

**Comment by ecdye** [comment]
Are you using the latest image: [openHABian 1.6.2](https://github.com/openhab/openhabian/releases/tag/v1.6.2)? If not, please use it and try again.

**Comment by Jochen1980** [comment]
Thanks for your fast reply @ecdye !

I looked into my openhabian-config About information - I am using indeed 1.6.1. I haven't tried to change the whole image of my RbPi - I expected that the "update openhabian" function pulls the latest version, here 1.6.2 by itself?

**Comment by ecdye** [comment]
It does but it will still fail if the original install was bad.

**Comment by mstormi** [comment]
FWIW it didn't display when on 1.6.2, as I learnt today this requires the tag to be an _annotated_ one. Now v1.6.2 is.

**Comment by mstormi** [comment]
pls reopen if this is still an issue
and provide a debug log (debugmode=maximum)
