### ISSUE TITLE
OH3 + Grafana/InfluxDB package // access rights missing after reboot

### ISSUE THREAD

**Issue by renekar** [openhab/openhabian#1332]
Fresh installation using OH3 (3.0.0) and Grafana+InfluxDB works fine till first reboot of the raspberry Pie.  After reboot Grafana frontend (localhost:3000) isn't reachable anymore.

`sudo journalctl | grep grafana` replies:

`grafana-server[897]: Failed to start grafana. error: failed to create log directory "/var/log/grafana": mkdir /var/log/grafana: permission denied`

A manual adjustment 
```
sudo mkdir /var/log/grafana
sudo chown -R grafana:grafana /var/log/grafana
sudo systemctl start grafana-server.service
```
works till but until next reboot only.

Seems permissions are not set correctly during installation routine.

**Comment by mstormi** [comment]
could be related to the ZRAM startup order thingy so we should revisit this when that is done.

**Comment by eikowagenknecht** [comment]
This still happens for me, Openhabian 1.6.3 with current openHAB3 branch of the config tool installed.

The directory is non existent after reboot. The commands above fix it until next reboot.

Is there any command I need to execute to enable this permanently?

**Comment by Semurak** [comment]
Happens for me as well, which is really anoying

**Comment by eikowagenknecht** [comment]
@mstormi I don't know if you receive pings for closed issues, so sorry for tagging you directly ;-)

Should this issue be reopened or a new one created?

**Comment by mstormi** [comment]
Check /opt/zram/log.bind/grafana. I'd guess it has bad permissions.
If you fix those I'd expect that to be reboot-safe and fix this issue, please try.
