### ISSUE TITLE
FIND3 setup uses nonexistent user group "openhabian"

### ISSUE THREAD

**Issue by MaxBlasto** [openhab/openhabian#1333]
## Issue information:
When trying to install the FIND3 server using openhabian-config, these two commands from functions/find.bash (lines 111/112) fail:
```
  if ! (id -u find3 &> /dev/null || cond_redirect useradd --groups openhabian find3); then echo "FAILED (adduser)"; return 1; fi
  if ! cond_redirect chown -R find3:openhabian /opt/find3; then echo "FAILED (permissions)"; return 1; fi

```
The group "openhabian" does not exist. I changed this to use the existing group "openhab" and it works fine.

The two files includes/find3server.service and find3ai.service also contain the "openhabian" group. I changed this as well but it didn't seem to have any effect.

So far, the find server seems to be running nicely.

## Debug information:
See above.

## System information:
cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

uname -m
armv7l

**Comment by mstormi** [comment]
When changing to group "openhabian" does not work it is because you defined your own user+group to run openHABian under
(username in `openhabian.conf`) so you should change it to be owned by that one.

@ecdye we need to chown ${username:-openhabian} in FIND3 install.
