### ISSUE TITLE
ZRAM OpenHAB3

### ISSUE THREAD

**Issue by Michi1983** [openhab/openhabian#1335]
Hello,

I have a problem with a fresh installation of OpenHAB 3 with openhabian and probably ZRAM.
When I restart with reboot my Raspberry 3B the items stored in the persistence are not restored. If I restart only OpenHAB, it works without any  problems. Since I manually stopped zram once, the data that was current at that time is always loaded when I restart the pi.
Is there something wrong with the configuration of the ZRAM or ist the problem the reboot?

Michael

**Comment by ecdye** [comment]
It's a bug, I'm working on a fix now.

**Comment by ecdye** [comment]
Try uninstalling and reinstalling zram now and see if it works.

**Comment by Michi1983** [comment]
@ecdye Great job is working now.

**Comment by mstormi** [comment]
@ecdye is this the same issue why shutdown/reboot takes so long ?

If yes, we need to recommend to reinstall ZRAM to all users that have this problem, correct ?
(because ZRAM setup on disk does not upgraded through openhabian-config)

**Comment by ecdye** [comment]
Correct. Although we could change it to just upgrade through the menu.

**Comment by mstormi** [comment]
Nah I think it just affected some users (do you know how long this "bad" code was online?).

a Happy and Healthy new Year to you !

**Comment by ecdye** [comment]
Not sure, a week at maximum. I think it was closer to 2-3 days.

**Comment by Michi1983** [comment]
@mstormi I have reinstalled ZRAM via openhabian the possibility already exists. Must be done in two steps (uninstall then install)

**Comment by brangc** [comment]
Unsubscribe

Markus Storm <notifications@github.com> schrieb am Do. 31. Dez. 2020 um
14:03:
