### ISSUE TITLE
missing mail-address in /etc/email-addresses

### ISSUE THREAD

**Issue by mues-lee** [openhab/openhabian#1348]
Issue information:
when changing the username in openhabian.conf and also activating mail relay settings the mail address for the new user account is not been added to /etc/email-addresses 

Additional information:
fresh install openhabian-pi-raspios32-v1.6.2.img.xz @ rPi 4

**Comment by mstormi** [comment]
Of course it is not.
You must not change the username in openhabian.conf except _before_ installation but _never after_ it.

**Comment by mues-lee** [comment]
yes that is what i done ...
- flash the sd card
- made the username changes and added the mail relay settings to openhabian.conf 
- let the scripts to the magic
- found out it does not work

**Comment by mstormi** [comment]
> what you made think that i was trying to change the username retroactively?

Your statement did. If you only change this _before_ installation it would rather be called "to set" it as the user does not yet exist, wouldn't it?

I fixed that in master. Please validate and confirm.

**Comment by mues-lee** [comment]
thanks for the fast fix, not sure if `${username:-openhabian}` is correct I would had changed it to `${username}`

Sorry I can't test if it working way you changed it, because I can't access the linux partition on my windows machines
