### ISSUE TITLE
bind mouted entries under /srv are mounted ro instead of rw

### ISSUE THREAD

**Issue by WolfgangSn** [openhab/openhabian#1355]
[##]Issue information:
Mounted directories unter /srv ( ) are mounted read only; not read-write after a reboot:
mount |grep /srv 
/dev/sda7 on /srv/openhab-userdata type ext4 (ro,relatime,errors=remount-ro)
/dev/sda7 on /srv/openhab-addons type ext4 (ro,relatime,errors=remount-ro)
/dev/sda7 on /srv/openhab-conf type ext4 (ro,relatime,errors=remount-ro)
/dev/sda7 on /srv/openhab-sys type ext4 (ro,relatime,errors=remount-ro)

They are initially mounted rw but remounted ro ( see attached logging from systemctl with debug information ).

Also running openhabian-config menu 13 immediately mounts them rw. After a reboot they are ro again.

Changing the mount template from
     Before=smbd.service
     After=zram-config.service
to
     Before=smbd.service
     After=network.target

fixes this and the directories are mounted rw ( see attached logging from systemctl with debug information ).

## Debug information:
see attached files
srv-remounted-ro-journalctl.txt shows that the directories are mounted rw first and in later stages of systemd they are remounted ro.
srv-mounted-rw-journalctl.txt shows that the directories are mounted rw.

## System information:
version of openhabian-config: [openHAB3]v1.6.2-1075(1041167)

OS:
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

Kernel:
Linux myopenhabian 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux

[srv-remounted-ro-journalctl.txt](https://github.com/openhab/openhabian/files/5754092/srv-remounted-ro-journalctl.txt)
[srv-mounted-rw-journalctl.txt](https://github.com/openhab/openhabian/files/5754093/srv-mounted-rw-journalctl.txt)

**Comment by mstormi** [comment]
> fixes this and the directories are mounted rw ( see attached logging from systemctl with debug information ).

systemd startup order is coincidential so if this worked you're lucky. Adding network.target is fine but removing zram-config.service is not.
Try to add both as After= and let me know if that works

**Comment by WolfgangSn** [comment]
Based on your suggestion I tested
          After=network.target zram-config.service
and I can confirm that the directories are mounted rw after a reboot.

**Comment by mstormi** [comment]
thanks. Have a couple of reboot at different times if you have a chance to to make sure this isn't just coincidence

**Comment by mstormi** [comment]
I added network.target to future install
pls test nonetheless
@ecdye fyi

**Comment by cee-dee** [comment]
After my first reboot, I still could not write to openhab2-conf, after the second reboot it worked. I'll report on how stable this solution is.

Anyway, I noticed that on my system openhab2-logs directory is now empty.

**Comment by WolfgangSn** [comment]
> I added network.target to future install
> pls test nonetheless
I did 20 reboots and the folders always were mounted rw.

**Comment by mstormi** [comment]
Ok so with #1367 merged I'll consider this to be fixed.
Reopen if you encounter again
