### ISSUE TITLE
Release openHABian v1.6.1 Rasbeery PI doesn't work 

### ISSUE THREAD

**Issue by raj007manda** [openhab/openhabian#1358]
## Issue information:
First boot log says - [openHABian] Starting webserver with installation log... FAILED.
I think it's because I don't want to connect to WIFI and only using Ethernet.

## Debug information:
Please provide all of the output provided by utilizing the `debugmode=maximum`
parameter in the `/etc/openhabian.conf` file. For more information on how to
accomplish this, please see [openhabian-DEBUG.md](https://github.com/openhab/openhabian/blob/master/docs/openhabian-DEBUG.md#create-a-debug-log).

## System information:
Please tell us what OS you are running (Raspberry Pi OS, Debian, Ubuntu), what
HW you are running on (Raspberry Pi, amd64). Also include the output of
`cat /etc/os-release` and `uname -m`.

**Comment by mstormi** [comment]
You must not use Github to *request support*. Read the debug guide and links on when and how to open an issue.
