### ISSUE TITLE
Openhabian Welcome Screen informations maybe wrong

### ISSUE THREAD

**Issue by LCN-User** [openhab/openhabian#1361]
## Issue information:
Not really an important problem...
After putting the SD-card in another Raspi-Device and starting PuTTY on my Windows-Device, the Openhabian the Welcome-Screen shows the wrong IP-Adress and the wrong Revision of the Raspi-Device. Maybe the informations won't be updated? 

![Screenshot-PuTTY-2020-12-31](https://user-images.githubusercontent.com/76812252/103409043-41a45180-4b65-11eb-9798-d607f41d1de1.jpg)

## Debug information:
cat /proc/cpuinfo or
cat /proc/device-tree/model 
both show the correct Revision 1.2 of the new Raspberry Pi 4B
## System information:
I installed OpenHAB3.0.0 release via openhabian v1.6.2 on a Raspberry Pi 4B, 4GB, Revision 1.1, later I changed the Hardware to a Raspberry Pi 4B, 4 GB, Revision

**Comment by mstormi** [comment]
the login screen data gets upgraded from a systemd timer I think once a day so just wait for that to happen
