### ISSUE TITLE
enforce smbv2 ?

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1365]
see https://community.openhab.org/t/openhabiandevice-too-long-for-windows/112255

@ecdye
do you think we should add those smb settings, invalidating smbv1 ?
do you think we should change the default hostname to have less chars ?

**Comment by ecdye** [comment]
> do you think we should add those smb settings, invalidating smbv1 ?

Unless you can think of a breaking issue that would be cause by doing so, I don't see why not.

> do you think we should change the default hostname to have less chars ?

Wouldn't hurt, we could just change it back to `openhabian` and keep it simple.

**Comment by mstormi** [comment]
ok see linked thread: I'd think we need not change smb.conf.
Changing the hostname to openhabian makes sense though, will do.
