### ISSUE TITLE
New installation will not finish with OH3

### ISSUE THREAD

**Issue by MarkusGafner** [openhab/openhabian#1368]
Regarding to the script first-boot.bash Lines 242/243:

`# this took ~130 seconds on a RPi2
if ! tryUntil "curl --silent --head http://${HOSTNAME:-openhab}:8080/start/index |& grep -qs 'HTTP/1.1 200 OK'" 20 10; then echo "OK"; else echo "FAILED"; exit 1; fi
`
The installer waits until the webserver is ready, but ":8080/start/index" is not available for OH3

**Comment by ecdye** [comment]
You are not using the latest image, as in the latest image the fix is already present.
