### ISSUE TITLE
Serial Error: Port /dev/ttyAMA0 does not exist

### ISSUE THREAD

**Issue by martindlarsson** [openhab/openhabian#137]
A fresh install of the latest image running on a Raspberry Pi 2 Model B Rev 1.1 and trying to get my Z-wave (Razberry) to work. I ran openhabian-config to add support for razberry and then followed the instructions here: [cd-jackson.com/...](http://www.cd-jackson.com/index.php/openhab/habmin/10-habmin-zwave-binding-initialisation). But when I save the settings for the controller I get Serial Error: Port /dev/ttyAMA0 does not exist.
When I do ls -la under /dev/ I can see ttyAMA0. I have added openhab user to group tty and dialout. I actually did `sudo chown opanhab /dev/ttyAMA0` too but dont know if that is a bad idea.
Each and every time I have made a change I have rebooted but with no luck.
Now Im out of ideas, or rather Google is out of ideas. Can anybody help?

**Comment by martindlarsson** [comment]
I got it working! Did as this forum post suggested: https://community.openhab.org/t/has-anyone-gotten-razberry-working-with-openhab-2/12539/11
Specifically the /boot/cmdline.txt and the usermode stuff. Maybe something to consider when releasing the next version?

**Comment by ThomDietrich** [comment]
All of this has long been implemented and can be found in the openHABian Configuration Menu:

* http://docs.openhab.org/installation/openhabian.html#first-steps
* https://github.com/openhab/openhabian/issues/33#issuecomment-267465644

**Comment by martindlarsson** [comment]
That is good but apparently that did not help in my situation. I can investigate what step in the forum posts steps did the trick. Either the /boot/cmdline.txt edit or the group thing.

**Comment by ThomDietrich** [comment]
Hmm all of this is covered and the Razberry is used by many openHABian users without problems. Who knows what caused the problem. Let's see if anyone else encounters the issue, if so feel free to comment here!

**Comment by ThomDietrich** [comment]
Probably related to https://github.com/openhab/openhabian/issues/138
