### ISSUE TITLE
homegear systemd service file references wrong openhab systemd service file

### ISSUE THREAD

**Issue by RogerG007** [openhab/openhabian#1375]
## Issue information:
The systemd service file /etc/systemd/system/homegear.service created when installing homegear via openhabian-config tool wrongly references dependencies to openhab2.service instead of openhab.service
Stopping of openhab service therefore does not stop homegear service.

## Debug information:
/etc/systemd/system/homegear.service and the original /opt/openhabian/include/homegear.service:

```
[Unit]
Description=Homegear
PartOf=openhab2.service
...

```

## System information:
openhabian 1.6.2b

**Comment by mstormi** [comment]
should be fixed by https://github.com/openhab/openhabian/commit/c296da17a34009ea244df108b63df4d07cd01187
