### ISSUE TITLE
Setup of InfluxDB and Grafana goes to FAILED

### ISSUE THREAD

**Issue by dimmenhau** [openhab/openhabian#1377]
## Issue information:
I wanted to install the InfluxDB and Grafana package today on a newly set up system and then the status "FAILED" keeps coming back. Before today's patchday the installation worked without problems.

## Debug information:
    + echo -n '2021-01-04_23:33:53_CET [openHABian] Setting up InfluxDB service... '
    2021-01-04_23:33:53_CET [openHABian] Setting up InfluxDB service... + cond_redirect sed -i -e 's|auth-enabled = true|# auth-enabled = false|g' /etc/influxdb/influxdb.conf
    + [[ -n '' ]]
    + echo -e '\n\033[90;01m$ sed -i -e s|auth-enabled = true|# auth-enabled = false|g /etc/influxdb/influxdb.conf \033[39;49;00m'
    
    $ sed -i -e s|auth-enabled = true|# auth-enabled = false|g /etc/influxdb/influxdb.conf 
    + sed -i -e 's|auth-enabled = true|# auth-enabled = false|g' /etc/influxdb/influxdb.conf
    + return 0
    + zram_dependency install influxdb
    + local zramServiceConfig=/etc/systemd/system/zram-config.service
    + local install=yes
    + zramServiceConfig=/tmp/z
    + [[ -f /etc/ztab ]]
    + [[ install == \i\n\s\t\a\l\l ]]
    + shift 1
    + [[ influxdb == \r\e\m\o\v\e ]]
    + for arg in "$@"
    + [[ yes == \y\e\s ]]
    + grep -qs influxdb.service /tmp/z
    ++ timestamp
    ++ date +%F_%T_%Z
    + echo -n '2021-01-04_23:33:53_CET [openHABian] Adding influxdb to zram service dependencies... '
    2021-01-04_23:33:53_CET [openHABian] Adding influxdb to zram service dependencies... + cond_redirect sed -i -e '/^Before/s/$/ influxdb.service/' /tmp/z
    + [[ -n '' ]]
    + echo -e '\n\033[90;01m$ sed -i -e /^Before/s/$/ influxdb.service/ /tmp/z \033[39;49;00m'
    
    $ sed -i -e /^Before/s/$/ influxdb.service/ /tmp/z 
    + sed -i -e '/^Before/s/$/ influxdb.service/' /tmp/z
    sed: can't read /tmp/z: No such file or directory
    + return 2
    + echo 'FAILED (sed add dependency)'
    FAILED (sed add dependency)
    + return 1
    + return 1
    + return 1
    + echo FAILED
    FAILED

## System information:
    [00:04:19] openhabian@openhab:~$ cat /proc/cpuinfo | grep Model
    Model		: Raspberry Pi 4 Model B Rev 1.2
    
    [23:23:58] openhabian@openhab:~$ cat /etc/os-release
    PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
    NAME="Raspbian GNU/Linux"
    VERSION_ID="10"
    VERSION="10 (buster)"
    VERSION_CODENAME=buster
    ID=raspbian
    ID_LIKE=debian
    HOME_URL="http://www.raspbian.org/"
    SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
    BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
    [23:28:13] openhabian@openhab:~$ uname -m
    armv7l

**Comment by mstormi** [comment]
branch?

**Comment by mstormi** [comment]
should be fixed by https://github.com/openhab/openhabian/commit/1334748f4b112576c181c995bea42bf35abcd501
