### ISSUE TITLE
Frontail looks very strange in openHAB3 Branch

### ISSUE THREAD

**Issue by florian-h05** [openhab/openhabian#1382]
## Experienced issue
After upgrading my openhabian-config tool to the openHAB3 Branch and reinstalling frontail log viewer,
it looks very strange and not like before. 
![2021-01-05 14_21_39-Window](https://user-images.githubusercontent.com/73423173/103651123-62074e00-4f61-11eb-9164-2cde775d42fc.png)

## System information:
Raspberry Pi 3 Model B Plus Rev 1.3
openHABian 3.0.0 - Release Build

`cat /etc/os-release` 
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

`uname -m`.
armv7l

**Comment by juanhaywood** [comment]
What does your frontail.service file look like?

`sudo nano /etc/systemd/system/frontail.service`

**Comment by mstormi** [comment]
>  it looks very strange and not like before.

so what?  My car doesn't either after I have washed it.
Least thing you must provide when you open an issue is to properly describe the problem and why it is a bug.
