### ISSUE TITLE
Timestamp item fault on analog channel (temperature)

### ISSUE THREAD

**Issue by Mclupo** [openhab/openhabian#1389]
System pi 4 with 4 Gb Ram 
I installed a timestamp item for a digital channel (switch) which works fine.
The timestamp item for an analog channel (temperature) failed at the first installation. The repeated installation was ok. But the next update of the timestamp failed again.
![image](https://user-images.githubusercontent.com/53428233/103801311-da4b3d80-504d-11eb-84a1-a5b450d04079.png)

![image](https://user-images.githubusercontent.com/53428233/103801977-c227ee00-504e-11eb-9d63-54caea55fbcc.png)

![image](https://user-images.githubusercontent.com/53428233/103801997-c94efc00-504e-11eb-99e1-8cc646671810.png)

**Comment by ecdye** [comment]
@Mclupo This is a openhab issue not openhabian, please open it the correct project or go to the fourm to get the help you need.
