### ISSUE TITLE
Add pigpio package

### ISSUE THREAD

**Issue by nils-bauer** [openhab/openhabian#139]
I commited a [GPIO binding](https://github.com/openhab/openhab2-addons/pull/1334) which depends on the pigpio package. 
If this package is preinstalled the users can use their PIs GPIO Pins without any linux skills.
Pigpio is in the repo (can be installed via 'sudo apt-get install pigpio').

**Comment by ThomDietrich** [comment]
Gladly. I'll comment in the other thread.

**Comment by ThomDietrich** [comment]
Please keep me informed about the progress of the PR ;)

**Comment by EliasGabrielsson** [comment]
@nils-developersinblue Saw that you made some progress on the binding this spring. We will install relevant packages to base installation of openHABian when your binding ready and merged.

**Comment by mstormi** [comment]
@nils-bauer can you please give a statement on this, would any OH install to use the GPIO binding need the pigpio or any other GPIO specific package installed ?
If no I'd like to close this.

**Comment by nils-bauer** [comment]
It is not needed if you only want to control remote PIs.
But I think it might be a common use case to control the GPIOs on the pi where oh is also installed.

**Comment by mstormi** [comment]
is the binding ready for use ?

**Comment by nils-bauer** [comment]
The binding's pull request is still not accepted.
I would suggest that we wait till it is merged before we put any effort into adding pigpiod to the system.

From my side, we can close this issue for now and I will reopen it if I have something new. Would that be okay?

**Comment by mstormi** [comment]
Sure. Please don't hesitate to reopen. Thanks.

**Comment by nils-bauer** [comment]
@mstormi can you please reopen this issue? The binding is now merged.

> is your request only to add the pigpio linux package ? or some other package ?
> over even config for it ? Or would that be left to the user.

It is needed to install and enable pigpio.

**Comment by mstormi** [comment]
Do I understand that right: you want to run a remote RPi that has sensors or whatever attached to its GPIOs.
You do NOT run openHAB there but you want to run this remote RPi on openHABian ?

**Comment by nils-bauer** [comment]
You can use both the local raspberry pi, which is also running openhab, and remote raspberry pi. 
But even if you want to control the GPIOs of the pi running openhab, you need to have pigpio running.

So I want to be able to run openHAB, openhabian and pigpio on the same pi.

**Comment by mstormi** [comment]
If someone runs openhab he's most likely using the gpio binding in the first place.
I fear that installing pigpio might break that.

(And if you don't run openHAB it's none of openHABian's business so no reason to include either)

**Comment by nils-bauer** [comment]
The old GPIO binding for openHAB is not any longer working with openHAB 3. And the new one only works with pigpio running.

**Comment by mstormi** [comment]
ok. Is there any need to configure pigpio or is it just about installing it ?
