### ISSUE TITLE
Error when installing additional components on OH3

### ISSUE THREAD

**Issue by timbms** [openhab/openhabian#1394]
## Issue information:
When installing optional component 21  Log Viewer, i.e. frontail, an error is shown: `There was an error or interruption during the execution`
An annoyance because frontail is actually installed.

## Debug information:
```
+ echo -n '2021-01-07_14:53:44_CET [openHABian] Adding an openHAB dashboard tile for '\''frontail'\''... '
2021-01-07_14:53:44_CET [openHABian] Adding an openHAB dashboard tile for 'frontail'... + case $application in
+ true
+ openhab_is_installed
+ openhab2_is_installed
++ dpkg -s openhab2
++ grep Status
++ cut '-d ' -f2
+ [[ '' == \i\n\s\t\a\l\l ]]
+ return 1
+ openhab3_is_installed
++ dpkg -s openhab
++ grep Status
++ cut '-d ' -f2
+ [[ install == \i\n\s\t\a\l\l ]]
+ return 0
+ return 0
+ [[ -d /etc/openhab2/services ]]
+ echo 'FAILED (openHAB or config folder missing)'
FAILED (openHAB or config folder missing)
+ return 1
+ '[' 1 -ne 0 ']'
+ whiptail --msgbox 'There was an error or interruption during the execution of:\n  "20 | Optional Components"\n\nPlease try again. If the error persists, please read /opt/openhabian/docs/openhabian-DEBUG.md or https://github.com/openhab/openhabian/blob/master/docs/openhabian-DEBUG.md how to proceed.' 14 80
```

Also the information shown in frontail is incorrect:

<img width="1376" alt="Screenshot 2021-01-07 at 16 16 11" src="https://user-images.githubusercontent.com/5411131/103909224-b9ddba80-5103-11eb-85e0-848345b43eb3.png">

Similar issue also on apply permissions: 
```
$ chown --recursive openhab:openhab /etc/openhab2 /var/lib/openhab2 /var/log/openhab2 /usr/share/openhab2 
+ chown --recursive openhab:openhab /etc/openhab2 /var/lib/openhab2 /var/log/openhab2 /usr/share/openhab2
chown: cannot access '/var/log/openhab2': No such file or directory
+ return 1
+ echo 'FAILED (openhab folders)'
FAILED (openhab folders)
+ return 1
+ '[' 1 -ne 0 ']'
+ whiptail --msgbox 'There was an error or interruption during the execution of:\n  "10 | Apply Improvements"\n\nPlease try again. If the error persists, please read /opt/openhabian/docs/openhabian-DEBUG.md or https://github.com/openhab/openhabian/blob/master/docs/openhabian-DEBUG.md how to proceed.' 14 80
```

## System information:
See #1393

**Comment by ecdye** [comment]
You appear to be on either the master or stable branch. Please switch to openHAB3 branch and try again. I know that this fuction works properly as I have personally used it many times in the last few days while testing this exact problem.

**Comment by timbms** [comment]
I took your advice, switched to openHAB 3 branch in openhabian-config and can confirm that errors are gone. 

Let met just be clear: Stable is stated to be the recommended standard version:
<img width="793" alt="Screenshot 2021-01-07 at 22 05 16" src="https://user-images.githubusercontent.com/5411131/103944780-7780a180-5134-11eb-8aa6-ba2cf4c94c4b.png">

This is at least misleading.
