### ISSUE TITLE
disklist configured by openhabian for OH3 has /var/lib/openhab2 while it should be /var/lib/openhab

### ISSUE THREAD

**Issue by timbms** [openhab/openhabian#1397]
## Issue information:
openhabian supports the user with the configuration of amanda. 
The disklist generated for a freshly installed OH3 contains /var/lib/openhab2 while it should be /var/lib/openhab

## System information:
```
[22:49:23] backup@josefpi4:~$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

```
[22:53:12] backup@josefpi4:~$ uname -m
armv7l
```

**Comment by mstormi** [comment]
No it doesn't. It depends on the branch that is active by the time you install Amanda so you used an OH2 branch and not "openHAB3".
Thanks for your contributions but please make sure you understand the stuff better before you open your next issue.
And set debugmode=maximum to provide debug logs with your issues. We cannot act upon simple claims like this one here.
