### ISSUE TITLE
Documentation on Amanda

### ISSUE THREAD

**Issue by timbms** [openhab/openhabian#1398]
## Issue information:
Documentation seems inconsistent:
Recommendation is to use exfat:
`root@pi:/# mkexfatfs /dev/sda1
`
Mounting instructions are for fat
`root@pi:/home/pi# echo "/dev/sda1     /storage/usbstick-msdos    vfat     noatime,noauto,user,uid=backup  0       1" >> /etc/fstab`

This should be aligned. 

Ideally, the instruction for the two alternatives, exfat and ext4, could be disentangled.

**Comment by mstormi** [comment]
It is neither a recommendation nor instruction, it is *examples*

| Ideally, the instruction for the two alternatives, exfat and ext4, could be disentangled.

go ahead make a PR

**Comment by timbms** [comment]
exfat is not included with the packages exfat-fuse and exfat-utils out of the box in openhabian. 
Would you put the packages in the setup of amanda?

**Comment by mstormi** [comment]
>  Would you put the packages in the setup of amanda?

When you commit a PR to the docs that require availability of these, yes
