### ISSUE TITLE
Add usbutils to distro

### ISSUE THREAD

**Issue by VanHogan** [openhab/openhabian#140]
Please add package usbutils to the distro.

**Comment by ThomDietrich** [comment]
No real problem but could you tell me why?

**Comment by VanHogan** [comment]
Oops, sry i thought i did mention it…. Somehow that was not included in my posting.
 
I’m setting up enocean via the enocean usb300 module and i discovered that lsusb is missing. I tjink that the usbutils would be helpful for other dongles as well. (i needed them because i have problems getting enocean up and running but that is OT here).

**Comment by ThomDietrich** [comment]
Done ;)
