### ISSUE TITLE
Fresh installation of OH3 ask me to upgrade to OH3

### ISSUE THREAD

**Issue by retos** [openhab/openhabian#1403]
After installing the image openhabian-pi-raspios64beta-v1.6.2b.img.xz I receive this message when starting openhabian-config:

![cc8b813b5dc8d799b2172dcf8270ef70d037aeb4](https://user-images.githubusercontent.com/4066100/104293683-924d7000-54be-11eb-9be1-ecf493020b61.png)

`You are currently the latest (“openHAB3”) openhabian environment version. you will need to be on here (openHAB3) if you want to run openhab version 3.`

Not sure if this is the right place to report this. As [mentioned here](https://community.openhab.org/t/fresh-installation-of-oh3-ask-me-to-upgrade-to-oh3/113891) I just make sure I don't move the asterisk.

**Comment by mstormi** [comment]
so where's the problem? This is normal, correct behavior.

**Comment by retos** [comment]
Ok,  I see. It is just confusing to me then. Even in the menue of openhabian-config It gives me the option to upgrade to OH3, but I already have it. I assumed it checked to see if there is a new version and somehow mistook it for a different version than I already have.

**Comment by eikowagenknecht** [comment]
"sudo openhabian-config" also shows a possibly misleading wording:

![image](https://user-images.githubusercontent.com/1475672/104507574-464a1a80-55e7-11eb-8b24-b62620e5e971.png)

From that text I'm not sure if I need to use "stable" or "openHAB3" for the latest OH3 stable version.

**Comment by mstormi** [comment]
> From that text I'm not sure if I need to use "stable" or "openHAB3" for the latest OH3 stable version.

That's no longer in the current code so I think you have not updated.

**Comment by eikowagenknecht** [comment]
Thanks for the clarification. Then consider this a non-issue (any more) :-)
