### ISSUE TITLE
degraded systemd units

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1406]
Seems we improperly setup some services, see `systemctl list-units --state=failed`
Need to check and fix each of them individually.

Verify at least these:
```
● amandaBackupDB.service     loaded failed failed nightly backup: Amanda config, DB, logs
● amdump-openhab-dir.service loaded failed failed nightly Amanda backup: openhab-dir
● logrotate.service          loaded failed failed Rotate log files
● systemd-timesyncd.service  loaded failed failed Network Time Synchronization
● dhcpcd.service             loaded failed failed dhcpcd on all interfaces
```

I think one issue is with Amanda where there exist .timer AND .service and the .service is degraded (it shouldn't be started as a service anyway because it is only ever trigger by the timer)

**Comment by ecdye** [comment]
Hmmm, my backups still work, I get an email every night.

**Comment by mstormi** [comment]
The fresh install box only lists `dhcpcd.service` as failed.
That's probably related to the hotspot code (I think I installed that box using the hotspot feature but I'm not sure).
Not sure if we should remove dhcpcd.service after install or in specific situations.

**Comment by mstormi** [comment]
I believe it was a false alarm, sorry. I was actually able to *start* the "failing" services manually but even then they remain listed as failed".
The remedy is to enter `systemctl reset-failed`.
