### ISSUE TITLE
Raw copy SD starts but fails when drive is mounted

### ISSUE THREAD

**Issue by chaosjug** [openhab/openhabian#1412]
## Issue information:
When executing menu entry 54 "Raw copy SD" in openhabian-config and selecting a drive where at least one partition is mounted this breaks in several ways. It add the new partition table but can't reload it and the tries to write all the data to a file in /dev which obviously just fills up the main SD card.

I would have expected two things to happen:
Some sort of warning, that all data is deleted on that drive. In my case I misinterpreted the text and thought it would write an image file to the drive. But even if you are aware what this option does I think a warning before writing a new partition table would be helpful.
And if a partition is mounted this should be detected and abort. Unfortunately I didn't copy the messages but there was at least one big warning about this which should be caught and reacted to.

## System information:
Raspberry Pi 4 with up-to-date openhabian

**Comment by mstormi** [comment]
There's a number of safety checks including one for mounted partitions of the destination device so normally that should not happen. I don't know how you managed to get into that situation so please provide a debug log showing your specific problem.

**Comment by mstormi** [comment]
Reopen when you have a log to show the problem
