### ISSUE TITLE
openhabian-config seems broken after recent update?

### ISSUE THREAD

**Issue by Diapolo** [openhab/openhabian#1432]
## Issue information:
It seems that some commands that are executed are waiting for an "enter" or do not show the desired information in terminal. I'm on openHABian configuration tool version [stable]patchday-20210119-1114(e0c0204).

I tried to switch to latest stable for prepaing an OH3 update in the near future, but it waits for an enter after "Updating repositories and upgrading installed packages..." upgrading Java to version 11 was waiting for an enter after "Downloading Java Zulu 11 32-Bit OpenJDK..."

## System information:
Release = Raspbian GNU/Linux 10 (buster)
Kernel = Linux 5.4.83-v7l+
Platform = Raspberry Pi 4 Model B Rev 1.1

**Comment by ecdye** [comment]
@Diapolo that should be fixed now. Please reopen if still an issue.

**Comment by Diapolo** [comment]
@ecdye There has been no self-update of openhabian-config, so it's not yet working ;). Anything I can do to force an update of it?

**Comment by ecdye** [comment]
Switch your branch to `main` as that is where the change is located.
