### ISSUE TITLE
[OH3] Failed installing .. Permission denied

### ISSUE THREAD

**Issue by ChristianF1** [openhab/openhabian#1434]
Hi Everyone,

I am having some issue post my OH2 to OH3 upgrade. I am running openHabian version on a raspberry and upgraded using the openhabian config tool

When I install bindings and add-ons I am getting a permission denied. From the log file:

``` 
2021-01-24 15:06:50.721 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-misc-openhabcloud': Permission denied
```

I am posting here on openhabian, because I think its a user permission issue.

After the upgrade I think something happened with the user/group permissions.

Look at this

```
openhabian@openHABianPi:/var/lib/openhab $ ps -u openhab
  PID TTY          TIME CMD
  272 ?        00:00:05 node
 1349 ?        00:00:00 tail
 6518 ?        02:10:39 java
```

There is an `openhab` user running the java (openhab process), a lo of permissions on openhab folders are set to `openhabian` or is mixed and this is true throughout most of the system.

```
openhabian@openHABianPi:/var/lib/openhab $ ls -lsa
4 drwxrwxr-x+ 13 openhab openhabian 4096 Jan 19 21:42 .
4 drwxr-xr-x  41 root    root       4096 Jan 18 23:04 ..
4 drwxrwxr-x+  2 root    root       4096 Jan 18 22:55 backups
4 drwxrwxr-x+  3 openhab openhab    4096 Jan 20 20:21 cache
4 drwxrwxr-x+  5 openhab openhab    4096 Jan 19 21:55 config
4 drwx------+  3 openhab openhab    4096 Nov  3  2019 .config
4 drwxrwxr-x+  3 openhab openhabian 4096 Jan 18 23:05 etc
4 drwxrwxr-x+  3 openhab openhab    4096 Jan 20 19:32 jsondb
4 drwxrwxr-x+  2 openhab openhab    4096 Oct 22  2017 log
4 drwxr-xr-x+  5 openhab openhab    4096 Jan 18 23:04 persistence
4 drwxrwxr-x+  2 openhab openhab    4096 Jan 18 23:08 secrets
4 drwxrwxr-x+  8 openhab openhab    4096 Jan 20 20:22 tmp
4 drwxrwxr-x+  2 openhab openhab    4096 Nov  3  2019 zwave
```

```
openhabian@openHABianPi:/etc/openhab $ ls -lsa
total 64
 4 drwxrwxr-x+  14 openhabian openhabian  4096 Nov  3  2019 .
12 drwxr-xr-x  106 root       root       12288 Jan 19 20:14 ..
 4 drwxrwxr-x+   2 openhabian openhabian  4096 Jan 18 23:05 html
 4 drwxrwxr-x+   3 openhabian openhabian  4096 Oct 22  2017 icons
 4 drwxrwxr-x+   2 openhabian openhabian  4096 Jan 18 23:05 items
 4 drwxr-xr-x+   2 openhabian openhabian  4096 Nov  3  2019 openhab
 4 drwxrwxr-x+   2 openhabian openhabian  4096 Jan 18 23:05 persistence
 4 drwxrwxr-x+   2 openhabian openhabian  4096 Jan 18 23:05 rules
 4 drwxrwxr-x+   2 openhabian openhabian  4096 Jan 18 23:05 scripts
 4 drwxrwxr-x+   2 openhabian openhabian  4096 Jan 18 23:05 services
 4 drwxrwxr-x+   2 openhabian openhabian  4096 Jan 18 23:05 sitemaps
 4 drwxrwxr-x+   2 openhabian openhabian  4096 Jan 18 23:05 sounds
 4 drwxrwxr-x+   2 openhabian openhabian  4096 Jan 18 23:05 things
 4 drwxrwxr-x+   2 openhabian openhabian  4096 Jan 18 23:05 transform
```

I have not installed anything manually - only used the openhabian config tool. 

When openhab is trying to install a binding it needs to add files/folders to e.g. `/etc/lib/openhab` and gets a permission denied due to the permissions being wrong. Since this ownership mismatch is happening through all the openhab folders I am not sure how to correct it. 

Any ideas how to go about fixing this and is the cause of this a bug in the openhabian upgrade process?

**Comment by ChristianF1** [comment]
I did

```
sudo chown -R openhab:openhab /etc/openhab
sudo chown -R openhab:openhab /var/lib/openhab/etc
```

As these had openhabian as user:group and a restart of openhab

That solved the problem. Would still like to know if this my fault or if there was a problem with openhabian config tool / upgrade process.

**Comment by mstormi** [comment]
I don't know what you did to your system but you're the first to report this so I don't think it is a problem with the tool.
group ownership depends on the user you installed for.
BTW there's a menu option to fix permissions.
