### ISSUE TITLE
Fix parsing integer & booleans parameters in UI component based sitem…

### ISSUE THREAD

**Issue by FloriGlori** [openhab/openhabian#1436]
For some time I have had the problem that I cannot enter the height variable in the sitemap via the web UI without errors. This malfunction seems to have been fixed in openHAB according to this link: https://github.com/openhab/openhab-core/pull/2072

In addition, I would have the question of whether openHABian always takes over all bugfixes from openHAB the same way.

>I have already tried the upgrade from the stable version to the main version (1.6.3). Unfortunately without success.

**Comment by mstormi** [comment]
Pardon my directness but I believe you have not fully understood what openHABian is.
I don't understand how your first 2 sentences relate to openHABian.
On the last one, it depends on the openhab repo you selected and when you tell openHABian to update everything (menu 02).
