### ISSUE TITLE
Integration of HABApp logs in frontail

### ISSUE THREAD

**Issue by magnuslsjoberg** [openhab/openhabian#1445]
I just upgraded openHABian and reinstalled HABApp with the new openHABian option. Very smooth!
Since HABApp now logs to the default openHAB log directory, I think it would make sense to integrate better with frontail.

Please also see: https://github.com/spacemanspiff2007/HABApp/issues/202

I have done this in my own openHABian setup and think it would benefit other users if it would be done automatically by openhabian-config. A minor part was a change in HAPApp that @spacemanspiff2007 already have taken care of, the other part is in the openhabian setup.

The changes required are small:

1. In `/etc/systemd/system/frontail.service`:
    add `/var/log/openhab/HABApp.log` to `ExecStart=/usr/lib/node_modules/frontail/bin/frontail...`

2. In `/usr/lib/node_modules/frontail/preset/openhab.json`:
    add `"/var/log/openhab/HABApp.log": "text-align: right; font-size: 0.8em; border-top: 2px solid #F8F8F8;",` in the lines section. (Just realised that i forgot to update the `openhab_dark.json` as well!!)

I have tried to incorporate this into the openhabian installation scripts, but even if the function below works well,
I don't know how to handle the interdependency between frontail and HAPApp, since they can be installed and removed independently of each other. To have the code below in both `setup_frontail` and `setup_habapp` is quite messy and I think the function is too specialised to fit in `helpers.bash`.

I would greatly appreciate if I could get some guidance on where I should add this function so I can submit it as a PR.

```
## Function for integrating HABApp logs with frontail
## Valid arguments: "install" or "remove"
##
##    habapp_frontail_integration()
##
habapp_frontail_integration() {
  local frontailService="/etc/systemd/system/frontail.service"
  local frontailJSON="/usr/lib/node_modules/frontail/preset/openhab.json"
  local habappLogFile="/var/log/openhab/HABApp.log"
  local openhabLogFile="/var/log/openhab/openhab.log"

  if [[ $1 == "remove" ]]; then
    echo -n "$(timestamp) [openHABian] Removing HABApp-frontail log integration ... "
    if ! cond_redirect sed -i "/^ExecStart=/ s= ${habappLogFile}==" "${frontailService}"; then echo "FAILED (update frontail service file)"; return 1; fi
    if ! cond_redirect sed -i "\\=${habappLogFile}=d" "${frontailJSON}"; then echo "FAILED (update frontail preset file)"; return 1; fi
    if ! cond_redirect systemctl -q daemon-reload &> /dev/null; then echo "FAILED (daemon-reload)"; return 1; fi
    if cond_redirect systemctl restart frontail.service; then echo "OK"; else echo "FAILED (restart frontail)"; return 1; fi

    if [[ -n "$INTERACTIVE" ]]; then
      whiptail --title "HABApp-frontail log integration removed" --msgbox "We permanently removed the HABApp-frontail log integration from your system." 7 80
    fi
    return 0;
  fi
  if [[ $1 != "install" ]]; then return 1; fi

  echo -n "$(timestamp) [openHABian] Installing HABApp-frontail log integration ... "
  if [[ $( ! grep -q "^ExecStart=.*${habappLogFile}" "${frontailService}" ) ]]; then
    if ! cond_redirect sed -i "/^ExecStart=/ s=\$= ${habappLogFile}=" "${frontailService}"; then echo "FAILED (update frontail service file)"; return 1; fi
  fi
  if [[ $( ! grep -q "${habappLogFile}" "${frontailJSON}" ) ]]; then
    if ! cond_redirect sed -i "\\=${openhabLogFile}=p; s=${openhabLogFile}=${habappLogFile}=" "${frontailJSON}"; then echo "FAILED (update frontail preset file)"; return 1; fi
  fi
  if ! cond_redirect systemctl -q daemon-reload &> /dev/null; then echo "FAILED (daemon-reload)"; return 1; fi
  if cond_redirect systemctl restart frontail.service; then echo "OK"; else echo "FAILED (restart frontail)"; return 1; fi


  if [[ -n "$INTERACTIVE" ]]; then
    whiptail --title "HABApp-frontail log integration installed" --msgbox "HABApp-frontail log integration was successfully installed on your system." 7 80
  fi
  return 0;

}

```

**Comment by magnuslsjoberg** [comment]
I just realised that perhaps it could be a general option in openhabian-config, where one can add any log to frontail?

**Comment by ecdye** [comment]
This is a very reasonable and thoughtful request. I'll take a look and see what we can do.
