### ISSUE TITLE
CPU speed

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1447]
Despite of the 'cpufrequtils' package installed & configured I keep seeing that my Raspi keeps running at minimum frequency
"powersave" is probably the default somewhere but I have not found out so far where it's overriding the cpufrequtils setting (which is "ondemand" which is what we want).

Workaround: add another service with a timer "on boot" (or make it part of the start script of zram or openhab?)

echo "ondemand">/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

**Comment by ecdye** [comment]
No, this is not correct. I have not had issues on my end, it has been persistent on my end, perhaps just your box?

**Comment by mstormi** [comment]
yeah but possibly others, too ? So it should not do harm to set it, should it ?

**Comment by ecdye** [comment]
Perhaps, but I just don't like the idea of creating another service, I feel like we have so many already and we have had so many issues with them. Let me look into it and see if there is a better solution that persists across reboots for everyone.

**Comment by mstormi** [comment]
ok but it would be a one-time service (no running one), we could even remove the cpufrequtils again

**Comment by mstormi** [comment]
ok if you don't mind I'll add that echo line above to openhabian_config startup and re-remove the extra cpufrequtils install (it's still installed in needed_packages() on unattended install)

**Comment by mstormi** [comment]
re-open if you find any reason why governor is set to powersave
