### ISSUE TITLE
Add MapDB persistence to openHABian

### ISSUE THREAD

**Issue by scatterthought** [openhab/openhabian#1450]
## Issue information:
I've noticed in the OH Community that some people are confused by the fact that RRD4j persistence only works for numeric items. As a result, they have to go through the added step of installing MapDB and configuring .persist strategies in text files. This has also led to questions about which service should be the "Default" in the OH3 UI (which should still be RRD4j).

With this in mind, I propose configuring openHABian to install MapDB and have basic persistence strategies in place for RRD4j and MapDB. This would enable openHABian to specify that MapDB be used for restoreonstartup (instead of RRD4j), and avoid confusion over which service should be set as the "Default" in the OH3 UI. It would also provide users with a solid foundation in case they want to learn more about (and adjust) their persistence strategies.

This is definitely a "Nice to have" feature request, and not at all a priority. However, I think it would be beneficial for new users and eliminate the "why aren't my string or datetime items restoring" questions we've seen a few times.

Thanks for your consideration. Keep up the good work!

**Comment by mstormi** [comment]
Hmm, I see your motivation but this request does not really match what openHABian is. openHABian does not provide any openHAB config whatsoever, and what you want/need is right that. We could provide an "ALL" mapdb.persist but that's pointless as that would AFAIK be the default if there's no config file.
Bottom line though is we would need to enable mapdb persistence in the *openHAB config*. But that is independent of openHABian and that we cannot (and don't want to) mess with.

**Comment by scatterthought** [comment]
Sounds goodMakes sense to me. Thanks @mstormi!
