### ISSUE TITLE
Additional link local address gets assigned

### ISSUE THREAD

**Issue by eikowagenknecht** [openhab/openhabian#1456]
## Issue information:
I encountered an issue with the homematic binding (https://github.com/openhab/openhab-addons/issues/10075) that led me to  investigate the network part of openhabian.

In short: On my openHAB3 Raspberry Pi there is an additional link local IP address and a route:

```
openhabian@pi-openhab3:~ $ hostname -I
192.168.40.39 169.254.246.159 2a02:8108:8f80:a68:1a24:542e:6c72:fb51 2a02:8108:8f80:a68:ecc7:227:6b65:6de4
openhabian@pi-openhab3:~ $ route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.40.1    0.0.0.0         UG    202    0        0 eth0
169.254.0.0     0.0.0.0         255.255.0.0     U     202    0        0 eth0
192.168.40.0    0.0.0.0         255.255.255.0   U     202    0        0 eth0
```

This is on a fresh install of v1.6.3 (literally did nothing but write it on the SD card, changed the hostname in the config file and SSHed into it.

After installing some addons etc. it looks like this:

![image](https://user-images.githubusercontent.com/1475672/107131404-2ea83e00-68d6-11eb-92be-27ba9766cc31.png)

So some ports (for example homematic from the above linked issue) are bound to the wrong ip address.

On my older installation of openHAB2 (also older openhabian version) there is no such address:

```
[22:25:11] openhabian@pi-openhab:~$ hostname -I
192.168.40.32 2a02:8108:8f80:a68:ea7:2bbc:83e:2f6f
[22:25:13] openhabian@pi-openhab:~$ route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.40.1    0.0.0.0         UG    202    0        0 eth0
192.168.40.0    0.0.0.0         255.255.255.0   U     202    0        0 eth0
[23:46:31] openhabian@pi-openhab:~$
```

Both are on identical hardware (Raspberry Pi 4) and on the same network switch.

I'm sure this is an issue of obenhabian but currently I can't figure out anything else that might be causing it.

So I'm foremost interested in knowing if it is supposed to look like it does in my openhab3 installation.

Thanks!

**Comment by ecdye** [comment]
Do you have both WiFi and Ethernet enabled? I can't think of any other reason DHCP would assign multiple IP addresses to a single box. Perhaps it is a bug with your DHCP server?

**Comment by eikowagenknecht** [comment]
No, fresh install, only ethernet is connected. Wifi has never been set up (no user/pass).

Can't say for sure if it might be related to my DHCP server. Can't swap that one out so easily. For all my other Raspberry PIs (5 currently) this does not happen though.

This command apparently fixes it: `sudo dhclient -v -r eth0`

```
openhabian@pi-openhab-test:~ $ hostname -I
192.168.40.39 169.254.246.159 2a02:8108:8f80:a68:1a24:542e:6c72:fb51 2a02:8108:8f80:a68:ecc7:227:6b65:6de4
openhabian@pi-openhab-test:~ $ sudo dhclient -v -r eth0
[sudo] password for openhabian:
Internet Systems Consortium DHCP Client 4.4.1
Copyright 2004-2018 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/

Listening on LPF/eth0/dc:a6:32:41:e1:96
Sending on   LPF/eth0/dc:a6:32:41:e1:96
Sending on   Socket/fallback
DHCPRELEASE of 192.168.40.39 on eth0 to 192.168.40.1 port 67
openhabian@pi-openhab-test:~ $ hostname -I
192.168.40.39 2a02:8108:8f80:a68:1a24:542e:6c72:fb51 2a02:8108:8f80:a68:ecc7:227:6b65:6de4
openhabian@pi-openhab-test:~ $ sudo dhclient -v eth0
Internet Systems Consortium DHCP Client 4.4.1
Copyright 2004-2018 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/

Listening on LPF/eth0/dc:a6:32:41:e1:96
Sending on   LPF/eth0/dc:a6:32:41:e1:96
Sending on   Socket/fallback
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 8
DHCPOFFER of 192.168.40.39 from 192.168.40.1
DHCPREQUEST for 192.168.40.39 on eth0 to 255.255.255.255 port 67
DHCPACK of 192.168.40.39 from 192.168.40.1
RTNETLINK answers: File exists
Warning: The unit file, source configuration file or drop-ins of systemd-timesyncd.service changed on disk. Run 'systemctl daemon-reload' to reload units.
bound to 192.168.40.39 -- renewal in 255481 seconds.
openhabian@pi-openhab-test:~ $
```

But it only lasts until the next reboot.

I'm starting to wonder it this could be a raspberry hardware problem: https://github.com/raspberrypi/linux/issues/3108, https://github.com/raspberrypi/linux/pull/3121. But adding `genet.force_reneg=y` to cmdline.txt did not help. Ethernet startup is also fine.. I guess?

```
openhabian@pi-openhab-test:~ $ dmesg | grep bcmg
[    1.325471] bcmgenet fd580000.ethernet: GENET 5.0 EPHY: 0x0000
[    1.343541] libphy: bcmgenet MII bus: probed
[    8.257345] bcmgenet fd580000.ethernet: configuring instance for external RGMII (RX delay)
[    8.257789] bcmgenet fd580000.ethernet eth0: Link is Down
[   12.393831] bcmgenet fd580000.ethernet eth0: Link is Up - 1Gbps/Full - flow control off
openhabian@pi-openhab-test:~ $
```

I'll switch the raspberrys (openHAB2 and openHAB3) tomorrow and see what happens..

**Comment by eikowagenknecht** [comment]
Ok so I tried to redo this with my Raspberry Pi that is known to be working (e.g just a normal 192.168.* ip ülus one ipv6) with the openHAB2 installation. 

I took out the openHAB2 SD card and inserted a **freshly flashed** openhabian 1.6.3 into the same Raspberry. The only thing changed there was the hostname to pi-openhab-test2 in the config file. No other changes (same physical port, same cable, same DHCP etc.).

On a very quick SSH into it, just after the Pi started responding to pings, it shows the problem again. Notice the hostname openhabian, so I guess the openhabian config script has not yet run at this point of time and set the hostname to pi-openhab-test2:

**First boot**

```
openhabian@openhabian:~ $ hostname -I
169.254.112.250 192.168.40.32
```

```
openhabian@openhabian:~ $ ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 169.254.112.250  netmask 255.255.0.0  broadcast 169.254.255.255
        inet6 fe80::905b:8dfb:eaff:3d0  prefixlen 64  scopeid 0x20<link>
        ether dc:a6:32:64:f2:06  txqueuelen 1000  (Ethernet)
        RX packets 10799  bytes 14505748 (13.8 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2445  bytes 178578 (174.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 13  bytes 1004 (1004.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 13  bytes 1004 (1004.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 62:69:9e:71:77:2c  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

```
openhabian@openhabian:~ $ route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.40.1    0.0.0.0         UG    100    0        0 eth0
0.0.0.0         192.168.40.1    0.0.0.0         UG    202    0        0 eth0
169.254.0.0     0.0.0.0         255.255.0.0     U     100    0        0 eth0
169.254.0.0     0.0.0.0         255.255.0.0     U     202    0        0 eth0
192.168.40.0    0.0.0.0         255.255.255.0   U     202    0        0 eth0
```

**Second boot*
After some time and the first automatic reboot the hostname changes to pi-openhab-test2, but all command outputs stay the same. Some more commands tried:

** More commands tried**
```
openhabian@pi-openhab-test2:~ $ sudo dhclient -v -r eth0
Internet Systems Consortium DHCP Client 4.4.1
Copyright 2004-2018 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/

Listening on LPF/eth0/dc:a6:32:64:f2:06
Sending on   LPF/eth0/dc:a6:32:64:f2:06
Sending on   Socket/fallback
```

```
openhabian@pi-openhab-test2:~ $ sudo dhclient -v eth0
Internet Systems Consortium DHCP Client 4.4.1
Copyright 2004-2018 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/

Listening on LPF/eth0/dc:a6:32:64:f2:06
Sending on   LPF/eth0/dc:a6:32:64:f2:06
Sending on   Socket/fallback
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 7
DHCPOFFER of 192.168.40.32 from 192.168.40.1
DHCPREQUEST for 192.168.40.32 on eth0 to 255.255.255.255 port 67
DHCPACK of 192.168.40.32 from 192.168.40.1
RTNETLINK answers: File exists
Warning: The unit file, source configuration file or drop-ins of systemd-timesyncd.service changed on disk. Run 'systemctl daemon-reload' to reload units.
bound to 192.168.40.32 -- renewal in 287531 seconds.
```

```
openhabian@pi-openhab-test2:~ $ ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 169.254.112.250  netmask 255.255.0.0  broadcast 169.254.255.255
        inet6 fe80::905b:8dfb:eaff:3d0  prefixlen 64  scopeid 0x20<link>
        ether dc:a6:32:64:f2:06  txqueuelen 1000  (Ethernet)
        RX packets 2329  bytes 333556 (325.7 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1102  bytes 167592 (163.6 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 38  bytes 3154 (3.0 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 38  bytes 3154 (3.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 6e:1a:59:ae:c1:d2  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

```
openhabian@pi-openhab-test2:~ $ hostname -I
169.254.112.250 192.168.40.32
```

```
openhabian@pi-openhab-test2:~ $ ip a show eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether dc:a6:32:64:f2:06 brd ff:ff:ff:ff:ff:ff
    inet 169.254.112.250/16 brd 169.254.255.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
    inet 192.168.40.32/24 brd 192.168.40.255 scope global dynamic noprefixroute eth0
       valid_lft 604267sec preferred_lft 528667sec
    inet6 2a02:8108:8f80:a68:7a2f:d4bc:5e37:596/64 scope global dynamic mngtmpaddr noprefixroute
       valid_lft 6987sec preferred_lft 3387sec
    inet6 2a02:8108:8f80:a68:645:b6d1:e825:a2f0/64 scope global dynamic noprefixroute
       valid_lft 6987sec preferred_lft 3387sec
    inet6 fe80::905b:8dfb:eaff:3d0/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
```

After some time the ipv6 adresses also show up:
```
openhabian@pi-openhab-test2:~ $ hostname -I
169.254.112.250 192.168.40.32 2a02:8108:8f80:a68:7a2f:d4bc:5e37:596 2a02:8108:8f80:a68:645:b6d1:e825:a2f0
```

**Temporary fix**
Restarting the network interface seems to help:
```
openhabian@pi-openhab-test2:~ $ sudo ip addr flush eth0 && sudo systemctl restart networking
```

```
openhabian@pi-openhab-test2:~ $ ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.40.32  netmask 255.255.255.0  broadcast 192.168.40.255
        ether dc:a6:32:64:f2:06  txqueuelen 1000  (Ethernet)
        RX packets 7321  bytes 1112713 (1.0 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 3073  bytes 457974 (447.2 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
...
```

```
openhabian@pi-openhab-test2:~ $ hostname -I
192.168.40.32
```

But after a reboot... it's back to the problematic state again :-(

```
openhabian@pi-openhab-test2:~ $ hostname -I
169.254.112.250 192.168.40.32
```
```
openhabian@pi-openhab-test2:~ $ ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 169.254.112.250  netmask 255.255.0.0  broadcast 169.254.255.255
        inet6 fe80::905b:8dfb:eaff:3d0  prefixlen 64  scopeid 0x20<link>
        ether dc:a6:32:64:f2:06  txqueuelen 1000  (Ethernet)
        RX packets 438  bytes 58841 (57.4 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 346  bytes 53221 (51.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```
```
openhabian@pi-openhab-test2:~ $ ip a show eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether dc:a6:32:64:f2:06 brd ff:ff:ff:ff:ff:ff
    inet 169.254.112.250/16 brd 169.254.255.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
    inet 192.168.40.32/24 brd 192.168.40.255 scope global dynamic noprefixroute eth0
       valid_lft 604739sec preferred_lft 529139sec
    inet6 fe80::905b:8dfb:eaff:3d0/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
```


**Results**
- Old openhabian -> No problem
- New openhabian 1.6.3 on the same hardware, same network etc. -> Wrong /duplicate IP assignment from DHCP, can be fixed temporarily with a reset of eth0

The only thing that changed is the software (openhabian). I can't see what else could be causing this. Maybe you have another idea?

I do understand that this doesn't seem to happen in your installations though, which makes it quite hard to track down :-(

**Comment by eikowagenknecht** [comment]
Ok, this gets even weirder. I just plugged the card back into the second Pi and on the first boot there, only the correct IP address got assigned (yay, but why?). After the next reboot, the additional 169.254.* showed up again. Some more reboots and I noticed that in maybe 1 out of 10 cases it works and in the others it doesn't.

I just now noticed that plugging it into my router directly (fritzbox) seems to make it work. All other devices are connected to a Unifi 24port switch. So that sounds like it could be somehow related to the RPi hardware issue I linked above, even though none of the commands found there fix it for me :-(

It still is weird, why this **never** happens on the older openhabian with openHAB2, though.

**Comment by ecdye** [comment]
The OH2 image probably is running an older kernel version. I'm honestly not sure about what would cause this. What happens if you disable IPv6? You can change `/etc/openhabian.conf` the line reading `ipv6=enable` and then run `sudo openhabian-config` and it should disable it after the next reboot.

The most difficult thing about this issue is that nothing major has changed since we stopped actively developing for OH2. Is it possibly due to the way that the OH addon you are using interacts with the network interfaces?

Also thank you very much for being proactive and providing helpful debug information and searching for the solution on your own.

My best guess in this case is that it is a hardware issue and I would suggest providing this info to the kernel guys for RPi and see if they can offer a solution.

**Comment by mstormi** [comment]
> It still is weird, why this **never** happens on the older openhabian with openHAB2, though

We didn't really change anything in openHABian networking but 1.6.3 image is built on top of a new Raspi OS version so that's probably what brought this in.
169.254.0.0/16 actually is a special address range that is guaranteed not to conflict with officially assigned adresses if you use it internally. If I was to guess there has been a change in dhcpcd.
Then again, what's the deal with this ? Would we need to disable it ?
(possibly yes, I remember I also had trouble on my system because I think it was homegear had bound itself to the wrong address)

**Comment by eikowagenknecht** [comment]
> The OH2 image probably is running an older kernel version.

Nope, both showed  "Kernel = Linux 5.4.83-v7l+" when this started. Trying to fix this I updated the Kernel to "Kernel = Linux 5.10.11-v7l+" but nothing changed at all.

> I'm honestly not sure about what would cause this. What happens if you disable IPv6? You can change `/etc/openhabian.conf` the line reading `ipv6=enable` and then run `sudo openhabian-config` and it should disable it after the next reboot.

Not tested yet, thanks for the input, will try that later today.

> The most difficult thing about this issue is that nothing major has changed since we stopped actively developing for OH2. Is it possibly due to the way that the OH addon you are using interacts with the network interfaces?

Since it happens on a freshly flashed image of openhabian 1.6.3 I think we can safely rule out addons at this stage.

> My best guess in this case is that it is a hardware issue and I would suggest providing this info to the kernel guys for RPi and see if they can offer a solution.

I will try a few more things and gather more data and then I will certainly do so.

> We didn't really change anything in openHABian networking but 1.6.3 image is built on top of a new Raspi OS version so that's probably what brought this in.

Seems likely. So if you want to close this issue I understand and will try to follow this up upstream (raspi kernel devs?). I'm quite certain it has to do something with STP, because when I enable it on my UniFi switch the problematic behaviour starts and it shows "STP blocking" on the port the openhabian 1.6.3 is connected to for quite a while before it switches to "normal":

![image](https://user-images.githubusercontent.com/1475672/107195122-3ad4ee00-69f1-11eb-9b3d-5a5efe6419a5.png)

![image](https://user-images.githubusercontent.com/1475672/107195238-5dff9d80-69f1-11eb-87d7-0fe72fac1951.png)

**New finding**
Comparing the "broken state" to the "working state" this is what I get in dmesg output:

Broken (STP enabled):
```
[    7.925972] bcmgenet fd580000.ethernet: configuring instance for external RGMII (RX delay)
[    7.927782] bcmgenet fd580000.ethernet eth0: Link is Down
[    7.972760] Adding 614396k swap on /dev/zram0.  Priority:75 extents:1 across:614396k SSFS
[    8.755562] systemd-journald[107]: Received SIGTERM from PID 1 (systemd).
[    8.755950] systemd[1]: Stopping Journal Service...
[    9.232243] systemd[1]: systemd-journald.service: Succeeded.
[    9.234649] systemd[1]: Stopped Journal Service.
[    9.242709] systemd[1]: systemd-journald-dev-log.socket: Succeeded.
[    9.244256] systemd[1]: Closed Journal Socket (/dev/log).
[    9.246085] systemd[1]: systemd-journald.socket: Succeeded.
[    9.247565] systemd[1]: Closed Journal Socket.
[    9.249293] systemd[1]: systemd-journald-audit.socket: Succeeded.
[    9.250786] systemd[1]: Closed Journal Audit Socket.
[    9.382721] zram: Added device: zram1
[    9.387207] zram1: detected capacity change from 0 to 524288000
[    9.387558] zram: Can't change algorithm for initialized device
[    9.732842] EXT4-fs (zram1): mounted filesystem with ordered data mode. Opts: (null)
[    9.732887] ext4 filesystem being mounted at /opt/zram/zram1 supports timestamps until 2038 (0x7fffffff)
[   10.337339] zram: Added device: zram2
[   10.341759] zram2: detected capacity change from 0 to 524288000
[   10.342099] zram: Can't change algorithm for initialized device
[   10.678070] EXT4-fs (zram2): mounted filesystem with ordered data mode. Opts: (null)
[   10.678116] ext4 filesystem being mounted at /opt/zram/zram2 supports timestamps until 2038 (0x7fffffff)
[   10.782252] systemd[1]: Listening on Journal Socket.
[   12.072971] bcmgenet fd580000.ethernet eth0: Link is Up - 1Gbps/Full - flow control off
[   12.073031] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[   14.536456] Bluetooth: Core ver 2.22
[   14.536566] NET: Registered protocol family 31
[   14.536583] Bluetooth: HCI device and connection manager initialized
[   14.536613] Bluetooth: HCI socket layer initialized
[   14.536636] Bluetooth: L2CAP socket layer initialized
[   14.536670] Bluetooth: SCO socket layer initialized
[   14.546044] Bluetooth: HCI UART driver ver 2.3
[   14.546065] Bluetooth: HCI UART protocol H4 registered
[   14.546185] Bluetooth: HCI UART protocol Three-wire (H5) registered
[   14.546499] Bluetooth: HCI UART protocol Broadcom registered
[   14.821854] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   14.821878] Bluetooth: BNEP filters: protocol multicast
[   14.821913] Bluetooth: BNEP socket layer initialized
[   47.975870] ICMPv6: process `dhcpcd' is using deprecated sysctl (syscall) net.ipv6.neigh.eth0.retrans_time - use net.ipv6.neigh.eth0.retrans_time_ms instead
```

Working:
```
[    7.944085] bcmgenet fd580000.ethernet: configuring instance for external RGMII (RX delay)
[    7.945824] bcmgenet fd580000.ethernet eth0: Link is Down
[    8.694158] systemd-journald[111]: Received SIGTERM from PID 1 (systemd).
[    8.696903] systemd[1]: Stopping Journal Service...
[    9.108341] systemd[1]: systemd-journald.service: Succeeded.
[    9.111439] systemd[1]: Stopped Journal Service.
[    9.118944] systemd[1]: systemd-journald-dev-log.socket: Succeeded.
[    9.120576] systemd[1]: Closed Journal Socket (/dev/log).
[    9.122395] systemd[1]: systemd-journald.socket: Succeeded.
[    9.124381] systemd[1]: Closed Journal Socket.
[    9.126155] systemd[1]: systemd-journald-audit.socket: Succeeded.
[    9.127708] systemd[1]: Closed Journal Audit Socket.
[    9.292107] zram: Added device: zram1
[    9.297225] zram1: detected capacity change from 0 to 524288000
[    9.297570] zram: Can't change algorithm for initialized device
[    9.641801] EXT4-fs (zram1): mounted filesystem with ordered data mode. Opts: (null)
[    9.641848] ext4 filesystem being mounted at /opt/zram/zram1 supports timestamps until 2038 (0x7fffffff)
[   10.240095] zram: Added device: zram2
[   10.244723] zram2: detected capacity change from 0 to 524288000
[   10.245099] zram: Can't change algorithm for initialized device
[   10.585785] EXT4-fs (zram2): mounted filesystem with ordered data mode. Opts: (null)
[   10.585832] ext4 filesystem being mounted at /opt/zram/zram2 supports timestamps until 2038 (0x7fffffff)
[   10.687862] systemd[1]: Listening on Journal Socket.
[   12.073024] bcmgenet fd580000.ethernet eth0: Link is Up - 1Gbps/Full - flow control off
[   12.073081] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[   13.926752] ICMPv6: process `dhcpcd' is using deprecated sysctl (syscall) net.ipv6.neigh.eth0.retrans_time - use net.ipv6.neigh.eth0.retrans_time_ms instead
[   14.407808] Bluetooth: Core ver 2.22
[   14.407954] NET: Registered protocol family 31
[   14.407973] Bluetooth: HCI device and connection manager initialized
[   14.408004] Bluetooth: HCI socket layer initialized
[   14.408030] Bluetooth: L2CAP socket layer initialized
[   14.408083] Bluetooth: SCO socket layer initialized
[   14.433275] Bluetooth: HCI UART driver ver 2.3
[   14.433303] Bluetooth: HCI UART protocol H4 registered
[   14.433440] Bluetooth: HCI UART protocol Three-wire (H5) registered
[   14.433792] Bluetooth: HCI UART protocol Broadcom registered
[   14.869990] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   14.870010] Bluetooth: BNEP filters: protocol multicast
[   14.870041] Bluetooth: BNEP socket layer initialized
```

Major difference is the timing of the dhcpcd message. My completely uneducated guess is that with STP enabled, the DHCP assignment takes too long (don't know why) and because of that a link local address (169.254.*) gets assigned that later is then complemented by the "real" address. Or something like that.

So from my testing so far it seems to be:
- An underlying OS problem (not openhabian itselt but raspi os or kernel)
- Somehow related to the combination of Raspberry Pi 4 and certain switches (e.g. my UniFi switch)
- Somehow related to STP (at least in combination with my UniFi switch)
- Somehow related to DHCP

Thanks to both of you for providing input!

**Comment by mstormi** [comment]
Spanning tree peers make use of that APIPA IP address to communicate.
I'd disable STP. Granted it's running on my switches, too, but who needs that ?
You won't want your openhabian to become a bridge. If I was you I'd google for more on that address range in combo with STP.
Look for dhcpcd config or kernel parameters to turn STP off and let us know if you find anything.

**Comment by mstormi** [comment]
See https://serverfault.com/questions/132657/where-does-the-route-to-169-254-0-0-comes-from for a possible fix.

**Comment by eikowagenknecht** [comment]
Seems like this is quite sometimes a problem with STP and DHCP: https://community.ui.com/questions/IP-assigning-can-be-too-slow/3f990e01-60c5-40f2-aa50-c01c5b0fdbce

So I guess disabling the zeroconf address should help. I'll try the fix in your link soon. Maybe this was disabled in older versions by default?

**Comment by eikowagenknecht** [comment]
> See https://serverfault.com/questions/132657/where-does-the-route-to-169-254-0-0-comes-from for a possible fix.

Unfortunately that link doesn't work for raspi os because the config file mentiones doesn't exist (it's based on redhat). But I found https://www.raspberrypi.org/forums/viewtopic.php?t=224511 instead.

> Try adding "noipv4ll" in dhcpcd.conf. See "man dhcpcd.conf"
This fixed it for me.

I think it would help avoid this problem for some users (e.g. me) and I can't think of a reason why someone would need a link local address on an openHAB Pi.

It's up to you of course to decide if you want to implement this is the general distribution by default. Or maybe as an option in the config tool so it can be easily changed.

**Comment by mstormi** [comment]
worked for me, too

**Comment by eikowagenknecht** [comment]
Thanks!
