### ISSUE TITLE
Incomplete message after WiFi setup

### ISSUE THREAD

**Issue by eikowagenknecht** [openhab/openhabian#1457]
## Issue information:
I was just trying to switch to WiFi because of another issue and noticed that the text seems to be cut of in the "success" message (Please what?):

![image](https://user-images.githubusercontent.com/1475672/107145328-f427bb00-6940-11eb-924e-0cb1c13f55ea.png)

Using the current openHAB3 branch.

**Comment by ecdye** [comment]
I'll look into it.
