### ISSUE TITLE
Add NodeRED as optional component

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhabian#146]
> * This OH Node - https://www.npmjs.com/package/node-red-contrib-openhab22
> * BigTimer for setting schedules / sunrise-set events - https://flows.nodered.org/node/node-red-contrib-bigtimer
>  
> Those are the only 3rd party nodes I'm currently using. Another one, if they want more complete Astro replacement: https://flows.nodered.org/node/node-red-contrib-sunevents
> 
> Once key tutorial for more complex rules is around functions: http://nodered.org/docs/writing-functions.html

**Comment by kubawolanin** [comment]
Hey Thom, that's an awesome enhancement idea!

> This OH Node - https://www.npmjs.com/package/node-red-contrib-openhab22

The correct link to the npm package is here:
https://www.npmjs.com/package/node-red-contrib-openhab2

**Comment by ThomDietrich** [comment]
Hey @kubawolanin, for now it was just an idea but with more and more people interested I'll definitely look into it soon. I was going to switch frontail over from "optional" to "pre-installed". Node.js will hence be available on all openHABian systems in the future.
