### ISSUE TITLE
x86 install ?

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1461]
see https://community.openhab.org/t/oh3-is-not-recognizing-cpu-correctly/117323/7

At least when an openhabian.conf without hw= and hwarch= parameters is used, openhabian-config is writing back the default which is hw=pi4. That now makes future installs like java fail on x86.

Can you check what happens for a fresh install on x86? I'd guess it won't work either.

I think we should fix to dynamically determine arch and hw params rather than to take a default off a defaults file.

**Comment by ecdye** [comment]
@mstormi I think it is actaully an issue with the setup of our `openhabian.conf` I noticed this issue before in a different circumstance. What we need to do it add a space after every commented out line in `openhabian.conf` as without it bash won't treat it like a comment.

**Comment by mstormi** [comment]
no, #xxx are treasted as comments as well as # xxx

See update_openhabian_conf: when a parameter is missing that is in /opt/openhabian/openhabian.conf.dist
a) the line is copied there (but for hw and hwarch the lines in the template are commented out so it keeps them commented out)
and b) the line is freed of the comment AND evaluated. But the default in the template for hw and hwarch are rpi parameters
so now anyone running on x86 will be treated like on rpi i.e. as  if he used those params to "fake" his box into a rpi.

**Comment by ecdye** [comment]
Then we should not set them by default, simply make them set to `parameter=""` instead `parameter=rpi4`

**Comment by mstormi** [comment]
right, I've put up a PR to change the templates
