### ISSUE TITLE
image openhabian-pi-raspios32-v1.6.3b.img.xz is in zip format instead of in xz format

### ISSUE THREAD

**Issue by WolfgangSn** [openhab/openhabian#1465]
file openhabian-pi-raspios32-v1.6.3.img.xz openhabian-pi-raspios32-v1.6.3b.img.xz
openhabian-pi-raspios32-v1.6.3.img.xz:  XZ compressed data
openhabian-pi-raspios32-v1.6.3b.img.xz: Zip archive data, at least v2.0 to extract

according to the file extension the file openhabian-pi-raspios32-v1.6.3b.img.x should be in xz format.

**Comment by mstormi** [comment]
fixed on Github
