### ISSUE TITLE
sdrawcopy + sdrsync run on boot

### ISSUE THREAD

**Issue by joevie** [openhab/openhabian#1466]
I have freshly installed openhabian-pi-raspios32-v1.6.3b on Raspberry Pi 3+ update to -> [main]patchday-20210118-1214
mirror_SD activated and Backup SD inserted.
After a reboot I noticed that the system is very slow. The Journal shows that mirror_SD is running... ?
Made a systemd-analyze plot: both sdrsync.service and sdrawcopy.service are running parallel after network-online.target reached.
I thing it is not so good for the SD.
After some searching, I found out that it seems that the "Requires=" entrys causes the startup on boot. I have commented them out and now it is OK. Maybe the same for amanda and firemotd.

sdrawcopy.timer:
[Unit]
Requires=sdrawcopy.service

sdrsync.timer:
[Unit]
Requires=sdrsync.service

**Comment by mstormi** [comment]
Well to be mean it'll just hit people that are booting their box often (against all recommendation)
but you're of course right this should not happen.

**Comment by mstormi** [comment]
Then again I cannot confirm your observation it starts on _every_ boot. In fact I did not see _any_ dd start at all and was unable to reproduce what you said.

**Comment by ecdye** [comment]
> Then again I cannot confirm your observation it starts on _every_ boot. In fact I did not see _any_ dd start at all and was unable to reproduce what you said.

I have not had a chance to test recently, but when I made the change it did not do this on every boot either.

**Comment by joevie** [comment]
Sorry for the circumstances. After a new installation I ever check the boot process. 
But what should be different with my installation?
In my case only helped comment out the "Requires" line  in the timers.
e.g. #Requires=sdrsync.service

I can also trigger the service without reboot 
e.g.: systemctl enable --now  firemotd.timer 
Requires=firemotd.service ->  Starting FireMotD system updates check (randomly execute between 0:00:00 and 5:59:59)...
#Requires=sdrsync.service -> nothing happens

**Comment by ecdye** [comment]
@mstormi Have you tried again on a fresh install?

**Comment by joevie** [comment]
I can do it but need some time. 
openhabian-pi-raspios32-v1.6.3b -> enabled sdmirror in openhabian.config 
sdmirror my start during install but not after first reboot. Do you agree?

I would like to mention that I found my solution in a reddit post. I don't realy understand why but it works.

**Comment by mstormi** [comment]
> 
> 
> @mstormi Have you tried again on a fresh install?

no but I copied the current .timer/.service

On a sidenote why did you add the Required part ? Independent of this issue I think it's not required to have *the service* running, is it.


@joevie of course *if* you start the timer it'll run the service. That's intentional. But the timer should not trigger on reboot.
or did you *activate* sdrawdump.service ?

**Comment by ecdye** [comment]
It is simply a more explicit way to trigger the service. If it turns out that it causes issues in more than isolated cases it can be removed.

**Comment by mstormi** [comment]
Yes but it worked without didn't it. Any particular reason you added it ?

**Comment by ecdye** [comment]
> Yes but it worked without didn't it. Any particular reason you added it ?

No, there was no particular reason for it.

**Comment by mstormi** [comment]
Then please remove it. I think it's not right. The timer will *start* the service, the service is not a prerequisite.

**Comment by joevie** [comment]
Today I had the chance to test an other pi4,  fresh SD with raspios32-v1.6.3b and internet via LAN. I have not changed anything. 
After finish logged in via ssh and did a reboot. 
firemotd.service was triggered!

By the way, why is the b-image a main branch?  clonebranch=HEAD
I would probably never have noticed the issue otherwise. I also like it when the systems run for years without reboot!

**Comment by mstormi** [comment]
FWIW today I had a dd running on my test box after a boot. Turned out it still had the Requires=`sdrawcopy.service` that we've meanwhile removed from the code. So Requires: is harmful in fact.

**Comment by ecdye** [comment]
> FWIW today I had a dd running on my test box after a boot. Turned out it still had the Requires=`sdrawcopy.service` that we've meanwhile removed from the code. So Requires: is harmful in fact.

Interesting, weird that I never noticed this behavior when I originally tested.
