### ISSUE TITLE
Unlucky frontail format when using dark more on a mobile

### ISSUE THREAD

**Issue by Boby71** [openhab/openhabian#1467]
openHABian Version: „openhab3“
OH version: 3.1 (latest Snapshot)

When using frontail with dark mode on a mobile, the structure of the displayed data is a bit unlucky, especially in portrait mode. It‘s better in landscape, but the output would need some minor improvement as well. In both views there is not much to see and a lot of scrolling necessary.

Unfortunately it's not possible to upload any pictures, so the only description I can offer is this text.

**Comment by Boby71** [comment]
Screenshot can be found here: https://ibb.co/4Jf1ry5

**Comment by ecdye** [comment]
There is no way for us to fix this, this is all because logs are not designed to be read on a mobile webpage. Please use a desktop instead.
