### ISSUE TITLE
mirror mirror who is the fairest ...

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1469]
Following up on complaints on the forum a user cannot boot from a mirror SD he made of a mirror, it drops into emergency mode.
Duh.

Not ultimately clarified yet but educated guessing it's possibly because it cannot mount /dev/sdX3 as /storage.
Note that partition a) is created only if on running setup_mirror_SD, the external card is larger than the internal one and b) unlike partitions 1 & 2, it is not mirrored so does not exist on the mirror's mirror.

Not fully sure yet how to handle that best so writing it down in the first place. @ecdye let me know your opinion.
If someone has equal sized cards, it won't create the storage partition on mirror setup because the flashed image expands /dev/mmcblk0p2 to all available space but I didn't manage to avoid that (this is what #1254 is really about).
But if it's a mirror inserted to boot from it could exist there so we could check for existence of /dev/mmcblk0p3 in setup_mirror_SD() and dd-copy it, too. I believe it won't exist on flashed images but eventually on mirror cards.
And/or should we remove or at least disable the storage in `/etc/systemd/system/storage.mount` ?
[how does disabling work if you didn't boot from it but mounted "/" as "/mnt" or other? option to sysctl? Manually rm the link?]

**Comment by ecdye** [comment]
Honestly, after the first mirror for our sake and sanity I would say anything beyond that should be unsupported as the mirror is already a pretty good backup.

Also, nice title.

**Comment by mstormi** [comment]
Hmm. Thought that in the beginning, too, but what if someone really needs to resort to using the mirror, how would he need to proceed then to re-activate another mirror? Buy a half-the-size SD and amrestore, then switch to boot from there ? Awkward for newbies.
I'd guess he would expect it should work to re-select the SD mirror menu. Simple. But it won't, will it.
