### ISSUE TITLE
Zram logging issues

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1474]
I noticed the logrotate error on my system after a user reporting this.

Also, mirror_SD logging should be suppressed or redirected to some logfile.

openhabian@openhab:/var/log $ zgrep zram syslog*4*
Feb 28 00:00:02 openhab logrotate[12786]: error: error renaming /usr/local/share/zram-config/log/zram-config.log.4.gz to /usr/local/share/zram-config/log/zram-config.log.5.gz: Read-only file system
Feb 28 02:08:50 openhab mirror_SD[31807]: /opt/openhabian/functions/zram.bash
Feb 28 02:08:51 openhab mirror_SD[31807]: /opt/zram/log.bind/mosquitto/mosquitto.log

**Comment by ecdye** [comment]
OK, found the [issue](https://askubuntu.com/questions/1275668/logrotate-succeeds-when-manually-run-as-root-but-fails-with-read-only-file-sys), now I'm trying to think why I shouldn't just move logging to `/var/log` to make my life simpler.

**Comment by mstormi** [comment]
good find, you're never done learning. Yeah why not move it to /var/log/(/openhab ?)

**Comment by ecdye** [comment]
Because then it would cause issues with the zram device removal when the process is logging to the directory while unmounting the same directory. It results in failure to remove devices and data loss.
