### ISSUE TITLE
Dark theme in frontail: typo in openhab_dark.json

### ISSUE THREAD

**Issue by Interstellar0verdrive** [openhab/openhabian#1476]
## Issue information:
When I use frontail to read logs, and I have selected the dark theme, I notice there's a little inconsistency in the layout between light and dark theme when it comes to styling some log lines.
I went to check the json and css files and noticed that inside this file: 
/usr/lib/node_modules/frontail/preset/openhab_dark.json

These lines:

```
    "/var/log/openhab2/openhab.log": "text-align: right; font-size: 0.8em; border-top: 2px solid #F8F8F8;",
    "/var/log/openhab2/events.log": "text-align: right; font-size: 0.8em; border-top: 2px solid #F8F8F8;",
```

Should be:

```
    "/var/log/openhab/openhab.log": "text-align: right; font-size: 0.8em; border-top: 2px solid #F8F8F8;",
    "/var/log/openhab/events.log": "text-align: right; font-size: 0.8em; border-top: 2px solid #F8F8F8;",
```

## System information:
Raspberry Pi 4 Model B Rev 1.2
openHABian 3.0.1 Release Build

PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
armv7l

**Comment by mstormi** [comment]
openHABian shouldn't be using that file, it's probably an artefact of some older code version.
Check `/etc/systemd/system/frontail.service` for what's it currently using.

**Comment by Interstellar0verdrive** [comment]
If you install frontail (I did it through openhabian-config), and choose to use the dark theme in the settings, your` /etc/systemd/system/frontail.service` will have this line:

`ExecStart=/usr/lib/node_modules/frontail/bin/frontail --ui-highlight --ui-highlight-preset /usr/lib/node_modules/frontail/preset/openhab_dark.json -t openhab_dark -l 2000 -n 200 /var/log/openhab2/openhab.log /var/log/openhab2/events.log`

So the mentioned `/usr/lib/node_modules/frontail/preset/openhab_dark.json` is used.

**Comment by mstormi** [comment]
No current openHABian does not. You probably used an outdated version.

**Comment by ecdye** [comment]
@Interstellar0verdrive Make sure that you are using the `main` branch as it has the latest updates.

**Comment by Interstellar0verdrive** [comment]
Hey @ecdye 
I confirm I am on the `main` branch.
I reinstalled Frontail from openhabian-config. 
Result: the file `/usr/lib/node_modules/frontail/preset/openhab_dark.json` is still there, and still being called inside `/etc/systemd/system/frontail.service`, BUT the content has changed, and the lines I was refering to have been deleted. 
So I had an oudated version of that file, as @mstormi pointed out. Sorry for the waste of time!

**Comment by ecdye** [comment]
You are fine, mistakes happen. Glad it was resolved.
