### ISSUE TITLE
openHAB certificates

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1480]
Let's check what's needed to create certificates for openhab https through certbot (which gets installed as part of nginx setup)

See https://community.openhab.org/t/openhab-certbot-integration/118521

**Comment by mstormi** [comment]
Now I believe it is sufficient to install certbot and python3-certbot-nginx like we do when we install nginx
Installing these is taking care to renew packages
```
certbot certificates
systemctl list-timers
```
Only thing is, port 80 needs to be available to nginx (it normally is) AND open to the public, any router/firewall needs to direct incoming (NAT) requests to port 80 to the openhab machine running nginx - this can only be manually done on the firewall,
and people sensitive to security will only temporarily open/forward this port so it cannot work fully automated.

@ecdye Do you think we would need to do anything else about it ?

**Comment by ecdye** [comment]
I don't think so, that all sounds correct. We would probably want to provide some generalized instructions for how to port forward for those who don't know how.

**Comment by mstormi** [comment]
Docs exist for that: https://www.openhab.org/docs/installation/security.html#nginx-setup

Maybe you cross-check and eventually correct them again but they're ok at first glance. I think we're done here.
