### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by milkmansson** [openhab/openhabian#149]
Hi there; on the download elements on Git, an XZ file is presented for download.  I think for a noob like me, the path to finding a way to unpack the XZ file was problematic.  Tar on macos didn't recognise the file, nor unpack it when the type was forced (tar -xJf).  I ended up finding an eventual site which explained what I needed to do to a linux distro to get a tool called "unxz" to do the trick.  I then used the standard diskpart tool to unmount and then dd to create the image.

I don't know if this is me being silly, but if it helps, I struggled only with this part.  XZ isn't a format i recognised - I wonder if anyone else has that issue on other os's,... maybe worth using Zip, or, giving a note to say 'the XZ format can't be imaged, you have to find a way to unpack it first' or something?  Thanks to you and all the community for such a great effort!!

**Comment by ThomDietrich** [comment]
Hello @milkmansson,
I'm all-in for a good documentation and you are right, there are a few things the documentation is lacking. The problem you are talking about is covered... somehow: http://docs.openhab.org/installation/openhabian.html#raspberry-pi

> * Download the latest “openHABianPi” SD card image file
> * Write the image to your SD card (e.g. with Etcher)
> * Insert the SD card into the Raspberry Pi, connect Ethernet and power

Etcher will process the xz compressed image. No need to extract manually.

I get your concern and will be sure to update the documentation in the matter.

**Comment by milkmansson** [comment]
Cool guys... just thought I'd share what caught me as a noob.  Thanks heaps!

**Comment by ThomDietrich** [comment]
This should be fixed with https://github.com/openhab/openhabian/commit/c692d448a4c32b91b02f90930ab942f314b6898e
What do you think?

The article update will be available in the official documentation shortly.
