### ISSUE TITLE
Unable to fix file permissions after fresh install of openhabian op RPI4

### ISSUE THREAD

**Issue by sceppi** [openhab/openhabian#1492]
## Issue information:
I just freshly installed openhabian (1.6.4) on a new Pi4B (an upgrade from my previous Pi3B)

In the first-boot.log, there are 2 errors:

`2021-03-24_13:53:10_CET [openHABian] Applying miscellaneous system settings... realpath: '': No such file or directory
FAILED (setcap java)`

`2021-03-24_13:55:10_CET [openHABian] Applying file permissions recommendations... FAILED (openhab log on zram)`

For the rest , openhabian and openhab installed fine. I then wanted to fix file permissions  in the openhabian-config. There I get the error:

>   │ There was an error or interruption during the execution of:                  │
                                                                              │   "10 | Apply Improvements"   

I've put debugmode to maximum. Below is the debug information

## Debug information:
See attached txt file 
[Debug info.txt](https://github.com/openhab/openhabian/files/6197595/Debug.info.txt)

## System information:
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
armv7l

**Comment by mstormi** [comment]
Thanks for providing a debug log.
It's a cosmetic error only the fix_permissions routine proceeds.

@ecdye I saw the same two errors on a freshly installed box of mine, too
I [moved](https://github.com/openhab/openhabian/commit/d0a95f8bb2f6738e2b17fce45a2cca56225320cd) the Java setcap after java install
On the 2nd error my guess is /opt/zram/log.bind/openhab is empty at that stage.
Do you think it would do harm to move permissions_corrections AFTER zram setup? Or run it twice to be sure?

**Comment by ecdye** [comment]
I don't think it matters to much, I would test it before moving it to after zram install just to make sure.

**Comment by mstormi** [comment]
Ok I did a minimum test, the lowerFS is accessible after start (that dir in question which is probably dynamically generated on start).
It seems to work fine.
When you have tested too can you please move the permission_correction() call inside openhabian-setup.sh ?

**Comment by ecdye** [comment]
Will do, I'll try to get it done by this weekend.
