### ISSUE TITLE
nginx installation fails on clean install - openhabian install script does not show the prompts that are returned from certbot

### ISSUE THREAD

**Issue by rdiem** [openhab/openhabian#1493]
I prepared a SD card with Raspberry Pi Imager an openhabian 1.6.4.
After the setup completed I did connect via ssh and called sudo openhabian-config
I navigated through the menu to 44 Reverse Proxy and selected Yes when promting for securing the interface with https.
I entered my domain and the installation started.
It stucks at nginx: configuration file /etc/nginx/nginx.conf test is successful

I did view the script in the repo that is performing those steps and this is the point where the certbot is trying to obtain a certificate from letsencrypt.
In /var/log/letsencrypt/letsencrypt.log I see the entry: certbot.plugins.selection:Single candidate plugin: * webroot

When I enter an email adress in the console where the installation stucks the letsencrypt.log proceeds with the following messages:
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = certbot.plugins.webroot:Authenticator
Initialized: <certbot.plugins.webroot.Authenticator object at 0xb52d2c70>
Prep: True
2021-03-26 00:38:57,175:DEBUG:certbot.plugins.selection:Selected authenticator <certbot.plugins.webroot.Authenticator object at 0xb52d2c70> and installer None
2021-03-26 00:38:57,175:INFO:certbot.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2021-03-26 00:39:44,382:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2021-03-26 00:39:44,389:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2021-03-26 00:39:45,075:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 658
2021-03-26 00:39:45,078:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Thu, 25 Mar 2021 23:39:44 GMT
Content-Type: application/json
Content-Length: 658
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "jSeB91NYjeg": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}

**It seems that the openhabian install script does not show the prompts that are returned from certbot.** 

Openhabian 1.6.4
on RPI 4 4GB
 cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by mstormi** [comment]
Edit /opt/openhabian/functions/packages.bash line ~595 reading
`if cond_redirect certbot certonly --webroot -w /var/www/"$domain" -d "$domain"; then echo "OK"; else echo "FAILED"; return 1; fi`
Remove the `cond_redirect` and retry.

**Comment by rdiem** [comment]
I tried it right now and it works as expected. I get the prompts and the certificate ist installed. Thanks for your help.
