### ISSUE TITLE
I get 2 frontail warnings after upgrading to OH3 | frontail got not upgraded

### ISSUE THREAD

**Issue by Diapolo** [openhab/openhabian#1494]
After upgrading my Raspi4 2GB from OH2 to OH3 via openhabian-config I now see two warnings shown in frontail:

> [WARN ] [core.karaf.internal.FeatureInstaller] - The ui add-on 'dashboard' does not exist - ignoring it.
> [WARN ] [core.karaf.internal.FeatureInstaller] - The ui add-on 'paper' does not exist - ignoring it.

It seems there got some orphan entries left in some configuration files as these 2 UIs were removed AFAIK? Any hint where I can find these and remove the entries?

Also I had to reinstall Frontail in order to get rid if the OH2 title and style, that should or could be done by the upgrade script, or?

Thanks,
Dia

**Comment by mstormi** [comment]
> The ui add-on 'dashboard' does not exist - ignoring it.

This is an openHAB output and unrelated to openHABian.

> Also I had to reinstall Frontail in order to get rid if the OH2 title and style, that should or could be done by the upgrade script, or?

Sure but not everybody is using it so it's left to the user.
