### ISSUE TITLE
Permissions in ``/opt/habapp`` for user

### ISSUE THREAD

**Issue by spacemanspiff2007** [openhab/openhabian#1501]
Hello,

if a user installs HABApp through the ``openhabian-config`` he does not have permission to manually update packages in the venv.
Imho it is because HABApp gets installed with ``openhab:openhabian`` and the user logs in as ``openhabian:openhabian`` and the latter is missing execution and write privileges for (``/opt/habapp/``).
Should these privileges be added by the setup? Should I add an "update" button to the openhabian-config menu?
What is a good way to resolve this?

**Comment by mstormi** [comment]
make /opt/habapp group-writable for group openhabian ?

**Comment by mstormi** [comment]
Fixed by #1512
