### ISSUE TITLE
Replace bintray repos with artifactory

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1503]
See #1502, https://community.openhab.org/t/openhabian-frontail-log-doesnt-work-21-leads-to-error/121788 and probably others

Should we replace ALL bintray repos by their artifactory equivalents on openhabian-config startup ?
If we only do per-menu option this'll keep us busy telling people over and over.

Probably we should create a popup informing the user so he knows where to look should something go wrong.

**Comment by ecdye** [comment]
Sounds like a good idea to me, have we finished migrating all of the repos to artifactory yet?

**Comment by mstormi** [comment]
Would we need to backport our fix to the stable branch, too ?

**Comment by marcelser** [comment]
I definitly would opt for backporting. Cause anyone using openhab2 or OpenHAB3 (stable) branch will have this problems all of a sudden and like me at first have no clue how to resolve it.
