### ISSUE TITLE
new image needed?

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1510]
Look for "FAILED" in the debug log at the bottom of https://community.openhab.org/t/first-trial-of-oh3-on-rpi4-fails-from-fresh-openhabian-image-with-possible-solution/121951

Those on git  I cannot explain for the time being, but they're apparently not critical.
The one on java setcap (due to missing 'realpath' due to missing 'coreutils' package) I've opened #1509 for.

But the important one is when it tries to download from bintray so this still seems to be part of the image code ?
Image was created back at a time when bintray was still the 'right' repo, and it does not run fix_openhab_repo() as it does not do in offline mode. Changing the routine won't help (at least not in offline mode but probably it also can not be run at this early stage it would be needed in).
So I think we would need to create a new image and probably announce it as v1.6.5

**Comment by ecdye** [comment]
Seems fine to me.

**Comment by mstormi** [comment]
it's online

**Comment by ecdye** [comment]
I'm going to follow through on my words and delete the master branch now that the next release is live

**Comment by mstormi** [comment]
released
