### ISSUE TITLE
After update to openHABian 1.6.5 with OH2 Stable apt-update throws an error due to wrong file name

### ISSUE THREAD

**Issue by DigiH** [openhab/openhabian#1513]
I just updated to openHABian 1.6.5 while running the OH2 Stable branch and afterwards doing an apt-update throws the error

`N: Ignoring file 'openhab2.liste' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension`

Happened after accepting the new jfrog artifactory repo link, which is now in the new openhab2.list. 

Not sure why the old openhab2.list has been renamed to 'openhab2.liste' though, causing this.

**Comment by mstormi** [comment]
current openHABian code or upgrade did not cause so there's nothing to do about it. Just delete that file.

**Comment by DigiH** [comment]
That's what I immediately did. But other than doing

sudo apt-get update
sudo apt-get upgrade
(which both didn't come up with any issues) and then
sudo openhabian-config
with the update and new link confirmation
and immediately afterwards going a
sudo apt-get update
again, which came up with the wrong file name, it very much looks like the openhabian new link confirmation caused this, as nothing else fiddled with the sources.list files in this short time.

Was more of an FYI issue for you though, and was very unsure if logging anything would even be worth it.
