### ISSUE TITLE
[Feature Request] Please include FFMPEG at least in openhabian

### ISSUE THREAD

**Issue by houshasen** [openhab/openhabian#1517]
## Issue information:

Default inclusion of FFMPEG may improve ease for developer and user for integrating camera devices. If core version cannot include FFMPEG by default, I wonder if this can be considered as one of the useful tool within openHabian.

## Potential Use Cases

1. End user - May have easier time setting up IPCamera Binding for any camera with RTSP stream i.e. I could have skipped FFMPEG installation step and directly install IPCamera binding and immediately start setting up my camera stream within openHAB.
 
2. Developer - May be able to assume FFMPEG default installation existence and add it to their binding.

**Comment by mstormi** [comment]
I don't see any valid point in spending work on this, the number of people to benefit would be abysmally small.
Feel free to contribute and maintain it yourself, then we'll be happy to include it.
