### ISSUE TITLE
Remove Telldus

### ISSUE THREAD

**Issue by ecdye** [openhab/openhabian#1529]
As the telldus package is no longer maintained, we should remove support for it from openHABian because it has become increasingly difficult to maintain. 

@mstormi WDYT

**Comment by mstormi** [comment]
thought about it, too

@EliasGabrielsson I think you've added this long ago, right ? wdyt ?

**Comment by EliasGabrielsson** [comment]
Correct Marcus, I did initially add it. 
Kind of surprised that the script is failing as the driver haven't been updated from telldus in a while.
It's hard to say how well this part is used, however the binding in openhab is still mantained.

I can have a look on this module and try to fix arised hassle.

**Comment by ecdye** [comment]
The issue is that Telldus has never updated their stuff and some of the dependencies it uses have been removed from the more recent versions of linux the Debian/Ubuntu have been using.

**Comment by EliasGabrielsson** [comment]
I get the issue (Y). Everything can't be supported forever.
Found this though on the openhab forum: https://community.openhab.org/t/solved-telldus-core-depends-on-libconfuse-but-it-is-not-installable/89856/15
Looks like someone solved the issue already.

**Comment by ecdye** [comment]
Yes but is it reasonable to implement this? Or do we just stop providing support.

**Comment by EliasGabrielsson** [comment]
I would say drop it, if someone request it let's reconsider then.

**Comment by ThomDietrich** [comment]
Vaguely remember we added it pretty early on the journey. Agree to remove. If someone steps up to maintain its integrated suppor they can step forward 👍

**Comment by ecdye** [comment]
Thats what I thought, thanks for the insight.
