### ISSUE TITLE
OH branch in version string

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1542]
@ecdye could you add the openHAB repo and eventually version to the openHABian version that is displayed at the top?
You changed that last time so know best where to do it.
Eventually if it gets too long move the commit display to the "About" window  .

**Comment by ecdye** [comment]
Would it not be better to just put the openHAB version to the about window because it already displays on the login screen, and that way when people tell us what version of openHABian they are running they don't just automatically assume that we mean the openHAB version which is displayed very obviously on the openhabian-config title string.

**Comment by mstormi** [comment]
Hmm, the login screen is long gone so that , at least for me, doesn't work.
But your other point is valid. Yeah, let's put the openHAB branch(repo) and version into the 00 About screen.

**Comment by mstormi** [comment]
on a sidenote, I noticed you provided a replacement for the OH logo.
As far as I read it's compiled into some bundle.
Is there a simple way to exchange the logo ?

**Comment by mstormi** [comment]
On another sidenote, do you think https://github.com/openhab/openhab-distro/releases/tag/3.1.0#Upgrade-Process is correct ?
Kai didn't ask just took the 3.0 text.

**Comment by ecdye** [comment]
> On another sidenote, do you think https://github.com/openhab/openhab-distro/releases/tag/3.1.0#Upgrade-Process is correct ?

Yes that should work fine

> Is there a simple way to exchange the logo ?

Which logo are you referring to, the one displayed on login? If so, no there is not an easy way to replace it as it is openhabian specific.

> But your other point is valid. Yeah, let's put the openHAB branch(repo) and version into the 00 About screen.

Will do, probably won't happen until sometime on Wednesday or Thursday.

FWIW I am pretty sure that most people won't have the issue that you and I have where our login screen is several thousand lines in the past as we develop and use our systems in a pretty unusual way.

**Comment by mstormi** [comment]
> Which logo are you referring to, the one displayed on login?

no, the top-left openHAB logo of main UI

**Comment by ecdye** [comment]
Yes, that will be automatically updated now that OH 3.1 has been released

**Comment by mstormi** [comment]
> Yes, that will be automatically updated now that OH 3.1 has been released

yes but can I replace it somehow ?

**Comment by ecdye** [comment]
Like with something custom?

**Comment by mstormi** [comment]
yes. I didn't see a simple file to exchange though

**Comment by ecdye** [comment]
Well if you wanted to self compile and install the whole openHAB webui bundle I could tell you what to change but as a simple file replacement I have no idea.
