### ISSUE TITLE
Purge cache on OH package upgrade?

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1548]
every now and then there's reports of problems after an OH upgrade that are fixed by purging the OH cache.
I though it is but seems this is *not* always done in the package installation process
@BClark09 can you comment ?

So eventually we should add that in options 02, 03, 42.

**Comment by BClark09** [comment]
```
removeCache(){
  [ -d ${UD_CACHE} ] && rm -rf ${UD_CACHE}
  [ -d ${UD_TMP} ] && rm -rf ${UD_TMP}
  [ -d ${UD_KAR} ] && rm -rf ${UD_KAR}
  true
}
```

Is always called during `preinst` for an install or an upgrade. These folders should not exist on first launch of any upgraded openHAB instance.

**Comment by BClark09** [comment]
Tested an upgrade on an Ubuntu setup:

```
inotifywait -m -e modify,create,delete,move /var/lib/openhab
Setting up watches.
Watches established.
/var/lib/openhab/ CREATE .restartOnUpgrade
/var/lib/openhab/ DELETE,ISDIR cache
/var/lib/openhab/ DELETE,ISDIR tmp
/var/lib/openhab/ CREATE .previousVersion
/var/lib/openhab/ MODIFY .previousVersion
/var/lib/openhab/ CREATE,ISDIR tmp
/var/lib/openhab/ DELETE .previousVersion
/var/lib/openhab/ DELETE .restartOnUpgrade
/var/lib/openhab/ CREATE,ISDIR cache
```

**Comment by ecdye** [comment]
Well seeing as how we are already doing it on OH install, we should just ignore the outliers as it is redundant to do it in openHABian. As such I will close.
