### ISSUE TITLE
Modify Wi-Fi transmit power ?

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1554]
Just came across the info that e.g. `iwconfig wla0 transmit 30` will set transmit power on a  Wi-Fi interfaces incl. RPi's internal.

Seems the default 'auto' option sets it to maximum (31)
Shall we add a menu 1X option to allow to limit txpower?

FWIW, the allow maximum (in Germany only?) is 1000mW = 30dBm or rather some less (400mW on 5 GHz, 200 mW on 2.4GHz) see https://wiki.freifunk.net/WLAN-Antennen

**Comment by ecdye** [comment]
I don't know, I think that leaving it to its default and letting any enterprising users change it by doing it manually is better. I don't know about you but I don't think I want to support that sort of feature when a user can easily set it to the wrong value and screw up their system so it doesn't work the way it should. This seems a little advanced for the average user.

I don't know about any max for the US, I sure there is one but I don't think it is that low.

**Comment by mstormi** [comment]
Hmm. Yeah, looking after Wi-Fi issues, I was quite enthusiastic to find this in the first place, later on again it turned out it's using the maximum already so I now agree we can't win anything there all we might get is more issues if someone reduces it.
