### ISSUE TITLE
Bullseye release

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1557]
Debian 11 ("bullseye") was released August, 14th.
We should follow up asap with 1.7 and a bullseye based RPi image.

FWIW, I had (accidentially) upgraded my dev machine to bullseye several months ago and had no issues since,
but we should have a formal compatibility check.

Let's collect in this issue what else we need to check/rework for openHABian to work with a bullseye OS.

- [X] upgrade and check CI base image
- [x] wait for Pi OS image
- [x] update repos
- [x]  Fix BATS for
- - [x] homegear
- [x] check Github actions
- [x] check code for explicit buster specifics
- [X] is_bullseye in helpers.bash

**Comment by ecdye** [comment]
I would be careful not to rush it too much. I would prefer to wait until maybe a month or so after the release to formally support it just to let the dust settle and to make sure we don't miss anything. WDYT?

**Comment by mstormi** [comment]
Debian is usually pretty reliable so I don't expect much dust but you are right in that there is absolutely no need to hurry and we should take the time it takes to find and validate all the bits and pieces.

**Comment by mstormi** [comment]
I just worked around an Influx package bug, it failed to start because the start script was lacking the executable bit.
This may or may not have been the reason for our BATS test to fail on Influx.
But now with that applied I'm not even seeing the permissions_correction() routine (where the fix is) being executed in the build logs 🤔 and wonder why.

**Comment by ecdye** [comment]
> But now with that applied I'm not even seeing the permissions_correction() routine (where the fix is) being executed in the CI build logs 🤔 and wonder why.

Probably because we only run those tests in BATS where we only run the essential install routine and permissions corrections won't run at the end of setup like during a full install.

**Comment by mstormi** [comment]
> in BATS where we only run the essential install routine

right. I think we should change the BATS tests to call permissions_corrections then

**Comment by ecdye** [comment]
@mstormi I just realized this and wanted to make sure you knew too, we will have to wait until Raspberry Pi releases an image based off of bullseye to release a new image based on bullseye. I think it should happen pretty soon but its just something to keep in mind.

**Comment by NorbertHD** [comment]
Raspberry Pi OS Bullseye has been released:
https://www.raspberrypi.com/news/raspberry-pi-os-debian-bullseye/
https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2021-11-08/
https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2021-11-08/

**Comment by ecdye** [comment]
@mstormi FWIW I have been running Bullseye on my production system since it was officially made available in August. So far I have had 0 issues. I still need to check and see if Homegear has fixed their repos for Bullseye yet.

**Comment by mstormi** [comment]
Yeah actually I have been running my dev rpi for more than a year on sid/bullseye since I accidentially upgraded it ;-) with no issues either.

did you cross-check all the code for buster specifics ? if so please tick in post #1

on homegear, I asked devs to provide nightly via repo. No response from the owner but his main fellow dev offered to provide a repo, but that would be sort of a private offering without any warranty it'll persist so I'm unsure if we would want to switch there, wdyt ?

**Comment by ecdye** [comment]
Probably not, we should probably just wait until there is official support and until then the user can jump of the deep end and try to do it themselves.

**Comment by ecdye** [comment]
@mstormi I have made an alpha image. I think or plan should be as follows:
Alpha testing / bug fixing until next Monday (Nov 15)
Beta testing / bug fixing until December 1 at which point we release the full 1.7 image.

I can take care of the building / releasing of the images. Lets try to only issue bug fixes / minor patches until image release so that way we have a nice and stable image. No merging any big changes to the code (ie. Java 17 can wait until after release).

**Comment by mstormi** [comment]
I'm fine with that plan

**Comment by mstormi** [comment]
So with one week to go, what's the state of the nation. Any bugs found, any fixes outstanding? Ready to rumble ?

**Comment by ecdye** [comment]
I think that we are pretty good in terms of bugs, I haven't spotted much else since I did the mass of patches between the alpha and beta images. Do you have last minute concerns that you would like to resolve before I forward everything to the openHAB3 branch and make the final release next week?

**Comment by mstormi** [comment]
I just noticed that the 1.7 image has
clonebranch=HEAD
which I think should be openHAB3, shouldn't it ?

**Comment by mstormi** [comment]
There's also 2 reports of installing into OH2 (clonebranch=stable) to fail but frankly with that
first guy in particular I'm not motivated to go after those

https://community.openhab.org/t/unable-to-install-openhabian-with-clonebranch-stable-successfully/129458/10
https://community.openhab.org/t/installing-oh2-on-openhabian/129494

**Comment by ecdye** [comment]
Yes, I'm looking into it now.

**Comment by mstormi** [comment]
> which I think should be openHAB3, shouldn't it ?

we should also forward main to openHAB3, shouldn't we ?

**Comment by ecdye** [comment]
Already done. I'm going to release 1.7.1 to fix the issue.

**Comment by mastertape** [comment]
When i try to install homegear with the actual Stable release from openhabian over the openhabian-confi tool i get these error notice:
│                                                                              │
                                   │ There was an error or interruption during the execution of:                  │
                                   │   "20 | Optional Components"                                                 │
                                   │                                                                              │
                                   │ Please try again. If the error persists, please read                         │
                                   │ /opt/openhabian/docs/openhabian-DEBUG.md or                                  │
                                   │ https://github.com/openhab/openhabian/blob/main/docs/openhabian-DEBUG.md how │
                                   │ to proceed.

**Comment by ecdye** [comment]
Well, you clearly didn't read the instructions that `openhabian-config` provided you or you wouldn't have posted here.

I can't help without more information, maybe try doing **exactly** what the tool told you to and I might be able to help.
