### ISSUE TITLE
How do can update knxd?

### ISSUE THREAD

**Issue by TomW80** [openhab/openhabian#1559]
Hello,

I have installed openhabian-pi-raspios32-v1.6.5 on my Raspi. This Version includes knxd with version 0.14.30.
With this knxd version i have any problems to connect to my [knx usb interfaces](https://www.busch-jaeger.de/en/online-catalogue/product-overview?tx_nlbjproducts_catalog%5Baction%5D=show&tx_nlbjproducts_catalog%5BcatBjeProdukt%5D=32383&tx_nlbjproducts_catalog%5BcatStdArtikel%5D=124171&tx_nlbjproducts_catalog%5Bcontroller%5D=CatStdArtikel&cHash=0caa098c1fe960eda7fe2a6b1db8ef5c).
Now I want to update knxd to the lasted version. (now 0.14.41)

How can I do that?

**Comment by ecdye** [comment]
You can try running `sudo openhabian-config` and choosing menu option 02 to upgrade all of your packages but other than that you would have to manually build and install it. We only provide support for the version of the package that is provided by APT.

**Comment by mstormi** [comment]
I just installed knxd for a test I got 0.14.30 so there is no newer package available.
So you have to install from sources yourself or wait until the package maintainer releases a package update.
