### ISSUE TITLE
Homegear broken in Bullseye currently

### ISSUE THREAD

**Issue by ecdye** [openhab/openhabian#1570]
This is a place to track updates and eventually resolve the fact that as of now Homegear is broken in Bullseye, due to dependencies that cannot be meant currently. Hopefully will be resolved with the next release of Homegear.

**Comment by mstormi** [comment]
Hi Ethan,
what actually is it that isn't working with Homegear on bullseye?

Proper use from within OH AFAIK requires a version >=0.8 hence a 'nightly' which isn't(?) available via repo
https://homegear.eu/downloads.html?version=0.8

**Comment by ecdye** [comment]
Because we don't want to use nightly right? We just need for them to release 0.8 because we don't want to support the nightly releases and as such we can't install the old version properly on bullseye. If you think we can support the nightly version feel free to update the code to support it but I didn't want to open that door so I didn't try to switch to nightly.

Does that make sense.

**Comment by mstormi** [comment]
Makes sense, I don't wanna dissect the nightly install script either and ever keep catching up with changes there.
However I'm wondering what that has to do with the buster->bullseye move. The current stable code should work equally well (or not) on both of these, shouldn't it ?
I think we would need to eventually change the repo (to keep using the "buster" repo as AFAIK there's none for bullseye yet) but why refuse to install instead ?

And to tell the truth, homegear hasn't been and still isn't working properly with OH with any 0.7 version (it's even in the OH release notes the binding requires >= 0.8-something).

**Comment by mstormi** [comment]
I contacted the HG devs and asked to provide nightly via repo. Let's wait and see.

**Comment by ecdye** [comment]
So, the install for 0.7 failed because of missing packages that are no longer included in bullseye that's why we fail on attempt to install. I don't personally use HG but I observed this behavior when doing migration testing and its why we have consistently failing BATS test for HG.

**Comment by mstormi** [comment]
Then shouldn't we be able to automatically add those dependency packages to make 0.7 work on bullseye ?

**Comment by mstormi** [comment]
Can you write it up ? Then I can post this over in the HG forum in German.

**Comment by ecdye** [comment]
What specifically do you want me to write up just the broken package dependencies for bullseye. I think that they already know about them as the nightly version contains a fixed version they just need to either back port the fix or release a stable version of the nightly with the fix.

**Comment by mstormi** [comment]
fyi I requested the homegear devs to provide their nightly code via repo.
Strictly speaking OH users already today need to run a nightly version because the OH binding is known to not fully work with the stable HG version, but since the nightly isn't available via repo we have somewhat of a catch-22 here
(that we as openHABian devs should not be forced to resolved by integrating their awkward nightly installer's script)

No response yet, unfortunately.

**Comment by ecdye** [comment]
Figures, they probably won't respond until they release their next version which will be fixed which could be a few months from now.

**Comment by Meep0815** [comment]
Just wanted to let you know that homegear released a stable version that works on bullseye:
https://homegear.eu/downloads.html?version=0.7&system=raspbian_bullseye
