### ISSUE TITLE
Auto Backup won't boot

### ISSUE THREAD

**Issue by 2relativ** [openhab/openhabian#1571]
Hello,

I tried the simple auto mirroring tool in openhab as a simple mirror of the used sd card seems enough for me.
I've got a 16 and 32 GB SD card, mirroring from 16 to 32. The mirroring itself seems successful. I've tried the unattended and the openhabian-conf version. No errors, all 3 partitions exist and contain data, folders, etc.
But if I swap the 32 GB in and try to boot it stops after 8  seconds and after 120 seconds there is a last message.![IMG_20210819_081847_HDR.jpg](https://user-images.githubusercontent.com/34840792/130055846-bf5f6677-55b5-4008-bd93-dcd348669125.jpg)

I've tried different SD cards in sizes and manufacturer. Everytime the same result. It is a fresh installation, I've tried upgrading before backup etc. Maybe some files are broken or nonexistent but I don't know where to start.

**Comment by mstormi** [comment]
Github is not a support medium but to track *identified* issues so please turn to the forum for help.

And start there by providing comprehensive infomation like hardware details, openHABian version and at least some diagnostics output like `blkid` with both cards in.

> But if I swap the 32 GB in and try to boot it stops after 8 seconds

Do you mean swap like you have also put the original card into the external card reader ?
The message @8.05 indicates it's accessing whatever is in the external card reader. 


Closing this here as in this form, there is no (clearly) wrong behavior so it is not an openHABian issue (yet).
If there was to emerge new information that indicates there is a misbehavior, post it here and we might reopen this issue.
