### ISSUE TITLE
v1.6.6 image

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1595]
@ecdye Ethan please check yourself and eventually re-set the release to draft/halted. Thanks.
I need to leave now for today.
https://github.com/openhab/openhabian/releases/tag/v1.6.6

**Comment by ecdye** [comment]
Will do.

**Comment by ecdye** [comment]
Seems to be working to me. I'm going to leave it as is as my test install went fine.

**Comment by mstormi** [comment]
thanks
