### ISSUE TITLE
Java 17

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1602]
As Java 17 is now out as the current long term support version and likely the one openHAB will move to soon(ish), we should include this in openHABian asap.
Open for ideas how to do it best, probably as another alternative (like Java 8 and Adopt are today) with the default still being Java 11. @ecdye Ethan I hope it's okay I assign that to you.

**Comment by ecdye** [comment]
Yeah Java is kind of my wheelhouse I more or less made all of the code for it. I'll work on figuring it out.
