### ISSUE TITLE
Running amanda setup causes error

### ISSUE THREAD

**Issue by nicelifeBS** [openhab/openhabian#162]
It looks like /var/backup does not exist when running the amanda setup from the menu.

0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
/usr/local/bin/openhabian-config: line 1313: /var/backup/.amandahosts: No such file or directory
/usr/local/bin/openhabian-config: line 1314: /var/backup/.amandahosts: No such file or directory
/usr/local/bin/openhabian-config: line 1315: /var/backup/.amandahosts: No such file or directory
/usr/local/bin/openhabian-config: line 1316: /var/backup/.amandahosts: No such file or directory
chown: cannot access ‘/var/backup/.amandahosts’: No such file or directory

**Comment by ThomDietrich** [comment]
@mstormi

**Comment by mstormi** [comment]
Ok, a typo that slipped. Just add the "s" in the lines above.
/var/backup**s** should have been created on Amanda package installation (in setup script line 1364), @nicelifeBS can you confirm it's there ? What's the Amanda package you got installed ? 

PS: @ThomDietrich, I can't assign this issue to me, can you? Or do we need some GitHub setting here?

**Comment by nicelifeBS** [comment]
@mstormi yes the directory and its contents are there. Amana-3.3.6 is installed

**Comment by maschenborn** [comment]
I installed Amanda over openhabian-config and entered /NAS/Backups while the installation-process as local target-folder. It's a mounted folder of my synology.
The slot-folder were created on the correct location - but so far no backup was created.
Is /var/backups a special folder or just an example in your case?

**Comment by mstormi** [comment]
/var/backups is not for storage, it's a special folder created and used by Amanda.
Backups are initiated from cron at 0100. Or start `amdump <config>` manually, see README in docs.
 @nicelifeBS, tell me your entries in `/etc/cron.d/amanda` ... note the setup removes and recreates that file every time, so you will have either entries for AWS _or_ local dir based backup, whatever you ran last.
You can edit the file to add a secondary backup run manually, but as a openHABian default, I thought it's better to eliminate eventually existing backup runs and just add a single new one.

**Comment by nicelifeBS** [comment]
`0 1 * * * backup /bin/bash /usr/sbin/amdump openhab-AWS &>/dev/null
0 18 * * * backup /bin/bash /usr/sbin/amcheck -m openhab-AWS &>/dev/null`
So it is only setting up AWS if configure it. If you skip AWS setup it is empty. I changed it to the openhab-dir but the setup should actually do this.

**Comment by mstormi** [comment]
Strange (if you look at the code), but I changed that now so to run Amanda setup deletes the cron file and it'll create unique entries for every backup method you choose. (@ThomDietrich: PR#163 pending)

**Comment by nicelifeBS** [comment]
Cool. Another issue regarding the cron job. It is executed at least I see it in the syslog but the amdump process is never started. And I don't know where it fails really no amanda log gets updated. So my bet is that something goes wrong here.
It runs fine if I run amdump with the backup user. So it is not access rights regarding writing to the backup directory

**Comment by mstormi** [comment]
Can you try to omit the "/bin/bash" field in crontab ?

**Comment by nicelifeBS** [comment]
Yap. That worked
