### ISSUE TITLE
Openhabian how to recover /boot partition

### ISSUE THREAD

**Issue by ZE135** [openhab/openhabian#1621]
Hello all,

I am not sure if this is the right forum, but I will try my luck. Hopefully somebody can help me.
What happend?
I am using since long time Openhabian on my Raspberry 3. I wanted to upgrade from 3.1 to 3.2 and did an

sudo apt-get update
sudo apt-get upgrade

After everything was installed I rebooted the system and somehow it did not reboot again.
To be on the safe side I immediatly did a clone of the SD card with

dd if=/dev/sdb of=/dev/sdc bs=512 status=progress

I do have access to the /rootfs partition.

I did download the latest openhabian and tested my pi if everything booting correct again. After seeing everything works fine I thought I could simply clode the first /partiion with dd.
Unfortunately it is still not booting.
I am not sure what could be the issue. Probably I need to use rsync and copy all files? I am not sure if the starting block might be an issue.

Could anybody has an idea? What could I do further?

Thanks in advance

**Comment by mstormi** [comment]
see my reponse on the forum

please do not open Github issues for support, for questions turn to the forum. Github is for development only.
