### ISSUE TITLE
Using a backslash within a password for influxdb leads to broken influxdb/grafana setup

### ISSUE THREAD

**Issue by guy-inkognito** [openhab/openhabian#1624]
## Issue information:
I found a bug when setting up influxdb + grafana via openhabian. I provided a password containing a backslash (e.g.: '1234\5678') which causes that setting the password fails and the user is not created.

## Debug information:
Can be reproduced by trying to create the user via command line:

```
create user openhab with password '1234\5678'
ERR: error parsing query: found \5, expected string at line 1, char 42
```

User is being created when escaping the backslash with another backslash. However, maybe this could be catched somehow to avoid that setup via openhabian creates a broken setup.

**Comment by mstormi** [comment]
Thanks fpr reporting but this is an external dependency beyond our reach, validating inputs to 3rd party tools is out of scope for openHABian. We don't maintain InfluxDB or any other of the tools you can install from within openHABian.
