### ISSUE TITLE
Can't detect wifi hardware on Raspberry Pi Zero W 2

### ISSUE THREAD

**Issue by danhpham1510** [openhab/openhabian#1626]
I'm trying to get openhabian running on the new Pi 0 W2. However, when the setup runs it can't detect the wifi hardware of the board. As a result, I couldn't connect to the internet and It could not start hotspot as well.

**Comment by ecdye** [comment]
We have not added support for this board yet, as a temporary fix try setting `hw=pi0w` in `/boot/openhabian.conf`. Make sure that you remove any comments from the beginning of the line (ie. '# hw=' to 'hw=pi0w').

**Comment by danhpham1510** [comment]
Thank you very much, this solved the issue!
