### ISSUE TITLE
Support I2C devices in menu

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1634]
WIP

communication with I2C devices requires to enable the bus =>
This is needed for various sensors and e.g. for the Waveshare UPS HAT.

`dtparam=i2c_arm=on` in config.txt
modprobe i2c-dev (eventually put into `/etc/modules`)

**Comment by mknet** [comment]
Hey Markus,

currently, I'm struggling to activate i2c to get my RaspBee2 running. I tried it also with a naked Raspberry PI OS Lite (bullseye as well) and it worked. Do you have and hint what I have to do aport from setting `dtparam=i2c_arm=on` in the config.txt?

Thanks for hint and regards
Marcel

**Comment by mknet** [comment]
I installed raspi-config myself and activated IC2 via the raspi-config UI. Not a charm but at least it works. :)

**Comment by mstormi** [comment]
> I installed raspi-config myself and activated IC2 via the raspi-config UI. Not a charm but at least it works. :)

Please figure out what raspi-config changed about config.txt to help with making that selectable in openHABian via menu.
That's what this issue is about.

**Comment by mstormi** [comment]
`dtparam=i2c_arm=on` is now standard

Reopen if needed
