### ISSUE TITLE
Serial connection to USB via FTDI

### ISSUE THREAD

**Issue by TomW80** [openhab/openhabian#1645]
Hello, 

I want to connect to openhabian via the serial console. 
I have added "enable_uart=1" at the end of boot/config.txt.
But unfortunately I can't get a connection.

Now I have installed Raspberry Pi OS Lite for testing purposes to rule out problems with the FTDI connection. 
The connection works with it.

Do I have to set anything special in openhabian?
If I activate "Disable serial console to give room for HATs" in "System settings - 35 Serial port", openhabian no longer starts.

Can someone tell me what I have to adjust so that I can connect via the serial console?

## System information:
`cat /etc/os-release` 
Raspbian GNU/Linux 10 (Buster)
openhabian 3.2.0
 `uname -m`
armv71

**Comment by mstormi** [comment]
No I cannot. openhabian works with #35 activated unless you have modified the system in a way we cannot know about.
Read the debug guide to increase debugging then you'll see what's happening.

And please don't use Github to get personal support. Address it on the forum. Thank you.
