### ISSUE TITLE
FireMotD failing (login delay)

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1653]
Logging into my test box w/ a fresh image installed takes several seconds, that ain't normal.
Not analyzed for now, this is a generic reminder.

Not sure if the reason could be within my local network but I don't think so in the first place.
IP is obtained from DHCP with a fixed mapping MAC->IP on the DHCP server/router and the test box is always the same (ie MAC does not change).

**Comment by ecdye** [comment]
Perhaps the cpu is just running startup tasks after the fresh install?

**Comment by blockbasti** [comment]
I have noticed this for a while now. Logging in via SSH takes 5 to 10 seconds. Switching from FireMOTD to neofetch helps somewhat but it still takes a lot longer to log in and get a shell than on other devices.

**Comment by mstormi** [comment]
I inserted "set -x" to some file in /etc/profile.d and it's FireMotd when generating the login page, apparently.
That should be fast once the FireMotd database is generated which happens offline daily.

**Comment by mstormi** [comment]
Reading https://www.outsideit.net/home I think it's about time to stop using FireMotD

**Comment by mstormi** [comment]
Added our own cache, seems to work for now
https://github.com/openhab/openhabian/commit/d1cce9c3f7d826e9843fa88695f0063cf6893273
