### ISSUE TITLE
Add zigbee2mqtt

### ISSUE THREAD

**Issue by Larsen-Locke** [openhab/openhabian#1656]
[Zigbee2mqtt](https://www.zigbee2mqtt.io/)  is used by many openhab-users as it greatly increases the number of possible ZigBee-hardware for openhab (especially sensors and switches that don't implement the ZigBee-standard very accurate)

The possibility to [install](https://www.zigbee2mqtt.io/guide/installation/01_linux.html#for-later-update-zigbee2mqtt-to-the-latest-version)  and update zigbee2mqtt would in my opinion  make a perfect fit.

There is nothing that has to be configured during installation cause everything can be set up in the (great) web frontend afterwards. 

I would like to know what you think and how I can contribute.

**Comment by mstormi** [comment]
With the ZigBee binding in openHAB at hand there is little benefit in going for a more complicated and error prone setup as is Zigbee2mqtt.
I would be accepting a PR to add Zigbee2mqtt to openHABian but I will not start work on that myself.

**Comment by Larsen-Locke** [comment]
Thank you for your answer. I understand that it's not on your list which is perfectly ok.
But just let me explain why many want or have to use zigbee2mqtt to integrate their hardware:
Only well implemented zigbee hardware gets identified by the openhab-binding. Many of the chinese zigbee devices just don't work with the binding (e.g. Livolo zigbee) as well as many coordinators (e.g. chipset TI 2652P with a really good range).
Another argument is that with zigbee2mqtt you can immediately see the complete topology of your mesh and test the device. This is very helpfull if something doesn't work. Thank you for your good work.

**Comment by Larsen-Locke** [comment]
allright. Let's give it a try:
I added a menu for zigbee2mqtt under "optional components" and added download and install-functionality in nodejs-apps.bash
What might be missing is a test routine in the .bats-file.
I start the PR..

**Comment by Larsen-Locke** [comment]
Well it got a lot bigger than I expected.
I think now it covers most of what's necessary like installing, removing, updating. You can set the mqtt user and password if necessary. 
Please tell me what to improve.
PR is [https://github.com/openhab/openhabian/pull/1666](https://github.com/openhab/openhabian/pull/1666)

**Comment by Larsen-Locke** [comment]
Finally all checks are passed without error and all requested corrections are implemented. Well, a lot more work than I expected, especially getting permissions right took me a while.
How the PR gets accepted now.
