### ISSUE TITLE
install failing no zram

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1657]
I just reinstalled my test box from latest image.
OH fails to start. The box failed to setup zram. I suspect the recent changes in the zram repo might be a problem.
Will update this as more info becomes available.

All options 38 openhabian-config fail because the zram-config.service is not installed.
/etc/systemd/system/zram-config.service is missing, after copying it over zram starts but OH still fails to.
Reason for that is the zram install routine gets interrupted in zram.bash l61 when attempting to copy zram-config.logrotate which was moved to the service directory. The install code was adapted in main but not in openHAB3 branch.
=> forwarding main to openHAB3 is required

**Comment by ecdye** [comment]
Sorry, thought that I got all of those. I'll double check and make a fix. Eventually I would like to migrate to using the sram-config builtin install script to hopefully avoid these type of issues.
