### ISSUE TITLE
Bug in system.bash fix_permissions if zigbee2mqtt is installed

### ISSUE THREAD

**Issue by Larsen-Locke** [openhab/openhabian#1684]
"Fix Persmissions" fails with an error (invalid user) if zigbee2mqtt is installed.
In system.bash tries to assign /var/log/zigbee2mqtt to user zigbee2mqtt instead of openhabian.
PR [https://github.com/openhab/openhabian/pull/1679](https://github.com/openhab/openhabian/pull/1679) fixes this bug (and one typo in changelog).
Please merge or tell me if something is missing.

**Comment by mstormi** [comment]
fixed by https://github.com/openhab/openhabian/commit/5a7b1ca6eeba07cb87f035194c5e0b0dea6eb12a
