### ISSUE TITLE
Fresh install of image v1.7.3 does not start openhab

### ISSUE THREAD

**Issue by DanielGlaas** [openhab/openhabian#1685]
## Issue information:
I downloaded the latetst 32bit image of openhabian via [this link](https://github.com/openhab/openhabian/releases/download/v1.7.3/openhabian-pi-raspios32-202203300347-git1305ac7-crcc3eb5287.img.xz)
The boot and installation process worked fine, I prepared wpa_supplicant.conf after flashing the image for logging into my Wifi. This worked and I could also login via SSH.

After the final rebot, openhab was not available via the 8080 port.

## Debug information:
I configured `debugmode=maximum` parameter in the `/etc/openhabian.conf` file. 

The output of `openhabian@openhabian:~ $ sudo openhab-cli start --debug` is:
```
A systemd service configuration exists...
Use 'sudo /bin/systemctl start openhab.service' to start an openHAB service
Launching an instance in this terminal..
Launching the openHAB runtime...
/usr/share/openhab/runtime/bin/karaf: 247: [: Illegal number: 
/usr/share/openhab/runtime/bin/karaf: 247: [: Illegal number: 
/usr/share/openhab/runtime/bin/karaf: 97: [: Illegal number: 
/usr/share/openhab/runtime/bin/karaf: 300: [: Illegal number: 
-Djava.endorsed.dirs=/usr/lib/jvm/java-11-openjdk-armhf/jre/lib/endorsed:/usr/lib/jvm/java-11-openjdk-armhf/lib/endorsed:/usr/share/openhab/runtime/lib/endorsed is not supported. Endorsed standards and standalone APIs
in modular form will be supported via the concept of upgradeable modules.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

```

## System information:
Please tell us what OS you are running (Raspberry Pi OS, Debian, Ubuntu), what
HW you are running on (Raspberry Pi, amd64). Also include the output of
`cat /etc/os-release` 
```
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```
and `uname -m`.
```
armv6l
```
startmessage when logging in via ssh:
```
###############################################################################
###############  openhabian  ##################################################
###############################################################################
##        Ip = 192.168.178.54
##   Release = Raspbian GNU/Linux 11 (bullseye)
##    Kernel = Linux 5.15.32+
##  Platform = Raspberry Pi Zero W Rev 1.1
##    Uptime = 0 day(s). 0:1:58
## CPU Usage = 1.01% avg over 2 cpu(s) (1 core(s) x 1 socket(s))
##  CPU Load = 1m: 1.20, 5m: 0.84, 15m: 0.34
##    Memory = Free: 0.26GB (58%), Used: 0.19GB (42%), Total: 0.46GB
##      Swap = Free: 0.83GB (100%), Used: 0.00GB (0%), Total: 0.83GB
##      Root = Free: 25.00GB (89%), Used: 3.02GB (11%), Total: 29.25GB
##   Updates = 0 apt updates available.
##  Sessions = 1 session(s)
## Processes = 86 running processes of 32768 maximum processes
###############################################################################

```

**Comment by DanielGlaas** [comment]
Note:
I already installed openhab on a "normal" rasbian image via Option 2 descibed [here](https://www.openhab.org/download/). This worked very smoothless and there no karaf appeared on the command lines.
Thus, I am not able to compare my two installation methods.

**Comment by DanielGlaas** [comment]
I just figured out, that this problem vanishes when using openjdk-17.
This seems to be related to the update to bullseye raspian base version.

**Comment by mstormi** [comment]
Cannot reproduce. If you still have an issue, reopen and provide an install log this time else I don't know what you want us to act upon here.
