### ISSUE TITLE
Feature proposal: Add cron-apt

### ISSUE THREAD

**Issue by florian-h05** [openhab/openhabian#1686]
## Feature proposal

I would like to discuss the idea of adding cron-apt to openhabian.

[cron-apt](http://manpages.ubuntu.com/manpages/bionic/man8/cron-apt.8.html) can be configured to automatically check for updates and download them only (not installing them). It can also send an email when updates are available.

This allows the user to keep his system up-to-date without thinking of checking for updates and it makes updates faster for the user as the new packages are already downloaded and only have to be installed.

You can also see the following for example of usage:
- https://geekthis.net/post/how-to-setup-cron-apt/
- https://wiki.ubuntuusers.de/cron-apt/ (in German, but great documentation)

**Comment by mstormi** [comment]
openHABian isn't really an OS that you should be updating constantly but only in select situations. The OS part actually rarely really _needs_ any such update.
Never change a running system.
No this will confuse and annoy more people than it'll help and would needlessly impose work to check stuff on everybody that  the average OH user does not even care about.
Feel free to implement it on your box but I don't see this in openHABian.

**Comment by florian-h05** [comment]
Okay, thanks for the feedback.
