### ISSUE TITLE
EVCC install fails

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1688]
See https://docs.evcc.io/docs/installation/linux for instructions, but the public key is unavailable after that.
No idea at the moment. Haven't been using repo signing code in a while so dunno what to check right now :-|

[22:07:25] root@smarthouse:~# apt-get update
OK:1 http://archive.raspberrypi.org/debian bullseye InRelease
OK:2 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
OK:3 http://davesteele.github.io/comitup/repo comitup InRelease
OK:4 https://deb.nodesource.com/node_14.x bullseye InRelease
Holen:5 https://dl.cloudsmith.io/public/evcc/stable/deb/debian any-version InRelease [5.104 B]
OK:6 https://openhab.jfrog.io/artifactory/openhab-linuxpkg stable InRelease
Holen:7 https://pkgs.tailscale.com/stable/raspbian buster InRelease
Fehl:5 https://dl.cloudsmith.io/public/evcc/stable/deb/debian any-version InRelease
  Die folgenden Signaturen konnten nicht überprüft werden, weil ihr öffentlicher Schlüssel nicht verfügbar ist: NO_PUBKEY EAD5D0E07B0EC0FD
Paketlisten werden gelesen… Fertig
W: GPG-Fehler: https://dl.cloudsmith.io/public/evcc/stable/deb/debian any-version InRelease: Die folgenden Signaturen konnten nicht überprüft werden, weil ihr öffentlicher Schlüssel nicht verfügbar ist: NO_PUBKEY EAD5D0E07B0EC0FD
E: Das Depot »https://dl.cloudsmith.io/public/evcc/stable/deb/debian any-version InRelease« ist nicht signiert.
N: Eine Aktualisierung von solch einem Depot kann nicht auf eine sichere Art durchgeführt werden, daher ist es standardmäßig deaktiviert.
N: Weitere Details zur Erzeugung von Paketdepots sowie zu deren Benutzerkonfiguration finden Sie in der Handbuchseite apt-secure(8).

**Comment by lskillen** [comment]
Hey folks, Lee from @cloudsmith-io here. You/evcc probably needs a fix similar to here:
https://github.com/caddyserver/dist/issues/83#issuecomment-1129025743

Basically, support for how signing keys works was updated, but any sites with "manual" instructions (i.e. not using the automated script) need to be updated in order for setup to continue working correctly.

**Comment by Macrisu** [comment]
https://dl.cloudsmith.io/public/evcc/stable/debian.deb.txt is the problem

the fix is:

nano 

**remove**

```
deb [signed-by=/usr/share/keyrings/evcc-stable-archive-keyring.gpg] https://dl.cloudsmith.io/public/evcc/stable/deb/debian any-version main

deb-src [signed-by=/usr/share/keyrings/evcc-stable-archive-keyring.gpg] https://dl.cloudsmith.io/public/evcc/stable/deb/debian any-version main
```

**add**

`deb [signed-by=/etc/apt/trusted.gpg.d/evcc-stable.asc] https://dl.cloudsmith.io/public/evcc/stable/deb/debian any-version main

deb-src [signed-by=/etc/apt/trusted.gpg.d/evcc-stable.asc] https://dl.cloudsmith.io/public/evcc/stable/deb/debian any-version main`

**Comment by mstormi** [comment]
Fixed by #1689
