### ISSUE TITLE
Can't switch to openHAB 2.2 unstable

### ISSUE THREAD

**Issue by kubawolanin** [openhab/openhabian#169]
Environment / device: latest openHABian on RPi3

Steps to reproduce:
1. `sudo openhabian-config`
2. Go to `40 | openHAB related`
3. Select `    | openHAB 2.2 unstable`

![bug](https://user-images.githubusercontent.com/2270505/27733001-37f6cb8a-5d94-11e7-8284-b2e8637e212f.gif)

Expected result:
User should be able to install openHAB2.2 unstable

Actual result:

This message shows up:
```
                       │ A not supported option was selected (probably a programming error):          │
                       │   "   | openHAB 2.2 unstable"
```

**Comment by ThomDietrich** [comment]
Hey @kubawolanin, thanks!
Corrected and tested. Should be working now.
