### ISSUE TITLE
Problem upgrading openhab (3.3.0-1) over (3.2.0-1) 

### ISSUE THREAD

**Issue by Diapolo** [openhab/openhabian#1695]
I tried to upgrade to latest openHAB via `openhabian-conf` and it fails with:

> sudo openhabian-config 
> 2022-06-30_11:07:34_CEST [openHABian] Checking for root privileges... OK
> 2022-06-30_11:07:34_CEST [openHABian] Loading configuration file '/etc/openhabian.conf'... OK
> 2022-06-30_11:07:34_CEST [openHABian] openHABian configuration tool version: [openHAB3]{2022-03-27T13:22:11-06:00}(1305ac7)
> 2022-06-30_11:07:35_CEST [openHABian] Checking for changes in origin branch openHAB3... OK
> 2022-06-30_11:07:37_CEST [openHABian] Switching to branch openHAB3... OK
> 2022-06-30_11:07:37_CEST [openHABian] Adding slightly tuned bash configuration files to system... OK
> 2022-06-30_11:07:39_CEST [openHABian] Updating Linux package information... OK
> 2022-06-30_11:07:40_CEST [openHABian] Updating repositories and upgrading installed packages...
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Calculating upgrade... Done
> The following packages will be upgraded:
>   openhab
> 1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> 5 not fully installed or removed.
> Need to get 0 B/98.2 MB of archives.
> After this operation, 321 kB disk space will be freed.
> apt-listchanges: Reading changelogs...
> dpkg: could not open log '/var/log/dpkg.log': Read-only file system
> (Reading database ... 60707 files and directories currently installed.)
> Preparing to unpack .../openhab_3.3.0-1_all.deb ...
> Unpacking openhab (3.3.0-1) over (3.2.0-1) ...
> dpkg: error processing archive /var/cache/apt/archives/openhab_3.3.0-1_all.deb (--unpack):
>  unable to create '/var/log/openhab/Readme.txt.dpkg-new' (while processing './var/log/openhab/Readme.txt'): Read-only file system
> dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
> Errors were encountered while processing:
>  /var/cache/apt/archives/openhab_3.3.0-1_all.deb
> Updating FireMotD available updates count ... 
> W: Problem unlinking the file /var/log/apt/eipp.log.xz - FileFd::Open (30: Read-only file system)
> W: Could not open file /var/log/apt/eipp.log.xz - open (17: File exists)
> W: Could not open file '/var/log/apt/eipp.log.xz' - EIPP::OrderInstall (17: File exists)
> W: Could not open file '/var/log/apt/term.log' - OpenLog (30: Read-only file system)
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> FAILED

**Comment by mstormi** [comment]
As outputs say, your system or parts thereof is readonly. That's not an openHABian problem in the first place.
Please respect that GitHub issues are not for your user support. Go to the forum.
