### ISSUE TITLE
After upgrade to Grafana 9.0.2, cannot access InfluxDB?

### ISSUE THREAD

**Issue by Diapolo** [openhab/openhabian#1696]
It seems the upgrade from 8.x to 9.x is causing some issues for Grafana on openHABian, I'm unable to access any data. My dashboard is not functioning at all and when I try to configure my InfluxDB data source via Grafana-UI I get `InfluxDB Error: Bad Request`. Seems they changed something which needs to be adopted by openHABian?

https://grafana.com/docs/grafana/latest/whatsnew/whats-new-in-v9-0/

Could be related to this?
https://github.com/grafana/grafana/issues/47570
https://github.com/grafana/grafana/issues/51547

Likely THIS is the related report in the Grafana repo:
https://github.com/grafana/grafana/issues/51076

**Comment by Diapolo** [comment]
It seems we have to re-enter the password to access the InfluxDB in the Grafana-UI -> Configuration -> Data Sources. If others could verify, this issue can be closed!

**Comment by mstormi** [comment]
If anything's wrong with the upstream (Grafana) that's not an openHABian issue. We cannot do anything about it.
openHABian installs the latest Grafana version by the time you install it. You can upgrade the packages at any time in case you obtained a 'bad' one.
