### ISSUE TITLE
Changing from openjdk 17 to openjdk 11 not working via openhabian-config

### ISSUE THREAD

**Issue by MatzeMuc86** [openhab/openhabian#1697]
Trying to change back from openjdk version 17 to version 11 will not be made.
 openHABian Configuration Tool — [main]{2022-06-30T11:22:00+02:00}(db24897) 
openHAB 3.3.0 - Release Build

See also: https://community.openhab.org/t/oh-3-3-integrated-tabs-not-working/137015/4

**Comment by mstormi** [comment]
the menu says "install", not "activate", so strictly speaking this is not a bug.
And OpenJDK 17 is experimental anyway.
But I've added code to also switch after install.

**Comment by MatzeMuc86** [comment]
Great, thanks! 
May I suggest to add the information about openjdk 17 to be experiment currently even within openhabian config menu? This might be helpful to have there directly.
