### ISSUE TITLE
Raspberry Pi Imager: Add openHAB/openHABian in the home automation section

### ISSUE THREAD

**Issue by Larsen-Locke** [openhab/openhabian#1703]
[Raspberry Pi Imager](https://www.raspberrypi.com/software/) offers quite a few home automation Systems (under section "other specific purpose os"), but no openHAB.

This should be changed!
To get openHAB included in rpi-imager a json-file describing the download parameters has to be provided in the download location of the image and a json-section has to be added to the application.
I made a first draft: [rpi-imager-openhabian.json](https://github.com/Larsen-Locke/rpi-imager_add-openHAB/blob/main/rpi-imager-openhabian.json) and [json-section](https://github.com/Larsen-Locke/rpi-imager_add-openHAB/blob/main/os_list_imagingutility_v3.json). 
The result in rpi-imager would look like this: 

<img width="387" alt="image" src="https://user-images.githubusercontent.com/78228200/181935707-ea73ab5b-aa3c-4dfb-ae44-8fad3c779549.png">

And below the two options for 32bit and 64 bit, like that:

<img width="341" alt="image" src="https://user-images.githubusercontent.com/78228200/182458135-e612eb41-f2ee-456a-af68-585d28a8abbe.png">

What do you think? Is the description (escpecially openhab/openhabian) correct? Any improvements?
As soon as the json is available I would ask the maintainers of rpi-imager to include the openhab-section in their application (they have to do it manually).

**Comment by mstormi** [comment]
omit the "(via wifi-hotspot)".
@openhab-maintainers any proposal or comment ?

**Comment by Larsen-Locke** [comment]
> omit the "(via wifi-hotspot)".
@mstormi : The intention was to prevent people from attaching keyboards and monitors during first boot. But maybe not the best way...
I removed it

**Comment by mstormi** [comment]
use (headless) or omit
Can we add this link ?
https://www.openhab.org/docs/installation/openhabian.html#raspberry-pi-prepackaged-sd-card-image

**Comment by Larsen-Locke** [comment]
> use (headless) or omit Can we add this link ? https://www.openhab.org/docs/installation/openhabian.html#raspberry-pi-prepackaged-sd-card-image

The only possibility for a link is the info-icon. I changed it like that: The info icon of the first menu (first screenshot) points to openhab.org and the info-icons of the next menu (second screenshot) point to the installation page.
I updated the screenshots accordingly. What do you think?

**Comment by mstormi** [comment]
well strictly speaking openHAB itself is the only part that does not care about 32 or 64 bit, so maybe omit it? It's in the title already.
Can you wrap the line at the "-" ? (no "-" needed then)

**Comment by Larsen-Locke** [comment]
> well strictly speaking openHAB itself is the only part that does not care about 32 or 64 bit, so maybe omit it? It's in the title already. Can you wrap the line at the "-" ? (no "-" needed then)

Sure.  json and Screenshots are updated

**Comment by mstormi** [comment]
LGTM go ahead please

**Comment by Larsen-Locke** [comment]
> LGTM go ahead please

The json-file has to be made available at the openhabian download location.
Precise questions:
Should the file rpi-imager.json be generated from a template during build or is it a static file  just for this version? (The latter means it has to be updated manually for each new version of openhabian)
I could prepare some code for the generation but i don't know where to put it (build.bash?), where to put the template and the output-file.

**Comment by mstormi** [comment]
Let's see... am right that we do not *create* the rpi-imager.json but just contribute our OH addition to the combined version?
I'd think we wouldn't want to have to contact the RPi foundation to update it every time we release a new image.
Yes I want it to be created during build. Image is created through GH actions.
See https://github.com/openhab/openhabian/blob/main/.github/workflows/build-action.yml
I'm unsure as Ethan did most of the work on GH actions (@ecdye do you copy ? Any comment ?)
Not sure if the filename already contains the hash but I'd think others to use GH to build releases will have had the same question and will have solved it so let's google for their solutions.

**Comment by Larsen-Locke** [comment]
> Let's see... am right that we do not *create* the rpi-imager.json but just contribute our OH addition to the combined version?

not quite: It takes two parts, one is static and one changes with versions (separate file in download location)

- the first one is the json snippet (line 237-243 in example above) which will be included in the rpi-imager. It contains the openhab part of the first screenshot. This doesn't need to be updated. It also contains the link to the json-file (rpi-imager-openhab.json)

- the second is the json-file that contains the download paths, checksums and text-content of the second screenshot. So this has to be re-generated with each version. It's not a part of rapi-imager. It's located where the images are provided. But always same name, same path, so that it's found by rpi-imager.

Hope it's a bit clearer now.

**Comment by mstormi** [comment]
anything you need to proceed?

**Comment by Larsen-Locke** [comment]
(Just some time and energy) I think I can finish my part this weekend, but someone  has to help integrating it in the build-scripts.

**Comment by mstormi** [comment]
No stress. We'll figure that out. 
I'd guess we'll have to do something like duplicate lines 41, 72 and 84 of the build workflow yaml (above).
Please provide a PR for a start.

**Comment by Larsen-Locke** [comment]
> Please provide a PR for a start.
And here it is: https://github.com/openhab/openhabian/pull/1708

**Comment by mstormi** [comment]
Closed-By: #1708

thanks

**Comment by mstormi** [comment]
It was just merged into Raspi imager and works right away.

Thanks for your efforts!

**Comment by Larsen-Locke** [comment]
Thanks. Just wanted to adjust the docs but apparently already accomplished. 👍
