### ISSUE TITLE
System is slow

### ISSUE THREAD

**Issue by hr3** [openhab/openhabian#171]
After setup 2.1 new (only openHAB and mosquitto) the system runs mutch slower as with 2.0.
After reboot, it takes about 1:15 hours, before the hole system is started and the files for the http-sites are prepared.
The identical windows installation works pretty good. So I think, if this is not a bug, the hardware is to small now.
```
###############################################################################
################# openHABianPi #################################### 7.05.170509
###############################################################################
##        Ip = 192.168.178.33
##   Release = Raspbian GNU/Linux 8 (jessie)
##    Kernel = Linux 4.9.28+
##  Platform = Raspberry Pi Model B Rev 2
##    Uptime = 0 day(s). 0:5:45
## CPU Usage = 100 % avg over 2 cpu(s)  (1 core(s) x 1 socket(s))
##  CPU Load = 1m: 2.13, 5m: 1.52, 15m: 0.72
##    Memory = Free: 0.12GB (26%), Used: 0.34GB (74%), Total: 0.47GB
##      Swap = Free: 0.09GB (100%), Used: 0.00GB (0%), Total: 0.09GB
##      Root = Free: 102.00GB (98%), Used: 1.91GB (2%), Total: 109.53GB
##   Updates = 0 apt-get updates available.
##  Sessions = 1 sessions
## Processes = 94 running processes of 32768 maximum processes
###############################################################################

              Welcome to            __  _____    ____  _
            ____  ____  ___  ____  / / / /   |  / __ )(_)___ _____
           / __ \/ __ \/ _ \/ __ \/ /_/ / /| | / __  / / __ `/ __ \
          / /_/ / /_/ /  __/ / / / __  / ___ |/ /_/ / / /_/ / / / /
          \____/ .___/\___/_/ /_/_/ /_/_/  |_/_____/_/\__,_/_/ /_/
              /_/
                  openHAB 2.1.0-1 (Release Build)
```

**Comment by cribskip** [comment]
Hi, I'm also seeing a slow system (raspian + apt openhab2) after upgrade from 2.0 to 2.1. Especially the startup seems to be factor 3 slower.

There have been some minor validation issues and syntax errors which were not preventing anything up till the update.
Fixing them did not improve performance.

**Comment by mbaehr2909** [comment]
I also seem to be having this problem. I installed a clean Version of Openhabian 1.4 (latest version) on my RPi 2 model b yesterday and since then I have 100% CPU Load. 
I didn’t run any Scans or tests yet, but this seems to persist with openhab 2.2.
I will get back to you as soon as I have inspected the problem further.

**Comment by EliasGabrielsson** [comment]
Guess some of the installed components where hugging the CPU. Feel free to reopen if issue still exist when the system have stabilized after installation.
