### ISSUE TITLE
SHA256 Checksums for v1.7.4b

### ISSUE THREAD

**Issue by HorstFrank** [openhab/openhabian#1710]
Are the Checksums for the SD-Card-Images okay?

32 bit image: c1850a1df5447a2d580feeae6ae83960fc443cd321a80d8deef1e85837e561dc
64 bit image: e5d62803fbaf6bac58428eae5283d6b2d10af90305fb82753c745ff9182f967f

My Checksums after the Download are:
32bit: 1a8d1f0509c3615fc076ae453c61db50623e3043a5021145bbd50ba3f0184d9c
64bit: a715152606a64e4a8615fb1565153342009f745acb1ecf4ec3d29d10c9e941be

**Comment by Larsen-Locke** [comment]
Yes, for the extracted images. The checksum for the compressed image is in the json, too.

**Comment by mstormi** [comment]
done. I think I'll omit them next time.

**Comment by HorstFrank** [comment]
Okay! Thank You! <3
