### ISSUE TITLE
[openHABian] Adding required keys to apt... curl: (22) The requested URL returned error: 502 Bad Gateway gpg: no valid OpenPGP data found. FAILED

### ISSUE THREAD

**Issue by hartmood** [openhab/openhabian#1715]
I am failing to install the latest openhabian hassle free install. It seems to be an issue with adding the keys.

```
[openHABian] Adding required keys to apt... curl: (22) The requested URL returned error: 502 Bad Gateway
gpg: no valid OpenPGP data found.
FAILED
```

Hope it will be fixed soon :-)

**Comment by z9th3** [comment]
Same issue here from the first-log.boot
Tried the command manually, same result.
```
openhabian@openhabian:~ $ curl -fsSL "https://openhab.jfrog.io/artifactory/api/gpg/key/public" | gpg --dearmor > openhab.gpg
curl: (22) The requested URL returned error: 502 Bad Gateway
gpg: no valid OpenPGP data found.
```
Same thing on my linux machine.
```
:~$ curl -fsSL "https://openhab.jfrog.io/artifactory/api/gpg/key/public" | gpg --dearmor > openhab.gpg
curl: (22) The requested URL returned error: 504
gpg: no valid OpenPGP data found.
```

**Comment by eerootsus** [comment]
+1

Started with 504 errors and then 502. Although this is more of a openHAB issue as they keystore is more likely managed by them.

**Comment by mstormi** [comment]
jfrog upstream is apparently broken, see also forum.

Sorry but that's not an openHABian problem.

**Comment by soukal24** [comment]
Hi, yesterday my SD card went bad and the mirror doesn't work. So I decided to clean install openhabian. Fortunately, I have a backup of the configuration, but I can't get openhabian working and I think it's because of this problem. Any chance it will be functional soon?

**Comment by hartmood** [comment]
Hmm, 

installation of milesonte release works with openhabian-config while the installation openHABian v1.7.4b still fails:

```
2022-09-15_18:11:41_CEST [openHABian] Adding required keys to apt... curl: (22) The requested URL returned error: 502 Bad Gateway
gpg: no valid OpenPGP data found.
FAILED

```

@mstormi If it "not an openHABian problem" why is still not working then although key adding on openhabian was re-established?

**Comment by soukal24** [comment]
At now it is OK, my home is working. But yesterday it was been stressful 🙂
