### ISSUE TITLE
Re-install of the fronttail component resulted in being locked out of SUDO

### ISSUE THREAD

**Issue by thetonto** [openhab/openhabian#1717]
I did a reinstall of front tail to my openhab installation and found that my sudo command has been disabled and is now owned by the fronttail user.

**Comment by mstormi** [comment]
Sorry but as Rich already responded on the forum there's nothing in openHABian that copes with sudo so this most likely is no openHABian issue.
If you can reproduce it (starting with a fresh i.e. unmodified installation), set `debugmode=maximum` in `/etc/openhab`, record the shell output and upload the log here.

**Comment by thetonto** [comment]
Hi Markus

I totally love the fast response from the team.   What is did was an 
update to openhab

Then over time I had noted that my link to front end did not work. I 
went back into openhab to reinstall and found i was locked out of sudo 
as the permission had changed.

e



Markus Storm wrote on 17/09/2022 2:42 AM:

**Comment by mstormi** [comment]
not an openhabian issue

reopen if you can provide an install log to show misbehavior.
