### ISSUE TITLE
java locale ?

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1721]
java needs to be run with -D options to have the proper locale in order to have OH display item states in the proper format (e.g. "," instead of "." as a separator behind the integer part of a number).
This may or may not be a problem in current openHABian but needs to be checked and changed, eventually. If so derive proper setting from the OS locale setting ?

EXTRA_JAVA_OPTS: "-Duser.country=DE"
EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Berlin"

**Comment by mstormi** [comment]
thanks for explaining and fixing

**Comment by mstormi** [comment]
Just hitting this again myself.
Thing is, system_default_locale was the openhabian.conf parameter to set locale on unattended installs.
It now doesn't work any more.
While current code is fine when system_default_locale is unset, it should be honored when set.

**Comment by florian-h05** [comment]
Oops, I was not aware of this.
I think it should be fine if we check for INTERACTIVE or UNATTENED mode and then use system_default_locale only if we are in UNATTENDED.
I‘ll provide a fix later.
