### ISSUE TITLE
NodeJS newer than v14?

### ISSUE THREAD

**Issue by florian-h05** [openhab/openhabian#1722]
@mstormi 
While I was working on the addition of openhab & openhab_rules_tools to the openhabian-config tool, I noticed that openhabians [`node_is_installed`](https://github.com/openhab/openhabian/blob/96c045b943744c6c8458e7e089fd91d98e4348bd/functions/helpers.bash#L643) check requires NodeJS v14.

As I am on v16 on my openHAB machine (a Debian machine that is using the openhabian-config tool), this causes me some inconvenience.

Is there any reason that we need NodeJS v14 or is it possible to update the check to also „allow“ newer version?

**Comment by mstormi** [comment]
I already updated nodejs install to have v16 installed.
So I believe that check is a leftover that should be updated.
I am not aware of other dependencies, but that is no warranty,
I didn't do this coding and nodeJS is a constant source of problems so this should be properly tested before changing.
Can you test and provide a PR ?

**Comment by florian-h05** [comment]
I found the following dependencies of NodeJS:
- Frontail (works fine with NodeJS v16 — personal experience)
- NodeRED (should work finde with NodeJS v16 — the official Docker container is using v16 & the NodeRED installer scripts by default also install NodeJS v16)

JS Scripting is no NodeJS dependency, we just need npm to install and manage our Node packages.
