### ISSUE TITLE
Can't install packages after latest upgrade

### ISSUE THREAD

**Issue by Lockzi** [openhab/openhabian#173]
Hello,

running OpenHABian on rPi 3. Since the latest upgrade I am unable to install packages.

It always gets stuck after:

```
...
Get:36 http://mirrordirector.raspbian.org/raspbian/ jessie/main libfont-afm-perl all 1.20-1 [14.4 kB]
Get:37 http://mirrordirector.raspbian.org/raspbian/ jessie/main libhtml-form-perl all 6.03-1 [23.9 kB]
Get:38 http://mirrordirector.raspbian.org/raspbian/ jessie/main libhtml-format-perl all 2.11-1 [43.1 kB]
Get:39 http://mirrordirector.raspbian.org/raspbian/ jessie/main libhttp-daemon-perl all 6.01-1 [17.3 kB]
Get:40 http://mirrordirector.raspbian.org/raspbian/ jessie/main libnet-smtp-ssl-perl all 1.01-3 [5,996 B]
Get:41 http://mirrordirector.raspbian.org/raspbian/ jessie/main libmailtools-perl all 2.13-1 [96.6 kB]
Fetched 6,063 kB in 6s (1,003 kB/s)
```

I've waited many hours with the same result, nothing more is being outputted to terminal and the process does not finish.
If I do ctrl+c to cancel process it tells me:

```
^CE: Problem executing scripts DPkg::Pre-Invoke 'if [ -x /usr/bin/etckeeper ]; then etckeeper pre-install; fi'
E: Sub-process returned an error code
```

any ideas?

**Comment by ThomDietrich** [comment]
Hey,
the etckeeper problem is unrelated.

The problem you are seeing can have many sources. Start here to debug it:

* `sudo apt-get clean` https://www.cyberciti.biz/faq/debian-ubuntu-linux-clear-the-package-cache/
* sudo apt update && sudo apt -V upgrade" https://linux.die.net/man/8/apt-get

**Comment by Lockzi** [comment]
@ThomDietrich 
So, I've been continuing with this. And I can now confirm that this messed up a lot of things :(

I stop being able to use apt-get upgrade, until I realized that I had to kill -9 the git --porcelin process.
It has something to do with the etckeeper process.

**Comment by ThomDietrich** [comment]
That's pretty weird. However if your issue is indeed related to etckeeper, you can simply uninstall it.
```
sudo apt purge etckeeper
```
