### ISSUE TITLE
Missing npm-shrinkwrap.json when updating Zigbee2MQTT

### ISSUE THREAD

**Issue by jzielke84** [openhab/openhabian#1735]
## Issue information:
When installing the package through the openhabian-ui the following repository gets cloned:
```shell
$ sudo -u openhabian git clone https://github.com/Koenkk/zigbee2mqtt.git /opt/zigbee2mqtt 
+ sudo -u openhabian git clone https://github.com/Koenkk/zigbee2mqtt.git /opt/zigbee2mqtt
Cloning into '/opt/zigbee2mqtt'...
```

However, when running the same command for updating the package, the following command is issues by the ui:
```shell
+ echo -e '\n\033[90;01m$ sudo -u openhabian git checkout HEAD -- npm-shrinkwrap.json \033[39;49;00m'

$ sudo -u openhabian git checkout HEAD -- npm-shrinkwrap.json 
+ sudo -u openhabian git checkout HEAD -- npm-shrinkwrap.json
```
This fails, because the file `npm-shrinkwrap.json` is not existing in the repository.

## System information:
```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by mstormi** [comment]
@Larsen-Locke can you take a look please ?

**Comment by Larsen-Locke** [comment]
This was an old problem due to a change in zigbee2mqtt-repository, but it's corrected in the current version.
Did you select "main" in menu "Select Branch"?

**Comment by jzielke84** [comment]
@Larsen-Locke It was set to `OpenHAB3` because of being recommended. I changed it to `main` and now the git pull works as expected. Thank you.
