### ISSUE TITLE
Latest Raspbian image wont'install due to Zulu wrong file names

### ISSUE THREAD

**Issue by abarcellona** [openhab/openhabian#1737]
Zulu API changed, so when trying a fresh install, openJDK installation Fails because **does not the find the files to fetch**.

**Comment by boris-ffm** [comment]
I think, i have same problem. Loading jdk 11 failed. With both Images 64 and 32 bit.

**Comment by mstormi** [comment]
This ain't the first time they change API and I'm really done with Azul.
If you figure out what we would need to change then let me know or provide a PR yourself.
But I won't keep playing catch-up with them.

**Comment by cncb-gh** [comment]
What it the latest version that will install correctly?  Thanks.

**Comment by mstormi** [comment]
We now dropped Zulu support
