### ISSUE TITLE
Zigbee2MQTT Update to newest Version

### ISSUE THREAD

**Issue by blackpeat** [openhab/openhabian#1739]
Hi,

I use Zigbee2MQTT via the openhabian-config Installation. But as far as I've seen Zigbee2MQTT is not updated to the newest Version ([1.28.2](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.28.2)) via the Update Openhabian in Openhabian-config.

What is the correct way to Update Zigbee2MQTT?

Is it missing in the update or is there an extra step that is needed?

Thanks in advance an extra step is fine but it would be nice to know.

**Comment by Larsen-Locke** [comment]
See menu 2A under 20 optional components.

**Comment by blackpeat** [comment]
Oh, quite easy to find. Started it but it didn't run through. Will later add more informations.

**Comment by Larsen-Locke** [comment]
Please also make sure that you selected main in 01_select_branch so that you have the latest bug-fix version of zigbee2mqtt install routine.
If it fails we have to do the steps manually to find the problem

**Comment by Larsen-Locke** [comment]
Please remove package_lock.json from /opt/zigbee2mqtt and try again.

**Comment by blackpeat** [comment]
Worked thanks @Larsen-Locke

**Comment by mstormi** [comment]
please close if you think the issue is solved
