### ISSUE TITLE
InfluxDB Problem with correct Rights

### ISSUE THREAD

**Issue by blackpeat** [openhab/openhabian#1741]
Hi,

I useded the openhabian-config to install InfluxDB and Grafana. But after installing I need to change the rights of the folder/var/lib/influxdb/. For that ZRAM needs to be disabeled would be nice if the installer can make it right in the first run.

(https://community.openhab.org/t/problems-installing-influx-on-openhabian-3-2-org-influxdb-influxdbexception-mkdir-var-lib-influxdb-wal-permission-denied/133032/4)

**Comment by mstormi** [comment]
It does. Manually purged and freshly installed InfluxDB:

[09:37:00] root@devpi:/home/openhabian/openhabian/functions# cd /var/lib/influxdb/
[09:37:05] root@devpi:/var/lib/influxdb# ls -lad .
drwxr-xr-x 1 influxdb influxdb 4096 Nov 22 09:33 .
[09:37:38] root@devpi:/var/lib/influxdb# ls -adl /opt/zram/influxdb.bind/
drwxr-xr-x 2 influxdb influxdb 4096 Okt 11  2021 /opt/zram/influxdb.bind/


Dunno where your issue originates from as you have not given comprehensive/required info but it doesn't seem to happen on
new installs so it isn't an issue.

**Comment by blackpeat** [comment]
Did a complete fresh install. And after a reboot the rights are not set correct. I use latest branch.

**Comment by mstormi** [comment]
> Did a complete fresh install.

Install of *what* ? Image, OS, apt package, via menu ?
Which HW ? Which version ? Which branch ? Did you remove Influx? How ?
Provide *comprehensive* information. This sort of Q&A game is annoying and waste of time.
