### ISSUE TITLE
Specify to not have a keyboard plugged in during setup (openhab-docs transfer)

### ISSUE THREAD

**Issue by Confectrician** [openhab/openhabian#1742]
Hi,

Just want to transfer an issue that came up in the cods repository.
I have mentioned @mstormi over there in September but did not receive a feedback yet.

Original issuer: @TangoOversway

---

>On the [OpenHABian setup page](https://www.openhab.org/docs/installation/openhabian.html) a keyboard and monitor and headless >use is mentioned 3 times:
>In Features, while listing features, one item states: Hassle-free setup without a display or keyboard, connected via Ethernet or Wi-Fi
>In Raspberry Pi prepackaged SD card image it states: openHABian is designed as a headless system, you will not need a display or a >keyboard.
>In Where is the graphical user interface? (under Did my Installation succeed? What to do in case of a problem?), it states: An RPi is not >(well, not necessarily) to be used with a keyboard and display.
>The last one is the strongest wording, but even then, the "not" (for use of a keyboard) is amended with "not necessarily." And now days >there is the Pi 400 and Raspbian itself comes with a GUI, so we can conclude that now Pis are often used on a desktop with a keyboard >and monitor (and often a mouse). I use Pis in my workshop to control devices and they have either touchscreen interfaces or a small >monitor and an accompanying mouse (and maybe a keyboard, depending on the device).

>However, the openHab setup does not work with a keyboard plugged in. I found this out through experience. While it might be a good idea to suggest that the setup be keyboard agnostic (as opposed to anti-keyboard), the wording in these three places basically says and implies "keyboard and monitor are optional." Many people prefer to have a keyboard and monitor attached to systems during setup.

>As long as oH will detect a keyboard and behave differently if one is attached, and that will prevent the install from working properly, when the keyboard and ability to run headless is mentioned, extra wording to clarify that that a keyboard should not be attached needs to be included.

>(Note: I use low price keyboard/mouse combinations that connect wirelessly to a USB dongle and my experience is that a lot of software doesn't detect a keyboard if the keyboard is turned off, but openHab had issues and detected the keyboard with the USB dongle plugged in and the keyboard turned off.)

Reference: https://github.com/openhab/openhab-docs/issues/1880

---

I can't do much about this in the docs repository and i am also not able to give any valuable feedback.

**Comment by mstormi** [comment]
Very explicit wording already *is* part of the current docs, see referred issue.
