### ISSUE TITLE
possible to use different mqtt server when installing zigbee2mqtt

### ISSUE THREAD

**Issue by mpuff** [openhab/openhabian#1747]
hello,

please add to specify another mqtt server when installing zigbee2mqtt

**Comment by Larsen-Locke** [comment]
Feel free to contribute;⁠)

**Comment by mstormi** [comment]
I'd be happy to take a PR that does it if you contribute it.
But I'm closing this as it's out of scope to expect from an openHABian installer to use a non-openHABian MQTT server.
