### ISSUE TITLE
add Clean cache menu option

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1748]

**Comment by mstormi** [comment]
@BClark09 maybe you could add it ?

**Comment by BClark09** [comment]
As in a menu option which simply runs `openhab-cli clean-cache`?

**Comment by mstormi** [comment]
yep

**Comment by mstormi** [comment]
I'm currently looking to reduce open issues and this looks like an easy one.
@BClark09 or @ecdye would you consider adding this ?

**Comment by ecdye** [comment]
I'm not opposed to looking into it. I can try and work on it when I get some free time to do it.
