### ISSUE TITLE
failure when try to update zigbee2mqtt

### ISSUE THREAD

**Issue by mpuff** [openhab/openhabian#1749]
I tried to do an update from openhabian-config, I get the error:

<img width="465" alt="Bildschirm­foto 2023-01-06 um 16 25 05" src="https://user-images.githubusercontent.com/13885599/211043933-caa30fd7-842d-432f-8b85-6184bc3c94c7.png">

<img width="690" alt="image" src="https://user-images.githubusercontent.com/13885599/211044207-a358ed31-e241-4352-8036-2e1ca8f09915.png">

**Comment by Larsen-Locke** [comment]
Please do
cd /opt/zigbee2mqtt
git pull
and tell me what you see

**Comment by mpuff** [comment]
<img width="445" alt="image" src="https://user-images.githubusercontent.com/13885599/211084704-de49691b-7e0a-46cf-aa77-ea38ab093377.png">

**Comment by mpuff** [comment]
git restore package-lock.json worked to remove error message ... thanks
