### ISSUE TITLE
Problem with beowulfe/HAP-Java

### ISSUE THREAD

**Issue by trailblazer2006** [openhab/openhabian#175]
Hi. I just installed version 2.1 from openhabian-config. But I was faced with a problem in the HomeKit addon, which has been solved long time ago. Here is the link https://github.com/beowulfe/HAP-Java/commit/9ba46a5b0363a1f954b039e678b1b911cac74650. I don't understand how to update hap-java to the working version. Help me please.

**Comment by ThomDietrich** [comment]
Hello, I have honestly no idea what you are talking about. Please remeber that openHABian is "just" your Linux distribution. For openHAB guidance please visit our excellent community forum.
http://community.openhab.org

Good luck!

**Comment by trailblazer2006** [comment]
Hello. Thank you for responding to my request. I have been reading forums for the third day, but I can not find any hint of a solution to my problem. I understand that I need to update the file or all that contains the wrong code. But I do not understand how to do this on raspberries. I installed the version manually on Vidovz and it all works. But I'm new to Unix systems and can not find the file itself, nor a hint on how to update the whole package. Please help, I think it will not be difficult for you to check which version of the file is in your distribution and how to fix the problem.
With hope, Alexander.

**Comment by ThomDietrich** [comment]
Hello @trailblazer2006,
I just saw your posting over there in the thread. I hope somebody will answer! :)
From what I can see, the version [included in the HomeKit addons](https://github.com/openhab/openhab2-addons/blob/master/addons/io/org.openhab.io.homekit/build.properties) is v1.1.3, which is older than the change you have linked above. Your best bet would hence be to ask the author (via the ticket you've created) to build and provide a new v1.1.4.
The alternative would be to build it yourself but it would be better to go this path, then officially include the new version in openHAB.

**Comment by trailblazer2006** [comment]
I understood my next steps. I'm very grateful for your help.
