### ISSUE TITLE
Problem while installing UI's

### ISSUE THREAD

**Issue by luisrival** [openhab/openhabian#176]
I´m doing a new installation in a rapi 3, but at time that I need to select the UI mode, it never finish the installation. the error in the log file is this:
[https://community-openhab-org.s3-eu-central-1.amazonaws.com/original/2X/b/b468776313f658f25f6cdfec4f15b403cae3e7c3.PNG](url)

And the Java versión I have installed si this:

[https://community-openhab-org.s3-eu-central-1.amazonaws.com/original/2X/0/0ebe07388c6832b22c24919112965897712b6e3f.PNG](url)

I downloaded and installed OpenHabian V1.3

**Comment by ThomDietrich** [comment]
Hello @luisrival,
without more info we can't help you much. Did you restart? Did you try to install something? Did you reload the page?

**Comment by luisrival** [comment]
Yes, I tried to restart, and when Bootup, there Still the sabe page of loading, the only think that O install before was Mosquitto, but then I reinstalled the hole system and try to install First de UI and the same result. I always try updated all with the "sudo apt-get update" and then install de UI from the webpage " ip address:8080" and the same results

**Comment by hr3** [comment]
How long did you wait and have you tried it again?
I think starting up is most slower now.

PS: I found your .PNGs but the links are wrong

**Comment by luisrival** [comment]
I Wait the whole night

**Comment by luisrival** [comment]
![imagen](https://user-images.githubusercontent.com/8862466/29755699-55059fa8-8b61-11e7-9a06-a4e8a0ca8c4a.png)

**Comment by ThomDietrich** [comment]
Hey guys, I suspect this to be solved and guess it was a temporary issue. Closing for now
