### ISSUE TITLE
Error: "Oh no! something have gone wrong." 

### ISSUE THREAD

**Issue by StergiosT0** [openhab/openhabian#1772]
Hello, after the openhab installation i get the error  during the boot.

Also i can't login in the desktop.
See attachements pics below

Any solution?

Thanks in advance!
![εικόνα_2023-04-23_144937101](https://user-images.githubusercontent.com/26569006/233837981-14e19932-7b66-411e-8367-5937ea6b2400.png)

![εικόνα_2023-04-23_144842919](https://user-images.githubusercontent.com/26569006/233837934-8ad750e7-9702-4ce3-aea4-14443d6dca7c.png)

**Comment by mstormi** [comment]
openHABian is headless. You are not supposed to login via GUI.

**Comment by StergiosT0** [comment]
Finally, i solve it using apt-get remove --auto-remove --purge libx11-.*
Then installed defauld UI
