### ISSUE TITLE
"Fix Permissions" gives wrong ownership to /var/lib/influxdb

### ISSUE THREAD

**Issue by jhazan-jpg** [openhab/openhabian#1781]
The Fix Permissions feature changes the ownership of /var/lib/influxdb to root:root. The correct permissions are influxdb:influxdb.

The result of the permissions being set incorrectly is that the influxdb service is unable to start as it cannot create /var/lib/influxd.pid
 
https://github.com/openhab/openhabian/blob/e63dbeca062b70d6586c2f66af8f0667f880cddf/functions/system.bash#L329

**Comment by mstormi** [comment]
Fixed-by: c471f037438966f1eed75d3fc099c946b97e5873
