### ISSUE TITLE
Error when setting up SD mirroring (mirror_sd)

### ISSUE THREAD

**Issue by jhazan-jpg** [openhab/openhabian#1782]
e2fsck does not have a -U option, so the command always fails and the dirty flag is therefore set. It appears that this option has been mistakenly copied from the call to tune2fs on the next line of code.

https://github.com/openhab/openhabian/blob/c471f037438966f1eed75d3fc099c946b97e5873/functions/backup.bash#L422

**Comment by mstormi** [comment]
thanks for reporting so precisely
