### ISSUE TITLE
Bookworm readyness

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1788]
New Debian release "bookworm" is out.

- [x] firmware move `config.txt`
- [x] check all 3rd party repos for bookworm upgrades and compatibility
- - [x] [deCONZ](https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/v2.22.2) (`generic` and `generic-beta` can be used instead of `bullseye` or `bookworm` now)
- - [x] [HomeGear](https://apt.homegear.eu/)  #1853 
- - [x] [InfluxData](https://repos.influxdata.com/debian/dists/) (no `bookworm` yet but `stable` exists, does this work?)
- - [x] [Node 18.x](https://deb.nodesource.com/node_18.x/dists/)
- - [x] [Tailscale (debian](https://pkgs.tailscale.com/stable/) `bookworm` exists).
- [x] build new image when Raspi OS image becomes available
- [x] static WiFi does not work any more https://github.com/openhab/openhabian/issues/1823
- - [x] comitup TBD
- [x] #1843

**Comment by BClark09** [comment]
> New Debian release "bookworm" is out. Expect Raspi OS images to follow anytime soon.
>     * [ ]  check all 3rd party repos for bookworm upgrades

To confirm the dist exists (not necessarily if they are installable on openHABian):

- [*] [deCONZ](https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/v2.22.2) (`generic` and `generic-beta` can be used instead of `bullseye` or `bookworm` now)
- [ ] [HomeGear](https://apt.homegear.eu/)
- [ ] [InfluxData](https://repos.influxdata.com/debian/dists/) (no `bookworm` yet but `stable` exists, does this work?)
- [*] [Node 18.x](https://deb.nodesource.com/node_18.x/dists/)
- [ ] [Tailscale (debian](https://pkgs.tailscale.com/stable/) `bookworm` exists but Raspberry Pi `bookworm` does not).

**Comment by mstormi** [comment]
> [deCONZ](https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/v2.22.2) (generic and generic-beta can be used instead of bullseye or bookworm now)

What exactly does that mean, could we change the repo to `generic` in all cases ? Would that work on bookworm ?
Or would I need to dynamically decide to use either `generic` or `generic-beta` depending on what the distro is ?

**Comment by BClark09** [comment]
> What exactly does that mean, could we change the repo to generic in all cases ? 
It looks like it, yes.

>Or would I need to dynamically decide to use either the generic or the generic-beta repo depending on what the distro is ?
No, generic-beta contains all packages. generic contains stable only but for multiple architectures.

```
ben@TEST-PC:~$ apt-cache madison deconz:amd64
    deconz | 2.22.02-debian-buster-stable | http://phoscon.de/apt/deconz generic/main amd64 Packages
    deconz | 2.22.02-debian-buster-stable | http://phoscon.de/apt/deconz bookworm/main amd64 Packages
    deconz | 2.22.02-debian-buster-beta | http://phoscon.de/apt/deconz generic-beta/main amd64 Packages

ben@TEST-PC:~$ apt-cache madison deconz:arm64
deconz:arm64 | 2.22.02-debian-buster-stable | http://phoscon.de/apt/deconz generic/main arm64 Packages
deconz:arm64 | 2.22.02-debian-buster-stable | http://phoscon.de/apt/deconz bookworm/main arm64 Packages
deconz:arm64 | 2.22.02-debian-buster-beta | http://phoscon.de/apt/deconz generic-beta/main arm64 Packages

ben@TEST-PC:~$ apt-cache madison deconz:armhf
deconz:armhf | 2.22.02-raspbian-buster-stable | http://phoscon.de/apt/deconz generic/main armhf Packages
deconz:armhf | 2.22.02-raspbian-buster-stable | http://phoscon.de/apt/deconz bookworm/main armhf Packages
deconz:armhf | 2.22.02-raspbian-buster-beta | http://phoscon.de/apt/deconz generic-beta/main armhf Packages
```

**Comment by krikk** [comment]
just did a fresh install on debian 12 (bookworm) **amd64** (netinstall iso) like described [here](https://www.openhab.org/docs/installation/openhabian.html#other-linux-systems-add-openhabian-just-like-any-other-software)

out of the box: 
`openhabian-config unattended`
fails...

i see the following errors:

**frontail installs fail because of missing npm**
Fix:
`apt install npm`
before running openhabian-config unattended

**java 17 install fail because failure to install ca-certificates-java** --> seems to be this [bug ](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1030129)
temporary FIX (should be fixed in stable bookworm in the next few days (weeks)): 
enable testing repos, see [here](https://jaqque.sbih.org/kplug/apt-pinning.html) and then install testing version:
`apt install ca-certificates-java/testing openjdk-17-jre-headless/testing`

another minor issue:
`update-alternatives: error: alternative /usr/lib/jvm/java-17-openjdk-armhf/bin/java for java not registered; not setting`
as i am on amd64 this call can not work, but because java 17 is the only java, no problem -> problem in openhabian script??

...so all in all only minor problem :)

**Comment by mstormi** [comment]
> Fix:
> `apt install npm`
> before running openhabian-config unattended

`npm` should be installed along the way.
Can you check `/boot/first-boot.log` and post that please. `debugmode=maximum` required during install of course else there will not be much contents of use.

> another minor issue:
> `update-alternatives: error: alternative /usr/lib/jvm/java-17-openjdk-armhf/bin/java for java not registered; not setting`

again post the install log please else I would not know what to make of that.

**Comment by Larsen-Locke** [comment]
@mstormi : That sounds similar to the issue we had with npm: It's installed together with node but sometimes node doesn't install (e.g. gpg-keys) and then the missing npm is the first problem that pops up.

**Comment by krikk** [comment]
as it is manual (openhabian-config unattended) install on **intel AMD64**, so no first-boot.log, but i have redirected all output to log file from "openhabian-config unattended"

first log with basic debian 12 (bookworm) netinstall, without preinstalling anything
[openhab_install_unatteded_FAILED.log](https://github.com/openhab/openhabian/files/12209436/openhab_install_unatteded_FAILED.log)

second log with preinstalled npm and java17:
[openhab_unatted_with_NPM_and_JAVA_preinstalled.log](https://github.com/openhab/openhabian/files/12209439/openhab_unatted_with_NPM_and_JAVA_preinstalled.log)

hope this helps, sorry no debugmode=maximum

**Comment by Egyras** [comment]
influxdb install issues with latest 1.9b image on rpi5:

`+ apt-get update
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://archive.raspberrypi.com/debian bookworm InRelease
Hit:3 http://deb.debian.org/debian-security bookworm-security InRelease
Hit:4 http://deb.debian.org/debian bookworm-updates InRelease
Hit:5 https://deb.nodesource.com/node_18.x bookworm InRelease
Hit:6 http://davesteele.github.io/comitup/repo comitup InRelease
Ign:7 https://repos.influxdata.com/debian bookworm InRelease
Err:8 https://repos.influxdata.com/debian bookworm Release
  404  Not Found [IP: 65.9.55.34 443]
Hit:9 https://openhab.jfrog.io/artifactory/openhab-linuxpkg stable InRelease
Reading package lists... Done
E: The repository 'https://repos.influxdata.com/debian bookworm Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
+ return 100
+ echo 'FAILED (update apt lists)'
FAILED (update apt lists)
+ return 1
+ return 1
+ echo FAILED
FAILED
`

**Comment by Larsen-Locke** [comment]
Just tested 1.8b: Everything smooth except npm was missing:
Do we still need the complicated install routing (nodejs-apps.bash line 8-48)?
I think that was because node was not included in the keys of buster.
I thought we could replace everything with a simple "sudo apt install nodejs npm -y".
But I don't know what this OFFLINE and PREOFFLINE is all about.

**Comment by HarrysLapTimer** [comment]
> influxdb install issues with latest 64bit 1.9b image on rpi5:
> 
> ```
> + apt-get update
> Hit:1 http://deb.debian.org/debian bookworm InRelease
> Hit:2 http://archive.raspberrypi.com/debian bookworm InRelease
> Hit:3 http://deb.debian.org/debian-security bookworm-security InRelease
> Hit:4 http://deb.debian.org/debian bookworm-updates InRelease
> Hit:5 https://deb.nodesource.com/node_18.x bookworm InRelease
> Hit:6 http://davesteele.github.io/comitup/repo comitup InRelease
> Ign:7 https://repos.influxdata.com/debian bookworm InRelease
> Err:8 https://repos.influxdata.com/debian bookworm Release
>   404  Not Found [IP: 65.9.55.34 443]
> Hit:9 https://openhab.jfrog.io/artifactory/openhab-linuxpkg stable InRelease
> Reading package lists... Done
> E: The repository 'https://repos.influxdata.com/debian bookworm Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> + return 100
> + echo 'FAILED (update apt lists)'
> FAILED (update apt lists)
> + return 1
> + return 1
> + echo FAILED
> FAILED
> ```
> 
> please change to **stable** as no more different packages according [influxdata/telegraf#13759](https://github.com/influxdata/telegraf/issues/13759)

Can you please let me know what exactly to change where? I run into the same issue when installing Influx/Grafana from openhabian-config

**Comment by mstormi** [comment]
> Just tested 1.8b: Everything smooth except npm was missing: Do we still need the complicated install routing (nodejs-apps.bash line 8-48)? I think that was because node was not included in the keys of buster. I thought we could replace everything with a simple "sudo apt install nodejs npm -y". But I don't know what this OFFLINE and PREOFFLINE is all about.

Please do.


OFFLINE is essentially what happens when the box-under-install has no Internet access. We provide Raspi OS but also some apt packages as part of the image and try to install from there when we cannot retrieve their latest versions from the repo.

I'd have to sync myself with the code again to make sure but I think PREOFFLINE is what happens on image creation, i.e. to pull in (download) apt packages and make them become part of the image so they're available when you want to install but are OFFLINE.

**Comment by mstormi** [comment]
@Egyras @HarrysLapTimer this is the development GitHub repo and not meant to be a user service desk

So if you can provide the information you're looking for or contribute a solution as a PR, please do, but don't request us to provide information we don't have ourselves. As can be read in the first post.

**Comment by JasonMask** [comment]
> > New Debian release "bookworm" is out. Expect Raspi OS images to follow anytime soon.
> > * [ ]  check all 3rd party repos for bookworm upgrades
> 
> To confirm the dist exists (not necessarily if they are installable on openHABian):
> 
> * [x]  [deCONZ](https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/v2.22.2) (`generic` and `generic-beta` can be used instead of `bullseye` or `bookworm` now)
> * [x]  [HomeGear](https://apt.homegear.eu/)
> * [ ]  [InfluxData](https://repos.influxdata.com/debian/dists/) (no `bookworm` yet but `stable` exists, does this work?)
> * [x]  [Node 18.x](https://deb.nodesource.com/node_18.x/dists/)
> * [x]  [Tailscale](https://pkgs.tailscale.com/stable/) (debian) `bookworm` exists but Raspberry Pi `bookworm` does not).

there are now stable releases available for bookworm for [HomeGear ](https://apt.homegear.eu/raspberry_pi_os/bookworm/homegear/stable/dists/bookworm/)and [Tailscale](https://pkgs.tailscale.com/stable/#debian-bookworm)

**Comment by JasonMask** [comment]
> Thanks for the info.
> 
> Can you create a Pull Request, too ?

unfortunately i couldn´t find where to update the paths so my answer is no (also i haven´t got the repo checked out currently)

**Comment by Egyras** [comment]
> > influxdb install issues with latest 64bit 1.9b image on rpi5:
> > ```
> > + apt-get update
> > Hit:1 http://deb.debian.org/debian bookworm InRelease
> > Hit:2 http://archive.raspberrypi.com/debian bookworm InRelease
> > Hit:3 http://deb.debian.org/debian-security bookworm-security InRelease
> > Hit:4 http://deb.debian.org/debian bookworm-updates InRelease
> > Hit:5 https://deb.nodesource.com/node_18.x bookworm InRelease
> > Hit:6 http://davesteele.github.io/comitup/repo comitup InRelease
> > Ign:7 https://repos.influxdata.com/debian bookworm InRelease
> > Err:8 https://repos.influxdata.com/debian bookworm Release
> >   404  Not Found [IP: 65.9.55.34 443]
> > Hit:9 https://openhab.jfrog.io/artifactory/openhab-linuxpkg stable InRelease
> > Reading package lists... Done
> > E: The repository 'https://repos.influxdata.com/debian bookworm Release' does not have a Release file.
> > N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> > N: See apt-secure(8) manpage for repository creation and user configuration details.
> > + return 100
> > + echo 'FAILED (update apt lists)'
> > FAILED (update apt lists)
> > + return 1
> > + return 1
> > + echo FAILED
> > FAILED
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > please change to **stable** as no more different packages according [influxdata/telegraf#13759](https://github.com/influxdata/telegraf/issues/13759)
> 
> Can you please let me know what exactly to change where? I run into the same issue when installing Influx/Grafana from openhabian-config

didnt tried to move forward with the install, dont have time to check now :(

**Comment by mstormi** [comment]
> there are now stable releases available for bookworm for [HomeGear ](https://apt.homegear.eu/raspberry_pi_os/bookworm/homegear/stable/dists/bookworm/)and [Tailscale](https://pkgs.tailscale.com/stable/#raspbian-bookworm)

@JasonMask I'm struggling with the homegear repo

On my RPi3 test box (armhf) it's trying to install arm64 any idea??

```
N: Das Laden der konfigurierten Datei »main/binary-arm64/Packages« wird übersprungen, da das Depot »https://apt.homegear.eu/raspberry_pi_os/bookworm/homegear/testing bookworm InRelease« die Architektur »arm64« nicht unterstützt.
```

**Comment by JasonMask** [comment]
@mstormi sorry for my late reply. I´ve been on holiday last week.
Unfortunately I´m not part of the Homegear project but was just checking that the repository path is now available.

I believe it was back then (with content) when I checked in January, however human error is always an option :/
However I believe the repository is now available again with the same file structure then the bullseye path
![image](https://github.com/openhab/openhabian/assets/11296381/c3b371c9-1c3b-4450-aad6-3026f4740837)

You might be able to run the build successfully now.

I´m sorry that I´m unable to do anything else but to check.

thank you for the work you put into this and best regards

**Comment by mstormi** [comment]
not really
or does this work for you?


```
[17:28:38] root@openhabian:/etc/apt/sources.list.d# cat homegear.list
deb [signed-by=/usr/share/keyrings/homegear-archive-keyring.gpg] https://apt.homegear.eu/raspberry_pi_os/bookworm/homegear/testing bookworm main
[17:28:40] root@openhabian:/etc/apt/sources.list.d# apt-get install --yes -o DPkg::Lock::Timeout= homegear homegear-homematicbidcos homegear-homematicwired homegear-max homegear-management
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package homegear
E: Unable to locate package homegear-homematicbidcos
E: Unable to locate package homegear-homematicwired
E: Unable to locate package homegear-max
E: Unable to locate package homegear-management
```

**Comment by JasonMask** [comment]
damn. just checked the actual file content and it turns out that while the file structure is there, it remains empty.
only thing i could find on their side was an git issue (https://github.com/Homegear/Homegear/issues/373) reported with a link to their forum that again is not reachable right now. At least I´m getting an "ERR_CONNECTION_TIMED_OUT" when trying to access the forum.
looks like we have to uncheck homegear again for now

**Comment by JasonMask** [comment]
> > > New Debian release "bookworm" is out. Expect Raspi OS images to follow anytime soon.
> > > 
> > > * [ ]   check all 3rd party repos for bookworm upgrades
> > 
> > 
> > To confirm the dist exists (not necessarily if they are installable on openHABian):
> > 
> > * [x]   [deCONZ](https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/v2.22.2) (`generic` and `generic-beta` can be used instead of `bullseye` or `bookworm` now)
> > * [ ]   [HomeGear](https://apt.homegear.eu/raspberry_pi_os/bookworm/homegear/stable/dists/bookworm/)
> > * [ ]   [InfluxData](https://repos.influxdata.com/debian/dists/) (no `bookworm` yet but `stable` exists, does this work?)
> > * [x]   [Node 18.x](https://deb.nodesource.com/node_18.x/dists/)
> > * [x]   [Tailscale](https://pkgs.tailscale.com/stable/#raspbian-bookworm).
> 
> there are now stable releases available for bookworm for [HomeGear ](https://apt.homegear.eu/raspberry_pi_os/bookworm/homegear/stable/dists/bookworm/)and [Tailscale](https://pkgs.tailscale.com/stable/#raspbian-bookworm)
Uncheck HomeGear as the current "releases" are empty

**Comment by thicknesss** [comment]
Goodday,
Debian 12 (Bookworm) forces the use of Python Virtual environments (venv) for some packages.
for example myflora-mqtt-daemon fails to install on the latest openhabian image.
See [PR 176](https://github.com/ThomDietrich/miflora-mqtt-daemon/pull/176) and [PR 177](https://github.com/ThomDietrich/miflora-mqtt-daemon/pull/177) on that repo to fix that.

IMHO this belongs in bookworm readyness to.
If you want me to make a new issue please let me know.

**Comment by mstormi** [comment]
>  If you want me to make a new issue please let me know.

Not really, there would be noone to work on this.
If you can contribute a PR to fix it, please do.

**Comment by mstormi** [comment]
seems we're finally done
