### ISSUE TITLE
openhab2 cannot open ports

### ISSUE THREAD

**Issue by ddorish** [openhab/openhabian#179]
Hello
I had a working installation of OH2, until some apt-get update.
Tried to remove everything, and freshly install, to no avail.
Current situation is:
- I start the OH2 service
- Then I `systemctl status openhab2`
And get
```● openhab2.service - LSB: openHAB2 server
   Loaded: loaded (/etc/init.d/openhab2)
   Active: active (running) since Thu 2017-07-13 12:55:57 IDT; 9min ago
  Process: 2981 ExecStop=/etc/init.d/openhab2 stop (code=exited, status=0/SUCCESS)
  Process: 5369 ExecStart=/etc/init.d/openhab2 start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/openhab2.service
           ├─5466 /bin/bash /usr/share/openhab2/runtime/bin/karaf server
           └─5569 /usr/lib/jvm/jre-8-oracle-x64/bin/java -Dopenhab.home=/usr/share/openhab2 -Dopenhab.conf=/etc/openhab2 -Dopenhab.runtime=/usr/share/openhab2/runtime -Dopenhab.userdata=/var/lib/openhab2 -Dopenhab.logdir=/var/log/openhab2 -Dfelix.cm.dir=/var/lib/openh...

Jul 13 12:55:57 storage openhab2[5369]: Starting openHAB2 server: openhab2.
Jul 13 12:55:57 storage systemd[1]: Started LSB: openHAB2 server.
```

But ports 8080 and 8101 are not listening (saw using `netstat -a | grep 8080` and alike)

All files in `/usr/share/openhab2` are owned by openhab:openhab

What am I missing ? Thanks in advance!

**Comment by BClark09** [comment]
Hi @ddorish, it might be better to post this issue in the [community forums](https://community.openhab.org/)

Are there any errors when you check `journalctl -u openhab2 -b`

**Comment by ddorish** [comment]
Oops... Sorry.
Moved it here:
https://community.openhab.org/t/openhab-cannot-start-after-upgrade-ports-not-opened/31527
Thanks

**Comment by ThomDietrich** [comment]
Thanks @BClark09
