### ISSUE TITLE
Upgrade to openhabian 1.8 an OH 4.0

### ISSUE THREAD

**Issue by helmar74** [openhab/openhabian#1791]
## Issue information:
Hi, I just have a question.
MAybe someone ca help me.
I'm currently running Openhab 3.4.4 on a "older" openhabian installation.
Now I'm thinking of doing a nwe installation of openhabian 1.8 (mainly in order to move to a new software platform (bulls eye))

So the question is:
If I install openhabian 1.8 on a new hardware and I create a Openhab 3.4.4 Backup on my productive system,
can I restore the 3.4.4 backup on a new openhabiab 1.8 / Openhab 4.0 system?

Of course I have to change/adapt all my system settings e.g cronjobs, backups, monitoring on the new system.
I would assume there's no other possibility to upgrade the current system to openhabian 1.8 and Openhab 4.0?

Thank you in advance!

## Debug information:
Please provide all of the output provided by utilizing the `debugmode=maximum`
parameter in the `/etc/openhabian.conf` file. For more information on how to
accomplish this, please see [openhabian-DEBUG.md](https://github.com/openhab/openhabian/blob/main/docs/openhabian-DEBUG.md#create-a-debug-log).
```
place logs here
```

## System information:
Please tell us what OS you are running (Raspberry Pi OS, Debian, Ubuntu), what
HW you are running on (Raspberry Pi, amd64). Also include the output of
`cat /etc/os-release` and `uname -m`.
```
place output here
```

**Comment by mstormi** [comment]
Github is for development.
Please direct questions at the forum only. You already have gotten an answer there.
