### ISSUE TITLE
Drop evcc user overrides

### ISSUE THREAD

**Issue by pauxus** [openhab/openhabian#1797]
## Issue information:
see https://github.com/evcc-io/evcc/discussions/8873

openhabian seems to configure evcc using the base user of the installation. This was valid for old evcc versions which did run under root by default.

However, newer versions (since 0.113 IIRC) run by a service user 'evcc', so the created override file might lead to confusion (as in the linked discussion).

Please consider completely dropping the overrides.

see https://github.com/evcc-io/evcc/blob/master/packaging/scripts/preinstall.sh for reference.

**Comment by mstormi** [comment]
please validate if that works for you

**Comment by mstormi** [comment]
feedback?

**Comment by pauxus** [comment]
Sorry, did not yet get around to it. 

One thing I noticed while looking at the PR (only on my mobile): Config of evcc seems to (still) reside in /home/…, this might cause problems. But I need a big screen to look at it (and to run a test).

**Comment by mstormi** [comment]
you seem to not have much interest in helping getting this done.
So I assume it's working.
