### ISSUE TITLE
Allplay-Binding not working because of wrong libssl

### ISSUE THREAD

**Issue by Uwe-Git** [openhab/openhabian#1805]
## Issue information:

The Allplay-Binding does not work in Openhabian 3.4.x and 4.0.x  (32 Bit) out of the Box. I have to install the libssl1.0.0_1.0.1t-1+deb8u12_armhf.deb in addition go get it work.

ldconfig shows:
*libssl3.so (libc6,hard-float) => /lib/arm-linux-gnueabihf/libssl3.so
libssl.so.1.1 (libc6,hard-float) => /lib/arm-linux-gnueabihf/libssl.so.1.1*

There seems to be a dependency of the AllPlay Binding for libsss 1.0

I have to install the old library to get the binding to work. With the old library, the binding works.
The binding does not find any of my Panasonic Allplay devices until I install the old libssl in addition with

*dpkg --force-depends -i libssl1.0.0_1.0.1t-1+deb8u12_armhf.deb*

## Debug information:
The Bindig will not support any Panasonic Allplay Device until I install the old library.

## System information:
At the moment Openhabian 3.4.1 (32 Bit) but I even tried 4.0.1 (32 Bit) with the same effect on an RaspberryPI.

**Comment by mstormi** [comment]
Bindings are Java they should not be using any libs so openHABian should not need to provide it.
Check with the binding maintainer.
