### ISSUE TITLE
openhab not installed

### ISSUE THREAD

**Issue by dimmenhau** [openhab/openhabian#1807]
## Issue information:
openhab is not installed in image 1.8 and 1.8b because it is not found in the apt repository.

## Debug information:
```
++ apt-cache madison openhab
++ head -n 1
++ cut '-d|' -f2
++ xargs
+ openhabVersion=4.0.1-1
+ [[ -n 4.0.1-1 ]]
+ installVersion='openhab=4.0.1-1 openhab-addons=4.0.1-1'
+ cond_redirect apt-get install --allow-downgrades --yes -o DPkg::Lock::Timeout= --option Dpkg::Options::=--force-confnew 'openhab=4.0.1-1 openhab-addons=4.0.1-1'
+ [[ -n '' ]]
+ echo -e '\n\033[90;01m$ apt-get install --allow-downgrades --yes -o DPkg::Lock::Timeout= --option Dpkg::Options::=--force-confnew openhab=4.0.1-1 openhab-addons=4.0.1-1 \033[39;49;00m'

$ apt-get install --allow-downgrades --yes -o DPkg::Lock::Timeout= --option Dpkg::Options::=--force-confnew openhab=4.0.1-1 openhab-addons=4.0.1-1 
+ apt-get install --allow-downgrades --yes -o DPkg::Lock::Timeout= --option Dpkg::Options::=--force-confnew 'openhab=4.0.1-1 openhab-addons=4.0.1-1'
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package openhab=4.0.1-1 openhab-addons
E: Couldn't find any package by glob 'openhab=4.0.1-1 openhab-addons'
E: Couldn't find any package by regex 'openhab=4.0.1-1 openhab-addons'
+ return 100
+ echo FAILED
FAILED
+ return 1
```
Search in apt repository
```
[07:06:11] root@openhabian:/etc/apt/sources.list.d# apt search openhab
Sorting... Done
Full Text Search... Done
openhab/stable,stable 4.0.1-1 all
  openhab

openhab-addons/stable,stable 4.0.1-1 all
  openhab-addons

openhab2/stable,stable 2.5.12-1 all
  openhab2

openhab2-addons/stable,stable 2.5.12-1 all
  openhab2-addons

openhab2-addons-legacy/stable,stable 2.5.3-1 all
  openhab2-addons-legacy
```

## System information:
cat /etc/os-release
```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
uname -m
`aarch64`

**Comment by dimmenhau** [comment]
Hello,
i have found the problem and i have a fix in my local installation.

The problem is line 101 in the script openhab.bash
actuell:
`if cond_redirect apt-get install --allow-downgrades --yes -o DPkg::Lock::Timeout="$APTTIMEOUT" --option Dpkg::Options::="--force-confnew" "$installVersion"; then echo "OK"; else echo "FAILED"; return 1; fi`
fix:
`if cond_redirect apt-get install --allow-downgrades --yes -o DPkg::Lock::Timeout="$APTTIMEOUT" --option Dpkg::Options::="--force-confnew" ${installVersion}; then echo "OK"; else echo "FAILED"; return 1; fi`

**Comment by dimmenhau** [comment]
Hello,
i found the problem in the script openhab.bash in line 101

line with the problem:
`if cond_redirect apt-get install --allow-downgrades --yes -o DPkg::Lock::Timeout="$APTTIMEOUT" --option Dpkg::Options::="--force-confnew" "$installVersion"; then echo "OK"; else echo "FAILED"; return 1; fi'

line with fix the problem:
`if cond_redirect apt-get install --allow-downgrades --yes -o DPkg::Lock::Timeout="$APTTIMEOUT" --option Dpkg::Options::="--force-confnew" ${installVersion}; then echo "OK"; else echo "FAILED"; return 1; fi`

Can you check this and fix repository, please.

Greating
       Dietmar

**Comment by mstormi** [comment]
Fixed-By: https://github.com/openhab/openhabian/commit/2419ef85d0742c7d6872b6bb1088d427a3745df7
