### ISSUE TITLE
New grafana signing key required

### ISSUE THREAD

**Issue by Diapolo** [openhab/openhabian#1809]
See https://grafana.com/blog/2023/08/24/grafana-security-update-gpg-signing-key-rotation

**Comment by mstormi** [comment]
Nope, latest key is retrieved right on install.

**Comment by Diapolo** [comment]
@mstormi So you don't care about machines already running and leave them stuck on the installed grafana versions because `apt update` fails for the grafana repo? At least you took the new URL for another pull but are unable to say at least thanks for the hint... wow.

**Comment by mstormi** [comment]
There's no mechanism to handle that in openHABian except on installs.
And there's no need to upgrade working Grafana so no I don't care.
Feel free to provide a PR that does better.
