### ISSUE TITLE
New Release or Nightly Builds?

### ISSUE THREAD

**Issue by felixekman** [openhab/openhabian#181]
Would it be possible to issue a new updated release since we've had some big changes in OpenHAB since the 1.3 release for both A64 and RPI. Alternatively or as an addition, nightly or more frequent builds of the ISO/img.

**Comment by ThomDietrich** [comment]
Hello @felixekman,
the openHABian image is only a base system to boot and initiate the openHABian setup process. The files needed for said process are however downloaded right in this second. All changes to openHAB and to openHABian are instantly available to new installations. You do not need to download a newer openHABian image for that.
Even if you already installed openHABian, you can benefit from additions and changes. The openHABian configuration menu can be updated to the latest version and offers many entries to apply improvements and add additional functionality.

This is actually a key feature of openHABian.
Do you see any need to clarify this in documentation?
