### ISSUE TITLE
Frontail: Update node.js to current LTS 18.x

### ISSUE THREAD

**Issue by chund** [openhab/openhabian#1810]
## Issue information:
After my Frontail installation was corrupted after a failed apt-get upgrade I tried to reinstall nodejs but it fails like this:
sudo apt-get install -y nodejs

Err:1 https://deb.nodesource.com/node_16.x bullseye/main armhf nodejs armhf 16.20.2-deb-1nodesource1
  404  Not Found [IP: 2606:4700:10::ac43:acd 443]
E: Failed to fetch https://deb.nodesource.com/node_16.x/pool/main/n/nodejs/nodejs_16.20.2-deb-1nodesource1_armhf.deb  404  Not Found [IP: 2606:4700:10::ac43:acd 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

Version 16.x is not supported and no longer available.

Would probably help to update openhabian to use Node.js 18.x 
For me it helped to bump the node.js version like this:
 curl -sL https://deb.nodesource.com/setup_16.x | sudo bash -

## System information:
Please tell us what OS you are running (Raspberry Pi OS, Debian, Ubuntu), what
HW you are running on (Raspberry Pi, amd64). Also include the output of
`cat /etc/os-release` and `uname -m`.
```
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
```

**Comment by chund** [comment]
Is PR #1787 related?
may adding that apt update to openhabian-config would be good, to keep the installations up to date.

**Comment by mstormi** [comment]
Fresh openHABian install already gives you v18

Keeping 3rd party stuff up to date isn't feasible at all times
