### ISSUE TITLE
RPi 5 support

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1818]
RPi5 is rumored to become released Oct, 23rd.
4/8 GB, 1/2 GB models to follow.

Raspi OS will be bookworm (Debian 12)
PCI-E interface (HAT to be separately released to host M.2 SSD)
New: real time clock, power button

- [x] support model detection etc in helpers.bash
- [ ] ~~support M.2 boot ?~~

Depends: #1788

**Comment by Egyras** [comment]
I have RPi5 8GB model, can help with testing if required ;)

**Comment by mstormi** [comment]
> I have RPi5 8GB model, can help with testing if required ;)

@Egyras You could figure out a is_pifive_8gb() function that return 0 on 8gb Pi5 only but 1 on Pi5 with less RAM.
See `/opt/openhabian/functions/helpers.bash` there's is_pifour() is_pifour_8gb() and is_pifive() as templates

**Comment by Egyras** [comment]
> RPi5 8GB

@mstormi how to call(execute) these functions in right way for checks ? From where you pass variable "$hw" ?

**Comment by barns-do** [comment]
@mstormi may this help you (pi5_8GB):

openhab:~ $ grep "^Revision"  /proc/cpuinfo
Revision        : d04170

openhab:~ $ grep "^Revision\\s*:\\s*[ 123][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]17[0-9a-fA-F]$" /proc/cpuinfo;echo $?
Revision        : d04170
0

openhab:~ $ totalMemory="$(awk '/MemTotal/ {print $2}' /proc/meminfo)";echo $totalMemory
8246848

**Comment by Egyras** [comment]
@barns-do  did you tried to install pre-release openHABian v1.9, for me seems wifi dont want to work (didnt tested LAN yet as kids sleeping where monitor and can plug cable).
Failed to start comitup.service - Comitup Wifi Managament.

**Comment by Egyras** [comment]
@mstormi pre-release openHABian v1.9 doesnt install with Wifi or even connected via cable.

**Comment by Egyras** [comment]
@mstormi  here is first-boot.log for RPi5 8GB connected via LAN
[first-boot.log](https://github.com/openhab/openhabian/files/13389082/first-boot.log)

**Comment by Egyras** [comment]
seem for WIFI in Raspberry Pi OS 12 'Bookworm' they dont use anymore **wpa_supplicant.conf**, instead this is used **nmcli** So this explain issues with WIFI on first boot.

**Comment by mstormi** [comment]
Try the comitup hotspot, please.

**Comment by Egyras** [comment]
> Try the comitup hotspot, please.

doesnt work, tried to connect but phone deosnt show it....

**Comment by barns-do** [comment]
@Egyras: I just installed V1.9 LAN-based. At first glance there are no problems with it. No WLAN-Testing ...

**Comment by Egyras** [comment]
made a new image via Raspberry Pi Imager and defined WIFI settings there, all went without any problems.

**Comment by mstormi** [comment]
Imager will get you an old image.

So seems RPi5 is supported but WiFi does not work yet. Continue in #1823
