### ISSUE TITLE
"illegal instruction" error with zulu openjdk on pine64 armbian

### ISSUE THREAD

**Issue by dolfandringa** [openhab/openhabian#182]
I just did a fresh install of armbian server edition and then git pulled the openhabian repos and am doing the openhabian-config on my pine64 (1Gb). I am going through the manual/fresh install parts of the menu (choosing zulu embedded instead of oracle) and everything seems to install fine. But when I execute `java -version` I get an error "Illegal instruction". 
Does anyone have an idea what could cause this?

```
~$ java -version
Illegal instruction
```
```
~$ uname -a
Linux pine64 4.11.1-sun50iw1 #14 SMP Tue Jun 13 08:03:38 CEST 2017 aarch64 aarch64 aarch64 GNU/Linux
```
```
~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```
```
~$ dpkg -l *zulu*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name               Version        Architecture   Description
+++-==================-==============-==============-==========================================
ii  zulu-embedded-8:ar 8.20.0.42      armhf          Azul Systems Zulu Embedded is a binary dis
```
```
~$ dpkg -l *jdk*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name               Version        Architecture   Description
+++-==================-==============-==============-==========================================
un  java7-jdk          <none>         <none>         (no description available)
un  java8-jdk          <none>         <none>         (no description available)
un  openjdk-6-jdk      <none>         <none>         (no description available)
un  sun-java5-jdk      <none>         <none>         (no description available)
un  sun-java6-jdk      <none>         <none>         (no description available)
```

**Comment by ThomDietrich** [comment]
Hello @dolfandringa 👋 
this might be related to the version of zulu embedded that got installed on your system. Could you purge and go through the zulu installation yourself? See: https://github.com/openhab/openhabian/blob/master/openhabian-setup.sh#L342-L352
You will realize, that the function `is_pine64` will not work as expected on your system. We should probably do something about that. Looking forward to your results.
Good luck! ;)

**Comment by dolfandringa** [comment]
Cool, will check and report back. Thanks @ThomDietrich

**Comment by dolfandringa** [comment]
It didn't solve it. I did what the setup script did (after purging all of the zulu and related pacakges), and searched the script for the is_pine64 variable to see what additional stuff was done bu the setup script. But the only thing the setupscript really does differently for the pine64 is add the armhf architecture, which as already there in the first place. So the armhf packages were already installed (this is also visible in the output on my original post). 
What I did see in dmesg after running java -version (and seeing the resulting Illegal Instruction error) is the following:

```
[ 1742.890752] force_signal_inject: 1 callbacks suppressed
[ 1742.890766] java[7200]: undefined instruction: pc=00000000f5e8c810
[ 1742.890774] Code: e1931f9f e1830f9c e3500000 1afffffb (ee070fba) 
```

I am going to try a fresh install with the oracle jdk first to see if that makes a difference.

**Comment by ThomDietrich** [comment]
Hello @dolfandringa !

> this is also visible in the output on my original post

Ah right, sorry about that.
Hmmm then I'm afraid we are out of luck. However this might be an interesting error report for zulu themselves! You should consider posting your findings to their support ticket system!

Yes please try oracle jdk and let me know how it went.

Btw: Why did you choose to go with armbian?

**Comment by dolfandringa** [comment]
It didn't solve it. I did what the setup script did (after purging all of the zulu and related pacakges), and searched the script for the is_pine64 variable to see what additional stuff was done bu the setup script. But the only thing the setupscript really does differently for the pine64 is add the armhf architecture, which as already there in the first place. So the armhf packages were already installed (this is also visible in the output on my original post). 
What I did see in dmesg after running java -version (and seeing the resulting Illegal Instruction error) is the following:

```
[ 1742.890752] force_signal_inject: 1 callbacks suppressed
[ 1742.890766] java[7200]: undefined instruction: pc=00000000f5e8c810
[ 1742.890774] Code: e1931f9f e1830f9c e3500000 1afffffb (ee070fba) 
```

I am going to try a fresh install with the oracle jdk first to see if that makes a difference.

**Comment by IOOOTAlan** [comment]
I just had a chat with Azul support about this: seems like their Zulu Embedded armhf build is built for ARMv6 and some ARMv8 CPUs (like the pine64) are not 100% backward compatible to the ARMv6 instruction set, hence the illegal instruction error.
They then told me that this _might_ get fixed in a future public release, but there's no ETA at the moment.

**Comment by EliasGabrielsson** [comment]
Closing this as it looks like a upstream problem.
