### ISSUE TITLE
box crash on JDK17 install

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1822]
Installing the openjdk17-jre-headless package reproducibly(!) crashes my RPi3 test box, leading to successive errors.

No idea for now why.

@BClark09 can you help with testing this out ? I'm at a loss.
Use latest image from
https://github.com/openhab/openhabian/actions/workflows/build-action.yml
as earlier ones don't start the oh installation process because of bookworm changes.

Maybe you could try if this happens with vanilla Raspi OS ?

**Comment by BClark09** [comment]
Yes, no problem. Are you able to grab which exact version of the package it's trying to install?

**Comment by mstormi** [comment]
Latest: openjdk-17-jre-headless 17.0.8+7-1~deb12u1

Keeps crashing my box every time as soon as it starts unpacking. But hardware is fine, no other problems. Even changed SD card.
Tried with 32 and 64bit Raspi OS, no difference.

**Comment by BClark09** [comment]
Okay, I'm also using `17.0.8+7-1~deb12u1` but on a vanilla Debian Bookworm image for the Raspberry Pi 4.

I'll try with the openHABian image when I can, and then will try with a Raspberry Pi 3.

**Comment by mstormi** [comment]
Tried with another RPi3 and a RPi4 - same problem.

Used the 64bit image off here https://github.com/openhab/openhabian/actions/runs/6704022156

**Comment by mstormi** [comment]
any findings?

**Comment by mstormi** [comment]
Works with latest changes although I'm not sure what it was that made it work.
Exchanged power supply, had reproducible image crahes before now same image is fine.
