### ISSUE TITLE
Check latest version of openhabian

### ISSUE THREAD

**Issue by skatun** [openhab/openhabian#183]
Maybe something that should not be to hard to program in is to check when you run openhabian -config, first it checks your version against latest version on the web, then prompt you if you want to upgrade or read the release note if it versions does not match up..

**Comment by ThomDietrich** [comment]
Hey @skatun 👋 😃 
Some parts of this should be easy, others might be a bit tricky. A good feature request! Thanks 😉

**Comment by ThomDietrich** [comment]
Happy to report: https://github.com/openhab/openhabian/pull/261
