### ISSUE TITLE
how to uninstall openhabian completely?

### ISSUE THREAD

**Issue by utap2001** [openhab/openhabian#1844]
Dear author: 
I recently install openhabian in my Ubuntu 20.04, and my previous openhab version is 3.1. 
But after I install the openhabian script, the ubuntu login information became this: 

(base) xx_user@openhabian:~$ 
instead of (base) xx_user@local_ip: ~$

Now I have two login ID and different ip address, therefore I want to remove the openhabian script and manually upgrade my openhab version. But the script had no choice to uninstall the files and setting . 

I want to ask how to completely uninstall the openhabian script and returned to my previous system setting ? 
Thanks !

-----------------------

## Debug information:
Please provide all of the output provided by utilizing the `debugmode=maximum`
parameter in the `/etc/openhabian.conf` file. For more information on how to
accomplish this, please see [openhabian-DEBUG.md](https://github.com/openhab/openhabian/blob/main/docs/openhabian-DEBUG.md#create-a-debug-log).
```
place logs here
```

## System information:
Please tell us what OS you are running (Raspberry Pi OS, Debian, Ubuntu), what
HW you are running on (Raspberry Pi, amd64). Also include the output of
`cat /etc/os-release` and `uname -m`.
```
x86_64

NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

```

**Comment by mstormi** [comment]
There's no uninstall instructions. Use a different UNIX user or edit it's dotfiles.
Sorry but this is the wrong place to ask for user help.
