### ISSUE TITLE
Discussion: Documentation instructions 32/64 bit

### ISSUE THREAD

**Issue by masipila** [openhab/openhabian#1845]
## Issue information:
The current openHABian installation instructions have two sections that talk about 32 vs 64 bit images.

* _RPi 3 and 4 have a 64 bit processor and you may want to run openHAB in 64 bit. Be aware that running in 64 bit has no relevant advantages but a major drawback: increased memory usage. That is not a good idea on a heavily memory constrained platform like a RPi. On x86 hardware, 64 bit is the standard._
* _Write the image to your SD card using the official [Raspberry Pi Imager](https://www.raspberrypi.org/software/)[ (opens new window)](https://www.raspberrypi.org/software/). openHABian can be selected via 'Other specific purpose OS / Home assistants and home automation'. Choose the 32bit version, it's more efficient !_

I recently updated from openHAB 3.3 to 4.1 and noticed that some of my Javascript rules were extremely slow, also after the first run (i.e. the caches were warm). "Extremely slow" here means tens of seconds on OH4.1, where they were running in a matter of couple of seconds on OH3.

I found this:
https://github.com/openhab/openhab-addons/issues/15600

And based on the comments over there decided to try a fresh openHAB 4.1 install using a 64-bit image. The performance of the Javascript rules was now on the same level as they were on openHAB 3.

## System information:
Raspberry Pi 4, 4 GB of memory

## Documentation considerations
I don't know much (if any) about the GraalVM/GraalJS things, but it seems that I'm not the only one that was taking a huge performance hit when using 32-bit openHABian image. But based on these observations, I feel that the current openHABian installation instructions are outdated and this 32/64 bit consideration is not as straight forward ("just use 32 bit version, it's more efficient") as the current doc phrasing implies.

I'm not suggesting to change it to anything like "always use 64 bit version, it's better", but to elaborate more on what pros / cons these have.

Thoughts and comments from other community members?

Cheers,
Markus

**Comment by egoist6** [comment]
see here:
[https://github.com/openhab/openhab-addons/issues/15600?notification_referrer_id=NT_kwDOBJVyg7M3NzI5MjM4Mzk3Ojc2OTAzMDQz#issuecomment-1949540917]

**Comment by mstormi** [comment]
I've updated the openHABian docs on that part.
