### ISSUE TITLE
Release 1.8c not respecting "clonebranch=openHAB3" setting

### ISSUE THREAD

**Issue by michikrug** [openhab/openhabian#1846]
## Issue information:
Yesterday, I tried to upgrade my PI to the lastest openhabian image to update my OH3 setup to OH4.
As advised in the forum (https://community.openhab.org/t/openhab-4-migration-faq/148144), I first went for a OH3 setup based on the new image.
So I flashed release 1.8c to a brand new SD card and set both the "clonebranch=openHAB3" and also the "initialconfig" option.
After openhabian finished its setup, I was presented with a fresh OH4.1.1 installation with nothing restored.
When looking in the "openhabian.conf" file after setup, it was like default, without my changes.
I even tried it twice. Also openhabian was running on main branch.

After that, I flashed the 1.8 release and with that everything worked as expected.
openhabian was using openHAB3 branch, OH3 was installed and my zip was restored.

Are the instructions outdated? Has there been some change in 1.8c that breaks that option but has not been outlined?

## Debug information:
Not kept the logs, but can try again if required, as it seems reproducible.

## System information:
RaspberryPi 3B, fresh SD card flashed with release 1.8c 64bit image

**Comment by mstormi** [comment]
Please try again with 1.9

**Comment by michikrug** [comment]
> Please try again with 1.9

Thanks, currently trying... will report back

**Comment by michikrug** [comment]
Worked as expected.
I would say we can close this issue with the reference to use the new 1.9 release.

Btw. would there be any reason to start again with my setup with the 1.9 version, if I just did so with 1.8?

**Comment by mstormi** [comment]
Thanks.
1.9 is bookworm based, 1.8 is still the older Linux distro and you cannot (safely) upgrade that. So if I were you I'd go with 1.9 now.
