### ISSUE TITLE
MIFLORA

### ISSUE THREAD

**Issue by skatun** [openhab/openhabian#185]
Add implementation for Miflora,

I suggest not to go down the MQTT way, or leave it as optional. Since openhabian is running on rpi which in many cases has built in bluetooth, there is no need to send it to a broker, which requires cpu time and might go down instead of just sending it directly to openhab with json parsing.

**Comment by kubawolanin** [comment]
Hey @skatun I think it's a wrong repository for that kind of request. Check out [openhab2-addons](https://github.com/openhab/openhab2-addons/issues)

Also, did you see [this tutorial](https://community.openhab.org/t/xiaomi-miflora-sensor-integration/17453)?
There are a few people that attempted to do a binding for MiFlora (@hakan42 and @dimalo I think).

**Comment by ThomDietrich** [comment]
Hey @skatun, thanks for opening the issue. You should have also linked the related discussion: https://community.openhab.org/t/xiaomi-miflora-sensor-integration/17453/5

@kubawolanin: Kim and I were already talking about integrating the Miflora setup as an optional component in openHABian. However I'm not sure about that as the tutorials depend on your system and home and you'll need to follow the tutorials.

The Miflora integration would indeed be a great Binding idea and if any of @hakan42 or @dimalo are working on one, that would be amazing.

**Comment by hakan42** [comment]
I actually started working on a binding and use it to good effect in at least three OH2 installations.

I would like to start with the mqtt way as BLE support is still not in the main tree. I'll document what I have on the community forum.

**Comment by ThomDietrich** [comment]
Hey guys, today I finally took the time to set up some Mifloras.

A few notes:

* Update pip: `sudo apt remove python-pip && sudo easy_install pip`
* `sudo pip install paho-mqtt`
* Gattlib:
  * `sudo apt install libbluetooth-dev libboost-python-dev libglib2.0-dev`
  * `sudo vim /etc/dphys-swapfile` -> set `CONF_SWAPSIZE=500`
  * `sudo /etc/init.d/dphys-swapfile restart`
  * `sudo pip install gattlib`
  * Reset CONF_SWPASIZE

Next you can use one of the many available scripts:

* https://github.com/marcelrv/miflora
* https://github.com/open-homeautomation/miflora
* https://community.openhab.org/t/xiaomi-miflora-sensor-integration/17453/1
* https://community.openhab.org/t/xiaomi-miflora-sensor-integration/17453/5

**Comment by ThomDietrich** [comment]
@skatun in case you are interested:

I installed a few sensors this weekend and had a go at the different solutions out there. As none of them really fit my needs I pretty much build my own (based on one here on GitHub). Here you go: https://github.com/ThomDietrich/miflora-mqtt-daemon - It **does** depend on MQTT. I found it to be the perfect interface option for all kinds of devices with openHAB. It's really a shame we do not yet have the ESH MQTT binding...

Anyhow. Feel free to test and I'll be looking into an automated python+gattlib installation soon! :wink:

**Comment by hakan42** [comment]
@ThomDietrich , I just started a PR, but please don't shame me when you discover that the binding is mainly a set of thing configuration with little "real" code in it 😊 

Just waiting for BLE to land, honest 😄

**Comment by hakan42** [comment]
> It does depend on MQTT. I found it to be the perfect interface option for all kinds of devices with openHAB. It's really a shame we do not yet have the new ESH MQTT binding...

Actually, this is not such a bad thing. my OH2 is running on a PI3 with BLE on board, true, but the plants are in two different rooms and the PI is in the cellar. No chance for BLE to reach from the PI to the plants...

Currently, I am working on a ESP32-based BLE to MQTT bridge specifically for the MiFlora sensors.

**Comment by ThomDietrich** [comment]
@hakan42 that's great! I'm not sure when I'll have the time to check it out but I'll subscribe and comment.
I also do agree, that the MQTT approach is especially useful for distributed systems.

Still @skatun, to answer your request: I've added an mqtt-less mode: https://github.com/ThomDietrich/miflora-mqtt-daemon/commit/fc3c2b8b68ddf13b293d041d0c3cb02b228b8a68 - For now it just writes the whole set of retrieved data to stdout as a json string. Let me know if that's useful for you.

**Comment by skatun** [comment]
@ThomDietrich  ur link ThomDietrich/miflora-mqtt-daemon@fc3c2b8 seems to be broken.. Can you fix it?

**Comment by ThomDietrich** [comment]
@skatun check the project main page
https://github.com/ThomDietrich/miflora-mqtt-daemon/
The Readme should contain everything you need to know and do to get you starting. Looking forward to your feedback!

**Comment by ThomDietrich** [comment]
Settled with #238
