### ISSUE TITLE
Frontail fails to install

### ISSUE THREAD

**Issue by Skinah** [openhab/openhabian#1852]
Just a heads up that Frontail would not install for me on a PI3 with the latest image from raspberry pi imager program.

I used my own script and it was working after that so did not fault find. Your using node 18 and the latest is now node20. Since this is tested on the openhabian image, feel free to grab what you need...

```
wget www.pcmus.com/openhab/scripts/install-frontail.sh
sudo bash ./install-frontail.sh
```

A user also posted they had issues here on the forum so figured it should get posted on here it needs further testing...

https://community.openhab.org/t/unable-to-install-frontail-on-fresh-install-oh-4/153751

**Comment by mstormi** [comment]
I read both of those threads myself but frankly what do you expect me to do by opening this issue ?
Sit down myself and fiddle things out of logfiles you didn't provide then get back to you for *you* to test on *your* platform ?
I'm not your support guy, just the maintainer than will assemble what contributors will need to send in.
Frontail is an awfully complex and dependent combo of OS packages and config I did not develop myself and the original program isn't maintained any more so my willingness to invest more time is low to none, I'd rather drop support.
OHian is an OSS project, so please provide the analysis yourself and preferrably the fix, too, if you want to keep using frontail.

FWIW, 1.9 is about to be released. Frontail works there. Try with that image.

**Comment by Skinah** [comment]
If it works in 1.9 then great, thanks for already having fixed it. Sorry to bother you, wont bother making a report in the future.
