### ISSUE TITLE
Homegear on bookworm

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1853]
Homegear so far fails to install on latest bookworm based OHian.
https://github.com/openhab/openhabian/actions/runs/8224683972/job/22488806804

bookworm repo at
https://apt.homegear.eu/raspberry_pi_os/bookworm/homegear/stable/dists/bookworm/

BUT IT IS EMPTY

Comments on the homegear forum indicate it's possibly a dying project so nothing we can do about it for now.

**Comment by clown522** [comment]
It is not empty anymore ;-)

**Comment by mstormi** [comment]
But there's only armhf binaries. How would it work to install those on 64 bit OS (arm64 arch) ?

**Comment by miloit** [comment]
Some news here?

**Comment by SteWers** [comment]
Good news!

Homegear on bookworm is now available. The installation worked without any issue. Also the function of homegear looks good to me.
Many thanks to @hfedcba! 👍

**Comment by SteWers** [comment]
I'm also on a RasPi 3:
```
root@raspberrypi:/home/pi# cat /sys/firmware/devicetree/base/model
Raspberry Pi 3 Model B Plus Rev 1.3r
```
but not with a 64 bit system:
```
root@raspberrypi:/home/pi# dpkg --print-architecture
armhf
```
My sources.list.d:
```
deb https://apt.homegear.eu/raspberry_pi_os/bookworm/homegear/testing/ bookworm main
```

As I need `homegear` and `homegear-max`, I only installed that two to packages. To verify the installation of same packages as you, I did:
```
apt install homegear homegear-homematicbidcos homegear-homematicwired homegear-max homegear-management
```
The result was, that all packages were installed correctly.

On the [download page for homegear](https://homegear.eu/downloads.html?version=0.8-testing&system=raspbian_bullseye), the script mentions, that you have to use another source for 64 bit systems (here modified for bookworm):
```
deb https://apt.homegear.eu/debian/bookworm/homegear/testing/ bookworm main
```
Maybe this solves the problem on 64 bit systems.

**Comment by mstormi** [comment]
I've now used the right repo based on 32 or 64, our standard test build process doesn't proceed (it's a virtual 64 bit rpi64), there's now dependencies lacking:

https://github.com/openhab/openhabian/actions/runs/11174601805/job/31064537122#step:8:168

**Comment by SteWers** [comment]
You got it to run! 👍😊

There is something else, I found out:
The repository `https://apt.homegear.eu/debian/bookworm/homegear/testing/` now contains the files for `armhf`, `arm64` and `amd64`. So this repository can be used for all three processor architectures. Makes it a bit simpler.
