### ISSUE TITLE
OH4 webserver problem

### ISSUE THREAD

**Issue by Gringohekus** [openhab/openhabian#1863]
## Issue information:
1. on a fresh installation openhab webserver does not start. 
2. if I want to set up OH4 in openhabian-config I got the following error: There was an error or interruption during the execution of: "30 | System Settings"
3. when I start the SSH on the welcome tesxt i see this error: "sed: can't read /var/lib/openhab/etc/version.properties: No such file or directory" see the attached printscreen
![error](https://github.com/openhab/openhabian/assets/49864253/b7b45fe4-ed0f-4401-9309-e10c803ecdb9)

I had the similar issue before but as I remember after 02 and/or 03 of openhabian-config I could solve it and the system had been  running for months. Than suddenly the web UI disappeared. I was also not able to connect using Samba to save a backup and couple of days later the system crashed. It seemd any network error as I was not able to ping its IP address and it did not connect neither on WIFI nor ethernet. Than I tried to reinstall the entire OH4 using a new SD card. 

## Debug information:
[first-boot.txt](https://github.com/openhab/openhabian/files/14898703/first-boot.txt)
[openhabian.txt](https://github.com/openhab/openhabian/files/14898704/openhabian.txt)

Before installation I changed the hostname to rpi
During installation I did not get any error.
If I check /opt/openhabian-install-successfull looks OK
After installation I restarted the rPi using SSH.
Than I changed the config file with ipv6=disable and restarted again but it did not helped

## System information:
OS: Raspberry Pi OS at Rpi 3B
HW: you are running on (Raspberry Pi, amd64).
Connection: Ethernet
'uname -m' returns with armv7l
[os-release.txt](https://github.com/openhab/openhabian/files/14898717/os-release.txt)
I have run another OH4 instance on the same network on a Rpi4 

Thanks for your kind support
/

**Comment by mstormi** [comment]
Github an this are not for your personal support, please turn to the forum.

PS see line 3158 of log, something's bad probably with your SD card. Re-install from the beginning.
