### ISSUE TITLE
Bookworm ready python install in venv

### ISSUE THREAD

**Issue by thicknesss** [openhab/openhabian#1867]
Hi all,
because bookworm enforeces virtual enviroments for python we need to make some changes in below snippet:

https://github.com/openhab/openhabian/blob/9d6fbd6ecc8a5a042ad6af61392a31053a6307c3/functions/packages.bash#L444-L445

The venv must be prepared:
python -m venv --system-site-packages env
and activated
source env/bin/activate
before PIP is used to install the requirements.
for the package a [pr](https://github.com/ThomDietrich/miflora-mqtt-daemon/pull/177) is made to update the template.service

Brgds André

**Comment by mstormi** [comment]
Fixed-By: #1869
