### ISSUE TITLE
install zigbee2mqtt with ethernet coordinator

### ISSUE THREAD

**Issue by moodyblue** [openhab/openhabian#1868]
## Issue information:
I have a zigbee internet coordinator, more specifically the SLZB-06. When trying to install zigbee2mqtt using openhabian menu it is not possible to specify the IP address of the coordinator and the installation is not done.

## System information:
Raspberry Pi 4B-2G
openhabian 64-bit

Output of
`cat /etc/os-release` and `uname -m`.
```
openhabian@openhabian:~ $ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
openhabian@openhabian:~ $ uname -m
aarch64
```

**Comment by mstormi** [comment]
@Larsen-Locke please decide if you want to add this as a feature

**Comment by Larsen-Locke** [comment]
Currently not. I didn't have that hardware and till now there was only one user asking for it.

**Comment by mstormi** [comment]
@moodyblue sorry

**Comment by moodyblue** [comment]
I understand. What if I develop this myself ?

**Comment by mstormi** [comment]
Please do. I'd be happy to merge a PR if you put up one.

**Comment by moodyblue** [comment]
Where is `zigbee2mqtt_setup` ? This is one of the files that need be changed.

The change is simple, in your skeleton `configuration.yaml` includes these lines:
```
serial:
  port: "/dev/serial/%adapter"
```

In my production case these lines are:
```
serial:
  port: tcp://192.168.129.41:6638
```
(the ip address is installation specific, the port is device specific, for example the slzb-06 uses port 6638, but I have another coordinator that uses port 1053)

**Comment by moodyblue** [comment]
PR submitted, hope that it is ok.
