### ISSUE TITLE
Startup loop

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1870]
At times, after updating the  openHAB package, startup is stuck in a loop, spitting lots of java component errors.
I came to think if we can supervise startup, detect and break these loops ?
Unsure how, though.

Maybe if detected, `pkill -9 java` maybe add that to the update script option ? 
Add `openhab-cli clean-cache`, too ? (I think it's done on package install so may not help to do again but not 100% sure)
Or add a systemd timer to do a regular health check maybe ? Note that can be a dangerous sword should it mistakenly detect OH to be down. It should only be active for say some hours after openhab service startup time.

**Comment by BClark09** [comment]
I've not had this myself, but I have seen many talk about this issue. Is the openHAB process restarting (i.e. Karaf) or is the loop happening within openHAB's functions. If the former, then we can do a lot if an exit code is issued.

> Add `openhab-cli clean-cache`, too ? (I think it's done on package install so may not help to do again but not 100% sure)

[It is done on package install or on update.](https://github.com/openhab/openhab-linuxpkg/blob/10061acd36524afb12a033fea6dcf142b399bf56/resources/control-runtime/preinst#L84).

> Or add a systemd timer to do a regular health check maybe ?

There are things we can test by polling the activeness of core bundles: https://github.com/openhab/openhab-linuxpkg/issues/138

> I came to think if we can supervise startup, detect and break these loops ?

I've been wondering if it's related to the amount of time that openHAB takes to shut down or restart. If it takes more than 120 seconds, then the openHAB service is killed with a `SIGTERM`, and I wonder if this has any effect on the quality of the update.

**Comment by ecdye** [comment]
So are we just trying to add a temporary fix on the openHABian side until the underlying bug can be corrected with openHAB and its Java process?

**Comment by mstormi** [comment]
yeah, although AFAIK there's no such bug filed with openHAB

**Comment by miloit** [comment]
I have never seen this, but if you have @mstormi than file an issue so that they girls and boys aware if it

**Comment by mstormi** [comment]
> I've been wondering if it's related to the amount of time that openHAB takes to shut down or restart. [If it takes more than 120 seconds](https://github.com/openhab/openhab-linuxpkg/blob/10061acd36524afb12a033fea6dcf142b399bf56/resources/systemd/openhab.service#L27C1-L27C15), then the openHAB service is killed with a `SIGTERM`, and I wonder if this has any effect on the quality of the update.

As said the issue here is Java exceptions so from systemd perspective the service (= java process) *is* running and I don't think it's related to your 120 secs timeout.

**Comment by mstormi** [comment]
openhab.log for such an occurrence (haven't analyzed it)

[continuous-restart.log](https://github.com/user-attachments/files/16569310/continuous-restart.log)
