### ISSUE TITLE
[Proposal] Integrate Yeoman openHAB generator

### ISSUE THREAD

**Issue by kubawolanin** [openhab/openhabian#188]
This suggestion is a shameless plug of mine :smile: 

Since we have a Node.js in place, we could integrate my [Yeoman openHAB generator](https://community.openhab.org/t/openhab-generator-design-your-smart-home-in-no-time/32250) into openHABian. It'll allow the newcomers to start off easily.

Here's the repository:
https://github.com/kubawolanin/generator-openhab

@ThomDietrich thoughts?

**Comment by ThomDietrich** [comment]
> This suggestion is a shameless plug of mine :smile:

:astonished: how could you!? :smile: Sure thing. Looks pretty neat!

Looking at the result of your generator I think we should seriously consider defining an openHAB style guide for names and config files. I've already mentioned that over in the vscode repo. Your generator result looks quite similar to how I'd organize my items but the mixture with groups and the intention is quite strange to me (this is an example and not bad). On the other side [I am a big fan of table style indention](https://github.com/ThomDietrich/openhab-config/blob/master/items/homematic-heizung.items) and would love to see a vscode beautify extension with it one day.

**Comment by kubawolanin** [comment]
I've been following the following format:

* `[Room]_[Device]` if a house has just one floor
* `[GF|FF|F2|F3...]_[Room]_[Device]` for multi-floor house ;-)

> On the other side I am a big fan of table style indention and would love to see a vscode beautify extension with it one day.

Hey, just check out [Alignment](https://marketplace.visualstudio.com/items?itemName=annsk.alignment) plugin to VSCode.
By simply selecting your text block and hitting `Alt + -` it transforms this:
```
Group Bedroom "Bedroom" <bedroom> (Home)
    Switch Bedroom_Light "Light" <light> (Bedroom, Lights) { channel="" }
    Contact Bedroom_Window "Window" <window> (Bedroom, Windows) { channel="" }
    Contact Bedroom_Door "Door" <door> (Bedroom, Doors) { channel="" }
    Rollershutter Bedroom_Shutter "Shutter" <rollershutter> (Bedroom, Shutters) { channel="" }
```

To this:
```
Group Bedroom       "Bedroom"       <bedroom> (Home)
      Switch        Bedroom_Light   "Light"   <light>         (Bedroom, Lights)   { channel="" }
      Contact       Bedroom_Window  "Window"  <window>        (Bedroom, Windows)  { channel="" }
      Contact       Bedroom_Door    "Door"    <door>          (Bedroom, Doors)    { channel="" }
      Rollershutter Bedroom_Shutter "Shutter" <rollershutter> (Bedroom, Shutters) { channel="" }
```

:wink:

**Comment by ThomDietrich** [comment]
Nice!!

The `[Room]_[Device]` format is how I go at it as well. Still there are details to specify. Like in this example: I have a groups for my "GF" which is highlighted differently in all kinds of editors, because the editor thinks it's a constant...

Back to the topic: You want me to work out the PR or are you going to build something?

**Comment by kubawolanin** [comment]
> We should define a formal style guide recommendation in docs I believe. Wdyt?

Absolutely! I think I saw something on OH1.x wiki a while ago. Or maybe it was community/google groups thread? :thinking: 

> Back to the topic: You want me to work out the PR or are you going to build something?

I'll make a PR later this week! :+1:

**Comment by ThomDietrich** [comment]
I believe there was a posting by Rich once. However he's using the hungarian notation and well... no :smile_cat:

**Comment by kubawolanin** [comment]
Quick question regarding integration with openHABian - would you rather see it as an optional component (next to the Log Viewer, NodeRED etc) or rather something pre-installed for all users with nodejs, just like `frontail`?

```
  if is_pione || is_pizero || is_pizerow; then true; else nodejs && frontail; fi
```

**Comment by ThomDietrich** [comment]
Hmmm...
I'd say it qualifies as an optional component for most users.
However especially the new user might want to execute it right away without having to first going into some menu.

Ah you know what, add it as a pre-installed component. You could also add an alias while you are at it. :+1:
