### ISSUE TITLE
Not possible to do a fresh install a

### ISSUE THREAD

**Issue by joe197319** [openhab/openhabian#1882]
## Issue information:
I am using an Raspberry Pi 3B with Raspbian GNU/Linux 10 (buster) and openHAB 3.4.4 (Java11).
I want to upgrade to openhab 4.x (Java17).
First I did install a fresh installation of Debian 12.5 (bookworm) on a VM (Proxmox) for easier testing. Then I tried to install openHAB 3.4.4 (or 3.4.5) by using openhabian (like described at [https://community.openhab.org/t/openhabian-howto-install-openhab3-with-current-openhabian-image/148043].
But how can I install the openHAB version 3.4.4 (with Java 11) to restore my backup and upgrade to 4.x then?
Unfortunately I did not suceed!

With the openhabian-config tool I can:

- switch the branch (release, latest, legacy)
- install the latest openHAB (4.x)
- install manually the Java version (11 or 17 for example)

I did check the openhabian-conf file, there I can change the java-version and the branch also.
But how can I install the openHAB version 3.4.4 or 3.4.5 (with Java 11) to restore my backup?

I found this on openHAB documentation:

> openHABian will install openHAB 4 and Java 17 by default. The openHABian image will install openHAB 4 by default, to have it install openHAB 3 right from the beginning, set clonebranch=openHAB3 in openhabian.conf before first boot. Use clonebranch=legacy to get openHAB 2.

I tried this, but it results in an 4.x installation also.

Thank you very much for your commitment and your time!

## Debug information:
Please provide all of the output provided by utilizing the `debugmode=maximum`
parameter in the `/etc/openhabian.conf` file. For more information on how to
accomplish this, please see [openhabian-DEBUG.md](https://github.com/openhab/openhabian/blob/main/docs/openhabian-DEBUG.md#create-a-debug-log).
```
place logs here
```

## System information:
**Live system:**
Raspberry Pi 3B with Raspbian GNU/Linux 10 (buster) and openHAB 3.4.4 (Java11).
```
openhabian@openhabian:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
openhabian@openhabian:~ $                            

openhabian@openhabian:~ $ uname -m
armv7l
openhabian@openhabian:~ $
```

**New System:**
```
root@openHab:/home/joe# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@openHab:/home/joe# 

root@openHab:/home/joe# uname -m
x86_64
root@openHab:/home/joe# 
```

**Comment by ecdye** [comment]
I'm sorry, please provide more details on the issue, or we will be unable to assist you. Follow the directions given in the post template to explain the problem and we should be able to assist.

**Comment by joe197319** [comment]
Sorry, I did update the information.
The goal is to update from openHAB 3.4.4 to 4.x.

**Comment by ecdye** [comment]
I may be misunderstanding but if your goal is ultimately to migrate to OH4 you should be able to simply start with a new install on OH4 and import your backup then.

**Comment by joe197319** [comment]
Ah, ok!
You mean, I can do a backup from my installation version 3.4.4 and import this in the new OH version 4.x?
I thought I can import only the same version of OH:
I will try this!

**Comment by mstormi** [comment]
No you cannot import OH3 config into OH4.
Install a fresh openHABian system with OH3 (use `clonebranch=openHAB3`, see FAQ link), import your old OH3 config, and finally use the `openhabian-config` menu to upgrade that box to OH4.
See https://community.openhab.org/t/openhab-4-migration-faq/148144

Please note that this (github) is not the right medium for user support.
Just post on the community forum if you still have issues.
