### ISSUE TITLE
hotspot not starting

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1901]
Reported on RPi5

reproduced with 64bit 1.9.1 on rpi3 without network or openhabian.conf modifications
(I've just fired up a headless pi and did not see any hotspot)

-> need to figure out of first-boot.log why comitup does not start and/or fires up no wi-fi
(I don't have access to the needed lab equipment for now so @ecdye please could you have a look? thanks)

There was a another Raspi OS release July, 4th i.e. between 1.9.0 and 1.9.1 that may or may not have caused this
tried 1.9 but no hotspot either

**Comment by ecdye** [comment]
Yeah, I'll build a new release now, and try and test today

**Comment by mstormi** [comment]
Using console to debug, seems comitup startup fails with some python error.
The pkg version that is installed (cached on image build?)  is 1.38-2~deb12u1

Will try to manually get that to work but I'd believe we need a comitup package with a fix to work with latest Raspi OS/python/whatever

**Comment by mstormi** [comment]
Part of the comitup install process is to get the repo information as
`wget https://davesteele.github.io/comitup/latest/davesteele-comitup-apt-source_latest.deb`
That URL fails as of now.
I think we should statically add a repo file as a fallback to contain
`deb http://davesteele.github.io/comitup/repo comitup main`

**Comment by mstormi** [comment]
Added static repo as fallback 
it now should install latest comitup, 1.42

That one however still fails to start, giving the same error.

Opened an issue https://github.com/davesteele/comitup/issues/253

**Comment by mstormi** [comment]
comitup author responded we need a more up-to-date version of the python3-networkmanager package.
That's not available in the general python repos but in comitup's.

We're already installing the latest package version (in the same go that we install comitup) so whenever the comitup repo is correctly setup, it should do.
That however was not the case in our latest image. My quick fix hopefully fixed that.
Please test.

**Comment by mstormi** [comment]
Fixed the repo config download URL

Fixed-By: https://github.com/openhab/openhabian/commit/16b97e05be5d9d0b3eeb1bd25c31a20c8d4acb0f
