### ISSUE TITLE
Ensuring network connectivity FAILED - fix for issue 1771 seems to be reverted

### ISSUE THREAD

**Issue by ballle98** [openhab/openhabian#1903]
https://github.com/openhab/openhabian/blob/9c23182ee8dd7dac0e47dbc5a4ecdb3bee8d9fcb/build-image/first-boot.bash#L161

On my network 8.8.8.8 is blocked and the curl line is failing because it should use "https:" instead of "http:"

Looks like this was fixed with #1771 but that fix is not longer in first-boot.sh

**Comment by mstormi** [comment]
That is not a bug. openHABian is not designed to work in restricted environments. You should be unblocking yours.

**Comment by mstormi** [comment]
I've re-applied the #1771 fix 
see if that helps
main branch only

**Comment by ballle98** [comment]
@mstormi thanks that was what I was asking for.  Just for reference the other issue this was related to was #192 which is the issue I was having.
