### ISSUE TITLE
Wrong platform identification

### ISSUE THREAD

**Issue by miloit** [openhab/openhabian#1916]
If I connect via ssh to my raspberry I found this in the ssh header

`platform = BCM43455 37.4MHz Raspberry Pi 3+-0190`

But I am using a raspberry pi 4.

**Comment by mstormi** [comment]
so what ? what do you want to tell openHABian developers ?
SSH is not part of openHABian but of Raspi OS.
Neither are tools like firemotd that creates the login banner (I guess that's what you refer to by "ssh header").
