### ISSUE TITLE
Wrong identification of platform 

### ISSUE THREAD

**Issue by miloit** [openhab/openhabian#1917]
If you connect to openhabian via ssh the welcome message is displayed with the wrong platform information.

`release = Debian GNU/Linux 12 (bookworm)
##  Platform = BCM43455 37.4MHz Raspberry Pi 3+-0190`

But I am using a raspberry pi 4. 

So the welcome message should be identify the platform correctly.

**Comment by ecdye** [comment]
I'm sorry but that is not an openhabian issue. It is pulling from the system values as delivered by the Linux kernel. Please stop opening issues (#1916)
