### ISSUE TITLE
IPv6 Route Advertisements Not Accepted

### ISSUE THREAD

**Issue by msw1970** [openhab/openhabian#1919]
## Issue information:
A Matter binding is under development/testing, written by digitaldan, which can integrate Matter Thread based devices using an external Thread Border Router into openHAB. However, by default an openhabian build does not allow for the IPv6 route advertisments to be accepted which stops the binding discovery process from working when the openHAB server is connected wired and the Thread Border Router is connected wirelessly.

## Debug information:
The following parameters need to be added to /etc/sysctl.conf to allow IPv6 Route Advertisments
```shell
net.ipv6.conf.eth0.accept_ra_rt_info_max_plen = 64
net.ipv6.conf.eth0.accept_ra = 1
``` 
Where eth0 is the relevant ethernet interface name that is being used.

## System information:
OS: Raspberry Pi OS
HW: Raspberry Pi 3 Model B you are running on (Raspberry Pi, amd64). Also include the output of
`cat /etc/os-release` and `uname -m`.
```
openhabian@WGB01DEV1002:~ $ cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
openhabian@WGB01DEV1002:~ $ uname -m
armv7l
```

**Comment by ecdye** [comment]
This seems like a reasonable thing to add support for in openHABian as it's a dependency for a major advertised feature in the upcoming openHAB release. @mstormi what do you think about adding this to openHABian?

I can probably look into adding it if you agree.

**Comment by msw1970** [comment]
Further update... If using DHCP to assign an IP address to the Raspberry Pi then the /etc/dhcpcd.conf also needs to be updated to append

```
noipv6
noipv6rs
``` 
Otherwise dhcpcd will always override the accept_ra option everytime the interface is restarted and the accept_ra configuration will be lost

**Comment by mstormi** [comment]
> @mstormi what do you think

okay for me but you need to ensure it's compatible with Raspi OS and potential package upgrades.

**Comment by ecdye** [comment]
@msw1970 Can you confirm that the changes in #1922 fix route advertisements on a fresh install?
