### ISSUE TITLE
Improve initial online check in first-boot script

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhabian#192]
Related to: https://github.com/openhab/openhabian/blob/master/build-rpi-raspbian/first-boot.sh#L52
and https://github.com/openhab/openhabian/blob/master/build-pine64-image/first-boot.sh#L52

Discussed in: https://community.openhab.org/t/openhabian-on-raspberrypi2modelb-gets-ip-but-error-no-network/31478

Problem: The google DNS server is blocked by some ISPs.

Solutions:
* Ping a different IP like [4.2.2.2](https://www.tummy.com/articles/famous-dns-server/)
* Do an HTTP request instead: https://superuser.com/a/769248

**Comment by BClark09** [comment]
If an ISP is blocking 8.8.8.8 then it is [likely](https://www.quora.com/My-isp-block-Google-and-Opendns-dns-what-should-I-do-How-to-keep-using-Google-dns) that that they'll block 4.2.2.2 sooner or later. A HTTP request might be the best way forward.

**Comment by AngelosF** [comment]
If an ISP is blocking ICMP and DNS queries to external name servers... they should be losing customers because they are not providing a proper service.
I don't think that you patch openHABian because 1 ISP is doing a bad job.

**Comment by ThomDietrich** [comment]
Hey guys!
I've enhanced the function to test for either ping OR an http request. That should solve the issue once and for all.
