### ISSUE TITLE
Tooling: openHABian to support necessary RRD conversions on RPI

### ISSUE THREAD

**Issue by holgerfriedrich** [openhab/openhabian#1925]
This issue is related to OH5 preparations. A lot of users will need to migrate their setup to 64-bit.

**RRD database format is dependent on the platform, i.e. during migration from 32-bit to 64-bit system those databases need special treatment.**
It seems that an xml export / import is necassary.

See for example https://blog.remibergsma.com/2012/04/30/rrdtool-moving-data-between-32bit-and-64bit-architectures/

As this is the default database format, we need to support users during migration. There is an issue about documenting the necessary steps, openhab/openhab-docs#2395.
**This issue is about a tool support to ease migration of RRD databases.**

**Comment by holgerfriedrich** [comment]
Maybe we should think of an easy-to-use approach, e.g. a full backup of the system including the OH json db, and also including RRD and possibly Influx databases. It should be possible to backup the 32-bit system and import on the 64-bit system.

Influx is also a todo on the OH5 planning, not sure about 1.8 and 2.0 versions. Any thoughts on this?

**Comment by mstormi** [comment]
I'm not keen on attempting to figure out how to support users in *migrating* from 32 to 64.
Lots of hassle and time to waste, plus pitfalls,  and to be frank: this is not a openHABian maintainer's or contributor's job.
Any 32 bit users will have to reinstall their RPi(+ OH), and historic data will be gone.
If you want to write a script to import old data, be it for rrd4j or even Influx, please do and contribute as PR, but as said I don't see this to be our job.

**Comment by holgerfriedrich** [comment]
Maybe my formulation was misleading. When I said "migration". I was referring to the RRD files. Of course, I am expecting that users do a fresh install using a 64-bit image.

If I got it correctly, currently, historic data is not in the scope of the backup/restore mechanism.
If we can prevent users from loosing historic data, e.g., by providing an extended backup/restore mechanism, this would be a good thing.

Let's see the options we have to do this. For now, platform dependent RRD file format is one of the issues identified on our way towards OH5/64-bit.

**Comment by mstormi** [comment]
openhab-cli has a --full option that also backups rrd persistence data.
But it won't migrate it to 64 I believe.

**Comment by mstormi** [comment]
> openhab-cli has a --full option that also backups rrd persistence data.

wouldn't it make sense to add the 32->64 converter to the restore function in openhab-cli ? @BClark09 wdyt?
(if needed at all, I have no idea if that conversion is mandatory)

**Comment by BClark09** [comment]
I agree that we should have some functionality to convert here - if RRD is the default format then I'm assuming there's a way to do the export/import from openHAB, rather than the scripts it comes with? Either way it might be something we wish to track with the other OH5 preparations.

If we do have to make platform dependent provisions - do I understand correctly that we have to export/dump from the old architecture and restore on the new?

**Comment by holgerfriedrich** [comment]
There is actually no need to convert data. We are using RRD4J database format, which is _not_ dependent on platform.
This is also mentioned as one of the main selling points of RRD4J:
https://github.com/rrd4j/rrd4j#why-rrd4j
> Why RRD4J?
> Portable files, RRDTool files are not


I just imported data from my old backups and could still visualize it on my 64-bit system.

Sorry for the confusion.
