### ISSUE TITLE
Amanda backup cannot be installed on FAT-formatted storage

### ISSUE THREAD

**Issue by ththeimer** [openhab/openhabian#1928]
Hello, I tried to get Amanda backup solution installed using Openhabian and followed the instructions in the documentation. I have an exFAT formatted USB storage connected to the Pi, as Windows-formatted storage is one of the examples given in the docs. So I was assuming this should work. As it turns out, it does not.

I am running the latest stable SW (4.2.3) on a Raspberry Pi4, with a standard configuration on SD card, and an external USB storage as mentioned. In general, that is working very well and stable.

When running the Amanda install in Openhabian, I have encountered two issues:

1. Openhabian tries to force the Amanda directory to ownership of backup:backup. Unless the file system is already mounted with that ownership, it will fail, as FAT devices do not support changing the ownership of files.

Debug Information:

> $ chown --recursive backup:backup /storage/ssd-backup/amanda
> + chown --recursive backup:backup /storage/ssd-backup/amanda
> chown: der Eigentümer von '/storage/ssd-backup/amanda' wird geändert: Die Operation ist nicht erlaubt
> + return 1
> + echo 'FAILED (chown)'
> FAILED (chown)

To avoid that, the fstab entry would have to include gid=backup, which is not the case in the example of the docs. Of course that could be fixed easily, and in that case the installation gets a little further but then hits another blocking point:

2. Openhabian tries to create a symbolic link under the slots directory. This fails, because FAT devices do not support symbolic links.

Debug information:

> $ ln -sf /storage/ssd-backup/amanda/slots /storage/ssd-backup/amanda/slots/drive0
> + ln -sf /storage/ssd-backup/amanda/slots /storage/ssd-backup/amanda/slots/drive0
> ln: die symbolische Verknüpfung '/storage/ssd-backup/amanda/slots/drive0' konnte nicht angelegt werden: Die Operation ist nicht erlaubt
> + return 1
> + echo 'FAILED (link drive0)'
> FAILED (link drive0)

This is a real blocking point and cannot be fixed by the user.

In my view, either the creation of such links is removed from the Amanda installer, (not sure why that is needed), or the Windows FAT example is removed from the docs or replaced by a comment that FAT devices cannot be used for storage.
I am assuming these issues will not arise on ext4 formatted drives, but I have not tested that.

Just for completeness:

> openhabian@openhab3:~ $ cat /etc/os-release
> PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
> NAME="Raspbian GNU/Linux"
> VERSION_ID="11"
> VERSION="11 (bullseye)"
> VERSION_CODENAME=bullseye
> ID=raspbian
> ID_LIKE=debian
> HOME_URL="http://www.raspbian.org/"
> SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
> BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
> 
> openhabian@openhab3:~ $ uname -m
> aarch64
>

**Comment by mstormi** [comment]
You have not properly read and misinterpreted the docs.
The storage medium has to be mounted BEFORE you install Amanda.
Amanda is not meant to be installed on removable media anyway as storage has to be guaranteed to be available on every backup run.
Plus, storage must be large enough to have the cumulated backup data fit in, which usually means at least 3-4 times the size of the SD card to be backed up.
Permanently mount a suitably large medium and try again.

**Comment by ththeimer** [comment]
Perhaps the source of confusion is this: "Unless the file system is already mounted with that ownership". What I meant to say is that one has to include both user and group "backup" in the mount options, then the first issue will not arise. That is what I then did, mounted again, and then I hit the second issue which is a hard blocker.

**Comment by mstormi** [comment]
I've updated the docs and removed the FAT example.
Use ext4 formatting.
That'll also ensure you don't accidentally remove the stick and forget to put it back in time for the next backup run.

**Comment by ththeimer** [comment]
Thanks Markus, that makes sense. In just noticed that the usbstick-msdos is still mentioned in the SW installation section below the example.Am 10.12.2024 um 09:23 schrieb Markus Storm ***@***.***>:﻿
I've updated the docs and removed the FAT example.
Use ext4 formatting.
That'll also ensure you don't accidentally remove the stick and forget to put it back in time for the next backup run.
