### ISSUE TITLE
Wi-Fi channel 12 issue and REGDOMAIN fix for it

### ISSUE THREAD

**Issue by jacekswoboda** [openhab/openhabian#198]
Hi, is it possible to add option from openhabian-config to easily edit country code (REGDOMAIN) in:
`/etc/default/crda`?
Without setting for example **PL** for Poland, there is issue with WiFi networks witch uses 12 channel.

Here is example topic about that issue in Raspberry Pi 3:
[https://raspberrypi.stackexchange.com/questions/43474/how-to-enable-wi-fi-channel-12-on-raspberry-pi-3](https://raspberrypi.stackexchange.com/questions/43474/how-to-enable-wi-fi-channel-12-on-raspberry-pi-3)
and using command:
`iw reg set`
with also works good but must be set from crontab after each reboot.
Best regards

**Comment by ThomDietrich** [comment]
Seems like it.
