### ISSUE TITLE
Bluetooth prompt when enabling serial

### ISSUE THREAD

**Issue by skatun** [openhab/openhabian#199]
When user select serial activation on RPI3 from the Openhabian menu, this will diable the bluetooth. This should be prompted in clear text to the user, and also how the user later can reenable it. I think it will be hard to scan the bindings and see if some of them require bluetooth and then in addition tell them that those bindings will not work any more.

**Comment by ThomDietrich** [comment]
Hey @skatun!

The second menu entry is called ""(RPi3) Disable Bluetooth module". To reenable Blueooth, just unselect the entry.

Not sure what is unclear or can be improved here!?

**Comment by skatun** [comment]
I thought you said when you activate the serial port the bluetooth gets disabled automatically, and this happens without a warning

**Comment by ThomDietrich** [comment]
No check it out yourself: https://github.com/openhab/openhabian/blob/master/openhabian-setup.sh#L702

This is the important part:

```shell
if [[ $selection == *"2"* ]]; then
    if is_pithree; then
       echo "dtoverlay=pi3-miniuart-bt" >> /boot/config.txt
```

**Comment by ThomDietrich** [comment]
This is settled? Please comment if not ;)
