### ISSUE TITLE
ssh issue

### ISSUE THREAD

**Issue by gagadepp** [openhab/openhabian#200]
can't ssh into openhab server on my raspberry pi3 

copying the output -
ssh openhabian@192.168.1.4 -v
OpenSSH_6.9p1, LibreSSL 2.1.8
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: Connecting to 192.168.1.4 [192.168.1.4] port 22.
debug1: Connection established.
debug1: identity file /Users/Gagan/.ssh/id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/Gagan/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/Gagan/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/Gagan/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/Gagan/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/Gagan/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/Gagan/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/Gagan/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.9
debug1: Remote protocol version 2.0, remote software version OpenSSH_6.7p1 Raspbian-5+deb8u3
debug1: match: OpenSSH_6.7p1 Raspbian-5+deb8u3 pat OpenSSH* compat 0x04000000
debug1: Authenticating to 192.168.1.4:22 as 'openhabian'
debug1: SSH2_MSG_KEXINIT sent
Connection closed by 192.168.1.4

Can anyone help fix this ?

**Comment by ThomDietrich** [comment]
Please do not double-post. As I don't think this is a openhabian issue but a usage problem I'll close the issue, we can reopen if a real issue presents itself.

https://community.openhab.org/t/ssh-issue/33327/3
