### ISSUE TITLE
Can you please add a Set Pi IP address to the Config Tool? 

### ISSUE THREAD

**Issue by Michilson02** [openhab/openhabian#202]
Hey guys for new people to Openhabian I have a couple of requests.

Can you add the following to the Config Tool Screens Maybe under system settings: 

User Name for Pi, OpenHab, & Network Shares
And I IP address config Screen to set the IP address in the Config tool. 

Thanks Guys!

**Comment by ThomDietrich** [comment]
Hello @Michilson02 👋 

The name of the linux and samba users can be set already, it's an undocumented feature though. After flashing the image, edit the file "openhabian.conf" on the root of the sd card. See [here](https://github.com/openhab/openhabian/blob/master/build-rpi-raspbian/openhabian.raspbian.conf).
the openhab user can not be changed (it's neither meaningful nor supported by openHABian). Let me make clear that the openHAB setup and execution process, including the apt method, has full support for that. So if you (for whatever reason) want to go with another user, I can point you in the right direction.

The IP address is retrieved from your local DHCP server. At one point we decided against an menu entry to set the IP manually. Check out [this discussion](https://community.openhab.org/t/openhabian-and-static-ip-address/25403/6?u=thomdietrich) for all details, arguments and instructions on how to do it anyhow. Please add your opinion if you feel differently ;)

Are you happy with these answer?
