### ISSUE TITLE
Upgrade to Debian Stretch

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhabian#203]
https://www.raspberrypi.org/blog/raspbian-stretch/

It's only a matter of days till *somebody* asks for a Raspbian Strech based openHABianPi image. I'm not expecting any problems with that, just needs to be build and tested. I'm on vacation till next weekend, the release can be expected in the first days of September. 

For whoever is reading this: The release will also be a good point to announce noteworthy new features (as always). If you want to contribute something, now's the time ;)

**Comment by andrey-yantsen** [comment]
Hi, is there any chance for stretch-based image soon? :) I need new `gammu`, and it's not available in backports repo.

**Comment by ThomDietrich** [comment]
Still waiting for https://github.com/eclipse/mosquitto/issues/529 to be addressed...

**Comment by ThomDietrich** [comment]
I've looked into the task today and ran into only minor issues. The system is working fine on my testing system and I've tested most functions. 
I'll release the image together with a few release notes in the next 1-2 days.

**Comment by ThomDietrich** [comment]
For early testers, feedback would be appreciated.

https://drive.google.com/file/d/1tfcwcnUWWBWvTSVNi0f3mulTiG5IidKd/view?usp=sharing

**Comment by dotorg** [comment]
I just tried this image -- it didn't work. Networking didn't come up properly. (Specifically, WiFi). Without digging out a keyboard/mouse and poking around (which I don't have time to do right now), I can't say why.

**Comment by ThomDietrich** [comment]
Damn! I'll look into it. Thanks

**Comment by ThomDietrich** [comment]
@dotorg I can confirm the wifi issues. Also see: https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=191061

Currently working on the solution.

**Comment by dotorg** [comment]
Glad it wasn't just something on my end. My unit is now pretty heavily configured, so I probably won't be able to test a fix any time soon (I want to be 100% sure I understand how to fully backup and restore first).

**Comment by ThomDietrich** [comment]
Just a suggestion, my backup strategy is pretty simple: All data is accessible via samba under the `openhab-share` share. Install https://www.duplicati.com on your main PC and do a backup from there. It's a no-brainer and offers all the advantages.

Besides that, you can do your testing with a second SD card. However don't stress yourself, I'm also doing wifi testing here now. Did you experience any other issues or find any room for improvement?

**Comment by dotorg** [comment]
My controller is headless, so that was a blocking issue for me... as a result, I wasn't able to do any other testing on that version. I would've had to dig out a monitor/keyboard/etc, or move it somewhere I had an Ethernet port available.

**Comment by ThomDietrich** [comment]
I see. I'll keep you posted wrt the wifi issue.

Just so you know: The installation log is written to the SD card. You can access it on your main PC after the installation succeeded or failed.

**Comment by dotorg** [comment]
Yeah I know, the problem is that was a hard stop -- because the connection didn't come up, everything stops at that point. So there's nothing else in the log. What I couldn't do, because of that, was manually configure the wifi. (Although, looking at the logs, I was guessing it wasn't a configuration problem, but something with the OS image itself. I didn't dig into it much, though.)
