### ISSUE TITLE
Trouble with Ui´s

### ISSUE THREAD

**Issue by luisrival** [openhab/openhabian#207]
I have troubles with the UI´s it was function perfectly when one day I try to access via de android app and it was unable to conect, then i try with the ip address:8080 and it says that it can´t connect, but i have access to the raspberry via PUTTY in SSH. How can I fix this?
I install the lastest version a month ago.

![imagen](https://user-images.githubusercontent.com/8862466/29755705-63de2aae-8b61-11e7-9346-c81628f419d3.png)

**Comment by ThomDietrich** [comment]
Please check the datetime setting of your system. Not sure why it is not off but everything should work after you've dealt with that.

**Comment by luisrival** [comment]
Do you know how can i change the date and time manually? I try changing the ntp and forcing the update but with no luck

**Comment by ThomDietrich** [comment]
NTP should be the way to go. Otherwise https://www.debian.org/doc/manuals/system-administrator/ch-sysadmin-time.html

(date --set)
