### ISSUE TITLE
Differentiate between nodejs for armv7 and armv6

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhabian#209]
https://github.com/openhab/openhabian/blob/0e2437c2875f9235ef0346e3647023e26707cafe/openhabian-setup.sh#L531-L532

https://crycode.de/installation-von-node-js

**Comment by Wolfmanxxx** [comment]
Don't know if it helps. haven tried it yet but found these links:
https://github.com/sdesalas/node-pi-zero
https://blog.miniarray.com/installing-node-js-on-a-raspberry-pi-zero-21a1522db2bb

**Comment by ThomDietrich** [comment]
Please consider submitting a PR. Thanks!

**Comment by Wolfmanxxx** [comment]
script from row 563 in openhabian/openhabian-setup.sh worked for me. it installed perfectly on my pi0
(ran just the script "bash <(curl -sL https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/update-nodejs-and-nodered)"

**Comment by Wolfmanxxx** [comment]
Tried deleting the command nodejs_setup on both a pi 3 and pi 0
and ran the install.
on pi 3 it installed nodejs v7.10.1 and npm 4.2.0
on pi 0 it installed node v6.12.2 and npm 3.10.10 both running node-red v0.17.5

**Comment by ThomDietrich** [comment]
Sounds good to me! Your steps are however a bit unclear to me. Could you open a PR?
