### ISSUE TITLE
How to upgrade the right way

### ISSUE THREAD

**Issue by ChrisWorks** [openhab/openhabian#214]
Hi,

This is probably covered somewhere, but I have not been able to find a definitive answer.

I have an older openhabian install from 2016, and I dont know how to upgrade it. I saw one answer which was:

sudo apt-get update
sudo apt-get upgrade

This gives an error:

W: Failed to fetch https://openhab.ci.cloudbees.com/job/openHAB-Distribution/ws/distributions/openhab-offline/target/apt-repo/Packages  HttpError404

W: Failed to fetch https://openhab.ci.cloudbees.com/job/openHAB-Distribution/ws/distributions/openhab-online/target/apt-repo/Packages  HttpError404

I have also done a sudo openhabian-config and pulled the latest version of the config tool. That resulted in this WARNING:

> Attention: It was brought to our attention that the old openHABian ua-netinst based image has a problem with a lately updated Linux package.  If you upgrade(d) the package 'raspberrypi-bootloader-nokernel' your Raspberry Pi will run into a Kernel Panic upon reboot!   
> Do not Upgrade, do not Reboot!

I would like to get the latest version running with the latest openhab2 and not have to wipe/re-configure everything.

So where do I start?

I would love something like: "backup these 3 files, wipe and re-install, put back 3 files..."

**Comment by ThomDietrich** [comment]
Hey Chris,
you'll need to start with a fresh setup. openHABian always tried to stay backwards compatible but the switch of the base from ua-netinst to raspbian can not be automated.


Your last sentence is already correct. Backup, install, restore:

* http://docs.openhab.org/installation/linux.html#backup-and-restore
* http://docs.openhab.org/installation/openhabian.html
