### ISSUE TITLE
PINE64 - Hang on boot after first reboot after installation

### ISSUE THREAD

**Issue by EliasGabrielsson** [openhab/openhabian#215]
This is rather odd behavior or bug concerning PINE64. After successfully installed `Openhabian` and restarting it's hangs on boot with no sign of being alive.
[Thread discussion](https://community.openhab.org/t/openhabian-1-2-pine64-hangs-after-reboot/26857)

#### Symptom:
After restarting an installed system it's hangs on boot.
* No LED are blinking on network port. No access to device. `Ping`, `arp` etc.
* No HDMI signal

#### Reproduce:
1. Download image with version `v1.2`, `v1.3` or commit `0e2437c`
2. Use a 32gb SD card extract the image using `Etcher`.
3. Install Openhabian either headless or with HDMI cable, no difference.
4. Verify functionality with SSH or local console.
5. Reboot, error occurs.

#### Hardware:
```
Pine64 2GB, no addon at all like WiFi / BT

Revision info: (sticker on back)
201-A64DB110-02
A64-DB-V1.1 2G
C160358 04.10
```

**Comment by ThomDietrich** [comment]
Hey Elias,
did you find a solution, this is an odd and alarming issue. We should resolve it quickly and I'd love to see your help. Pay attention to the comment I left in the community thread. https://community.openhab.org/t/openhabian-1-2-pine64-hangs-after-reboot/26857/6

**Comment by EliasGabrielsson** [comment]
Made some more research on this topic.  Seems to be related to https://github.com/longsleep/build-pine64-image/issues/51. A bug concerning the kernel for Pine64, I don't think this will be fixed.

If anyone else encounter this the best workaround so far is just doing a plain install of ubuntu (with [this](http://wiki.pine64.org/index.php/Pine_A64_Software_Release#Xenial_Minimal_Image_.5B0.6.2-77.5D_by_ayufan) ) and then add openhabian by hand. Eg. login to the board and run:

```
sudo apt install git
git clone https://github.com/openhab/openhabian.git /opt/openhabian
sudo /opt/openhabian/openhabian-setup.sh
```

**Comment by ThomDietrich** [comment]
@EliasGabrielsson I am not using the Pine on a regular basis.
Does that mean, that you would recommend a standard Ubuntu over the longsleep build? Would you recommend to advertise this as the general method for the Pine?

**Comment by EliasGabrielsson** [comment]
I am currently using an Ubuntu image which is based on the longsleep image (ayufan, see link). It's look like ayufan still actively maintain the image ([latest pre-release was 16 oct 2017](https://github.com/ayufan-pine64/linux-build/releases) compared to longsleep 13 may 2017). When ayufan releases next stable build I think it worth looking into changing openhabians pine64 base. AFAIK the ayufan build have not solved the hang issue pointed out above. 

So for now just keep the base image as long no one else is having trouble I would say.
I know only two people have had this issue based on the [thread discussion](https://community.openhab.org/t/openhabian-1-2-pine64-hangs-after-reboot/26857).

**Comment by thomasgregersen** [comment]
@EliasGabrielsson 
I actually had the same issue on a newly purchased Pine64 a few months ago, but I thought it was related to hardware-issues and didn't have time to pursue, but I see I'm not the only one in that boat...
How do you power the Pine64 - by USB and with how many milliAmps?
BR Thomas

**Comment by ThomDietrich** [comment]
@EliasGabrielsson Thanks for the info. I'll keep my eyes open.
Just to put this out here: If you want to help improve the experience with the Pine, I'd be happy to have you as a regular collaborator for the Pine image. Otherwise the easiest maintainable version of openHABian-on-Pine would probably be the Manual Setup...
