### ISSUE TITLE
Openhabian-config, disable console problem

### ISSUE THREAD

**Issue by massimilianocasini** [openhab/openhabian#216]
openHABian Configuration Tool [master]v1.3-303(0e2437c)
Via script, to flag "[*] 1  (RPi) Disable serial console"  insert "enable_uart=1" to /boot/config.txt instead to delete it.
Via script, when to remove flag "[] 1  (RPi) Disable serial console"  try to delete  'dtoverlay=pi3-miniuart-bt' from /boot/config.txt instead of add "enable_uart=1"

**Comment by ThomDietrich** [comment]
Could you please add some context? I'm not sure what this issue is about...

**Comment by massimilianocasini** [comment]
I just needed to enable the terminal, set "[*] 1 (RPi) Disable serial console" and see that the script adds the parameter "enable_uart = 1" in /boot/config.txt, is it normal? When flag "Disable serial console" What do you mean?

**Comment by ThomDietrich** [comment]
Enabling the flag should configure the Pi to disable the serial console to free the serial interface for peripherals. See [here](https://elinux.org/RPi_Serial_Connection#S.2FW:_Preventing_Linux_from_using_the_serial_port) and [here](https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=141195).

Removing the flag would revert that action but as no one actually needs the serial console, we didn't bother to implement that step yet, see https://github.com/openhab/openhabian/blob/master/openhabian-setup.sh#L749-L752

**Comment by ThomDietrich** [comment]
Is the issue settled? Please comment if not. Thanks
