### ISSUE TITLE
Mention Amanda as optional component

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhabian#227]
By @mstormi 
> Please mention Amanda on http://docs.openhab.org/installation/openhabian.html#optional-components, too.

I'll do that the next time I'm working on openHABian. (Soon)

**Comment by mstormi** [comment]
See also [PR #231](https://github.com/openhab/openhabian/pull/231)

**Comment by ThomDietrich** [comment]
Done. Please check if you are satisfied ;)

**Comment by mstormi** [comment]
Yes (except typo: buil**t**in). Will that show up in the link I mentioned, too?
Not sure if people even read the docs/openhabian.md at all, I think most will just browse the webpage.

**Comment by ThomDietrich** [comment]
Typo corrected. It will soon be available under http://docs.openhab.org/installation/openhabian.html#optional-components

I'm not sure either. Maybe now that there is a clear link... Judging by the community thread the interest is quite high. Maybe you could additionally post the article there as a Tutorial and get a discussion going
