### ISSUE TITLE
openhabian-config tries ipv6 and fails

### ISSUE THREAD

**Issue by BrutalBirdie** [openhab/openhabian#228]
Problem:
openhabian-config tries to install like mosquitto over ipv6 and times out

I forced my apt to use -o Acquire::ForceIPv4=true but that does not work with openhabian-config
An option to select this would be good.

**Comment by ThomDietrich** [comment]
Hey Elias! 👋 
I'd say that depends on your environment, doesn't it? If your ISP/network provides IPv6 addresses, it should also provide the means to have apt do whatever it wants... Please correct me if I'm mistaken.

**Comment by motionless** [comment]
Hi Thomas,
it's correct that it depends on the environment. Nevertheless, it's still a problem that stops the auto setup of OpenHabian to work in certain environments.
Elias was asking for a switch. I would prefer to have this switch either in the openhabian.conf or a file like the ssh one on the boot partition.
If you have any recommendations of the path I could look at, I wouldn't hesitate to implement this feature.

**Comment by mstormi** [comment]
This is an interesting issue and possibly still a problem for a number of users.

@BrutalBirdie can you elaborate what's the conditions that make openhabian fail to finish installing?

**Comment by mstormi** [comment]
@BrutalBirdie ping

**Comment by mstormi** [comment]
@BrutalBirdie @motionless can you please precisely describe the problem and what you think we would need to change in openhabian.
I don't understand the relation to Mosquitto. openhabian-config just uses apt-get so there should be no difference no matter what package you install. It's either always using ipv6 or never.
We also have no influence on your Inet connection, and we don't change anything specific about routing compared to the Raspbian base (or whatever base you may use this on, you fail to mention that). BTW Raspbian also has changed (to buster) since you opened this issue.

**Comment by BrutalBirdie** [comment]
Oh f*ck! I did not get any notification about this Issue, I am very sorry for the delay!

My initial issue was never related to mosquitto, is was targeted at the initial install process.

The initial problem for me was that openHABian install apt tried to use IPv6 and failed without a real verbose output. Leading to a never ending install process.


imo the best option would be to make it a config flag in [openhabian.conf](https://github.com/openhab/openhabian/blob/master/build-image/openhabian.conf) file that should default to IPv4.

**Comment by mstormi** [comment]
I don't understand yet what your issue is in the first place so don't talk about solutions yet please.
What does not work with the initial install process ?
Does that still happen with the latest version?
What is that flag supposed to do ? and finally 
*Why* do you think you need to have that ?

**Comment by BrutalBirdie** [comment]
> So far I don't understand what your issue is in the first place so don't talk about solutions yet and start explaining from the beginning please.

Problem was/is that when starting openHABian for the first time, it tried for ever to apt install and failed after 1 hour or more.
then when inspecting the apt logs I noticed it tried to use IPv6 but failed without a message

> What does not work with the initial install process ?

The initial start of openHABian hanging up on apt install

> Does that still happen with the latest version?

Did not have the time to test it again, but it got reported several times in the community.

> What is that flag supposed to do?

The flag I tried to propose, is supposed to set apt to force use IPv4

```
echo 'Acquire::ForceIPv4 "true";' | sudo tee /etc/apt/apt.conf.d/99force-ipv4
```

> Why do you think you need to have that ?

Since I created the issue on 2 Nov 2017 and did not test it again so far I can't even tell if it's still relevant.

**Comment by mstormi** [comment]
> Since I created the issue on 2 Nov 2017 and did not test it again so far I can't even tell if it's still relevant.

Then please do. We moved to buster meanwhile that could have changed things.
Also it seems a bit unlikely that it keeps trying ipv6 forever without ever falling back to ipv4.

**Comment by mstormi** [comment]
FYI https://community.openhab.org/t/setup-of-openhabian-continuously-fails/94893/18
