### ISSUE TITLE
GPIO Binding error not binding

### ISSUE THREAD

**Issue by cdelrey** [openhab/openhabian#229]
Another noob here banging my head trying to set up GPIO bindings on OH2 to work. I have a RP3 running Jesse using standard apt install for OP2. I've follow many different guides to get me where I am and I thinking it may be part of the issue. I do have something working, 2 connected temp sensors reading into OH2. What's weird is natively in RP using wiringpi scheme I can trigger the relay ports "gpio mode out, gpio write 1 0 and everything works i trigger the relays. It took me a while but I using the BCM gpio numbers I can set the value on /sys/class/gpio and that works.... which is confusing, nevertheless, anytime I update my items file the log is throwing errors. 

```
2017-11-02 23:32:43.006 [ERROR] [ab.binding.gpio.internal.GPIOBinding] - Error occured while creating backend object for item LED, exception: /sys/class/gpio/unexport
2017-11-02 23:32:43.015 [ERROR] [ab.binding.gpio.internal.GPIOBinding] - Error occured while creating backend object for item channel1, exception: /sys/class/gpio/unexport
2017-11-02 23:32:43.023 [ERROR] [ab.binding.gpio.internal.GPIOBinding] - Error occured while creating backend object for item channel2, exception: /sys/class/gpio/unexport
2017-11-02 23:32:43.030 [ERROR] [ab.binding.gpio.internal.GPIOBinding] - Error occured while creating backend object for item channel3, exception: /sys/class/gpio/unexport
2017-11-02 23:32:43.037 [ERROR] [ab.binding.gpio.internal.GPIOBinding] - Error occured while creating backend object for item channel4, exception: /sys/class/gpio/unexport
```

I made sure permissions match adding openhab to the gpio group 

```
cat /etc/group |grep gpio
gpio:x:997:pi,cdelrey,openhab
```

```
ls -l /sys/class/gpio/
total 0
-rwxrwx--- 1 root gpio 4096 Nov  2 23:59 export
lrwxrwxrwx 1 root gpio    0 Oct 29 23:48 gpiochip0 -> ../../devices/platform/soc/3f200000.gpio/gpio/gpiochip0
lrwxrwxrwx 1 root gpio    0 Oct 29 23:48 gpiochip100 -> ../../devices/gpiochip2/gpio/gpiochip100
lrwxrwxrwx 1 root gpio    0 Oct 29 23:48 gpiochip128 -> ../../devices/gpiochip1/gpio/gpiochip128
-rwxrwx--- 1 root gpio 4096 Nov  3 00:15 unexport
```

I have both "Exec Bindings and GPIO Bindings and REGEX Transformation installed. Everything else is kind of default not sure what else to look at? I tried installing libjna-java and setting JAVA_ARGS=-Djna.boot.library.path=/usr/lib/jni but it doesn't look like it's for this version, the instructions aren't that clear and I just don't want to keep installing stuff blind. 

Any guidance would be appreciated! Thanks, Chris

**Comment by ThomDietrich** [comment]
Hey! I'm the maintainer of this repository but have little personal experience with the GPIO binding. Please contact the openHAB community forum for help. You will reach many openHABian users by posting in the main thread: https://community.openhab.org/t/openhabian-hassle-free-openhab-setup/13379

**Comment by ThomDietrich** [comment]
Hey, did you find a solution to the issue?

**Comment by robbyb67** [comment]
In my /etc/rc.local script was an "exit 0" just before the preparation of the /sys/class/gpio filetree:

`#!/bin/sh -e
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.

FLAG="/opt/afterfirstboot.lock"
FIRSTBOOT="/boot/first-boot.sh"

# Only executed after first boot
if [ ! -f "$FLAG" ]; then
  echo "[openHABian] Flag file 'afterfirstboot.lock' not found, continuing with '$FIRSTBOOT' script."
  if [ ! -f "$FIRSTBOOT" ]; then "[openHABian] 'first-boot.sh' not found, Exiting."; exit 0; fi
  if (/bin/bash "$FIRSTBOOT"); then
    echo "[openHABian] Finishing up... "
    echo "[openHABian] Created after first boot script succeeded (see /etc/rc.local). Do not delete." > "$FLAG"
  else
    echo "[openHABian] Script '$FIRSTBOOT' failed."
  fi
fi

exit 0

chown -R root:gpio /sys/class/gpio

chmod -R ug+rw /sys/class/gpio

chown -R root:gpio /sys/class/gpio

chmod -R ug+rw /sys/class/gpio

# vim: filetype=sh`

If I comment this out it simply works :-)
