### ISSUE TITLE
audio not working on raspberry openhabian  2.2.0~20171030010135-1 (Build #1072) 

### ISSUE THREAD

**Issue by vk45** [openhab/openhabian#232]
audio on a raspberry pi 3 is not working on a fresh installation 2.2.0~20171030010135-1 (Build #1072) .

I found that openhab is not in the audio group
I edit /etc/group 
was: audio:x:29:openhabian
changed to : audio:x:29:openhabian,openhab

Maybe is a good idea to change this one of the next builds

regards

**Comment by ThomDietrich** [comment]
Thanks for the issue report. I've just fixed that.
