### ISSUE TITLE
Zulu or Oracle Java install fail with dirmngr error

### ISSUE THREAD

**Issue by kai-bcn** [openhab/openhabian#233]
My openhabian image doesn't work, so I installed the openhabian-config file on top of raspbian, and went through all the different steps, including 61 (Upgrade) + 62 (install needed and recommended system packages).
After that, trying any of the 2 Java items from the menu fails.

**Suggestion: include dirmngr in step 62, please.**

2017-11-10_18:22:08_CET [openHABian] Installing Zulu Embedded OpenJDK...
$ apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 219BD9C9
Executing: /tmp/apt-key-gpghome.U1xlmvGQ9J/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 219BD9C9
gpg: failed to start the dirmngr '/usr/bin/dirmngr': No such file or directory
gpg: connecting dirmngr at '/tmp/apt-key-gpghome.U1xlmvGQ9J/S.dirmngr' failed: No such file or directory
gpg: keyserver receive failed: No dirmngr
FAILED (keyserver)
pi@raspberrypi:~ $

pi@raspberrypi:~ $ sudo openhabian-config
2017-11-10_18:22:15_CET [openHABian] Checking for root privileges... OK
2017-11-10_18:22:15_CET [openHABian] Loading configuration file '/etc/openhabian.conf'... OK
2017-11-10_18:22:18_CET [openHABian] Preparing and Installing Oracle Java 8 Web Upd8 repository...
$ apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886
Executing: /tmp/apt-key-gpghome.hFVPdBKVJ7/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886
gpg: failed to start the dirmngr '/usr/bin/dirmngr': No such file or directory
gpg: connecting dirmngr at '/tmp/apt-key-gpghome.hFVPdBKVJ7/S.dirmngr' failed: No such file or directory
gpg: keyserver receive failed: No dirmngr
FAILED (keyserver)
pi@raspberrypi:~ $

**Comment by ThomDietrich** [comment]
Weird but seems to check out. https://stackoverflow.com/a/44697554

Thanks. Will be added soon. Feel free to open a pull request!

**Comment by ThomDietrich** [comment]
Thanks again! I had the chance to test this and am about to commit the needed change
