### ISSUE TITLE
Find server installation, data and templates folders missing

### ISSUE THREAD

**Issue by mherwege** [openhab/openhabian#236]
I tried the Find server install option yesterday.
The script ran through successfully, but the findserver did not start. The service was in failed state.
Further investigation pointed to missing data and templates folders. I checked in the install zip and these should indeed be in the current directory when executing the find server. Copying these from the zip file to the /var/lib/findserver directory solved this issue. However, I am not sure these should be there. Maybe there is an environment variable to put it in a more appropriate place.
I believe the install script should be extended to put these directories and file in the appropriate place.

**Comment by ThomDietrich** [comment]
@mstormi any idea?

**Comment by mstormi** [comment]
yes, seems I didn't extract all required files so far. Here's a fix:
https://github.com/openhab/openhabian/pull/237
