### ISSUE TITLE
Grafana on Ubuntu 17.10 fails to install

### ISSUE THREAD

**Issue by ConfusedTA** [openhab/openhabian#239]
Hi,

I have set up a Minimal Ubuntu Server 17.10 system in a virtual machine on ESXi 6.5 (just in case it's relevant, or anyone wants to replicate my setup!)

When attempting to install InfluxDB & Grafana, it fails.

By Looking at the script, it appears to be bypassing the steps regarding the repository and keyserver for Grafana, because these are wrapped within first a check that it's `jessie` and secondly that it's on a Pi. As I'm failing both of these checks, apt is never informed of where to get Grafana from, so fails on `apt -y install grafana`

InfluxDB appears to be installing and running OK.

**Comment by ConfusedTA** [comment]
I have manually installed Grafana now using these additional commands:

`curl https://packagecloud.io/gpg.key | sudo apt-key add -
sudo apt-add-repository "deb https://packagecloud.io/grafana/stable/debian/ jessie main"
`
My guess is that these need to be inserted into the script if it's not running on a Pi - but I'm not au fait with this scripting to make a PR myself I'm afraid!

**Comment by kubawolanin** [comment]
FYI - Grafana installation script is located here:
https://github.com/openhab/openhabian/blob/ef175b2e7e2b4ada815b7d1ffea0e0194ceada2c/openhabian-setup.sh#L1197-L1221

**Comment by ThomDietrich** [comment]
Thanks @kubawolanin for your help! I have to admit that this part (without any else handling) was pretty weak. Happy to improve it now.

@ConfusedTA If you'd like, it would be great to also add the rest of the setup steps as described in the Tutorial... Might be a bit too much for a self-proclaimed Linux Noob but on the other hand, there are many routines you can take examples from ;)

**Comment by kubawolanin** [comment]
> @ConfusedTA If you'd like, it would be great to also add the rest of the setup steps as described in the Tutorial... Might be a bit too much for a self-proclaimed Linux Noob but on the other hand, there are many routines you can take examples from ;)

That's right, came here to propose the same thing! :laughing: 

@ConfusedTA take a look at https://github.com/openhab/openhabian/issues/35 - would you mind taking a stab?

**Comment by ConfusedTA** [comment]
Well I guess it'll give me some more exposure to Linux... can't make any guarantees, but I'll have a look and see how I get on... 😄
