### ISSUE TITLE
openHAB 2.2 stable: Add openhab-cli to welcome message

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhabian#242]
After openHAB 2.2 is in the stable branch we can advertise the new `openhab-cli` by @BClark09 on the login screen alongside `openhabian-config`

**Comment by BClark09** [comment]
Sounds good to me!  ☺️

**Comment by BClark09** [comment]
Speaking of which is there anything that would be beneficial to include in it?

One thing I need to remember to do before 2.2.0 is extend the `openhab-cli` with options that would typically be used with karaf.

**Comment by ThomDietrich** [comment]
I've also thought about this for a while now. What is the future of openHABian? What's the purpose of `openhab-cli` on an openHABian system? With the `openhabian-config` menu a powerful script already exists and is known by all openHABian users. How can both programs live alongside each other?

Looking from a user perspective I wonder if it would be more meaningful to include the openhab-cli functionality in `openhabian-config`. Looking from a developer perspective I wonder how we can synchronize the work on both projects.
