### ISSUE TITLE
Persistent issue installing the latest build ...

### ISSUE THREAD

**Issue by dotorg** [openhab/openhabian#245]
This has been a problem in attempting to install the 1.3 release of OpenHABian for a few days now.

The system basically fails with non-obvious errors during the setup, 

The important bits are at the end ...

```
2017-11-27_12:10:25_EST [openHABian] Adding slightly tuned vim config file to system... OK
2017-11-27_12:10:25_EST [openHABian] Downloading and setting up FireMotD... OK
2017-11-27_12:11:49_EST [openHABian] Installing etckeeper (git based /etc backup)... OK
2017-11-27_12:12:09_EST [openHABian] Installing Zulu Embedded OpenJDK... OK
2017-11-27_12:14:19_EST [openHABian] Installing openHAB 2.1 (stable)... FAILED (apt)
2017-11-27_12:14:43_EST [openHABian] Initial setup exiting with an error.
```

It took a while to figure out why openHAB 2.1 was failing to install. 

"apt-get update" has this nugget:
W: Failed to fetch http://dl.bintray.com/openhab/apt-repo2/dists/stable/main/binary-armhf/Packages  405  Not Allowed [IP: 52.35.233.252 80]

Looks like the repo for the actual openHAB packages is returning a 405. (Note, that IP isn't mine, its an AWS one)

Google suggests that bintray does not allow HTTP connections. There's actually a post about it in the openhab forum, as well:
https://community.openhab.org/t/solved-unable-to-install-using-apt-get-getting-405-not-allowed-when-updating/28296/5

The problem is, at setup time there doesn't seem to be a spot to make that change. I can overwrite openhab2.list in the first_boot.sh script, but something during the install process overwrites it with the bad one again. If I manually fix it after the setup has broken, the system fails at this point:

```
2017-11-27_13:23:48_EST [openHABian] Cloning myself... FAILED
2017-11-27_13:23:48_EST [openHABian] Initial setup exiting with an error.
```

It seems the steps it executes during "Cloning myself" errors if its already been done. 

If I manually install openhab2, the install does work correctly as long as that URL is https, but because the first start won't re-run properly, the system is still left in a broken state.

Is there any way, short of someone releasing a patch, to get that repository URL correct at boot so the install works properly? Or is the current Pi installer just FUBAR?

**Comment by dotorg** [comment]
One update... adding an "rm -rf /opt/openhabian" before the git clone got past that and the install worked. 

So that seems to be a work-around in case anyone else runs into any issues.

**Comment by ThomDietrich** [comment]
Hello @dotorg,
this is a surprise to me. At this point I'm not sure why the situation is like it is. I agree that it should be https, even though it works with http, at least for the 99% of other users 😄 

I've just created and merged the relevant change. Could you please try again?

**Comment by dotorg** [comment]
So I suspect the issue, from doing some poking around, is that bintray is using geographically distributed servers in AWS with an SSL proxy in front, and that proxy (or Route53) is doing geographic load balancing, and the specific combination of proxy and/or back-end server that is covering my region is mis-configured. So it may only impact people in certain parts of the world. 

Happy to give a try with the new image -- the Pi my OpenHAB is running on right now is just being used for learning OpenHAB while I'm building a few custom bindings, so there's nothing on it I can't lose doing a reinstall. 

Is there an updated v1.3 build with the fix? I can try that, as well.

**Comment by ThomDietrich** [comment]
Great. Here you'll find the image: #203 

> Is there an updated v1.3 build with the fix?

As you seem to have a good understanding of your bits and bytes, maybe you are interested in the basic workings of openHABian. As you [might know](http://docs.openhab.org/installation/openhabian.html) the openHABian project provides two things: A set of scripts to install and configure an openHAB-hosting Linux system and images for the RPi and the Pine A64 to further automate the process.
The RPi image is a slightly modified of the original Raspbian image. It includes a script which is called on first boot. This script will then simply `git clone` the openHABian repository and execute the openhabian tool in a special `unattended` mode.

This has the big advantage, that we (I) rarely have to update the images themselves. All changes are pushed to the repository and henceforth applied on new installs with the image created months ago. The same goes for already existing setups. A user can execute `sudo openhabian-config` -> "Update" and voilà he/she has access to the newest additions.

So to answer you question: Both the v1.3 image and the unofficial v1.4 image linked above already include the fix 😄 

Please go all out and test the new image. Let me know of all tiny issues you uncover! 😉 

Best! Thomas

**Comment by dotorg** [comment]
Ah, so that's what it was doing with the git-clone. I figured it was the software, but it wasn't clear how much of the system was pulled at that point. 

I'll do some testing, and see if they help. Thanks!

**Comment by dotorg** [comment]
So, the updated 1.3 worked fine this time with that change. I did get one error I'm pretty sure I didn't the last time:

Failed to start apply_noobs_os_config.service.
See 'systemctl status apply_noobs_os_config.service' for details.

I don't see any obvious issues with the system as a result. This is what was reported:

[14:03:18] openhabian@openHABianPi:~$ sudo systemctl status apply_noobs_os_config.service
● apply_noobs_os_config.service
   Loaded: not-found (Reason: No such file or directory)
   Active: failed (Result: timeout) since Tue 2017-11-28 13:48:16 EST; 15min ago

Apr 10 05:58:50 openHABianPi apply_noobs_os_config[396]: Applying config from /boot/os_config.json (if it exists):.
Nov 28 13:48:16 openHABianPi systemd[1]: apply_noobs_os_config.service start operation timed out. Terminating.
Nov 28 13:48:16 openHABianPi systemd[1]: Failed to start apply_noobs_os_config.service.
Nov 28 13:48:16 openHABianPi systemd[1]: Unit apply_noobs_os_config.service entered failed state.
[14:03:21] openhabian@openHABianPi:~$

I'll pull the 1.4 one down and give it a shot in a little while ...

**Comment by ThomDietrich** [comment]
`apply_noobs_os_config.service` :roll_eyes: Not sure what that is. Where did you see the error?

**Comment by rwmccoy** [comment]
ThomDietrich, can you give a little more information about your workaround? 

I have the same issue and I can't find openhab2.list in first_boot.sh. 

Thanks

**Comment by ThomDietrich** [comment]
Hello,
@rwmccoy which error are you talking about? It should be solved by now.
Please describe the error you are facing in detail, thanks!

**Comment by rwmccoy** [comment]
Exactly the error you described at the top of the thread. I must fall within the geography that is seeing the http error. I'm using the OpenHabian image which hasn't been updated yet. If you think my best bet is to do a manual install, I'll go that way. I just wasn't able to find the item in first_boot.sh you mention changing to get around the problem. 

This is my first really forey into OpenHab, so forgive me if I'm missing the obvious and thanks for your help.

**Comment by ThomDietrich** [comment]
Weird. As I said before, the image you are using **does** contain the fix.
You have two options:

1. Use the latest image I'm going to officially publish this evening: https://drive.google.com/open?id=1Y9Vz8rJbkQ3qlzm3P2LfY9nEQ-_x2iyc
2. Go the manual setup path by first flashing and booting a normal Raspbian system, then follow http://docs.openhab.org/installation/openhabian.html#manual-setup

I'm sorry for the trouble getting started, I expect both options to succeed. Please let me know how it went! Good luck!

**Comment by rwmccoy** [comment]
Per the old image containing the fix. Read and understood. 
Short on time today so I had to take a quick run using your new image. 
Short version: It worked.
Thank you for the help!
