### ISSUE TITLE
FireMotD: Implement openHAB statistics

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhabian#253]
Not critical but rather nice to have.

This might be a fun task for someone new but with shell development experience. The task is to implement routines to retrieve simple openHAB statistics, e.g. through REST API, then store and present them inside FireMotD. No implementation on openHABian side needed.

See for more details: https://github.com/OutsideIT/FireMotD/issues/46

**Comment by mstormi** [comment]
After 3yrs on idea level I think we need to close this.
Reopen if you have something new closer to an implementation.
