### ISSUE TITLE
Add user openhab to group homegear

### ISSUE THREAD

**Issue by jboeddeker** [openhab/openhabian#254]
The user openhab is used to run shell scripts (executeCommandLine). In order to control Homegear via scripts, it is neccessary to add this user to the homegear group. (user openhabian is already)

I created a script to modify the parameter of an homematic direct link, Homegear refused to run this script with permission denied. 

The script worked as soon as i added the openhab to the group homegear.

**Comment by ThomDietrich** [comment]
May I ask what you use the scripting for? I'm a Homematic/Homegear user myself and control everything via openHAB.

**Comment by ThomDietrich** [comment]
Done. It was already close btw, the openhabian user was already added to the homegear group.

Best!
