### ISSUE TITLE
Add force user/group to Samba

### ISSUE THREAD

**Issue by gerritv** [openhab/openhabian#255]
Several comments in the forums plus my own recent experience result in this Issue.
At present when editing existing shared files there is no problem as the files were created under the correct user/group. New files however are not, leading to Openhab ignoring them. E.g. when creating a sitemap using VS Code Openhab plugin.

The PR provides an updated smb.conf file.

**Comment by ThomDietrich** [comment]
I can't confirm that. Files are created as `openhabian:openhabian` and the correct access rights so openHAB can read them. There is a function to fix permissions, which handles most of that for you: https://github.com/openhab/openhabian/blob/master/functions/system.sh#L159

Could you please give an example how I can provoke your issue?

**Comment by gerritv** [comment]
![ownership](https://user-images.githubusercontent.com/8202594/33809248-dcc98500-ddc1-11e7-9d21-59c83c0ceef3.JPG)

I changed other things since then and can't repro it right now. I will delete the PR.

**Comment by ThomDietrich** [comment]
I've done some changes with regard to file rights a few months back Maybe that brought the changes you are seeing now. Please reopen if you ever find an issue!
