### ISSUE TITLE
Optional component: Add MQTT client UI

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhabian#266]
What do you think?

https://github.com/hivemq/hivemq-mqtt-web-client

Do you know a better alternative?

**Comment by ConfusedTA** [comment]
Is WebSockets enabled by default on the installed MQTT server?

Having this utility available as an option to test a newly set up system would be beneficial to some users.

**Comment by ThomDietrich** [comment]
I think so too. Would you care to set it up on your local system and do some testing? Maybe add a PR afterwards ;)

**Comment by EliasGabrielsson** [comment]
I like this idea a lot. I do think however that this should be added as an "openHAB UI" directly instead of through openhabian.

**Comment by mstormi** [comment]
Guys, @holgerfriedrich any opinion how to proceed ?

**Comment by mstormi** [comment]
Given our refocusing and availability of choices for MQTT clients on Windows and others, I'll close this.
