### ISSUE TITLE
Combine toolchain for RPi and for PineA64 to one with conditional actions.

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhabian#269]
The files for both images are mostly identical. For the next image release I plan to merge inside
https://github.com/openhab/openhabian/tree/master/build-rpi-raspbian and
https://github.com/openhab/openhabian/tree/master/build-pine64-image

**Comment by EliasGabrielsson** [comment]
Fixed in: https://github.com/openhab/openhabian/pull/358
