### ISSUE TITLE
New optional component frontail

### ISSUE THREAD

**Issue by jameshiscott** [openhab/openhabian#28]
I was wondering if it was possible to add the component: https://github.com/mthenw/frontail to the build, its a very nice light weight application for streaming logs to the browser. It's a tail -F with UI.

It makes keeping a log window open nice and easy and i dont need two SSH sessions open.

**Comment by ThomDietrich** [comment]
Oh I like that!
Already thought of some kind of a log interface but didn't know how... I'll have a look

**Comment by jameshiscott** [comment]
Yep, it's very cool and very lightweight. I run it on my pi as an additional step after using your image.

**Comment by ThomDietrich** [comment]
How about (additionally) http://rpi-experiences.blogspot.de/p/rpi-monitor.html

**Comment by jameshiscott** [comment]
Looks good as an additional optional add-on built into your menu. Not seen it before but tbh, for me,  the info in your SSH login info screen (uptime, CPU, etc) is just as good. 

Frontal is just a very nice stand alone log tail. It also works nicely with habpannel :)

**Comment by ThomDietrich** [comment]
Just saw that this depends on NodeJS :-/ Is there a minimal setup you would recommend?

**Comment by jameshiscott** [comment]
I find NodeJS is very light weight anyway but i just install it with the following: 

$ curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
$ sudo apt install nodejs

**Comment by kubawolanin** [comment]
I second frontail as a great tool for logs! I have latest NodeJS on my openHABian whatsoever - some of my rules depend on webscrapers that I wrote in JS.

Setting up frontail would require the following steps:
1. Install NodeJS like @jameshiscott mentioned
2. `npm i frontail -g`
3. Configure frontail to be launched on boot by either:
    * Using [forever](https://github.com/foreverjs/forever) and/or custom daemon script in `/etc/init.d/`
    * Modifying `/etc/rc.local` ?
4. Enable some basic configuration in `openhabian-config` (?) like:
    * theme `-t` (dark/default)
    * port `-p` (default - 9001)
    * custom openHAB logs highlight json file (?)

Here's an example usage:

    frontail -t dark -p 8889 --ui-highlight /var/log/openhab2/openhab.log /var/log/openhab2/events.log

I'll post an update with my custom script for `/etc/init.d/` here later.

**Comment by ThomDietrich** [comment]
Fantastic @kubawolanin
I'll implement as soon as you got it the script ready. I would vote to just use one theme+port combination. The user can still change this manually if this might actually be needed. What do you think? 
I would love to see a customized highlighting! Especially for Stack traces and status changes.

**Comment by kubawolanin** [comment]
Ok, I found easier and more convenient way to do it.

First, let's install all dependencies:

    curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
    sudo apt install nodejs
    npm i frontail -g
    
Then let's create a sevice (you will probably do `cp` or `mv` instead)

    cd /lib/systemd/system/
    sudo nano frontail.service

And here's the script:

    #!/bin/sh -

    [Unit]
    Description=Frontail
    
    [Service]
    ExecStart=/usr/bin/frontail --ui-highlight -t dark /var/log/openhab2/openhab.log /var/log/openhab2/events.log
    Restart=always
    User=pi
    Group=pi
    Environment=PATH=/usr/bin/
    Environment=NODE_ENV=production
    WorkingDirectory=/usr/bin/
    
    [Install]
    WantedBy=multi-user.target
    Alias=frontail.service

Keep in mind that in my case npm installed `frontail` in `/usr/bin/`
After it's saved, you need to make it executable + reload daemon:

    sudo chmod 644 /lib/systemd/system/frontail.service
    sudo systemctl daemon-reload
    sudo systemctl enable frontail.service
    sudo systemctl start frontail.service

Now there's a way to pass `--ui-highlight-preset <path>`  attribute, but couldn't make it working.
Here's my `preset.json`

```json
{
    "words": {
        "ERROR": "color: #E88D67;",
        "WARN": "color: yellow;",
        "INFO": "color: #99C5B5;",
        "Node is DEAD": "color: #E88D67;",
        "ItemStateChangedEvent": "font-weight: bold;"
    },
    "lines": {
        "ERROR": "font-weight: bold;"
    }
}
```

**Comment by jameshiscott** [comment]
Hi both, not sure if this helps or not as my knowledge level is very low (other than following snippets i find on google) @ThomDietrich obviously ignore this, if the method above works better with how you build openhabian but i simply do the following:

First, let's install all dependencies:
```
curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
sudo apt install nodejs
npm i frontail -g
```

I then just add the following into /etc/init.d/:

`sudo frontail /var/log/openhab2/openhab.log /var/log/openhab2/openhab.log /var/log/openhab2/events.log &`

However i like your highlight file @kubawolanin so may try including that.

**Comment by ThomDietrich** [comment]
Hi @jameshiscott, I di not ignore you or your suggestions. I simply returned from a two week india trip yesterday and didn't have the time to do anything ;)
I would however very much prefer the service approach. Sending a detached process into the background is a way to achieve what we are looking for but that is far from clean.
Did you (other than @kubawolanin) get the highlighting working? I'll probably have a look at the whole thing today or till the end of the week ;) Thank you both

**Comment by jameshiscott** [comment]
Hi @ThomDietrich no problem at all, didn't think you had ignored me in the slightest. Just trying to help in anyway I can (which is quite limited currently) but i am learning when I can.

Looking forward to being able to skip this manual install step. Hope you enjoyed India :)

**Comment by ThomDietrich** [comment]
Hey @jameshiscott, Hey @kubawolanin,
would one of you be interested in building a Pull Request? If you want to, just let me know, otherwise I'll look into this in the next 2-3 weeks.

**Comment by jameshiscott** [comment]
@ThomDietrich  I would love to, but my knowledge level on this sort of stuff is very low. I am not even sure how to build the solution to then test the changes. Wish I could help you out.

**Comment by LeDumpier** [comment]
@kubawolanin A huge thanks to you and the others for the information here. I implemented the commands described by you above and Voila, I could retrieve the logs. Nice indeed. As a beginner it means your steps are pretty much comprehensive.

I'm looking forward to seeing the setup option in the OpenHABian menu :) 

It would be useful to use in Habpanel UI for testing, i.e. to put up some switches, knobs, dummies etc and monitor the output in the same dashboard.

@jameshiscott , being I newbie I didn't quite get:

> 
I then just add the following into /etc/init.d/:

frontail /var/log/openhab2/openhab.log /var/log/openhab2/events.log &

> 

I need some babysitting on these things. Is that addig the command to any new file?

**Comment by ThomDietrich** [comment]
This is still on the todo list! Valuable feature indeed. I've been swamped with other things like the documentation for the openHAB 2 docs page. @LeDumpier this will start frontail on boot automatically. You might not even need it.

**Comment by tnemrap** [comment]
Is it possible to supress lines in Frontail like in grep -v "NIBE_Raw"?

**Comment by Lysolol** [comment]
Where do you put the preset.json file?

**Comment by ThomDietrich** [comment]
Hey @Lysolol, check out the Pull Request: https://github.com/openhab/openhabian/pull/118/files#diff-cdd86852ccd3c255a7233e741f26a137R460

The file is located at `/usr/lib/node_modules/frontail/preset/openhab.json`. Be sure to restart the frontail service before changes to the file take effect.

I have a request: If you add additions or improvements to the file, please provide them as a Pull Request or simply as a comment here for everyone to benefit from! ;)
