### ISSUE TITLE
Homegear won't install because list file points to Jessie repository

### ISSUE THREAD

**Issue by lfrancke** [openhab/openhabian#286]
When trying to install Homegear it fails on Openhabian 1.4 with these errors:

> The following packages have unmet dependencies:
 homegear : Depends: libgnutls-deb0-28 (>= 3.3.0) but it is not installable
            Depends: libmysqlclient18 (>= 5.5.24+dfsg-1) but it is not installable
            Depends: libssl1.0.0 (>= 1.0.1) but it is not installable
E: Unable to correct problems, you have held broken packages.

The problem seems to be in `/etc/apt/sources.list.d/homegear.list` which points to Jessie. Looks like this comes from here `https://github.com/openhab/openhabian/blob/master/functions/packages.sh` but I'm not too sure. Happy to submit a Pull Request to update that file but I'm not sure if you've fully migrated to Stretch or if there's still Jessie support in there.

I guess other list files also need to be updated for Stretch

**Comment by ThomDietrich** [comment]
Hello @lfrancke,

thanks for reporting the issue! You are absolutely right. I've tested most of the optional components on the new stretch system, it could be that I forgot about homegear -.-

A PR by you would be amazing! Yes you'd need to differentiate between different systems. Could you please add a `is_stretch` function here: https://github.com/openhab/openhabian/blob/master/functions/helpers.sh#L90
After that you may use it to insert either the Stretch or Jessie repo line. While looking at it, homegear provides packages for Debian, Ubuntu and Raspbian. I can't ask that of you but taking care of all of these would be amazing!

Best, Thomas

**Comment by Freelord94** [comment]
Good evening,

first project with openhabian and this problem^^
Is there a short solution or a fix which i can try over ssh?
May befor christmas would be cool ^^ :)

Best Johannes

**Comment by lfrancke** [comment]
Hi @Freelord94 

You should be able to do this once you've SSHed into the Raspberry:

```
sudo su
echo 'deb https://apt.homegear.eu/Raspbian/ stretch/' > /etc/apt/sources.list.d/homegear.list
apt -y install homegear homegear-homematicbidcos homegear-homematicwired
systemctl enable homegear.service
systemctl start homegear.service
adduser openhabian homegear
adduser openhab homegear
```

**Comment by lfrancke** [comment]
@ThomDietrich I did submit a Pull Request. I used a slightly different route than you suggested to avoid lots of nested if-then statements. Hope that works for you.

**Comment by Freelord94** [comment]
Thank you for the fast answer. 
I`ve set up a clean openhabian installation preparing some steps for the HM-...-PCB, do config and install java8. If i fill in the 3rd line "apt -y install homegear homegear-homematicbidcos homegear-homematicwired" the Pi is unable to find the packages, may the line befor won`t be effectiv.

**Comment by lfrancke** [comment]
You're right. I forgot an `apt update` command. I'm not a big Ubuntu/Debian user and always forget. Let me know if that works.

**Comment by Freelord94** [comment]
That is it. Thank you and merry christmas :)

**Comment by mbaehr2909** [comment]
Hi there, has this issue been integrated into the latest Update? I installed Openhabian yesterday from a newly downloaded image and it still seems to exist.

**Comment by ThomDietrich** [comment]
Not yet. I'm waiting on a formality :) See: https://github.com/openhab/openhabian/pull/297
