### ISSUE TITLE
Dashboard tile creation: Respect changed hostname

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhabian#287]
The hostname used in the dashboard tile configuration (`dashboard.cfg`) contains a fixed hostname in the URL entry. The hostname might be changed by the user at some point in time, making the link invalid.

1. Change the URL when changing the hostname
2. Look into the implementation of the dashboard or contact one of the original developers to support a `HOSTNAME` placeholder inside the `dashboard.cfg`.

Depends on a deeper issue: Currently the hostname is retrieved from the configuration file, that doesn't make much sense as the linux system knows it best. Replace or remove the configuration value.

**Workaround:** If you face the issue above right now, simply correct the hostname in the URLs configured in `/etc/openhab2/dashboard.cfg`

**Comment by ThomDietrich** [comment]
Good news! The needed change is implemented: https://github.com/openhab/openhab-core/pull/274
Bad news: It will be available with openHAB 2.3 (SNAPSHOT or stable)

**Comment by kubawolanin** [comment]
@ThomDietrich regarding the change in openhab-core you've mentioned - do you mean that all we have to do is to modify [this file](https://github.com/openhab/openhabian/blob/master/includes/dashboard-imagedata.sh) by replacing `$hostname` to `{HOSTNAME}`?
If so, let me create a PR  :-)

**Comment by ThomDietrich** [comment]
Jup that should be it 😄
