### ISSUE TITLE
Dashboard tile creation: Invalid dashboard.config if existing links present

### ISSUE THREAD

**Issue by ConfusedTA** [openhab/openhabian#288]
Hi,

I had previously manually edited my dashboard.config file to include links to Grafana and phpMyAdmin, and the contents of my file was as such:

```
grafana.link-imageurl="../static/grafana.png"
grafana.link-name="Grafana"
grafana.link-url="http://openhab:3000"
openhabiandocs.link-url="https://docs.openhab.org/installation/openhabian.html"
phpmyadmin.link-imageurl="../static/phpmyadmin.png"
phpmyadmin.link-name="phpMyAdmin"
phpmyadmin.link-url="http://server:8888/phpmyadmin"
service.pid="org.openhab.dashboard"
```

Following the recent update of the utility, it became slightly corrupted, the first line ended up something like this (not exact, I've corrected it since):

`grafana.link-imageurl="../static/grafana.pngopenhabiandocs.link-name"\openHABian Help\"`

This meant that both my Grafana and openHABian help items weren't present on the dashboard.

**Comment by ConfusedTA** [comment]
After restarts of OH it's corrupting itself again. Maybe it's pulling something from elsewhere when OH starts?

The first line is getting corrupted to:
`grafana.link-imageurl="../static/grafana.pngopenhabiandocs.link-name\=openHABian\ Help"`

**Comment by ThomDietrich** [comment]
Hello @ConfusedTA, I believe this happens because there is no newline at the end of your configuration file. I've fixed that in #292. However that wouldn't explain your example. Could you please do some testing and see if you can provoke the behavior again? Thanks!

**Comment by mstormi** [comment]
Hello @ConfusedTA 

is this still an issue? If no please close, thank you.

**Comment by mstormi** [comment]
pinging @ConfusedTA

**Comment by ConfusedTA** [comment]
I'll admit I've not looked back at this, sorry! I'll see about spinning up a new VM and try to replicate the original issue, but the changes made in #292 does sound like it might well be the fix!

**Comment by mstormi** [comment]
@ConfusedTA have you been able to validate this ?
Can I close this issue ?

**Comment by mstormi** [comment]
@ConfusedTA ping

**Comment by mstormi** [comment]
Ok, no feedback so I assume this is no longer an issue.
Reopen in case you encounter it again.
