### ISSUE TITLE
FireMotD -HV unknown

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#290]
this is on latest (dist-upgraded) openhabian. You get that warning, too when bashrc runs that command.
@ThomDietrich I guess you know best how to fix it

[17:52:10] openhabian@openHABianPi:~$  bash /opt/FireMotD/FireMotD -HV --theme gray
You specified a non-existant option: -HV
[18:02:05] root@openHABianPi:/home/pi# egrep -i 'firemot.*HV' ~openhabian/.??*
/home/openhabian/.bash_profile:  bash /opt/FireMotD/FireMotD -HV --theme gray
grep: /home/openhabian/.ssh: Is a directory
grep: /home/openhabian/.vim: Is a directory
[18:02:13] root@openHABianPi:/home/pi#

**Comment by ThomDietrich** [comment]
I know how to fix it. You just have to upgrade FireMotD (through openhabian-config). `-HV` is a new option not previously available.

The more interesting question is how did you end up in this situation and should be do something about that?

**Comment by mstormi** [comment]
Point is, I'm regularly doing apt dist-upgrade which is the same as doing it in openhabian-config, right?
And just did explicitly use the menu to upgrade (but guess what: nothing found to upgrade).
So FireMotD is latest version, still it doesn't know about -HV.
I noticed it isn't a Raspian package, so how is it supposed to be updated ?

[11:22:19] root@openHABianPi:/home/openhabian# ls -l   /opt/FireMotD/FireMotD ^C
[11:22:27] root@openHABianPi:/home/openhabian# head  /opt/FireMotD/FireMotD
#!/bin/bash
# Script name:  FireMotD
# Version:      v7.05.170509
# Created on:   10/02/2014
# Author:       Willem D'Haese
# Contributors: Gustavo Neves, Thomas Dietrich, Dmitry Romanenko
# Purpose:      Bash script that will dynamically generate a message
#               of they day for users logging in.
# On GitHub:    https://github.com/willemdh/FireMotD
# On OutsideIT: https://outsideit.net/FireMotD

**Comment by ThomDietrich** [comment]
No :D FireMotD is not installed as a package, hence it will not be affected by "Upgrade", which simply calls "apt upgrade". You'll need to execute the FireMotD function specifically.

Excellent discussion though. It seems like we should consider extending the "Upgrade" function. A normal user will expect it to upgrade openHAB just as well as FireMotD.
Additionally I'd like to add other changes to the basic routines. e.g. the following PR will not be available for existing users automatically. They would need to call one of the basic routines, which is illogical. #284

**Comment by mstormi** [comment]
Have you created an issue to remember ? (#284 is something different ?)
_Aber vor Mai Finger wech!_

**Comment by ThomDietrich** [comment]
No I did not. Feel free to create one.
And yes, I will not invest the time now. Would be great if you could step in!

**Comment by mstormi** [comment]
Fixed bymanual upgrade, general improvement to be applied via #293
