### ISSUE TITLE
Check if updates to FireModD are available when openhabian-config UPGRADE is executed.

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#293]
such as FireMotD

Would this work?
```
if [ -d /opt/FireMotD ]; then
    cd /opt/FireMotD
    git checkout
fi
```

Are there any other "non-package" openhabian components we need to think of ?

**Comment by ThomDietrich** [comment]
Checkout is not the right command. You need to use fetch or pull. Also you can get rid of the second line.

```
git -C /opt/FireMotD pull
```

However most of the installation routines I've developed is able to detect and update an existing component. I wonder if it would be easier and more complete to just call the FireMotD function.

Further components depends on how far you want to go. We could include the bash, vim, multitail, .... functions as well. That would be most effective. Only downside I can think of: Users might have added custom settings to those, we would need to detect that somehow...

@mstormi if you want to implement this we can start slow. Let's not get stuck in details. Would you like to open a PR for frontail?

**Comment by ThomDietrich** [comment]
Another idea! How about a [Checklist](https://en.wikibooks.org/wiki/Bash_Shell_Scripting/Whiptail#Check_list) where the user can select what he want's to upgrade? I like this idea a lot!

**Comment by EliasGabrielsson** [comment]
Specifying this to FireModD to easier track what issues covers. See individual issues for other components.

**Comment by mstormi** [comment]
We are rarely ever in need of a firemotd update as older versions work fine most of the time, too.
Users can trigger to reinstall via menu 15 if in need.
