### ISSUE TITLE
Homematic offline

### ISSUE THREAD

**Issue by Skysurfer-14** [openhab/openhabian#294]
On a fresh openhabian v1.4 installation on a Raspi 3 I installed the Homematic Binding and got the Homematic Things CCU2 and other Homematic components. After a few minutes the state of the Bridge CCU2 changes from ONLINE to OFFLINE because of communication problems.
Before with openhabian v1.3 it worked well.

**Comment by ThomDietrich** [comment]
Hello @Skysurfer-14,
this is probably not or not directly related to openHABian but the new openHAB version or the new Homematic binding version. Please create a thread in the openHAB community forum and mention `@gerrieg` in it. He'll be able to help you further.
