### ISSUE TITLE
Creating Let's Encrypt certificate... failed

### ISSUE THREAD

**Issue by arnoldpistorius** [openhab/openhabian#296]
Hi,

I wanted to activate the reverse proxy with Let's encrypt certificate, but it failed. The trace is included below. Do you have any idea how I can solve this?

```
Installing certbot...
Reading package lists...
Building dependency tree...
Reading state information...
certbot is already the newest version (0.10.2-1~bpo8+1).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
Creating Let's Encrypt certificate...
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.10.2', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 13, in <module>
    from acme import jose
  File "/usr/lib/python2.7/dist-packages/acme/jose/__init__.py", line 37, in <module>
    from acme.jose.interfaces import JSONDeSerializable
  File "/usr/lib/python2.7/dist-packages/acme/jose/interfaces.py", line 9, in <module>
    from acme.jose import util
  File "/usr/lib/python2.7/dist-packages/acme/jose/util.py", line 5, in <module>
    import OpenSSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 124, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
```

Thank you for your help and have a Merry Christmas :-)

**Comment by mais88** [comment]
I have the same issue here... Googeling for a solution right now... :-)

**Comment by mais88** [comment]
Just to be sure: I'm not an expert, so I can't guarantee this to work
but this is what made it work on my system:

'sudo apt-get install python-cffi libssl-dev
sudo python -m easy_install --upgrade pyOpenSSL
sudo openhabian-config'

-> Restart the nginx setup and follow instructions

Please feel free to try and give feedback :-)

**Comment by mais88** [comment]
@ThomDietrich 
Great job OpenHab developers, providing this cool functionality for ReverseProxy setup!!! 
Otherwise this would have been a lot of research and try and error for me :P

Probably the above issue is interesting for you?
In my case it was a fresh Openhabian 2.2.0 setup
on a raspberry pi 3.

Best regard's and a Happy New Year!
Marcel

**Comment by arnoldpistorius** [comment]
Hi Marcel,

I will give it a try tonight.

**Comment by ThomDietrich** [comment]
Hey guys. With Raspbian Stretch as the new base of this image, the error and the fix @mais88 presented are likely. @arnoldpistorius can you confirm it solved the problem?

**Comment by ThomDietrich** [comment]
The two commands above fixed it for me but the certificate creation by certbot still failed, my feeling is there was something wrong with the webroot configuration. Maybe that changed with a recent version of certbot? I'm currently in no position to dig deeper. @BClark09 could you run a test? Thanks!

**Comment by BClark09** [comment]
Sure thing! I've broken my testing Pi, but I'll try the script out on my home server and see what I can find!

**Comment by ThomDietrich** [comment]
@BClark09 another try today (I am setting up a new system and experiencing issues).
Today the process went through after just executing the two lines above prior to the Reverse Proxy function.
The whole process seems to be a bit wonky...
Random thought: Did you ever look into Caddy? Webserver that provides Let's encrypt and reverse proxy with a few simple commands.

**Comment by BClark09** [comment]
Sorry for the delay @ThomDietrich, I tested came across the same error and it appears to be Debian stretch related.

Could you confirm that the following fix works:

- changing `jessie-backports` to `stretch-backports`
- changing the install from `certbot` to `python-certbot-nginx` as indicated [here](https://certbot.eff.org/#debianstretch-nginx)
