### ISSUE TITLE
Tiles in openhab dashboard for previously installed services (like node-red)

### ISSUE THREAD

**Issue by dakipro** [openhab/openhabian#298]
Hi,
Very nice to see tiles added to the openhab dashboard for log viewer and node-red etc. It would be nice if there is an option (or is it?) to add existing services to dashboard, f.eks. node-red installed with previous version of openhabian. Is that possible?

Also, I re-installed log viewer now via config tool and log viewer is now added to the dashboard, which is great. (i assume node-red would be overwriten/reset if I do the same?) 
However, url to logviewer from dashboard is http://openhabiandevice:9001/ on my vanilla ubuntu installation. That fails, as there is no such server on my network, I access server via IP. Service itself runs fine on http://192.168.1.2:9001/ as before. 
Can we chose the link in the tiles? Or can we manually add tiles somehow?
Thanks for the awesome improvements!

**Comment by unparagoned** [comment]
I noticed this as well. 
I'm not sure if I should just rename my device to openhabiandevice since it may expect that name in future releases or just change the code to check hostname first. 

I've never fixed someone else's code on github before but I might try and give this a go.

**Comment by ThomDietrich** [comment]
Hey everyone, this is a known bug. Please see: #287

**Comment by dakipro** [comment]
Thanks @ThomDietrich , is there an issue/feature request for first part of the question maybe?
"It would be nice if there is an option (or is it?) to add existing services to dashboard, f.eks. node-red installed with previous version of openhabian. Is that possible?"

**Comment by ThomDietrich** [comment]
All openHABian routines are designed so they can be executed multiple times. The first execution would for example install a service, the second execution would update it. Run the node-red routine again and you should get the tile inserted.

**Comment by dakipro** [comment]
Thanks, that is awesome feature! 
I guess I missed it but it should be emphasized in the documentation (the tool itself), that it is "non-destructible"
Will run it right away :)
