### ISSUE TITLE
Deactivate power saving mode for Wifi in openHABian

### ISSUE THREAD

**Issue by binderth** [openhab/openhabian#299]
I had some issues with a binding, which was reliant on real-time information and with power saving mode active, I had some strange side effects. After some hours spending on the cause, I discovered, that deactivating power save mode, made all issues gone! ;)

**Comment by ThomDietrich** [comment]
Heyho Thomas! Could you add some details or links about how to do so and if this step has any known drawbacks!?

**Comment by binderth** [comment]
As openHABian uses Raspbian Stretch there was some changes to the configuration and also Wifi.
I didn't find something on how to configure the power saving mode via configuration. 
In the bash use:
`sudo iw wlan0 get power_save` (if wlan0 is your Wifi).

so I just added that line to my `rc.local` (without sudo) and it seems to work. I didn't find a config-file for this as in previous Raspbian distributions....

**Comment by mstormi** [comment]
@binderth would you mind and prepare a PR for current (buster) openHABian ?
I think the rationale is still valid.

**Comment by binderth** [comment]
@mstormi I would if I knew what to do. I'm no developer and not used to all this branching, PR and stuff...

**Comment by mstormi** [comment]
You don't have to be a developer. Neither am I. Setting up git/GitHub is an initial hurdle and something you have to do twice maybe to get used to it but it's not hard.
And we have enough time these days, so why not learn something new?
Give it a try
1) find the place inside the openhabian code where it's best placed, probably in the WiFi setup routine.
Code is on your box under /opt/openhabian/*. You can change it live to test if you dare. If you let openhabian-config update itself on start, it'll overwrite your changes.
2) see https://community.openhab.org/t/how-to-file-an-issue/68464 for the simple GitHub GUI way of editing and submitting the PR.

There's guides on Github how to setup Github and git, but in a nutshell:
1) git clone https://github.com/openhab/openhabian.git
2) cd openhabian
3) git checkout -b myrepo
4) (edit)
5) git add (changed files)
6) git commit -s -m "comment"
7) git remote add myrepo https://github.com/<mygithubuser>/openhabian.git
8) git push myrepo
(it'll output an URL where you can proceed with submitting the PR)

Good luck and don't give up too early.

**Comment by mstormi** [comment]
Cleaning up outstanding issues.
Please reopen if you have a contribution. to share.
