### ISSUE TITLE
opemHABian time sync

### ISSUE THREAD

**Issue by sysadmama** [openhab/openhabian#300]
Hi,

it is more a feature request than an issue: as far as I can see (and please correct me if I'm wrong) openHABian does not do any kind of time sync at all. This can (and did, in my case) cause weird system behaviour. That's why I'd like to suggest adding some kind of time synchronization like ntpd to the release.

Cheers,
  Marianne

**Comment by ThomDietrich** [comment]
Hey Marianne,
are you sure ntp is not working? It is part of the setup and my system seems okay:

![grafik](https://user-images.githubusercontent.com/2870104/34532006-bc1ab76a-f0b4-11e7-87c9-f880af7d80ab.png)

**Comment by sysadmama** [comment]
Hi Thomas,

huh, that's fascinating...
```
# systemctl status ntp.service
Unit ntp.service could not be found.
```

And even more:
````
# dpkg -l|grep ntp
#
````

Hmmmm. Have no idea at the moment. I'm pretty sure I didn't irritate the setup process manually ;) But for the moment, I can't reproduce setup, I am out of hardware. Perhaps a thing to keep in mind?

Cheers,
Marianne

**Comment by ThomDietrich** [comment]
Hey @sysadmama, I was able to reproduce the issue. Apparently a setup of the latest openHABian image (v1.4 based on Raspbian Stretch) suffers from it. We need to solve this issue.

Would you like to dig in and identify the solution?

**Comment by ThomDietrich** [comment]
Seems like stretch is shipped with a new service by default now. So even though it is not ntp, you should have a synced clock: https://wiki.archlinux.org/index.php/Systemd-timesyncd

**Comment by sysadmama** [comment]
Wow, you're absolutely right. I never heard of `systemd-timesyncd` and... okay, it seems to be the new standard, so why *mimimi*? ;) Thanks for your help, I'll close my issue now.

Cheers,
  Marianne

````
# timedatectl status
      Local time: Sun 2018-01-21 21:48:53 CET
  Universal time: Sun 2018-01-21 20:48:53 UTC
        RTC time: n/a
       Time zone: Europe/Berlin (CET, +0100)
 Network time on: yes
NTP synchronized: yes
 RTC in local TZ: no
````
