### ISSUE TITLE
raspi-config should catch return value when modifying files

### ISSUE THREAD

**Issue by sysadmama** [openhab/openhabian#301]
Hi,

I'm using a Raspberry Pi Noir V2.1 camera on my freshly installed openHABian-1.4. Today I was about to integrate it into my setup as I noticed the following:

`raspi-config` will modify `/boot/config.txt` in order to make the camera working. But it does not check whether file modified successfully; it just does its magic, reports absolutely no errors, recommends a reboot - and the whole system state is unchanged.

My request is to change this behaviour; it should catch the return value when modifying config and show up errors when they occur.

Some background: I forgot that in my setup the whole `/boot` partition is ro to take care of the SD card (all other partitions are located on an external hard disk), so the file wasn't writable at all.

Cheers,
  Marianne

**Comment by ThomDietrich** [comment]
Hey,
we are not the developers of raspi-config. In fact raspi-config should not be preent on an openHABian system to begin with. I've opened #289 for that.

As for your problem: My best advice would be to do the preparation manually: https://github.com/RPi-Distro/raspi-config/blob/master/raspi-config#L1136

**Comment by mstormi** [comment]
raspi-config meanwhile got removed and I think a camera hat is no longer in line with the range of HW we want to support in openHABian so I'll close this.

best regards,
Markus
