### ISSUE TITLE
[downloading openHABian] openHABian not listed on openhab download page

### ISSUE THREAD

**Issue by bgilmer77** [openhab/openhabian#303]
openHABIAN is not easy for NOOBS to find if they come to the project through the website "front door" at www.openhab.org.  openHABIAN is not on the openHAB [download page](https://openhab.org/downloads.html).

I would suggest adding a link on the download page and would ask @ThomDietrich to suggest an appropriate article to link to.

**Comment by ThomDietrich** [comment]
Hey @bgilmer77, as per the other discussion I thought you wanted to discuss ways to improve the process of onboarding AFTER the user found the instructions over at http://docs.openhab.org/installation/openhabian.html

How to get there is a task for the documentation/webpage project.

**Comment by bgilmer77** [comment]
You are correct - but I was trying to keep it simple to start with.  Please just set the direction and we can tackle the issue.  Generally, I think it is extremely important to improve the onboarding process for NOOBS.  The number of posts in the community that start out, "I am giving up on OH" is way to high, and we are the team that can help with this.

**Comment by ThomDietrich** [comment]
I wouldn't overdramatize. openHABian seems to succeed for most users who simply follow the instructions,both the instructions and all failsafe steps I've introduced should take care of the whole onboarding problem.

Now your issue in the other thread was the fact that the images are provided in the compressed xz format. The reason for that is simple: The image size shrinks significantly and etcher can directly work with it. If you don't want to use etcher you can extract the image.
What's your opinion about that?
