### ISSUE TITLE
Fronttail installation fails to due new paths

### ISSUE THREAD

**Issue by mhaack** [openhab/openhabian#304]
With change  https://github.com/mthenw/frontail/commit/6cf8a3391f7ca5cf370dcf4a7ffe0eccff584936 the `frontail_setup()` function fails due to changed folders for frontail preset and css location.

**Comment by Govna5** [comment]
Im having somewhat the same issue, but also just installed openHab last night and working through getting it set up.  I was able to successfully install frontail outside of `sudo openhab-config` settings on Rpi B+ with `sudo npm i -g frontail` but when i try to update it from `sudo openhab-config`, it fails indicating there is no file or directory.

Even though frontail installed for me, the log viewer tile doesn't work on the openHab UI, indicates the site cant be reached.

**Comment by ThomDietrich** [comment]
Hey @mhaack 👋 thanks for reporting the error and researching the cause. Would like to / are you able to submit a pull request with the fix?

**Comment by mhaack** [comment]
Yes I will provide a PR, got it workings manually last night. The main issues is that the preset is not found which makes frontail fail starting.

**Comment by TouchRu** [comment]
Hi! May be need to remove "lib/" in destination path in https://github.com/openhab/openhabian/blob/master/functions/nodejs-apps.sh#L36

**Comment by mhaack** [comment]
Created PR #306

**Comment by ThomDietrich** [comment]
Everyone, Thanks to Markus's fix it should now work once again. Just update, then execute the frontail installation routine
