### ISSUE TITLE
[Feature] Installing iputils-arping to fully support binding-network.

### ISSUE THREAD

**Issue by EliasGabrielsson** [openhab/openhabian#307]
The [network binding](https://github.com/openhab/openhab2-addons/tree/master/addons/binding/org.openhab.binding.network) in openhab enables presence detection for devices. 

In the latest release it have been updated to utilize arp-ping as well as DHCP packets. `arping` is not installed as default and I don't know if openhab have permission to bind to port 67 (DHCP). 
I think we should at least give the option to install and configure permission for this.
I would prefer support out of the box.

**Comment by BrutalBirdie** [comment]
Good Idea.

**Comment by gelsas** [comment]
Just found this, could anyone guide me on what to install on my openhabian pi so arp ping works with the network binding. A tutorial would be nice (if possible)

**Comment by BrutalBirdie** [comment]
Ehm..?
sudo apt-get install arping

**Comment by EliasGabrielsson** [comment]
The readme of the [network binding](https://github.com/openhab/openhab2-addons/tree/master/addons/binding/org.openhab.binding.network#arping) explains this: `apt-get install iputils-arping`

**Comment by BrutalBirdie** [comment]
`pi@openhab:~ $ apt search arping                                                                                 [17/17]
Sorting... Done
Full Text Search... Done
arping/stable 2.14-1 armhf
  sends IP and/or ARP pings (to the MAC address)`

**Comment by EliasGabrielsson** [comment]
closed by pull request 311
https://github.com/openhab/openhabian/pull/311

**Comment by rzwarts74** [comment]
Any suggestions on getting this to work on Mac OSX? I installed arping manually using homebrew. Put in the same folder as OpenHab ../runtime/bin/. and gave /dev/bpf0 777 rights. It works from commandline... but OpenHAB doesn't use it...

**Comment by ThomDietrich** [comment]
Please consult the openHAB community forum with this question. Good luck!
