### ISSUE TITLE
System binding need 32-bit patch on PINE64 platform 

### ISSUE THREAD

**Issue by EliasGabrielsson** [openhab/openhabian#310]
### Symptom

Currently the system binding will throw errors regarding `udev` because of missing 32 bit library on PINE64.

### Fix

Apply the fix described in [this post](https://community.openhab.org/t/systeminfo-initialization-error-on-pine64/11726/9) for pine64. This will maybe be fixed upstream later on so put it in a special "fix function" for easy removal later on.

**Comment by EliasGabrielsson** [comment]
Closed by pull request 311.
https://github.com/openhab/openhabian/pull/311

**Comment by ThomDietrich** [comment]
This is sadly not the first fix for the pine64: https://github.com/openhab/openhabian/blob/master/functions/system.sh#L220
