### ISSUE TITLE
openHABian should have write access in /srv root

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhabian#312]
```
chmod g+w /srv
```

**Comment by mues-lee** [comment]
based on test build `openhabianpi-raspbian-201803301036-gitccab172-crc2ebd058f.img.xz` this is already the case:

`[16:44:48] openhabian@openHABianPi:~$ ls -l / | grep srv`
`drwxr-xr-x   7 openhab openhabian  4096 Mar 30 14:42 srv`

**Comment by ThomDietrich** [comment]
Good to know. I wonder when this changed.

Btw. openHABian comes with the `ll` alias ;)
