### ISSUE TITLE
Reverse proxy on port 80 as default component

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhabian#313]
The nginx reverse proxy is currently missing in the optional components menu

**Comment by ThomDietrich** [comment]
A good point. There was another issue or at least the idea once before. I would like to continue with what @mues-lee did with his WebIF. After the webif is closed it would be nice to see an nginx process transparently redirecting from port 80 to 8080. When the user chooses to activate authentication, it is just "added". @BClark09 wdyt? I'm still not in the position to get back in the game :(

**Comment by mstormi** [comment]
any news ? Still an issue ?

**Comment by ThomDietrich** [comment]
This would be an excellent addition. There are many ways to solve this but a permanent redirect on port 80 with optional port 443 access would increase usability a lot.

**Comment by mstormi** [comment]
OH3 is gonna include authentication
but let's leave this open until then

**Comment by mstormi** [comment]
Just a thought: we already have the webserver running that displays `boot.log` during installation.
Wouldn't it make more sense to send a redirect to the dashboard (port 8080) when install has finished rather than to start/config nginx for just that purpose?

**Comment by mstormi** [comment]
cc: @EliasGabrielsson @holgerfriedrich

I just installed a box and when it finished, the log display was removed and the webserver provided a link to the dashboard.
Isn't that what's the intention here ?
(okay, we could also trigger a redirect after 10 seconds, but other than that?)
