### ISSUE TITLE
Frontail service: exchange user

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhabian#316]
Related to https://github.com/openhab/openhab-linuxpkg/issues/108
Turns out using the user `openhab` as the user for the frontail service was a bad idea. We should switch to one of the default system users. @mhaack what do you think?

CC @BClark09

**Comment by mhaack** [comment]
@ThomDietrich I have no strong opinion on that. It might help to mitigate https://github.com/openhab/openhab-linuxpkg/issues/108, but other components like homegear or node red also run with the `openhab` user. There is no guarantee to solve that.

**Comment by mstormi** [comment]
still relevant ? If no please close.

**Comment by ThomDietrich** [comment]
@BClark09 what's the latest on the openHAB side of things?

**Comment by mstormi** [comment]
pinging @BClark09

**Comment by mstormi** [comment]
@BClark09 openhab user still in use.
What about making frontail PartOf=openhab2.service in systemd ?

**Comment by BClark09** [comment]
Sorry, I've let this slip. I agree that using the `openhab` user might not be the best approach for services that aren't directly associated with `openhab`. The easiest fix, and one I really should have implemented a long time a go is the one we discuss in   openhab/openhab-linuxpkg#108

**Comment by mstormi** [comment]
> , but I'm not sure having a list of overrides in different systemd files is very maintainable.

Well that just applies to openHABian, and for anything not-openhab2 that's no packages you would need to fiddle tohat into but just files we place during installation anyway, or am I wrong there ?
And is there more than frontail.service ?

**Comment by mstormi** [comment]
@BClark09 does closing openhab/openhab-linuxpkg#108 mean this now works and I can close it, too?

**Comment by BClark09** [comment]
The issue fixed in linuxpkg was about the errors caused when another service uses the `openhab` user. 

Ideally, these services should use a default or new user to manage their permissions. So there is still something to improve on openHABian's end I think.

**Comment by ecdye** [comment]
If I understand this correctly. What you are saying is that we should use a new user for frontail perhaps even just a new user called frontail? 

If so then it should be an easy fix right?

**Comment by mstormi** [comment]
That's how I, too, understood it. just go for it

**Comment by mstormi** [comment]
upps, wrong button
