### ISSUE TITLE
[grafana] Missing icons in Web UI on Pine64

### ISSUE THREAD

**Issue by robbyb67** [openhab/openhabian#319]
On a Pine64 the installed grafana package misses important icons in the web UI. The web UI, especially the query editor, is unusable.
Maybe this is linked to this issue: https://github.com/grafana/grafana/issues/4712

**Comment by EliasGabrielsson** [comment]
Probably upstream error which have been patched. If error still persist on new installations feel free to reopen @robbyb67 and we will have another look at it.
