### ISSUE TITLE
Reproducable kernel panic on Raspberry Pi 3

### ISSUE THREAD

**Issue by sysadmama** [openhab/openhabian#320]
Hi Thomas and all,

I'm writing this issue, but I'm unsure if this is the right place. It's the (temporary) end of weeks of debugging. I'll try to make it short:

My Raspberry Pi 3 running openHAB 2 under last openHABian crashes with kernel panic (frozen, only hard resetting helps). This behaviour is reproducible: crashing occurs when system is on (even short timed) high load (every morning when running cron jobs par example).

I tested with `stress -c $NUMCPU -t 900s`
* NUMCPU 1 or 2 - everything is fine
* NUMCPU 3: it crashes mostly near the end, in rare circumstances this test proceeds
* With 4 cores: it crashes within the first two minutes

Before final crashing, openHAB 2 begins to reload/ re-initialize. But in `openhablog`, there's no *reason* logged *why* it reloads - in fact I was not able to find a notice in *any* of the logs. It just does, and then the whole system crashes with a `java Not Tainted`.

I hardly tested PSU and voltage, disk and SD card and so on. But my hardware is okay, I'm sure. When I stop the openhab2 process, I can succeed `stress -c 4 -t 1800s` without any problems. It seems the openhab2 process (or *any* kind of Java process?) the culprit. It's some kind of kernel bug? Java bug? openHAB 2 bug? 

I'll attach the kernel panic, but I'm sorry, it's just a photo. The bad is that this **always** happens when load is above, let's say 2.6, and not only on stress tests. So I have lots of unexpected crashes and a system which I consider to be *"not stable"*.

Anyone else ran into that issue? Anything else I could provide to help debug this?

Thank you very much in advance!

Cheers,
  Marianne

Some system specs:

My `uname`:
```
# uname -a
Linux openHABianPi 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux
````

Version:
````
# vcgencmd version
Oct 24 2017 17:09:22
Copyright (c) 2012 Broadcom
version a3d7660e6749e75e2c4ce4d377846abd3b3be283 (clean) (release)
````

openHAB 2: `openhab2-2.2.0-1`
Java: `openjdk version "1.8.0_152" build 1.8.0_152-b76`

Photo of kernel panic:
![img_2011](https://user-images.githubusercontent.com/11242139/35198417-f269fba8-feee-11e7-9428-637e80f4f867.JPG)

**Comment by MarcusWolschon** [comment]
just for completeness, what is the rating of your power supply?
Is the Raspberry providing power for any other devices (e.g. usb devices, hats, displays,...)?

**Comment by sysadmama** [comment]
Uh, I'm sorry I forgot to mention it...

* PSU is 5V 2.5A
* I had a Pi Noir Camera connected, but I disconnected it; it makes no difference, same behaviour
* I use an external SSD via USB, it's connected to an active USB hub
* no other devices
* I wrote a script that monitors the value of `vcgencmd get_throttled`, and the host never reports under voltage

Hope that helps :) 

Cheers,
  Marianne

**Comment by ThomDietrich** [comment]
Hey @sysadmama, I've done the 4 core stress test on two RPi3 for over half an hour, no issues on my side... Can't really say what's up but this issue seems to be related to your setup or your unique device. Sorry I can't say more :-/

**Comment by sysadmama** [comment]
Huh @ThomDietrich, that's weird.
I'll try to borrow another RPi3. I'll ping you again if this strange behaviour persists in other environment ;)

Cheers,
  Marianne

**Comment by ThomDietrich** [comment]
Hey Marianne!
Just out of curiosity, any news on your situation?

**Comment by sysadmama** [comment]
Uhm - yes. I was not able to borrow a Raspberry, but I got an UpBoard - that's where I moved my huge installation to ;) On the Raspberry, there's now only a small test installation with a not too big number of items left, so everything runs fine (when the load is too high, the Raspberry still crashes). Perhaps the hardware, indeed...
