### ISSUE TITLE
knxd versions newer than 0.14.19-2 do not start at boot

### ISSUE THREAD

**Issue by guiott** [openhab/openhabian#321]
The knx daemon, installed with the openhabian-config script should start automatically at boot using systemd
The default parameters suggested at installation (KNXD_OPTIONS="–eibaddr=1.1.128 --client-addrs=1.1.129:8 -d -D -T -R -S -i --listen-local=/tmp/knx -b tpuarts:/dev/ttyAMA0") was good until version 0.14.19-2 of knxd-
As explained on knxd github the “-d” parameter is needed to demonize the program when launched manually from cli, so it’s redundant when launched by systemctl, but was “tollerated” until that version.
Using that parameter, starting from version 0.14.22, causes the program to quit immediately with exit code [0]Success, even if it is still good using the cli.
It must be removed manually editing /etc/default/knxd.
The correction must be repeated if you reinstall knxd (now at version 0.14.23) because openhabian-config installation repropose the same configuration file.

**Comment by ThomDietrich** [comment]
Hello @guiott, thanks for the info! Would you like to contribute a PR?  
What do you think about replacing the used installation script as discussed in #85?

**Comment by guiott** [comment]
Hi Thomas,

I’m not good on writing scripts but I’m a good tester, I install often OpenHAB and knxd on the board we developed (https://www.acmesystems.it/CM3-HOME <https://www.acmesystems.it/CM3-HOME>). The openhabian installation script is very useful because otherwise the installation is very complicated.
I’m going to test the suggested script ASAP and I’ll give my personal opinion.

ciao
Guido

**Comment by ThomDietrich** [comment]
That would already be a big help! Thanks!

I know your CM3-Home and it's a great product! Happy to see that you are using openHABian with it! I'd be happy to discuss further integration of available hardware and setup steps in openHABian! At some point we could also mention the CM3-Home as an openHAB(ian)-ready product in our documentation

**Comment by guiott** [comment]
GREAT! 
I’d be happy to. 
I’m working a lot on OpenHabian, trying to integrate all the devices I always desired to use in my home. Which way can be better than testing your own product in your own, real environment?

All the devices/configurations/services I’ve used are documented on this article series:
http://www.tanzolab.it/openhab_gettingstarted

I was still waiting to share the link because the articles are not yet be all translated in English, I’m working on that, but I’m quicker on adding functions than on translating :-) 
It’s just a collection of info gathered around, but I hope it can be helpful for someone. Those are all really practical, working configurations done starting from the, sometimes, too theoretical instructions and tutorials available. I have had a big help from all the participants on the forum and I want to give back something to thanks all of you for a so beautiful product and community.

**Comment by guiott** [comment]
Hi Thomas,

I eventually tried to install knxd on a fresh installation of openhabian using the Mauro Ferratello script following this instructions:

https://github.com/ferratello/knxd_installer <https://github.com/ferratello/knxd_installer>

first of all to the setup instructions must be added:

sudo chmod +x knxd_install.sh 

then, the script fails with this result:

dpkg-buildpackage: info: source package pthsem
dpkg-buildpackage: info: source version 2.0.8
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Martin Koegler <mkoegler@auto.tuwien.ac.at>
dpkg-buildpackage: info: host architecture armhf
 dpkg-source --before-build pthsem-2.0.8
dpkg-checkbuilddeps: error: Unmet build dependencies: cdbs
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
dpkg: error: cannot access archive 'libpthsem*.deb': No such file or directory
Branch stable set up to track remote branch stable from origin.
Switched to a new branch 'stable'
dpkg-buildpackage: info: source package knxd
dpkg-buildpackage: info: source version 0.14.24-3
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Matthias Urlichs <matthias@urlichs.de>
dpkg-buildpackage: info: host architecture armhf
 dpkg-source --before-build knxd
dpkg-checkbuilddeps: error: Unmet build dependencies: libusb-1.0-0-dev (>= 1.0.9) libsystemd-dev (>= 228) | libsystemd-daemon-dev (>= 200) | base-files (<< 8) libev-dev libfmt-dev | libfmt3-dev | cmake (>= 2.8.12)
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
dpkg: error: cannot access archive 'knxd_*.deb': No such file or directory

**Comment by EliasGabrielsson** [comment]
Closing this for having clean issue log.
Track progress in: https://github.com/openhab/openhabian/issues/651
