### ISSUE TITLE
[security] Java keystore is using default password

### ISSUE THREAD

**Issue by EliasGabrielsson** [openhab/openhabian#323]
## Problem
The installed JVM all have an keystore for manage certificates.
This keystore file can for example be found in: `/usr/lib/jvm/zulu-embedded-8-armhf/jre/lib/security/cacerts` for Zulu embedded java. The keystore is using the default password:`changeit`.

## Possible solution:
1. On installation generate a random password to replace `changeit`.
2. Give the option to change the keystore password in the "change password menu".

## Example

```
keytool -list -v -keystore usr/lib/jvm/zulu-embedded-8-armhf/jre/lib/security/cacerts
```

**Comment by ThomDietrich** [comment]
Hey @EliasGabrielsson 👋 
Excuse my ignorance but could you enlighten me why we would actually need to change/set it?

**Comment by EliasGabrielsson** [comment]
I would definitely say this is a *minor* one but when security issues is used together they can form an attack vector.

Anyhow, if you have the password you could add trusted CA certificate (eg. self-signed) and therefor impersonate a host or service. In my case I have an external influxDB server running on a NAS. The influxDB server uses a certificate to encrypt communication with HTTPS to my openhab host. The JVM uses the truststore for ensuring a valid cert. If a program have access to the truststore it can add a cert and become man-in-the-middle between for example my openhab host and influxDB.

Of course is this needed to be combined with other means but its another puzzle piece to hack a host.

**Comment by ThomDietrich** [comment]
As I thought.

Imho this is a very special problem and I'm not sure if we want to "solve" it in openHABian.

If you feel strongly about it and want to do something here we could talk about changing it in combination with the user password. This would give the user a certain traceability in case he actually want's to access the keystore.

**Comment by robbyb67** [comment]
Maybe this and #327 could be handled in some "hardening script". Both issues are relevant on systems which are exposed directly to a network router that has no or unsufficient  firewall capabilities.

**Comment by ThomDietrich** [comment]
Hardening the network settings because of special network conditions should stay the task of the individual user. I'm not sure if openHABian should include such an option. We could just as well propose this for Raspbian and see how it goes ;)

**Comment by EliasGabrielsson** [comment]
Closing this as there are doubtful security gains on actually changing the password. Better to put effort of maintaining code onto something else
