### ISSUE TITLE
[security] When nginx auth is enabled the openhab instance is still accessible on default port

### ISSUE THREAD

**Issue by EliasGabrielsson** [openhab/openhabian#327]
## Symptom
When enabling nginx with username and password it's set up on port 80/443 for HTTP/HTTPS. The default port for openhab in my case :8080 could still be used like before.

## Expected
Openhab shall only be accessed on port 80 or 443 (HTTP / HTTPS)

**Comment by ThomDietrich** [comment]
When working on the whole feature I was not sure if this is desired by every user.
However I am willing to discuss improvements here

* A user might not want to authenticate locally (can be configured as an exception in nginx)
* I was thinking about making 80/443 the default port for all openHABian installations to begin with
* Additional Security: It might be desired to block certain areas for users outside the local network, e.g. Paper UI or certain sitemaps

Wdyt?
CC @BClark09

**Comment by BClark09** [comment]
I agree it would helpful to have an additional question asking the user if they want to prevent external access on port `OPENHAB_HTTP_PORT` and `OPENHAB_HTTPS_PORT` after a successful setup of nginx.

Specifying "yes" to the above could set `OPENHAB_HTTP_ADDRESS=127.0.0.1` in `/etc/defaults/openhab2`

> 80/443 the default port for all openHABian installations

I like the idea, but wouldn't this make openHAB a root instance? Also, do you think many users will find the docs which usually specify 8080 as confusing?

**Comment by ThomDietrich** [comment]
Both good points. How about a default nginx redirect with minimal settings

**Comment by mstormi** [comment]
With all issues to reference this already closed and 2 yrs later I think we should close this, too.
More changes to come with OH3 to include authentication so we will be able to omit nginx some day.
