### ISSUE TITLE
openhab-generator command not found

### ISSUE THREAD

**Issue by Confectrician** [openhab/openhabian#329]
Moved from openhab/openhab-docs#641
Original Issue was made by: @michaelrice 

> Following this: https://docs.openhab.org/installation/openhabian.html#what-next it says
>
>After your first setup is done, you might want to generate Items, Sitemap and HABPanel dashboard for your home. Simply log in to your Raspberry PI with SSH and type openhab-generator.
>
>But using Version: 2.2.0 (Build) you get openhab-generator: command not found

Seems that somethings missing here.

**Comment by EliasGabrielsson** [comment]
I think that the documentation has a typo. The generator is currently an optional component and can be found as `22 - openHAB Generator` in submenu `20 - Optional components`

**Comment by ThomDietrich** [comment]
Most importantly: We can remove this component. It's the successor to the now openHAB 2.2 available Home Builder. cc @kubawolanin 

@EliasGabrielsson would you do us the honors?

**Comment by Confectrician** [comment]
So we can remove it in the docs too then?

**Comment by ThomDietrich** [comment]
From script and documentation yes. However the openhabian.md article is copied over from here so you don't have to do anything in the openhab-docs repo.

Regarding the quote from above: We can mention the Home Builder instead of the generator there.

**Comment by EliasGabrielsson** [comment]
I can look into this when fixing all other stuff. But I guess we live nodejs right, is it used by other components?

**Comment by ThomDietrich** [comment]
👍 Yes, currently for frontail and nodered but i expect further projects to join at some point.
