### ISSUE TITLE
Improve hardware detection for more boards

### ISSUE THREAD

**Issue by EliasGabrielsson** [openhab/openhabian#333]
There is a need of improving for PIN64. Currently scripts only trigger when using exact the base image openhabian uses. 

There is a great detection script here: https://github.com/leonsio/arm-board-detect.

I suggest if this script is implemented to also make an compatibility chart which points out which boards is tested and works. Long-term HW boards will come and go so its great to have a framework for supporting them. Maybe assign maintainer and tester for each board as well so each new release have at least been installed from ground up for each board type.

**Comment by EliasGabrielsson** [comment]
https://github.com/openhab/openhabian/pull/309

**Comment by ThomDietrich** [comment]
That's an important point. Let's also mention @leonsio here.

One question arising for me: How do we want to include it. Because of the need to use these functions right from the beginning we might need to hard-include it as a copy.

@leonsio the detection for the Pine model can be done even better, see my PR here:
https://github.com/OutsideIT/FireMotD/pull/35
Feel free to use it.

**Comment by EliasGabrielsson** [comment]
I maybe misunderstand this but doesn't the linked patch have the same problem as in this repository that the board detection is based in iamge. Eg.  `elif [[ $(uname -r) =~ "pine64-longsleep" ]] ; then` assumes that the image is longsleep.

My output of `uname -r` on the PINE64 using another base image  produces: `3.10.105-bsp-1.2-ayufan-118`. This was the problem referred to in first post but not written out.

@leonsio script does use processor info and is unrelated to installed kernel.

**Comment by leonsio** [comment]
the best way to detect SoC is to use the information from device-tree/model or ( if not present ) to detect Soc based on some hardware specification. 

for example CPU architecture or hardware string in /proc/cpuinfo

the biggest problem is to identify the correct board, if many boards uses the same chipset. for example Allwinner A64 is used on this boards

-  Azpen hybrx
-   FriendlyARM NanoPi A64
-   Olimex A64-OLinuXino
-   Pine64
-   Sinovoip Banana Pi M64
-   Xunlong Orange Pi Win

in this case you need some more unique specifications to detect the right hardware like RAM/ethernet/soundchips or other

The kernel string can be set to anything

**Comment by EliasGabrielsson** [comment]
Closing this as effort goes into export relevant installation scripts to the Armbian Project.
