### ISSUE TITLE
Add (isolated) hotspot configuration option

### ISSUE THREAD

**Issue by shabbab** [openhab/openhabian#336]
Would be nice if there was an option in openhabian-config to set up a local hotspot.
That is the Raspberry Pi should offer a hotspot that we can use to connect sensors and gateways to. This hotspot should have the option of being isolated from the wired ethernet that is used to connect Openhab to the outside. 

This is to make sure the cheap chinese gadgets don't send all my data to china (I'd like to keep these gadgets separated from my main Wifi network).

**Comment by ThomDietrich** [comment]
Sounds useful for some. Would you be able to provide a PR for the feature?

**Comment by shabbab** [comment]
Maybe I should have added that I have not much clue about this. I can follow guides and dig my way around, but not much more. 

Trial and error led me to this guide, which works on recent openhabian:
https://github.com/SurferTim/documentation/blob/6bc583965254fa292a470990c40b145f553f6b34/configuration/wireless/access-point.md

**Comment by mstormi** [comment]
This is a somewhat tempting idea albeit I don't see much potential (not many to use this) but a lot of potential usage and implementation problems as most will have have another WiFi on their router.
Either way, here's no update in 2yrs and in the light of refocusing (not to add new features) I'll close this. You can reopen when there's substantial news.
