### ISSUE TITLE
Within initial setup process the system hangs in an invinite loop Started openHAB 2 - Stopped openHAB 2

### ISSUE THREAD

**Issue by Kamayaka** [openhab/openhabian#339]
Hi,

i downloaded the newest openhabian image https://bintray.com/openhab/bin/download_file?file_path=openhabianpi-raspbian-201712171718-git30faec3-crccc053823.img.xz.
Imagte was burned using Etcher on a 2GB SD Card.
After inserting the sd card the system the initial startup begins does dozen of things which finally leads to an invinite loop logging Started OpenHAB 2, Stopped OpenHAB 2.

An idea concerning this issue?

- 2017-11-29_02:37:22_UTC [openHABian] Starting the openHABian initial setup.
- 2017-11-29_02:37:22_UTC [openHABian] Storing configuration... OK
- 2017-11-29_02:37:22_UTC [openHABian] Changing default username and password... OK
- 2017-11-29_02:37:24_UTC [openHABian] Setting up Ethernet connection... OK
- 2017-11-29_02:37:24_UTC [openHABian] Ensuring network connectivity... OK
- 2017-11-29_02:37:24_UTC [openHABian] Waiting for dpkg/apt to get ready... OK
- 2017-11-29_02:37:56_UTC [openHABian] Updating repositories and upgrading installed packages... OK
- 2018-02-16_18:45:17_UTC [openHABian] Installing git package... OK
- 2018-02-16_18:45:55_UTC [openHABian] Cloning myself... OK
- 2018-02-16_18:46:04_UTC [openHABian] Executing 'openhabian-setup.sh unattended'... 
- 2018-02-16_18:46:04_UTC [openHABian] Checking for root privileges... OK
- 2018-02-16_18:46:04_UTC [openHABian] Loading configuration file '/etc/openhabian.conf'... OK
- 2018-02-16_18:46:04_UTC [openHABian] Setting timezone based on IP geolocation... OK (Europe/Berlin)
- 2018-02-16_19:47:47_CET [openHABian] Setting locale based on openhabian.conf... OK
- 2018-02-16_19:48:21_CET [openHABian] Setting hostname of the base system... OK
- 2018-02-16_19:48:22_CET [openHABian] Setting the GPU memory split down to 16MB for headless system... OK
- 2018-02-16_19:48:22_CET [openHABian] Enabling Audio output... OK
- 2018-02-16_19:48:22_CET [openHABian] Installing basic can't-be-wrong packages (screen, vim, ...)... OK
- 2018-02-16_19:50:14_CET [openHABian] Installing additional needed packages... OK
- 2018-02-16_19:50:52_CET [openHABian] Installing additional bluetooth packages... OK
- 2018-02-16_19:51:01_CET [openHABian] Adding slightly tuned bash config files to system... OK
- 2018-02-16_19:51:01_CET [openHABian] Adding slightly tuned vim config file to system... OK
- 2018-02-16_19:51:01_CET [openHABian] Downloading and setting up FireMotD... OK
- 2018-02-16_19:51:43_CET [openHABian] Installing Zulu Embedded OpenJDK... OK
- 2018-02-16_19:54:00_CET [openHABian] Installing or upgrading to latest openHAB release (stable)... OK
- 2018-02-16_19:56:05_CET [openHABian] Adding an openHAB dashboard tile for 'openhabiandocs'... OK
- 2018-02-16_19:56:05_CET [openHABian] Adding openHAB syntax to vim editor... OK
- 2018-02-16_19:56:06_CET [openHABian] Adding openHAB syntax to nano editor... OK
- 2018-02-16_19:56:06_CET [openHABian] Adding openHAB scheme to mulitail... OK
- 2018-02-16_19:56:07_CET [openHABian] Preparing openHAB folder mounts under /srv/... OK
- 2018-02-16_19:56:08_CET [openHABian] Applying file permissions recommendations... OK
- 2018-02-16_19:56:10_CET [openHABian] Applying miscellaneous system settings... OK
- 2018-02-16_19:56:10_CET [openHABian] Setting up Samba network shares... OK
- 2018-02-16_19:57:44_CET [openHABian] Installing Node.js (prerequisite for other packages)... OK
- 2018-02-16_19:59:35_CET [openHABian] Installing the openHAB Log Viewer (frontail)... OK
- 2018-02-16_20:00:22_CET [openHABian] Adding an openHAB dashboard tile for 'frontail'... OK
- 2018-02-16_20:00:22_CET [openHABian] Execution of 'openhabian-setup.sh unattended' completed.
- 2018-02-16_20:00:22_CET [openHABian] Waiting for openHAB to become ready...
- 2018-02-17_10:17:09_CET [openHABian] Starting the openHABian initial setup.
- 2018-02-17_10:17:09_CET [openHABian] Storing configuration... OK
- 2018-02-17_10:17:10_CET [openHABian] Changing default username and password... SKIPPED
- 2018-02-17_10:17:10_CET [openHABian] Setting up Ethernet connection... OK
- 2018-02-17_10:17:10_CET [openHABian] Ensuring network connectivity... OK
- 2018-02-17_10:17:10_CET [openHABian] Waiting for dpkg/apt to get ready... OK
- 2018-02-17_10:17:33_CET [openHABian] Updating repositories and upgrading installed packages... OK
- 2018-02-17_10:25:32_CET [openHABian] Installing git package... OK
- 2018-02-17_10:25:34_CET [openHABian] Cloning myself... FAILED
- 2018-02-17_10:25:49_CET [openHABian] Initial setup exiting with an error!

**Comment by EliasGabrielsson** [comment]
The error have to do with openhabian fetching the latest script from github.
Maybe you had bad luck and github.com couldn't be reached or similar.

Simply make another try.

**Comment by ThomDietrich** [comment]
I agree with @EliasGabrielsson, this is some form of hick-up you should be able to eliminate by a second try.

If you are experiencing issues once again, please let us know and I'll reopen the issue!
