### ISSUE TITLE
openhab manual setup broken

### ISSUE THREAD

**Issue by mczerski** [openhab/openhabian#341]
It seems like last commit has broken the manual setup:
/opt/openhabian/functions/menu.sh: line 171: openhab2_stable_setup: command not found

changing openhab2_stable_setup to openhab2_setup in line 171 seems to solve the problem.

**Comment by EliasGabrielsson** [comment]
Thanks for reporting. Added a patch as you described. 👍

**Comment by ThomDietrich** [comment]
@mczerski thanks for the bug report. The fix is merged now.

**Comment by mczerski** [comment]
@ThomDietrich sure, no problem ;)
