### ISSUE TITLE
[bug] reverse proxy failed to update directory after blank domain name

### ISSUE THREAD

**Issue by WeirdlyChosen** [openhab/openhabian#343]
Hello, I am no programmer nor able to contribute on openhabian.

I installed reverse proxy without https on my pi3, works fine.
Then I reinstall reverse proxy with https, but I didn't specify domain name this time.
Now everytime I open my openhabian IP address, both port 80 and 443, it opens http://localhost, so I cannot access openhab.
I tried to reinstall reverse proxy, with https, specifying my domain name, it tells an error "Sadly there was a problem setting up the selected option. Please report this problem in openHAB community forum, or as a openhabian github issue"
If I try to install reverse proxy without https, it tells no problem, but it still open http://localhost, so no use.

**Comment by ThomDietrich** [comment]
Hello,
the quick solution should be to uninstall the webserver, then deleting the configuration, then run the Reverse Proxy menu option.

From my head:
```
sudo apt purge nginx
sudo rm /etc/nginx/sites-enabled/openhab
```

@BClark09 sounds like a bug to me. Would you like to explore it?

**Comment by BClark09** [comment]
Will do! :)

**Comment by mstormi** [comment]
Cannot reproduce, and it's 2 yrs. old. Please reopen with details if this is still a problem.
