### ISSUE TITLE
System Tweaks causing read only file system

### ISSUE THREAD

**Issue by paulianttila** [openhab/openhabian#349]
openHABian version (460ce2fc03eb22389072dac88631df19f5a56fb2)

/etc/fstab before:
```
# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a
# device; this may be used with UUID= as a more robust way to name devices
# that works even if disks are added and removed. See fstab(5).
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
/dev/mapper/openhab2--vg-root /               ext4    errors=remount-ro 0       1
# /boot was on /dev/sda1 during installation
UUID=79a98787-7a81-4a9d-9df8-fe0dc46ecf65 /boot           ext2    defaults        0       2
/dev/mapper/openhab2--vg-swap_1 none            swap    sw              0       0

```
After executing System Tweaks:
```
# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a
# device; this may be used with UUID= as a more robust way to name devices
# that works even if disks are added and removed. See fstab(5).
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
# /boot was on /dev/sda1 during installation
UUID=79a98787-7a81-4a9d-9df8-fe0dc46ecf65 /boot           ext2    defaults        0       2

/usr/share/openhab2          /srv/openhab2-sys           none bind 0 0
/etc/openhab2                /srv/openhab2-conf          none bind 0 0
/var/lib/openhab2            /srv/openhab2-userdata      none bind 0 0
/var/log/openhab2            /srv/openhab2-logs          none bind 0 0
/usr/share/openhab2/addons   /srv/openhab2-addons        none bind 0 0
```

Environment:
Release = Ubuntu 16.04.4 LTS
Kernel = Linux 4.4.0-116-generic
Platform = QEMU Standard PC (i440FX + PIIX, 1996)
openHAB 2.2.0-1 (Release Build)

**Comment by paulianttila** [comment]
I made some investigation to find the root cause...

Background information:
I'm testing openHAB on Proxmox VE as I want to virtualize my openHAB environment. Test system hostname is set openhab2 as openhab is already reserved. I use LVM storage and it seems that fstab contains word openhab2 (Ubuntu mounts LVM volumes).

srv_bind_mounts function seems to remove all lines from fstab which contains openhab2 word.

```
srv_bind_mounts() {
  echo -n "$(timestamp) [openHABian] Preparing openHAB folder mounts under /srv/... "
  sed -i "/openhab2/d" /etc/fstab
  ...
```

**Comment by ThomDietrich** [comment]
Hey @paulianttila,

🙈 this is embarrassing! Yes it does indeed. https://github.com/openhab/openhabian/blob/460ce2fc03eb22389072dac88631df19f5a56fb2/functions/system.sh#L141
This is not the first time pattern-matching leads to such side effects. On the other hand I have to admit that I apparently didn't try too hard to define a good pattern.

Do you agree that this would be a good solution?
```shell
sed -i "#/srv/openhab2-#d" /etc/fstab
```

**Comment by paulianttila** [comment]
Hi @ThomDietrich,

> Do you agree that this would be a good solution?

Yes, that should be safe I think, but should it actually be (\ before first hash)?

`sed -i "\#/srv/openhab2-#d" /etc/fstab`

maybe even more safe (line should contain one space or tab before /srv/...)

`sed -i "\#[ \t]/srv/openhab2-#d" fstab`

**Comment by ThomDietrich** [comment]
Yes of course you are right. This escaping the non-standard delimiter rule doesn't hold true for substitution. Thanks for the quick review.

I wouldn't say the extra condition is needed, but hey sure thing.

**Comment by ThomDietrich** [comment]
Would you do me the honors of a final test in production?
