### ISSUE TITLE
E: Unable to locate package git

### ISSUE THREAD

**Issue by mronus** [openhab/openhabian#356]
Hello,

I couldn't successfully installed openhabian due to an issue. I replaced "&>/dev/null" with "&>/boot/firs-boot-debug.log" to see what the issue is, and I saw that there is a problem with git installation:

```log
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package git
```
I've tried adding `apt-get update` and `apt-get -y upgrade` right before `apt-get update` but it didn't work. Any idea?

**Comment by mues-lee** [comment]
Hello, 

could you please show us the output of `sudo apt-get update` as well as the output of `sudo apt-cache policy git`

Best
mues-lee

**Comment by mronus** [comment]
@mues-lee Sorry, I've just seen your message. I've tried something else after reporting this issue. I replaced all `apt` commands with `apt-get`, and it worked, installation was completed successfully. It is strange because, as I know, theoretically there is no difference between `apt` and `apt-get`. I've just run `sudo apt-get update` and `sudo apt-cache policy git` with working openhab, and

the output of `sudo apt-get update`:
```log
Hit:1 https://deb.nodesource.com/node_7.x stretch InRelease
Ign:2 https://dl.bintray.com/openhab/apt-repo2 stable InRelease
Hit:3 https://dl.bintray.com/openhab/apt-repo2 stable Release
Hit:5 http://raspbian.raspberrypi.org/raspbian stretch InRelease                                                         
Hit:6 http://archive.raspberrypi.org/debian stretch InRelease                                                            
Ign:7 http://repos.azulsystems.com/debian stable InRelease                      
Hit:8 http://repos.azulsystems.com/debian stable Release
```

the output of `sudo apt-cache policy git`:
```log
git:
  Installed: 1:2.11.0-3+deb9u2
  Candidate: 1:2.11.0-3+deb9u2
  Version table:
 *** 1:2.11.0-3+deb9u2 500
        500 http://raspbian.raspberrypi.org/raspbian stretch/main armhf Packages
        100 /var/lib/dpkg/status
```

**Comment by mues-lee** [comment]
good that it's working now, but i think the problem was more that your system had trouble to reach raspberrypi.org rather than the change from `apt` to `apt-get`
I just did a test install on a pi 3b+ using the openHABian image and it worked without a any problem

**Comment by ThomDietrich** [comment]
I also think a temporary issue is more likely. Those sadly happen from time to time.
Glad you got it working.
