### ISSUE TITLE
first-boot.log in bash output

### ISSUE THREAD

**Issue by mues-lee** [openhab/openhabian#357]
Hi,
 
> file I'm talking about 
> openhabian/includes/bash_profile

i suggest to change from `cat` to `tail n=20` because when the log gets longer, for example when failing the install, cat will only showing the first part pf the log, giving the user old outdated data.

PR?

Best
mues-lee

**Comment by ThomDietrich** [comment]
Ah you mean in the watch view? Did you encounter a log longer than you console window in maximized view? I'd rather not cut away parts of the log...

**Comment by mues-lee** [comment]
the reason i brought this up was my experience, during the very first install
i had the putty window not maximized, but as I always do, in the default, smaller window it starts with on Windows. After a while i started to wonder why the log didn't continue scrolling down

I also think not there will be many causal user that also will not maximize the window

To improve the usability I see these options:
 - add a note to the installation guide to use a maximized window, so you can see all the log
 - adding a additional `echo` during first boot, so it writes a hint in the first line to maximize the window
        to prevent spaming up the log with this messages and waste screen space in case of reboot:
        ` if ! grep -q "maximize window to see the whole log" /boot/first-boot.log;  then`
        ` echo echo -e "$(timestamp) [openHABian] HINT: maximize window to see the whole log \\n\\n" `
        ` fi `
 - pruning the log output to create a scrolling log

**Comment by mues-lee** [comment]
sorry my fault, wrong button, didn't meant to close this

**Comment by ThomDietrich** [comment]
I get your point. I see why this is a valid issue and we should look into it. Let's schedule it for the next image though... till then we can think of a solution.

May I add another option. How about we replace `cat` by `tac`?

I'd very much prefer a solution that just scrolls down, like cat would do normally. Maybe there is a better option than `watch cat ...`

Finally: I was thinking about providing a webserver right from the beginning. A user interested in the installation progress could then find the log under http://openhabianpi - no SSH, no console magic.

**Comment by mues-lee** [comment]
a lightweight webserver is a nice idea and since there is already python3 installed on raspbian not so hard to do
i will created a PR for this, adding the changes only for raspberry, since I don't own a Pine A64 and I can't test it on

**Comment by EliasGabrielsson** [comment]
@mues-lee @ThomDietrich What do we do with this issue?
Does the web interface solve the original problem?

**Comment by mstormi** [comment]
Guys, is this still an issue we would need to leave open ?

**Comment by mstormi** [comment]
I'll close this issue as I neither get any response in a month nor that I'm aware of the problem to still exist.
Reopen if you disagree but if so please describe the current state again and what's the problem on that.
