### ISSUE TITLE
change Samba share password is not working on raspberry pi 3b+

### ISSUE THREAD

**Issue by bones78** [openhab/openhabian#362]
I have tried to change the Samba share password via openhabian-config. This does not work. It said password changed, but only the default  password (openhabian) worked. 
If I change the password via smbpasswd, the new one is accepted.
I downloaded the "old" 1.4 image and I changed the start.elf.

**Comment by ThomDietrich** [comment]
Interesting... thanks for the notice!
@EliasGabrielsson @mues-lee could you have a look?

**Comment by EliasGabrielsson** [comment]
This is definitely something we need to look into. Spontaneously, I do not understand why this would happen. 

@bones78 Could you please provide samba version by running: `smbd -V`.

Also when you used `smbpasswd` how did you use it?

Do you also mind trying the script below as I can't reproduce the error myself?
Copy the content to a file like `test.sh`, eg. `nano test.sh`, past content below, run with `sudo bash ./test.sh`.
The script shall change the smb password to "newpassword", just dubbel check the username. Check if that work or output any errors. This is what openhabian tool does but isolated to just this feature.

```
username="openhabian"
(echo "newpassword"; echo "newpassword") | /usr/bin/smbpasswd -s -a "$username"
```

**Comment by mues-lee** [comment]
i also can't reproduce this, changing the password works no matter if you just select samba or all

@bones78 may sound like a stupid question, but you also set a `*` in the samba line, right?

**Comment by BClark09** [comment]
This was due to a small typo, submitted a PR.

**Comment by ThomDietrich** [comment]
Typos are sometimes the worst problems to solve 😄 Thanks Ben!

**Comment by bones78** [comment]
ok I see problem is solved.
Just to complete: I typed in: smbpasswd and followed the instructions.
Yes I set a * in the line. The Samba Version is: Version 4.5.12-Debian
