### ISSUE TITLE
Script full Grafana & InfluxDB setup

### ISSUE THREAD

**Issue by EliasGabrielsson** [openhab/openhabian#366]
Script the content of this post:
https://community.openhab.org/t/influxdb-grafana-persistence-and-graphing/13761/1

See password change function for influx as inspiration how to handle databases.

**Comment by mues-lee** [comment]
an addition though maybe adding the option to make influxDB an optional installation step, so user that want to use an existing database,  e.g. mysql, can just install grafana

**Comment by EliasGabrielsson** [comment]
Agree @mues-lee. I run an influxDB on a more persistent storage and Grafana on the Openhabian installation.

t would also be fluid to install openHAB addons either with the `extension REST API` or with the openhab console.
