### ISSUE TITLE
Openhabian 1.4.1 download 404

### ISSUE THREAD

**Issue by helpshelps** [openhab/openhabian#369]
The link for the 'Hassle free' Pi image download for V1.4.1 leads to a 404 error. However the Pine A64 image link works.

These links are at 
https://github.com/openhab/openhabian/releases

**Comment by ThomDietrich** [comment]
Thanks for the hint! It's fixed now.

Here you go: https://drive.google.com/open?id=1jh5rs44l-Pbiz0fG9eSoX5WikOZu1e2-
