### ISSUE TITLE
Review variable scope

### ISSUE THREAD

**Issue by EliasGabrielsson** [openhab/openhabian#373]
Currently almost every variable used within this tool is declared global. As the complexity and size of the tool growth this can result in variable conflicts due "code invisibility" when developing.

The solution would be to declare variables `local varablename="value"` when not used within the whole tool. An boring but simple review followed by testing will do the job.

**Comment by ThomDietrich** [comment]
A good point and the "boring but simple" aspect held me back from doing this so far :)
Feel free to shoot!

**Comment by ThomDietrich** [comment]
@EliasGabrielsson thanks for redirecting me here. Seems like I already knew about this 😄 Feels like this issue can be closed!?

**Comment by EliasGabrielsson** [comment]
I see this more of a long-going initiative of reviewing all code. So far have I refactored code when I touched it for other reasons or when reviewing PR. It's a lot of code still using global variables.

We could of course split up this issue in to smaller parts corespondent to different pieces of code, but I don't wanted to clutter the issue log with this.

**Comment by ThomDietrich** [comment]
Okay let's leave it open for now. I'll remember to introduce local when working on parts of the code base.

**Comment by mstormi** [comment]
With coding guidelines in place now and the shellcheck review, is this still an issue ?

**Comment by ThomDietrich** [comment]
Don't think so
