### ISSUE TITLE
Detect RPi3B+

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhabian#374]
https://community.openhab.org/t/raspberry-3-b-wifi-on-openhabian/43417

@mues-lee could you troubleshoot this problem for me?

My guess: This routine doesn't match the new Pi, hence that condition isn't true:

https://github.com/openhab/openhabian/blob/master/functions/helpers.sh#L55
https://github.com/openhab/openhabian/blob/master/functions/wifi.sh#L5

**Comment by haroldh** [comment]
I checked the helpers.sh part:

This is what my RBP3+ says in /proc/cpuinfo :
`Hardware	: BCM2835`
`Revision	: a02082
`

As far as I can see, the WiFi part of the logic should include the country selection part.
This link may help: https://raspberrypi.stackexchange.com/a/72721

**Comment by ThomDietrich** [comment]
Good point. It should and is already available to be copy&paste'ed here: https://github.com/openhab/openhabian/blob/master/build-rpi-raspbian/first-boot.sh#L48

**Comment by ThomDietrich** [comment]
> Revision : a02082

Interestingly this is supposedly still a normal 3B:
https://www.raspberrypi.org/documentation/hardware/raspberrypi/revision-codes/README.md

**Comment by haroldh** [comment]
@mues-lee yes, I am 100% sure. But I made a mistake copying the revision info from the wrong terminal screen :( (I compared the pi3b and the pi3b+ before I created the information here)
I corrected the information in my original entry.

**Comment by mues-lee** [comment]
@haroldh ah i see, sorry wasn't meant to sound rude

**Comment by haroldh** [comment]
@mues-lee no worries, I should have used more emoticons to show that I was not offended :-) 

By the way, is there a reason for not using `is_pi3plus` ? It makes reading a little easier perhaps.

**Comment by mues-lee** [comment]
the only reason for this is because there was already a `is_pithree` and didn't wanted to introduce a new naming scheme and yes i agree a `is_pi3plus` is much easier to read

**Comment by Wirsing84** [comment]
Awesome! When can one expect for these changes to make it into a new release? Or put otherwise: I have a freshly flashed sd-card I created today with  1.4.1 - but as it seems wifi won't work on my RPi3b+ if I use it. However I can't find the respective files (e.g., functions/helpers.sh), they seem to be compressed in the image. What do I do? Calling for help, I'm new :)

**Comment by ThomDietrich** [comment]
The addition here is actually unrelated to the issue. Most parts of the openHABian project are not directly included in the provided RPi image but rather part of the openHABian configuration tool, which is shipped with a self-update function.

> but as it seems wifi won't work on my RPi3b+ if I use it

Please open a new issue and describe what you mean with "won't work". Thanks ;)

**Comment by Wirsing84** [comment]
Oh, I see, then I probably misunderstood. I came here from https://community.openhab.org/t/raspberry-3-b-wifi-on-openhabian/43417/11

I didn't even try the setup process yet as I don't want to run into trouble early on. However I have this brand new RPi3b+ and am seeing these issues arise w/ others... I have a bad feeling about this

**Comment by Wirsing84** [comment]
Well actually... I have started up the RPi3b+ with 1.4.1 image and ssid and pw set in the config file almost one hour ago. Still no new device in the wifi router... seems like a fail to me?

**Comment by Wirsing84** [comment]
Confirmation from first-boot.log on sd:
2018-03-13_22:53:58_UTC [openHABian] Starting the openHABian initial setup.
2018-03-13_22:53:58_UTC [openHABian] Storing configuration... OK
2018-03-13_22:53:58_UTC [openHABian] Changing default username and password... OK
2018-03-13_22:53:59_UTC [openHABian] Setting up Wi-Fi connection... OK, rebooting... 
2018-03-13_22:54:31_UTC [openHABian] Starting the openHABian initial setup.
2018-03-13_22:54:31_UTC [openHABian] Storing configuration... OK
2018-03-13_22:54:32_UTC [openHABian] Changing default username and password... SKIPPED
2018-03-13_22:54:32_UTC [openHABian] Setting up Wi-Fi connection... OK
2018-03-13_22:54:32_UTC [openHABian] Ensuring network connectivity... FAILED

I was not able to connect to the configured Wi-Fi.
Please try again with your correct SSID and password.
Also check your signal quality. Available Wi-Fi networks:
wlan0     Interface doesn't support scanning : Network is down


2018-03-13_22:56:16_UTC [openHABian] Initial setup exiting with an error!


Ho hum

**Comment by ThomDietrich** [comment]
Interesting. This routine worked with the RPi3. @mues-lee would you be able to troubleshoot?

@Wirsing84 please go with Ethernet for now. That's better anyhow. After the installation is complete you can still decide to configure and switch over to Wifi.

For all future discussion, please open a new issue! Thanks.
Good luck!

**Comment by Wirsing84** [comment]
Thank you @ThomDietrich, will do - and would have been next step

**Comment by jayloo** [comment]
Dear Thom, will you work on this [problem](https://community.openhab.org/t/raspberry-3-b-wifi-on-openhabian/43417/18?u=jayloo) soon or should I switch to a former firmware and just go with ethernet....?
