### ISSUE TITLE
log tail with colors

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhabian#38]
Enhance the openhab log tail with coloring. can be done with tools like grc or ccze. Needs further investigation.

**Comment by mstormi** [comment]
do you still want to keep this on the todo list ?
Please also check #42 and #48 .

**Comment by mstormi** [comment]
Given our refocusing and this idea is 3+ yrs old, I don't see any need to act on anything here.
Please reopen if you disagree.
