### ISSUE TITLE
My 2 Cents. Wifi not activating on Pi3

### ISSUE THREAD

**Issue by EkDor** [openhab/openhabian#387]
I was stuck for some time and could not resolve my issue based on many "google" results. Wifi on my Raspberry Pi 3 on a fresh install from their img. But I found an older SD card with a working WiFi. So I explored and found the following. I offer this information for those that find other information un-resolving of their issue (sorry didn't know how to phrase that better - drunk at the moment... Don't let that dissuade you I am thinking clearly if not on a fly-by-wire method). I suspect it's related my my Local network setup which is almost all Apple routing. I have a typical Apple routing setup with WPA2 security and mixed 2.4ghz and 5ghz network.

**Interfaces File Contents**
location: sudo nano /etc/network/interfaces

```
auto lo
iface lo inet loopback
iface eth0 inet dhcp

allow-hotplug wlan0
auto wlan0

iface wlan0 inet dhcp
   wpa-ssid "YOUR-NETWORK-NAME"
   wpa-psk "YOUR-PASSWORD"
```

**Supplicants File Contents**
Location: sudo nano /etc/wpa_supplicant/wpa_supplicant.conf

```
country=AU
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
# RETROPIE CONFIG START
network={
        ssid="YOUR-NETWORK-NAME"
        psk="YOUR-PASSWORD"
}
# RETROPIE CONFIG END
```

I tried for 2 days to get my wifi to work. This alone in a single implementation fixed it for me. So Again i offer this as For Your Information.

**Comment by MZorzy** [comment]
#351  
#378

**Comment by EliasGabrielsson** [comment]
@EkDor Thanks for your input. 👍

**Comment by jscottnz** [comment]
@EliasGabrielsson this very much looks like it.
@EkDor  can test by running
```
sudo  rfkill unblock wifi
sudo  ifconfig wlan0 up
```

**Comment by EliasGabrielsson** [comment]
@jscottnz Thanks for your input.
@EkDor I close this for now. If the problem still exist after the workaround don't hesitate to reopen this issue.

**Comment by dcmccubbin** [comment]
EkDor, thank you!!! 
After working on this for 2 days, your solution has my Wifi working with Incredible PBX. 
Quite a relief to get past that problem.
