### ISSUE TITLE
Manual setup: Log Viewer tile points to the wrong host

### ISSUE THREAD

**Issue by brianwarner** [openhab/openhabian#389]
I did a [manual setup of OpenHABian](https://docs.openhab.org/installation/openhabian.html#manual-setup), where I:
1. Installed Ubuntu Server 18.04 on x86
2. Ran `openhabian-setup.sh`
3. Executed all numbered steps in `Manual/Fresh Setup` except `FireMotD`

Everything is working right except the tile for the log viewer.  For some reason, it tries to send me to the host `openhabiandevice`.  Every other tile goes to the proper host, as defined in `/etc/hostname`.  I can't find this string anywhere, does anybody have an idea where I went wrong and how to fix it?

**Comment by ThomDietrich** [comment]
Hey! First and foremost, this might be related or at least solved during the work on #287 

The function creating tiles is this one: https://github.com/openhab/openhabian/blob/master/functions/openhab.sh#L131 and tile data comes from: https://github.com/openhab/openhabian/blob/master/includes/dashboard-imagedata.sh

... I am not sure where your error came from.
