### ISSUE TITLE
RPi3+ @ Stretch /w swap file - Memory leak

### ISSUE THREAD

**Issue by s0170071** [openhab/openhabian#392]
I installed openhab2 stable on an existing raspi3b+ stretch installation with piViccu, influxDB, grafana and mosquitto. Upon startup of the system, openhab seems to start up OK.

BUT: 
HTOP shows multiple (>40) java threads being started. Four at a time, about each second. The swap file grows to several hundred MB over time. Eventually the system becomes partly unresponsive. 

If I disable the swap file, the memory consumption rises sharply to about 600MB and stays there or rises only slightly over time. I also tried rpi-update and OH re-install with the OH Testing release- same.
Jave version is oracle8.

**Comment by ThomDietrich** [comment]
Hello @s0170071,
please understand that this is the openHABian issue tracker, reserved for openHABian related development.
Your description sounds like something you should discuss in the openHAB community forum. Please repost your text there. However, please be sure to state a clear question... I can only speculate what you are asking for. Best of luck!
