### ISSUE TITLE
openhabain should set gpg key for repository on stable and unstable releases

### ISSUE THREAD

**Issue by tbail** [openhab/openhabian#393]
I setup openhabian with a manual install and the use the option fresh install. While using the unstable openhab option i was not able to install openhab unstable, becase the gpg key is not available. Tjis key is only set if you select the stable version.

It should be set in any case.

**Comment by ThomDietrich** [comment]
Hey @tbail, I am not sure which key was missing from your system. Could you provide more details? Here's the execution in questions:

https://github.com/openhab/openhabian/blob/master/functions/openhab.sh#L40

**Comment by ThomDietrich** [comment]
Ah! Now I get it. Yes that should be general for both. Interesting that no one ran into the issue yet because almost everyone starts with stable. Let me fix this real quick...

**Comment by ThomDietrich** [comment]
Solved @tbail  ;)
