### ISSUE TITLE
Full image for users with bad internet connection

### ISSUE THREAD

**Issue by AIWintermuteAI** [openhab/openhabian#398]
I've been trying to install openhabianpi for 3 days now.  Currently residing in China I blame ISP for that. Mainland China is known for blocking ... well, anything they don't like on the internet.  I've tried manual install on fresh raspbian to see the output of installation script. I think most often it fails on installing Node 8 and also Zulu installation takes painfully long(8 hours something). 

Does somebody has a full image of openhabian? Also is it in project's pipeline to release such image alongside with "Openhabianpi Lite"?

**Comment by ThomDietrich** [comment]
Hey,
such an image was not planned for the future. So far I never saw a good reason for it. In most weird cases I'd suggest the manual setup path based on a Raspbian image - You have already tried that... Hmmm

What is "Openhabianpi Lite"

What's the opinion of others on the matter?

**Comment by EliasGabrielsson** [comment]
I agree with Marcus here.
I think this projects spare voluntarily resources need to directed elsewhere. 
I close this for now.
