### ISSUE TITLE
Failed installing 'openhab-package-standard': No matching features for openhab-package-standard/0.0.0

### ISSUE THREAD

**Issue by Alluuu** [openhab/openhabian#404]
Raspberry Pi 3 B+ new install

After getting everything through and "working", going to the dashboard and selecting "Standard" package, all my dashnoard has is the log and helpbuttons, and in the log the error mentioned in the title: 

"Failed installing 'openhab-package-standard': No matching features for openhab-package-standard/0.0.0"

Don't have any UI's or anything:

![image](https://user-images.githubusercontent.com/22728104/40548283-f08e47bc-603c-11e8-8367-445894e7d48b.png)

**Comment by EliasGabrielsson** [comment]
Hi,
Have you tried to reinstall everything from scratch again?
Which log did you find the error in?
