### ISSUE TITLE
Create new log file [first-boot-debug.log] containing all output while installing (instead of pipe to /dev/null)

### ISSUE THREAD

**Issue by asoltesz** [openhab/openhabian#408]
The first-boot.sh script runs for a long time and seemingly fails for a fair amount of people for a wide variety of reasons.

I find it a very bad idea that it sends command output to /dev/null so the user cannot see the progress of the commands and neither the error messages when the script fails.

I recommend using section markers (like "------------------" before executing a command and leaving the command output intact (displayed on the screen and in the log file).

**Comment by ThomDietrich** [comment]
@EliasGabrielsson I like the approach!

**Comment by ThomDietrich** [comment]
See the update to this question and the comment:
- https://stackoverflow.com/questions/314675/how-do-i-redirect-the-output-of-an-entire-shell-script-within-the-script-itself/314678
- https://stackoverflow.com/questions/314675/how-do-i-redirect-the-output-of-an-entire-shell-script-within-the-script-itself/314678#comment67651454_314675
