### ISSUE TITLE
Prepare for change in package directory.

### ISSUE THREAD

**Issue by BClark09** [openhab/openhabian#41]
As I understand in openhab/openhab-linuxpkg#2 the package directory will change to bintray, just as the beta builds are. We need to be prepared for this change so that it can be quickly reflected in openHABian.

**Comment by ThomDietrich** [comment]
Hey Ben thanks for the heads up. I saw the ticket but overlooked that detail. I'll ask my further questions over there.

**Comment by BClark09** [comment]
As a heads up, the bintray repo is now working along-side cloudbees for the time being. The snapshot distribution can be added to the debian package list via the commands:

```
echo 'deb http://dl.bintray.com/openhab/apt-repo2 unstable main' | sudo tee /etc/apt/sources.list.d/openhab2.list
wget -qO - 'https://bintray.com/user/downloadSubjectPublicKey?username=openhab' | sudo apt-key add -
sudo apt-get update
```

**Comment by ThomDietrich** [comment]
Hey @BClark09, thanks. I'll have a look into it next week. I guess some more steps will be needed with the new online/offline packages.
I saw that there are two or three build types. Please correct me if I'm wrong:
**unstable**: Will always deliver the latest snapshot.
**testing**: Will always deliver latest beta. (or stable when no newer beta is available)
**stable**: Will always deliver latest stable release. (soon 2.0.0 GA)

**Comment by BClark09** [comment]
Absolutely right on the build types. Changing the source list for now should be all that is required whilst online/offline versions exist.

When offline is removed, "openhab2-online" will become "openhab2" but since you can't directly rename packages from different sources, the order of commands to make the switch should be:

```
sudo apt-get remove openhab2-o*
sudo apt-get install openhab2
```

Followed optionally by:
```
sudo apt-get install openhab2-addons
```

I'm working on getting the openhab2-addons package sorted soon.

**Comment by BClark09** [comment]
Turns out that we can make it so that `sudo apt-get install openhab2` will remove `openhab2-online` for you!

@ThomDietrich. thought you should know that the new package types will be available when https://github.com/openhab/openhab-linuxpkg/pull/18 is merged and it's had a chance to have one build. 

The older offline/online packages will still exist as long as the version that contains it does so if you simply change the sources list then users should still have a working first setup for a while.

**Comment by ThomDietrich** [comment]
It's about time to move over! I've just switched over to the new repository.
It's already tested on my system. 
The next step will be to

1. Switch to installing `openhab2 openhab2-addons` or only `openhab2` on new systems
2. Transition updating systems away from `openhab2-offline`
3. Provide the choice to install stable, testing or unstable through the menu (With stable being the default)

**Comment by BClark09** [comment]
Hi @ThomDietrich, I have prepared a debian repo for you to test with:

It contains, in version-chronological order:

 - 2.0.0~b5 (online and offline) in the testing branch.
 - 2.0.0 in the stable branch (which is actually just a [perhaps unstable] snapshot I built today)
 - 2.0.0~[snapshot] in the unstable branch (built after 2.0.0)

I hope this helps, if you need anything else inside it just let me know!

**Comment by ThomDietrich** [comment]
Amazing. Thank you @BClark09 !

**Comment by BClark09** [comment]
Sorry to have to do this to you again! We will be moving the snapshots to a new repo, since Bintray can't support the nightly nature of openhab:

```
deb https://openhab.jfrog.io/openhab/debian-local unstable main
```

I've placed a snapshot build on there for you to test with, but at the moment it is not GPG signed, so you will have to state yes when it tells warns you of no authentication. That's the most likely place it'll go but the "debian-local" name might change.

**Comment by ThomDietrich** [comment]
Hey @BClark09 thanks for the heads up!
Actually this is not of concern to here *atm*. openHABian doesn't have the function to switch to another branch yet. http://docs.openhab.org/installation/openhabian.html#switch-openhab-branch
But of course I wanted to add that function eventually. Thanks!

**Comment by BClark09** [comment]
Hey @ThomDietrich, I was looking through the list of my open issues. Since you're running on the stable version I'd assume we can close this? If not, would you like some help with that function to switch branches?

**Comment by ThomDietrich** [comment]
Hey Ben, actually I've implemented something in this direction. I forgot to mention the PR (https://github.com/openhab/openhabian/pull/132) here. The function is capable to install unstable as a fresh setup or as an upgrade to an existing stable setup.
I'd say with that this issue is solved, what do you think?

**Comment by BClark09** [comment]
Yep that looks good! Thanks again!
