### ISSUE TITLE
openHAB Stable option should downgrade if needed

### ISSUE THREAD

**Issue by BClark09** [openhab/openhabian#410]
At the moment, if a user is on a 2.4.0-SNAPSHOT, they cannot use the menu to "downgrade" to stable.

One way of doing this is to:

1. Switch to the stable repository.
2. Parse `apt-cache policy openhab2` (or `showpkg` or `madison`)
3. Install the version noted on the first line via `apt install -y openhab2=<version>`

**Comment by ThomDietrich** [comment]
Just to clarify one thing: I believe to not have specifically covered that switch because of potential side effects.

I wonder if it's finally time to implement helper functions to retrieve the currently installed version and repository versions, then offer more tailored openHAB menu entries...

**Comment by BClark09** [comment]
That's fair enough, do you think this is something `openhab-cli` can handle?

**Comment by ThomDietrich** [comment]
What exactly? No I'd like to keep as much as possible inside `openhabian-setup`. I'm still not sure how both can coexist meaningfully. It would be easy to merge the few functions of `openhab-cli`

**Comment by ThomDietrich** [comment]
Sorry, that might sound wrong.

I'm still unsure how both command line tools can coexist. Both do similar things and eventually will have overlapping functionality. I wonder if it would make sense to merge them and to ship openhabian-config with the apt package (with the appropriate parametrization to not identify as openHABian of course)

**Comment by mstormi** [comment]
I think there is a --allow-downgrades option now.

Thomas, Ben, where to move from here ?

**Comment by mstormi** [comment]
@ThomDietrich @BClark09
How to treat this issue from here on?
I think we should separate the initial issue from any discussions on openhab-cli and openhabian-config to overlap/integrate/whatever (if that still is an issue after all).

Isn't the original issue fixed now that we have a --allow-downgrades option so we can close this?
(and open another issue for the tool discussion if needed)

**Comment by mstormi** [comment]
@BClark09 ping .... is there anything you think we would still need to do ?

**Comment by BClark09** [comment]
If an `--allow-downgrades` option has been added, and there is sufficient warning that downgrading may have side effects, then no I don't think there is.

**Comment by mstormi** [comment]
yes (both)
so will close this issue, reopen if you find anything wrong with it
