### ISSUE TITLE
Test webIF on PineA64 base image

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhabian#412]
During image creation we should test if the web interface by @mues-lee would also work on the Pine A64 image.

Potentially interesting to: @EliasGabrielsson @1activegeek 

https://github.com/openhab/openhabian/pull/372#issuecomment-390254008

**Comment by 1activegeek** [comment]
@ThomDietrich - I've switched over to DietPi and HomeAssistant, so I don't run this release anymore. 😉 Sorry!

**Comment by EliasGabrielsson** [comment]
I can put some effort into that this upcoming month.

**Comment by EliasGabrielsson** [comment]
Fixed in: https://github.com/openhab/openhabian/pull/358
