### ISSUE TITLE
Loss of DNS resolution breaks operation

### ISSUE THREAD

**Issue by jscottnz** [openhab/openhabian#415]
One of my installs starting erroring on all sorts of unreachable host exceptions.

I found that while the local network was still working (i'd ssh'd in over wifi) there was no dns resolution.

restarting the networking fixed it `sudo /etc/init.d/networking restart`

I do not know why it broke, but the fix was simple.

While poking around the internet I came across this script:

https://www.linuxquestions.org/questions/linux-networking-3/script-to-check-connection-and-restart-network-if-down-262281/#post3815629

which effectively checks for connectivity and restarts networking if required.

I'm going to add this to my install and thought that if you all think that this could be the cause of other issues ( maybe https://community.openhab.org/t/icloud-binding-stopped-working/38639/13 ) then this could be a simple fix.

openhabian 1.4
RPI3B+
Wifi only

**Comment by EliasGabrielsson** [comment]
Hi Jeremy 👋

Good finding. I don't think we shall make this workaround a core component but maybe an optional one. This almost qualify for a new script category where it shall be able to toggle things on and off.

I keep the issue open for discussion.

**Comment by jscottnz** [comment]
I think that the root cause of this is the dns resolution using /etc/resolv.conf is using my local router which i do not trust. I've thrown in some google nameservers to see if that fixes the issues I've been seeing.

**Comment by mstormi** [comment]
Yes there's some prerequisites to openHABian such as internet access, DNS and DHCP. If your local router isn't reliably providing these, it's very hard and dangerous to try working around, let alone in a scripted fully or semi-automated fashion. Remember we need to remain able to install headless.
Thanks for suggesting, but I'd rather opt against such an addition as it'll likely only be useful in corner cases while for the rest of the time, it is providing a false sense of a "working" openHABian when the environment in fact isn't stable and needs to be taken care of.

**Comment by mstormi** [comment]
Given our responses and many changes in Raspbian (now on buster) and openHABian that took place since, I'd say this is no longer an issue or development target.
Feel encouraged to reopen if you still encounter problems with current openHABian.
(if so, please provide a new analysis and solution)
