### ISSUE TITLE
Can't select options on Manual/Fresh setup on Openhabian

### ISSUE THREAD

**Issue by jordiponsmartell** [openhab/openhabian#418]
Hello,
I'm trying to install Openhab with Openhabian (Orange Pi Zero with Armbian Stretch), and in the Manual/Fresh menu, I see the cursor next to every line but I can't select no one. When I hit enter I'm ejected to the principal menu.
I saw the similar issue, but in my case is not a size/column/ssh problem.
Can somebody give me a hint??
Thank you.

**Comment by EliasGabrielsson** [comment]
Could you provide a screenshot? When you quit the tool what is logged in your terminal?

**Comment by jordiponsmartell** [comment]
Hi, I finally installed manually and went good. But would be great to know why that happens. Just to paste the image, I started (./openhabian-setup.sh) and choosed the manual/fresh option, and hitted the update option inside it.

![terminal_exit](https://user-images.githubusercontent.com/33551885/41202178-999306b0-6cc5-11e8-83b4-7fd07b7240c3.png)

**Comment by EliasGabrielsson** [comment]
I think this is a easy one. Try `space` in the menu and you will have great success.
I close this one for now don't mind to reopen it if I misunderstood you.
