### ISSUE TITLE
nano editor config

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhabian#42]
openHABian is equiped with a nice vimrc file making the vim editor more useful.

Despite the fact that vim is superior to nano (pun intended), I can see how some prefer to use nano. If someone wants to contribute a nano configuration, do not hold back.

**Comment by BClark09** [comment]
No love for [emacs?] (http://xkcd.com/378/)  ;)

**Comment by ThomDietrich** [comment]
Hahaha 🔟  points for linking xkcd.
I'm a vim believer myself but do as you like ;)

**Comment by BClark09** [comment]
I do believe though that nano is probably where many openHABian users will feel comfortable considering it's ease of use and the fact that the useful shortcuts are displayed all the time. I might be able to do something here but will let you know later!

**Comment by ThomDietrich** [comment]
I think so too. Hence the ticket. **If** there are recommended settings every user might love, we could add them. See [here](https://github.com/ThomDietrich/openhabian/blob/master/includes/vimrc) for my vimrc.

**Comment by mstormi** [comment]
We have a (colorful !) nano config. Dunno when it was added but it's there, so I'll close this.
