### ISSUE TITLE
Extend Wifi based setup by geolocation-based detection of region

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhabian#422]
Based on https://github.com/openhab/openhabian/pull/384

If a user installs or runs openHABian over wifi, the wifi region needs to be configured for the region/country the user is located in. Similarly to the automatic detection of ones timezone, we could add a step to automatically detect the location (two-letter country code) of the user. 

See e.g.: https://ipinfo.io --> "country"

Exception: Do not automatically set, if [`wifi_country`](https://github.com/openhab/openhabian/blob/master/build-image/openhabian.pi-raspbian.conf#L24) is given by the user.

CC @jscottnz

**Comment by jscottnz** [comment]
however to do this you need to be connected to the internet, which comes after setting up wifi - the only case that I can think that this would work is that if the user does not set the country code manually and it defaults to US, once the internet comes up, it could perform these checks and reconfigure the wifi?

**Comment by ThomDietrich** [comment]
That is exactly what I was thinking ;)

**Comment by mstormi** [comment]
@jscottnz Do you mind helping with a contribution here ? 

If noone does, it'll remain an unrealized nice idea and I'd close this issue ...

**Comment by mstormi** [comment]
@jscottnz ping

**Comment by jscottnz** [comment]
hi there. sorry I don't have the capacity to work on this.

**Comment by mstormi** [comment]
Thanks for your info. Alright then.
So will close. Feel free to reopen at any time when you have some time or code to contribute.
