### ISSUE TITLE
Add openhab user to audio group

### ISSUE THREAD

**Issue by triller-telekom** [openhab/openhabian#426]
Hello,

on the weekend I struggled to get TTS running in openHAB and it turned out that my "openhab" user was not in the "audio" group. Since this image aims at making the openHAB installation as easy as possible, how about adding the "openhab" user per default into the "audio" group. Maybe also into the groups to access ttyUSBX devices, while you are at it anyway :)

regards,

Stefan

**Comment by ThomDietrich** [comment]
Hey Stefan!
That is a good idea. I thought so too... https://github.com/openhab/openhabian/blob/master/functions/system.sh#L169-L171 Do you have any idea why this got past your system?

(you can run those lines via "14 | Fix Permissions")

**Comment by ThomDietrich** [comment]
Ah, did you uninstall/reinstall openHAB or switch to unstable?

**Comment by triller-telekom** [comment]
Very strange. My system was installed on a raspberry pi3 in august last year. I started with unstable directly. And there where a couple of uninstall/install cycles and updates until now. But somehow my user was not in the audio group, though it was in "tty", "dialout", and "gpio".

But since the lines are in your scripts, there must have been something wrong with my upgraded setup and I guess a blank installation would be fine now.

Thus, I will close this issue. Thanks for digging into your scripts to check it!

**Comment by ThomDietrich** [comment]
Strange but let's hope its not systematic. Thanks for reaching out! Enjoy your system ;)
