### ISSUE TITLE
Motivate pi user password change

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhabian#43]
I chose Raspbians default username+password to make the start for every user as easy as possible. Changing the password is of course something a user should do and can easily by executing ``raspi-config``... but yeah. That's something we could promote more, maybe by forcing the user to set a password on first ssh login or first ``openhabian-config`` execution.

**Comment by binderth** [comment]
This would be a must-have in my eyes: After the first boot, the user is forced to change the password. Or you could add a new password in an ini-file on the SC-Card, to make it easier for the non-experienced to change the password. At next boot, the password is changed and the password is deleted.?

**Comment by ThomDietrich** [comment]
@binderth @BClark09 what do you think?

**Comment by BClark09** [comment]
LGTM, I have a general question though. Since openHABian is now in the openHAB organisation, aren't maintainers supposed to submit all changes via PR requests? Or does it work differently to the others since it's a utility rather than part of the system.

**Comment by binderth** [comment]
:100:
