### ISSUE TITLE
Frontail installation issues

### ISSUE THREAD

**Issue by ConfusedTA** [openhab/openhabian#431]
Hi all,

Have just tried to install Frontail on my headless Ubuntu 18.04 box, but the installation is giving the following messages, and Frontail service doesn't start successfully.

```
2018-08-11_13:51:45_BST [openHABian] Installing the openHAB Log Viewer (frontail)...
$ npm install -g frontail
npm WARN deprecated connect@2.11.0: connect 2.x series is deprecated
/usr/local/bin/frontail -> /usr/local/lib/node_modules/frontail/bin/frontail
/usr/local/lib
└── frontail@4.2.2


$ npm update -g frontail
cp: cannot create regular file '/usr/lib/node_modules/frontail/preset/openhab.json': No such file or directory
cp: cannot create regular file '/usr/lib/node_modules/frontail/web/assets/styles/openhab.css': No such file or directory

$ systemctl daemon-reload

$ systemctl enable frontail.service

$ systemctl restart frontail.service
OK
```

Service status:

```
confused@openhab:~$ sudo systemctl status frontail.service
● frontail.service - Frontail openHAB instance, reachable at http://openhab:9001
   Loaded: loaded (/etc/systemd/system/frontail.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2018-08-11 13:51:51 BST; 3min 10s ago
     Docs: https://github.com/mthenw/frontail
           https://github.com/openhab/openhabian/issues/28
  Process: 17446 ExecStart=/usr/bin/frontail --ui-highlight --ui-highlight-preset /usr/lib/node_modules/frontail/preset/
 Main PID: 17446 (code=exited, status=203/EXEC)

Aug 11 13:51:51 openhab systemd[1]: frontail.service: Main process exited, code=exited, status=203/EXEC
Aug 11 13:51:51 openhab systemd[1]: frontail.service: Failed with result 'exit-code'.
Aug 11 13:51:51 openhab systemd[1]: frontail.service: Service hold-off time over, scheduling restart.
Aug 11 13:51:51 openhab systemd[1]: frontail.service: Scheduled restart job, restart counter is at 5.
Aug 11 13:51:51 openhab systemd[1]: Stopped Frontail openHAB instance, reachable at http://openhab:9001.
Aug 11 13:51:51 openhab systemd[1]: frontail.service: Start request repeated too quickly.
Aug 11 13:51:51 openhab systemd[1]: frontail.service: Failed with result 'exit-code'.
Aug 11 13:51:51 openhab systemd[1]: Failed to start Frontail openHAB instance, reachable at http://openhab:9001.
```

**Comment by BGunnarB** [comment]
I just want to add that I experience the same issue on my MacMini Intel Solo box running Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-31-generic i686)

**Comment by rwestnl** [comment]
New install today gave me te same issue. Virtual machine > Ubuntu 16.04.5 (server , i386) > openhabian
```
$ npm update -g frontail
cp: cannot create regular file '/usr/lib/node_modules/frontail/preset/openhab.json': No such file or directory
cp: cannot create regular file '/usr/lib/node_modules/frontail/web/assets/styles/openhab.css': No such file or directory
```

When checking the path it seems that the folder **node_modules** `/usr/lib/node_modules/` isn't present.

Also had some other trouble; zulu-8 not found, npm install failed

**Comment by xsherlockpl** [comment]
Anyone managed to solve that ,I have the same issue on fresh ubuntu 18.04 install

**Comment by maestr0** [comment]
Update  `WorkingDirectory=/usr/lib/node_modules/frontail/` in `/etc/systemd/system/frontail.service`

`
[Unit]
Description=Frontail openHAB instance, reachable at http://%H:9001
Documentation=https://github.com/mthenw/frontail
Documentation=https://github.com/openhab/openhabian/issues/28
After=openhab2.service

[Service]
Type=simple
ExecStart=/usr/bin/frontail --ui-highlight --ui-highlight-preset ./preset/openhab.json -t openhab -l 2000 -n 200 /var/log/openhab2/openhab.log /var/log/openhab2/events.log
Restart=always
User=openhab
Group=openhab
Environment=PATH=/usr/bin/
Environment=NODE_ENV=production
WorkingDirectory=/usr/lib/node_modules/frontail/

[Install]
WantedBy=multi-user.target`

`sudo systemctl daemon-reload`
`sudo systemctl stop frontail.service`
`sudo systemctl start frontail.service`


Works on

OpenHabian Version:     2.4.0 (Build)

Linux openHABianPi 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux

**Comment by EliasGabrielsson** [comment]
@maestr0 Thanks for finding a solution to this.

**Comment by EliasGabrielsson** [comment]
This error will not be addressed by the openhabian scripts. Recommend to manually apply workaround described above.

**Comment by deutschmavic** [comment]
Fixed as mentioned above with an additional modification to ensure my code matched exactly at the line 
`ExecStart=/usr/bin/frontail`
