### ISSUE TITLE
Issue with link-local routes (169.254.x.x) on hardware with multiple NICs

### ISSUE THREAD

**Issue by asvilabs** [openhab/openhabian#433]
Hi, we have seen issues with Apple time-capsule device IP resolution on raspbian stretch.
When we investigated the issue, we found that Mint/Ubuntu has avahi-autoipd installed by default and raspbian doesn't.

It creates a routing table entry for link-local route (169.254.x.x). This entry allows selecting target interface when pinging Apple device from a multi-homed openhab server.

The time-capsule even if it has been assigned a static IP 10.0.1.1, intermittently get resolved (via MDNS) to link-local IP in range 169.254.x.x. On openhabian since link-local entry is missing, ping fails from Java and so does any other attempt to communicate with Apple device.

Avahi-autoipd package takes care of this (partially). It installs a hook in /etc/network/if-up.d/ that creates link-local route entry. See next post for caveats involved:

**Comment by asvilabs** [comment]
Actually its still in a very fuzzy state, even after adding avahi-autoipd, the interface eth1 (internet) is getting link-local route instead of eth0 (internal). We had to manually remove route and add a new one.

```
sudo /bin/ip route del 169.254.0.0/16
sudo /bin/ip route add 169.254.0.0/16 dev eth0 metric 1000 scope link
```

Need to ivestigate a better solution. But the original request is still valid. avahi-autoipd should be added to openhabian.

http://developer.apple.com/qa/qa2004/qa1357.html

**Comment by EliasGabrielsson** [comment]
Hi 👋
Well described issue with clear suggestions.
Adding `Avahi-autoipd`would be no issue, I will fix it.
About the multi-homed case please look into a good solution and make a pull request then we can discuss it from there.

**Comment by asvilabs** [comment]
Sorry, this will be closed from our end as we are in the process of migrating away from ESH/OH platforms.
