### ISSUE TITLE
Add the milestone build repository

### ISSUE THREAD

**Issue by thedannymullen** [openhab/openhabian#435]
Can the new milestone build repository be added to the install options?

Thanks!

**Comment by kaikreuzer** [comment]
To be precise: Besides the "unstable" and the "stable", there should be the "testing" repo offered as an option.

@ThomDietrich Any chance you could deal with that? Would make life of the users much easier!

**Comment by mstormi** [comment]
I've just created https://github.com/openhab/openhabian/pull/436.
Just need Thomas to review and commit it. But haven't heard anything recently from him so I guess he's very busy at the moment.

**Comment by BClark09** [comment]
I'll have a look at it and test now :)

**Comment by EliasGabrielsson** [comment]
Left a few comment about categorisation in the description text so they confirm with "unstable", "stable" and "testing". When @BClark09 gives thumbs up I will merge it.

**Comment by thedannymullen** [comment]
Thanks for prompt response!  I can test it once merged.

**Comment by EliasGabrielsson** [comment]
Fixed
