### ISSUE TITLE
Update Grafana to official ARM repository

### ISSUE THREAD

**Issue by PartTimeDev** [openhab/openhabian#437]
If I read it correctly https://github.com/fg2it/grafana-on-raspberry is discontinued, due to the arm support of [Grafana 5.2](https://grafana.com/grafana/download/5.2.3?platform=arm). See https://github.com/fg2it/grafana-on-raspberry/wiki#state-end-of-life

Please fix packages.sh accordingly, so we can get past version 5.1.4

Sowhere here around L442 I guess?!
https://github.com/openhab/openhabian/blob/ecf59c4227acf79f38f0f396be26ea379f5c6e8e/functions/packages.sh#L442

**Comment by EliasGabrielsson** [comment]
Thanks for notice. Put it in backlog for next version.

**Comment by EliasGabrielsson** [comment]
The current official APT repository does not support ARM architecture. 
Follow this thread: https://github.com/grafana/grafana/issues/12761

Until then a static updated package will be the way to go for ARM.
(Will post an initial PR later this weekend.)

**Comment by EliasGabrielsson** [comment]
Arm arch does currently only support static versions.
Update with ARM repository when ready; https://github.com/grafana/grafana/issues/12761
