### ISSUE TITLE
Minor openhabian-config issue

### ISSUE THREAD

**Issue by Terr4** [openhab/openhabian#438]
I found a minor issue in openhabian-config which shows an error message as a result.

OpenHAB: openHAB 2.3.0-1
OpenHabian Config Tool: 1.4.1-413(7799e0d)

Steps to reproduce:

1. run "sudo openhabian-config"
2. select "About openHABian"
3. on the next screen press ESC
4. You get the error message:

> There was an error or interruption during the execution
> of:
>    "00 | About openHABian    "
> Please try again. Open a Ticket if the error persists:
> https://github.com/openhab/openhabian/issues

So here is the ticket as instructed ;)

thanks!

**Comment by EliasGabrielsson** [comment]
Thank for input!
