### ISSUE TITLE
Inject configuration before installing: static ip

### ISSUE THREAD

**Issue by ghost** [openhab/openhabian#439]
Is there any chance to set up static IP before first boot please? 
I have no access to ext partition. No DHCP on network.

I have been trying change 

> cmdline.txt

file
adding

> ip=10.0.0.100

I was able to connect with pi on ssh but it stop on

> 2018-03-13_22:53:34_UTC [openHABian] Starting the openHABian initial setup.
> 2018-03-13_22:53:34_UTC [openHABian] Storing configuration... OK
> 2018-03-13_22:53:34_UTC [openHABian] Changing default username and password... OK
> 2018-03-13_22:53:34_UTC [openHABian] Setting up Ethernet connection... OK
> 2018-03-13_22:53:34_UTC [openHABian] Ensuring network connectivity... 

Then nothing.

Also I was try add adres to 

> openhab.config

no connection at all.

Please can any one give me any solution please?

**Comment by buczoprazy** [comment]
Wow so many ideas, that is amazing thanks.

**Comment by buczoprazy** [comment]
connect with DHCP then search your pi

**Comment by thedannymullen** [comment]
@buczoprazy   Were you able to get this to work in the end?

For the openhabian maintainers, here were my thoughts from the forum.  [https://community.openhab.org/t/static-ip-before-first-boot/51382/17?u=thedannymullen](url)

> 
> You may be able to modify the first-boot.sh file to copy a config file from the boot partition to the ext partition. Add a line in the file at the top cp netfile_from_sd /etc/netfile_where_it_goes.
> 
> I am unclear exactly how to setup the static ip using a file, it looks as if the dhcpd file needs to be modified. you could put it on the sd card then use a cp command to copy to the correct place.
> 
> If a reboot would be required to get the file read in you could add that into the first boot file also or just wait a few mins until you know nothing going on and manually power cycle.
> 
> Just an idea I had, It may work. If it does let me know, I am curious. I can’t try right now no spare sd card.
> 
> Note: if you want to reboot gracefully, you could look for the presence of a file or lack of file using if [ -f file ] xxx do a man on test or google for syntax. Something like:
> 

```

if [ -e myfile ] 

    then 

    rm -f myfile        

    reboot

fi
**double check syntax.

```
**My Idea:**
I was thinking maybe we could modify the first-boot.sh to contain a file for static ip addresses.  Maybe it could be called staticip-example.txt, if it were renamed to staticip.txt then the first boot script would act.  I am happy to try to for the file then write up the fix and contribute it back.  This of course is assuming you guys would like that contribution.  Please let me know.

**Comment by buczoprazy** [comment]
I would be happy with that, I am in. :)

**Comment by EliasGabrielsson** [comment]
I acknowledge the need of having static IP, DNS, gateway when installing. 
As the openhabian have a requirement of having headless installation injecting configuration beforehand is the way to go. I liked your idea @thedannymullen.

I would say a config file with predefined parameters which could be out comment provided in the SD root folder could be a good tradeoff in usability. Config parameters shall be strict seperate from the script itself. eg. first-boot.sh.

@thedannymullen would you like to spearhead a first implementation, make a pull request so we can discuss it from there?

**Comment by thedannymullen** [comment]
Yes let me start looking at it.  I believe I can have something in the next few days.

**Comment by thedannymullen** [comment]
@EliasGabrielsson I have this started.  Git won’t let me issue a pull so I am working offline for the time being.

**Comment by thedannymullen** [comment]
I have my initial changes ready to be merged.  
[static.sh.txt](https://github.com/openhab/openhabian/files/2431117/static.sh.txt)
[static_ip.txt](https://github.com/openhab/openhabian/files/2431118/static_ip.txt)

Once I am able to create a pull request I can make the changes and merge.

**Comment by alwashe** [comment]
please add hostname

**Comment by thedannymullen** [comment]
Hostname can already be configured using the openhabian config file.

There should be no need to add here, if so please explain.

**Comment by alwashe** [comment]
i did not know that, thx alot

**Comment by EliasGabrielsson** [comment]
@thedannymullen Nice to see progress. 
We really need a pull request though. It's enable us to efficiently review, comment and improve things together.

**Comment by thedannymullen** [comment]
Yes I agree!  GitHub won’t allow me to make one though.  Any suggestions?

**Comment by EliasGabrielsson** [comment]
1) Fork this repo ✔️ 
2) Create new branch in your fork locally eg.  `static ip`
3) Push branch to github in your fork
4) Navigate to this repo, pull req window will show, make request.

Google for details. There is plenty of good guides :-)

**Comment by thedannymullen** [comment]
Thanks will try.  This is my first one.

**Comment by EliasGabrielsson** [comment]
Nice! Welcome to the world of git with a lot of possibilities and opportunities to get lost in the commandline. ;-)

**Comment by mstormi** [comment]
@EliasGabrielsson I think we can close this one.

**Comment by mstormi** [comment]
See agreement in #458
