### ISSUE TITLE
Look into BerryBoot

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhabian#44]
https://community.openhab.org/t/openhabian-hassle-free-rpi-image/13379/325

**Comment by mstormi** [comment]
I don't think we would want to change our setup after another 3 yrs this ticket has been around, would we ?

**Comment by EliasGabrielsson** [comment]
I don't mind old ideas per say but don't think BerryBoot actually solves a problem we have. 

> For people short on SD cards

Doesn't feel like a real problem for us, i.e the cost of SD cards is marginal to all other expenses related to smarthomes. Closing this now.
