### ISSUE TITLE
optimize Java memory for Raspis and other lowmem SBCs

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#442]
I stumbled across [this ancient post](https://community.openhab.org/t/raspberry-pi-before-i-pull-the-trigger/4781/17), noticed openHABian still uses stock Java options, tried it and came to think that's a valuable optimization to put into openHABian.
PR to follow when I find the best place inside openhabian setup to place this.

**Comment by mstormi** [comment]
Created [PR #443](https://github.com/openhab/openhabian/pull/443)

**Comment by EliasGabrielsson** [comment]
Good finding Marcus! Merged :-)
