### ISSUE TITLE
usbip not working

### ISSUE THREAD

**Issue by stefanheijnen** [openhab/openhabian#446]
Rpi 3B+ openHABian image
Linux openhab 4.14.71-v7+ #1145 SMP Fri Sep 21 15:38:35 BST 2018 armv7l GNU/Linux

Today I tried to setup usbip following [this](https://community.openhab.org/t/forwarding-of-serial-and-usb-ports-over-the-network-to-openhab/46597) tutorial.

Sharing the BT adapter on my Manjaro desktop gives no errors:
```
sudo usbip --debug bind -b 3-2.4.1
usbip: debug: usbip.c:141:[run_command] running command: `bind'
usbip: info: bind device on busid 3-2.4.1: complete
```
On openHABian I'm greeted with:

```
sudo usbip --debug attach -r 10.0.1.1 -b 3-2.4.1
usbip: debug: usbip.c:141:[run_command] running command: `attach'
libusbip: error: udev_device_new_from_subsystem_sysname failed
usbip: error: open vhci_driver
usbip: error: query
```
BT dongle is visible on the network:
```
sudo usbip list -r 10.0.1.1
Exportable USB devices
======================
 - 10.0.1.1
    3-2.4.1: Cambridge Silicon Radio, Ltd : Bluetooth Dongle (HCI mode) (0a12:0001)
           : /sys/devices/pci0000:00/0000:00:08.1/0000:38:00.3/usb3/3-2/3-2.4/3-2.4.1
           : Wireless / Radio Frequency / Bluetooth (e0/01/01)
```
vhci_hcd is loaded:
```
lsmod |grep vhci
vhci_hcd               28672  0
usbip_core             16384  1 vhci_hcd
```
If I must believe [this](https://jon.sprig.gs/blog/post/657), it is because off missing userland tools.

**Comment by EliasGabrielsson** [comment]
Did you do an apt-get update / upgrade?

As I know openhabian in itself does not explicit install `usbip`, maybe it's and dependency of some package? We are using rasbian as base image so as long they update their repositories we will get patches down stream. What kind of base installation do you have, raspberry pi?

**Comment by stefanheijnen** [comment]
Yes my Pi is up to date. Correct, I've installed usbip manually. It is the latest Pi 3B+

**Comment by EliasGabrielsson** [comment]
Hmm. As long `usbip` is not explicit added by openhabian script we will not put any effort in updating it. I recommend you point this out upstream instead.
