### ISSUE TITLE
Java Cryptographic Extensions

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#447]
Users need to add JCEs to their Java install for the Eclipse marketplace to work (and probably more stuff to show up in the future).
See https://community.openhab.org/t/failed-downloading-marketplace-entries-received-fatal-alert-handshake-failure/52045/14

We should add this capability to openHABian as a menu option.
But note that I believe (at least I'm not sure) we cannot simply add a download line to the Java install routine(s) for legal reasons. Any user has to confirm Terms of Use for both, Oracle and Zulu JCE, so any install routine should maybe prefetch & present these and ask for download confirmation.

Oracle: https://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html
Zulu: https://cdn.azul.com/zcek/bin/ZuluJCEPolicies.zip

**Comment by gelsas** [comment]
Just running into this problem I placed the Zulu: https://cdn.azul.com/zcek/bin/ZuluJCEPolicies.zip files in the folder specified in the forum post. But it still shows up in the logs. Do I need to restart openhab for it to work ?

**Comment by p1ranha** [comment]
Adding those JAR's seems to break a lot of things including hue and the amount of errors in the log is much greater after the change.

**Comment by mstormi** [comment]
> 
> 
> Adding those JAR's seems to break a lot of things including hue and the amount of errors in the log is much greater after the change.

what does it break? what's the errors you're seeing and why do you think it's the JCE to cause that ?
