### ISSUE TITLE
Harden all services

### ISSUE THREAD

**Issue by jakobjp** [openhab/openhabian#448]
It would be great, if there was an installation option available that could install a hardened setup with all services only available via HTTPS with authentication.

(I.e. make openHAB, Node Red, Frontail etc. all ONLY accessible via HTTPS with authentication via reverse proxy.)

**Comment by EliasGabrielsson** [comment]
There is an ongoing discussion about this see: https://github.com/openhab/openhabian/issues/327
In term of prioritization there are more urgent fixes need to be made. Another aspect of this is that authentication layer is discussed to be integrated within openhab itself and I think we shall follow that track.

Closing this now but keep the discussion going in the other thread. Cheers.

**Comment by ThomDietrich** [comment]
Just a few comments:
1. Your steps do not increase the secureness of access to any of those services *from the public internet*. As you specifically point out, the important aspect is to configure the correct set of port-forwardings. Those steps are of course interesting in a bigger local subnet you can not trust (e.g. a dormitory LAN or a shared WiFi).
2. You did not "harden" services in the sense the word is used in network security circles. See this excellent guide: https://bettercrypto.org/static/applied-crypto-hardening.pdf
3. Feel free to add PRs for Frontail and NodeRED forwarding ;)
