### ISSUE TITLE
Java 11

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#450]
openHAB is to move to Java 11 soon, see [this](https://github.com/openhab/openhab-distro/issues/768) for current status.

We need to offer this to at least be an install option.

**Comment by EliasGabrielsson** [comment]
Notice license change from oracle when doing this.

**Comment by kaikreuzer** [comment]
> openHAB is to move to Java 11 soon

Not at all "soon" - we are just evaluating and trying to fix issues, so that IF someone uses Java 11 by accident can still use it. The recommendation will be Java 8 for the foreseeable future.

For openHABian, we use Zulu Embedded JVM, so Oracle licensing does not impact us.
There are no Zulu Embedded builds of Java 11 available, so this is another reason to stick to Java 8.

I'd suggest to only open an issue here once there is a decision to upgrade from 8 to anything newer.

**Comment by mstormi** [comment]
I disagree a little here and I think you shouldn't close it as fast as you did.
First, the issue is meant to provide Java 11 just as an install _option_ (not default) and I think it makes sense to have that available in openHABian *before* OH moves to Java 11 so people can start testing early.

Also remind you openHABian runs (and is supposed to run) on non-ARM hardware as well, and there's Java 11 Zulu on x86 already available.
Also, until now Oracle is a supported alternative on both, ARM and non-ARM, so either we decide to discontinue support for Oracle or we mustn't ignore licensing issues.

**Comment by kaikreuzer** [comment]
This issue made the impression as if there can/should be something done in openHABian. I don't agree that we should add features where we know that it is NOT working, just for the sake of testing.

> Also remind you openHABian runs (and is supposed to run) on non-ARM hardware as well

Ok, good point - I was so far only aware that we package Zulu embedded in the images (and I cannot see anything in the [features](https://github.com/openhab/openhabian/blob/master/docs/openhabian.md#optional-components) that mentions x86 JVMs as an install option).

> so either we decide to discontinue support for Oracle

Not sure who and why this has ever been added, but I'd be all for removing it indeed.

**Comment by ThomDietrich** [comment]
Hey guys!

>> so either we decide to discontinue support for Oracle
>
> Not sure who and why this has ever been added, but I'd be all for removing it indeed.

The routine was working when we decided to switch over to Zulu. At this point I decided to offer the Oracle solution as an alternative, in case Zulu created issues for some. Never removed it since.
@mstormi feel free to remove the menu entry.
