### ISSUE TITLE
Update habmin to latest version

### ISSUE THREAD

**Issue by peterloron** [openhab/openhabian#451]
The version of Habmin installed by openHABian 1.4.1 is 2.0.0, which is several releases behind the current. Please pull in an updated release. Thanks.

**Comment by EliasGabrielsson** [comment]
Hi Peter.
`habmin` is related to the openhab release which this tool (openhabian) integrate.
I think `habmin` follow that release track. You could try to change to openhabian unstable to get the bleeding edge of all packages. See option 41 in `openhabian-config`

**Comment by BClark09** [comment]
I believe the 2.0.0 string is hard-coded into habmin. It will show 2.0.0 but is indeed the latest version.

**Comment by peterloron** [comment]
Ah, ok. Thanks.
