### ISSUE TITLE
Revert hciuart service deactivation in else branch

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhabian#452]
Serial port options: The service unit `hciuart` must be re-enabled when 2 is not selected

https://github.com/openhab/openhabian/blob/de039dac49462990992cf127b82316202e639700/functions/system.sh#L324-L335

@EliasGabrielsson @BClark09 @mstormi I am signing for my apartment today and will restart work on openHABian in the next couple of weeks. Sorry for my long absence!

**Comment by BClark09** [comment]
Great news! It's good to hear from you again 😃

Good luck with the move in!

**Comment by mstormi** [comment]
Glad you're back. Will it really just take a couple of weeks to equip your apartment ?

**Comment by EliasGabrielsson** [comment]
Hi Thomas. Glad you are back! 
No hurry, get your life going first :-)

I have had sparse amount of time myself these month so focus have been on keep the project "floating" with focus on categorise and triage issues.
@mstormi Started looking on your MTA pull request. Have some thoughts, needs to summarize them into addressable action points we can discuss. Sorry for lagging behind.
