### ISSUE TITLE
javax.net.ssl.SSLHandshakeException - handshake_failure

### ISSUE THREAD

**Issue by Markkuuss** [openhab/openhabian#453]
The Zulu Embedded Java (1.8.0_152) included with openhabian causes some problems with TLS handshake. There is a newer version (1.8.0_181) on the homepage https://www.azul.com/downloads/zulu-embedded/ meanwhile. This fixes these bugs, so this version should also be included in the openhabian package.

See also: https://community.openhab.org/t/solved-http-binding-javax-net-ssl-sslhandshakeexception-handshake-failure/54253/3?u=mas

**Comment by mstormi** [comment]
We currently use the Azul repo for install, and seems _152 is the latest in there so we would need for that to get updated or rework the install system. Not sure if we wanna do the latter as there is no real need for _181. The TLS issue can also be fixed [by installing JCE](https://github.com/openhab/openhabian/issues/447) as well.

**Comment by EliasGabrielsson** [comment]
fixed by updated java packages
