### ISSUE TITLE
Install fails if default GW is not a DNS resolver

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#456]
Subject says it all I guess. Installation can (or will ?) fail if people don't have their router configured to properly work as a DNS resolver.
As a fix we should add a working DNS resolver such as 8.8.4.4 as a secondary entry to /etc/resolv.conf.

I'd do but I just din't find the right place yet alongside the Raspbian install process where resolv.conf is generated.

**Comment by EliasGabrielsson** [comment]
Let's align this with: https://github.com/openhab/openhabian/issues/439

**Comment by mstormi** [comment]
Err, no. #439 was a very weird wish from someone who was unwilling to provide an environment with the basic requisites. We should align with #458 .

**Comment by EliasGabrielsson** [comment]
Let's keep issues and PR apart, i.e. #458 is an implementation of the issue/discussion in #439.
Maybe the initial request was a bit off but it have been further developed in the thread as we can see.

**Comment by EliasGabrielsson** [comment]
Will be solved by discussed issues in thread
