### ISSUE TITLE
include Jython

### ISSUE THREAD

**Issue by mjcumming** [openhab/openhabian#461]
Would there be interest including Jython in the basic installation? There is a core group of users and developers supporting it on the forum. Including it would make it easier to attract additional users.

**Comment by EliasGabrielsson** [comment]
Hi @mjcumming!
Pull request are welcome. The few maintainer we have are at the moment are busy patching up core functionality so don't expect this in the short term. Sorry.

**Comment by EliasGabrielsson** [comment]
Related to this:
https://github.com/openhab/openhab-docs/pull/1012

**Comment by mstormi** [comment]
jython will be a jar in and thus part of OH 2.5+ so no (more) need to include it in openHABian
