### ISSUE TITLE
Inform user that reboot is required after openhabian.conf is changed

### ISSUE THREAD

**Issue by bodiroga** [openhab/openhabian#463]
Hi @ThomDietrich and guys!

I have noticed that, if I change the hostname in the openhabian.conf file right after flashing the SD card, the device doesn't change its hostname until a manual reboot is done. That's very confusing for new and inexperienced users, because they try to access their openHAB installation in the new URL: http://<new_hostname>.local:8080, but it doesn't work because the old http://openhabianpi.local:8080 url applies.

How could we address this? Could we store the "reboot requirement" information during the installation process and reboot the Raspberry Pi at the end of the process?

Many thanks and best regards,

Aitor

**Comment by mstormi** [comment]
Mmh, I don't see this to be a bug. If a user _manually_ changes hostname (instead of using the openhabian-setup menu) he should know what he's doing and how to proceed.
We cannot cater for any off-mainstream modifications.

**Comment by EliasGabrielsson** [comment]
You are technical correct Markus it's not a technical bug, but from a user perspective someone is confused about it.
What do you think off adding an information line in the config file?

**Comment by mstormi** [comment]
ok, I went for b)
https://github.com/openhab/openhabian/pull/582
