### ISSUE TITLE
Possible Memory Leak

### ISSUE THREAD

**Issue by jvincze84** [openhab/openhabian#469]
Hi All,

I'm experiencing possible memory leak in my OpenHABian (2.3.0) running on RP3.
**jconsole:**
![screenshot from 2018-11-23 12-18-35](https://user-images.githubusercontent.com/22055109/48943595-fc43dd80-ef23-11e8-9360-63eb7690875d.png)

System:
```plain
#################################
[budles.txt](https://github.com/openhab/openhabian/files/2610731/budles.txt)
#############################################
###############  openHABianPi  ################################################
###############################################################################
##        Ip = 172.16.0.250
##   Release = Raspbian GNU/Linux 9 (stretch)
##    Kernel = Linux 4.14.79-v7+
##  Platform = Raspberry Pi 3 Model B Rev 1.2
##    Uptime = 0 day(s). 0:1:11
## CPU Usage = 55.81% avg over 4 cpu(s) (4 core(s) x 1 socket(s))
##  CPU Load = 1m: 4.13, 5m: 1.22, 15m: 0.42
##    Memory = Free: 0.29GB (31%), Used: 0.65GB (69%), Total: 0.95GB
##      Swap = Free: 0.09GB (100%), Used: 0.00GB (0%), Total: 0.09GB
##      Root = Free: 40.53GB (90%), Used: 4.06GB (10%), Total: 47.06GB
##   Updates = 0 apt updates available.
##  Sessions = 0 sessions
## Processes = 135 running processes of 32768 maximum processes
###############################################################################
```

I've created heap dump, but failed to find the root cause of this memory consumption.

**Bundle list:**
[budles.txt](https://github.com/openhab/openhabian/files/2610734/budles.txt)

**MAT screens:**
![screenshot from 2018-11-23 13-44-23](https://user-images.githubusercontent.com/22055109/48944164-eb946700-ef25-11e8-85cb-372eab78968c.png)
![screenshot from 2018-11-23 13-32-55](https://user-images.githubusercontent.com/22055109/48944173-f2bb7500-ef25-11e8-9053-d282d84d319d.png)

Could somebody help me to find the problem?

Thanks,
Janos Vincze

**Comment by EliasGabrielsson** [comment]
Hi Janos!
Thanks for a detailed report. It looks like this related to OpenHAB itself which openhabian installs and configure. 

@kaikreuzer @martinvw @wborn 
In which repository is this best re-posted?

**Comment by jvincze84** [comment]
Hi,
Thanks for your reply.
If it helps I can share the HeapDump with you.
Br,
VJ

**Comment by wborn** [comment]
Can you also add a thread dump? It could be that due to deadlock lots of tasks are added to the queue but  they are never executed due to a lock not being released.

**Comment by jvincze84** [comment]
Hi All,
Thanks for your help.

You can download the dump from my GDrive: [heapdump.hprof.zip](https://drive.google.com/open?id=1wJgPzveueVQUgUnPQwGtZJhqMrkiA9pC)

Best Regards,
Janos Vincze

**Comment by wborn** [comment]
Looks like there are almost 1,5 million tasks in the queue for the `items` workers but for some reason all worker threads are blocked so they can't process these tasks. A thread dump would show why these worker threads are blocked.

**Comment by EliasGabrielsson** [comment]
I close this as it's not direct related to openhabian.
You are welcome to continue the discussion but I think it's better to open it in correct repo.
