### ISSUE TITLE
Transfer to openhab organization

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhabian#47]
@kaikreuzer
openHABian has gotten [quite mature](https://github.com/ThomDietrich/openhabian/graphs/traffic) over the last few months and has a [nice userbase](https://community.openhab.org/t/openhabian-hassle-free-rpi-image/13379) that helped test and improve it. I'd like to synchronize the release of "Version 1.0", the introduction of openHABian in docs (with the Big PR) and the transfer to the openhab organization. It would be great to do that before the next big announcement, meaning the openHAB beta 5 build. (Could also wait of course)

openHABian is at a state where I can just declare it as version 1.0, I could also settle a few more Issues, depending on the time I have. The documentation article is at the bare minimum right now, if I have the time, I could enhance it to a full blown description of what openHABian contains and how to use it. Transferring the project to the openhab organization will not be a big deal as GitHub will redirect the old URL.

What are your thoughts?

@BClark09 might also be interested in this, ping ;)

**Comment by kaikreuzer** [comment]
Sounds wonderful :-)

Two things to clarify before the move:
1. [LICENSE](https://github.com/ThomDietrich/openhabian/blob/master/LICENSE): As all of openHAB is under the EPL, would you be ok to license openHABian under the same terms?
2. CONTRIBUTING.md: It would be nice if you could add our standard text for how to contribute to the repo, see e.g. [openhab-docker](https://github.com/openhab/openhab-docker/blob/master/CONTRIBUTING.md) as an example. Related to this: As the current commit history does not comply to those rules (e.g. having all commits properly signed-off), it imho would make sense to squash the current history and be left with a single commit, which would be the starting point at the openHAB organisation.

**Comment by BClark09** [comment]
It would be great to see this as part of openHAB! I'm sure you've helped many people get started with openHAB with this too!

Since the "full" openHABian setup automatically installs "external" Linux tools and features, and can prompt users to install other programs automatically, is there a licence issue here too?

**Comment by ThomDietrich** [comment]
Hey @kaikreuzer, I feared to be hit with these kinds of problems. 

You have to know, that openHABian is based on [raspbian-ua-netinst](https://github.com/debian-pi/raspbian-ua-netinst) and resumed under the same license. Besides that other "external" software is only downloaded by the scripts but not contained in them. I would be okay to switch to EPL, I'm however not sure if I am allowed to do so. I believe you have more experience in this area. What do you think?

I'll be adding a CONTRIBUTING.md, that's not a problem and should have been there in the first place.

Regarding the sign-off: I see how this is a problem for you. As you know, almost all of my commits are PGP-signed, except for very few which were done from another PC or by GitHub. "Signed-off-by"-yadayada is not part of any of the commits as I personally never saw any reasoning for that, I will of course comply with that rule as soon as we agree to define it for this repository. I have no problem with that.

> imho would make sense to squash the current history and be left with a single commit

I'm very strongly against that. This seems like the worst thing anyone could ever do to a git repository and I'm afraid a baby octodex just died somewhere :smiley: No, seriously, do you see a way around that? Would a not-signed history from before the transition really be a problem?
I could `git filter-branch` hack the "signed-off-by" into all commits. That would be acceptable to me and should not create any problems for end users (the way the installation and the updater work). I would however like to avoid this step as you know this could create pretty awkward constellations...

**Comment by kaikreuzer** [comment]
> You have to know, that openHABian is based on raspbian-ua-netinst and resumed under the same license.

Well, then you have already violated the [LICENSE](https://github.com/debian-pi/raspbian-ua-netinst/blob/master/LICENSE), which states: 
```
Copyright (c) 2013 Toni Spets <toni.spets@iki.fi>
...
...provided that the above copyright notice and this permission notice appear in all copies.
```

So yes, under these circumstances, we can keep the license as is (assuming you restore the original copyright and maybe add yourself and any further contributors - or simply add an "and others" to the copyright, which makes it much simpler for the future (that's how the Eclipse Foundation handles it)).

> As you know, almost all of my commits are PGP-signed, except for very few which were done from another PC or by GitHub.

Besides your commits, there are also unsigned commits from @BClark09.

> This seems like the worst thing anyone could ever do to a git repository

Well, you didn't fork https://github.com/debian-pi/raspbian-ua-netinst either and build on it - you rather copied the content (thus losing the history) and taking that as an initial starting point.
I am asking the same here: Do not include any fuzzy history in the official repo that might contain shady content that is not immediately visible), with an unclear contribution agreement at the time of the commit etc. Think of your current repo being a feature branch that is used during development and squashed once being merged into the official repo. You can still keep a copy of all your history in a personal repo at Github.

**Comment by BClark09** [comment]
Apologies both, signing off commits was new to me coming into this project but have made sure it's embedded into my memory by now!

If these commits are squashed, then I'm assuming an also-by signoff is fine for the additional contributors?

**Comment by kaikreuzer** [comment]
> Apologies both, signing off commits was new to me coming into this project but have made sure it's embedded into my memory by now!

No need to apologize, so far this was not required on the openHABian repo, so you didn't do anything wrong here!

> If these commits are squashed, then I'm assuming an also-by signoff is fine for the additional contributors?

Yes, exactly, this would be my suggestion. @ThomDietrich would state with that line that he has your approval to commit your contributions under the given terms.

**Comment by ThomDietrich** [comment]
@kaikreuzer I just fixed the LICENSE and added CONTRIBUTING.md from openhab-docker (with some non-intrusive modifications). I hope they are to your liking.

The situation with raspbian-ua-netinst is a bit different. This project is a tool used in openhabian. As a comparison: you do not fork the twitter bootstrap repository when starting to work on a new website project...

Squashing everything will not bring any clarity and will in fact create what you were afraid of: a "fuzzy history" with potentially "shady content". A 120 commits history with clear content and authorship (linked to days long PR discussion threads) must be what we are all looking for. Isn't it!? I want to kindly ask to suggest another solution.

I could add "signed-off-by"s retroactively to all commits (will sever the GitHub references). I could recommit the whole source code in one signed commit. We could just leave everything as it is - the CONTRIBUTING rules were added only today and thereby no prior commits are bound to them (my preference).

**Comment by kaikreuzer** [comment]
> the CONTRIBUTING rules were added only today and thereby no prior commits are bound to them (my preference).

This is exactly the issue that I wanted to address. As there were no contributing guidelines before, the legal situation of that code is not clarified.

But ok, if you insist to keep the commit history in place, I give in.
What we imho need retroactively is a confirmation of all three committers that they confirm [these statements] for all previous commits that they have already done.

So @ThomDietrich, @BClark09 & @jupe76: Could you all leave a comment here that you confirm these statements?

**Comment by BClark09** [comment]
I can confirm and agree to the statements in the DCO for all my previous commits to this repo.

**Comment by ThomDietrich** [comment]
Thanks @kaikreuzer. I'm happy we found an agreement we both can live with. I am sorry for any inconvenience this might have created for you. After we got all three confirmations and signed-off-by's I'll additionally add a commit to mark this step in the commit history unrelated to GitHub.

---

I hereby confirm the statements in "Developer Certificate of Origin (Version 1.1)" for all previously done contributions in this project and agree to also comply to these in all my future contributions.

Signed-off-by: Thomas Dietrich <thomas.dietrich@tu-ilmenau.de> (github: ThomDietrich)

**Comment by jupe76** [comment]
I confirm the statements in the "Developer Certificate of Origin" for my previous commits to this repo and agree to also comply to these in all my future contributions.

Signed-off-by: Peter Jünger (peter.juenger@gmx.net)

**Comment by kaikreuzer** [comment]
Thanks for the quick response everyone, I have captured it in an image :-)

<img width="773" alt="screen shot 2016-12-14 at 21 21 34" src="https://cloud.githubusercontent.com/assets/3244965/21199318/53588130-c243-11e6-990f-1d5f0f962c04.png">

@ThomDietrich I gave you temporary admin access to the openhab organisation. With this, you should now be able to transfer the repository yourself - let me know in case there is anything I should help with!

**Comment by ThomDietrich** [comment]
@kaikreuzer The transfer is finished.
I followed what I saw and created a "openHABian Maintainers" team. I've not changed anything else.
I've also documented what we discussed here in https://github.com/openhab/openhabian/commit/9283848e6f9c86f4800ce6487a99561ae9adaff1

I think this issue can be closed.

**Comment by kaikreuzer** [comment]
Cool, many thanks and welcome openHABian at the openHAB org :-)
