### ISSUE TITLE
Google assistant not linked with openhab

### ISSUE THREAD

**Issue by mmike887** [openhab/openhabian#473]
Hi,
i'm tring to link my google account with open habian. 
When i tip + then select open hab, insert my account data i can't associate it with rooms. It drops 2 steps before.
A push that says "Your account is linked" comes out but no devices will be displayed in the list.

How can i solve? 
thank you very much in advance

**Comment by ThomDietrich** [comment]
Hey there!
The openHABian repository and its issue tracker is just for development of the openHABian openHAB base system/toolchain. We can't help with your specific question.

Please contact the openHAB community forum made for this kind of question. Many users will be able to help you. Best!
