### ISSUE TITLE
Add chown for Backup Script 

### ISSUE THREAD

**Issue by floriandd2ba** [openhab/openhabian#477]
Hello,

i spend some time to get the Amanda backup works.

For my opinion is an new line need in "openhabian/functions/backup.sh" after line 51 "/bin/chown ${backupuser}:backup ${storage}/Slots"
New line: /bin/chown backup:backup /media/test/slots/*

The first chown change the directory slots, but the subdirectories slot1-15 are still in ownership from root.
The user backup have no rights to write data in the slotX folders and failed.
After change the ownership of the subfolders the backup works for me.

Thx
Florian

**Comment by floriandd2ba** [comment]
Sorry,
after line 111 "   mkdir -p ${storage}/slots/slot${counter}" is the right place.
Better I go sleep now...

**Comment by EliasGabrielsson** [comment]
@mstormi can you take a look on this if you have some spare time?

**Comment by mstormi** [comment]
You're right, must have happened on last refactoring. Thanks for finding.
Fix in https://github.com/openhab/openhabian/pull/494
