### ISSUE TITLE
Installation fails on Stretch with unsigned repo error

### ISSUE THREAD

**Issue by brianwarner** [openhab/openhabian#479]
I'm installing OpenHabian stable on Debian Stretch.  I installed the missing `apt-transport-https` as reported in #478 and ran into a new issue.  The install is failing in step 03, and the reported reason is:
`E: The repository 'https://dl.bintray.com/openhab/apt-repo2 stable Release' is not signed.`
`N: Updating from such a repository can't be done securely, and is therefore disabled by default.`

I see that `openhab.sh` is attempting to add a key, and the operation succeeded.  However, I wonder if this is the right public key for this particular repo?  Does anybody have any thoughts?

Thanks!

**Comment by BClark09** [comment]
Hi @brianwarner this was an issue from https://github.com/openhab/openhab-linuxpkg but has now been fixed. Please try again and let us know if you have any more issues.

**Comment by brianwarner** [comment]
It worked!  Thanks @BClark09.
