### ISSUE TITLE
Separate "InfluxDB and Grafana" to individual parts

### ISSUE THREAD

**Issue by EliasGabrielsson** [openhab/openhabian#482]
Enable possibility to install InfluxDB or Grafana individually.

**Comment by EliasGabrielsson** [comment]
There was a request to explicit install Grafana without the use of influxDB. It kind of make sense as InfluxDB could easily (or other databases in general) write down the SD card used by RPi and other boards. Current setup prerequisite that an InfluxDB is available.

I think an implementation should support:
* Separate installation but still keep capability of auto configuration.
* Maybe add an SQL database or such supported both by OpenHAB as well as Grafana.

**Comment by mstormi** [comment]
I don't see a point in this any more. Grafana without any database whatsoever does not make sense,
and the current install procedure allows for using an external InfluxDB instance, too.
If installed locally, default use of ZRAM for all persistence data mitigates SD wearout.

**Comment by mstormi** [comment]
Separating installs might lead to problems with non-matching program versions or config hence I don't want to offer that.

And installing InfluxDB does not mean to make use of it.
Anyone can choose to install via openHABian and change config such that it ain't used. They can also disable or purge manually.
