### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by bsadams1999** [openhab/openhabian#487]
I've tried installing several times, I continue to get an error when trying to update Openhab 2.  

It says the repository is not signed, then stops install

Manual update gives same error.  Any suggestions?

**Comment by ThomDietrich** [comment]
@EliasGabrielsson any pointers? I installed a fresh system a few days ago (before openHAB 2.4) and had no problems.

**Comment by EliasGabrielsson** [comment]
I have not looked into this yet so I don't know really.
@bsadams1999 Did you do a retry on the installation? Same results?

**Comment by bsadams1999** [comment]
@EliasGabrielsson I tried again last night, it worked fine using the openhabian-config and manual steps.  I think the mirror must have been down this weekend.   

The site is working and i have configured a dashboard BUT when I reboot, it tries to install again with an error.   How do I fix first boot so it doesn't try to install again?

**Comment by EliasGabrielsson** [comment]
Try this I think it will solve it. Otherwise is my recommendation to do a new reinstallation.

```
rm -f /opt/openHABian-install-inprogress
touch /opt/openHABian-install-successful
```
