### ISSUE TITLE
Menu options in openHABian are a bit confusing for new users

### ISSUE THREAD

**Issue by jameshiscott** [openhab/openhabian#49]
Hi Thom,

I find the menu options in openHABian a bit confusing for new users. I was never sure which open is actually needed to just update openHAB (until looked over the code).

Looking to try and help however I can so happy to do a pull request with my recommended changes for you to review.

**Comment by ThomDietrich** [comment]
Hey @jameshiscott, thanks for your feedback. That's much appreciated. I'm currently working on a page for docs.openhab.org on openhabian, which will describe more details. Would be great to get some feedback from you there!

Could you tell me what you find confusing about the menu options? Each entry will do one thing and almost each entry opens a second dialog with detailed explanation. I've actually [added one](https://github.com/ThomDietrich/openhabian/blob/master/openhabian-setup.sh#L980-L992) of these to "Basic Setup" right before you wrote your ticket yesterday :) This dialog also answers your question regarding updating openHAB.

**Comment by jameshiscott** [comment]
I made some changes to the main menu titles in a fork i have locally (was trying to see if i could sort the frontail addition (#28) but my skill level was not good enough), but will post the suggestions on hear.

The second dialog information looks good and should go a long way to solving the problem, defiantly happy to help with the docs and will post the updates when i get home (fork is on my home PC not laptop)

**Comment by jameshiscott** [comment]
My changes:
```
  "01 | Update"                 "Pull the latest version of the openHABian Configuration Tool (no changes to openHAB itself are made)" \
  "02 | Basic Setup"            "Perform all basic setup steps recommended for openHAB 2 on a new Raspbian system (install VIM, adjust memory split, etc)" \
  "03 | Java 8"                 "Install the latest Revision of Java 8 provided by WebUpd8Team (needed by openHAB 2)" \
  "04 | openHAB 2"              "Pull and install the latest openHAB 2 snapshot (or update your current install to the latest version)" \
```

Again happy for this to just go in docs if you would prefer it

**Comment by ThomDietrich** [comment]
Hey @jameshiscott,
I attended to your suggestions. One problem I'm having is, that the length of the menu line is restricting me from longer explanations. The second dialog information should be okay for that.
I realized, that the main problem is, that you (and others) are not sure about if or if not the first few options need to be executed once, never or in certain situations. That's something I mentioned in some changelog once but I see the confusion. I will have to move these entries (2,3,4,5) into a submenu with additional description. While I'm at it, I might do the same thing to the optional components.
What do you think?

**Comment by jameshiscott** [comment]
@ThomDietrich  sounds like you have hit the nail on the head, i like the move things into a sub menu idea as well.

**Comment by EliasGabrielsson** [comment]
I think some submenus would to great for this installer, especially if there will be a lot of contributions coming. When I where coding the password change menu I start to wonder if a overview structure like this could clear things up a bit:

```
  "01 | Initial installation"                 "Steps to install necessary components to get a running system.  " \
  "02 | Raspberry"            "Specific tuning and addons for the Raspberry Pi series of computers" \
  "03 | Pine64"            "Specific tuning and addons for the Pine64 series of computers" \
  "04 | Optional components"                 "Addons which is not directly a part of openhab but could be essential the smarthome." \
  "05 | Maintenance"            "Menu for script like backup and password management." \
  "04 | About"              "Pull and install the latest openHAB 2 snapshot (or update your current install to the latest version)" \
```

The script itself could also reflect these menus so it's easy to navigate in the code. I guess the setup script could be rather long if there are many components added.

**Comment by mstormi** [comment]
With submenus in place and no news in years I think we can close this
