### ISSUE TITLE
Grafana setup always tries to install armhf instead of actual architecture

### ISSUE THREAD

**Issue by GruensFroeschli** [openhab/openhabian#495]
Clean debian stretch installation.

**Comment by GruensFroeschli** [comment]
functions.sh
influxdb_grafana_setup()
Lines 608 and 614
The checks on the architecture do nothing because this is not a bash "if" statement but a value assignment.

**Comment by EliasGabrielsson** [comment]
Thanks again for fixing this 👍 
Closing this now.
