### ISSUE TITLE
Initial configuration of shellcheck and relevant cleanup

### ISSUE THREAD

**Issue by GruensFroeschli** [openhab/openhabian#498]
While debugging issue #495 i let shellcheck run on the various scripts in this repository.

Is it desirable to improve the code based on the output of shellcheck?

After looking through the output, most of the messages can be ignored afaik, but there are some which may prevent the scripts from running in certain setups.
e.g on systems where bash symlinks to ash (OpenWRT/LEDE or other low resource environments) you can't assign a local variable a value at declaration.

I couldn't find anything regarding coding style (not in CONTRIBUTING.md, or elsewhere).
Are pullrequests which only "fix" coding style to "solve" messages from shellcheck welcome?

BR
Matthias

**Comment by GruensFroeschli** [comment]
Regarding coding style:
What is the preferred style for indention?
I see several styles mixed together, not even consistent in itself.
I haven't seen any tabs, so i guess all spaces?
Would 2 spaces per indention level be good to be enforced everywhere?

**Comment by EliasGabrielsson** [comment]
Hi Matthias!
First off glad to see that you would like to contribute more on this project. 👍 

> Is it desirable to improve the code based on the output of shellcheck?

Shellcheck was added early last year in a effort to improve the codebase by @ThomDietrich.
No one have had time to explore it and correct the codebase yet,  *but it's desired*.

> e.g on systems where bash symlinks to ash (OpenWRT/LEDE or other low resource environments) you can't assign a local variable a value at declaration.

The current "supported" hardware platforms are all `Raspberry Pi` boards plus `pine64`.
`Debian 9 Stretch` and `Ubuntu 18.04` for `amd64` is also "supported".
With that said does your finding above fit into these categories?

> I couldn't find anything regarding coding style (not in CONTRIBUTING.md, or elsewhere).

I have notice this myself and kind of miss it. If you would like to give guidance and spearhead a code guide you are very welcome. Things which have come to my mind:

* Have tried to make some method comments seen for example [here](https://github.com/openhab/openhabian/blob/e88aed01fce54602485f565109d04ace70e06b19/functions/packages.sh#L844) . Does shellcheck have any recommendation on method description or testcases against it?
* How to use GUI menus look like in general. Header etc.
* In which case could the script interact with the openHAB installation and what needs to be confirmed by the user. Eg. shall openhabian be allowed to install a binding through the API?
* Enforce greater use of `local` varible
* Error handling

> Are pullrequests which only "fix" coding style to "solve" messages from shellcheck welcome?

More then welcome!

> What is the preferred style for indention?

No one officially decided, but I use two spaces.

> Would 2 spaces per indention level be good to be enforced everywhere?

Let's decide that here and now and then enforce it. **We use 2 spaces**.

**Comment by GruensFroeschli** [comment]
So i sent a PR with the work I've done so far.
I'm not sure if i was able to test all the changes i did.
However since almost all changes are non-functional i don't see much risk of anything breaking.

**Comment by ThomDietrich** [comment]
Hey guys! Happy to see you are picking this up. @GruensFroeschli thanks for your work.
As Elias already said: I integrated shellcheck because I was anyhow using it. By the time I did however not have time to improve settings or attend to all errors. That is why (1) errors are ignored atm and (2) I'm very happy to see your addition! 😉 👏

**Comment by ThomDietrich** [comment]
#510

**Comment by GruensFroeschli** [comment]
I started a first attempt at coding style guide.
What do you guys think about linking to this
https://google.github.io/styleguide/shell.xml

**Comment by EliasGabrielsson** [comment]
Follow discussion here: https://github.com/openhab/openhabian/issues/519
