### ISSUE TITLE
Enable Hardware Watchdog of the pi

### ISSUE THREAD

**Issue by FipsJr** [openhab/openhabian#50]
I'm not sure if the built in hardware watchdog of the pi is enabled (default = off), e.g. when openHAB isn't responding any more or something else gets instable.
If not already done, you should think about enabling the hw wd.

**Comment by zdzichu** [comment]
This is the job for the operating system itself - you can enable `RuntimeWatchdogSec=` in `/etc/systemd/system.conf`

OTOH, it would be nice if openHAB implented sd_notify() support, with application level watchdog.

**Comment by ThomDietrich** [comment]
@zdzichu the first part of your answer would be something in the scope of openHABian.

I'd be careful with adding all kinds of things, just because we can. The reason for adding a watchdog are not yet clear to me. I did not yet experience nor hear of an openHAB freeze/crash and if any part of the RPi hardware is unstable, it's probably wise to take care of that issue instead of automatically restarting.

Please enlighten me if I'm wrong. :wink:

Regarding `sd_notify()`: Could you name the possibilities?

**Comment by zdzichu** [comment]
Hi,

First, I'm sorry. I misread this bugreport, thinking it is about openHAB itself. It is not, this is a bugreport about openhabian. In such case, enabling system-wide watchdog in systemd is a good idea, and setting `RuntimeWatchdogSec=` is something that should be done by the distribution makers.


Now, answering to your question, Thom. Adding application-level watchdog is done to make sure application always run, and is restarted if hangs. But in case of openHAB this won't help. During few years of using openHAB, I _never_ saw it hang. Is is so stable, there's noting to improve here :)
(I quite often see REST interface hang, requiring restart of openhab itself, but this case won't be caught by app watchdog).

Adding application watchdog is often tiny addition on top of basic systemd-notify implementation. This protocol is mainly for: a) informing systemd that application started and is ready to work; b) providing extended status info for administrator to see.
Now, with a) - when systemd knows exactly when application is ready, it can start any other services depending on openhab running at this moment. Without this, other application must resort to sleep & retry.

Implementation of systemd notify protocol is very simple, see here for example: https://github.com/faljse/SDNotify  . But, having said all above, I don't see any obvious advantages of doing this in openHAB. It would be _nice_, but there is no great improvement to gain.

**Comment by ThomDietrich** [comment]
Thanks for the exhaustive explanation! I'll tag @kaikreuzer 

If you think an integration would give us certain benefits or new possibilities, you could create a PR! ;)

**Comment by ThomDietrich** [comment]
I can actually think of a simple use case. The method `SDNotify.sendStatus()` could be used to inform systemd about the current state of openHAB. Users in the forum often think their installation is "working" because systemctl status says "active" ...

**Comment by skatun** [comment]
My openhabian which is a very early version, hangs like every 2 month or so(I think this is due to the DMX binding or http binding). I have solved it by physically solder a switch to the power supply! This way my guest can easily restart it when needed.

**Comment by mstormi** [comment]
already tagged "wontfix" and no news in 2,5yrs so I guess we should close this.
