### ISSUE TITLE
Check for java runtime during openHAB setup routine

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhabian#514]
During a time when the java installation failed due to a bug in the code base, the installation of openHAB continued without problems. Should we actively check for a java runtime during openHAB setup?

----

I am affraid the install did not succeed. It stalls at `2019-01-11_17:15:58_CET [openHABian] Waiting for openHAB to become ready...`.
I checked the status of openhab2 on a different console:
```
sudo service openhab2 status
● openhab2.service - openHAB 2 - empowering the smart home
   Loaded: loaded (/usr/lib/systemd/system/openhab2.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2019-01-11 16:41:22 CET; 30ms ago
     Docs: https://www.openhab.org/docs/
           https://community.openhab.org
  Process: 3529 ExecStop=/usr/share/openhab2/runtime/bin/karaf stop (code=exited, status=1/FAILURE)
  Process: 3510 ExecStart=/usr/share/openhab2/runtime/bin/karaf $OPENHAB_STARTMODE (code=exited, status=1/FAILURE)
 Main PID: 3510 (code=exited, status=1/FAILURE)

Jan 11 16:41:22 openHABianPi systemd[1]: openhab2.service: Failed with result 'exit-code'.
```

_Originally posted by @elektronaut69 in https://github.com/openhab/openhabian/issues/508#issuecomment-453575181_

**Comment by EliasGabrielsson** [comment]
Hmm, I would say we should:
* Do the Java routine more robust if needed
* Run the "installation-test" from bats to verify a complete installation.

and not check for java in openhab routine

**Comment by mstormi** [comment]
What about this in the light of current codebase ? Close? Superseded by #723?

**Comment by mstormi** [comment]
With a bats test from #682 and Travis builds to fail if Java install fails, would we need to do anything else ? I think no and will close this issue unless you come back with a response in the next 2 weeks.
