### ISSUE TITLE
constantly starting + stopping openhab2 

### ISSUE THREAD

**Issue by Hasplit** [openhab/openhabian#515]
It just keeps stopping and starting after it installs
![20190110_223406](https://user-images.githubusercontent.com/42632016/51061520-94c01b00-15c1-11e9-870b-da7a98e09483.jpg)

**Comment by ThomDietrich** [comment]
Hello @Hasplit this issue is related to #508 and we will fix it within the hour. It would be best to follow that issue, then start with a fresh flash of the image. Sorry for the inconvenience!
