### ISSUE TITLE
Codestyle guide 

### ISSUE THREAD

**Issue by EliasGabrielsson** [openhab/openhabian#519]
Reference work done by others:
https://google.github.io/styleguide/shell.xml

**Comment by EliasGabrielsson** [comment]
@GruensFroeschli Let's continue the discussion of the code guide in a separate issue

**Comment by EliasGabrielsson** [comment]
Full path: `/bin/apt` vs "normal"-path: `apt`

**Comment by ThomDietrich** [comment]
to be discussed... ;)

**Comment by EliasGabrielsson** [comment]
From other thread: 

    Have tried to make some method comments seen for example here . Does shellcheck have any recommendation on method description or testcases against it?
    How to use GUI menus look like in general. Header etc.
    In which case could the script interact with the openHAB installation and what needs to be confirmed by the user. Eg. shall openhabian be allowed to install a binding through the API?
    Enforce greater use of local varible
    Error handling

**Comment by EliasGabrielsson** [comment]
Pick best part of this one: https://google.github.io/styleguide/shell.xml

**Comment by mstormi** [comment]
What's the way forward on this - is there any concrete TODO ?

**Comment by mstormi** [comment]
@ecdye did a good job in writing down what's been in use and 'floating around' in
https://github.com/openhab/openhabian/blob/master/CONTRIBUTING.md#codestyle

That's a good starter we can work based on.

Feel free to raise additional items for discussion and eventually document results in `CONTRIBUTING.md`.
