### ISSUE TITLE
[Feature request] One click password changer

### ISSUE THREAD

**Issue by EliasGabrielsson** [openhab/openhabian#52]
I miss a menu which could handle all password changes for the system.

* pi user -> `passwd`
* Samba user, openhab -> ?
* HTTP basic authentication for nginx HTTPS setup.

I also wonder if it would be easier for the end user if the Samba account (openhab) and local admin (pi) would have the same username, eg. `openhab-admin`. Then there could be one "set admin password promt" which changes both passwords.

**Comment by ThomDietrich** [comment]
Hey Elias,
I've been thinking about that too. I guess your idea came after you saw the "Please change the default password" dialog, which is actually only a few days old. The possibility to change all passwords right from the menu would be nice indeed.

* system users (pi) -> `passwd`
* samba users (openhab) -> `smbpasswd` ([Example](https://github.com/openhab/openhabian/blob/master/openhabian-setup.sh#L285-L286))
* karaf ssh login -> menu entry "06 | Karaf Console"
* nginx HTTP(S) auth -> `htpasswd` ([Example](https://github.com/openhab/openhabian/blob/master/openhabian-setup.sh#L877))

Regarding the samba user: that would be possible. Would probably make a few things easier. I will need to look into this. In the end I would like to see one menu entry to change all passwords. 

Do you want to help in any of these parts?

**Comment by EliasGabrielsson** [comment]
I can look into it and see what I could manage to come up with. I am currently working to get a install script for some telldus parts as well.

**Comment by ThomDietrich** [comment]
Thanks again!
