### ISSUE TITLE
InfluxDB error

### ISSUE THREAD

**Issue by coolduke666** [openhab/openhabian#521]
hi,

I always get these error when installing influxDB and Grafana on a RPI3 with openhabian-config - Grafana Install works but I can't start influxDB manually... any ideas? thx

$ apt -y install influxdb 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  influxdb
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 43.0 MB of archives.
After this operation, 93.2 MB of additional disk space will be used.
Get:1 https://repos.influxdata.com/debian stretch/stable armhf influxdb armhf 1.7.2-1 [43.0 MB]
Fetched 43.0 MB in 6s (6,717 kB/s)                                                                                                                  
Selecting previously unselected package influxdb.
(Reading database ... 46257 files and directories currently installed.)
Preparing to unpack .../influxdb_1.7.2-1_armhf.deb ...
Unpacking influxdb (1.7.2-1) ...
Setting up influxdb (1.7.2-1) ...
chown: invalid group: ‘influxdb:influxdb’
chown: invalid group: ‘influxdb:influxdb’
Processing triggers for man-db (2.7.6.1-2) ...
Updating FireMotD available updates count ... 

$ systemctl daemon-reload 

$ systemctl enable influxdb.service 

$ systemctl restart influxdb.service 
OK Configure InfluxDB admin account... curl: (7) Failed to connect to localhost port 8086: Connection refused
FAILED Configure listen on localhost only... 
$ sed -i -e /^# Determines whether HTTP endpoint is enabled./ { n ; s/^# enabled = true/enabled = true/ } /etc/influxdb/influxdb.conf 

$ sed -i s/# bind-address = ":8086"/bind-address = "localhost:8086"/g /etc/influxdb/influxdb.conf 

$ sed -i s/# auth-enabled = false/auth-enabled = true/g /etc/influxdb/influxdb.conf 

$ systemctl restart influxdb.service 
FAILED 
Setup of inital influxdb database and InfluxDB users... curl: (7) Failed to connect to localhost port 8086: Connection refused
curl: (7) Failed to connect to localhost port 8086: Connection refused
curl: (7) Failed to connect to localhost port 8086: Connection refused
curl: (7) Failed to connect to localhost port 8086: Connection refused
curl: (7) Failed to connect to localhost port 8086: Connection refused

**Comment by EliasGabrielsson** [comment]
Thanks for reporting and identified the issue. It's strange that the user and group aren't created.
I will look into it when time permits. If you have a fix already made up please provide an PR.
