### ISSUE TITLE
Create specific "openhabian" line in configuration file: /etc/defaults/openhab2 

### ISSUE THREAD

**Issue by johanneskropf** [openhab/openhabian#522]
Hello, on a Raspberry 3B+ running openhabian and Openhab 2.4 I encounter an issue where if I check the three prepare serial port options in preparation of a razberry and than reboot I can't reach the openhab2 service anymore. I can connect to the Pi over SSH without an issue. But can't reach anything openhab related. This perceists if I reboot. Once I uncheck the options again and I reboot everything is back to working normally.

**Comment by ThomDietrich** [comment]
Hey Johannes,
could you please switch on the third option, then post the content of your `/etc/defaults/openhab2` file? Thank you

**Comment by johanneskropf** [comment]
I will switch on only the the third option and than send a copy of the EXTRA_JAVA_OPTS. The only thing that is in there now that I  added is Symlink stuff.

**Comment by johanneskropf** [comment]
Openhabian adds this:

EXTRA_JAVA_OPTS="-Xms250m -Xmx350m -Dgnu.io.rxtx.SerialPorts=/dev/ttyUSB0:/dev/ttyS0:/dev/ttyS2:/dev/ttyACM0:/dev/ttyAMA0"  # serial ports added by openHABian
EXTRA_JAVA_OPTS="-Xms250m -Xmx350m -Dgnu.io.rxtx.SerialPorts=/dev/ttyUSB0:/dev/ttyS0:/dev/ttyS2:/dev/ttyACM0:/dev/ttyAMA0"  # serial ports added by openHABian

It over wrote my Symlinks 🤨
When I un check the option in the Openhabian configs it leaves the /default/ooenhab2 like this

EXTRA_JAVA_OPTS="-Xms250m -Xmx350m"
EXTRA_JAVA_OPTS="-Xms250m -Xmx350m"

I already noticed one line of this was there when I created my Symlinks and I didn't put it there. I guess itmust have been created when I tried the Serial Options in the Config before. Does it need to be there? I deleted it right now and only left my rewritten Symlink line in there.
Hope this is what you were after

**Comment by ThomDietrich** [comment]
First thing to note: We shouldn't blindly overwrite user-provided options like your Symlinks addition.

Secondly: The name `EXTRA_JAVA_OPTS` is just a variable and is such will be overwritten by a second line. The first one in your case does hence not matter to the system. You'd need to do something like this (not tested):

```
EXTRA_JAVA_OPTS="my specific symlinks stuff" # user defined
EXTRA_JAVA_OPTS="-Xms250m -Xmx350m $EXTRA_JAVA_OPTS" # openHABian, do not edit
```

**Comment by johanneskropf** [comment]
My Symlinks were never working right, now that I put it in one line like this:

EXTRA_JAVA_OPTS="-Xms250m -Xmx350m -Dgnu.io.rxtx.SerialPorts=/dev/ttyEnocean:/dev/ttyZwave:/dev/ttyZigbee"

They are working just fine. So it doesn't seem to work to have two lines of EXTRA_JAVA_OPTS in the openhab2 file.

**Comment by paulipaul** [comment]
Hello,
I have a similar problem but I don't use Symlinks.
I have a fresh installed Openhabian with OpenHab. I did not configure OpenHab 2 yet.
When I check the three serial Ports setting (especially the third one) OpenHab won't start.

When I type in 

> sudo systemctl status openhab2 <

I get following error message:

`openhab2.service - openHAB 2 - empowering the smart home
   Loaded: loaded (/usr/lib/systemd/system/openhab2.service; enabled)
   Active: deactivating (stop) (Result: exit-code) since Sat 2019-01-19 19:16:44 CET; 643ms ago
     Docs: https://www.openhab.org/docs/
           https://community.openhab.org
  Process: 3730 ExecStart=/usr/share/openhab2/runtime/bin/karaf $OPENHAB_STARTMODE (code=exited, status=1/FAILURE)
 Main PID: 3730 (code=exited, status=1/FAILURE);         : 3842 (karaf)
   CGroup: /system.slice/openhab2.service
           └─control
             ├─3842 /bin/sh /usr/share/openhab2/runtime/bin/karaf stop
             ├─3918 /usr/bin/java -version
             └─3919 grep ^IBM

Jan 19 19:16:42 openHABianPi systemd[1]: Started openHAB 2 - empowering the smart home.
Jan 19 19:16:43 openHABianPi karaf[3730]: Error: Could not find or load main class serial
Jan 19 19:16:43 openHABianPi systemd[1]: openhab2.service: main process exited, code=exited, status=1/FAILURE`

**Comment by EliasGabrielsson** [comment]
```
EXTRA_JAVA_OPTS="my specific symlinks stuff" # user defined
EXTRA_JAVA_OPTS="-Xms250m -Xmx350m $EXTRA_JAVA_OPTS" # openHABian, do not edit will be automatic overwritten.
```
@ThomDietrich Having one "line" for openhabian like your idea above is great. I think we should create a helper function handling this, eg.

```
## Add Java option to openhab used while starting the service
## 
##      addOpenhabOption(String option) { 
## 

addOpenhabOption() {
 - Adds new option to openhab config file.
 -  Create specific openhabian line if not exist
}
```

This also ensures that we can write tests for it ;-)

**Comment by ThomDietrich** [comment]
@EliasGabrielsson 🎖 for thinking generalized AND test driven 😊 

There are 2-3 spots that need to be replaced.
The default option introduced by @mstormi would need to be part of the function?

**Comment by mstormi** [comment]
I'd think there is no longer a need for this.
* Java does not need extra params (possibly we can even omit the Xms/Xmx in Java 11)
* -Dgnu.io is deprecated (#883)
* Menu option 35 was rewritten in #861
