### ISSUE TITLE
Grafana missing configuration parameter org_name

### ISSUE THREAD

**Issue by EliasGabrielsson** [openhab/openhabian#523]
Missing `org_name` see comment below.

> Just a comment,
> I'm not sure but I think that org_name is mandatory now when authorizing anonymous access
> in section
> [auth.anonymous]
> (line 639 of this commit)
> I didn't check with this unattend install script, so maybe it works by default.
> Just in case

https://github.com/openhab/openhabian/commit/99530fb20b62ae52add8a6bc8f62dc527439cd29

**Comment by EliasGabrielsson** [comment]
@aymeric106 reposting your comment here so it doesn't get lost.

**Comment by holgerfriedrich** [comment]
@EliasGabrielsson had a short look at this when I worked on #860, I don't think we should do anything here. Putting an org_name requires the corresponging org name to be created in Grafana. Not setting it defaults the value to "Main Org." which does exist.

As nobody reported any problem here, I think we can close the ticket.

**Comment by mstormi** [comment]
Sounds reasonable to me.
@EliasGabrielsson please reopen if you disagree.
