### ISSUE TITLE
OpenHABian systemd service fails after openhabian-config serial reconfiguration

### ISSUE THREAD

**Issue by reinierhamstra** [openhab/openhabian#529]
Hey guys,

I just did a fresh install of OpenHABian and all seems to be working well until I use the openhabian-config > system settings > serial and tick all three options in order to enable the serial ports for use with a Razberry2 add-on board. 

When not configuring the third option (Add common serial ports to openHAB JVM) the Openhab systemd process keeps running fine.

Note: I have not yet plugged in the Razberry2 GPIO board or done any configurations inside OpenHAB2 yet at this point, nor have I installed Z-Way or any other additional packages or upgraded anything through the openhabian-config menu options.

When enabling all three options I get the following output after which I do a reboot. .

`Adding 'enable_uart=1' to /boot/config.txt`
`Removing serial console and login shell from /boot/cmdline.txt and /etc/inittab`
`Disabling serial-getty service`
`$ systemctl stop serial-getty@ttyAMA0.service `
`$ systemctl disable serial-getty@ttyAMA0.service `
`$ systemctl stop serial-getty@serial0.service `
`$ systemctl disable serial-getty@serial0.service` 
`$ systemctl stop serial-getty@ttyS0.service `
`$ systemctl disable serial-getty@ttyS0.service` 
`Adding 'dtoverlay=pi3-miniuart-bt' to /boot/config.txt (RPi3)`
`Adding serial ports to openHAB java virtual machine in /etc/default/openhab2`

This leads to the following entry in /etc/default/openhab2:

`EXTRA_JAVA_OPTS="-Xms250m -Xmx350m -Dgnu.io.rxtx.SerialPorts=/dev/ttyUSB0:/dev/ttyS0:/dev/ttyS2:/dev/ttyACM0:/dev/ttyAMA0"`

After reboot this leads to a failing systemd service with the following systemctl and journalctl messages:

######### systemctl #########

`[00:36:36] openhabian@openHABianPi:~$ sudo systemctl status openhab2.service `
`● openhab2.service - openHAB 2 - empowering the smart home`
 `  Loaded: loaded (/usr/lib/systemd/system/openhab2.service; enabled; vendor preset: enabled)`
`   Active: activating (auto-restart) (Result: exit-code) since Thu 2019-02-14 00:36:33 CET; 4s ago`
`     Docs: https://www.openhab.org/docs/`
`           https://community.openhab.org`
`  Process: 1152 ExecStop=/usr/share/openhab2/runtime/bin/karaf stop (code=exited, status=1/FAILURE)`
`  Process: 1034 ExecStart=/usr/share/openhab2/runtime/bin/karaf $OPENHAB_STARTMODE (code=exited, status=1/FAILURE)`
` Main PID: 1034 (code=exited, status=1/FAILURE)`

`Feb 14 00:36:33 openHABianPi systemd[1]: openhab2.service: Control process exited, code=exited status=1`
`Feb 14 00:36:33 openHABianPi systemd[1]: openhab2.service: Unit entered failed state.`
`Feb 14 00:36:33 openHABianPi systemd[1]: openhab2.service: Failed with result 'exit-code'.`
`

######### journalctl -xe #########

`-- The start-up result is done.`
`Feb 14 00:39:27 openHABianPi karaf[5855]: Error: Could not find or load main class serial`
`Feb 14 00:39:27 openHABianPi systemd[1]: openhab2.service: Main process exited, code=exited, status=1/FAILURE`
`Feb 14 00:39:29 openHABianPi karaf[5963]: Error: Could not find or load main class serial`
`Feb 14 00:39:29 openHABianPi systemd[1]: openhab2.service: Control process exited, code=exited status=1`
`Feb 14 00:39:29 openHABianPi systemd[1]: openhab2.service: Unit entered failed state.`
`Feb 14 00:39:29 openHABianPi systemd[1]: openhab2.service: Failed with result 'exit-code'.`

Note the " Error: Could not find or load main class serial" message. @paulipaul shows similar output in his comment under [https://github.com/openhab/openhabian/issues/522](url).

System: Raspberry 3B
OpenHAB version: openHAB 2.4.0-1 (Release Build)
OpenHABian image file: openhabianpi-raspbian-201804031720-gitdba76f6-crc9e93c3eb.img.xz
Java: 
`[00:46:12] openhabian@openHABianPi:~$ java -version`
`openjdk version "1.8.0_152"`
`OpenJDK Runtime Environment (Zulu Embedded 8.25.0.76-linux-aarch32hf) (build 1.8.0_152-b76)`
`OpenJDK Client VM (Zulu Embedded 8.25.0.76-linux-aarch32hf) (build 25.152-b76, mixed mode, Evaluation)`

Any help would be much appreciated.

Thanks,
Reinier

**Comment by BClark09** [comment]
Hi Reiner, as you have mentioned you're not the first person to come across this issue I will try to replicate and attempt to fix soon!

**Comment by reinierhamstra** [comment]
Hi,
Thanks for your prompt response. Below is the output you requested. Journalctl repeats the below output continuously it seems but does not go into much detail. Let me know if you need anything else done. Thanks!

####### journalctl ########

`[16:10:58] openhabian@openHABianPi:~$ sudo journalctl -u openhab2 -b`
`Feb 14 16:08:34 openHABianPi systemd[1]: Stopped openHAB 2 - empowering the smart home.`
`Feb 14 16:08:34 openHABianPi systemd[1]: Started openHAB 2 - empowering the smart home.`
`Feb 14 16:08:35 openHABianPi karaf[7397]: Error: Could not find or load main class serial`
`Feb 14 16:08:35 openHABianPi systemd[1]: openhab2.service: Main process exited, code=exited, status=1/FAILURE`
`Feb 14 16:08:37 openHABianPi karaf[7505]: Error: Could not find or load main class serial`
`Feb 14 16:08:37 openHABianPi systemd[1]: openhab2.service: Control process exited, code=exited status=1`
`Feb 14 16:08:37 openHABianPi systemd[1]: openhab2.service: Unit entered failed state.`
`Feb 14 16:08:37 openHABianPi systemd[1]: openhab2.service: Failed with result 'exit-code'.`


####### openhab-cli #######

`[16:11:13] openhabian@openHABianPi:~$ openhab-cli info`

`Version:     2.4.0 (Build)`

`User:        openhab (Environment Variable Set)`
`User Groups: openhab tty dialout audio bluetooth gpio`

`Directories: Folder Name      | Path                        | User:Group`
`             -----------      | ----                        | ----------`
`             OPENHAB_HOME     | /usr/share/openhab2         | openhab:openhab`
`             OPENHAB_RUNTIME  | /usr/share/openhab2/runtime | openhab:openhab`
`             OPENHAB_USERDATA | /var/lib/openhab2           | openhab:openhabian`
`             OPENHAB_CONF     | /etc/openhab2               | openhab:openhabian`
`             OPENHAB_LOGDIR   | /var/log/openhab2           | openhab:openhabian`

`URLs:        http://192.168.178.222:8080`
`            https://192.168.178.222:8443`

**Comment by BClark09** [comment]
Thanks @reinierhamstra, from what I can see I don't think you'll need to set the serial ports in the "Dgnu.io.rxtx.SerialPorts" option.

Can you edit the `EXTRA_JAVA_OPTS` line to simply read:

```
EXTRA_JAVA_OPTS="-Xms250m -Xmx350m"
```

And then try restarting the service?

**Comment by reinierhamstra** [comment]
Okay @BClark09 I edited the java options line to reflect the above.
 
######## /etc/default/openhab2 ########

`EXTRA_JAVA_OPTS="-Xms250m -Xmx350m"  # serial ports added by openHABian`

The systemd process fails persistently across reboot with the following output:



######## systemctl #######

`[21:37:49] openhabian@openHABianPi:~$ sudo systemctl status openhab2.service `
`[sudo] password for openhabian: `
`● openhab2.service - openHAB 2 - empowering the smart home`
`   Loaded: loaded (/usr/lib/systemd/system/openhab2.service; enabled; vendor preset: enabled)`
`   Active: activating (auto-restart) (Result: exit-code) since Thu 2019-02-14 21:37:54 CET; 1s ago`
`     Docs: https://www.openhab.org/docs/`
`           https://community.openhab.org`
`  Process: 3682 ExecStop=/usr/share/openhab2/runtime/bin/karaf stop (code=exited, status=1/FAILURE)`
`  Process: 3580 ExecStart=/usr/share/openhab2/runtime/bin/karaf $OPENHAB_STARTMODE (code=exited, status=1/FAILURE)`
` Main PID: 3580 (code=exited, status=1/FAILURE)`

######## journalctl #######

`[21:37:56] openhabian@openHABianPi:~$ sudo journalctl -u openhab2 -b`
`Feb 14 21:38:00 openHABianPi systemd[1]: openhab2.service: Main process exited, code=exited, status=1/FAILURE`
`Feb 14 21:38:01 openHABianPi karaf[3895]: Invalid maximum heap size: -Xmx350m#`
`Feb 14 21:38:01 openHABianPi karaf[3895]: Error: Could not create the Java Virtual Machine.`
`Feb 14 21:38:01 openHABianPi karaf[3895]: Error: A fatal exception has occurred. Program will exit.`
`Feb 14 21:38:01 openHABianPi systemd[1]: openhab2.service: Control process exited, code=exited status=1`
`Feb 14 21:38:01 openHABianPi systemd[1]: openhab2.service: Unit entered failed state.`
`Feb 14 21:38:01 openHABianPi systemd[1]: openhab2.service: Failed with result 'exit-code'.`

Seeing the above "Invalid maximum heap size" error I decided to take the full command normally installed there through the opehabian-config tool and remove the trailing comment `# serial ports added by openHABian` from the line, then rebooted, to find the systemd process keeps running.


######## /etc/default/openhab2 ########

`"EXTRA_JAVA_OPTS=-Xms250m -Xmx350m -Dgnu.io.rxtx.SerialPorts=/dev/ttyUSB0:/dev/ttyS0:/dev/ttyS2:/dev/ttyACM0:/dev/ttyAMA0"`

######## systemctl #######

`[22:01:12] openhabian@openHABianPi:~$ sudo systemctl status openhab2.service `
`● openhab2.service - openHAB 2 - empowering the smart home`
`   Loaded: loaded (/usr/lib/systemd/system/openhab2.service; enabled; vendor preset: enabled)`
`   Active: active (running) since Thu 2019-02-14 21:58:54 CET; 2min 21s ago`
`     Docs: https://www.openhab.org/docs/`
`           https://community.openhab.org`
` Main PID: 491 (java)`
`   CGroup: /system.slice/openhab2.service`
`           └─491 /usr/bin/java -Dopenhab.home=/usr/share/openhab2 -Dopenhab.conf=/etc/openhab2` `-Dopenhab.runtime=/usr/share/openhab2/runtime -Do`

`Feb 14 21:58:54 openHABianPi systemd[1]: Started openHAB 2 - empowering the smart home.`

######## journalctl #######

`[22:01:46] openhabian@openHABianPi:~$ sudo journalctl -u openhab2 -b`
`-- Logs begin at Thu 2019-02-14 21:58:38 CET, end at Thu 2019-02-14 22:03:09 CET. --`
`Feb 14 21:58:54 openHABianPi systemd[1]: Started openHAB 2 - empowering the smart home.`

I myself am at a bit of a loss why this would happen, maybe you can make sense of it? If there is anything else you need checking then let me know...

Cheers

**Comment by reinierhamstra** [comment]
@BClark09 , just an update. I have just gone into the UIs and succesfully added the Razberry2 GPIO module manually using serial port: /dev/ttyAMA0

**Comment by BClark09** [comment]
I suspect because it's fed into the systemd service you don't need the quotation marks. The line is parsed exactly as is.

Could you try exactly the line:

```
EXTRA_JAVA_OPTS=-Xms250m -Xmx350m
```

Without the serial port part and confirm that it the GPIO module still works?

**Comment by reinierhamstra** [comment]
Excellent. Thanks to you and the rest of the team for your work, it is much appreciated!

Cheers,
Reinier
