### ISSUE TITLE
Amanda backup configuration fails after commit #430

### ISSUE THREAD

**Issue by ppieczul** [openhab/openhabian#531]
Please see comment for the root cause https://github.com/openhab/openhabian/commit/c38c029fa722ff84198e9ee4a3a0e25cbd134b87#r32364274

**Comment by EliasGabrielsson** [comment]
@mstormi do you mind have a look on this when time permits?

@ppieczul Thanks for reporting and investigate the issue. If you feel that you can provide a fix yourself contributions are very welcome!

**Comment by mstormi** [comment]
Oh, just saw that today. Got stuck in my spam folder, they must have changed filters.
Thanks for analyzing @ppieczul 
Created https://github.com/openhab/openhabian/pull/535 to fix this.

**Comment by mstormi** [comment]
pls close as #535 was merged
