### ISSUE TITLE
Don't set Dgnu.io.rxtx.SerialPorts

### ISSUE THREAD

**Issue by BClark09** [openhab/openhabian#532]
Currently we are making the following serial port configuration:

```
Dgnu.io.rxtx.SerialPorts=/dev/ttyUSB0:/dev/ttyS0:/dev/ttyS2:/dev/ttyACM0:/dev/ttyAMA0
```

This shouldn't be necessary, as all ports mentioned above are covered in the serial library's port enumeration:

https://github.com/NeuronRobotics/nrjavaserial/blob/4ce383ae8dc8f702438323dd52585d993f58693b/src/main/java/gnu/io/RXTXCommDriver.java#L653-L664

Setting them explicitly prevents the search, so devices not in the list such as `/dev/ttyUSB1` can be missed.

**Comment by BClark09** [comment]
Opened up for testing in the community forums: https://community.openhab.org/t/testers-wanted-removing-the-dgnu-io-rxtx-serialports-recommendation/68327

**Comment by EliasGabrielsson** [comment]
If it's like you describe we shall definitely not add it. Lets wait and see what the testing comes up with. 👍

**Comment by mstormi** [comment]
@BClark09 is this still an issue ? If no please close.

**Comment by mstormi** [comment]
pinging @BClark09 Benjy, is this still an issue we would need to work on ?

**Comment by BClark09** [comment]
I believe so, yes. openHABian still sets the property:

https://github.com/openhab/openhabian/blob/292d452288205d4043d6b83066ec1290f6b1ec47/functions/system.bash#L341

**Comment by mstormi** [comment]
and it's as simple as to remove it ? are you sure it'll work without ?

**Comment by BClark09** [comment]
Yes but if you set a permanent/unique device name, you'll need to include it the setting and this means having to set the others too.

**Comment by mstormi** [comment]
Pardon, I don't understand. Do you need to set it in some situations ? If so why setting this by default is wrong? and what "others" are you referencing?

**Comment by mstormi** [comment]
Read https://community.openhab.org/t/testers-wanted-removing-the-dgnu-io-rxtx-serialports-recommendation/68327 - did your last comment refer to symlinks ?

Then what would you propose to be the right fix - remove everything including the openHABian option 35 ? Or just remove it to be in by default but keep 35 ?

**Comment by BClark09** [comment]
The serial library we use by default scans for serial ports that start with the strings in [this list](
https://github.com/NeuronRobotics/nrjavaserial/blob/master/src/main/java/gnu/io/RXTXCommDriver.java#L653-L664). However, if `Dgnu.io.rxtx.SerialPorts` is set, the library only uses the parameter and ignores the list.

openHABian sets the parameter to use:

```
/dev/ttyUSB0
/dev/ttyS0
/dev/ttyS2
/dev/ttyACM0
/dev/ttyAMA0
```

Which is only limiting, all these ports are covered in the serial library's list so all setting it this way does is prevent the other default from being found. My suggestion here is to leave `/etc/defaults/openhab2` as it is on `openhab2`'s install.

I'm not aware of any fixed name serial ports that openHABian sets, but if it does it'll need to add it to `Dgnu.io.rxtx.SerialPorts` in addition to the the list above.

**Comment by mstormi** [comment]
Ok, then as 35/3 does not allow for adding free-form names but only adds -Dgnu... for ports already in your list, it is useless as an option, hence I'll remove it.  PR to come in the next minutes.
