### ISSUE TITLE
Setting up amanda without openHABian user fails

### ISSUE THREAD

**Issue by BClark09** [openhab/openhabian#533]
The line @ [backup.sh](https://github.com/openhab/openhabian/blob/master/functions/backup.sh#L166) will fail if the openhabian user does not exist. It is likely trying to set ownership to the default user's group for easy access.

We should check if the openhabian user exists first before executing such a command, and make the inputs to the usermod function variables.

A secondary question: Should the openhabian group exist for manual installs too?

See: https://community.openhab.org/t/fatal-error-when-installing-amanda-backup-via-openhabian-config/68229/4

**Comment by mstormi** [comment]
If the user openhabian does not exist  I think the chmod -a G won't do anything thus no harm.
usermod does not change any permissions.
Install from scratch will create that user, won't it ?

Your secondary question I don't understand there's no openhabian group. Do you mean the user to exist ? If your worries are manual install (with a user other than openhabian to preexist and be used for working on the system) I can check for existence and eventually ask the installer for that.


On a sidenote see permissions_corrections() in system.bash, it's using the user_name_ as a group name ?

**Comment by mstormi** [comment]
@BClark09 Benjy is this still an issue ?
