### ISSUE TITLE
Sort out correct user:group combinations

### ISSUE THREAD

**Issue by BClark09** [openhab/openhabian#534]
Related somewhat to #533

openHABian sets the permissions of the openHAB directories to `openhab:openhabian` which overwrites the package/service's default of `openhab:openhab`.

It seems weird to me to assign folder permissions created by a service to a user group so. I believe it would be best to keep the permissions rights as it is, and if necessary add the `openhabian` user (as well as any service users that need write permissions e.g. for backup) to the `openhab` group.

We can then call `openhab-cli reset-ownership` to deal with openHAB's own folder structure.

WDYT?

**Comment by EliasGabrielsson** [comment]
I personally don't have any experience to add to the question, but if this is the de-facto standard for Linux I would prefer this design. @ThomDietrich do you have any thoughts to add on to this design decision?

**Comment by mstormi** [comment]
Agree keeping the openhab group default is Linux standard and I'd prefer that, too.

**Comment by ThomDietrich** [comment]
I agree. The openhabian group is not needed and as openhabian is member of the openhabian group, all stays the same for openhabian in case of `openhab:openhab` permissions

**Comment by mstormi** [comment]
> I agree. The openhabian group is not needed and as openhabian is member of the openhabian group, all stays the same for openhabian in case of `openhab:openhab` permissions

I assume you mean the user openhabian to be member of the group **openhab** (without 'ian') ? Else with this change openhabian will not be usable any more for operating OH ?

**Comment by ThomDietrich** [comment]
No you are correct.
