### ISSUE TITLE
/lib/modules versions don't match kernel version - can't insmod or modprobe additional drivers

### ISSUE THREAD

**Issue by davidgurr** [openhab/openhabian#537]
"uname -r" reports 4.14.79-v7+, but /lib/modules contains: 4.14.98+  4.14.98-v7+

As a result, modprobe and insmod both fail when loading additional modules.

How can I resolve this?

**Comment by davidgurr** [comment]
Found the solution. 

For some reason it looks like there's an issue in the Raspbian build that causes the kernel to be a few versions behind /lib/modules. The solution is to reinstall both, using the method detailed here: https://raspberrypi.stackexchange.com/questions/83329/linux-modules-mismatch-version/94716

**Comment by EliasGabrielsson** [comment]
Does this happen on a new clean installation?

**Comment by mstormi** [comment]
I encountered that at times, too, but it's not reproduceable and something to fix upstream anyway, so I suggest to close the issue.

**Comment by mstormi** [comment]
@davidgurr mind to close this ?
