### ISSUE TITLE
Update Grafana repository (x86)

### ISSUE THREAD

**Issue by jtag66** [openhab/openhabian#538]
The Grafana repository for x86 changed from packagecloud.io to grafana.com:

Locate line 662 ff: "echo -n "Installing Grafana...""
change line 676 (just behind "else") to: cond_redirect wget -O - https://packages.grafana.com/gpg.key | apt-key add - || FAILED=2
change line 677 to: echo "deb https://packages.grafana.com/oss/deb stable main" > /etc/apt/sources.list.d/grafana.list || FAILED=2
comment out lines 678 - 680 (cause I see no specifics for ubuntu here)

**Comment by EliasGabrielsson** [comment]
Related to this: https://github.com/openhab/openhabian/issues/437
Please provide a patch and I will merge it.

**Comment by jtag66** [comment]
It's not the same as #437 - update arm repos but will update x86 repos.
Sorry for the delay - I've never used github before and need some time to figure out, how to provide a patch :-)
