### ISSUE TITLE
mounting /dev/mmcblk0p2 on /rootfs failed: Invalid argument

### ISSUE THREAD

**Issue by jamesfawcett** [openhab/openhabian#54]
I'm having trouble with the installer, 

https://github.com/openhab/openhabian/blob/master/scripts/etc/init.d/rcS line 412:
`rootfs_mkfs_options=${rootfs_mkfs_options:-'-f'}`

The -f is causing this error for me: https://github.com/debian-pi/raspbian-ua-netinst/issues/29 

> mounting /dev/mmcblk0p2 on /rootfs failed: Invalid argument

I'm having trouble building the img after removing the -f, the openhab-build.sh script isn't working for me although I am quite new to compiling so I may be doing something wrong.

**Comment by ThomDietrich** [comment]
Is building the image your intention? If you want to install openHABian on your Raspberry Pi, just take the already build image available under [Releases](https://github.com/openhab/openhabian/releases/tag/v1.0) ;)

**Comment by jamesfawcett** [comment]
Hi ThomDietrich. Thanks for your reply, I am currently formatting a new SD card to give it another go.

My issue is with the installer, installation fails at "Mounting new filesystems..."

The fix seems to be to remove the -f on line 412 of the install process but I cannot get the project to recompile. Do not worry, this may be a rare problem and may be fixed with the new SD card.

Hardware: Raspberry PI 3 Model B with 32gb card

**Comment by ThomDietrich** [comment]
Sure think so. Can't think of another reason why a RPi3+SDcard combo would suddenly need another routine, other than hardware damage. Good luck ;)

Just for completeness: Executing `sudo bash openhabian-build.sh` should be all that's needed. I've however done something to prevent accidental execution, maybe you stumbled into that. Check out this [line of code](https://github.com/openhab/openhabian/blob/master/openhabian-build.sh#L7). Also check the dependencies: https://github.com/debian-pi/raspbian-ua-netinst/blob/master/BUILD.md

**Comment by jamesfawcett** [comment]
That worked spot on thank you Thom, it was the dependencies. I just compiled on a remote Centos server and it worked first time. Just downloading the img file now so I'll give it a go without the -f in the rootfs_mkfs_options. I also believe it's hardware related, will know shortly :)

**Comment by jamesfawcett** [comment]
Hi @ThomDietrich I can confirm you were right and this was a hardware issue. Purchasing a Genuine Sandisk ULTRA SD card from a reputable source, the installation went smoothly and correctly first time. Thank you for your time, and I'm looking forward to having Openhab running again this evening so I can have the heating on at home!

**Comment by ThomDietrich** [comment]
Wonderful. Good luck ;) 👌
