### ISSUE TITLE
first-boot.sh is looking for openhabian-setup.sh and not .bash

### ISSUE THREAD

**Issue by Mbogdan95** [openhab/openhabian#550]
Last commit changed the extension of some files from .sh to .bash and now first-boot.sh is confused not finding openhabian-setup.sh

**Comment by EliasGabrielsson** [comment]
Sorry for the breaking update.
Please run `sudo /opt/openhabian/openhabian-setup.bash` and apply the update.

After the update is complete you maybe need to run `ln -sfn /opt/openhabian/openhabian-setup.sh /usr/local/bin/openhabian-config` as well if `sudo openhabian-setup` doesn't work.

// EG
