### ISSUE TITLE
Investigate ARM QEMU image for travis

### ISSUE THREAD

**Issue by EliasGabrielsson** [openhab/openhabian#559]
Currently the testing framework only test against x86 architecture. As the images produced by openhabian are ARM based (32/64bit) it would be good to emulate ARM and run the tests on that architecture as well.

What we need is a docker image running QEMU Rasbian with systemd as PID 1.

**Comment by mstormi** [comment]
Fun to play with ... a little premature as I still need to fiddle out what's missing in the image for openhabian-setup.sh to complete, but this is almost working.
The first docker command will do the magic if the image contains qemu.

.travis.yml:
language: bash

addons:
  apt:
    packages:
    - shellcheck
    update: true

services:
  - docker

install:
  - shellcheck --version
    #  - docker build --tag openhabian/openhabian-bats .

script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t openhabian/rpi-openhabian .
  - docker run --rm -e TINI_SUBREAPER= -it -d -p 80:80 openhabian/rpi-openhabian

    #  - docker run -it openhabian/openhabian-bats bash -c 'bats -r -f "unit-." .'
    #  - docker run --name "install-test" --privileged -d openhabian/openhabian-bats
    #  - docker exec -it install-test bash -c "./build.bash local-test && mv ~/.profile ~/.bash_profil && /etc/rc.local"
    #  - docker exec -it install-test bash -c 'bats -r -f "installation-." .'
    #  - docker exec -it install-test bash -c 'bats -r -f "destructive-." .'

  - shellcheck -s bash openhabian-setup.sh || true
  - shellcheck -s bash functions/*.bash || true
  - shellcheck -s bash build-image/*.bash || true

Dockerfile:
FROM balenalib/raspberry-pi2

RUN apt-get update && apt-get install -y git locales
RUN git clone https://github.com/bats-core/bats-core.git && \
    cd bats-core && \
    ./install.sh /usr/local
RUN adduser openhabian --gecos "Openhabian,,," --disabled-password
RUN echo "openhabian:openhabian" | chpasswd
RUN /bin/echo -n "Running on " && /usr/bin/arch

COPY . /opt/openhabian/
COPY openhabian.conf.dist /etc/openhabian.conf

WORKDIR /opt/openhabian/

RUN ./openhabian-setup.sh unattended_debug

**Comment by EliasGabrielsson** [comment]
Nice @mstormi!
I will check it out when most important stuff are fixed

**Comment by EliasGabrielsson** [comment]
Some relevant information: https://www.balena.io/blog/building-arm-containers-on-any-x86-machine-even-dockerhub/

**Comment by mstormi** [comment]
Yes... strictly regarding the title of this one, using balenalibs images (which I think is a good base as it's by far the greatest library) cross-compiling now is as easy as to embrace everything by
RUN [ "cross-build-start" ] ... RUN [ "cross-build-end" ].
So we could either close this and keep #595 open or rename this.

Where do we want to continue tracking work on the build pipeline ?
They removed the INITSYSTEM while leaving an explanation how to include your own at
https://www.balena.io/docs/reference/base-images/base-images/#installing-your-own-initsystem
I'm still struggling, however, to get this to work, I'm still getting Travis to tell me errors that systemd isn't started as PID 1 see e.g. https://travis-ci.com/mstormi/openhabian/builds/119937639

**Comment by EliasGabrielsson** [comment]
We keep the discussion here.
We need to keep the `systemd` even if it's hard to achieve. The goal is primarily not to do a docker image, that is already done. Why I initially choose to use docker was the fast build-up and tear-down of a good enough test environment. The test case should always be possible to be executed on real hardware as will.

**Comment by EliasGabrielsson** [comment]
Only way to investigate this is to ssh to the machine and have a look I guess.
Maybe implicit but when we manage to get this image to work we will run the CI build on two docker images, one for ARM and one for x86.

**Comment by mstormi** [comment]
ok I got systemd to work somewhat but still hit a number of issues, container starting but terminating being among them. One must provide a CMD so I provided a long "sleep" for now.

Now I'm seeing [this](https://travis-ci.com/mstormi/openhabian/builds/121088349) output:
`No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself`
I still quite don't understabnd this as in [this build](https://travis-ci.com/mstormi/openhabian/jobs/220436281) base on the older non-balenalib image it worked out.

**Comment by mstormi** [comment]
Woo-hoo, here we finally are.
A Raspbian buster based image with a modified systemctl allows for building and testing an armv71 image on Travis: https://travis-ci.com/mstormi/openhabian/builds/121676218
wdyt?

**Comment by EliasGabrielsson** [comment]
Exciting! This will save us ton of work in future fore sure :-)
The PR is ready to merge when the commits are squashed. Made a short guide in the PR if it is needed.

**Comment by mstormi** [comment]
see PR #616 
close this one?
