### ISSUE TITLE
Configuration of Grafana admin account fails

### ISSUE THREAD

**Issue by EliasGabrielsson** [openhab/openhabian#562]
Installation fails when updating admin password.
`Updating Grafana admin password...curl: (7) Failed to connect to localhost port 3000: Connection refused`

See thread: https://community.openhab.org/t/influxdb-grafana-installation-error/51708/10

**Comment by gismofx** [comment]
@ThomDietrich  @EliasGabrielsson  I'm still experiencing this issue with 2.5 and latest openhabian-config.

`$ systemctl start grafana-server.service
OK
Updating Grafana admin password...{"message":"Invalid username or password"}OK Updating Grafana configuration...
$ sed -i -e /^# disable user signup \/ registration/ { n ; s/^;allow_sign_up = true/allow_sign_up = false/ } /etc/grafana/grafana.i                        ni

$ sed -i -e /^# enable anonymous access/ { n ; s/^;enabled = false/enabled = true/ } /etc/grafana/grafana.ini

$ systemctl restart grafana-server.service
Connection Grafana to InfluxDB...{"message":"Invalid username or password"}Adding openHAB dashboard tile for Grafana... 2020-04-30_                        10:35:45_EDT [openHABian] Adding an openHAB dashboard tile for 'grafana'... Replacing... OK
Adding install InfluxDB with database configuration to openHAB
`

**Comment by holgerfriedrich** [comment]
@gismofx I was able to reproduce your problem, but only when installing for the second time.
Grafana server responds with "Invalid username or password" when password was already set before.
Is this also the case on your side?

**Comment by gismofx** [comment]
@holgerfriedrich I received an error both times, After the second time, I came here with the copied output. It may have been a different error the first time, but I recall the last line in terminal said "FAILED".

**Comment by holgerfriedrich** [comment]
@gismofx maybe password too short, grafana needs minimun 5 characters.....
I see, we need some error handling here.

**Comment by holgerfriedrich** [comment]
@gismofx PR #860 is merged, it should fix the problem. Can you confirm?

I am closing the issue, please reopen it in case you still experience a problem.
