### ISSUE TITLE
Installation issues after crash on rPi2b+

### ISSUE THREAD

**Issue by howroyd** [openhab/openhabian#563]
Long time user of openhab on pi2 and pi3.  The past 24hrs been installing a fresh on a new pi2b+ for another project and had some issues.

I think all caused because the pi crashed mid way through the first boot (bad power supply, my fault.  It was a 2.4A one but clearly rubbish!  Now using the official rPi one.)

Some of the first boot sequence fails because it has already been actioned, but IMO it should skip through.

Reasonably easy fix but has meant I needed to comment out some lines in the first boot sequence after confirming that those lines have actually been executed previously (successfully).

Unfortunately, my bash knowledge sucks so I can't propose a fix.  Hopefully the below can help the devs or others with the same issue.

Hope this is helpful.  Thank you to all for such an amazing bit of software.

Cheers

Simon

PS: Sorry about the horrendous formatting below...I tried!

----------------------------------------------------------------

**/boot/first-boot.sh**
_already cloned.  Hangs here forever because directory already exists.  Removed dir and manually cloned, success.  Commented out as below and progresses past this point ok._
> `echo -n "$(timestamp) [openHABian] Cloning myself... "`
> `#/usr/bin/git clone -b master https://github.com/openhab/openhabian.git /opt/openhabian &>/dev/null`
> `#/usr/bin/git clone -b develop https://github.com/openhab/openhabian.git /opt/openhabian &>/dev/null`
> `#if [ $? -eq 0 ]; then echo "OK"; else echo "FAILED"; fail_inprogress; fi`
> `ln -sfn /opt/openhabian/openhabian-setup.sh /usr/local/bin/openhabian-config`

 **/opt/openhabian/functions/system.bash**
_had already been installed, script hangs here forever.  Ran manually to confirm and checked everything was not broken.  Commented out as below and can now progress._
> `basic_packages() {`
> `echo -n "$(timestamp) [openHABian] Installing basic can't-be-wrong packages (screen, vim, ...)... "`
> `#  cond_redirect apt update`
> `#  apt remove raspi-config &>/dev/null || true`
> `#  cond_redirect apt -y install screen vim nano mc vfu bash-completion htop curl wget multitail git bzip2 zip unzip \`
> `#                               xz-utils software-properties-common man-db whiptail acl usbutils dirmngr arping`
> `#  if [ $? -eq 0 ]; then echo "OK"; else echo "FAILED"; exit 1; fi`
> `}`

 **/opt/openhabian/functions/openhab.bash**
_Needed to manually run the following lines.  I think it was failing because my power supply & wifi dongle combination was causing it to fail which then effectively bricked the code when different hardware was used to try again_

**Comment by EliasGabrielsson** [comment]
Hi Simon!
When a crash occurs as you describes the recommended action is to do a full reinstallation from scratch.

We don't aim to fix all edge-cases for broken installation due to time-constrains of the maintainers but it is good that you have reported the issues. Sometime we can see a error-pattern from multiple error-logs.

Closing this now.
Regards

**Comment by howroyd** [comment]
No worries.  Wasn't sure if there was a flag or something that could be set to progress through the script if something is already installed fully (I am still learning!)  I managed to get everything working without a full re-flash but I will make sure I keep this in mind if I get issues later down the line that it may be my own doing!

Keep up the ace work.

Cheers

Simon
