### ISSUE TITLE
Can't Connect to webpage

### ISSUE THREAD

**Issue by DarrenSanders123** [openhab/openhabian#564]
i have the pi setup as he tutorial did.
but when I type the ip/dns on my search bar it says cant find 192.168.11.*
how do I fix this?
I have already reinstald it

**Comment by EliasGabrielsson** [comment]
You need to specify the full IP number with all 4 fields of number filled in.
Also you need to specify the port, i.e `192.168.11.100:8080` where 100 is replaced with your ip number on the machine.
