### ISSUE TITLE
Chacon Dio 54754 with RFXCOM

### ISSUE THREAD

**Issue by fgouland** [openhab/openhabian#573]
Hello,
I think there is an issue with Chacon Dio 54754 which I want to use as a true Rollershutter item.

My device works fine when I configure it as a switch (channel: command) item but no RFXCOM command is sent when I use is as Rollershutter (channel:shutter) item.
The problem is perhaps with Rollershutter because when I define my device as Rollershutter (channel:command), it doesn't work.
Thank you in advance
Regards

**Comment by EliasGabrielsson** [comment]
Hi Jean-Louis!

Thanks for reporting an issue. This issue however regards an addon of openhab and should therefor be placed here: https://github.com/openhab/openhab2-addons.

Use the title: `[RFXCOM] Chacon Dio 54754 as Rollershutter does not work`

Please repost it there.

Regards,
