### ISSUE TITLE
grafana update

### ISSUE THREAD

**Issue by HerzScheisse** [openhab/openhabian#574]
Hey,

is there any plan to update the grafana version which is shipped with openhabian?
i'm on the latest snapshot build and my Grafana is v5.1.4 the currently avaiable is v6.2.1

can we just update the grafana via apt-get? if so can you explain how and which platform?

WHY update?
I was getting mad about the scrollbar, when using iframe in my HABPanel... and then i stumpled upon this grafana issue https://github.com/grafana/grafana/issues/12589

thanks

**Comment by EliasGabrielsson** [comment]
Hi,
The Grafana packages are updated for new installations but no automatic upgrade pattern have been developed. You could install the new one using the provided menu but I don't take any responsibilities for the outcome of the migration.

If you use a RPi I would recommend you to make a new installation on a new card, and then migrate manually. Better to play safe.

If you would like to contribute to making a safe upgrade script you are more then welcome.
This is a good place to start at: https://github.com/openhab/openhabian/blob/master/functions/influxdb%2Bgrafana.bash

Closing this now,
Regards

**Comment by MoerkyMark** [comment]
Hi, what do you mean with "using the provided menu"? Which menu is provided for upgrade an where? I don't see this in Grafana itself.
