### ISSUE TITLE
Installation on Raspberry 3B+ failed wrong apt version

### ISSUE THREAD

**Issue by Siox0911** [openhab/openhabian#577]
In openHABian, latest from april 2018, apt 1.4.9 is installed, but for apt-get upgrade apt version 1.4.8 is needed. So the install process will fail. 

The command "apt -fix-broken install" will fix the problem.

**Comment by mstormi** [comment]
With #575 merged, can you please check install now works for you?

**Comment by Siox0911** [comment]
I have added the changed code in the **first-boot.sh**, between the **update** and **upgrade** code.
Yes, now it works fine. On a raspberry 3B+, the installation takes 30 minutes with the 1.4.1 release and the changed **first-boot.sh**. 

😊

**Comment by mstormi** [comment]
fine, then please change the issue

**Comment by EliasGabrielsson** [comment]
Thanks everyone committed to solve this. Sorry delaying the process. 👍
