### ISSUE TITLE
Upgrade to Debian Buster

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#579]
Oh dear, RasPi 4 is out and requires Debian Buster. Raspbian image jumped there, too.
Time to stresstest our new build system I guess.

**Comment by holgerfriedrich** [comment]
First thing is to add "export DEBIAN_FRONTEND=noninteractive" to all scripts calling apt/apt-get in an unattended mode. Buster tries to open a user dialog during installation of the samba package which keeps the firsttime install script waiting forever.
With this, openhab installs and starts up.

**Comment by holgerfriedrich** [comment]
@ThomDietrich @EliasGabrielsson Any hint how to deal with Zulu Embedded? In case we do not use a repository but download it directly, we will run into trouble keeping it up to date... openhabian-config, "Upgrade System: Upgrade all installed software packages to their newest version" will not catch this.

**Comment by holgerfriedrich** [comment]
...and where should we keep the TODO list for buster? Separate issues?
I already see a few of the additional SW packages which are still at stretch, no buster repos available....

**Comment by holgerfriedrich** [comment]
...update issue also valid for node.js....

**Comment by EliasGabrielsson** [comment]
> Any hint how to deal with Zulu Embedded? In case we do not use a repository but download it directly, we will run into trouble keeping it up to date... 

Zulu embedded is currently not upgraded after first installation, correct.
As you can see will the script fetch the latest version during install though.
This is an desire feature and I created an issue for it: https://github.com/openhab/openhabian/issues/592

> ...and where should we keep the TODO list for buster? Separate issues?

I would say we try to keep it in this thread for now if it´s possible.

> ...update issue also valid for node.js....
Created an issue for that as well: https://github.com/openhab/openhabian/issues/593

**Comment by EliasGabrielsson** [comment]
I can verify that newly built images works with RPi4, both ethernet and wifi installations.
Maybe specific APT repositories need to be updated but so far everything have been working.
Closing this now, upcoming issue could specifically be solved as we iron them out.

**Comment by mstormi** [comment]
oooooo-kay ... so current openHABian is supposed to run on both, stretch AND buster ?
Do we recommend to dist-upgrade to buster (on non-RPi4 of course) ? did you verify that to work, too?

**Comment by holgerfriedrich** [comment]
I think we have some more work to do until all the optional  packages are working properly. Homegear not ready yet (Buster repo still not fully available), some minor stuff in the menus to be updated, etc. Depends in those projects of course. Finally, I have not seen influx&grafana running yet... 
But as the System itself is running with at least basic functionality, we can go on with separate issues as Elias proposed.

**Comment by ThomDietrich** [comment]
Great to hear @EliasGabrielsson !!
What do you guys see as the next step? We should release a Buster based image as soon as possible... however I personally think that ALL menu entries should first be updated and tested. If a component is in fact currently not available for buster (and no workaround can be found) we should add a warning and cancel the action.

@holgerfriedrich @EliasGabrielsson you already have a running system. Will you take care of the testing and open issues for everything that comes up?

@mstormi I would not expect too many issues. Of course a dist upgrade will disable all added repositories and individual packages might not work anymore. Re-executing the respective menu entry should fix that (after the changes mentioned above). I personally would say the upgrade of an existing system is of secondary priority right now. Wdyt?

**Comment by EliasGabrielsson** [comment]
#### Migration
> so current openHABian is supposed to run on both, stretch AND buster ?

This is a tricky question. For new installations I would say _no_, only buster (and latest Ubuntu LTS). On the other hand is it nice to keep running installations working, especially for the "openhab" brand in general. Migrating paths for system is hard though, it's not made easier that every system installed by openhabian will have a unique _state_ depending on when it's installed.

Some possible options could be: (can be combined)
* Create a maintenance branch basically freezing current state of openhabian used for old base systems.
* Recommend users to reinstall base-system otherwise explicit warn them that they are using unsupported software.
* Create an upgrade script that migrate systems to a new version of Debian (Ubuntu). I honestly don't want to put my hands into that.

We already have the same issue with the pine64 image as it's using Ubuntu 16.10 (Old LTS release).

#### Regards upcoming issues
I suggest that all new issues detected gets an improved or written BATS test for them. I will then use the written test to verify functionality. This is the only way to keep this project manageable if we will add more boards or add-ons.

**Comment by EliasGabrielsson** [comment]
I have a pi4 at hand, or at least some time. 
I would like to have all issues in 1.5 fixed before we release an new image. The part of dumping a full installation build will be of great help for detecting upcoming bugs https://github.com/openhab/openhabian/issues/408.

**Comment by ThomDietrich** [comment]
openHABian already accompanied two upgrades of the base system. SO far we always delivered the newest image with the newest base (obviously) and tried to support different base systems for optional components (es, this was never complete).
As for upgrading: I think we shouldn't expect users to dist-upgrade their base. A running system will continue running and apt based package upgrades keeps installed packages up to date. At a certain point the user might choose to dist-upgrade or preferable reinstall openHABian with the latest image. Additions to the options offered through the menu are not tested for the old base and might fail.

I am not saying this is the best offer possible - this is how it was so far.

**Comment by mstormi** [comment]
Well. We would either need to release a buster image asap or ANY new install from image will still be stretch (or was it even jessie?) so if we postulate buster to be supported or even recommended we will get many to ask these questions and see a number of people to migrate on their own.
So while I agree most people will not dist-upgrade, some will and we need to have answers ready.
A working dist-upgrade to get over to buster will not be "secondary" at all but very important then.
I'd suggest we test dist-upgrade with a Pi flashed with the current old image.
Then we can take the time it takes to release a new buster based image (incl. 1.5 with all relevant stuff fixed and to also support RPi4).

btw do we have an idea of how many installations we have on RPi and x86 and which UNIX release they run ? (sidenote: we should add a statistics gatherer; maybe add it to the self-update run).
