### ISSUE TITLE
Raspberry Pi 4 support?

### ISSUE THREAD

**Issue by dannycohn** [openhab/openhabian#581]
With the [Raspberry Pi 4 released](https://www.raspberrypi.org/products/raspberry-pi-4-model-b/), do we know if the current release will work out of the box, or if work will be required to support it?

**Comment by ThomDietrich** [comment]
Hey community,
without putting much thought into it I believe there will at least be a couple of issues. The new RPi was released with the new Raspbian build and we need to create a new openHABian image based on it. I would not recommend installing openHABian with the older Raspbian base.

**Workaround:** Till the new image is available please use the latest Raspbian image and follow the Manual Setup path for the openHABian installation. This way you should come close to a working openHABian system and any issue that comes up can quickly be dealt with in this project, even before releasing the new image (which would then include the fix).
Please report about your experiments!

Happy Testing!

**Comment by mstormi** [comment]
There will be issues for sure as Pi foundation themselves says you need to run Debian Buster release for a RPi4.
I already created #579 to track this. May I suggest you close this issue to avoid duplicates.

**Comment by dannycohn** [comment]
Closing as duplicate of #579
