### ISSUE TITLE
Additional EXTRA_JAVA_OPTS for jython

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhabian#584]
Hey guys,
I wonder if we should assist with the setup of Jython in openHABian? See this latest contribution:
https://github.com/openhab/openhab-docs/pull/1012

**Comment by EliasGabrielsson** [comment]
Sound reasonable

**Comment by EliasGabrielsson** [comment]
Superseeded by: https://github.com/openhab/openhabian/issues/461
