### ISSUE TITLE
OpenHabian-config clean install hangs

### ISSUE THREAD

**Issue by bwosborne2** [openhab/openhabian#588]
I have verified this several times.
When performing a clean install on Raspbian Lite with a RPi 3B+ & USB connected SSD 
and selecting the following: 
60 Manual/Fresh Install
then
Choose stable, testing, or unstable.
Choose 65, 66, 67, 68, & 69

Select Execute.

openhabian-config seems to hang trying to remove raspi-config.

Killing (control-c) and restarting the installation works fine.

I have tested this with clean installs for stable & testing.

**Comment by bwosborne2** [comment]
I am not an experienced programmer, but line 22 in "system.bash" seems to be the issue.

apt remove raspi-config &>/dev/null || true

might better work as

apt remove -y raspi-config &>/dev/null || true

I think "apt-remove" is prompting for acknowledgement.

**Comment by bwosborne2** [comment]
A side issue is WHY is raspi config removed anyway??

**Comment by EliasGabrielsson** [comment]
Hi! 
Thank you for the report and your investigation. Looks like a possible error.
@ThomDietrich what was the design decision to remove raspi-config?

Related to this https://github.com/openhab/openhabian/issues/289 ??

**Comment by bwosborne2** [comment]
Thank you for responding so quickly.  
I am more experienced in Unix than some users who will try to use the product for onboarding. I believe Raspbian Buster has been released so it may be worth trying it with that OS version too.

**Comment by holgerfriedrich** [comment]
@bwosborne2 You might have run into trouble with debconf, trying to show a dialog.  
export DEBIAN_FRONTEND=noninteractive
apt-get remove -y raspi-config &>/dev/null || true
If this does not help you could try to comment everything starting with the & and see what happens...

**Comment by bwosborne2** [comment]
My point is that the script is missing the "-y" so it hangs as apt waits for confirmation. You need to ass the "-y" on that line, according to my testing.
This happened on a clean install of Raspbian Lite with nothing else installed other than enabling ssh server & updating packages.

**Comment by ThomDietrich** [comment]
A bit late but to add an answer: raspi-config is removed because it colides with some things that openhabian does during initial setup and in the individual menu options. I had to realize that respi-config is not well developed to check the status quo before doing changes to the system. At some point (would need to search old tickets) it lead to an error.

**Comment by bwosborne2** [comment]
So really, you should include the options from raspi-config that are not in openhabian-config. Things like setting Wi-Fi country, etc.
