### ISSUE TITLE
Change locale in raspi-config

### ISSUE THREAD

**Issue by Waldknoblauch** [openhab/openhabian#59]
"Change locale" in raspi-config in openhabian has no effect. For example, it is not possible to change from English to German. The original Raspian works. Can anybody confirm that?

**Comment by nwootton** [comment]
I'm having the same issue. I've been able to remove the de_DE.UTF-8, but adding en_GB.UTF-8 and/or replacing en_US.UTF-8 all result in errors. Tried using raspi-config and via terminal.

**Comment by ThomDietrich** [comment]
Hello,
I didn't look into this yet. 
As a workaround, you should be able to set them manually. These are the commands openHABian uses:

```
## locale
  sed -i 's/\# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g' /etc/locale.gen
  sed -i 's/\# de_DE.UTF-8 UTF-8/de_DE.UTF-8 UTF-8/g' /etc/locale.gen
  /usr/sbin/locale-gen
  /usr/sbin/update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8
```

So please edit /etc/locale.gen according to your needs and execute the two commands. I'll have to look into this problem at a later point.

**Comment by nwootton** [comment]
Thom - sorry I didn't get a notification that you'd replied to this. I'll try that ASAP and get back to you.

**Comment by ThomDietrich** [comment]
Hey @Waldknoblauch and @nwootton,
just so you know. With Version 1.1 I introduced a few changes regarding this topic. I'll still have to add a menu entry to switch from within openhabian-config. Till then, please see: http://docs.openhab.org/installation/openhabian.html#timezone-locale

I would not recommend using raspi-config and will remove it from openHABian when doing the above.

What do you think? Please test the changes

**Comment by nwootton** [comment]
@ThomDietrich Just gone back to OpenHABian and used the instructions you linked to above worked fine.

**Comment by ThomDietrich** [comment]
Hey guys, please pay attention to version 1.2. Should solve this whole issue.
