### ISSUE TITLE
Check if updates to Node.js are available when openhabian-config UPGRADE is executed.

### ISSUE THREAD

**Issue by EliasGabrielsson** [openhab/openhabian#593]
If Node.js is installed with ".tar" method which is the case when using RPi no updates are installed later on. Improve this by check if updates to Node.js are available when openhabian-config UPGRADE is executed.

**Comment by mstormi** [comment]
is this still needed ?

**Comment by mstormi** [comment]
nodejs is installed using apt so I believe this is no longer of relevance.
Reopen if you disagree.
