### ISSUE TITLE
Missing Java after following installation instructions

### ISSUE THREAD

**Issue by ianmacs** [openhab/openhabian#596]
To install openHABian on a Rapberry Pi 4, I booted the Pi from a fresh SD card with latest Raspbian Lite and then followed the instructions for other linux systems at https://www.openhab.org/docs/installation/openhabian.html#other-linux-systems-add-openhabian-just-like-any-other-software because there is not yet an openHABian SD card image for the Pi 4.

I followed the instructions to the letter and stepped through the openHABian configuration menu. This includes as I understand an apt upgrade of the OS and installation of additional packages recommended by openHABian. From the optional components I only chose

- Log Viewer
- Mosquitto. Set an authentication password.
- Influxdb & Grafana
- NodeRED
- 1wire. Does not succeed. Maybe needs adaptation to Pi 4.
- change hostname
- change time zone
- Change passwords for samba and amandabackup (But I did not install amandabackup)

After rebooting, openHAB was not running:
pi@pi4:~ $ service openhab2 status

    ● openhab2.service - openHAB 2 - empowering the smart home
       Loaded: loaded (/usr/lib/systemd/system/openhab2.service; enabled; vendor preset: enabled)
       Active: activating (auto-restart) (Result: exit-code) since Sun 2019-07-14 22:30:46 CEST; 2s ago
         Docs: https://www.openhab.org/docs/
               https://community.openhab.org
      Process: 780 ExecStart=/usr/share/openhab2/runtime/bin/karaf $OPENHAB_STARTMODE (code=exited, status=1/FAILURE)
     Main PID: 780 (code=exited, status=1/FAILURE)

I found that my installation was still missing Java. The installed openhab2 debian package lists possible JVM dependencies only in the `Suggests:` section. After installing openjdk-8-jdk-headless and another reboot, openHABian works for me.

Suggestion:
Get users installing openHABian on "other linux systems" to install Java by either
- telling them in the text of the instructions on https://www.openhab.org/docs/installation/openhabian.html#other-linux-systems-add-openhabian-just-like-any-other-software
- Extending the installation of recommended software step of the openHABian configuration to also install a JVM
- Moving the JVM dependency from "Suggests:" to either "Recommends:" or "Depends:" in the openhab2 deb package

**Comment by mstormi** [comment]
So you intentionally chose to manually install packages on a (for the time being) unsupported platform, went through all the install options but forgot to do that for Java although it's well-known that OH is Java based and the docs in fact read "Execute **all** entries one after the other to get the full openHABian experience.". That's an unambigous statement so you didn't follow the install instructions.

**Comment by EliasGabrielsson** [comment]
Hi @ianmacs!
Out of curiosity did you try the JAVA install option in the openhabian menu, does it work for RPi4?

I think the reason for "Suggests" instead of "Depends" is a matter of not forcing the user to use a specific JVM product, i.e. openjdk-8-jdk in your case.

I closing this now but have your thoughts in mind when the documentation should be reviewed.
Thanks for your input 👍

**Comment by ThomDietrich** [comment]
@BClark09 could you please refer to the issue with the suggests vs depends discussion? Thanks

**Comment by BClark09** [comment]
Sure thing: https://github.com/openhab/openhab-linuxpkg/issues/123
