### ISSUE TITLE
optional component: Logstash + Elasticsearch + Kibana

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhabian#6]
A very powerful log analyzer. Filtering rules for openHAB have to be built.

**Comment by jscottnz** [comment]
woah - heavy duty. what would you use this for? Do you use this currently - I be interested in the use case.

**Comment by ThomDietrich** [comment]
Hey @jscottnz an old issue indeed. I did some testing a while back and while it was nice to have (I already utilize an ELK stack) this is definitely not interesting to the common user and shouldn't be installed on our typical RPi

We now also have frontail (with its limitations...)

I'd suggest to close this issue. If someone is interested, see: https://community.openhab.org/t/logging-to-logstash-elasticsearch-kibana/30821
