### ISSUE TITLE
Install Hangs after a while, no idea how to debug

### ISSUE THREAD

**Issue by RaimondB** [openhab/openhabian#60]
Hi,

I've run the install several times but each time after a while only the red led is lit, and network lights are out. But it stays that way (even after keeping it running for a night).

When I disconnect and reconnect power when I get to above situation I get into the "failed" modus with the green led blinking fast however, because of the reboot (I think) the log file contains only a few lines.

After following instructions in the ssh session to reinstall I get into the same situation as mentioned above. Please advice on how to debug this or get around it. 

Unfortunately not hassle free until now :-/ I hope you can help, thanks in advance.

I have a Raspberry Pi 3.

**Comment by ThomDietrich** [comment]
Hello, could you provide more details? You should have seen a screen similar to this: 

![](https://community-openhab-org.s3-eu-central-1.amazonaws.com/original/2X/a/a89960f6b99f1ab9af41f6efd04a477e71007817.png)

Please post the output of `sudo tail -n 20 /var/log/raspbian-ua-netinst.log` here (only the last 20 lines are important).

These are the two typical causes of a failed installation:

* temporary network connection outage -> restart the installation (you already did that)
* a defective SD card

I'll have to look at the log file to know more.

**Comment by RaimondB** [comment]
This is what I get after powercycling the Rpi after the hang (because I cannot ssh at that point).
Only 3 lines..

[openHABian] Booting for the first time!
[openHABian] Installing Oracle Java 8 from Web Upd8 repository... OK
[openHABian] Indicating failure through green LED fast blinking.

**Comment by RaimondB** [comment]
Btw, the SD card is not defective, as I used it sucvcesfully for an OpenHAB1 installation..

**Comment by ThomDietrich** [comment]
That's very strange. Never experienced this behavior. Could you please additionally look for the file under boot, it could be named slightly differently. `sudo tail -n 20 /boot/raspbian-ua-netinst.log`

**Comment by RaimondB** [comment]
I'm sorry, in the mean time I decided to just go the apt-get way and got it up and running. 

Unfortunately I have no second SD card to easily switch setup. Is there an easy way to completely backup the SD card under windows so I can make a complete backup to test the openhabian again and get the above log?

**Comment by ThomDietrich** [comment]
That would be great! Chances are high it will work now (a couple of days later).
Yes there is. I guess you used Win32DiskImager to "Write" the fresh image to your sd card!? You can simply go the other way and "Read" the current system back into an image file.

**Comment by RaimondB** [comment]
I have just reinstalled using openhabian and things went fluently this time :-D

**Comment by ThomDietrich** [comment]
Great to hear ;)
