### ISSUE TITLE
Returning back to openHAB

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhabian#603]
Hey @EliasGabrielsson, @mstormi, @BClark09, @kaikreuzer, @davidgraeff, @kubawolanin and others,

I'm using this ticket to let you know that I am slowly coming back to help with the openHAB / openHABian project. When I decided to take a step back from the open source world at the beginning of 2018 I planned with approximately half a year to concentrate on my career. 
It have been 1,5 years since then and I can finally tell you that I am settled in my new job and just recently finished my PhD. With those things out of the way I am ready to re-join and enjoy this great community and all things accomplished and still to come.

I might spend the next couple of days just reading issues and adding comments. Please forgive all redundant questions and uninformed suggestions 😅 It might take me some time to get up to speed again but I can't wait to push my first PR.

Thanks for having me 😉

**Comment by kaikreuzer** [comment]
That's exciting news, it is awesome to hear that you are back with us!!! Btw, congrats on your PhD 🎉 .

**Comment by EliasGabrielsson** [comment]
Openhabian Captain back on ship, wonderful. Welcome back!
I really understand your career priorities, no worries. Take your time to get back. 😃

**Comment by dome2048** [comment]
That’s fantastic news! Congrats on your PhD!

**Comment by BClark09** [comment]
Congratulations! Happy to have you back with us! 🎉

I'm still sorting myself out but slowly coming back into things too. 😉

**Comment by ThomDietrich** [comment]
Thanks you all!

@kaikreuzer if the offer still stands I'd love to catch up some time.
@BClark09 right, are you also finished now?
@EliasGabrielsson from what I've seen you and the others have done a great job keeping everything up to speed. It's a shared effort 👍 We should synchup, I'll contact you via the team function.
