### ISSUE TITLE
Update keys with Upgrade option (02)

### ISSUE THREAD

**Issue by BClark09** [openhab/openhabian#607]
See https://community.openhab.org/t/apt-repo-public-key-expiration-update/78638.

Worth adding?

**Comment by mstormi** [comment]
No, we already do that
https://github.com/openhab/openhabian/blob/master/functions/openhab.bash#L49

**Comment by ThomDietrich** [comment]
In the forum comments users claim it didn't work for them when solely selecting the Upgrade option. @BClark09 I think this should definitely be added but accompanied by a TODO comment to remove after 2019-12 (or similar)
Would you like to create a PR?

**Comment by BClark09** [comment]
Done :)

**Comment by EliasGabrielsson** [comment]
@mstormi New systems work but older ones need to be fixed.
