### ISSUE TITLE
NGINX Proxy Configuration 

### ISSUE THREAD

**Issue by JoergPi** [openhab/openhabian#61]
Hi all,

I had to change one line in the generated NGINX config:
`#        proxy_set_header Host                   $http_host; `
`        proxy_set_header Host                   $proxy_host;`
The outcommented line redirected me always to "localhost".

Thanks to ThomDietrich for preparing openhabian and saving a lot of time for many people!

**Comment by BClark09** [comment]
Interesting! I can't replicate this problem, is there anything you've done to the hosts file after setting up openHABian?

**Comment by JoergPi** [comment]
Strange, I can reproduce this: changing the line back to " $http_host" gives me a redirection to "https://localhost" instead of forwarding to the openhab web service. 
My hosts file is
```
127.0.0.1 localhost
127.0.1.1 openhab
```
If I want to reproduce the effect after reloading the NGINX config, I have to close the browser window and initiate a new connection (using chromium on linux) to avoid just looking at my local cache.

**Comment by BClark09** [comment]
Right I've had a look at the script again, how do you connect to openHAB, through an IP or a domain name? Has your server_name been set to "localhost"?

**Comment by JoergPi** [comment]
I connect via IP address and the $server_name is "localhost (see the full NGINX / openhab conf file below).

```
#################################
# openHABian NGINX Confiuration #
#################################

## Redirection
server {
   listen                          80;
   server_name                     localhost;
   return 301                      https://$server_name$request_uri;
}

## Reverse Proxy to openHAB
server {
#    listen                          80;
   listen                          443 ssl;
    server_name                     localhost;
   add_header                      Strict-Transport-Security "max-age=31536000; includeSubDomains";

## Secure Certificate Locations
   ssl_certificate                 /etc/ssl/certs/openhab.crt;
   ssl_certificate_key             /etc/ssl/certs/openhab.key;

    location / {
        proxy_pass                              http://localhost:8080/;
#        proxy_buffering                         off;  # openHAB supports non-buffering specifically for SSEs now
#        proxy_set_header Host                   $http_host;
        proxy_set_header Host                   $proxy_host;
        proxy_set_header X-Real-IP              $remote_addr;
        proxy_set_header X-Forwarded-For        $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto      $scheme;

## Password Protection
#       auth_basic                              "Username and Password Required";
#       auth_basic_user_file                    /etc/nginx/.htpasswd;
    }

## Let's Encrypt webroot location
#   location /.well-known/acme-challenge/ {
#       root                                    /var/www/localhost;
#   }
}

# vim: filetype=conf

```

**Comment by BClark09** [comment]
Thanks! server_name shouldn't really be set as localhost, it should be the domain or ip address as the third line is redirecting using it. (I might have missed this change @ThomDietrich, sorry!) but I'm guessing that this is now the case if you have a non-static IP. We'll need to find a change that is suitable for all users, so will test various configurations using $proxy_host. But ideally $server_name should be your wan ip.

**Comment by mstormi** [comment]
given this is now 1.5 years old and nginx configuration generation has changed since, I suggest to close this issue as no longer relevant. @BClark09 please do if you agree.

**Comment by BClark09** [comment]
Yep, agreed.

**Comment by ThomDietrich** [comment]
@BClark09 did I not send you an invite to be a Collaborator a while back?

Agreed. @mstormi thanks for your housecleaning efforts
