### ISSUE TITLE
Cosmetical upgrade issue

### ISSUE THREAD

**Issue by JoergPi** [openhab/openhabian#62]
apt detects the currently installed openhab version as "upgradeable" but the target version is exactly the same:
```
[14:59:14] root@openhab:~# apt list --upgradable -a
Listing... Done
openhab2-offline/unknown,unknown 2.0.0~20161230210222 all [upgradable from: 2.0.0~20161230210222]
openhab2-offline/now 2.0.0~20161230210222 all [installed,upgradable to: 2.0.0~20161230210222]
```
Maybe that's gone after the next "real" upgrade ...

**Comment by BClark09** [comment]
This is a problem with the apt package for any apt users, not just openHABian. We're aiming to fix it when we move the Debian package creation over to it's own repo, as explained in https://github.com/openhab/openhab-linuxpkg/issues/11 . This has been working on initial tests.

**Comment by ThomDietrich** [comment]
This should be solved for a long time now. Thanks for initially reporting @JoergPi !
