### ISSUE TITLE
Deprecate support for Ubuntu [RFC]

### ISSUE THREAD

**Issue by EliasGabrielsson** [openhab/openhabian#621]
I suggest that we drop support for Ubuntu distros and only supports Debian based ones to reduce maintenance cost of the project. 

- [ ] Remove all traces of Ubuntu in the codebase
- [ ] Update Documentation
- [ ] Inform the user in the update dialog that Ubuntu based distros have been deprecated.

**Comment by mstormi** [comment]
Not sure I agree here.
Let's make sure first we talk about x86 only here (there's also Ubuntu on Raspi but that never has been supported so I think this talk is not about that).
Now there's way more users (out of those to run x86) that run Ubuntu than do run plain Debian x86.
A quick glance at the code shows Ubuntu specific code in InfluxDB and Homegear installation.
Both today seem to provide Ubuntu and Debian specific builds - not sure if they _require_ users to install this specific package (for InfluxDB the 'debian' seems to be a link to the ubuntu dirs?), but I assume the distinction is there for a reason.

Also remember Travis testing is based on Ubuntu not Debian.

**Comment by mstormi** [comment]
As commented we *should* support Ubuntu. Taking this forward in #926.
