### ISSUE TITLE
Export relevant openHAB installation script to the Armbian Project + deprecate support for PINE64

### ISSUE THREAD

**Issue by EliasGabrielsson** [openhab/openhabian#622]
The [Armbian project](https://www.armbian.com/) have an similar menu installation tool as our "manual installation" variant. In order to reduce maintenance of this project and support more ARM-based board I suggest that we try to contribute relevant code into that project.

There have already been effort of doing this in the past but I guess or script can improve the quality of the installation a bit. [Old work](https://github.com/armbian/config/blob/1338517aaec57662b4e7265474f36716057d79cc/debian-software#L919).

It's also tricky on which extent we should export features from openhabian script. 
My view so far:

- [ ] Install and switch between openHAB releases: _Stable_, _Milestone_, _Nightly_
- [ ] Install Java Zulu which is proven to work well with openHAB on ARM platforms.
- [ ] Configure a Samba share to reach the openHAB configuration files.

When we have an PR merged in the Armbian project we could:

- [ ] Drop support for PINE64 / clean our repo.
- [ ] Update and clean opnehab documentation with link to Armbian project.

**Comment by holgerfriedrich** [comment]
Hi @eliasgabrielsson, is there any progress? We are right now discussing how to reduce the maintenance effort and one thing would be to remove pine64 support...

**Comment by mstormi** [comment]
I'm wary of this proposed procedure. I don't mind to support Ambian maintainers but they have not really shown interest in this and, more important, we make ourselves dependent on them. We should not do that.
I'd rather drop PINE support now and tell PINE users (and those to use other unsupported ARM HW, see also #730) to check out Armbian, no matter if it includes exported work of ours or not. Manual install is supposed to work.
