### ISSUE TITLE
Deprecate support for Debian 8 - Jessie

### ISSUE THREAD

**Issue by EliasGabrielsson** [openhab/openhabian#623]
I suggest that we drop support for `Debian 8 - Jessie` to reduce maintenance in our codebase. (The LTS for Debian support release will expire June 30, 2020. )

**Comment by mstormi** [comment]
anything we would need to do other than to state that in the README ?

**Comment by holgerfriedrich** [comment]
In order to keep the codebase clean, remove any if_jessie clauses.
Deprecation note in README.
Do we need a disclaimer when openhabian-config starts on Jessie?

**Comment by mstormi** [comment]
See my proposed change #730 on HW/OS support.
So in this issue, there's the removal of jessie reminiscences from the code to remain.
