### ISSUE TITLE
Drop fixed path in favor of relative when calling binaries

### ISSUE THREAD

**Issue by EliasGabrielsson** [openhab/openhabian#625]
In order to get some more headroom for folder changes should the scripts in what extent is possible use relative calling on binaries. i.e. `git` in favor of `/local/bin/git`.

- [x] Update CONTRIBUTE.md with coding style
- [ ] Review all files in the whole repository

**Comment by mstormi** [comment]
For proper understanding: you mean in DISfavor of using the whole path, i.e. just use "git" in our scripts - correct ?
