### ISSUE TITLE
Remove speedtest install script

### ISSUE THREAD

**Issue by EliasGabrielsson** [openhab/openhabian#626]
There is a speedtest feature integrated within the Network Binding now.
Let's remove the speed test package.

**Comment by ThomDietrich** [comment]
Did any of you compare the two? Functionality and output are comparable? Happy to drop this in favor of an integrated solution

**Comment by EliasGabrielsson** [comment]
I did a fast compression and would say the main features of the OH version is in parity with the removed one.

**Comment by ThomDietrich** [comment]
Wonderful. Thanks
Sounds like a good step forward :)
