### ISSUE TITLE
Autoconfigured system-monitoring using openHAB Basic UI

### ISSUE THREAD

**Issue by EliasGabrielsson** [openhab/openhabian#627]
There is a need for a system monitoring feature accessible within a web-browser.
New linux/openhab users must have a feeling of confidence for and control over their system.

This issue tracks progress of automatically configure openHAB Basic UI with relevant bindings to provide that information. 

#### Information to show and sort of how: 

Network related:
- [ ] Speedtest - Internet speed (Network binding)
- [ ] Working public DNS ()
- [ ] Correct time, NTP connection. ()

**Comment by mstormi** [comment]
Depends: #998 
Speedtest AFAIK is gone but you're right, it would be a nice extension to have the DNS and NTP status 
Another important value is CPU load, systeminfo binding can provide that.

But we should not mandata any openHAB setup so how is this supposed to work outside OH?
FireMotD ?
Some script to feed the webserver that is used to display install logs ?
... ?

@openhab/openhabian-maintainers @holgerfriedrich @ecdye
any thoughts ?

**Comment by ecdye** [comment]
I almost feel like this would better exist as a separate openHABian binding which interfaces with openHAB directly. But that is also outside of the scope of this project.

**Comment by mstormi** [comment]
FWIW, FireMotD -t html will generate am HTML page of what you see on login

**Comment by mstormi** [comment]
on second and third thought, this will not offer what a user might expect to get from this (some sort of "auto error diagnosis").
There's NTP, network and sysinfo bindings in OH and if Internet really is gone the user will notice quickly anyway so little poitn in duplicating that in openHABian.
