### ISSUE TITLE
Remove script for installing Eclipse Mosquitto MQTT server

### ISSUE THREAD

**Issue by EliasGabrielsson** [openhab/openhabian#628]
Since openHAB 2.4 there exist an integrated MQTT server in the framework. This implementation have had some issues but most om them will probably be fixed by openHAB 2.5 release whereupon Eclipse Mosquitto optional package could be removed.

Make sure following optional packages don't rely on Eclipse Mosquitto:

- [ ] Miflora
- [ ] Find3 (or 2 if not updated)

This removal should be released inline with openHAB 2.5 as that release contain important MQTT fixes. (Elias guess for release date is december 2019)

**Comment by mstormi** [comment]
I believe it is a misunderstanding that the broker in Eclipse framework is to replace Mosquitto.
I think it has even been removed from the codebase meanwhile (probably even more probable now that openHAB moved away from ESH).
Can you confirm and eventually close this please ?

**Comment by mstormi** [comment]
Moquette (the embedded MQTT broker) has been removed from OH again, so we better keep mosquitto working.
