### ISSUE TITLE
New JAVA for openHAB3

### ISSUE THREAD

**Issue by EliasGabrielsson** [openhab/openhabian#629]
There are discussion on updating JAVA for openHAB 3.0 to at least JAVA 11.
https://github.com/openhab/openhab-distro/issues/768

Nothing new really, just update the packages when times come.
Java Zulu are providing 32-bit packages so we don't need to drop support for older RPis.

**Comment by mstormi** [comment]
There have been a number of proposals, issues and pieces of information related to what Java to use in the future such as  #805, #766, #723, #714, a number of forum posts such as https://community.openhab.org/t/running-openhab-2-on-openjdk/21443/8?u=benjy and more.

I'd like to be this the central place for discussing the way forward w.r.t. Java provider.

**Comment by mstormi** [comment]
Ok, I'll throw my hat to the round as a starter proposal:
* Let's not act overhasty and change the standard from Azul to whatever before OH 3 is ready.
  We should fix current issues to affect our current (Azul) Java install first such as #723 and #729 .
* Let's identify a JDK to be:
   Java v11, to have a JIT compiler, to be Open Source of course, to offer repo based install
   AdoptOpenJDK was proposed, other suggestions welcome
* let's add that _asap_ as an install _option_ in openHABian (alternative to Azul) to get this out to as many voluntary testers as possible to gain experiences
  (not sure if we can go straight to v11 with 2.5.3/3.0beta or still need to provide a v8 package)

**Comment by mstormi** [comment]
Going for Adopt 11 _and_ Zulu 11 now, with Zulu 8 to remain the default for now.

**Comment by mstormi** [comment]
@ecdye would you say we're done with this ?

**Comment by ecdye** [comment]
Yeah, It has been implemented and so far seems to be solid so I think we are done.

**Comment by mstormi** [comment]
Great. Thanks again for your contribution.
(btw I'm running Zulu11 for some days now).

**Comment by ecdye** [comment]
Glad to hear that it is working for you.
