### ISSUE TITLE
Openhabian failed to install

### ISSUE THREAD

**Issue by berre73** [openhab/openhabian#63]
Hi,

I have tried to install openhabian on a raspberry 2 and it fails to install.  Error sits on line:
Adding openHAB 2 Snapshot repositories to sources.list.d.  

I downloaded the latest image from openhab website.

What am i doing incorrectly?

Regards,

Bert

**Comment by berre73** [comment]
Solved in the meanwhile, most likely the server to get the repositories was down.  Thx

**Comment by ThomDietrich** [comment]
Happy to hear you've got the problem solved. Happy automating ;) 

Of the rare occasions something goes wrong, this seems to be one of the recurring reasons. I'll look into a retry strategy...
