### ISSUE TITLE
Update FIND optional package to version 3

### ISSUE THREAD

**Issue by EliasGabrielsson** [openhab/openhabian#632]
A new major rewrite of the FIND framework have been released. Would be nice have our script updated as well to install that version.

**Comment by mstormi** [comment]
it's been on my TODO list (I had been doing the old v2 package, too)

**Comment by EliasGabrielsson** [comment]
You are using it, perfect! Know what it does but aren't using it. Okey if I assign it to you?

**Comment by mstormi** [comment]
yes

**Comment by EliasGabrielsson** [comment]
Make sure this rewrite uses the internal MQTT server in openhab so we can deprecate Eclipse Mosquitto MQTT package. https://github.com/openhab/openhabian/issues/628

This patch should if possible install the internal MQTT broker by openHAB rest interface if needed.

**Comment by mstormi** [comment]
Mmh, I wouldn't eliminate Mosquitto in the first place. MQTT broker is brand new and not proven to work yet, and even if FIND3 did work with it there's many MQTT clients out there that may or may not.

**Comment by mstormi** [comment]
also update dashboard tile .gif with https://www.internalpositioning.com/splash-static/splash.gif

**Comment by ecdye** [comment]
I'm working on a update. I will share more when it is closer to completion.

**Comment by mstormi** [comment]
Good you mention it.
So did I a few days back. But I got stuck. I see HTTP requests going but it's not generating the DB like it did in earlier attempts and FIND2.

And don't start as root that'll create DB file that cannot be written to once you start as another user, resulting in server crash.

**Comment by ecdye** [comment]
Yeah, also I saw you had trouble installing `scipy` I figured out a workaround. Use `apt-get install --yes python3-scipy` it took me hours to figure it out.

**Comment by mstormi** [comment]
for scipy https://github.com/schollz/find3/pull/201

**Comment by ecdye** [comment]
I saw that, but the way to circumvent that for the moment is to use `apt-get install --yes python3-scipy`
