### ISSUE TITLE
Enhance debugging

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#638]
Re-reading the docs following 1.5 release, I came to think of this:
We (most noteworthy Thomas :)) want a lean, error-free screen output on standard installations
(openhabian-setup-sh unattended).
But we would also benefit from an extensive logfile a user can upload if his install goes wrong
(.... unattended_debug ? Eventually with even some more debugging).

I suggest to refactor all logging so we can have both at the same time, going to different logs.
wdyt?

**Comment by EliasGabrielsson** [comment]
Yes, already covered. Just a matter of having time to do the implementation.
See: https://github.com/openhab/openhabian/issues/408
