### ISSUE TITLE
Implement "tryUntil()" function for network actions.

### ISSUE THREAD

**Issue by EliasGabrielsson** [openhab/openhabian#639]
A lot of scripts in this repository deals with installation depending on network. All part which is not `apt-get` does not have internal error handling. I suggest we somehow create a method or standard pattern which tries a command and re-tries it until success. This is relevant for fetching of:

* TAR files
* Keys to apt-get repositories.

**Comment by EliasGabrielsson** [comment]
I found this promising software `loop` which looks like a good multitool for solving asynchronous stuff. However the installation is not super easy in current situation, would be nice to have it pre-included or at least available in the apt repositories.

https://github.com/Miserlou/Loop

**Comment by mstormi** [comment]
#681 will add tryUntil()
