### ISSUE TITLE
Bluetooth

### ISSUE THREAD

**Issue by alvarq** [openhab/openhabian#64]
The following file is generated the wrong way : 

> /lib/systemd/system/hciuart.service 

The device is referenced as Serial1 instead of ttyAMA0.
Attached the fixed output:

`
[Unit]
Description=Configure Bluetooth Modems connected by UART
ConditionPathIsDirectory=/proc/device-tree/soc/gpio@7e200000/bt_pins
Before=bluetooth.service
After=dev-ttyAMA0.device

[Service]
Type=forking
ExecStart=/usr/bin/hciattach /dev/ttyAMA0 bcm43xx 921600 noflow -

[Install]
WantedBy=multi-user.target
`

**Comment by ThomDietrich** [comment]
Hey @alvarq sorry for answering on this only now. What's the effect of what you are posting here.

Please be aware of https://community.openhab.org/t/openhabian-hassle-free-rpi-image/13379/650
I'll be looking to implement this.
