### ISSUE TITLE
Script fails to install zulu-embedded (due to new url maybe) 

### ISSUE THREAD

**Issue by libo** [openhab/openhabian#642]
This line https://github.com/openhab/openhabian/blob/master/functions/java-jre.bash#L38
tries to fetch the `tar.gz` from azul.com website by parsing the HTML code.

It looks like Azul changed something lately and the url the script tries to load:
`https://www.azul.com/downloads/zulu-embedded` actually redirects to `https://www.azul.com/products/zulu-embedded/`

(we don't use the `-L` option in curl so it doesn't follow redirections)

I have tried to update the URL in the script but with no success... looks like the page changed a lot.

**Comment by teolairlasg** [comment]
The links apparently are now in:
https://www.azul.com/downloads/zulu-community/

Download links (I think): (**https**)
https://cdn.azul.com/zulu-embedded/bin/zulu8.40.0.178-ca-jdk1.8.0_222-linux_aarch64.tar.gz
https://cdn.azul.com/zulu-embedded/bin/zulu8.40.0.178-ca-jdk1.8.0_222-linux_aarch32hf.tar.gz

I tried to change the regular expression adding the https but still not working. 
Could it be because of AJAX?

**Comment by libo** [comment]
Yes I inspected the code and can confirm that the list is populated asynchronously via a POST request to this end-point `https://www.azul.com/wp-admin/admin-ajax.php`

<img width="827" alt="Screenshot 2019-08-06 at 10 11 46" src="https://user-images.githubusercontent.com/37512/62522846-d270e380-b832-11e9-9218-951f2918a0b1.png">

@EliasGabrielsson I am wondering if it would make sense at this point to hard code the URLs to the JDK distros instead of trying to parse HTML with a regexp. That would also allow us to point to a specific version of the dist, and that might be not that a bad idea after all.

**Comment by EliasGabrielsson** [comment]
Hi!
Thanks for your research of this issue. I will try to make a patch for it this evening.
If any of you could make an PR I will merge it directly. 

// EG

**Comment by mstormi** [comment]
It's ok as a quick fix but generally speaking hardcoded URLs are not a good solution (as can be observed here).
As we have this in several locations I think it is worth a general review/refactoring of these.


On this here with Java, Azul seems to provide repos (again)
https://docs.azul.com/zulu/zuludocs/Content/ZuluReleaseNotes/Troubleshooting.htm#Azul_Repo_Tips

Maybe switch back to that install method ?

**Comment by EliasGabrielsson** [comment]
Repositories are ofc perferred if they are updated. They was listed in the documentation before as well even if they wasn't updated. I think we just need to try and find out. Otherwise we need to rework our regex script.

**Comment by BClark09** [comment]
> I think we just need to try and find out.

```
java -version
openjdk version "1.8.0_152"
OpenJDK Runtime Environment (Zulu Embedded 8.25.0.76-linux-aarch32hf) (build 1.8.0_152-b76)
OpenJDK Client VM (Zulu Embedded 8.25.0.76-linux-aarch32hf) (build 25.152-b76, mixed mode, Evaluation)
```

Is still the latest available from the provided repository.
