### ISSUE TITLE
Frontail optional fails to install

### ISSUE THREAD

**Issue by BClark09** [openhab/openhabian#647]
Not sure if this is platform specific (using Buster on RPi 4)

```
2019-08-06_17:23:01_BST [openHABian] Installing the openHAB Log Viewer (frontail)...
$ npm install -g frontail
npm ERR! path /usr/lib/node_modules/frontail
npm ERR! code EISGIT
npm ERR! git /usr/lib/node_modules/frontail: Appears to be a git repo or submodule.
npm ERR! git     /usr/lib/node_modules/frontail
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-08-06T16_23_10_187Z-debug.log
FAILED (frontail)
```

This can be fixed by removing the `/usr/lib/node_modules/.git directory` and trying again, but I'm not sure if this is an issue for openHABian or an upstream repo somewhere.

**Comment by holgerfriedrich** [comment]
Hi Ben, I encountered the same prob. My guess ist that it is already installed by default on openhabian in thus fails.

**Comment by pjbooth** [comment]
I have that same problem, but removing /usr/lib/node_modules/frontail/.git directory does not fix it.
