### ISSUE TITLE
Make openHABian less dependent of upstreams

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#655]
We have a couple of places where - in addition to where we use debian repos - we wget some URL or git clone Github repos.
We're usually retrieving the latest version which means it is not known to work at the time of install. Some of these instances even require to compile code, others in turn use yet another upstream.

I suggest we increase reliability by either of these methods or combinations thereof:
* fetch _tagged_ git versions only that we know to work
  (instead of master or anything that's subject to change quickly and without that we notice).
* create a cache by creating github mirror repos (or mirror them into openhabian repo)
* fetch packages and store them in openhabian repo for download
* compile binaries at image creation time and store them in openhabian repo for download

Instances to work on (will track here, let me know more via comments)

Critical (any user needs it):
~~openhabian repo itself~~
~~openhabian-zram, overlayfstools~~
~~Zulu Java~~, ~~Adopt Java~~, (OpenJDK ?)

Optional:
knxd
Tellstick
miflora daemon

Fixed for zram in PR #656 
Created 2 nested(!) mirror repos and added/use "openhabian_v1.5" tag for working code.

**Comment by EliasGabrielsson** [comment]
I actually discussed this topic with @ThomDietrich not long ago. First off all I don't see "one" correct way of solving this matter. I was exploring the thought of providing a verified configuration, per-installed image which is somewhat what you are suggesting. We ended up the discussion that is about where to put the maintenance resources and that when issues have occurred they have been solved rather quickly.

But maybe we need cherrypick some unstable upstream packages better. Which things have been-longterm broken so far because of upstream patches weren't merged?

**Comment by mstormi** [comment]
zram, knxd and Tellstick I believe, all of which were not ready for Buster.
Agree there's no single "correct" way but I think what I did for zram is a good solution for Github repos.
Mirror repos effectively don't change unless we actively pull/merge the upstream so they cost no maintenance resources unless we're willing to spend them as part of component or openHABian upgrade activities. Meanwhile no untested upstream can break installs.

**Comment by EliasGabrielsson** [comment]
Hmm, I think we should as long as possible stay with original repos to easliy track work. We should only use packages which are well maintained. It's always possible to checkout a single commit as well.

**Comment by mstormi** [comment]
I see no contradiction. Our mirror is just that, a mirror of the original repo. Albeit a more reliable, less volatile one. We could change something ourselves in there if needed or at least determine _when_ we expose openHABian users to changes in the original. Cloning the original repo during a user's install will _not_ provide that level of control.

**Comment by EliasGabrielsson** [comment]
> Let's continue discussion on #655 for that - we don't want updates to happen automatically.
> But we can enforce them at any time by updating the repo mirror.

I don't agree on this approach. I would say that the normal usecase shall be fetch upstream patches as fast as possible and rather fix bugs upstream or integration-issues downstream in our codebase. It is important to be in sync with upstream sources so we not get in a state with a lot of technical debt.

There can of course be exception to this as well. 

@BClark09 and @ThomDietrich, do you have any reflections on this?

**Comment by BClark09** [comment]
I agree with @EliasGabrielsson. Original upstreams should be use where possible. 

The workload of knowing which fixes/patches/features are maintained where becomes greater. Some upstream libraries may be slow to respond, but I would much rather this than figuring out how bugfix B from the upstream can be merged with additional feature A from a mirror.

To add, the zram feature has been moved from the original upstream (which looks well maintained) to a different upstream and this does not really solve the issue of making the openHABian project independant. Say we encounter an error that needs fixing, it's just more work to send a bugfix in two directions. (We shouldn't just patch our version of the code. I don't feel this is very friendly to an open source ecosystem.)

As @EliasGabrielsson mentioned, a specific commit from an upstream can be used if volitility is an issue.

**Comment by mstormi** [comment]
> To add, the zram feature has been moved from the original upstream (which looks well maintained) to a different upstream and this does not really solve the issue of making the openHABian project independant.

Err, no, it isn't really well-maintained. That maybe ain't visible at first, but that in fact was the reason for me to introduce that mirror level.

> Say we encounter an error that needs fixing, it's just more work to send a bugfix in two directions. (We shouldn't just patch our version of the code. I don't feel this is very friendly to an open source ecosystem.)

Agree insofar as in the normal case, we should send fixes of ours to the upstream only in the first place. But if he's slow or unwilling to react, we do have a means of overriding and mitigate impact that we do not have today.
And remember most upstreams don't "produce" for openHABian or are even just aware that we use their code. Actually if there is a change to the upstream that does not mean we need to have it or it is beneficial to us at all. It can even be the opposite. The consequence and downside of unvalidatedly forwarding changes to our users is that you take a fair risk to install something that's broken which shows up in openHABian first or only.  And to most of our own users this will look like a openHABian problem.
Most of the time it just doesn't matter if the old or new version is used thus there's no benefit in changing. Meanwhile any change has a potential to break/interrupt operations, and only in very few cases it's a fix we benefit from. In those cases we of course will take over the change by simply copying the repo (git rebase). Note this will also reduce the number of different versions in use which is desirable from the professional point of view.
We should aim professionalize our release management. It's known best practice in professional environments not to deploy any software that you have not previously tested yourself or to deploy versions that you don't need.

**Comment by EliasGabrielsson** [comment]
> In those cases we of course will take over the change by simply copying the repo (git rebase).

Merging diverted codebases are not as simply as you describe it and require extensive amount of work. I do not agree that your proposed method of release management is suitable for this project. I don't say it is wrong, but not suitable. To give the end user a good first-time experience using openHAB they should have the latest and greatest of all optional packages etc.

To achieve quality with that goal in mind I would say we shall focus on integrate and deploy often.
(Check this slidedeck why: http://frequentdeploys.club/)

If a user wants a super stable conservative installation for running critical automation they should not use openHABian as base installation.

**Comment by mstormi** [comment]
> Merging diverted codebases are not as simply as you describe it and require extensive amount of work.

Err ... that makes me believe we're not talking about the exactly same thing. I mean to use the origin repo as the *only* source (except in emergencies). All fixes should be sent & applied upstream and will trickle back down to us when we mirror (merge, but it's all from that single source so not really a merge).
You can also setup auto-mirroring to auto-replicate every change of a specific repo into openHABian if you really believe the latest is always the greatest. But I don't. [The Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance) between _leading_ edge and _bleeding_ edge is just 2 ...

**Comment by mstormi** [comment]
@EliasGabrielsson @holgerfriedrich please have another at this proposal.
The recent problems with Azul Java are a good example why we really need this IMHO.
Note that it isn't one-or-the-other.
While I still have the firm pov that latest isn't automatically greatest - i.e. we shouldn't install HEAD from remote repos -, we at least should reliability e.g. like this:
We could download and 'cache' a known-to-work package by storing it in the openhabian repo.
The install routine could then be reworked to try retrieving it from the source, but fall back to our copy if the source is unavailable.  wdyt?

**Comment by EliasGabrielsson** [comment]
The downtime during Azul Java change was around ~1day before it was fixed. I would say that is good enough tradeoff of always using the latest possible SW artifacts. Better to integrate often so we don't lag behind.

**Comment by mstormi** [comment]
FYI, we have another problem right now. Latest Azul package is broken.
We really need to come with a solution to cache "good" releases of upstreams.

Needless to say that the "integrate often" approach doesn't work when maintainers are absent.

**Comment by ecdye** [comment]
I don't believe that this is entirely necessary, in the Azul instance you refer to, it was more of a oversight than anything else. Additionally, the fix you suggested does not work in the case outlined as the system still downloads the binary and then bypasses the cache.

Also, the whole principle of openHABian is to create a lightweight system to be run on a small system like a RPi. The principle of caching is not holding true to the intended goal of the project. Furthermore, as it states in the installation article "The good news: openHABian helps you to stay away from Linux - The bad news: Not for long..." Which goes to show that it remains a user involved process. That is not to say that we should make it noob unfriendly but that there will be some errors and users should be able to report issues when they arise.

If the expectation is to provide a up-to-date system that is fully featured then I think that the approach we are implementing is perfectly fine. Particularly after the creation of a stable branch. Otherwise, we will effectively be changing the scope of the project.

**Comment by mstormi** [comment]
>I don't believe that this is entirely necessary,
> Additionally, the fix you suggested does not work in the case outlined
not sure what you mean (and no, not to be discussed here but in the respective issue please) but I fail to understand why we cannot (pre-)store a proven working copy

> Also, the whole principle of openHABian is to create a lightweight system to be run on a small
> system like a RPi. The principle of caching is not holding true to the intended goal of the project.

That's just an interpretation of yours and to be frank it's wrong. System size does not matter, there's enough space left even on a 8GB SD to do that. And don't take on the wording ("caching"), it's just one way of describing my intention.
I see no conflict with project goals in using caching/pre-storage/whatever .... that's what the image already does today.
On the contrary, this is a contribution to "hassle-free-ness" in its best possible sense.

> Which goes to show that it remains a user involved process. That is not to say that we should 
> make it noob unfriendly but that there will be some errors and users should be able to report 
> issues when they arise

That's yet another completely different thing, please don't mix all of these.
First and foremost goal is openHAB to be hassle-free and we want to avoid a need for users to manually step in (and hence a need for them to be proficient in Linux).
Today's openHABian is less so than it would be with my proposal here in place because today it depends on external sources to be available at installation time.
Installation time is the first time a user has contact with openHABian and openHAB.
If that does not work out for the user, it's also often the last time he touches this stuff.
Remember there's no chance for a 2nd first impression!

Enhancements to troubleshoot openHABian again is yet another story, but this was quite recently adressed as well with the debug guide in #683 and continues to be of relevance in everything we do.

**Comment by mstormi** [comment]
BTW The latest Raspbian (lite) image that is available for download includes Oracle JDK and other packages that require licensing. For their handling see [here](https://www.raspberrypi.org/downloads/raspbian/)

**Comment by ecdye** [comment]
Is it possible to remove licensed packages?

**Comment by mstormi** [comment]
> Is it possible to remove licensed packages?

Of course, Raspbian is no fixed bundle.

**Comment by mstormi** [comment]
openHABian has essentially been made capable of an install to succeed even if Internet connectivity is unavailable.
Enhancements to make this work for optional components too, like Tellstick, are of course still welcome but they're not crucial.
As the main goal is reached (and the main driver gone), I'll close this issue.
