### ISSUE TITLE
customize Java parameters depending on HW+OS architecture

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#669]
Current values are good for 1GB RPis but there's also ARM machines with more RAM and
there's x86. And it depends on the JVM and OS version to be 32 or 64bit.
We should provide adjusted parameters.

64bit x86 will use 4 times as much RAM as 32 bit ARM.

**Comment by EliasGabrielsson** [comment]
Sounds reasonable.
Are there any historical data on memory usage floating around in the forum?

**Comment by mstormi** [comment]
no I think everything floating is what I have come up with

**Comment by wborn** [comment]
The memory requirements are probably also different if you use a 32-bit JVM on a 64-bit OS.

**Comment by mstormi** [comment]
yes. Unfortunately I don't have all the HW and OSs to test.

**Comment by EliasGabrielsson** [comment]
@BClark09 I wonder if this configuration should be included in openhab installation, i.e.`openhab-linuxpkg`. This issue is not unique for openhabian rather applicable for all linux installations.

**Comment by mstormi** [comment]
> This issue is not unique for openhabian rather applicable for all linux installations.

No it **is** as params are set in  /etc/default/openhab2

**Comment by EliasGabrielsson** [comment]
> This issue is not unique for openhabian rather applicable for all linux installations.

... running openHAB.

**Comment by EliasGabrielsson** [comment]
Did some random searches on the forum and found the data below.
(I have not taken into account for the number of packages etc. installed.)

A variant could be:
`xms = RAM * 0.2` at least `250M` max `400M`
`xmx = RAM * 0.6` at least `350M` max `1000M`

```
612M
598M
164M
471M
501M
546M
532M
164M
```

**Comment by BClark09** [comment]
> This issue is not unique for openhabian rather applicable for all linux installations running openHAB.

It's applicable to all installs regardless of operating system. So if setting the maximum allocation pool is important wouldn't this be more appropriate to do in the distribution's `setenv` and `setenv.bat` scripts?

**Comment by wborn** [comment]
Personally I never touch the Xmx and Xms settings unless I a have good reason. A memory constraint device with <= 1GB memory could be a good reason to touch it.

AFAIK the JVM already has a decent mechanism to scale the memory based on what is available. So also this [StackOverlow discussion](https://stackoverflow.com/a/28273076).

**Comment by EliasGabrielsson** [comment]
@BClark09 do you know where to find these files / function?

**Comment by BClark09** [comment]
I also have never set them on my systems, and have had no reason to even when I had my home system on the RPi 3.

With the other additional services openHABian brings onto a system with 1GB of ram though as @wborn said it could be important. I think this means that this is primarily an openHABian issue? If not then...

> do you know where to find these files / function?

https://github.com/openhab/openhab-distro/tree/master/distributions/openhab/src/main/resources/bin

**Comment by EliasGabrielsson** [comment]
Okay, reading from documentation:

> **maximum heap size**
> Smaller of 1/4th of the physical memory or 1GB. Before Java SE 5.0, the default maximum heap size was 64MB. You can override this default using the -Xmx command-line option.

I interpret it as if openHAB should have access to 600Mb of heap (xmx) all system below 2.4GB ram would need to have this setting adjusted. I will create an PR in the `openhab-distro` repository. 

And, yes we shall remove all memory adjustment code from this repository when openHAB 2.5 is released assumed that fix above is merged.

**Comment by mstormi** [comment]
FTR: there's a specific need to increase -Xms because it'll keep compiled rules in RAM rather than to dump them on garbage collections which happens if you use the default Java strategy.
Re-loading rules means hefty delays (even more so on ARM) which is impacting user experience and IMHO is inacceptable in OpenHAB deployments.

Xmx is not important as it's the hard limit (Java to stop) but we have not really seen that happen except in rare cases with memleaks.

**Comment by mstormi** [comment]
Thinking to add GC optimization parameters instead of/in addition to -Xms
Goal: keep compiled rules in RAM. There's multiple reports of days of several seconds when a rule was used again after some hours of inactivity.

Candidates:
1. -XX:-UseAdaptiveSizePolicy -XX:+UseParallelGC -XX:InitiatingHeapOccupancyPercent=95
2. -XX:MinHeapFreeRatio=15 -XX:MaxHeapFreeRatio=30
3. -XX:+UseCodeCacheFlushing

Anyone willing to help with testing, please join in.

**Comment by mstormi** [comment]
FYI with #684 merged, we can build all these variants in Travis
BUT mind #855: I have not found a good way to measure and compare memory usage _inside_ Travis yet. Any ideas welcome.

**Comment by mstormi** [comment]
Using our new CI pipeline, I just found out that Azul JVM does not work in 64 bit on RPi 3/4.
Couldn't believe that and thought the tests must have been bad but validated by failing to manually upgrade my own box. It's true.

**Comment by mstormi** [comment]
FYI with #848 merged we now enforce 32bit Azul install where 64 would not work

Java parameters are still TBD

**Comment by mstormi** [comment]
Current code set a low -Xms (16m) on ARM devices < 1GB, slightly increases -Xms -Xmx over defaults if on ARM with >= 1GB and uses JVM defaults if on x86.

Things may change when 64bit OS for ARM becomes available but there is none such there today.
64bit JVMs turned out not to run on 32bit OS so we now check and downgrade if necessary.

After playing with various more settings on memory, I believe that for the time being keeping the current code provides pretty good settings and we should mess with that no further.
Anyone, please reopen if there's significant news or you disagree with my reasoning.
