### ISSUE TITLE
Installation failes due to missing repos

### ISSUE THREAD

**Issue by anttisep** [openhab/openhabian#67]
Hi,

The installation of latest image fails due to some missing repos. From /var/log/raspbian-ua-netinst.log:
`[openHABian] Adding openHAB 2 Snapshot repositories to sources.list.d... FAILED`

The reason can be found while manually running /opt/openhabian/openhabian-setup.sh:
```
W: Failed to fetch https://openhab.ci.cloudbees.com/job/openHAB-Distribution/ws/distributions/openhab-offline/target/apt-repo/Packages  HttpError404
W: Failed to fetch https://openhab.ci.cloudbees.com/job/openHAB-Distribution/ws/distributions/openhab-online/target/apt-repo/Packages  HttpError404
```

Thank you for all your efforts and Best Regads,
 - Antti

**Comment by devgiants** [comment]
Hello,
I just had the same thing, 2 install failed last night and this morning too.

Thank you for your work,
Regards,

Nicolas

**Comment by anttisep** [comment]
It appears that the installer is using cloudbees Jenkins workspace as a repository. As the previous Jenkins build was aborted, the build artifacts are missing from workspace. Until new (successful) build is triggered, installer can't install packages. Future installations will occasionally fail if e.g. Jenkins build is ongoing.
So this isn't openhabian bug as itself, but an alternative solution for installer to fetch packages might be a worth of something to look into.

**Comment by anttisep** [comment]
Temporary ugly workaround:
1) After failed installation, log into the system.
2) Modify /opt/openhabian/openhabian-setup.sh:
   - In function openhab2_addrepo() comment out (or remove) the two lines which are adding the failing repositories: 
     # echo "deb https://openhab.ci.cloudbees.com/job/openHAB-Distrib.... >> /etc/apt/sources.list.d/openhab2.list
     # echo "deb https://openhab.ci.cloudbees.com/job/openHAB-Distrib.... >> /etc/apt/sources.list.d/openhab2.list
   - In function openhab2_install() comment out line:
     # cond_redirect apt -y install openhab2-offline
3) Manually fetch and install last successful artifact:
   wget https://openhab.ci.cloudbees.com/job/openHAB-Distribution/lastSuccessfulBuild/artifact/distributions/openhab-offline/target/openhab2-offline-2.0.0-SNAPSHOT.deb
   dpkg -i openhab2-offline-2.0.0-SNAPSHOT.deb
4) Remove missing repository entry:
   rm -f /etc/apt/sources.list.d/openhab2.list
5) Restart unattended setup:
   /opt/openhabian/openhabian-setup.sh unattended

**Comment by anttisep** [comment]
The repository seems to have come back available. Closing this issue.

**Comment by ThomDietrich** [comment]
Hey @anttisep you should just have waited :D The problem is unfortunate for sure. I hope/believe this problem will not occur with the new repository available soon. From the instructions you posted I get the impression that yo dug deep into the openHABian scripts. Nice work ;)
