### ISSUE TITLE
Docker (Travis) test installation often fail on "Updating repositories and upgrading installed packages"

### ISSUE THREAD

**Issue by EliasGabrielsson** [openhab/openhabian#678]
Travis often fail due to:
```
2019-08-25_06:14:31_JST [openHABian] Updating repositories and upgrading installed packages... FAILED
```
After some retry the test use to be successful.
Investigate and fix.

**Comment by mstormi** [comment]
In my build syystem refactoring I introduced a parameter "mode" to openhabian.conf with default "unattended" to define the parameter(s) that "openhabian-setup.sh" is called with from within build-image/first-boot.bash. Set it via sed in Dockerfile.openhabian to "unattended_debug" to get the output.

I don't remember the reason for every single changeI made in the buildsystem PR, but setup hanging at this stage was among them. Now I don't see it any more.

**Comment by EliasGabrielsson** [comment]
Good to see some progress!
If it is possible I would like smaller patches for the buildsystem when you are ready,
i.e isolate smaller parts as separates PR. 

For example the "unattended_debug" solution you implemented sounds closely related to: https://github.com/openhab/openhabian/issues/408 . Isolating would improve and speed up the review process a lot.

**Comment by mstormi** [comment]
As requested will split into smaller patches.
I keep https://github.com/openhab/openhabian/pull/616 open to track all of this.

On this issue here, I just encountered it when building #681 , too.
But the (verly likely) reason for this is that test builds are for now still based on the ancient minimum2scp/systemd-stretch image which has no python etc.
Let's revisit when we're done with the buildsystem upgrade.

**Comment by mstormi** [comment]
> For example the "unattended_debug" solution you implemented sounds closely related to: #408 .
it's related but a different request.

What a user can do now when he has install troubles is to edit /etc/openhabian.conf to contain mode=unattended_debug and reinstall. Will provide us "debug level" first-boot.log.

**Comment by mstormi** [comment]
> For example the "unattended_debug" solution you implemented sounds closely related to: #408 .
I've now also added an "unattended_debug_maximum". I had experimented with a complementary log as discussed in #408 but didn't find any satisfying solution. Now this options does "set -x" so every command is literally recorded, too. Not the nicest of formattings but simple and effective.

**Comment by mstormi** [comment]
minimum2scp/systemd-buster image has become available
Upgraded there in #681

**Comment by mstormi** [comment]
With #681 and #682 merged, I have not seen this any more.
Please re-check and eventually close.
