### ISSUE TITLE
getting error invalid distance too far back

### ISSUE THREAD

**Issue by idkpmiller** [openhab/openhabian#679]
I am looking to update using openhabian-config and when I do I get this output.
I am on OH 2.4 stable and I installed openhabian a year or more ago, not sure when I last tried to update it.
Please advise.

`[14:15:03] openhabian@openhab:~$ sudo openhabian-config
2019-08-25_14:15:18_NZST [openHABian] Checking for root privileges... OK
2019-08-25_14:15:19_NZST [openHABian] Loading configuration file '/etc/openhabian.conf'... OK
2019-08-25_14:15:22_NZST [openHABian] openHABian configuration tool version: [master]v1.4.1-413(7799e0d)
2019-08-25_14:15:22_NZST [openHABian] Checking for changes in origin... error: inflate: data stream error (nvalid distance too far back)
error: failed to read object 629870b3ebe5ca46fb22e78de1e6c2283d125338 at offset 377572 from .git/objects/pak/pack-94dc81e2b904f0c1ab298b1fa191427bef519c38.pack
fatal: packed object 629870b3ebe5ca46fb22e78de1e6c2283d125338 (stored in .git/objects/pack/pack-94dc81e2b90f0c1ab298b1fa191427bef519c38.pack) is corrupt
fatal: index-pack failed
OK
2019-08-25_14:15:29_NZST [openHABian] Updating myself... error: inflate: data stream error (invalid distanc too far back)
error: failed to read object 629870b3ebe5ca46fb22e78de1e6c2283d125338 at offset 377572 from .git/objects/pak/pack-94dc81e2b904f0c1ab298b1fa191427bef519c38.pack
fatal: packed object 629870b3ebe5ca46fb22e78de1e6c2283d125338 (stored in .git/objects/pack/pack-94dc81e2b90f0c1ab298b1fa191427bef519c38.pack) is corrupt
fatal: index-pack failed
FAILED - There was a problem fetching the latest changes for the openHABian configuration tool. Please chec your internet connection and try again later...
2019-08-25_14:15:39_NZST [openHABian] Checking for default openHABian username:password combination... OK
2019-08-25_14:15:39_NZST [openHABian] We hope you got what you came for! See you again soon ;)
`

Regards
Paul

**Comment by idkpmiller** [comment]
I have moved on some what.
I renamed the /opt/openhabian directory to .bak
I deleted the /usr/local/bin/openhabian-config file and then followed the install process as described here under other Linux system.
[https://www.openhab.org/docs/installation/openhabian.html#other-linux-systems-add-openhabian-just-like-any-other-software](url)

now I can perform update, and system update fine but when I get to stable update I get this error

`$ apt-get -y --allow-downgrades install openhab2=2.4.0-1
E: Command line option --allow-downgrades is not understood
FAILED (apt)
`

I will try next to run the command locally sudo apt-get -y install openhab2=2.4.0-1
That says I am already on the lastest version.
I do seem to hitting one problem after another I can only assume that I have something wrong from the start???

Thanks
Paul

**Comment by holgerfriedrich** [comment]
Hi Paul, 
I introduced
<pre>--allow-downgrades</pre>
just a few days ago to allow switching to between openhab releases on newer versions of apt.
Can you please let me know on which operating system you run openhabian and the version of apt (e.g. <pre>cat /etc/debian_version
apt --version
</pre> on Raspbian or Debian based systems.)
Thanks.

Regarding openhab, version 2.4.0-1 is still the current stable release.

**Comment by holgerfriedrich** [comment]
Cannot reproduce. Tried to execute the typical commands from openhabian.bash for updating on an old backup, did not get this error.
My assumption is that the repo was somehow damaged.
