### ISSUE TITLE
Replace apt snapshot repository

### ISSUE THREAD

**Issue by kubawolanin** [openhab/openhabian#68]
Apt repository changed for recent openHAB2 distro. See [this thread](https://community.openhab.org/t/replacement-of-the-apt-snapshot-repository/19674) for more details.

Also it would be good to have a choice in openHABian config whether you want to update to "unstable" (old "snapshot") or "stable" distro.

Thank you @ThomDietrich for your work! 🙂

**Comment by kubawolanin** [comment]
Closing since was resolved with #71 - Thanks @ThomDietrich 

In the future, do you think it will be feasible to choose between latest (e.g. openHAB2 final) and unstable (snapshot)?

Best regards

**Comment by ThomDietrich** [comment]
https://github.com/openhab/openhabian/issues/41#issuecomment-271367723

Yes ;)
