### ISSUE TITLE
Remove unneccesary "apt-get update"

### ISSUE THREAD

**Issue by EliasGabrielsson** [openhab/openhabian#685]
Remove all `apt-get update` beside:
a) Run once in first-boot
b) Run once when openhabian-config start
c) Run when a new repository is added.

- [ ] Update codebase
- [ ] Update CONTRIBUTING.md

**Comment by mstormi** [comment]
It's actually a little annoying to wait for apt update to finish on every tool start.
Could we maybe put that process into the background? apt has a locking system that should guarantee we cannot issue more than one command at a time.

**Comment by EliasGabrielsson** [comment]
I thought about that as well when I implemented it. 
Having it in the background is great idea. Is it possible that `apt-get` command could be queued?
Otherwise the script will fail.

**Comment by mstormi** [comment]
Maybe like this?
https://askubuntu.com/questions/132059/how-to-make-a-package-manager-wait-if-another-instance-of-apt-is-running

**Comment by mstormi** [comment]
See #724
