### ISSUE TITLE
Make sure "Frontail" installation is adapted to node.js installation structure

### ISSUE THREAD

**Issue by EliasGabrielsson** [openhab/openhabian#687]
There have been several issues with frontail depending on how the node.js structure is.
Rewrite `Frontail` (and other?) package to dynamic set this somehow.

See:
https://github.com/openhab/openhabian/pull/676
https://github.com/openhab/openhabian/pull/674
https://community.openhab.org/t/frontail-not-starting-after-fresh-install-openhabian/80597

**Comment by mstormi** [comment]
PR #688

**Comment by mstormi** [comment]
fixed by #688 I believe, if not please reopen
