### ISSUE TITLE
Setup Camera Module to work with openHAB

### ISSUE THREAD

**Issue by EliasGabrielsson** [openhab/openhabian#693]
Raspberry Pi offers the possibilities to attach a camera. 
A little edge use-case which could be worth looking into is to integrate that into openHAB.

- [ ] Use [RPi-Cam-Web-Interface](https://elinux.org/RPi-Cam-Web-Interface) to setup video and still-images endpoint using `https`.
- [ ] Make sure the web-server configuration is compatible with other web-services provided by openHABian. The setup could conflict.
- [ ] Password protect the installation and also make it possible to change password from "Password Menu" in openHAB.
- [ ] Make a link to the RPi-Cam-Web-Interface webinterface on the "openHAB" dashboard.
- [ ] Create an example sitemap for basic-UI using the camera.

- [ ] Investigate if the camera RPi-Cam-Web-Interface provide some sort of API and if so integrate support into the [IP Camera binding](https://github.com/Skinah/IpCamera)

**Comment by mstormi** [comment]
@openhab/openhabian-maintainers @holgerfriedrich
would you think this is still in line with our recent agreement to shift focus to reliability rather than new features ?
I think it's a new feature and an edge case (if I was to use a camera, I wouldn't use a Pi hat)

**Comment by holgerfriedrich** [comment]
I think it is useful to demonstrate capabilities, but probably not the typical use case for openHAB.
Not yet clear how to implement, and challenging to add useful tests in our CI.
Seems to be out of focus right now.

**Comment by mstormi** [comment]
I hope you agree if I was to say it's not in scope for openHABian.
So will close. Feel free to reopen if you have code to share to make it work.
