### ISSUE TITLE
Rewrite tmp folders ".XXXXXX" to show connection to openhabian.

### ISSUE THREAD

**Issue by EliasGabrielsson** [openhab/openhabian#694]
> I would prefer a pattern like openhabian.XXXX
> .hides the directory and users cannot see which script created the directory, just in case we fail in deleting it.

cc @holgerfriedrich 

At least I think we would mark them with openhabian, hidden or not.
@mstormi what do you say?

**Comment by mstormi** [comment]
yep makes sense to me

PS oh dear it's already a quarter to 2AM. Need to get some sleep now
