### ISSUE TITLE
openhab can't control GPIO raspberrypi (using a LED for testing)

### ISSUE THREAD

**Issue by primafauzan** [openhab/openhabian#698]
I had installed openhab2  using manual installation. i followed the instruction like the link says
https://www.openhab.org/docs/installation/linux.html#package-repository-installation

and I also had installed MQTT server clients, GPIO binding, and HabCloud.

I edited the items (Type in sudo nano /etc/openhab2/items/home.items) and I type : 
Switch LED "LED" { gpio="pin:21" }
I also edited the sitemap (type in sudo nano /etc/openhab2/sitemaps/home.sitemap) and I type :
Switch item=LED

I can open my openhab and turn on/off the switch on its interface. but nothing happened my LED.

Anyone can help me?
p.s : I use debian jessie OS, and GPIO pin 21 BCM

**Comment by mstormi** [comment]
Sorry but this is the wrong location for requests like yours.
Open a thread over at https://community.openhab.org .

**Comment by EliasGabrielsson** [comment]
Hi @primafauzan 
Welcome using the openHAB software.
These issue threads are about a specific installation script called [openHABian](https://www.openhab.org/docs/installation/openhabian.html) automating the manually installation which you have already done (i.e installing openHAB). As Markus says the forum is the right place to ask for guidance about configuring openHAB.
