### ISSUE TITLE
"Homegear" packages timeout in Travis

### ISSUE THREAD

**Issue by EliasGabrielsson** [openhab/openhabian#699]
The tests concerning Homegear have timed several times.
This could indicate some issue with the installation code maybe or that we need to improve the error handling. 

Investigate and resolve

**Comment by mstormi** [comment]
With #682 merged, check this again please

**Comment by mstormi** [comment]
Elias with the all-new build system in place, is this still an issue ?

**Comment by mstormi** [comment]
I have not seen any homegear BATS test or install fail throughout all of the new build system development.
Please reopen if you see it happen again.
