### ISSUE TITLE
Installation finishes but says "seems to have failed"

### ISSUE THREAD

**Issue by brunosarlo** [openhab/openhabian#70]
Hi, first of all thanks for this magical img!

I have this alert after installation and just wanted to report it, in case it's helpfull for you.

My first try give me this alert when I logged in first time:

`Attention! The openHABian setup process seems to have failed on your system.
Sorry, this shouldn't happen! Please restart the installation process. Chances
are high setup will succeed on the second try. Execute the following commands
to restart now:
   sudo mv /boot/config-reinstall.txt /boot/config.txt
   sudo reboot

In order to find the cause of the problem, have a look at the installation log:
   sudo tail -n 20 /var/log/raspbian-ua-netinst.log
`

This are the last 200 lines of the log: https://gist.github.com/brunosarlo/c6ff65ad5d13bd567eb0d8c109cb7447

**Comment by ThomDietrich** [comment]
Hey @brunosarlo, you really decided to install openHABian on the wrong day :) There have been some changes to the openHAB repository today and I'll change the openHABian installation script this evening. I'll let you know. After it's done you just have to execute the mentioned two commands.

**Comment by ThomDietrich** [comment]
@brunosarlo You should be good to go.

```shell
sudo mv /boot/config-reinstall.txt /boot/config.txt
sudo reboot
```

**Comment by brunosarlo** [comment]
Thanks! :)
