### ISSUE TITLE
Bluetooth not initializing on boot ?

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#707]
from syslog right after boot
I did not use menu to enable BT and cannot test if BT works or not so this might be a problem or not. Either way the error message should not show up.

HW is a RPi 2 
root@openhab:/home/openhabian# ls -l /dev/serial*
lrwxrwxrwx 1 root root 7 Sep  6 11:01 /dev/serial0 -> ttyAMA0

```
Sep  6 10:07:01 openhab systemd[1]: dev-serial1.device: Job dev-serial1.device/start timed out.
Sep  6 10:07:01 openhab systemd[1]: Timed out waiting for device /dev/serial1.
Sep  6 10:07:01 openhab systemd[1]: Dependency failed for Configure Bluetooth Modems connected by UART.
Sep  6 10:07:01 openhab systemd[1]: hciuart.service: Job hciuart.service/start failed with result 'dependency'.
Sep  6 10:07:01 openhab systemd[1]: dev-serial1.device: Job dev-serial1.device/start failed with result 'timeout'.

```

**Comment by EliasGabrielsson** [comment]
Are these issues also present on the released image?

**Comment by mstormi** [comment]
dunno, can't test ATM
I don't think it's shellcheck related so I would guess yes

**Comment by EliasGabrielsson** [comment]
I reread this issue today Markus but I have a hard time following you. You are discussing WiFi USB sticks but the title rather implies that the issue is about bluetooth. Could you maybe restructure the main post to clearly point out the error symptom? 

Thereafter you are very welcome to add your conclusions about the issue.

**Comment by mstormi** [comment]
ok, I removed the confusing WiFi stuff

**Comment by mstormi** [comment]
not observed in most recent code
