### ISSUE TITLE
openhabian_update() switches back to master

### ISSUE THREAD

**Issue by holgerfriedrich** [openhab/openhabian#715]
During development, `build.bash` can be used with option `dev-git`.
The current repo and branch is put into first-boot script.

Running the config tool an running the option `01 | Update`, currently checked out branch is ignored and reset to master. My expectation would be that it sticks to the branch.

Looking at the implementation of `openhabian_update()` I am a bit confused.

**Comment by mstormi** [comment]
I didn't have a closer look, but I would NOT expect to keep the branch. It's only us (contributors, testers) to need/ever be affected by that. And you must not use 01 | Update during tests.
Ok, you _could_ change the code if you have the spare time, but be aware to not increase the risk of some user to accidently get affected, too.

**Comment by ThomDietrich** [comment]
Hey guys,
Generally I agree with @mstormi, this is only for developers and should not be a real issue to be solved.

Another undocumented function you might be interested in is https://github.com/openhab/openhabian/blob/master/functions/openhabian.bash#L42
Press any button right after selecting the update option to check out a custom branch.

**Comment by EliasGabrielsson** [comment]
The `dev-git` option was developed to enable real hardware installation tests of new feature branches like the shellcheck one. The installation was not meant to be upgraded after that. I don't think we should clutter the production code to handle this edge case. 

What I do think is a natural development of the `dev` option for building images is to automatically run all test after the system is installed. In that way we will get a reproducible test we can run for every new major change in the codebase.

**Comment by mstormi** [comment]
@holgerfriedrich with the build system to checkout the _changed_ repo and the dev stage tests introduced in #682, can we close this? If so please do.

**Comment by holgerfriedrich** [comment]
Need to re-evaluate one we manage to merge those PRs...

**Comment by mstormi** [comment]
With #681 merged (to fix the same problem on unattended installs), is this still a problem for builds ?

**Comment by mstormi** [comment]
@holgerfriedrich with #683 now merged, is this still an issue ?
Did you check if build.bach works again ?

**Comment by mstormi** [comment]
@holgerfriedrich with all build system PRs now merged, is this still an issue ?

**Comment by holgerfriedrich** [comment]
Adding of `repositoryurl`and `clonebranch` to `/etc/openhabian.conf` resolved this issue.
