### ISSUE TITLE
build.bash - usablity improvements

### ISSUE THREAD

**Issue by holgerfriedrich** [openhab/openhabian#716]
@holgerfriedrich 
build.bash shall check the second parameter to catch typos or unknown-parameters (who can remember if it is dev-git or git-dev?).

If a non-standard repo is used, filename of the generated image shall shall either include a string "custom" or include the repo and branch name. 

This is just a reminder for me to make a PR after shellcheck stuff is merged.

**Comment by EliasGabrielsson** [comment]
You are very welcome to improve this. It was really sketchy work when it initially was developed 👍

**Comment by mstormi** [comment]
@holgerfriedrich reminding you of your reminder :)
