### ISSUE TITLE
Clearify formating of "FAILED" check.

### ISSUE THREAD

**Issue by EliasGabrielsson** [openhab/openhabian#720]
The fixes of the shellcheck issues made the code related to checking for errors a bit more foggy. An simple rewrite of the if statements would be:

```
if \
  command1 && \
  command 2 && \
  command 3 ; \
then echo "OK"; else echo "FAILED"; exit 1; fi
```

**Comment by mstormi** [comment]
We don't use && all that frequently and I don't see the need to rework the whole code because of this.
Feel free to reopen if you disagree.
