### ISSUE TITLE
Beautify install output

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#721]
Using the RPi image, openhabian install starts before the boot process ended, resulting in an ugly mix of log lines printed to the console.
The whole look isn't _trustworthy_ .
Not sure what's the best fix, a sleep or dependency in systemd to start later.

**Comment by ThomDietrich** [comment]
I didn't get that. Could you explain in another way? There are steps (like the loop around apt-get update) to ensure that parts of the system are ready when needed

**Comment by mstormi** [comment]
![IMG_20190923_165738](https://user-images.githubusercontent.com/12220522/65438731-4b99b980-de26-11e9-9694-7026c0b653c5.jpg)

This looks messy because installation is started before the boot sequence finishes.

**Comment by mstormi** [comment]
@ThomDietrich did this happen on your recent install ? (or did you not use a console? If no please try with one)

**Comment by holgerfriedrich** [comment]
Looked the same when I did an install recently.

Maybe we should make sure normal system start is done before starting installation. This may also have positive side effects like system time being set before....

I would also propose to use another console for the detailed output which can instantly be seen when strg-alt-f2 is hit.

**Comment by mstormi** [comment]
Holger would you say we're done here ?

**Comment by mstormi** [comment]
My most recent install with the beta image on a RPi4 showed little but still some remaining overlapping.
The first OHian install related message after which there were no more boot messages has a timestamp of 60.xxx.

So Holger can insert an additional delay of 1 minute before executing first-boot?
That should do I guess.

**Comment by mstormi** [comment]
@holgerfriedrich could you add that 1 min delay then close this ?

**Comment by holgerfriedrich** [comment]
@mstormi I don't think that adding delays is the right way to go here, though it makes the install look nice. People will wonder why they cannot connect via webif for such a long time, etc. WiFi based install will wait twice due to reboot. 
For me it would be much cleaner solution to look which services are producing the output and play with the systemd dependency/after/... options to resolve.
I won't be able to do this the next days.

**Comment by ecdye** [comment]
> For me it would be much cleaner solution to look which services are producing the output and play with the systemd dependency/after/... options to resolve.

In this case I agree with Holger, we should look into other solutions. This does not need to be in before a new image so we can take our time.

**Comment by mstormi** [comment]
Did that already: https://github.com/openhab/openhabian/pull/985#issuecomment-654664698

**Comment by ecdye** [comment]
Yeah, I noticed that after I posted that comment.

**Comment by mstormi** [comment]
The current setup via systemd dependencies, while not perfect, has been optimized and latest installations look pretty fine now (in a literal sense) so I'd think we can close this now.
