### ISSUE TITLE
current Java gets installed again and openHAB restarted on every system upgrade from openhabian-config

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#723]
See https://community.openhab.org/t/openhabian-config-zulu-openjdk-forces-openhab-to-restart/82173/2

**Comment by mstormi** [comment]
Just guessing, maybe the repo based install is still 'active' because of sources in /etc/apt/sources.list.d to still exist ? Haven't checked if these still get installed but at least they're still there with installs that were made earlier when this for sure was still part of the code.

**Comment by mstormi** [comment]
system_upgrade() calls java_install_or_update()
we should check to only (re)install java if the version has changed

**Comment by mstormi** [comment]
@EliasGabrielsson could you check this please?
With everybody moving to OH 2.5 I suspect this happens a lot, first one [here](https://community.openhab.org/t/openhabian-config-error-on-upgrade-system/81400/59)

**Comment by mstormi** [comment]
Another thread and people to complain
https://community.openhab.org/t/openhabian-config-error-on-upgrade-system/81400/61

@EliasGabrielsson please have a look it shouldn't be hard to fix but you wrote that code so waiting for you to jump in

**Comment by bwosborne2** [comment]
This happens for me too.

**Comment by erelor** [comment]
This happens for me too! :/

**Comment by nwootton** [comment]
Me too.

On a RPi 3 v2 this happens to me - openhabian-config says there are updates, does the 'correct' updates and then re-installs Java 1.8.0_222 again.

**Comment by mstormi** [comment]
It would be easier and more reliable to switch back to an apt-based install but that would mean to change the Java provider. See also #766.

**Comment by mstormi** [comment]
Mind #714 if going for an implementation based on Azul.

**Comment by mstormi** [comment]
As @ThomDietrich mentioned in #805, we'll stay with Azul (and thus its install methodology) for the time being and probably all the way up to OH3.
So we need a solution approach other than to switch to some repo/apt based Java package.

I believe we can remove the java_install_or_update() call from system_upgrade() as a quick fix
(then Option 03 "Upgrade" would not apply jo Java any more but I think that's acceptable for now).
