### ISSUE TITLE
WiFi config fails on RPiA3+

### ISSUE THREAD

**Issue by Ilnahro** [openhab/openhabian#725]
Setup:
Platform: RPi3A+
Storage: Kingston 64GB µSD
Build: openhabian-pi-raspbian-201908050414-gitca0976f-crc6a66b5a1
WiFi Accesspoint: AVM Fritz!Box 6490 (FW: 07.10)/Samsung Galaxy S7 (LOS 16)

The config fails to properly connect to WiFi and subsequently fails the connectivity check. The SSIDs are correctly correctly displayed afterwards and WiFi is working when manually connected. Tested several times, with multiple APs and varying SSID/PW configs.

Workaround: Boot without WiFi config in openhabian.conf, login with default raspbian user (user/pw: pi/raspberry), connect to WiFi using `sudo raspi-config` and then restart the first-boot script.

**Comment by aenertia** [comment]
Same on Pi 3B with 1.5 release image. Headless/wifi install is not working via the normal method of adding in credentials to openhabian.conf in the /boot partition. 

Also tried the adding ssh, and wpa_supplicant.conf into the boot as per usual raspbian image but this is ignored and deleted on boot.

**Comment by mstormi** [comment]
Assume it was the same issue as #767
