### ISSUE TITLE
Amanda configuration script broken

### ISSUE THREAD

**Issue by ndye** [openhab/openhabian#726]
The Amanda configuration script is broken in the latest update and it wasn't before. See [here](https://community.openhab.org/t/amanda-openhabian-only-empty-amanda-conf-file-after-setup-via-openhabian-config/82229) for example

**Comment by mstormi** [comment]
That's a pretty useless error report I cannot act upon. I could not reproduce that guy's error. Get me proper input.
Insert a line "set -x" as the first line in amanda_setup() in /opt/openhabian/functions/backup.sh, redo the install, record what you entered, and provide the entire log (record it in your terminal).

**Comment by mstormi** [comment]
Fixed in #722 
@EliasGabrielsson mind merging that one ?

**Comment by mstormi** [comment]
Fixed via #722, pls. close to confirm

**Comment by ndye** [comment]
Sorry I wasn't paying attention to the thread. Its been a busy few weeks, thanks it works.
