### ISSUE TITLE
Grafana build does not work on Raspberry Pi Zero

### ISSUE THREAD

**Issue by stuarts0011** [openhab/openhabian#727]
Please update the optional installation to download the grafana-rpi package for the Pi Zero not grafana

**Comment by mstormi** [comment]
I don`t think anyone would ever reasonably want to run Grafana on a Pi Zero with 512 MB only in parallel to openHAB which already uses that much memory all by itself (at least with standard openHABian parameters).
So this is a combo you can install at your own risk - you can do so at any time. 
But please don't expect us to maintain that officially. Doing so means we need HW and time to validate everything on a Zero, too, and that we don't have (and I doubt it would work for a majority of users).
