### ISSUE TITLE
OpenHABian manual install fails if zulu CDN not available 

### ISSUE THREAD

**Issue by MagicFab** [openhab/openhabian#734]
For some reason even though cdn.azul.com resolved and pings fine, downloading Zulu failed with:

```
...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for libc-bin (2.28-10) ...
https://cdn.azul.com/zulu-embedded/bin/zulu8.40.0.178-ca-jdk1.8.0_222-linux_aarch32hf.tar.gz: Invalid host name.

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
FAILED

```

This exited to the prompt, stopping a manual install.

**Comment by lgusewski** [comment]
Hmm, no response from the developers? Run today in the same problem. First tried Ubuntu Server 18.04.3 LTS minimal version and could not install zulu over the openhabian-config. Read something about to kill the ubuntu support and thought that debian could be better supported and this is a special Ubuntu problem. After running through the next minimal installation of debian 10.1, i got the same error like MagicFab.
All other packages could be loaded and installed. Made all with the root account to be shure not to have any right problems.
So the point 60/63 seems to be broken.

**Comment by lgusewski** [comment]
I do the same. Three times (twice ubuntu server and one debian) and every time the installation of the Zulu java package stops the process.

**Comment by EliasGabrielsson** [comment]
It's noticed that the endpoint have changed.
The solution to this is to rewrite the code to use their new API: https://www.azul.com/downloads/zulu-community/api/

Anyone mind helping out?

**Comment by danjhall** [comment]
needs a rework under java-jre.bash on line 136

**Comment by bazza1024** [comment]
Seeing exact issue as Chris669, looks like wget is trying to get from the local /tmp/openhabian.YuQER/zulu8.tar.gz, that's not a usage I'd used wget for before.

was just about to ask where i'd find that file, thanks danjhall

**Comment by danjhall** [comment]
wget is fine:

jdkTempLocation="$(mktemp -d /tmp/openhabian.XXXXX)"
wget -nv -O "$jdkTempLocation"/zulu8.tar.gz "$link"

It's just $link is false due to the filter now being incorrect due to the AZUL json format change @EliasGabrielsson mentioned.

Just needs a quick rework under java-jre.bash on line 136 (current master)

**Comment by danjhall** [comment]
At the moment I don't have time to correct this, given it's a very high priority bug (prevents all new installs) I would suggest that the main dev team get involved. @EliasGabrielsson can you contact anyone that might be able to make the change under java_jre.fetch_zulu_tar_url()?

**Comment by danpadure** [comment]
isn't there any workaround, like editing the install script to download a specific java file instead of filtering the latest version?

**Comment by MagicFab** [comment]
@danpadure did you read above ? See https://github.com/openhab/openhabian/issues/734#issuecomment-542253088

**Comment by udo1toni** [comment]
As a temporary workaround, I think you only have to install Zulu8 manually.

**Comment by EliasGabrielsson** [comment]
The current implementation uses a JSON object which Azul is providing for their download-page (https://www.azul.com/downloads/zulu-community/). This was made before the API was released and is a bit risky as they could change it more often, as happened now. 

I think the rewrite will be close to current implementation regard structure and such but with the API endpoints instead.

**Comment by danpadure** [comment]
I did install it manually, but I still get errors

2019-10-18_10:30:11_EEST [openHABian] Installing additional needed packages… OK
2019-10-18_10:30:14_EEST [openHABian] Adding slightly tuned bash config files to system… OK
2019-10-18_10:30:14_EEST [openHABian] Adding slightly tuned vim config file to system… OK
2019-10-18_10:30:14_EEST [openHABian] Downloading and setting up FireMotD… OK
openjdk version “1.8.0_222”
OpenJDK Runtime Environment (Zulu8.40.0.178-CA-linux_aarch32hf) (build 1.8.0_222-b178)
OpenJDK Client VM (Zulu8.40.0.178-CA-linux_aarch32hf) (build 25.222-b178, mixed mode, Evaluation)
openjdk version “1.8.0_222”
OpenJDK Runtime Environment (Zulu8.40.0.178-CA-linux_aarch32hf) (build 1.8.0_222-b178)
OpenJDK Client VM (Zulu8.40.0.178-CA-linux_aarch32hf) (build 25.222-b178, mixed mode, Evaluation)
2019-10-18_10:32:26_EEST [openHABian] Installing Java Zulu 32-Bit OpenJDK…
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
FAILED
2019-10-18_10:32:30_EEST [openHABian] Initial setup exiting with an error

**Comment by slh24** [comment]
A temporary workaround is described in the community forum:
https://community.openhab.org/t/initial-setup-failed-on-raspi3b-due-to-a-java-zulu-path-error/70699/7

**Comment by nattila1** [comment]
> A temporary workaround is described in the community forum:

Neither the temporary workaround solved the problem to me. After a successful setup with the workaround each time the raspberry is booting the the fist-boot procedure started again each time.

**Comment by MagicFab** [comment]
> > A temporary workaround is described in the community forum:
> 
> Neither the temporary workaround solved the problem to me. After a successful setup with the workaround each time the raspberry is booting the the fist-boot procedure started again each time.

My initial report and workaround are for the MANUAL installation of OpenHAB on Debian LXC container, not for automatic rPi installation. If you have an issue with install and initial setup from an SD card, please file a separate issue report.

**Comment by worm79** [comment]
Is this thread not correct for install issues with openhabian?
I have not been able to install a fresh instance of openhabian from sd card Img for over 2 weeks. Is there another thread where this should be logged?

**Comment by danjhall** [comment]
@mstormi Hi Markus, have you seen this issue? I see a recent commit in Master for other issues but it appears this has far higher priority, it stops all fresh installs.

The problem ( as noted by @EliasGabrielsson ) is that Azul have changed the zulu8 endpoint and return object. This results in the following error:

2019-10-18_10:32:26_EEST [openHABian] Installing Java Zulu 32-Bit OpenJDK…
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

A workaround is as follows:

1: Open /opt/openhabian/functions/java-jre.bash

replace $link (current line 87) with the full URL to the updated zulu8 from Azul:

     # Fetch and copy new JAVA runtime
      cond_redirect wget -nv -O "$jdkTempLocation"/zulu8.tar.gz **https://cdn.azul.com/zulu-embedded/bin/zulu8.40.0.178-ca-jdk1.8.0_222-linux_aarch32hf.tar.gz**
      tar -xpzf "$jdkTempLocation"/zulu8.tar.gz -C "${jdkTempLocation}"

2: open /boot/first-boot.bash

Comment out these 3 lines (current lines 148-150)

    # echo -n "$(timestamp) [openHABian] Cloning myself... "
    # [ -d /opt/openhabian/ ] && rm -rf /opt/openhabian/ # check if we have remnants of a previous installation attempt.
    # git clone -b master https://github.com/openhab/openhabian.git /opt/openhabian &>/dev/null

Reboot openhabian and it should successfully install.

**Comment by danjhall** [comment]
> 
> 
> Is this thread not correct for install issues with openhabian?
> I have not been able to install a fresh instance of openhabian from sd card Img for over 2 weeks. Is there another thread where this should be logged?

Well, this thread is for a specific issue in Setup, If you're receiving the error i explaned in my last message then you're in the right place. Please try out those steps and see how you get on.

**Comment by MagicFab** [comment]
>  Is there another thread where this should be logged?

I don't know. Please search and open a new one if relevant. 

Is this a common problem for all installs ? I have no idea. Please don't hijack this issue, which I opened and am able to test and follow up for MANUAL installs (not automatic from SD card).

**Comment by EliasGabrielsson** [comment]
I researched the API this weekend which sadly does not expose the "ARM" packages currently. I will patch with a static link.

**Comment by mstormi** [comment]
@EliasGabrielsson When you're on it, can you also add a check for installed java version and skip install when its version is lower than latest? That's how apt/dpkg do and it would fix #723.

**Comment by syahmimanaf** [comment]
> @mstormi Hi Markus, have you seen this issue? I see a recent commit in Master for other issues but it appears this has far higher priority, it stops all fresh installs.
> 
> The problem ( as noted by @EliasGabrielsson ) is that Azul have changed the zulu8 endpoint and return object. This results in the following error:
> 
> 2019-10-18_10:32:26_EEST [openHABian] Installing Java Zulu 32-Bit OpenJDK…
> gzip: stdin: unexpected end of file
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now
> 
> A workaround is as follows:
> 
> 1: Open /opt/openhabian/functions/java-jre.bash
> 
> replace "$link" (current line 87) with the full URL to the updated zulu8 from Azul:
> 
> ```
>  # Fetch and copy new JAVA runtime
>   cond_redirect wget -nv -O "$jdkTempLocation"/zulu8.tar.gz https://cdn.azul.com/zulu-embedded/bin/zulu8.40.0.178-ca-jdk1.8.0_222-linux_aarch32hf.tar.gz
>   tar -xpzf "$jdkTempLocation"/zulu8.tar.gz -C "${jdkTempLocation}"
> ```
> 
> 2: open /boot/first-boot.bash
> 
> Comment out these 3 lines (current lines 148-150)
> 
> ```
> # echo -n "$(timestamp) [openHABian] Cloning myself... "
> # [ -d /opt/openhabian/ ] && rm -rf /opt/openhabian/ # check if we have remnants of a previous installation attempt.
> # git clone -b master https://github.com/openhab/openhabian.git /opt/openhabian &>/dev/null
> ```
> 
> Reboot openhabian and it should successfully install.

i did this workaround on putty and it was successful, but i still cant open the OH configure page on web browser? why is that?

**Comment by danjhall** [comment]
It mostly just needs a little time to initialise. Wait 30 mins and then refresh the page.

**Comment by bodiroga** [comment]
Hi guys!

This is a real deal breaker, no new users will be able to start with a fresh new Raspberry Pi until this is solved :cry: 

The solution proposed by @danjhall on https://github.com/openhab/openhabian/issues/734#issuecomment-546875065 works, but it's not very user friendly. @EliasGabrielsson, how are you going to approach the solution to the problem? Will a PR with the static link to zulu8.40.0.178-ca-jdk1.8.0_222-linux_aarch32hf.tar.gz be approved? Although I'm not sure if it will work, as that solution is only valid for the Raspberry Pi and we support more platforms.

Looking forward to seeing this fixed as soon as possible, it is critical bug :heart:

Best regards,

Aitor

**Comment by syahmimanaf** [comment]
i have wait 30 minutes and nothing happen. and after 30 minutes, my modem restart itself automatically. is there possibilities that my modem have broken? because before the zulu problem happen, everything just works fine for me.

**Comment by kaikreuzer** [comment]
I just came across this issue myself as I tried to setup a new RasPi with openHABian and it failed...
So I absolutely agree that this is a very critical issue.

> I will patch with a static link.

@EliasGabrielsson When will you be able to do this? Hopefully asap! If it fixes it for all RasPi users, I think the criticality of the issue is greatly reduced.

Shall I get a contact at Azul to discuss why the new API does not contain ARM packages and how we should proceed from here?

**Comment by bodiroga** [comment]
> i have wait 30 minutes and nothing happen. and after 30 minutes, my modem restart itself automatically. is there possibilities that my modem have broken? because before the zulu problem happen, everything just works fine for me.

Hi @syahmimanaf! I don't think this issue is related in any way to your model problem, I suppose that it was a simple coincidence. 

@EliasGabrielsson I have submitted a PR that adds static java download links in the "java_zulu_8_tar" function, but I'm not sure if that was what you have in mind. Let me know :wink:

**Comment by mstormi** [comment]
> Shall I get a contact at Azul to discuss why the new API does not contain ARM packages and how we should proceed from here?

Yes please. We also tried to get in contact with them long ago but failed. Maybe you're more lucky?
I once did with my company account and got an instant response, but possibly they don't like to put efforts into non-paying customers....
Actually they used to provide a repo but they have stopped maintaining that. It still is the preferred install option.

**Comment by syahmimanaf** [comment]
> > i have wait 30 minutes and nothing happen. and after 30 minutes, my modem restart itself automatically. is there possibilities that my modem have broken? because before the zulu problem happen, everything just works fine for me.
> 
> Hi @syahmimanaf! I don't think this issue is related in any way to your model problem, I suppose that it was a simple coincidence.
> 
> @EliasGabrielsson I have submitted a PR that adds static java download links in the "java_zulu_8_tar" function, but I'm not sure if that was what you have in mind. Let me know 😉

ohh i see. so is there anyway for me to access the OH configure page? your help is so much appreciated sir. as im currently finishing my final year project on smart home project.

**Comment by EliasGabrielsson** [comment]
Great that you made contact to Azul @kaikreuzer. Optimal would be to access their ARM / embedded JRE through the API. The rewrite is not that huge and I will have time for it the upcoming weeks.
