### ISSUE TITLE
Debugging instructions

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#735]
Following up on a number of issues users brought up in response to 1.5 and comprehensive changes like the shellcheck stuff, I came to think that we should create a debug instructions README.
This (its Github link to always point to its current version) we can reference community users to so we don't have to individually help with explaining them how they would need to debug openHABian installs that fail.

Some unsorted, incomplete thoughts what should be contained, please add your own suggestions:
* prerequisites a user has to meet such as an (_totally?_) unfiltered Internet connect and a router to provide proper DNS and DHCP resolving (_is NTP mandatory, too?_)
* the location of the logfile(s) (_only first-boot.log ?_) to post
* a quick intro how to open a Github issue and - most noteworthy - what information to upload
* debugging options (`unattended`, `unattended_debug `and `debug_maximum`)
* the procedure to use in re-running an openhabian setup that failed with changed parameters
I'm not 100% sure of this myself. Can we change the `mode` parameter in `/etc/openhabian.conf`,
`rm -f /opt/openHABian-install-failed` and reboot ? If no please add the right instructions.

See also #408 and #683. In that latter I introduce another most-verbose debug level "debug_maximum" and the ability to define the debug level in openhabian.conf[.dist] which then is used by openhabian-set.sh and automated tests.
We might get to get around the need expressed in #408 to create a complementary log by only ever creating first-boot.log, have it remain to be the non-verbose default in the beginning but then instruct users when and how to switch to more verbose levels.

**Comment by mstormi** [comment]
Here's a draft
@EliasGabrielsson @ThomDietrich @holgerfriedrich 
any comments of yours ?


Prerequisites
-------------
First, please make sure you use proper host hardware that is supported as per README.
For one, openHABian requires a minimum of 1GB of RAM to run well. That's including commonly used tools such as frontail and mosquitto and an average-size
openHAB installation on top. So any SBC to have less memory such as a RPi Zero is not supported.
For two, on "supported" hardware in general:
It may work to install and run openHABian on these boxes or not. If it does not work on your box and it isn't any of the supported ones, you are welcome to find out what's
missing and come up with a Pull Request. We'll be happy to include that in openHABian so you can use the merged version on your box.
We'll keep that code in unless there's a valid reason to change or remove it. Remind you, though, that that still doesn't make your box a "supported" one as we don't have
it available for our further development and testing works.
So yes, there then still remains a risk that future openHABian releases will fail to work on your SBC because we changed a thing that broke support for your HW - 
unintentionally so but also inevitably so.
** DNS resolver, DHCP, NTP


Install
-------
Etch-Burn-Flash-whatever the image to an SD card and boot.
The console (if you have attached one) **also any remote login session??** will display the contents of /boot/first-log.boot at intervals of 2 seconds.

Login to your box using `ssh openhabian@`_hostname_. The default hostname (if you didn't change it at installation time) is `openhab`. The default passwort is `openhabian`. 
If that step already fails, it is likely because you have not provided proper DNS service as mentioned in the _prerequisites_ section.

Once logged in, enter "sudo bash" to become the root user.
If your install fails at some stage (or hangs forever), there will exist files either `/opt/openHABian-install-failed` or `/opt/openHABian-install-inprogress`
to reflect these states (to check, `ls -l /opt/openHABian-install*`).
As a first attempt, you should reboot your box to see if the same problems also occurs on its second attempt.

If that one fails, too, force another install run from scratch by removing the file using `rm -f /opt/openHABian-install*`, then reboot (`reboot`).

If that also fails, put openHABian into one of the two more verbose debug levels, edit the config file `nano /etc/openhabian.conf` and set the 'mode' parameter
to either `unattended` (which is the default), `unattended_debug` or `debug_maximum`, then reboot again.

If that still doesn't get you anywhere, I'm sorry we're out of ideas.
Please retrieve `/boot/first-log.boot` from the box and open a GitHub issue (see next paragraph) and upload the log.


How to open a Github issue
** what to upload: Copy /boot/first-boot.log over to your Desktop and upload it

Remember to let openhabian-config update itself on start


Workarounds
-----------
If you need to change anything to work around some not yet fixed bug, you can edit the code in and below `/opt/openhabian`.
Before, set the `debug_maximum` install mode in `openhabian.conf first to have openHABian show every single command it executes so you
get an idea which part of the code to look at.
The main program is in openhabian-setup.sh. If the initial unattended install fails again and again at the same step (say Java installation),
you may comment that step out.
Disclaimer:
For obvious reasons, this is not a supported procedure. We just want to give you a hint what you _could_ try doing if your install fails
and you're sitting there, desperately waiting for a fix.
G*oo*gle and learn yourself what you need to edit a file, learn to understand shell programming basics, you're on your own here.
Remember for the time it takes to get openHABian officially fixed, you must not let openhabian-config update itself on start as that would overwrite your changes.

**Comment by mstormi** [comment]
I've included a draft in PR#683,
see https://github.com/mstormi/openhabian/blob/buildsystem-init.bash/docs/openhabian-DEBUG.md
@EliasGabrielsson @ThomDietrich @holgerfriedrich any comments on that?

**Comment by holgerfriedrich** [comment]
@mstormi +1 for documenting the debug approaches! Sorry, I cannot spend much time at the moment... Just one point regarding NTP: I think as long as #594 is not resolved, announcing NTP servers via DHCP should not have any effect (as Raspbian does not enable this feature by default).

**Comment by mstormi** [comment]
@ThomDietrich @holgerfriedrich I think we should have a group chat to work on this document
