### ISSUE TITLE
Error in JS after running openhabian-config

### ISSUE THREAD

**Issue by gargamelonly** [openhab/openhabian#737]
Platform: RPI2
Build 2.5-M3
[master]v1.5-524(b0beb7f)

running normally except an error that keeps repeating itself every time after openhabian-config completes updating the system:

```
$ systemctl stop openhab2.service
error: first is not defined
[.[] | select(.category_slug == "java-8-lts") | select(.latest == 1)  | .["openjdk_version"]] | first                                                                                                1 compile error
openjdk version "1.8.0_152"
OpenJDK Runtime Environment (Zulu Embedded 8.25.0.76-linux-aarch32hf) (build 1.8.0_152-b76)
OpenJDK Client VM (Zulu Embedded 8.25.0.76-linux-aarch32hf) (build 25.152-b76, mixed mode, Evaluation)

$ systemctl start openhab2.service
OK
```

**Comment by mstormi** [comment]
Does it still happen in latest openHABian?
If no please close.

**Comment by bsailer2510** [comment]
I have the same issue since yesterday. Just upgraded and rebootet the system but no change. Openhab is running and works, i can access the Node-RED interface but when i try to open the OH interface i get a redirection to Port 8443/setup. Nothing in the logs.

**Comment by modestos** [comment]
I also realized that I have this issue since last time I updated. Nothing special on the logs.
