### ISSUE TITLE
openHABian Configuration Tool giving impossible advice regarding homegear-binding 

### ISSUE THREAD

**Issue by rori1977** [openhab/openhabian#746]
On a fresh install from SD and after installing “homegear” via the OpenHABian Configuration Tool, I receive an error when entering the recommended  "homergear -r" command as adviced by the the config tool:

openhabian@openhab:~$ homegear -r
10/20/19 13:12:53.484 Could not connect to socket. Error: Permission denied
10/20/19 13:12:53.485 Could not connect to socket. Error: Permission denied
10/20/19 13:12:55.483 Could not connect to socket. Error: No such file or directory
10/20/19 13:12:55.483 Could not connect to socket. Error: No such file or directory

Digging a bit deeper …

openhabian@openhab:~$ sudo systemctl status homegear.service
● homegear.service - Homegear
Loaded: loaded (/lib/systemd/system/homegear.service; enabled; vendor preset: enabled)
Active: active (running) since Sun 2019-10-20 13:11:49 CEST; 32min ago
Process: 4208 ExecStartPre=/etc/homegear/homegear-start.sh (code=exited, status=0/SUCCESS)
Main PID: 4210 (homegear)
Tasks: 82
Memory: 35.9M
CGroup: /system.slice/homegear.service
└─4210 /usr/bin/homegear -u homegear -g homegear -p /var/run/homegear/homegear.pid

Oct 20 13:11:49 openhab systemd[1]: Starting Homegear…
Oct 20 13:11:49 openhab systemd[1]: Started Homegear.
Oct 20 13:11:49 openhab homegear[4210]: 10/20/19 13:11:49.774 Loading RPC server settings from /etc/homegear/rpcservers.conf
Oct 20 13:11:49 openhab homegear[4210]: 10/20/19 13:11:49.780 Loading RPC client settings from /etc/homegear/rpcclients.conf
Oct 20 13:11:49 openhab homegear[4210]: 10/20/19 13:11:49.847 Info: Setting allowed core file size to “4294967295” for user with id 0 and group with id 0.
Oct 20 13:11:49 openhab homegear[4210]: 10/20/19 13:11:49.847 Info: Core file size now is “4294967295”.
Oct 20 13:11:49 openhab homegear[4210]: 10/20/19 13:11:49.847 Info: Setting maximum thread priority to “4294967295” for user with id 0 and group with id 0.
Oct 20 13:11:49 openhab homegear[4210]: 10/20/19 13:11:49.848 Info: Maximum thread priority now is “4294967295”.

… we can see that the service seems to run fine, however the recommended command will still fail.

As per the assumption with @mstormi this might be, because the system expects to run the command
as  openhab:openhab  (whereas openhabian:openhab is currently active).

Below some  standard information.

Platform information:
Release -> Raspbian GNU/Linux 10 (buster)
Kernel -> Linux 4.19.75-v7+
Platform -> Raspberry Pi 2 Model B Rev 1.1
openHABian Configuration Tool [master]v1.5-526(0986fff) 
Java Runtime Environment:
openjdk version “1.8.0_222”
OpenJDK Runtime Environment (Zulu8.40.0.178-CA-linux_aarch32hf) (build 1.8.0_222-b178)
OpenJDK Client VM (Zulu8.40.0.178-CA-linux_aarch32hf) (build 25.222-b178, mixed mode, Evaluation)

**Comment by mstormi** [comment]
You forgot how UNIX works. If you add the openhabian user to the homegear group, this only applies to **future** sessions.
Log out, log back in and close this issue, please.

[17:22:56] openhabian@devpi:~/openhabian$ homegear -r
10/20/19 17:23:04.068 Could not connect to socket. Error: Permission denied
10/20/19 17:23:04.069 Could not connect to socket. Error: Permission denied
10/20/19 17:23:06.067 Could not connect to socket. Error: No such file or directory
10/20/19 17:23:06.067 Could not connect to socket. Error: No such file or directory
[17:23:06] openhabian@devpi:~/openhabian$ sudo -u openhabian homegear -r
Connected to Homegear (version 0.7.40-2948).

Please type >>help<< to list all available commands.
> ^C
[17:23:38] openhabian@devpi:~/openhabian$ groups
openhabian adm tty dialout cdrom sudo audio backup video plugdev games users input netdev bluetooth openhab docker gpio i2c spi
[17:23:54] openhabian@devpi:~/openhabian$ sudo -u openhabian groups
openhabian adm tty dialout cdrom sudo audio backup video plugdev games users input netdev bluetooth openhab homegear docker gpio i2c spi
[17:24:05] openhabian@devpi:~/openhabian$

**Comment by rori1977** [comment]
Not forgotten, but just learning. :-)

Logging off and logging in again indeed helped.
Thanks for that hint.

Could be a good idea to add this text  - as a hint for other newbies like me - after the installation of homegear has succeeded.

Something like:
```
You homegear installation has succeded.
Please run "homegear -r" to configure it.
Due to changes made to group memberships you are recommended to re-establish your SSH connection.  
```

Again thanks for the helpful hint.
