### ISSUE TITLE
After successful installation of influxDB via OpenHABian Config Tool, PAPERUI still shows it as "not installed"

### ISSUE THREAD

**Issue by rori1977** [openhab/openhabian#747]
Hi, as an OpenHabian noob, I was confused by the below:

**Expected behaviour:** 
1.) Fresh setup of openHAB 2.5.0.M4 Milestone Build
2.) install InfluxDB+Grafana via the openHABian Configuration Tool
3.) Once finalized, navigate to PAPERUI / Add-ons / Persistence
4.) The user should see that the influxdb.binding "persistence-influxdb - 1.14.0.M4" is in status = "Installed"

**Observed behavior:** 
Using openHABian Configuration Tool [master]v1.5-526(0986fff) the install succeeds and influxdb and grafana services are started. However, in PAPERUI the persistence-addon is still "not installed" and the button allows installing it (once more?)

![PaperUI  2019-10-20 17-28-00](https://user-images.githubusercontent.com/56794204/67161887-1b7b0300-f35f-11e9-9baf-4fcf58e3dfc3.png)

**Comment by mstormi** [comment]
>  1.) Fresh setup of 1.14.0.M4

of what ???

**Comment by rori1977** [comment]
Sorry I confused the persistence version 1.14.0.M4 with the OpenHabian version (Latest Milestone version).

**Comment by mstormi** [comment]
> 4.) The user should see that the influxdb.binding "persistence-influxdb - 1.14.0.M4" is in status = "Installed"

No.
In order to see that you need to configure _openHAB_.
What you did was to install Influx DB, but you obviously didn't do that yet, and it is none of openHAB_ian_'s business to configure openHAB, so please close this issue as well.
_Wir freuen uns über jede Mithilfe. Das jetzt aber bitte nicht zur Gewohnheit werden lassen, openHAB auf diesem Wege lernen zu wollen._

**Comment by rori1977** [comment]
Maybe this screenshot explains it better ?

![persistence not installed but service running](https://user-images.githubusercontent.com/56794204/67162032-a4466e80-f360-11e9-9716-a450b2068e60.png)

**Comment by mstormi** [comment]
> Maybe this screenshot explains it better ?

I understood that. But you should read responses before posting ...

**Comment by rori1977** [comment]
I assume I have to read and learn more about OpenHAB to understand your repiy. 

_Nicht für ungut_ :-)
