### ISSUE TITLE
Fonts error, not able to see any chart

### ISSUE THREAD

**Issue by nesys** [openhab/openhabian#748]
Hi folks,

 openhabian 2.5.0~S1731-1 (Build #1731) here.

Starting from an upgrade from #1657 to #1712 I'm experiencing the same issue as this case:

https://github.com/openhab/openhab-docker/issues/73

It seems this is not related to docker, as here I have openhabian in a virtual machine (VMware).

Here my logs: https://justpaste.it/4wa9y

In facts, I'm not able to see any chart any more. I've tried to install manually fontconfig, but this didn't do the trick unfortunately :(

Any suggestion will be appreciated

Andrea

**Comment by NurNano** [comment]
Same issue at my side. I have a virtual Machine with the newest Debian Image and every time i install Openhabian over the git package I run into the "No fonts found." error.

**Comment by nesys** [comment]
my fault ... the solution was already in:

https://github.com/openhab/openhab-distro/issues/421

for my installation, sudo apt-get install fontconfig:i386 did the trick

Andrea

**Comment by NurNano** [comment]
Now i feel dump! 
apt-get install fontconfig:i386 did the trick for me too.
Thx a lot!

**Comment by ToddLorey** [comment]
I had the same issue on a new Proxmox container Ubuntu install (openhab v2.5.3).  The sudo apt-get install fontconfig:i386 worked for me too.  Gotta love google!  :)
