### ISSUE TITLE
hostname not changeable in openhabian-config

### ISSUE THREAD

**Issue by guruwoolfi** [openhab/openhabian#749]
openHABian Configuration Tool [master]v1.5-526(0986fff)

Dialogbox popping up:

There was an error or interruption during the execution
of:
"30 | System Settings"

**Comment by guruwoolfi** [comment]
Additional Info:
Setting hostname of the base system... /opt/openhabian/functions/system.bash: line 103: 3: Bad file descriptor

**Comment by rrobinet** [comment]
Changing hostname manually in /etc/hosts and in /etc/hostname gives as result:

sudo: unable to resolve host <hostname>: Name or service not known

**Comment by rrobinet** [comment]
This fix 750  is worst than the previous one, which at least allows to change the hostname correctly

**Comment by ThomDietrich** [comment]
@rrobinet could you elaborate?

**Comment by rrobinet** [comment]
Problem is corrected 12 minutes ago.
Thanks
