### ISSUE TITLE
Change keyboard layout in raspi-config is not working

### ISSUE THREAD

**Issue by leiweke** [openhab/openhabian#75]
I sudo raspi-config and change option I3 Change Keyboard Layout to German gives no error, but if you end raspy-config it will still be english, no Y=Z Z=Y ....

newest download and build from today 13.01.

**Comment by ThomDietrich** [comment]
[Use SSH.](https://community.openhab.org/t/openhabian-hassle-free-rpi-image-login-failed/18816/4?u=thomdietrich)

If you really want to use a keyboard, try the first two commands here or edit the config file directly: https://wiki.debian.org/Keyboard

**Comment by leiweke** [comment]
Thanks but i did that no luck. i also checked /etc/default/keyboard the settings are there but y is still z

**Comment by ThomDietrich** [comment]
Did you reboot?
You may also need to change your locale. https://wiki.debian.org/ChangeLanguage

**Comment by leiweke** [comment]
yes i did a reboot
and also followed the instructions. no luck.

on "normal" Jeesie image it i only change the keyboard without changing the local.

**Comment by ThomDietrich** [comment]
I read here: https://github.com/debian-pi/raspbian-ua-netinst/issues/226
that you need to `sudo apt install console-data console-setup keyboard-configuration`

**Comment by leiweke** [comment]
okay that was the final solution. thanks a lot

**Comment by ThomDietrich** [comment]
So the solution is these packages plus setting the layout via raspi-config?

**Comment by leiweke** [comment]
Yes

**Comment by michaelguild13** [comment]
I had to manually edit `sudo nano /etc/default/keyboard`
and change `gb` to `us`
