### ISSUE TITLE
Initial setup failed due to a Java - Zulu path error

### ISSUE THREAD

**Issue by rrobinet** [openhab/openhabian#751]
Please deal with issue a specified by
https://community.openhab.org/t/initial-setup-failed-on-raspi3b-due-to-a-java-zulu-path-error/70699

**Comment by mstormi** [comment]
Be more specific, that thread has 38 posts.

**Comment by rrobinet** [comment]
I just want to be sure that this problem is covered as an issue, which makes the installation of openhabian impossible and is easy to solve

**Comment by mstormi** [comment]
Then do. It won't be covered if you don't go the mile and collect and bring all required information.

**Comment by rrobinet** [comment]
Sorry about that !
