### ISSUE TITLE
don't put backups into zram

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#763]
On ZRAM activation, set ${OPENHAB_BACKUPS} in /etc/defaults/openhab2 to something other than the default so backups don't consume valuable zram space
Inform users about changed backup location (any good idea where to place them instead?)

**Comment by ethyr2000** [comment]
Is this a backup or an archive?  If it is a backup of settings, then the ideal would be to have it write to the base image that loads into zram.

**Comment by mstormi** [comment]
I don't understand your point. It's a archive.
And it's what's live on disk, so whenever you shutdown zram, it's synced to disk and loaded on next start. It's no "image" BTW but an OverlayFS.

**Comment by shutterfreak** [comment]
@mstormi How about a folder in /var/local/openhab or /opt/openhab ?

**Comment by mstormi** [comment]
@BClark09 would you mind changing the default backup location to /var/local/openhab-backup as
suggested ?
I would rather not like to start using different locations depending on whether ZRAM is on or off.

**Comment by BClark09** [comment]
`/var/lib/openhab/backup` was chosen because openHAB and the script that creates the backup it is installed through a package.

> I would rather not like to start using different locations depending on whether ZRAM is on or off.

But using a different location depending on if ZRAM is _installed_ should be simple, no?

**Comment by mstormi** [comment]
> But using a different location depending on if ZRAM is _installed_ should be simple, no?

Sure (that's what I, too, meant by "on"/"off" btw).
But I dislike the idea of having different locations for ZRAM users than others, will lead to confusion. Hence my proposal to move. ...?

**Comment by mstormi** [comment]
>  We could turn `/var/lib/openhab2/backup` into a link to the new location, wdyt?

@BClark09 ?

**Comment by BClark09** [comment]
I'm not sure about how I feel about changing the default location for all apt/yum users to solve an issue with ZRAM for openHABian users. Won't that have the same issue as giving different locations for different users depending on what version they're using, but with even more people?

I'm not completely against changing it, but if we do then it'd probably have to come with an announcement.

**Comment by mstormi** [comment]
I'd suggest to, on openhab2 package install, turn the old location /var/lib/openhab2/backup into a link to the new location so noone has to change (people can keep using the location they're used to) and everybody new to install oh will get the new location.
Sure you can have an announcement come along with that change, too.

**Comment by holgerfriedrich** [comment]
..,.or the other way around: leave it as it is for package install, existing and new installations.
Make zram installer to move the directory, put a symlink. There we can announce what we just did during the install.
For me not clear how to ensure that the symlink still exists and how to upgrade existing installations.

This approach would probably break less installations (you know, people implement a lot of stuff on top, e.g. rsync to different machines, which could possibly break when a symlink comes into play).

**Comment by mstormi** [comment]
Just like Benjy, I don't like to have dependencies of packages on each other, even less so between code in openhabian (zram installer) and code in preinst scripts. No I don't think that's a good idea.

**Comment by mstormi** [comment]
> I'm not completely against changing it (we picked the location only because it was the best fit), but if we do then it'd probably have to come with an announcement.

Agree. So how to proceed, change ? Would you do it or would you expect me to write a PR on your package ?
