### ISSUE TITLE
Change Java provider from Azul

### ISSUE THREAD

**Issue by ecdye** [openhab/openhabian#766]
Why not change our Java provider from Azul to something like AdoptOpenJDK? This is more of a brainstorming post than a true issue mainly stemming from the fact that whit the change of Azul's API they no longer appear to incorporate Linux in the mix of available Java builds in their API.

**Comment by ndye** [comment]
A great resource on the general background of this topic is here: https://medium.com/@javachampions/java-is-still-free-2-0-0-6b9aa8d6d244

**Comment by EliasGabrielsson** [comment]
Historically Azuls provided java version have shown great performance with openHAB2 and that is the main reasons we pursuit to install it with cumbersome scripts.

If `AdoptOpenJDK` could be a good replacement I would not hesitate to do so. From an openhabian standpoint that would be much more convenient as we can just use the `apt-get` routine.

Whats need to be done is some sort of extensive testing of AdoptOpenJDK. One way of simplify that testing could be an install in openhabian. You are very welcome to contribute.

**Comment by mstormi** [comment]
Will not change straight away but Adopt remains to be a favorite to succeed Azul.
We discuss the Java path forward in https://github.com/orgs/openhab/teams/refocus-ian/discussions/6
