### ISSUE TITLE
Wifi Password with special Characters needs to be escaped in openhabian.con

### ISSUE THREAD

**Issue by BobSilent** [openhab/openhabian#767]
When following instructions
https://www.openhab.org/docs/installation/openhabian.html#wi-fi-based-setup-notes

I need to take care that password with special characters needs to be escaped in `wifi_psk`, e.g. `$` in password needs to be written as `\$`

Maybe this needs to be considered or a hint in the installation description would have saved me a half day

**Comment by mstormi** [comment]
still valid ?

**Comment by BobSilent** [comment]
Did anything change with respect to reading the config file?

As it seems to be a default Java or Linux config reading mechanism special characters needs to be escaped.
This took me quite a long time to understand, maybe for Linux or Java insiders this is totally clear and obvious.

**Comment by mstormi** [comment]
I understand what you said.
But I want/need to know whether this is still happening in current openHABian.

**Comment by holgerfriedrich** [comment]
Seems easy to put a note in the config as a comment, since new users might not be aware of special characters.
Though, needs a description which characters are affected and some testing. I cannot spend the time for right now.
