### ISSUE TITLE
Configure openhabian SSH to use “screen”

### ISSUE THREAD

**Issue by shutterfreak** [openhab/openhabian#768]
Not sure if this is an enhancement or a bug.

Assuming openhabian buster and OH 2.5 M5 but also applies to other versions.

Consider changing `openhabian` to install `screen` by default, or to at least update the `openhabian-config` script to avoid undoing any `screen`-related setup.

Discussion:
https://community.openhab.org/t/configure-openhabian-ssh-to-use-screen/86027

**Comment by mstormi** [comment]
Frankly, it's the first time to head of dying sessions. A timeout is normal behavior, and unstable networking would be a user's domain to fix. I wouldn't think we should encourage users to start using screen. Anyone in need is free to install for himself.

**Comment by ThomDietrich** [comment]
Screen is installed by default: https://github.com/openhab/openhabian/blob/master/functions/system.bash#L28

Starting screen by default is a totally different story. This is not a general improvement but rather a personal choice. I would use screen for certain purposes but never all the time - of course others may choose to do so. I totally agree with Markus.

Regarding "undoing": The mentioned menu entry to write Bash and Vim settings is not something you should run regularly. However, if you do it will overwrite everything with our tested settings. If you decided to make custom changes to these files you need to reapply. Would you like to add a warning to the menu entry intro text?

**Comment by andrewbrake** [comment]
1) Sessions get closed for a variety of reasons, timeout, accidental closing,  machines going to sleep, the list is long. Several times, I have had to reboot and restart something because a session has  been ended.
2) The RaspberryPi is a slow, and not everyone has 100Mb internet. This means some operations can take a very long time. 
3)  I am not a linux expert, and dealing with the command line as not something I enjoy, it is frustrating. I do the best I can by googling and interpreting. I imagine a good proportion of the user base is similar.
4) It took me 2 years to discover that screen was even a thing, and I found out accidently while looking for a solution.

I would love to hear reasons why using screen by default is undesirable. So far I have only seen benefits.

**Comment by mstormi** [comment]
Thomas pretty much said it all: "his is not a general improvement but rather a personal choice"
Changing defaults is a very sensitive thing to easily annoy longtime users. One must not do this unless there's an overwhelming majority to vote for it.
So no we won't make it the default. It's installed and you and anyone else is free to use it.

**Comment by ThomDietrich** [comment]
Primarily "hidden complexity".
Screen is not something lightweight and can have many undesired side effects. E.g. it does change the function of some keyboard shortcuts and can influence how certain characters are presented in your terminal emulator (like putty). One easy example is that screen in standard configuration disables your ability to scroll up in your emulator. A very important function for many.
I would very much encourage you and others to use screen for important tasks like a big upgrade or a complete backup or similar. However... honestly I never do. A typical user session doesn't last long and even if you perform an `apt upgrade` after a few months, the execution will take only a few minutes. This does not much depend on the performance of the RPi or your internet bandwidth. In my experience screen is never really needed.

In the end I think your concern lies somewhere else. As Markus said: "A timeout is normal behavior, and unstable networking would be a user's domain to fix." - If you are dealing with regular disconnects you would do good to solve this. If you can't - use tools which help with this special issue, like screen :)

Btw just so you are aware, regarding your point 4: If you want to dive deeper into the topic, read up on newer tools in the screen universe. like tmux and byobu. Cool stuff

Once again regarding making screen (or tmux or byobu OR zsh for that matter) a default is not a good idea for the given reasons. I'll close the issue. If you can see any other way to help users like you, please let us know. One option would for example be to add a link to the mentioning of "screen" here to make discovery easier for users: https://www.openhab.org/docs/installation/openhabian.html#features
