### ISSUE TITLE
Fix change passwords menu

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#769]
Authentication is broken (menu optics, too) if there's multiple nginx users in .htpasswd:
```+ '[' -f /etc/nginx/.htpasswd ']'
++ cut -d: -f1 /etc/nginx/.htpasswd
+ nginxuser='openhab
markus'
```

**Comment by EliasGabrielsson** [comment]
The password change script for nginix does only support one user for now as I remember. 
I do however not understand from the output how it is broken.

**Comment by mstormi** [comment]
.htpasswd has multiple lines, thus 'cut ..... .htpasswd' output is multiple lines, too (lines 2+3 in output above)
