### ISSUE TITLE
Nginx satisfy any for local subnet

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhabian#77]
Add what was introduced here https://github.com/openhab/openhab-docs/pull/214 as an option

**Comment by mstormi** [comment]
still needed ?

**Comment by ThomDietrich** [comment]
If I remember correctly this change offers the option to not ask for the password locally.

I'd like to see this as commented lines for users to discover and activate manually... not sure if really needed.

@BClark09 @mues-lee I'll mention you once again. Of course anyone may help out here. If you don't feel it's worth it we can close the issue.

**Comment by mstormi** [comment]
Sorry I think I didn't get it right when browsing quickly for housekeeping purposes.
Re-reading, I now understood that the option is part of the docs but not of openhabians nginx config generation yet?
Then I think it should be in even the default setting in openhabian nginx config generation as that's how "security" works today in non-nginx setups:
open for LAN clients and (hopefully, left to the user) protected from WAN clients by internet router/firewall.
We should not query for a HTTP password when there's still LAN security to apply, i.e. devices either are cable-bound or need to know the WiFi password. 
I'd suggest to make this the default but to leave a comment in the sources so any paranoid can still re-enable HTTP password on top.

**Comment by mstormi** [comment]
Haven't encountered anyone to ask for this on the forum, and on second thought, anyone on the inside can directly OH instead of through proxy.
As you also suggested this I'll close the issue. Reopen if you feel we're in need to get that added.
