### ISSUE TITLE
Add JSR223 packages

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#771]
I recently started looking into Jython as a replacement to rules DSL. This is likely to become a future default. For now, anyone willing to go for it (or JS or Groovy) would need to install some stuff for himself. We should help users by including that with openHABian early.

See https://openhab-scripters.github.io/openhab-helper-libraries/Getting%20Started/Installation.html

**Comment by ThomDietrich** [comment]
Totally agree. From your experience, would it be a good idea to apply all needed preparations by default?

**Comment by mstormi** [comment]
I think to apply what's shown in the link I shared is useful and shouldn't hurt anyhing so yes. Can only comment on Jython though haven't tried the others.

**Comment by mstormi** [comment]
See https://community.openhab.org/t/beta-testers-wanted-jython-addon-w-helper-libraries/86633

**Comment by shutterfreak** [comment]
I moved all but one rule to Jython. I liked the simplicity of the Rules DSL but it was cumbersome to debug. Jython is more straightforward if you're a programmer.

**Comment by mstormi** [comment]
Well now that we've fought through for years .... *sigh*

Just read about big changes to come on. Scripting incl. Python will be integrated into OH.
So I think for this issue for the time being it does not make much sense to proceed with
(well unless that integration takes as long as moving off ESH ...)

**Comment by mstormi** [comment]
This is in beta but works fine. So it won't make sense to build an alternative approach into openHABian.
https://community.openhab.org/t/beta-testers-wanted-jython-addon-w-helper-libraries-requires-oh-2-5/86633/75
