### ISSUE TITLE
systemd logs - /run/log vs /var/log (zram)

### ISSUE THREAD

**Issue by shutterfreak** [openhab/openhabian#772]
On openHABian 1.5 (Buster), the systemd logs are stored in /run/log and are eating swap space.

Wouldn't it make more sense to relocate them to /var/log so zram could also compress these if needed?

**Comment by mstormi** [comment]
I don't think so. 'Relocating' is not an easy task as to do it properly, we would need to rework all packages to log there - including future versions. A lot of work and a lot of risk to break things.
And there's nothing wrong with eating swap - swap is on zram, too.
So thanks for sharing your idea but thanks no we better don't change it.

**Comment by shutterfreak** [comment]
According to the man page for `systemd-journald.service`:

*On systems where `/var/log/journal/` does not exist yet but where persistent logging is desired (and the default `journald.conf` is used), it is sufficient to create the directory, and ensure it has the correct access modes and ownership:*
```
mkdir -p /var/log/journal
systemd-tmpfiles --create --prefix /var/log/journal
```

So it's apparently a trivial thing to change.

**Comment by mstormi** [comment]
Yes apparently so. While that isn't quite what you wanted to be done in your original request, it's an improvement. Can you come up with a PR ?

**Comment by shutterfreak** [comment]
Hi Markus,

I wouldn't know where to start for a PR.

I'd however add one additional statement to keep only the logs from the past 30 days:

```
sudo journalctl --vacuum-time=30d
```

**Comment by mstormi** [comment]
Find a proper location when to apply code changes (probably in any of the system tweaks routine) and create a diff. Mind the [CONTRIBUTING](https://github.com/openhab/openhabian/blob/master/CONTRIBUTING.md) guidelines.
Post it here or If you're familiar with git, clone the openhabian repo, change your local copy and push it, git will answer with a URL you just need to follow to turn your diff into a PR.

**Comment by shutterfreak** [comment]
Here's an attempt at writing a patch file:

```
$ git diff master functions/system.bash 
diff --git a/functions/system.bash b/functions/system.bash
index 80c9bbd..eb4aaa2 100644
--- a/functions/system.bash
+++ b/functions/system.bash
@@ -207,6 +207,12 @@ misc_system_settings() {
   touch /home/"$username"/.ssh/authorized_keys
   chmod 600 /home/"$username"/.ssh/authorized_keys
   chown -R "$username:$username" /home/"$username"/.ssh
+  # By default, systemd logs are kept in volatile memory. Relocate to persistent memory to allow log rotation and archiving
+  echo "Creating persistent systemd journal folder location: /var/log/journal"
+  mkdir -p /var/log/journal
+  systemd-tmpfiles --create --prefix /var/log/journal
+  echo "Keeping at most 30 days of systemd journal entries"
+  journalctl --vacuum-time=30d
   # A distinguishable apt User-Agent
   echo "Acquire { http::User-Agent \"Debian APT-HTTP/1.3 openHABian\"; };" > /etc/apt/apt.conf.d/02useragent
   #
```
Do you want me to push this patch?

**Comment by shutterfreak** [comment]
Looks like I've clicked once too much :(

**Comment by mstormi** [comment]
No worries, just reopen.
More unfortunately, you merged into your own master, not openhabian's. Give it another try: push the repo again and on the Github page to create the PR, select openhabian/master as the repo to diff against.

**Comment by EliasGabrielsson** [comment]
@shutterfreak Thanks for contributing to the project.
This will hopefully gives us better debug capabilities in the future 👍

**Comment by shutterfreak** [comment]
You're welcome. Sorry for the unintentional Git mess, though.
