### ISSUE TITLE
RPI4 install "Cloning myself ... FAILED"

### ISSUE THREAD

**Issue by Chanete** [openhab/openhabian#776]
Hi, I'm unable to install a brand new RPI4 with the latest openhabian image (openhabian-pi-raspbian-201908050414-gitca0976f-crc6a66b5a1.img) it ends up with "Cloning myself ... FAILED"

I've googled around and found some old error suposedly resolved, seems somthing related with https access to git repository but I've been wise enough to solve it. 

any idea from where to start debugging?? 

Thx.

**Comment by mstormi** [comment]
Here's the (as of yet incomplete and thus unpublished) debug guide:
https://github.com/mstormi/openhabian/blob/buildsystem-init.bash/docs/openhabian-DEBUG.md.
Login and check _/boot/first-log.boot_. The step to fail is openhabian to clone itself from the openhabian github repo. Assuming your Inet access is unrestricted, possibly it's just a temporary state of inaccessibility. Just reboot to try again.

**Comment by mstormi** [comment]
Please reopen and supply details if still in need.
