### ISSUE TITLE
Uninstall ZRAM is causing "a not supported option was selected"

### ISSUE THREAD

**Issue by vidia** [openhab/openhabian#777]
I am trying to remove ZRAM (I am going to switch to moving the root to USB) and am running into an issue when selecting the option. 

I am on version [master]v1.5-539(8a3c4d5) of the config tool. 

I have tried re-running the setup for ZRAM to make sure it is installed correctly then attempting to uninstall again, but that did not help. 

I am not too familiar with the codebase, or bash code, but looking at the menu code, it looks like this may be related to the changes made in 26cc338 that changed the name of some of the menu options, specifically the change in functions/menu.bash line 115 causing the check on line 127 to fail.

**Comment by stefanheijnen** [comment]
Same here:

![Screenshot_20191213-184505_JuiceSSH](https://user-images.githubusercontent.com/1306331/70820397-de6c4380-1dd8-11ea-8ef3-d9a730c2bf58.png)
