### ISSUE TITLE
Password change function (karaf console) does not work

### ISSUE THREAD

**Issue by Harpo3** [openhab/openhabian#781]
Applies to openhabian-config, 30 System Settings, 34 Change Passwords, openHAB Console. 

The _Change Password_ function does not correctly change the console password.

Until it is fixed, a workaround is to use [this instruction](https://www.openhab.org/docs/administration/console.html#bind-console-to-all-interfaces) to reset the password from the command line:
`sudo sed -i -e "s/openhab = .*,/openhab = securePassword,/g" /var/lib/openhab2/etc/users.properties`
Substitute securePassword with your desired password.
Then, stop openhab and reboot.

**Comment by mstormi** [comment]
Do you mean to change the _password to Karaf console_ ?
That can't be done from openhabian-config. Option 34 is about the openhab UNIX user and UNIX console in fact.
I admit it's an unfortunate wording, but it's something else works as designed.

PS: no need to reboot in your "workaround"
