### ISSUE TITLE
Samba not starting on reboot

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#784]
Not sure if there's anything specific about my setup, at least I don't think so.
This is the 2nd time this happened to me that Samba shares are unavailable after the openHABian box booted. A simple `systemctl start smbd` restores the service.
Anyone else seeing that ? If so please comment.

[14:58:37] root@openhabianpi:/home/openhabian# systemctl status smbd
● smbd.service - Samba SMB Daemon
   Loaded: loaded (/lib/systemd/system/smbd.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2020-01-04 02:01:34 CET; 12h ago
     Docs: man:smbd(8)
           man:samba(7)
           man:smb.conf(5)
 Main PID: 559 (code=exited, status=1/FAILURE)
   Status: "daemon failed to start: Samba failed to init printing subsystem"

Jan 04 02:01:32 openhabianpi systemd[1]: Starting Samba SMB Daemon...
Jan 04 02:01:33 openhabianpi systemd[1]: Started Samba SMB Daemon.
Jan 04 02:01:34 openhabianpi systemd[1]: smbd.service: Main process exited, code=exited, status=1/FAILURE
Jan 04 02:01:34 openhabianpi systemd[1]: smbd.service: Failed with result 'exit-code'.
Jan 04 02:14:58 openhabianpi systemd[1]: /lib/systemd/system/smbd.service:9: PIDFile= references path below legacy directory /var/run/, updating /var/run/samba/smbd.pid → /r
Jan 04 02:15:00 openhabianpi systemd[1]: /lib/systemd/system/smbd.service:9: PIDFile= references path below legacy directory /var/run/, updating /var/run/samba/smbd.pid → /r

**Comment by mstormi** [comment]
Just guessing but maybe it makes a difference if Samba is started before or after ZRAM as it exports some of the ZRAM directories...

**Comment by holgerfriedrich** [comment]
Hi @mstormi, Samba always started automatically on my new OH 2.5 install... I had to disable it manually since I do not use it. No ZRAM in use here...

**Comment by JueBag** [comment]
Had to restart today (power interruption), samba continued to work for as well. I do not use ZRAM!

**Comment by mstormi** [comment]
Thanks for your input. My most recents boot runs were fine (including ZRAM of course). Let's wait and see if there's others to have this problem.

**Comment by mstormi** [comment]
@holgerfriedrich @JueBag anyone willing to check PR #807 ?
You would need to enable ZRAM for testing.

**Comment by mstormi** [comment]
not reproducible in weeks so closing
Anyone to still encounter this please reopen
