### ISSUE TITLE
in the opengah config cannot configure wifi settings

### ISSUE THREAD

**Issue by MaartenGoris** [openhab/openhabian#788]
n the openhab-config cannot configure wifi settings.

![IMG_20200115_075346](https://user-images.githubusercontent.com/42836064/72443754-15a28b80-37af-11ea-8cad-3cc5eba730d8.jpg)

**Comment by mstormi** [comment]
Does the error still occur with current openHABian? (have it update itself on start !) ?

If no, please close.

**Comment by mstormi** [comment]
got no feedback

**Comment by dariov** [comment]
> Does the error still occur with current openHABian? (have it update itself on start !) ?
> 
> If no, please close.

I have this same issue ....
I installed and updated via LAN and
- dpkg-query --showformat='${Version}' --show openhab2
returns 2.5.3-1

I then tried to activate wifi, with that same error...

**Comment by MaartenGoris** [comment]
Hi,

I was't able to check but i was able to solve this by configuring the setting file trough the terminal.

**Comment by dariov** [comment]
> Hi,
> 
> I was't able to check but i was able to solve this by configuring the setting file trough the terminal.

Thanks Marteen,
I tried to patch openhiab.config with Wifi data (SID, pwd) with no result....

How did you fix that via terminal?

**Comment by MaartenGoris** [comment]
Did you set the country ?
I believe WiFi is disabled is this is not set.

wifi_country="BE"

 for me BE for belgium...

**Comment by dariov** [comment]
Yes I did, just rechecked now....
mine is "IT"...  no way

**Comment by dariov** [comment]
Ok I FIXED the issue in this way (restarting from zero...):
1. dump image "openhabian-pi-raspbian-201908050414-gitca0976f-crc6a66b5a1.img.xz" to SD card
2. boot raspberry4 with NO LAN cable in
3. the installation fails, but you have openhab login prompt in the console
4. login openhabiam
5. edit /boot/opehabiam.config (I did it through sudo vi) adding wifi data: SID, pwd and country code
6. sudo shutdown -r now

The installation starts normally via Wifi

**Comment by mstormi** [comment]
Currently the wifi_setup() routine checks for Pi models and Pi4 is not among them,.
I guess that'll work once #829 is merged.

**Comment by dariov** [comment]
Guess there is a need to split 2 cases:
1. you DO NOT have a wired connection.... and you are then forced to start via wifi 
In this case you must provide to openhabian wifi info before starting the boot.
Checking some docs, I found this https://www.openhab.org/docs/installation/openhabian.html#wi-fi-based-setup-notes .... and i guess it's the correct method to be followed

2. you want to SWITCH to wireless after a openhabian LAN configuration....
In this case I guess the https://github.com/openhab/openhabian/pull/829 can correct the issue...

@mstormi i'm not the one opening the original issue, just stumbled upon the same problem

**Comment by mstormi** [comment]
> 
> 
> Guess there is a need to split 2 cases:
> 
>     1. you DO NOT have a wired connection.... and you are then forced to start via wifi
>        In this case you must provide to openhabian wifi info before starting the boot.
>        Checking some docs, I found this https://www.openhab.org/docs/installation/openhabian.html#wi-fi-based-setup-notes .... and i guess it's the correct method to be followed

Exactly, that's how it has always been (with any HW) with automated WiFi on boot.

> @mstormi i'm not the one opening the original issue, just stumbled upon the same problem

I know, my comment was targeting the OP
