### ISSUE TITLE
Errors while running openhabian-config

### ISSUE THREAD

**Issue by nwootton** [openhab/openhabian#789]
``` sudo openhabian-config``` 

Causes errors to be reported on the command line relating to both locale and a bash file.
![Openning error](https://user-images.githubusercontent.com/7591978/72836836-4853f480-3c85-11ea-806c-9dd3897754c6.png)
Neither logging out or reboot of device stops the issue. 

Once openhabian-config is running, accessing menu items often results in an error message.

![Screenshot 2020-01-21 at 19 47 45](https://user-images.githubusercontent.com/7591978/72837779-f7450000-3c86-11ea-8f00-107e71a80610.png)

Also able to replicate issue #788 

OpenHAB/OpenHABian functions as normal as far as I can tell.
OpenHAB 2.5.1-2 running on RPi3 B with wired network

**Comment by mstormi** [comment]
Do those error still occur with current openHABian? (have it update itself on start) ?

If yes, please describe every menu items/actions that you tried and that result in this msg.
If no, please close.

**Comment by nwootton** [comment]
TBH I've skipped using openhabian 2.5 via an image on a RPi as it kept dying on a weekly basis. 
Now I use an Intel NUC running ubuntu server and OpenHABian installed manually via the script. This allows me to use apt to manage the updates.

If I use openhabian-config it has been error free so far.

**Comment by mstormi** [comment]
Ok, now as this doesn't give us the information we would need to find the error cause in openHABian and you have a working setup, I'll close this.
