### ISSUE TITLE
Add a menu item to openhabian-config to change workgroup name

### ISSUE THREAD

**Issue by ddt3** [openhab/openhabian#802]
All my systems are in another workgroup because of that openhabian shares do not show up automatically, of course I can change that in samba.conf but would be nice if this is part of config.

**Comment by ThomDietrich** [comment]
Never ever did I change the working group setting on any device in the last 20 years. Are you sure this is needed to access shares through `\\openhabianpi` ?

**Comment by ddt3** [comment]
It is not needed to access them but when browsing from another workgroup these to do not show up automatically. Although it appears in Linux  this is not the case.... think you can cancel this one
