### ISSUE TITLE
OpenHABian REQUIRES an Internet connection

### ISSUE THREAD

**Issue by bwosborne2** [openhab/openhabian#803]
Although the installation documentation tells how to set up a Wi-Fi connection, no where does it say openHABian requires an Internet connection to install and operate (since addons package is not easily available).

See https://community.openhab.org/t/solved-installation-hangs-on-raspi-4-due-to-missing-ntp-connection/93459

**Comment by mstormi** [comment]
That's right for the time being.
A docs rework is in the making that will list prerequisites, an internet connection being among.

**Comment by bwosborne2** [comment]
The Linux installation has this statement about the addons package.

If you plan on disconnecting your machine from the internet, then you will want to also install the add-ons package.

Does that mean those people cannot use OpenHABian? I thought that was recommended for new users where possible.

**Comment by bwosborne2** [comment]
Requiring an Internet connection violates the stated openHAB vision [here]([url](https://www.openhab.org/about/who-we-are.htmlurl)).

> everything works nicely within the intranet and does not even require an Internet connection. We therefore also like to call it the "Intranet of Things".

**Comment by mstormi** [comment]
No it does not.
As replied on the forum already, this is nit-picking and wrong
(let alone that a "vision" by itself is an _ultimate_ goal you aim to but never fully reach)
