### ISSUE TITLE
Installing Java 64bit results in 32bit Version in 64bit path.

### ISSUE THREAD

**Issue by udo1toni** [openhab/openhabian#804]
Using openHABian in a debian buster 64bit VM (amd64).

After installing openHABian via official git command, Choosing 60 Manual/fresh setup and Zulu 64 bit version (instead of 32 bit), this results in installation of Zulu 32bit, but in the path `/opt/jdk/zulu8.42.0.21-ca-jdk8.0.232-linux_i686/`

**Comment by mstormi** [comment]
Duplicate of #729

**Comment by udo1toni** [comment]
Oh, did not find this. So I'll close this one.
