### ISSUE TITLE
rpi 4 wifi problem

### ISSUE THREAD

**Issue by tomadjk** [openhab/openhabian#806]
hallo, i have a problem mit wifi                                                         │
                      │ There was an error or interruption during the execution  │
                      │ of:                                                      │
                      │   "30 | System Settings"                                 │
                      │                                                          │
                      │ Please try again. Open a Ticket if the error persists:   │
                      │ https://github.com/openhab/openhabian/issues

**Comment by mstormi** [comment]
I know you were told to do that here but please turn to the forum for support.
Read https://community.openhab.org/t/how-to-file-an-issue/68464 and continue as told there.
Github is only when you have clearly identified the reason for a problem to be located _inside_ openHABian, and you would be expected to also supply the details we need to reproduce it.
(yes we need to remove that hint you saw)
