### ISSUE TITLE
Manual Setup instructions create /opt/openhabian/openhabian instead of /opt/openhabian

### ISSUE THREAD

**Issue by jtmoderate876** [openhab/openhabian#81]
I am following the "Manual Setup" instructions on my raspberry pi zero.

I ran into "directory does not exist" - cleaned up as if starting from scratch but this time making an adjustment to this line:
sudo git -C /opt/openhabian clone https://github.com/openhab/openhabian.git

Removing the first "/openhabian" to be:
sudo git -C /opt clone https://github.com/openhab/openhabian.git

**Comment by ThomDietrich** [comment]
Ah! Wrote that one command out of memory.
The even better solution is
```
sudo git clone https://github.com/openhab/openhabian.git /opt/openhabian
```
