### ISSUE TITLE
unattended install failing

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#821]
See https://community.openhab.org/t/openhabian-initial-setup-exiting-with-an-error-gpg-no-valid-openpgp-data-found/95780/3

Possibly related to #780 as it seems to have begun after that was merged but frankly I don't understand why.

**Comment by holgerfriedrich** [comment]
@mstormi Just a guess, system time not yet set properly yet, cert check fails? but why should it have worked before?

**Comment by mstormi** [comment]
Possible, someone proposed --no-cert-check as a fix.
But then why that gpg error message? Hoping for someone to add a -x so we get to see the command to fail

**Comment by mstormi** [comment]
Possibly it has been failing earlier, producing an empty but existing key file (and it was a "bug" that install continued nevertheless) ?
We use that pipe method I changed to in #780 in several locations, but we don't terminate install elsewhere when it fails.
I removed that "terminating" from the code, see #822. As an exception to the review rules, I ill merge that asap myself without waiting for review as unattended install is broken anyway and several people to complain.

**Comment by mstormi** [comment]
Ok so seems #822 fixed this. Reports are there's still log output that key download still does not work but now that we do no longer exit on failures, installation proceeds and _succeeds_.
I still don't understand why #780 broke it since unit testing (= manual execution of ...apt-keys) still is fine on my dev box (prod, too).  I've opened #824 to track.
Maybe we find out when automated builds works.

**Comment by mstormi** [comment]
Now some installs fail to download the openhab package in the next step to access the repo in
https://github.com/openhab/openhabian/blob/master/functions/openhab.bash#L60
That may or may not be "right" at this stage (internet access missing?)

**Comment by mstormi** [comment]
According to forum posts. said to fail on openhab2 pkg install when unattended but succeeds when installing manually
Created #833 to get debug output

**Comment by mstormi** [comment]
Actually the reason to fail was the `cond_redirect` in https://github.com/openhab/openhabian/blob/master/functions/openhab.bash#L48 that was introduced by #780 and removed again by #835.
`cond_redirect cmd_A | cmd_B` actually redirects the output of `cmd_A `and passes empty input to `cmd_B`, causing that to fail.
