### ISSUE TITLE
Offline install

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#825]
Is openHABian install supposed to finish even when Internet access isn't available ?

At least a number of users expect it to. I myself, frankly, I don't know. @ThomDietrich ?
We have a number of reported install fails at
https://github.com/openhab/openhabian/blob/master/functions/openhab.bash#L60

While not fully analyzed yet, it all boils down to the introductory question.
If yes, we would also need to test install runs under this condition.
If yes, we would need to identify the basicmost packages we need to get openHABian+openHAB running and include them with the image:
That would at least be needed_packages() - probably only python - PLUS Java PLUS openHAB packages (current release).

**Comment by holgerfriedrich** [comment]
@mstormi This would be a completely differnt approach compared to what we do now.
Currently, we have only sporadic releases of the base image and connect to the internet to upgrade the base system as well as openhabian and openhab. Latest is greatest approach. Following an offline approach for installation would require - at least from my point of view - regular releases of the base image including all updates up to that time. Jenkins/Travis could do this, but.... Considering the effort, I would vote against this. Let us deliver what we have and focus on stability. Developer community is too small for this.

Running openhabian-config without network is something different, at least for the part which changes some settings. Some people decide not to connect the home server to the internet and want it this way. So maybe the start of the script could skip the upgrade if not connected to the internet. Though, not sure how helpful this is at all. Nearly all functions are to install additional features, which is impossible withhout adding everything to the base image. I would suggest not to add error handling to the functions, maybe just a disclaimer/reminder when openhabian-config is started without internet connection.

**Comment by mstormi** [comment]
It's really meant as an question in the first place. _Was_ it supposed to work like that ?

**Comment by mstormi** [comment]
I'd like to move this forward. Aiming for an offline install capable image.

Components we would need to validate / enable caching or other pre-storage method for
(cast "in order of appearance"):

FireMotD
Java see #869 
openHAB2 stable release
vimrc, nanorc
Samba (is there a version included with Raspbian already ?)
Frontail

**Comment by holgerfriedrich** [comment]
Really serious about this?

From my point of view this would require executing the first-boot script before shipping the image.
Otherwise we will end up with two different types of installations with different sets of installed packages.

**Comment by mstormi** [comment]
Granted I have not analyzed what this would mean in detail but yes I'm serious about this because

> This could help in attracting users (or more precisely, to not lose them on first contact) because install fails.

My basic idea is to split the current install routines of each of those packages into download and install functions and to only run the downloads as part of an image build, storing download on the filesystem. No need to run the full first-boot I hope.
At installation time we will then download() again, checking for latest files on the Internet.
If that's unavailable we'll use the files from disk.

Let's carefully sort this out. No need to hurry.

**Comment by mstormi** [comment]
I created an access list on my router to block the openhabian box from accessing Internet, then
I called `openhabian-config unattended` on CLI and watched where it started to hang.

We need to browse/check those routines we call in openhabian-set.bash

- [ ] frontail install hangs in "npm install" if server unreachable
- [ ] does preload/include default Java (Zulu 8) with image work ?
- [ ] what happens in zram_setup() ?
- [ ] does the current code do harm if to openHABian repo itself fails?

**Comment by holgerfriedrich** [comment]
> What about the promised hook from [#950 (comment)](https://github.com/openhab/openhabian/pull/950#issuecomment-642290136) for all those packages we need to have available on offline installs ?

Can you already see what packages (including dependencies) are missing in the Rapberry Pi OS lite image? We need a proper way of installing them - I was thinking about a local apt repo.... If it is just a few, I would just install them in the beginning of the install from a cache folder....

**Comment by mstormi** [comment]
Would need to lookup each time. Does not do harm to list and eventually install again, does it ?
git libattr1-dev gcc

And you need to call the fetch routines for zram and java
