### ISSUE TITLE
add syntax highlighting for mcedit

### ISSUE THREAD

**Issue by CWempe** [openhab/openhabian#83]
I updated my syntax hiliighting files for mcedit from 2013 and created a repo.

https://github.com/CWempe/openhab-mcedit

Feel free to use, integrate it and improve if necessary. :)

btw: openhab community is down atm, so i created this issue instead of posting to the thread.

**Comment by mstormi** [comment]
You're welcome to create a PR at any time. Will close this issue though as it's 3yrs without any news.
