### ISSUE TITLE
Use of GitHub Actions in tests

### ISSUE THREAD

**Issue by ecdye** [openhab/openhabian#832]
Should we consider extending our testing procedures to include a GitHub Actions workflow?

**Comment by holgerfriedrich** [comment]
Worth a look, as we could also automate the image creation....

**Comment by holgerfriedrich** [comment]
I played a bit with this feature, and even managed to build our release image for the PI using actions...
https://github.com/holgerfriedrich/openhabian/tree/pr-actions
https://github.com/holgerfriedrich/openhabian/actions/runs/83309994

Not sure if I like this, though. Feels we are duplicating travis CI builds.

**Comment by ecdye** [comment]
Yes, but also the more tests the better. I think it really just depends on how much cost it adds to the workflow. 

If we end up using it for automating releases I think it could be worth it. I'm also interested to hear others thoughts on this.

**Comment by ecdye** [comment]
Also in the last statement of goals made by the Maintainers team one of the points was 
> "Focus of rapid deployment to ensure robust and tested software in opposite to create ready made images with cherrypicked artifacts."

Using GitHub action to create artifacts would certainly help accomplish that.

**Comment by ecdye** [comment]
This would also resolve #697

**Comment by holgerfriedrich** [comment]
Open questions for me:
* I don't want to do things twice, for me it is not clear what we should to with travis and what we should do here.
* Using the build action for the image works on my repository and will create an artifact of ~300MB. For me it is not clear how we deal with storage space and get rid of older artifacts, AFAIK github policy is to expire all artifacts after 90 day.
