### ISSUE TITLE
Release 1.0 not working for me

### ISSUE THREAD

**Issue by cribskip** [openhab/openhabian#84]
Hi,

today I gave openHABbianpi a try on my trustworthy PI2 which served me ages with openhab 1.8 and raspbian.

So I downloaded the image, dd'ed it to a known-to-work SD and booted. Network went up, ping works. Network showed some activity but ssh was not possible. I waited 10 minutes. Nothing.

Thinking the img is corrupt, I gave it another try. Downloaded again, sha'ed the download, same result. Anyway, flashed again. Same result. Then I powered off by unplugging and started again. This time, it doesn't even power up the ethernet jack :-(

Can someone verify this result on PI2? I'd really like to use openhabian :-)

Cheers,
Sascha

**Comment by mhoumark** [comment]
Hi,
Can verify that it runs just fine on PI2. 
The initial process was a bit slow, i think it took about 30-40 minutes to get it up and running.

**Comment by ThomDietrich** [comment]
> I waited 10 minutes. Nothing.

Did you read documentation? http://docs.openhab.org/installation/openhabian.html

![grafik](https://cloud.githubusercontent.com/assets/2870104/22270019/21fe61a2-e28e-11e6-9f55-7a5c58039d3a.png)
