### ISSUE TITLE
Errors in unattended install

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#840]
various errors seen in Travis deployments, see e.g.
https://travis-ci.com/github/mstormi/openhabian/jobs/350591314#L984
https://travis-ci.com/github/mstormi/openhabian/jobs/350591314#L1579

This may be a rc.local compatibility related problem rather than with Samba or other app that gets installed

**Comment by mstormi** [comment]
This may be a rc.local compatibility problem rather than Samba related

**Comment by holgerfriedrich** [comment]
rc.local compat error = first-boot script fails with exit code >0, misleading

**Comment by mstormi** [comment]
@holgerfriedrich I thought these errors were related to the rc.local stuff but they're still there
(I updated the links in post #1 with a recent master build).

Any idea ?

**Comment by mstormi** [comment]
@ecdye fyi
Both errors seem to be related to the fact that invoke-rc.d uses runlevels and those are not available inside Docker so it's probably a Travis-only problem but still I'd like to fix that.
Need to experiment some, tried to inject a 'runlevel' binary but my first attempt failed
https://travis-ci.com/github/mstormi/openhabian/jobs/351215031#L330

**Comment by ecdye** [comment]
Hmm, I'm no expert in Docker. But my guess is that there may not be a lot we can do until docker makes them available in their containers. I'll look into it.
