### ISSUE TITLE
State supported HW and OS 

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#846]
Clearly state in README what's supported and what's not.

We should also (technically) deny to install memory intensive extensions such as ZRAM or Grafana on boxes to have less than 1GB (e.g. RPi1, RPi0).

see #730 for a proposal
see https://github.com/orgs/openhab/teams/openhabian-maintainers/discussions/10

We would also need to state the OS we support see #621, #623 for OS

**Comment by ecdye** [comment]
@mstormi the link given for the discussion page returns as a link not found by GitHub. Is it possible it is a collaborator only link?

**Comment by mstormi** [comment]
yes

**Comment by ecdye** [comment]
Ok, that makes more sense.
