### ISSUE TITLE
Update test.bash and documentation

### ISSUE THREAD

**Issue by holgerfriedrich** [openhab/openhabian#856]
Test.bash is outdated.

* In #683 Dockerfile has been renamed. We need to update testing related scripts
and CONTRIBUTING.md, README.md `docker build -f Dockerfile.openhabian-x86 ...` *OR* decide  to rename Dockerfile.openhabian-x86 to Dockerfile (affects .travis.yml)
* Shellcheck test is incomplete (build.bash is not shellchecked, see .travis.yml for reference)
* Feature request: add calling bats test w/o Docker
* Add something about test.bash to documentation

**Comment by mstormi** [comment]
@holgerfriedrich mind to finally review ?
It's simple and still affecting users.

**Comment by mstormi** [comment]
Did you try build.bash after #684 meanwhile ?
Latest *is* shellchecked BTW.

**Comment by holgerfriedrich** [comment]
@mstormi I think you got me wrong, test.bash does not do it, so pre-commit testing might overlook it

**Comment by mstormi** [comment]
from .travis.yml: build.bash *is* shellchecked
      - shellcheck -x -s bash openhabian-setup.sh functions/*.bash build-image/*.bash build.bash && echo "shellcheck - OK"

**Comment by mstormi** [comment]
btw does building an image work ? Would like to provide a new one to contain the 02/2020 update from raspberry.org plus our pre-fetched java.

**Comment by holgerfriedrich** [comment]
@mstormi it should. I started using the image 1.6 milestone to collect what is essential from my point of view.

**Comment by mstormi** [comment]
haeh?
Won't wait for 1.6, that would be in time for bullseye upgrade.

**Comment by holgerfriedrich** [comment]
For me 1.6 is just next image milestone. I did remove "bullseye" from title.... bullseye is years away from now

**Comment by mstormi** [comment]
Well usually we only ever released images together with debian upgrades so I was thinking to call the next 1.5.1 then 1.6 would be for bullseye.
Then again, the Java upgrade also is pretty substantial. We can discuss for sure. Or roll dices ;-)

**Comment by mstormi** [comment]
@ecdye did your recent update on test.bash affect or fix this ?

**Comment by ecdye** [comment]
It should have, yes (once #938 is merged).
