### ISSUE TITLE
Setting timezone fails for new installations

### ISSUE THREAD

**Issue by holgerfriedrich** [openhab/openhabian#862]
`openHABian] Setting timezone based on
IP geolocation... FAILED`

Further investigation: tzupdate fails due to some Python issue.

`openhabian@openhab:~$ tzupdate
Traceback (most recent call last):
  File "/usr/local/bin/tzupdate", line 6, in <module>
    from tzupdate import main
  File "/usr/local/lib/python2.7/dist-packages/tzupdate.py", li
ne 69
    ) from None
         ^
SyntaxError: invalid syntax`

We need to check if installing tzupdate via pip is still a good solution.

**Comment by mstormi** [comment]
right, it's to fail very often
but try python3/pip3 first

**Comment by holgerfriedrich** [comment]
AFAIR, I did not want to introduce py3, as the base system includes only py2 until now....

**Comment by mstormi** [comment]
yes but meanwhile it's in now anyway, call it with python3 so give it a try
