### ISSUE TITLE
UARTs/HATs/Bluetooth on RPi

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#863]
UPDATE: skip to [here](#issuecomment-711073456)

Do serial cards (incl. HATs), options 35/1,3 still work for Pi4 ?
Bluetooth? WiFi ?

See:
https://www.raspberrypi.org/forums/viewtopic.php?t=246324
https://github.com/raspberrypi/firmware/blob/master/boot/overlays/README
https://www.raspberrypi.org/forums/viewtopic.php?t=244827

**Comment by mstormi** [comment]
help wanted for what exactly left to be done ?

**Comment by holgerfriedrich** [comment]
Someone who is into bluetooth and at best also uses a Pi HAT which need serial:
- RPi4 BT: clarify overlay pi3-miniuart-bt still applies (for me it seems it does not make sense on a RPi4 unless you set the CPU frequency scaling statically).
- RPI4 BT: clarify if you still need to do something about the BT when you want to use a HAT 
- RPI4 BT: maybe use the proper BT overlay to disable it (which might differ a bit from just breaking the functionality by using pi3-miniuart-bt with a variable frequency scaling)
- RPI4 BT: Which support libraries should be installed by our installer?

Someone who is willing to play with the WiFi functionality:
- RPi4: Check if we have a proper way of disabling and enabling WiFi. Check if the interfaces are gone after reboot. See what Rfkill does. 
- Investigate if we should turn off WiFi by default on wired installs.
...

**Comment by mstormi** [comment]
Ok, so that's beyond the scope of #861, right?
Can we finally merge that ? I removed the link to this issue here so that it does not get auto-closed on merge.

**Comment by ecdye** [comment]
I can't test anything with HAT's as I don't personally use any however I can test some other things.

These two links should help clarify what is happening with regards to `pi3-miniuart-bt` and how it relates to the serial ports (basically the same procedures as in the pi3 at least that's my understanding). 

https://www.raspberrypi.org/documentation/configuration/uart.md
https://www.raspberrypi.org/forums/viewtopic.php?t=246324#p1504155

**Comment by mstormi** [comment]
I have a RPi3 with a HAT (to use the UART) so I could disable BT and see if the HAT still works.
But I would not know what/how to test BT, let alone I hate to use that protocol for Home Automation purposes so I'm not euphoric to offer that anyway.

**Comment by mstormi** [comment]
btw @holgerfriedrich what does the "good first issue" label actually _precisely_ mean ?

**Comment by holgerfriedrich** [comment]
@mstormi this was introduced by github to mark issues as a good start for new contributors

**Comment by mstormi** [comment]
With #861 merged, please redo the list what's left. WiFi disablement you can test, BT alone, too.
BT+serial HAT IMHO never worked and still does not.

**Comment by mstormi** [comment]
I have a RPi4 and a ZWave HAT available now but I have no idea of BT.
Can you propose concrete basic BT tests ?
dtoverlay-miniuart-bt is disabled (absent from /boot/config.txt) by default on new RaspiOS
(on older ones probably as well)

**Comment by mstormi** [comment]
I can see no real TODO left here. Please reopen and explain if you disagree.

**Comment by mstormi** [comment]
See https://community.openhab.org/t/raspberry-pi4-and-razberry-zwave/79880/7

Can we get that incorporated ?

**Comment by mstormi** [comment]
I have BT *and* a ZigBee USB stick working on my RPi4 with current openHABian using the menu to move BT to miniuart so I think the current functionality is fine.
