### ISSUE TITLE
nginx install broken

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#866]
There's at least 2 problems on nginx install:
Seems a number of directories fail to get created on nginx package install. Need to take care of that in our install routine.
My problem with nginx failing to start started with a missing logdir after works on ZRAM (where /var/log/nginx was deleted).
This was on buster w/ ZRAM to "own" `/var/log` (incl. "`nginx`" below), but there is nowhere in neither the nginx package nor nginx_setup() that creates the `/var/log/nginx` directory for logfiles as they're used in the config that is generated - causing nginx to fail starting up.
Things went south when I advised some user with a broken nginx config to delete /etc/nginx and to reinstall. Seems even /etc/nginx is not created on install, let alone the stuff below.

Second, the config generated with default inputs (default user openhab, HTTPS yes, blank domain) is bad, the first section is partly still commented, see below. @BClark09 could you take a look please ?
```
#################################
# openHABian NGINX Confiuration #
#################################

## Redirection
#server {
#   listen                          80;
   server_name                     localhost;
   return 301                      https://$server_name$request_uri;
#}


```

**Comment by BClark09** [comment]
> @BClark09 could you take a look please ?

I can't test, but a glance it's because [Lines 6 and 10 in the default nginx.conf](https://github.com/openhab/openhabian/blob/master/includes/nginx.conf#L6,L10) need `#REDIR` keywords.

**Comment by mstormi** [comment]
Yes that worked. Whyever that was missing.
Could you please review #867 ?
