### ISSUE TITLE
openHabian fresh install on pi 4 fails with `[openHABian] Script '/boot/first-boot.bash' failed.`

### ISSUE THREAD

**Issue by f2calv** [openhab/openhabian#872]
I'm not a Linux guru so I followed [the beginner instructions](https://www.openhab.org/docs/installation/openhabian.html#raspberry-pi-prepackaged-sd-card-image) and prepared a 32GB sim with [openhabian-pi-raspbian-201908050414-gitca0976f-crc6a66b5a1.img.xz](https://github.com/openhab/openhabian/releases/download/v1.5/openhabian-pi-raspbian-201908050414-gitca0976f-crc6a66b5a1.img.xz) and just at the 'completion' stage the install fails with;
`[openHABian] Script '/boot/first-boot.bash' failed.`

![image](https://user-images.githubusercontent.com/16097639/81411096-2900aa80-9142-11ea-84d1-e9371d8eac25.png)

The dashboard on 8080 doesn't load at all, the log web server is running but devoid of any log data.
Any suggestions?

**Comment by mstormi** [comment]
Check out the [debug guide](https://github.com/openhab/openhabian/blob/master/docs/openhabian-DEBUG.md) and turn to the community forum for help, please.

**Comment by f2calv** [comment]
Thanks for the debug guide link.
However I did a 3rd fresh install the same as before and... there was no error, weird.

@mstormi for what it's worth the [debug guide](https://github.com/openhab/openhabian/blob/master/docs/openhabian-DEBUG.md) is not linked from the [openHabian page](https://www.openhab.org/docs/installation/openhabian.html#faq-and-troubleshooting), that might help others...
