### ISSUE TITLE
needed_packages() - python-pip fails on Ubuntu 20.04 

### ISSUE THREAD

**Issue by mateusz-dykszak** [openhab/openhabian#875]
Ubuntu 20.04 does not support python 2 by default. So installing need packages through Configuration Tool fails because python-pip package does not exist.

python-pip can still be installed but is not as easy as "apt install ..."
It's described for example here: https://linuxize.com/post/how-to-install-pip-on-ubuntu-20.04/

BTW: Is python 2 really needed by OpenHabian?

**Comment by mateusz-dykszak** [comment]
And another BTW: It's my first post in this community so "Hello everyone".

**Comment by holgerfriedrich** [comment]
I think last call to pip was removed from the code in #864. I'll give it a try to remove the installation and see what happens with the CI build.
