### ISSUE TITLE
correct references to Azul java versions

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#879]
We download and use the "Community" version for both, x86 and ARM.

Code and docs however sometimes still refer to these as "Enterprise" and "Embedded" version s, respectively.

Need to remove/correct these referrals (java-jre.bash, docs/openhabian.md)

**Comment by ecdye** [comment]
No, the ARM builds are actually embedded. Azul has made embedded builds available like all of their community builds.

**Comment by mstormi** [comment]
Err, ok. The current download link contains a "community"part.
And it's not about the code but about licensing, isn't it? Those distributed as 'community' fall under 'community' licensing (=no restrictions, essentially), or am I mistaken ?

**Comment by ecdye** [comment]
I'm actually not sure about that part. I would need to look into it, I mostly just re-implemented the download using the API. You can prove that it is actually a embedded build by looking at the links that it returns for downloads from the API it is pulling from the embedded folder.

**Comment by ecdye** [comment]
> And it's not about the code but about licensing, isn't it?

I think that Embedded builds are mostly just optimized for SoC's like the RPi. I could be wrong though. I'll look into it more tomorrow morning.

**Comment by mstormi** [comment]
Yes, Embedded essentially is ARM and Enterprise is x86.
I believe Community isn't a real build but just the same Embedded/Enterprise packages but with a different license attached.

**Comment by ecdye** [comment]
So I got in contact with Azul and their rep is going to get me in touch with the product manager to see if we can work something out.

**Comment by ecdye** [comment]
So, Azul's PM team is now aware of the issue and is looking into a fix. I'll update when I hear anything else.

**Comment by mstormi** [comment]
FYI
```
[12:51:58] openhabian@openhabianpi:~$ java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (Zulu8.40.0.178-CA-linux_aarch32hf) (build 1.8.0_222-b178)
OpenJDK Client VM (Zulu8.40.0.178-CA-linux_aarch32hf) (build 25.222-b178, mixed mode, Evaluation)
```
                                                                                                                                                   ^^^^^

**Comment by ecdye** [comment]
It has always said that.

**Comment by mstormi** [comment]
any feedback from Azul ? Do we need to do anything ?

**Comment by ecdye** [comment]
Nothing from them as of yet.

**Comment by mstormi** [comment]
so assuming we will not get any answer any more, would we need to change anything or rather close this issue?

**Comment by ecdye** [comment]
I don't believe anything needs to be done. I will keep an eye out but I doubt that I will get a response at this point. Hopefully it will be fixed some day.

**Comment by mstormi** [comment]
Will close for the time being, reopen it if there's news.

**Comment by ecdye** [comment]
I just looked today, no email but a fix for the API has been issued and I will include it in #990.

**Comment by holgerfriedrich** [comment]
> I just looked today, no email but a fix for the API has been issued and I will include it in #990.

Hi Ethan, can you pls do it on a separate PR? #990 should be more or less rewrite and free of side effects on actual features.
