### ISSUE TITLE
Manual Setup on fresh ubuntu 16.04 minimal server

### ISSUE THREAD

**Issue by bits4life** [openhab/openhabian#88]
Like requested in the docs I would like to report some errors when using openhabian-config on a freshly installed ubuntu 16.04 minimal server from mini.iso. 
First the good things 
- Java 8 install from the menu worked perfect.
-1wire install worked

Some issues I  encountered
Basic setup fails with _E: Package 'oracle-java8-jdk' has no installation candidate_ (Just wonder why java is also installed in this menu step ?)
Homegear setup also fails, seems it's not known in the default repository  
_Package homegear is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'homegear' has no installation _candidate_
E: Unable to locate package homegear-homematicbidcos
E: Unable to locate package homegear-homematicwired
FAILED_

Manual install worked with these commands

apt install apt-transport-https
wget https://homegear.eu/packages/Release.key && apt-key add Release.key && rm Release.key
echo 'deb https://homegear.eu/packages/Ubuntu/ xenial/' >> /etc/apt/sources.list.d/homegear.list
apt update
apt install homegear

Samba file share install blinks, could not even read the error message

I didn't test the other options.
Hope my feedback helps.
Thanks for the great work already

**Comment by ThomDietrich** [comment]
Hey @bits4life, 
thanks for your report! As it happens I was going to work on a few extended platform support features this evening. I'll make sure to take all your seen errors into consideration. I'll keep you posted!

Best Regards, Thomas

**Comment by ThomDietrich** [comment]
Hello @bits4life, All of this should be covered by the new version released today. Would be great if you could give this another try! Please open a new issue or reopen this one with everything you  experience failing or missing! ;) Thanks

https://github.com/openhab/openhabian/releases/tag/v1.1
