### ISSUE TITLE
Evaluate alternatives to Raspbian

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#886]
Interesting that HASS uses Balena ResinOS and that it does not show a boot issue that Raspbian does: https://community.openhab.org/t/openhabian-setup-fails-due-to-ipv6/98717/3

I'd guess they're mostly the same under the hood but let's dig into the differences to see if it's worth switching or at least to take advantage of the work done in there.
ResinOS is also Docker optimized (prime reason for HASS to use it I guess) but thing is it's also portable and available for many SBCs beyond RPis so we might get those supported as a side effect, too.
Last not least we already use the Balena images in our Travis testing, I believe they're the same.

**Comment by mstormi** [comment]
Well it's apparently a little different than I thought in the first place.
Balena provides docker images (which we also use for testing) but no plain images beyond a basic balenaOS per SBC. But that in turn only seems to work for their service (and ours would have to be available as a docker image to make use of that).

**Comment by ecdye** [comment]
Food for thought: Are we targeting Docker or end-user HW as our primary concern?

**Comment by mstormi** [comment]
> Food for thought: Are we targeting Docker or end-user HW as our primary concern?

Plain SBC hardware only, no Docker ever.

**Comment by mstormi** [comment]
Raspi Foundation coming up with their own 64bit OS:
https://www.raspberrypi.org/forums/viewtopic.php?f=117&t=275370

**Comment by ecdye** [comment]
Well once it leaves beta we will need to add support for it.

**Comment by mstormi** [comment]
Yeah. Would need a docker image in the first place for our CI pipeline.

**Comment by ecdye** [comment]
Yep

**Comment by mstormi** [comment]
With Balena working different, Raspi OS now out, Ubuntu support to come and no potential alternatives I could see for the time being, I think it's reasonable to stop searching for now.
Feel free to reopen if there's significant news that could become gamechangers.
