### ISSUE TITLE
disable IPv6 ?

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#887]
See https://community.openhab.org/t/openhabian-setup-fails-due-to-ipv6/98717 and elsewhere on the net for people to have a problem with Raspbian to use IPv6 (only) on boot.

See https://raspberrypi.stackexchange.com/questions/23884/force-ipv4-address for a potential way to change/fix that in openHABian.

Opinions ?

**Comment by ecdye** [comment]
I certainly think that we should prefer IPv4 especially in Java as I personally have issues every time with Homekit and Java IPv6. Overall, I don't think we need to disable it but rather find a way to make IPv4 preferred unless the user overrides.

**Comment by mstormi** [comment]
Agree. But how ?? You can prefer ipv4 over v6 in specific cases only [like apt](#228) but not globally.
Open for any suggestion to do the magic.

**Comment by ecdye** [comment]
I'm not sure. I'll look into it a bit.

**Comment by gitMiguel** [comment]
I disagree. Network problems/misconfigurations should not be resolved on this level. If the network isn't properly up, the installation should fail and user be informed. 

I'm curious, @ecdye, what IPv6 problems have you encountered?

**Comment by mstormi** [comment]
> I disagree. Network problems/misconfigurations should not be resolved on this level.

Well. We aim to build an image that installing works in as many environments as possible.
So what can we do if openHABian gets an IPv6 that isn't correctly setup or does not work to download packages? Force a fallback to use an IPv4 which should work.
As I said I'm open for any suggestion to do that magic but for now I don't know how to do it except to disable IPv6, BTW see #888. This implements an _option_ to disable IPv6 that the user can manually set. It's off by default i.e. IPv6 and IPv4 active.
We cannot/won't fix the environment or tell the user how to do that.

**Comment by gitMiguel** [comment]
Maybe I'm trying to say that the underlying OS should handle the fallback and we shouldn't need a switch to disable something. We could use some "getaddrinfo magic" to help the OS to prefer IPv4. See this [stackexchange.com](https://unix.stackexchange.com/a/13263) topic.

I know that all kinds of environments should be supported but if it's not properly configured?

**Comment by ecdye** [comment]
Homekit does not work with IPv6 and that is quite annoying. Then my personal experience has been that with the devices on my network that don't support IPv6, connecting to my RPi has been very difficult when it has defaulted to IPv6.

**Comment by gitMiguel** [comment]
I expected something more specific that just "it doesn't work".

**Comment by ecdye** [comment]
In my experience,(this could be just my own personal network setup) IPv4 devices connecting to IPv6 devices tends to fail. Additionally, the average layperson is usually running a IPv4 network at their house. 

I think that this is an issue better solved at the Debian options level meaning it should be addressed by the kernel with an option to prefer IPv4 when possible. Therefore the solution that @mstormi has proposed seems perfectly valid considering the lack of any option to in the kernel to prefer IPv4. If the user desires IPv6 then it is easy to find and enable. As @mstormi has stated many time First Impressions are everything and if a installation fails because of network issues we are likely to loose a potential user before they even get a functioning install working.

**Comment by mstormi** [comment]
> See this [stackexchange.com](https://unix.stackexchange.com/a/13263) topic.

That's a good hint, thanks. (@ecdye check it out on your box)
So would we want to modify `/etc/gai.conf` by default in openHABian ?

**Comment by gitMiguel** [comment]
> IPv4 devices connecting to IPv6 devices tends to fail

@ecdye, sorry but I don't understand what you mean here. These are two different protocols that devices either support or then they don't.

Disabling IPv6 to debug network problems is fine but as a default option? No.

**Comment by ecdye** [comment]
Devices connecting to the network using the IPv4 protocol can't connect to devices connecting to my network on the IPv6 protocol. But like I said it may just be my network that is causing the issue.
