### ISSUE TITLE
Builds to fail

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#896]
See https://travis-ci.com/github/openhab/openhabian/jobs/337265122#L1242 for x86 and
      https://travis-ci.com/github/openhab/openhabian/jobs/337265128#L1264 for arm32

After installation, openhab2 fails to start because of java, that's why builds ultimately fail

Possibly it downloads some wrong or bad package ?

Pinging @ecdye  @holgerfriedrich

**Comment by holgerfriedrich** [comment]
did you see the failing install of libc packages just before zulu install starts?

**Comment by mstormi** [comment]
Good catch.  That's apparently the relevant difference If I compare sub-builds from the same run
https://travis-ci.com/github/openhab/openhabian/jobs/337265126#L1225
https://travis-ci.com/github/openhab/openhabian/jobs/337265128#L1260

Although they have different line numbers so *something else* is different.

Might be due to differences in base images.
Test building within the "testbuild" branch to find out ....

**Comment by mstormi** [comment]
I changed to .... -build images just in those Dockerfiles to fail, resulting in a good build:
https://travis-ci.com/github/openhab/openhabian/builds/167098275

So I believe the following is what we see:
* the libc packages are required to run java, but they are missing in _some_ of the repos
  (those to fail, x86 and arm64, these are)
* using the ...-build images comes with them preinstalled so builds succeed

I'm not yet sure what to make of it.
We can ignore the .9 case (as it's a theoretical-only 64bit ARM) and "fix" that with the proper image.
But we cannot ignore the x86 build to fail.
Then again, libc should be part of ANY install, shouldn't it ? Wonder why this special install is there at all - @openhab/openhabian-maintainers any hint ?

**Comment by mstormi** [comment]
>     * the libc packages are required to run java, but they are missing in _some_ of the repos

which are exactly those same repos as the BT packages in #902 are missing in - coincidence ?

**Comment by ecdye** [comment]
Oddly enough, it seems to have corrected itself. Perhaps it was just a bug with the upstream.

**Comment by mstormi** [comment]
Yeah, odd.
I just received a bunch of Travis mails to report various _old_ builds both to fail and to succeed.
My [latest one ](https://travis-ci.com/github/mstormi/openhabian/builds/167681799)still fails but just for a specific architecture.

**Comment by mstormi** [comment]
>  @holgerfriedrich holgerfriedrich added upstream optional component labels 4 hours ago 

At 5am ? Wow.
But what's optional about this here?

**Comment by mstormi** [comment]
As you might know commits to repos with existing PRs actually create *two* builds for the same code. With my most recent attempt, one of them failed, the other one worked:

https://travis-ci.com/github/openhab/openhabian/jobs/338738959
https://travis-ci.com/github/mstormi/openhabian/jobs/338738947

**Comment by ecdye** [comment]
Perhaps its because Travis's arm support is still in beta and being worked on?

**Comment by mstormi** [comment]
We will not find out. ARM may be alpha but we also had many builds to fail on x86 so I don't think that is the main reason.

**Comment by mstormi** [comment]
Closing as it's working now without that we fixed anything about it.
Reasons for build failures remain unknown, though.

Reopen if you encounter anything like this again.
