### ISSUE TITLE
Installation of InfluxDB and Grafana (still) fails to complete 

### ISSUE THREAD

**Issue by AliFarmer001** [openhab/openhabian#906]
Hi,

Doing a vanilla install of openHab on a RPi 4 from the openHABian installer.

Completed the installation then went into openhabian-config and selected the install optional components and install InfluxDB & Grafana.

The installation ran through then failed - see below :

All went well to start with...
Setting up libqt5sensors5:armhf (5.11.3-2) ...
Setting up grafana-data (2.6.0+dfsg-3) ...
Setting up libwacom2:armhf (0.32-1) ...
Setting up grafana (2.6.0+dfsg-3+b1) ...
Created symlink /etc/systemd/system/grafana-server.service → /lib/systemd/system/grafana.service.
Created symlink /etc/systemd/system/multi-user.target.wants/grafana.service → /lib/systemd/system/grafana.service.
Setting up libsm6:armhf (2:1.2.3-1) ...
Setting up libdrm-amdgpu1:armhf (2.4.100-4+rpi1~bpo10+1) ...
Setting up gtk-update-icon-cache (3.24.5-1+rpt2) ...
Setting up libdrm-nouveau2:armhf (2.4.100-4+rpi1~bpo10+1) ...
Setting up dconf-gsettings-backend:armhf (0.30.1-2) ...
Setting up libgbm1:armhf (19.3.2-1~bpo10+1~rpt1) ...
Setting up libdrm-radeon1:armhf (2.4.100-4+rpi1~bpo10+1) ...
Setting up libqt5positioning5:armhf (5.11.3+dfsg-2) ...
Setting up libpango-1.0-0:armhf (1.42.4-8~deb10u1) ...
Setting up libgl1-mesa-dri:armhf (19.3.2-1~bpo10+1~rpt1) ...
Setting up libqmi-glib5:armhf (1.22.0-1.2) ...
Setting up libqt5network5:armhf (5.11.3+dfsg1-1+rpi1+deb10u3) ...
Setting up libinput-bin (1.12.6-2) ...
Setting up libegl-mesa0:armhf (19.3.2-1~bpo10+1~rpt1) ...
Setting up libqt5qml5:armhf (5.11.3-4) ...
Setting up libnotify4:armhf (0.7.7-4) ...
Setting up libqt5webchannel5:armhf (5.11.3-2) ...
Setting up libwacom-bin (0.32-1) ...
Setting up libegl1:armhf (1.3.0-7~bpo10+1) ...
Setting up libpangoft2-1.0-0:armhf (1.42.4-8~deb10u1) ...
Setting up libgtk-3-common (3.24.5-1+rpt2) ...
Setting up libpangocairo-1.0-0:armhf (1.42.4-8~deb10u1) ...
Setting up gsettings-desktop-schemas (3.28.1-1) ...
Setting up libinput10:armhf (1.12.6-2) ...
Setting up libglx-mesa0:armhf (19.3.2-1~bpo10+1~rpt1) ...
Setting up libglx0:armhf (1.3.0-7~bpo10+1) ...
Setting up libqt5gui5:armhf (5.11.3+dfsg1-1+rpi1+deb10u3) ...
Setting up libqmi-proxy (1.22.0-1.2) ...
Setting up libqt5widgets5:armhf (5.11.3+dfsg1-1+rpi1+deb10u3) ...
Setting up librsvg2-2:armhf (2.44.10-2.1+rpi1) ...
Setting up libqt5printsupport5:armhf (5.11.3+dfsg1-1+rpi1+deb10u3) ...
Setting up libgl1:armhf (1.3.0-7~bpo10+1) ...
Setting up librsvg2-common:armhf (2.44.10-2.1+rpi1) ...
Setting up modemmanager (1.10.0-1) ...
Created symlink /etc/systemd/system/dbus-org.freedesktop.ModemManager1.service → /lib/systemd/system/ModemManager.service.
Created symlink /etc/systemd/system/multi-user.target.wants/ModemManager.service → /lib/systemd/system/ModemManager.service.
Setting up libqt5quick5:armhf (5.11.3-4) ...
Setting up libqt5svg5:armhf (5.11.3-2) ...
Setting up libqt5webkit5:armhf (5.212.0~alpha2-21+rpi1) ...
Setting up adwaita-icon-theme (3.30.1-1) ...
update-alternatives: using /usr/share/icons/Adwaita/cursor.theme to provide /usr/share/icons/default/index.theme (x-cursor-theme) in auto mode
Setting up phantomjs (2.1.1+dfsg-2) ...
Processing triggers for libc-bin (2.28-10+rpi1) ...
Processing triggers for systemd (241-7~deb10u4+rpi1) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for dbus (1.12.16-1) ...
Processing triggers for fontconfig (2.13.1-2) ...
Processing triggers for mime-support (3.62) ...
Processing triggers for libglib2.0-0:armhf (2.58.3-2+deb10u2) ...
Setting up glib-networking:armhf (2.58.0-2) ...
Setting up libsoup2.4-1:armhf (2.64.2-2) ...
Setting up geoclue-2.0 (2.5.2-1) ...
geoclue.service is a disabled or a static unit, not starting it.
Setting up libsoup-gnome2.4-1:armhf (2.64.2-2) ...
Setting up librest-0.7-0:armhf (0.8.1-1) ...
Setting up libgtk-3-0:armhf (3.24.5-1+rpt2) ...
Setting up libgtk-3-bin (3.24.5-1+rpt2) ...
Setting up qt5-gtk-platformtheme:armhf (5.11.3+dfsg1-1+rpi1+deb10u3) ...
Setting up notification-daemon (3.20.0-4) ...
Processing triggers for libgdk-pixbuf2.0-0:armhf (2.38.1+dfsg-1) ...
Processing triggers for libc-bin (2.28-10+rpi1) ...
Processing triggers for dbus (1.12.16-1) ...
Updating FireMotD available updates count ...

$ systemctl daemon-reload

$ systemctl enable grafana-server.service
Failed to enable unit: Too many levels of symbolic links

$ systemctl start grafana-server.service
OK
Resetting Grafana admin password...
$ grafana-cli admin reset-admin-password admin
/opt/openhabian/functions/helpers.bash: line 24: grafana-cli: command not found
FAILED Connection Grafana to InfluxDB...{"id":1,"message":"Datasource added"}Adding openHAB dashboard tile for Grafana... 2020-05-21_17:56:32_BST [openHABian] Adding an openHAB dashboard tile for 'grafana'... OK
Adding install InfluxDB with database configuration to openHAB
$ touch /etc/openhab2/services/influxdb.cfg

**Comment by ecdye** [comment]
Is this a RPi4 1gb? If so, then you should not be trying to use Grafana as it is a known memory hog and will likely fail.

**Comment by holgerfriedrich** [comment]
Hi @AliFarmer001,
grafana-cli is not found, this has been reported by few people on the grafana bugtracker. 

To help yo we need more information:

Can you please provide more information about your OS environment?

Can you try to locate it (my guess: `/usr/sbin/grafana-cli`)? Can you call it directly?

Please provide the content of `$PATH` variable.

Thank you.

**Comment by axlerose** [comment]
Hi

I've a similar issue but the problem is that openhabian didn't install grafana because it didn't find it on ppa repo so to perform a correct installation i've to add the grafana ppa before the installation, perform an apt-update and next it was installed and make the same problem of the admin password reset.

i add an other detail, after the admin password reset issue , i try to access to grafana by the standard admin password( admin admin) and change the password, wen i try the command 

`$ grafana-cli admin reset-admin-password admin`

it works

**Comment by ocramleznem** [comment]
Just jumping in here. The same happened to me right now on my new installation on a Raspberry Pi 4 with 4GB of memory. I got texactly the same message as @AliFarmer001 

According to @holgerfriedrich my $PATH looks like this:
```
[21:54:20] openhabian@openhab:~$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
```

and trying the direct call ends in:
```
[22:00:16] openhabian@openhab:~$ /usr/sbin/grafana-cli
-bash: /usr/sbin/grafana-cli: No such file or directory
```

**Comment by holgerfriedrich** [comment]
@ocramleznem @AliFarmer001 
root cause seems that updating the package lists after adding the grafana repository was accidentially removed, resulting in a very old version of grafana being installed from raspbian repo. PR is already submitted, so it should be available soon.
You may need to remove the old version manually `sudo apt remove grafana grafana-data` before proceeding (on my test install the upgrade to 7.0 failed).

**Comment by ocramleznem** [comment]
Thanks for your quick fix @holgerfriedrich!

I removed `grafana` and `grafana-data` and restarted the installation by going through and updated `openhabian-config`.
