### ISSUE TITLE
FireMotD 

### ISSUE THREAD

**Issue by axlerose** [openhab/openhabian#908]
Hi

After the FireMotD installation on Ubuntu Server 20.04 i've notice that the used RAM percentage didn't work, and i've the error:

```
/usr/local/bin/FireMotD: line 149: ((: 10#3 > 10#UNKNOWN: value too great for base (error token is "10#UNKNOWN")
/usr/local/bin/FireMotD: line 153: ((: 10#3 < 10#UNKNOWN: value too great for base (error token is "10#UNKNOWN")
(standard_in) 1: syntax error
(standard_in) 1: syntax error
(standard_in) 1: syntax error

```

**Comment by mstormi** [comment]
Well FireMotD is just a tool we bundle with openHABian. We install the latest version.
If that doesn't work on latest Ubuntu please open an issue with the developers over at
https://github.com/OutsideIT/FireMotD/

**Comment by multimartin** [comment]
@axlerose - did you get this fixed ? I get the same error - with the same config...

**Comment by openPhiL** [comment]
let me add this link here: https://github.com/OutsideIT/FireMotD/issues/154
