### ISSUE TITLE
WiFi gone after HW upgrade RPi3 -> RPi4

### ISSUE THREAD

**Issue by holgerfriedrich** [openhab/openhabian#912]
Tried to upgrade my hardware from RPi3b to RPi4 _without a fresh install_.
WiFi was enabled and working before, LAN not connected.
System booted fine, but WiFi function was gone. Reboot did not help.

Since this is a typical upgrade situation, we should have a look if we can improve the behaviour.

**Comment by ecdye** [comment]
Did you have WiFi enabled on your RPi3b when you upgraded? If so, perhaps it just is a simple fix of checking the HW on boot and adjusting the settings for network if needed.

**Comment by mstormi** [comment]
While I disagree formally (you SHOULD install from scratch and migrate config only), you are correct that it would be a good idea if that worked at least in the most common setup (boot from SD). We should not aim to support external SSD, net boot or the like. 

Could you please review #861 so I can merge that asap, it has some changes to affect WiFi.

Is there anything about Wifi in your /boot/config.txt ?

**Comment by mstormi** [comment]
Just booted from a virgin image and noticed some startup messages about a
"Load/Save RF Kill Switch Status" right below "Starting Blueetooth service".
Probably worth to check out.

**Comment by mstormi** [comment]
Not sure if that's related but see https://github.com/openhab/openhabian/pull/931#issuecomment-641815609

**Comment by mstormi** [comment]
Holger can you retry with your new image and eventually use menu option 33 ?

**Comment by mstormi** [comment]
@holgerfriedrich ping

**Comment by mstormi** [comment]
Just upgraded the 'enclosure' of my SD card from a PRi2 to a RPi4 and WiFi is still there (with the default config in /etc/network/interfaces).

Let's close this one. You can reopen should you hit that again.
