### ISSUE TITLE
several BATS tests to fail

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#917]
Merging #918 made BATS output appear in 2nd Travis test stage
That revealed several BATS tests to fail once you're willing to look at them :-|
See https://travis-ci.com/github/mstormi/openhabian/jobs/339942816

We need to fix:
- [x] destructive-install_zulu8-64bit
- [x] destructive-install_zulu11-64bit
- [x] destructive-install_zulu8-32bit
- [x] destructive-install_zulu11-32bit
- [x] destructive-install_adopt
- [x] installation-Frontail_is_running

- [x] destructive-homegear_install

- [x] destructive-influxDB_install 
- [x] destructive-grafana_install (pinging @holgerfriedrich)

- [ ] java tests - decide if we want to test openhab startup with this java version, then CI test needs to install openhab as well (and stop in teardown)

**Comment by ecdye** [comment]
Its failing the Java installation test because it does not have a full openHABian image properly set up and booted. Basically that means that it fails because Java is not installed

**Comment by mstormi** [comment]
Why would it need a full image ? The BATS test is supposed to be a unit test, i.e. it should install Java, start it up for a smallish test (java -version or the like) and that's it ...

**Comment by holgerfriedrich** [comment]
@mstormi not easy to debug without any output.
How do we proceed here? Log file as artifact possible? Use $output?

**Comment by mstormi** [comment]
Huh? Did you see #918 ?
Rebase on master and you should see your output ...

**Comment by ecdye** [comment]
It doesn't because it is running in the bare docker image and the openHABian install is what installs Java, not docker.

**Comment by mstormi** [comment]
@ecdye I don't understand at all what you mean. Please quote lines if you refer to some earlier post,
and don't jump between issues, that's highly confusing.

As replied [here](https://github.com/openhab/openhabian/pull/869#discussion_r430685837), the BATS test itself is to install Java.

**Comment by holgerfriedrich** [comment]
> 
> 
> Huh? Didn't you see #918 ?
> Rebase on master and you should see your output ...

what I see in my tests is just 
```
not ok 1 destructive-influxDB_install
# (in test file ./functions/influxdb+grafana.bats, line 12)
#   `[ "$status" -eq 0 ]' failed with status 3
```

I can track this down to the command run before, but I do not see what happened.
E.g. grafana install failed with exit code. Good to know. But hard to debug.

**Comment by mstormi** [comment]
I see. Line 12 is systemctl ...
That eventually fails because systemctl doesn't work in docker.
That's why I install a replacement systemctl.py, but maybe not in the Dockerfile used here ?

**Comment by holgerfriedrich** [comment]
Bad luck, not that easy. This was also my first thought, and in #915 I have already added an additional check to see if the connection to the DB works.... (in addition to the systemctl).
But looking at the grafana error message, already the install fails....

**Comment by mstormi** [comment]
Almost there: https://travis-ci.com/github/openhab/openhabian/jobs/340632926
Come on Holger, just one more to go ...

**Comment by holgerfriedrich** [comment]
lets see what Grafana install comes up with today.... installation fail :-/

**Comment by ecdye** [comment]
Any idea why on the tests I've merged into my Adopt branch and the testbuild branch keep timing out on the Bats tests.

**Comment by mstormi** [comment]
> Any idea why on the tests I've merged into my Adopt branch and the testbuild branch keep timing out on the Bats tests?

Dunno what you mean, when I looked most were fine.
Give a link....
Is it reproducible? At least try restarting them

**Comment by ecdye** [comment]
I can't restart them it wont let me. Here is a link: https://travis-ci.com/github/openhab/openhabian/jobs/340618525#L540

**Comment by mstormi** [comment]
Button in upper right corner? I was able to restart yours.

**Comment by ecdye** [comment]
I think it is because I do not have write access to the repository. But it still is timing out after the Zram tests now any idea why?

**Comment by holgerfriedrich** [comment]
@mstormi did those bats tests ever work properly in the CI setup we have now? Many of them try to restart openHAO, relay on java and frontail to be availabe.... all the stuff which is currently not installed in the VM for the bats tests!
So my feeling is that we need to run them after a full installation.

**Comment by mstormi** [comment]
I don't know if they ever worked but none of the BATS unit tests should be built to require any prerequisites. Ethan has already fixed most of the java tests. The frontail install test should _install_ frontail and check after that if it's working.

**Comment by holgerfriedrich** [comment]
Frontail: agreed.
The tests do not directly restart openhab, but for example java installation procedure will halt and restart openhab.
```
$ unzip /tmp/openhabian.FqHy9/crypto.zip -d /tmp/openhabian.FqHy9 
Archive:  /tmp/openhabian.FqHy9/crypto.zip
   creating: /tmp/openhabian.FqHy9/ZuluJCEPolicies/
  inflating: /tmp/openhabian.FqHy9/ZuluJCEPolicies/LICENSE  
  inflating: /tmp/openhabian.FqHy9/ZuluJCEPolicies/README.txt  
  inflating: /tmp/openhabian.FqHy9/ZuluJCEPolicies/DISCLAIMER  
  inflating: /tmp/openhabian.FqHy9/ZuluJCEPolicies/local_policy.jar  
  inflating: /tmp/openhabian.FqHy9/ZuluJCEPolicies/US_export_policy.jar  
OK
$ systemctl start openhab2.service 
ERROR:systemctl:Unit openhab2.service could not be found.
not ok 3 destructive-update_java-64bit_tar
# (in test file ./functions/java-jre.bats, line 30)
#   `[ "$status" -eq 0 ]' failed
# Zulu 32-bit Java installation is being (test-)installed...
# Zulu 32-bit Java installation successful.
$ systemctl stop openhab2.service 
ERROR:systemctl:Unit openhab2.service could not be found.
/opt/openhabian/./functions/java-jre.bash: line 46: timestamp: command not found
 [openHABian] Installing Java Zulu 32-Bit OpenJDK... 
```
https://travis-ci.com/github/openhab/openhabian/jobs/340822671

**Comment by mstormi** [comment]
They shouldn't be doing that. But as I said I think @ecdye has reworked them already.

**Comment by ecdye** [comment]
They do and they should but it was really just an issue of return values. The restarting of openHAB does not effect the outcome when installing as it will just fail and continue. It is needed so that when installing new Java versions we don't do it while the current VM is still running. The tests are all fixed for Java as @mstormi said. 

The one issue I still have is that for some reason after the changes I made the install now hangs indefinitely and Travis terminates it as can be seen here: https://travis-ci.com/github/openhab/openhabian/jobs/340618525#L544

**Comment by mstormi** [comment]
> It is needed so that when installing new Java versions we don't do it while the current VM is still running.

Ok. So the original intention of unit tests was to have a _separate_ test routine to only contain what's needed but it's actually an even better test to make use of the real installation routine.
Maybe you can change the code there to do something like `systemctl -q is-active openhab2 && systemctl stop openhab2`

>The one issue I still have is that for some reason after the changes I made the install now hangs indefinitely.
I restarted your job and it happens again.
I'm 70% sure it's a Travis issue as the last BATS test (zram) to run has been unchanged in a while.
I did however change the call to use docker run -i (run in foreground) instead of -d (detach to background) so it *might* have to do with file descriptors or the like. Then again other builds like this https://travis-ci.com/github/openhab/openhabian/jobs/340707107 are fine.
 Just an idea remove --name param, maybe experiment with </dev/null or google up on BATS and fds.

**Comment by mstormi** [comment]
> The one issue I still have is that for some reason after the changes I made the install now hangs indefinitely

What's happening if you call the command on your box?
(beware it screws up install so make sure to run it on a test box only !)

**Comment by ecdye** [comment]
I think I figured it out, there are a bunch of missing semicolons in functions/packages.bash in if statements (primarily involving whiptail). We will see if that fixes it.

**Comment by holgerfriedrich** [comment]
...and I finally managed to get the grafana install working... but same error at the end of the test run.... 
Which files did you change? I will prepare a small PR which does not conflict.

**Comment by ecdye** [comment]
I just opened #930 to fix it.

**Comment by mstormi** [comment]
* Originally I think BATS tests were executed on a machine AFTER the unattended installation finished.
That's why stuff now missing (lsb-release etc) _was_ installed at that late stage.
Frontail test wants the service to run which in turn is difficult to get to run only using the standard routine that's also used in unattended install.
In cases like that it's ok to reduce the original test to something simple such as call to just output the program version, that's how I changed the Frontail test now.

* I saw the following in homegear bats test (running _after_ influx), so I think the influx test install has messed that up:
`E: Malformed entry 1 in list file /etc/apt/sources.list.d/influxdb.list (Component)`
This is how it looked like:
`deb https://repos.influxdata.com/debian  stable`

**Comment by holgerfriedrich** [comment]
see also #927, it fixes influx, grafana, frontail.
workarounds for homegear in place.

open point: will we rework the java tests to actually test if openhab can run with the installed java? Currently this is commented out in java-jre.bats, since during the destructive tests we do not have openhab installed.

**Comment by mstormi** [comment]
Using openhab to run the Java unit test is not needed and would create hard to resolve dependencies.
It's tested anyway later on in integration/deployment tests.

So can we close this issue ?

**Comment by holgerfriedrich** [comment]
Java/Openhab interaction to be checked in integration tests.
All other checks are ok.
