### ISSUE TITLE
Raspberry Pi 4 + openhabian 1.5 + Razberry2 HAT + Backup not working

### ISSUE THREAD

**Issue by mdivus** [openhab/openhabian#922]
I have a clean Pi 4 setup with a clean openhabian v1.5. Also a green Razberry2 modul HAT. 
Setting up software works fine, but I can't get my Razberry connected with my restored openhab backup from my previous Pi3 setup.
Tells me /dev/ttyAMA0 does not exist, although it is listed on the console.
Also Option 3 in openhabian-config -> Serial Port -> *Enabling JVM* is missing in my system

Any help is highly appreciated.

**Comment by mstormi** [comment]
Github is not for user support. Please post your question on the community forum.

PS: try removing `-Dgnu.io.rxtx.SerialPorts=.....` from `EXTRA_JAVA_OPTS `in /etc/default/openhab2
Option 3 changed that but it is harmful so we removed the option.
