### ISSUE TITLE
Ubuntu support

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#926]
Ubuntu clearly is the most popular Linux flavour for x86.
As we don't provide images for x86, I think we need to support it to gain a broader openHABian user base. As most packages are identical to Debian I wouldn't think it'll be much effort.

- [x]  Code cleanup to remove or update Ubuntu references
- [x]  Travis test case with proper Docker Ubuntu image (focal and bionic LTS releases) => #975
- [x]  docs update

**Comment by mstormi** [comment]
see also https://community.openhab.org/t/java-on-non-openhabian/99904/8
@ecdye: curl missing for Java at least on Odroid/bionic (not sure if that's plain bionic but I would think with regards to non-kernel stuff like curl it will be), so should be an easy catch

**Comment by ecdye** [comment]
They got the install to work and if they had installed the basic needed packages using menu 11 it would have worked perfectly.

**Comment by mstormi** [comment]
Yeah. Actually I wonder whether `openhabian-config unattended` would have worked and if we should put that into the docs for any non-image install.

**Comment by holgerfriedrich** [comment]
Will you close #621?

**Comment by mstormi** [comment]
I think so yes

**Comment by mstormi** [comment]
@ecdye @holgerfriedrich

Is there anything left we need to declare Ubuntu supported ?
