### ISSUE TITLE
Grafana on RPi 0/1

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#928]
Yes yes I know I shouldn't raise this.

Point however is that *if* someone decided (against all odds and recommendations) to run it, we should at least install the correct binary.
RPi0/1 are ARMv6l and the standard repo version does not work there.
=> test for hwarch in Grafana install routine and eventually download the hwarch specific version from https://grafana.com/grafana/download?platform=arm

**Comment by holgerfriedrich** [comment]
...and think of what database to use. Grafana and Infux on a Pi0/1 does not make much sense to me.

**Comment by mstormi** [comment]
Of course. However you can use simple DBs like rrd4j or an InfluxDB or MariaDB to run elsewhere such as on a NAS of yours.
So no excuses not to fix this (I thought it's simple so you can do it while you work on it anyway but if you disagree ok).
Now having said that reminds me of #482. I recently closed that as "does not make sense" but on second thought it _does_ make sense so I reopened.

**Comment by ecdye** [comment]
@mstormi I would expect you of all people to ignore this possibility as being completely unnecessary. However, I do see your point.

**Comment by Norde** [comment]
I fully understand the choice of not supporting an architecture that will give a bad user experience.

However, I noticed that the actual InfluxDB + Grafana script does not allow you to continue (and therefore to launch the time saving automatic configuration) even if Influx and Grafana are already installed.
Yet, this was the case in older versions.

Would it be possible to split the difference and authorize again to continue the automatic configuration under Rpi0 (if Influx and Grafana are already installed)?

**Comment by mstormi** [comment]
No we're not willing to spend any more work on that.
If you get it to work (scripted) we're happy to take any PR to include it in openHABian.

**Comment by Norde** [comment]
To be sure of the philosophy of this project on this subject (before scripting anything):

Would an update of the script allowing the installation of the ARMv6 package be accepted? (or possibly a separate script)

Or would only a modification allowing automatic configuration on an existing installation (Influx+Grafana on Rpi0) be welcome?

**Comment by mstormi** [comment]
Philosophy is ta have openHABian provide new installations only. Upgrades should be handled through the apt package mechanism (which is executed for ALL isntalled packages via option 02).
Then again if you can offer to migrate as well, we happily take this as well.
Mind the [CONTRIBUTING](https://github.com/openhab/openhabian/blob/master/CONTRIBUTING.md) standards.
