### ISSUE TITLE
Fix repo key downloads

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#936]
Several instances like
`cond_redirect wget -O - http://homegear.eu/packages/Release.key | apt-key add -`

can fail if repo file or repo are broken
should be rewritten like this
```
wget --no-check-certificate -qO "$RepoKey" 'https://bintray.com/user/downloadSubjectPublicKey?username=openhab'
cond_redirect apt-key add "$RepoKey"
rm -f "$RepoKey"
```

**Comment by ecdye** [comment]
This is part of what I would consider a bigger issue that involves rewriting most if not all of the functions for safer and more consistent execution and status reporting.

I am going to start re-writing many of the functions and will include this as part of the process.

**Comment by holgerfriedrich** [comment]
Consider using a helper function to implement this. mktmp could also be your friend.

**Comment by ecdye** [comment]
Yep.

**Comment by DjSni** [comment]
Hi,

it seems Bintray is deprecated. Openhab Update dont work.

`Bintray has been deprecated,
but never fear!
The JFrog Platform offers many solutions to distribute your software internally or externally. Read more on this page about JFrog Distribution, or new, exciting technologies like Federated Repositories and the world’s first Private Distribution Network.`
