### ISSUE TITLE
Rewrite of openHABian core functions

### ISSUE THREAD

**Issue by ecdye** [openhab/openhabian#937]
There are many places where the existing code is in need of a good tune up to make it safer in execution and to keep to a standard more consistently. 

This will take a while but I will open a PR and begin to rewrite the core of openHABian to have much safer execution and more clear outputs.

Related #936

**Comment by mstormi** [comment]
Another brick in this: Rewrite to use ${TEMP:/tmp} to honor $TEMP.
Just have the problem myself that I cannot install Java because /tmp is not large enough.

**Comment by ecdye** [comment]
where is $TEMP defined? Is it just an option for a user to export it so that we can use it for them?
Java should not be using tmp to install, can you point me to where it is?

**Comment by ecdye** [comment]
Also, do you want me to make one Behemoth PR and merge it all at once or would you like me to do it in smaller chunks to help make it more manageable.

**Comment by mstormi** [comment]
$TEMP is a generic env variable any user can set in his bash profile
https://github.com/openhab/openhabian/blob/master/functions/java-jre.bash#L239 and L368

I think having a set of PRs is easier to handle and validate. Make them groups of similar fixes.

**Comment by ecdye** [comment]
Sounds good. That is what I thought $TEMP was for.
