### ISSUE TITLE
Tellstick Binding fails

### ISSUE THREAD

**Issue by pigetto** [openhab/openhabian#94]
Cannot add Tellstick Add-on (1.9.0 or 2.0.0)

**openhab.log:**
2017-02-11 14:58:28.599 [ERROR] [l.discovery.TellstickBridgeDiscovery] - Could not load telldus core, please make sure Telldus is installed and correct 32/64 bit java. 
java.lang.UnsatisfiedLinkError: Unable to load library 'telldus-core': Native library (linux-arm/libtelldus-core.so) not found in resource path (/usr/share/openhab2/runtime/lib/boot/org.apache.karaf.diagnostic.boot-4.0.8.jar:/usr/share/openhab2/runtime/lib/boot/org.apache.karaf.jaas.boot-4.0.8.jar:/usr/share/openhab2/runtime/lib/boot/org.apache.karaf.main-4.0.8.jar:/usr/share/openhab2/runtime/lib/boot/org.osgi.core-6.0.0.jar)

**Comment by ThomDietrich** [comment]
Did you see https://github.com/openhab/openhabian/pull/56

**Comment by pigetto** [comment]
Oops, missed that one, sorry!
