### ISSUE TITLE
OpenJDK option

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#948]
OpenJDK is/will be part of Raspi OS images which are going to be the basis for our new image, too.
So it'll already be installed there. Some openHAB people even to use it today.

We should allow for activating it via openhabian-config menu.

**Comment by mstormi** [comment]
@ecdye saw this one ? Maybe a quick win as it's already installed ?

**Comment by ecdye** [comment]
I saw you opened it, I have not look much at the new RPi OS. I'll look into it some once I have the first set of rewrites complete (I am going to rewrite all of `packages.bash` and make that the first piece to test once it is merged and being validated I'll look at it but my guess is it will be pretty simple.

**Comment by mstormi** [comment]
No hurry. When rewriting, keep potential offline install in mind (is there packages we need for OH to work that are NOT already available as part of the image).

**Comment by ecdye** [comment]
Also do we want to keep the travis tests for the forcing of 64bit down to 32bit on unsupported platforms now that we know they work? My thought is to remove them to simplify the testing structure.

**Comment by mstormi** [comment]
yes remove it. Maybe some more cases we can slim down? Travis compile takes loooooong even parallelized because of so many parallel compiles.

**Comment by ecdye** [comment]
I'm toying with it, trying to find the best balance of adequate testing and reasonable time.

**Comment by mstormi** [comment]
@ecdye willing to take on this? I'd like to finalize the image see #946  and this should be in

**Comment by ecdye** [comment]
Sure, just to confirm, it is preinstalled in the lite image, correct?

**Comment by mstormi** [comment]
To check, I just installed a plain lite image and ... no it's missing.

So what do we do - omit, install ourselves or take the non-lite image ?
Is it as simple as to apt-get install ?

**Comment by ecdye** [comment]
I think it is just an apt install. I am not sure it is worth adding though because we already have to optimized alternatives using the same code-base and I would like to stick with the lite image to avoid extra bloating of the image.

**Comment by mstormi** [comment]
Yeah you're right. Our all assumption was it's in the image but it isn't even in the desktop one (just tried) unless they renamed it or did whatever strange stuff to it.

I also think it's not worth going for apt.

Will hence close this, you can reopen in case there's news or changes to our assumptions.
