### ISSUE TITLE
grafana fails after reboot

### ISSUE THREAD

**Issue by StMSchl** [openhab/openhabian#959]
Dear all,

I'm just trying to migrate from OH1 to OH2 ... one issue came up this moring.
System: Openhabian (stable) on Pi4 with zram

Symptom: grafana fails after restart:

Jun 11 11:11:25 ... systemd[1]: grafana-server.service: Main process exited, code=exited, status=1/FAILURE
syslog:Jun 11 11:11:25 ....systemd[1]: grafana-server.service: Failed with result 'exit-code'.
syslog:Jun 11 11:11:25 ... systemd[1]: grafana-server.service: Service RestartSec=100ms expired, scheduling restart.
syslog:Jun 11 11:11:25 ... systemd[1]: grafana-server.service: Scheduled restart job, restart counter is at 3.
syslog:Jun 11 11:11:25 ...  grafana-server[765]: Failed to start grafana. error: failed to create log directory "/var/log/grafana": mkdir /var/log/grafana: permission denied

I can fix this by creating the directories manually:

sudo mkdir -p -m 750 /var/log/grafana
sudo chown grafana:grafana /var/log/grafana
sudo systemctl start grafana-server

but it fails again after next reboot. Zram issue ??

Regards,
Stephan

**Comment by holgerfriedrich** [comment]
@mstormi can you please have a look at this?

**Comment by mstormi** [comment]
Stop Grafana, stop ZRAM, correct permissions then start again.
I'd think it's a leftover of bad earlier Grafana install routine that ran without ZRAM being on.

**Comment by StMSchl** [comment]
It did the trick:
* stopped zram (via openhabian-config)
* reboot > grafana failed
* added directory + permission fix
* reboot > grafana started
* restarted zram (openhabian-config)
* test reboot: everything fine !

@mstormi: thanks!

Stephan

**Comment by Diapolo** [comment]
@mstormi Wow that thread was hard to find as a newbie ;). I'm wondering why a current setup from openHABian master still has this unfixed?

**Comment by mstormi** [comment]
This is not the forum hence no "thread" meant for user support. Turn to the forum for that please.
And what do you mean? There was no fix needed in OH. The OP's problem was fixed by these instruction hence the issue closed.

**Comment by Diapolo** [comment]
Well I ran into the exact same issue for a new openHABian install based on the latest release image from this page. I'm currently doing a fresh install and will happily report back, if installing Influx and Grafana results in Grafana not working after a reboot...
