### ISSUE TITLE
Openhabian-config tool doesn't obtain public IP

### ISSUE THREAD

**Issue by E1i0** [openhab/openhabian#960]
When trying to set up a reverse proxy using https, and when the tool asks to fill in my domain, I fill in my duckdns.org domain (that is working fine). When the script checks if the domain IP is the same as my public IP, I get an error message. In the console logs, I see that "Obtaining public IP address..." returns a blanc value.
![image](https://user-images.githubusercontent.com/66377024/84388451-e6c10200-abf4-11ea-941b-3fb50384ba56.png)

This issue is also described on the opnhab forum: https://community.openhab.org/t/domain-does-not-resolve-to-public-ip/100444
Anyone know how I can fix this?
TIA

**Comment by mstormi** [comment]
No.
Set debugmode=maximum in /etc/openhabian.conf to see what it does, maybe that gets you a hint.

**Comment by E1i0** [comment]
> No.
> Set debugmode=maximum in /etc/openhabian.conf to see what it does, maybe that gets you a hint.

I did this, and now I can see where it goes wrong:
![image](https://user-images.githubusercontent.com/66377024/84397563-0d843600-abff-11ea-8198-59675a15842d.png)
The script tries to obtain the public IP address by using this command: "dig +short myip.opendns.com @resolver1.opendns.com", but that returns a blanc value, also when I try to execute the command in console. However, when I use this command, it returns my IP: 
![image](https://user-images.githubusercontent.com/66377024/84401219-50e0a380-ac03-11ea-96d0-1f1c18988dc4.png)
Can I edit the script with this command to make it work, and if yes, where can I find this script?
TIA

**Comment by mstormi** [comment]
/opt/openhabian/functions/packages.bash
Beware it gets overwritten when you update openhabian-config

**Comment by E1i0** [comment]
I managed to figure it out on my own, but still thanks!
I edited the line in the packages.bash file, adding the -4 as stated above, and the setup now continues with my domain.
Thanks for all the help, really appreciate it!
