### ISSUE TITLE
openhabian-config unattended to fail due to missing openhabian.conf

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#963]
/etc/openhabian.conf missing if openHABian installed as repo clone (without image)

**Comment by mstormi** [comment]
also installer-config.txt and potentially other files are missing
see https://community.openhab.org/t/cant-open-http-openhab-link/100395/47

**Comment by ecdye** [comment]
Also the current 1.5 image installs an older version of the openhabian.conf that does not contain all of the new options and `openhabian-config` does not update the current one with the new version.

**Comment by mstormi** [comment]
> the current 1.5 image installs an older version of the openhabian.conf

that will require a new image. As that's in the works, no need to take action here.

> openhabian-config does not update the current one with the new version.

how would that be supposed to work ? it may not overwrite it's own config file as it cannot know whether the changes in there are intentional

**Comment by mstormi** [comment]
Would it be a sufficient fix to simply tell users in the docs to create `/etc/openhabian.conf` as a copy of `/opt/openhabian/openhabian.conf.dist` ?

**Comment by mstormi** [comment]
Fixed by #964 ?

**Comment by ecdye** [comment]
Possibly, or if users have issues add a section in the debug guide outlining a fix.

**Comment by mstormi** [comment]
I've added that as code, too: #967
