### ISSUE TITLE
VPN / remote access

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#970]
Deploying openHAB/openHABian in any remote location incurs a need for (secure) remote access.

I would like a remote access server to become part of openHABian.
Any suggestions for a software framework or implementation ?
OpenVPN ?

See also https://github.com/orgs/openhab/teams/openhabian-maintainers/discussions/16 for related tasks.

**Comment by ramsonline** [comment]
How About [Wireguard](https://www.wireguard.com/) ? It seems to be the successor of OpenVPN.

**Comment by mstormi** [comment]
Seems there's no package available for Raspbian !?
There are "openvpn" packages, though.

**Comment by ramsonline** [comment]
They are not in the Raspberry OS repository yet, but there are usable versions in the Debian Repositories:
Here is a sample tutorial: https://engineerworkshop.com/blog/how-to-set-up-wireguard-on-a-raspberry-pi/

Wireguard would especially make sense since it has a lot less overhead and a very small codebase.

**Comment by mstormi** [comment]
Sounds reasonable. I've started an implementation in #1010.

Would you be willing to contribute ?

**Comment by mstormi** [comment]
I installed following that tutorial but my first attempt failed weith a "device wg0 not found."
This is on buster. Read somewhere it has to be bullseye ?
I don't see the wireguard-dkms module being loaded, it doesn't even exist in /lib/modules/...
Any idea ?

**Comment by mstormi** [comment]
Initial setup contributed in #1010 but this is WIP.

Currently wg-quick@wg0 service does not start (not even on reboot) because the systemd unit config file is missing ?

**Comment by mstormi** [comment]
please test
