### ISSUE TITLE
systemctl --wait unavailable

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#978]
@ecdye 
just noticed https://travis-ci.com/github/openhab/openhabian/jobs/350719621#L394

**Comment by ecdye** [comment]
Its because of our systemctl replacement in Docker. I'll look into it some more and see if we can use another option.

**Comment by holgerfriedrich** [comment]
This was just a test to see if we can use `systemctl --wait` in the tests.
If I call systemctl w/o wait, we need to figure out when the install actually finishes. I will roll back to calling first-boot.bash directly (which is called anyway by the service).
